### ISSUE TITLE
Thay đổi câu lệnh Replace

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1000]
admin/upload/functions.php 
tại function nv_filesListRefresh còn thấy sử dụng câu lệnh sql REPLACE
Cập nhật sớm để tương thích với các kiểu CSDL khác nhau

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/7a54618d45036a288b911728891115ebf379d698
