### ISSUE TITLE
Lỗi khi cài đặt mới

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1003]
[Notice(8): Trying to get property of non-object] [FILE: /install/index.php] [LINE: 427]
[Notice(8): Undefined index: site_home_module] [FILE: /includes/rewrite.php] [LINE: 35]
[User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'uploads/menu' for key 'name'] [FILE: /includes/class/db.class.php] [LINE: 123]
[Warning(2): preg_match(): Compilation failed: nothing to repeat at offset 0] [FILE: /includes/class/crypt.class.php] [LINE: 156]

**Comment by vuthao** [comment]
@truongemcom Vui lòng cung cấp thêm thông tin để chúng tôi có thể xây dựng môi trường thử nghiệm giống của bạn để kiểm tra
https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md

**Comment by truongemcom** [comment]
Phiên bản NukeViet	4.0.17 
Phiên bản PHP 5.5.11
Giao thức giữa máy chủ và PHP Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.11, apache2handler
Hệ điều hành máy chủ	WINDOWS NT
Phiên bản Database	mysql 5.6.16

**Comment by vuthao** [comment]
Hiện tại chúng tôi kiểm tra không thấy lỗi như bạn báo tại phiên bản NukeViet 4.0.18
