### ISSUE TITLE
Lỗi Warning

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1005]
[Warning(2): preg_replace(): Compilation failed: invalid range in character class at offset 7] [FILE: /includes/class/download.class.php] [LINE: 218]
[Notice(8): Undefined property: download::$disable_classes] [FILE: /includes/class/download.class.php] [LINE: 157]
[Warning(2): in_array() expects parameter 2 to be array, null given] [FILE: /includes/class/download.class.php] [LINE: 157]
[Warning(2): preg_replace(): Compilation failed: invalid range in character class at offset 7] [FILE: /includes/class/download.class.php] [LINE: 230]
[Warning(2): preg_replace(): Compilation failed: invalid range in character class at offset 7] [FILE: /includes/class/download.class.php] [LINE: 267]
[Warning(2): mkdir(): File exists] [FILE: /admin/extensions/upload.php] [LINE: 181]

**Comment by thehung** [comment]
Cảnh báo này xuất hiện khi nào vậy @truongemcom ?

**Comment by vuthao** [comment]
Bạn thử download lại file  includes/class/download.class.php  xem đã hết lỗi chưa.
