### ISSUE TITLE
Lỗi sử dụng tham số nv_redirect

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1006]
Tại trang login của module users có sử dụng tham số này.

VD http://domain/index.php?language=vi&nv=users&op=login&nv_redirect=L2luZGV4LnBocD9sYW5ndWFnZT12aSZhbXA7bnY9c3lzdGVtJmFtcDtvcD1vYmplY3RfY2hlY2tpbmc,

Đến đây, nếu người dùng chưa có tài khoản thì họ phải đăng ký, sau khi đăng ký xong hệ thống chuyển về lại trang main của users, mất luôn cái tham số nv_redirect, nên khi người dùng đăng nhập xong không về lại trang cũ.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/48e152b89e18776abc4f0fee605c63f5771e33f0

**Comment by hongoctrien** [comment]
Lỗi này vẫn còn đối với URL đăng ký anh ạ.

Ví dụ: http://nukeviet4.vn/index.php?nv=users&op=register&nv_redirect=L2luZGV4LnBocD9sYW5ndWFnZT12aSZhbXA7bnY9cmVjcnVpdG1lbnQmYW1wO29wPWpvYnByb3ZpZGVyLWNvbnRlbnQ,

Sau khi đăng ký xong => về trang đăng nhập (Về trang main của module users, nhưng chưa đăng nhập nên nó chuyển đến trang đăng nhập) => đăng nhập xong nhảy về thông tin tài khoản, lúc này thì tham số nv_redirect mất luôn chứ không còn để chuyển trang nữa.

**Comment by hongoctrien** [comment]
ak không lỗi, em nhầm xí.
