### ISSUE TITLE
Hỏi về thư mục tmp

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/nukeviet#1008]
trong thu mục tmp có mấy file bắt đầu bằng pclzip-5566a...... .gz. dung lượng khá lớn, xin hỏi nó là của modules hay của hệ thống ạ? làm tốn dung lượng host quá . Thanks
![2015-06-06_202414](https://cloud.githubusercontent.com/assets/10916826/8019778/3d1988f8-0c8a-11e5-8d48-d36a62ce59c9.png)

**Comment by vuthao** [comment]
Các vấn đề về thảo luận, bạn vui lòng đăng tại diễn đàn.
