### ISSUE TITLE
Lỗi trắng tinh khi click vô tìm kiếm

### ISSUE THREAD

**Issue by duongGitHub** [nukeviet/nukeviet#1009]
NV 4.0.17 lỗi trắng tinh khi click vô tìm kiếmt. Mình dùng:
Phiên bản NukeViet: 4.0.17
Môi trường thử Nghiệm: Localhost
Hệ điều hành: Win 7
Trình duyệt web: Chrome
Máy chủ web: VertrigoServ 231

**Comment by duongGitHub** [comment]
NV 4.0.17 bị lỗi tìm kiếm khi cài Module Photo Nukeviet 4x tại http://forum.nukeviet.vn/viewtopic.php?f=166&t=34935
Ai biết fix lỗi dùm. Thanks

**Comment by anhyeuviolet** [comment]
Vậy cái này ko phải do NV bạn ạ. Cần liên hệ người phát triển modules đó để sửa lỗi search.php
