### ISSUE TITLE
[Hỏi] Về cơ chế của modules comment với news.

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1010]
Xin chào.
Hiện mình có một modules dựa trên news, phần comment thay vì áp dụng chỉ cho bài chi tiết thì mình chuyển thành cho chuyên mục ( Category ).
Cái thú vị là nó comment và like rất ổn, nhưng còn tồn tại 02 vấn đề : 
01/ Khi click vào gửi comment, thông báo lỗi xuất hiện : "Lỗi trong quá trình xử lý dữ liệu hoặc dữ liệu không đầy đủ"

Tuy vậy F5 thì comment đã được lưu, có thể thích, không thích hay trả lời, xoá đều ok. Tất nhiên khi xoá thì cũng bị lỗi trên.
02/ Cấu trúc link trong phần quản lý comment là : 
http://localhost/417/admin/index.php?language=vi&nv=truyen&op=view&area=75&id=7

Tức là về cấu trúc, nó y chang như khi comment trong một bài viết con. Tuy vậy link này bị 404 khi click chứ ko chuyển hướng đến bài viết được như trong bài viết con.
Vậy liệu có cách nào để modules comment có thể tiện hơn trong việc đem đi nhiều func hay không ? Và cơ chế lưu comment thế nào, tạo URL trong quản lý comment ra sao ? 
Mong được giải đáp.

**Comment by vuthao** [comment]
Vấn đề này bạn vui lòng thảo luận tại diễn đàn nhé.
