### ISSUE TITLE
[Hỏi] về giao diện default

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/nukeviet#1011]
Cho em hỏi.

Sao bản này em cài lên localhost thì thấy giao diện default không co dãn trên màn hình được ?

**Comment by anhyeuviolet** [comment]
:D Bản này là bản nào bạn ?
Ít nhất thì đến 4.0.17 mình thấy theme vẫn tự co giãn tốt mà.

**Comment by trinhthinhhp** [comment]
@motcaiten hiện tại trên default có 3 tùy chọn ở phí dưới chân trang nhá bạn: máy tính, tùy biến và mobile.
- Máy tính: không cho co giãn
- tùy biến: cho co giãn
- mobile: co giãn trên mobile

**Comment by motcaiten** [comment]
@anhyeuviolet Bản mới nhất trên github.
@trinhthinhhp Vậy giờ khi khách vào website là phải chọn ạ. Giờ mình muoon nó mặc định là giao diện tùy biến không dùng mobile thì phải cấu hình thế nào ?

**Comment by trinhthinhhp** [comment]
@motcaiten khách hàng phải chọn. bạn muốn giao diện responsive mà ko dùng mobile thì bạn vào admin, click "cấu hình" chọn submenu "cấu hình site" , tìm đến "Giao diện mặc định cho mobile" tại đó bạn chọn "giao diện mặc định cho PC" và lưu là là dc, nhớ sau khi lưu lại phải vào dọn dẹp hệ thống nhé
