### ISSUE TITLE
Lỗi cảnh báo

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1013]
[Notice(8): Undefined index: nocatid] [FILE: /modules/news/blocks/global.block_tophits.php] [LINE: 59]
[Warning(2): in_array() expects parameter 2 to be array, null given] [FILE: /modules/news/blocks/global.block_tophits.php] [LINE: 59]
[Notice(8): Undefined index: title_length] [FILE: /themes/default/blocks/global.menu_footer.php] [LINE: 26]

**Comment by vuthao** [comment]
@truongemcom bạn kiểm tra dùm xem hiện tại còn lỗi này trên bản mới không nhé.
