### ISSUE TITLE
Module news: lỗi tại  block admin

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1015]
admin/index.php?nv=news&op=block&listid=
Danh sách bài viết được xuất hết ra + số vòng lặp weight quá lớn gây tràn bộ nhớ và trắng trang

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/e83a14a4a0d83408e24e069085a59d2467cfaff1
