### ISSUE TITLE
Hiển thị danh sách hình ảnh đã upload bên cạnh CKeditor

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1017]
Hiện tại trình upload của NKV có một hạn chế là khi đăng bài có nhiều hình (n hình) thì tương ứng với (n lần) đóng mở trình upload.
Do vậy: Nên thêm một khung hiển thị danh sách ảnh đã upload bên cạnh CKeditor muốn chèn hình nào chỉ việc bấm vào mà thôi.
Nếu tính năng này được thực hiện trong phiên bản tới thì mọi người đăng bài sẽ nhanh hơn, dễ quản lý hình ảnh, giảm tải cho máy.

Rất mong anh em phát triển NukeViệt quan tâm, xin chân thành cảm ơn!

**Comment by truongemcom** [comment]
Hiện tại NukeViệt upload ảnh theo thư mục tháng. Nếu chức năng này được thêm vào, hình ảnh upload trong 1 tháng sẽ rất nhiều do đó sẽ load chậm.
Vì vậy e góp ý là nên để chế độ upload ảnh theo ngày, khi đó thêm chức năng này mới được tốt như mong đợi.

**Comment by vuthao** [comment]
Chế độ upload ảnh theo ngày đã có sẵn trong cấu hình của module News
Ảnh upload của module được lưu trữ mặc định theo cấu trúc thư mục
