### ISSUE TITLE
Lỗi cảnh báo

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1018]
scandir(D:/web/htdocs/demo/modules/siteinfo/plugin/,D:/web/htdocs/demo/modules/siteinfo/plugin/): The system cannot find the path specified. (code: 3) in file /admin/index.php on line 184
Lỗi cảnh báo	Lỗi cảnh báo: Invalid argument supplied for foreach() in file /admin/index.php on line 185

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/59a1d1875941ee7729f5445b351b02fb6f1efbd7
