### ISSUE TITLE
Lỗi Warning

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1022]
[Warning(2): imagecolorsforindex(): Color index 255 out of range] [FILE: /includes/class/image.class.php] [LINE: 261]

**Comment by vuthao** [comment]
Thông báo lỗi không rõ ràng, không đúng quy định tại https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md, tôi xin phép đóng thông báo lại
