### ISSUE TITLE
Module news Lỗi tag

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1023]
Với từ khoá trống được thay bằng n/a
khi đó trình duyệt sẽ tạo liên kết là tag/n%26%23x002f%3Ba nhìn rất xấu link và không hợp lý

**Comment by vuthao** [comment]
gửi link demo đi @truongemcom, hiện tại mình ko thấy như thế.

**Comment by truongemcom** [comment]
cái này e nghĩ không cần thiết, vì không ai gõ vào chỗ từ khoá nội dung là n/a cả. A close đi.
