### ISSUE TITLE
Lỗi dùng từ

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1024]
Module comment khi ấn Thích hoặc không thích nhận được thông báo là "bạn đã đánh giá bình luận này trước đó"
Dùng từ đánh giá ở đây là ko đúng vì nó là trạng thái cảm xúc thích hoặc không thích chứ không phải là nhận xét

**Comment by vuthao** [comment]
mình thấy nó có khách ghì đâu nhỉ

**Comment by vuthao** [comment]
mình thấy nó có khách ghì đâu nhỉ
