### ISSUE TITLE
Module news lỗi dùng element

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1025]
Module news lỗi dùng element html block  global.block_category.php
<span class="arrow" id="expand">+</span>
Tồn tại rất nhiều id="expand" trong khi 1 page chỉ được phép duy nhất 1 id 
Specifies a unique id for the element. Naming rules:
Must contain at least one character
Must not contain any space characters
In HTML, all values are case-insensitive

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/7eb1c300915a9b198400883e1badb37615b21fae
