### ISSUE TITLE
Module news điểm bất hợp lý

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1027]
Module news khi ấn vào nút gửi bài viết qua email. mặc dù không có cấu hình gửi qua email từ là đã chặn hàm gửi mail
vẫn nhận được thông báo là bạn đã gửi thành công tới email demo@gmail.com
và lại được nằm ở dưới cùng khiến người gửi không rõ là đã gửi được hay chưa. Đề nghị đưa lên trên cho dễ nhìn thấy thông báo

**Comment by vuthao** [comment]
Việc gửi mail nếu có hàm mail thì code chỉ xác nhận việc chuyển nội dung cho hàm mail, việc có gửi được hay không sẽ không thể biết được.

Việc thay đổi vị trí thông báo tôi đã thay đổi lại: https://github.com/nukeviet/nukeviet/commit/8b841c57c57b1f5115ea9722583acd7a4bcaec9d
