### ISSUE TITLE
Lỗi trang trắng 4.0.18

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1029]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '6.ctypa_users WHERE md5username ='21232f297a57a5a743894a0e4a801fc3'' at line 1' in /Applications/XAMPP/xamppfiles/htdocs/6/includes/core/admin_login.php:90 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/6/includes/core/admin_login.php(90): PDO->query('SELECT * FROM 6...') #1 /Applications/XAMPP/xamppfiles/htdocs/6/admin/index.php(37): require('/Applications/X...') #2 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/6/includes/core/admin_login.php on line 90
-----------
Môi trường thử nghiệm
   - Phiên bản NukeViet: 4.0.18
    - Môi trường thử Nghiệm: Localhost via UNIX socket
    - Hệ điều hành: Mac os 64 bit
    - Trình duyệt web: chrom
    - Máy chủ web:  XAMPP 5.6.8-0
   - Server version: 5.6.24 
Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $
PHP extension: mysqli Documentation
PHP version: 5.6.8

**Comment by thehung** [comment]
@nhimthulinh cho biết em thấy lỗi trên trong tình huống nào nhé!

**Comment by vuthao** [comment]
@nhimthulinh kiểm tra dùm trên các máy khác xem có bị không, chứ hiện tại mình chưa có máy mac để kiểm tra.

**Comment by nhimthulinh** [comment]
Phiên bản hiện tại đã ổn anh
