### ISSUE TITLE
Góp ý về các class img-thumbnail

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#1031]
Để tiện cho việc người sử dụng thay đổi một số cách hiển thị của các class hình ảnh bao gồm: Module news; module shop... và một số Module có sử dụng đến class: img-thumbnail.
Mình có ý kiến nhỏ như sau:
VD: class của module news thì nên đặt là: img-thumbnail-news
       class của Module shop thì đặt là: img-thumbnail-shop
......
tương tự các block của News cũng vậy: img-thumbnail-hotnew: (tin mới)
..v..v.. Tránh việc khi sửa class: img-thumbnail của module nào thì ảnh hưởng đến module đó mà thôi. Chứ mỗi lần chỉnh sửa class: img-thumbnail thì mất công lại đặt lại tên cho nó rất tốn thời gian.

**Comment by trinhthinhhp** [comment]
cái này là cái img-thumbnail mặc định của bootstrap nên ko cần can thiệp gì, còn nếu bạn muốn như vậy thì viết bằng cách xem thuộc tính class phía trước là gì rồi tiến hành ".abc .dcs img" là dc, mình thường xài kiểu đó đỡ mất công đi tìm từng chỗ viết và thay thế trong tpl
