### ISSUE TITLE
Menu không bung ra khi xem ở giao diện mobile

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1032]
Khi xem ở chế độ mobile, menu không bung ra khi click vào

Phiên bản: 4.0.18
Trình duyệt Chrome 43.0.2357.124 m / window 8.1 
Trình duyệt internet explorer theo máy lumia 820/ window phone 8.3

**Comment by trinhthinhhp** [comment]
bạn kiểm tra kỹ lại nha, mình mượn máy của bạn mình check trên IE vẫn ngon, trừ khi IE cũ chưa update theo windowphone

**Comment by phongaz** [comment]
Lớp cha thì vẫn bung nhưng lớp con thì không nhé bạn
![mobile theme](https://cloud.githubusercontent.com/assets/6806295/8184893/31503d62-146b-11e5-9c3a-b4f90efd1984.PNG)

**Comment by trinhthinhhp** [comment]
ko nói rõ là menu nào làm mình nghĩ menu bootstrap
menu này fix ở đây nhá : https://github.com/trinhthinhhp/nukeviet/commit/8f5b07bc521604d288a7be70469ac65b60f3cd30
