### ISSUE TITLE
Loi khong hien thi quan ly bai viet o block content

### ISSUE THREAD

**Issue by ngthanhdo** [nukeviet/nukeviet#1033]
![untitled](https://cloud.githubusercontent.com/assets/12863717/8135349/e504656c-1160-11e5-9df0-0a8435ed31e5.png)
Môi trường thử nghiệm

Phiên bản NukeViet: 4.0.17
Môi trường thử Nghiệm: Localhost via openserver
Hệ điều hành: Win 2k8 64bit
Trình duyệt web: chrom
Máy chủ web: Open Server 5.2.2
Apache 2.2
MySQL 5.5
Php 5.3

**Comment by trinhthinhhp** [comment]
Block content của mình bình thường mà
![untitled](https://cloud.githubusercontent.com/assets/6928431/8183276/1303f5ce-1461-11e5-8b24-22af94ae7d26.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/0a9e56b32ab8b96e4be87046cad947677defd6ce
