### ISSUE TITLE
Lỗi trắng tráng 4.0.18

### ISSUE THREAD

**Issue by thanhvu7411** [nukeviet/nukeviet#1035]
- Phiên bản NukeViet: 4.0.18
Môi trường thử Nghiệm: Localhost
- Hệ điều hành: Windows 8.1
- Trình duyệt web: Mozilla Firefox 38.0.5
- Máy chủ web: XAMPP for windows

Đôi lúc đăng nhập vào admin bị lỗi trắng trang. Nếu vào được thì lại bị lỗi trắng trang khi click vào modules News

**Comment by vuthao** [comment]
Hiện tại chúng tôi không thấy lỗi như bạn thông báo.
Bạn cho biết bạn cài đặt mới hay là nâng cấp từ bản cũ lên.

**Comment by thanhvu7411** [comment]
Em cài đặt mới.
Có lẽ dó xung đột với modules shops. Bị từ sau khi cài modules shops
