### ISSUE TITLE
Thêm cấu hình tỷ lệ nén ảnh cho cấu hình chèn logo

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1036]
Với thông số mặc định của upload thì Nukeviet sẽ làm tăng dung lượng ảnh sau khi chèn logo. Nếu thêm thông số nén vào thì dung lượng hình ảnh sẽ được giảm xuống. Điều này rất có lợi cho những site chạy host giới hạn dung lượng.
Vậy e góp ý là trong cấu hình logo nên thêm một lựa chọn: Chọn thông số nén cho ảnh.

**Comment by vuthao** [comment]
Hiện tại cấu hình Chất lượng hình ảnh theo: Cấu hình ảnh thumbnail 
update: https://github.com/vuthao/nukeviet/commit/76c8de5157c437a2c9ce3ecfb56cdd8a9a94d428
