### ISSUE TITLE
Lỗi trắng trang khi kích hoạt block global.block_new_comment

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#1037]
Như tiêu đề: Comment cho bài viết thì hoạt động tốt, nhưng khi kích hoạt block global.block_new_comment thì lỗi trắng trang.

**Comment by trinhthinhhp** [comment]
Fixed: https://github.com/trinhthinhhp/nukeviet/commit/d48c32ce1ec2af28ed13bb802e9198a3d314130b
