### ISSUE TITLE
Lỗi khi sửa module menu

### ISSUE THREAD

**Issue by ntanh2605** [nukeviet/nukeviet#1039]
Khi chỉnh sửa menu của module menu, nếu để :
Thuộc mục & Liên kết đến module giống nhau sẽ bị lỗi dẫn đến trang trắng ! 
Nên có kiểm tra = java trước và thông báo đến người dùng trước khi submit để khỏi bị lỗi ! Thấy bị từ bản .17 và .18 vẫn chưa có fixed !

**Comment by trinhthinhhp** [comment]
Lỗi này mình ko thấy, mình để nó giống nhau cả menu cha và con đều ko bị, để ngang hàng cũng ko bị

**Comment by ntanh2605** [comment]
Không hiểu được luôn, Mình cài lại 2 lần đều bị. Đến lần thứ 3 xóa sạch tất cả cài lại theo thứ tự CMS, module shop ... thì hết bị !

**Comment by trinhthinhhp** [comment]
lúc bạn kiểm tra đã tắt tối ưu site chưa, vì cái đó nó sẽ sinh ra là và lưu lại để giảm thiểu tiêu tốn máy chủ
