### ISSUE TITLE
Lỗi trang trắng khi sử dụng menu global.bootstrap.php ở block

### ISSUE THREAD

**Issue by ntanh2605** [nukeviet/nukeviet#1040]
Mình cài mới 4.0.18 cùng shop 4.0.15. Khi đồng thời kích hoạt 2 menu bootstrap cho block MENUSITE và 1 block khác bất kì thì bị ra trang trắng. 
Còn 1 menu bootstrap và 1 metismenu cùng module MENU thì k bị ra trang trắng nhưng click vào dấu + để bung menu con thì không được (4.0.17 hoạt động bt) . Trong khi cũng 1 menu bootstrap của module MENU và block catalog của module SHOP sử dụng metismenu thì k hoạt động bình thường ! Mình kiểm tra thì thấy lỗi số 2 là do file js bị sai chổ này  $this.find('li').has('span').children('.expand').on('click', function (e) { . Đáng lẽ ra phải là #expand do khai báo trong file tpl là id ="expand" chứ k phải class !

**Comment by trinhthinhhp** [comment]
Fixed metismenu : https://github.com/trinhthinhhp/nukeviet/commit/8f5b07bc521604d288a7be70469ac65b60f3cd30
