### ISSUE TITLE
Xin hướng dẫn bật chế độ responsive theme khi dùng điện thoại

### ISSUE THREAD

**Issue by caicayvietnam** [nukeviet/nukeviet#1043]
Chào mọi người
Em có xem qua thảo luận này tại https://github.com/nukeviet/nukeviet/issues/947 .
Em muốn nó như bản 4.0.17 khi lựa chế độ hiển thị cho điện thoại là mặc định thì nó sẽ tự động responsive chứ không cần mở chế độ tự động bằng cách click vào nó ở footer nữa.
Em thấy có 2 bất lợi ở cái mới này:
1) Người dùng chưa chắc đã biết mở chế độ đó lên, nếu viết hướng dẫn cho họ thì chưa chắc họ thấy mà đọc.
2) Khi truy cập bằng điện thoại thì load trang rất nặng ( nó làm treo đt cùi mía của em), mà nếu mở chế độ tự động lên thì nó lại load trang thêm 1 lần nữa.
Web em mới mở nên cần nhiều chi tiết để trang trí nên dùng chế độ mobile không khả dụng.
Chốt lại là em muốn khi dùng điện thoại truy cập site thì nó trả về giao diện responsive chứ không cần lựa chọn gì cả.
Cảm ơn mọi người đã quan tâm và giúp đỡ em.

**Comment by trinhthinhhp** [comment]
bạn vào admin đến cấu hình -> cấu hình site, ở giao diện mobile thì bạn chọn là giao diện PC là được nhé

**Comment by vuthao** [comment]
@caicayvietnam  @trinhthinhhp.
Với các hướng dẫn các bạn vui lòng thảo luận tại diễn đàn, đây là khu vực quản lý lỗi.
