### ISSUE TITLE
Lỗi khi sử dụng website đa ngôn ngữ

### ISSUE THREAD

**Issue by vanthankhue** [nukeviet/nukeviet#1044]
Minh cài mới phiên bản 4.0.18 khi sử dụng chức năng đa ngôn ngữ trong web bị lỗi:
1. khi sử dụng 2 ngôn ngữ tiếng Việt và tiếng Anh, trong phần quản trị web bị lỗi hiển thị ngôn ngữ không nhất quán khi chuyển đổi qua lại 2 ngôn ngữ Việt - Anh (top menu hiển thị tiếng Anh, menu left hiển thị tiếng Việt và ngược lại)
2. Không sử dụng được layout: body-left-right trong giao diện ngôn ngữ English

**Comment by trinhthinhhp** [comment]
lỗi số 2 fixed: https://github.com/trinhthinhhp/nukeviet/commit/8b6fbd88155ed43fc335d0eaec2d9eaeb1ca4849
