### ISSUE TITLE
Lỗi cấu hình tạo module ảo.

### ISSUE THREAD

**Issue by PhamQuocTien132** [nukeviet/nukeviet#1045]
Tại file: version.php của modules Menu đang đặt: 'virtual' => 0  (Theo bản mặc định của hệ thống) nhưng khi tạo module ảo thì hệ thống vẫn cho tạo module ảo.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/f128a8eafc2ed0de470d889cc78f42f9eda03dda
