### ISSUE TITLE
Lỗi không hiển thị submenu ở giao diện Mobile

### ISSUE THREAD

**Issue by mathagu** [nukeviet/nukeviet#1046]
Môi trường thử nghiệm:
Phiên bản NukeViet: 4.0.18
Môi trường thử Nghiệm: localhost
Trình duyệt web: Google Chrome
Hệ điều hành: Win 8.1
Máy chủ web: Open Server 5.2.2 Ultimate

Mô tả: Khi chọn giao diện mobile, menu Bootstrap sẽ tự động chuyển thành menu Metis. Các menu có submenu đều xuất hiện dấu + nhưng bấm vào không mở được submenu.

**Comment by trinhthinhhp** [comment]
menu Metis đã fix lỗi này rồi nhé, bạn cần phải tải lại bản mới nhất để khắc phục lỗi metismenu 
Fixed: https://github.com/nukeviet/nukeviet/commit/8f5b07bc521604d288a7be70469ac65b60f3cd30
