### ISSUE TITLE
Phần giới thiệu ngắn gọn hiển thị thẻ br khi xuống dòng [NEWS]

### ISSUE THREAD

**Issue by anhtrangxua5** [nukeviet/nukeviet#1049]
Nhập nội dung có xuống dòng tại phần giới thiệu ngắn gọn module news, khi sửa lại bài viết thì hiển thị các thẻ br chứ không tự xuống dòng

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/b404c33b71e1cb9646396e50a1e0addea34b7965
