### ISSUE TITLE
Lỗi đăng nhập oauth trên PHP 5.6

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1052]
HIện tại lỗi đăng nhập oauth trên PHP 5.6 bị trang trắng trên cấu hình sau:
    - Phiên bản NukeViet: 4.0.18
    - Môi trường thử Nghiệm: Localhost/
    - Hệ điều hành: Fedora 22
    - Máy chủ web:  XAMPP for Linux  5.6.8 / PHP 5.6.8

Includes: Apache 2.4.12, MySQL 5.6.24, PHP 5.6.8 & PEAR + SQLite 2.8.17/3.7.17 + multibyte (mbstring) support, Perl 5.16.3, ProFTPD 1.3.4c, phpMyAdmin 4.4.3, OpenSSL 1.0.1m, GD 2.0.35, Freetype2 2.4.8, libpng 1.5.9, gdbm 1.8.3, zlib 1.2.8, expat 2.0.1, Sablotron 1.0.3, libxml 2.0.1, Ming 0.4.5, Webalizer 2.23-05, pdf class 0.11.7, ncurses 5.9, pdf class 0.11.7, mod_perl 2.0.8-dev, FreeTDS 0.91, gettext 0.18.1.1, IMAP C-Client 2007e, OpenLDAP (client) 2.4.21, mcrypt 2.5.8, mhash 0.9.9.9, cUrl 7.30.0, libxslt 1.1.28, libapreq 2.12, FPDF 1.7, ICU4C Library 4.8.1, APR 1.4.6, APR-utils 1.5.1

Trên XAMPP for Linux 5.5.24 / PHP 5.5.24 chạy bình thường.

**Comment by vuthao** [comment]
Phiên bản hiện tại đã chạy trên host php 5.6.

Các bạn thử cái login bằng facebook xem có được ko nhé: http://php56.vinades.net/

**Comment by phongaz** [comment]
Đã thử đăng nhập thành công.
