### ISSUE TITLE
Lỗi giao diện quản trị khi tối ưu site

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1056]
- Phiên bản NukeViet: 4.0.18
    - Môi trường thử Nghiệm: Hosting
    - Hệ điều hành: Fedora 22 - 64bit
    - Trình duyệt web: Google chrome 43.0.2357.125 (64-bit)
    - Công cụ quản lý hosting: DirectAdmin
    - PHP Ver: 5.5.25

![selection_044](https://cloud.githubusercontent.com/assets/6407361/8368601/8b0c0d64-1bd6-11e5-8eb7-cc9852f42a38.png)
![selection_043](https://cloud.githubusercontent.com/assets/6407361/8368602/8b130d08-1bd6-11e5-888d-a2f2f843ea69.png)

**Comment by vuthao** [comment]
Lỗi này xẩy ra khi server có thư viện: php_tidy

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/6b19810221687ccbbd0547085a4fa4d9a4ebe399
