### ISSUE TITLE
Lỗi url khi không có ký tự kết thúc

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1057]
Khi không có ký tự kết thúc thì báo **Object not found!**. 
Cần xử lý, khi không có ký tự kết thúc thì hệ thống tự động thêm vào và truy cập bình thường.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/10d70bc5f574e91b1e14aca236d0caff3feb4eed
