### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1060]
Phiên bản NukeViet	4.0.18 
Phiên bản PHP 5.5.11
Giao thức giữa máy chủ và PHP Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.11, apache2handler
Hệ điều hành máy chủ	WINDOWS NT
Phiên bản Database	mysql 5.6.16 
Notice: Undefined variable: module in modules\menu\admin\link_module.php on line 86

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/1843134cea911b51c4f229c0bb7a20db4c17852d
