### ISSUE TITLE
Module menu chưa nạp được menu cấp 3 trở đi 

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1062]
Phiên bản NukeViet 4.0.18 
Phiên bản PHP 5.5.11
Giao thức giữa máy chủ và PHP Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.11, apache2handler
Hệ điều hành máy chủ WINDOWS NT
Phiên bản Database mysql 5.6.16 
Đã test trên module shops và kết quả chỉ nạp được tới danh mục sản phẩm cấp 2

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/b030ae681b2d0bbcdff39a21f78a51582aec9164
