### ISSUE TITLE
Bất cập module menu

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1063]
Hiện tại các khu vực khác đã hỗ trợ box search cho select option tuy nhiên module menu thì lại chưa.
Với trường hợp danh mục menu của module nào đó có số lượng lớn từ 100 tới 200 danh mục sẽ phát sinh vấn đề option quá dài tốn nhiều công tìm kiếm

**Comment by vuthao** [comment]
@dangdinhtu2014  cho đề xuất cách xử lý nhé.

**Comment by hongoctrien** [comment]
Menu em có thêm, nhưng hình như bỏ sót :D

**Comment by vuthao** [comment]
box search cho select option mình không hiểu cái này là cái ghì nhỉ ?

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/nukeviet/commit/ddbdfb14ec3132675ce57440c50a5cd905b0fbd0

**Comment by dangdinhtu2014** [comment]
chú @hongoctrien  kiểm tra luôn phần nạp menu nó đã nạp được cấp 3 chưa hiện tại anh test nó vẫn chỉ nạp đến cấp 2 thôi
