### ISSUE TITLE
Đề xuất thêm class theo module và op cho layout để tăng tính tuỳ biến cho giao diện

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1064]
<body id="body-shops" class="body-main">
Với cấu trúc này ta có thể tăng thêm rất nhiều tính tuỳ biến cho giao diện ở nhiều khu vực khác nhau mà không cần tốn nhiều layout. vấn đề không mới nhưng vẫn phải nhắc lại. Mong các bạn xem xét vấn đề này

**Comment by vuthao** [comment]
Đọc cái này mình không hiểu là ghì @dangdinhtu2014

**Comment by dangdinhtu2014** [comment]
<body id="body-{MODULE_NAME}" class="body-{OP}">

**Comment by dangdinhtu2014** [comment]
<body id="body-{MODULE_NAME}" class="body-{OP}">

**Comment by vuthao** [comment]
Việc này không đưa vào giao diện mặc định là không cần thiết  Tứ, bỏi nó sẽ làm  phức tạp giao diện mặc định. 

Nếu làm theo cách này, tùy biến kiểu ghì cũng phải viết thêm css, khi đó người làm giao diện sẽ tự biết làm thế nào cho hợp lý.
