### ISSUE TITLE
[Góp ý] Cơ chế đóng gói modules bỏ sót theme mobile

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1066]
Như tiêu đề, khi đóng gói ứng dụng, mà ở đây là module thì phần theme hiện chỉ có default, admin_default; còn với mobile_default thì ko được đóng gói thành file tải xuống.
Hy vọng chức năng này có thể được bổ sung điều chỉnh sao cho phù hợp.

**Comment by vuthao** [comment]
Bạn vui lòng đọc hướng dẫn khi tạo 1 issues: Please review the guidelines for contributing to this repository. https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md

Phiên bản hiện tại chúng tôi không thấy lỗi như bạn thông báo.

**Comment by anhyeuviolet** [comment]
NV 4.0.18
Windows 7 SP1
XAMPP 1.8.3

Không biết anh @vuthao  có thử kiểm tra với các modules khác news chưa ?
Phiên bản hiện tại mà tôi báo lỗi, thì có 2 modules có thư mục bên trong mobile_default là news và comment.

![image](https://cloud.githubusercontent.com/assets/6290970/8397049/312bfa16-1de8-11e5-99f9-74bf2c1340c8.png)


Và đây là modules comment khi đóng gói về 
![image](https://cloud.githubusercontent.com/assets/6290970/8397051/417a7afa-1de8-11e5-8d54-93e136d1acb0.png)

Tất nhiên một modules tôi đang phát triển cũng không được đóng gói giao diện mobile_default khi dùng chức năng trong ACP.
