### ISSUE TITLE
Cơ chế đóng gói modules bỏ sót theme mobile

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1067]
NV 4.0.18
Windows 7 SP1
XAMPP 1.8.3

Không biết anh @vuthao có thử kiểm tra với các modules khác news chưa ?
Phiên bản hiện tại mà tôi báo lỗi, thì có 2 modules có thư mục bên trong mobile_default là news và comment.

![image](https://cloud.githubusercontent.com/assets/6290970/8397105/4ac5b01e-1dea-11e5-9911-50c44f9c0fc2.png)

Và đây là modules comment khi đóng gói về 
![image](https://cloud.githubusercontent.com/assets/6290970/8397106/5375a200-1dea-11e5-9a4f-a67b811d1a84.png)

Tất nhiên một modules tôi đang phát triển cũng không được đóng gói giao diện mobile_default khi dùng chức năng trong ACP.

https://github.com/nukeviet/nukeviet/issues/1066

Lỗi đã báo tại link trên và bị khóa.

**Comment by vuthao** [comment]
Nguyên tắc đóng gói 1 module là đóng gói tối thiểu những ghì cần.
Theme mobile_default là không bắt buộc dùng, nên chúng tôi không cho đóng gói.

**Comment by anhyeuviolet** [comment]
Điều này thì em hơi thắc mắc; trong trường hợp theme mobile được nhà phát triển đóng gói một cách có chủ ý, vì chức năng của bản PC và Mobile sẽ khác biệt nhau rất nhiều ( vì lý do thẩm mỹ hoặc giảm tải cho thiết bị mobile chẳng hạn ) thì phải xử lý thế nào.
News hiện khi đóng gói thì có kèm theo mobile_default, vậy modules này được cấu hình thế nào thì khi đóng gói sẽ bao gồm cả theme mobile ?

Khi biết được cơ chế đó thì tự thân người dùng cũng như người phát triển modules có thể linh động mà áp dụng có đóng gói hay không giao diện cho điện thoại.

**Comment by vuthao** [comment]
Bạn cần tạ gói ngày chuẩn, sau đó cài lại sang sai khác, lúc đó gói nó sẽ đóng gói đầy đủ, hoặc bạn cần thêm file này vào bảng nv4_extension_files

**Comment by anhyeuviolet** [comment]
Đã hiểu và thực hiện được.
Cảm ơn gợi ý của anh @vuthao .
