### ISSUE TITLE
Cấu hình CSDL  có vấn đề thấy không ổn

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#1072]
Ví dụ cấu hình như sau:
Kích hoạt tiện ích lưu CSDL	 (chọn)
Định dạng lưu CSDL	 (gz)
Lặp lại công việc sau	1 (ngày)
Thời gian lưu file backup CSDL	5  (ngày)

Trong phần Sao lưu dữ liệu sẽ là: 1 x 5 = 5 file CSDL được lưu trữ tự động.

Như theo tôi thấy thì với cấu hình trên các file csdl được tự động sao lưu có thể lên vài trăm file và có thể là nhiều hơn. Niếu cần xóa bớt thì phải xóa thủ công từng cái 1, như vậy bất tiện quá.
Còn để thì nó sẽ chiếm dung lượng hosting rất nhiều. 

Tôi thấy nên có chức năng tự động xóa các file csdl tự động lưu theo thời gian đã cấu hình.
Các file csdl do admin backup thì có thể chừa lại và phải xóa theo 1 cơ chế riêng.
Hiện nay niếu thực hiện backup csdl thì sẽ báo trang trắng, mặc dù đã thành công.

Phiên bản NukeViet đang sử dụng:	4.0.18
Domain: http://banthucphamsach.com

**Comment by thehung** [comment]
1. Cấu hình sao lưu cơ sở dữ liệu thời gian 5 ngày tức là sẽ có 5 file được lưu. Không thể có chuyện lưu đến mấy trăm file. Nếu file cũ không được xóa đi thì bạn kiểm tra và kích hoạt lại cronjob dọn dẹp cơ sở dữ liệu cũ nhé!
2. Tôi test trên localhost sử dụng Vertrigo 2.30 không gặp lỗi trang trắng như bạn nói. Vui lòng cung cấp thông tin môi trường thử nghiệm.

**Comment by anhyeuviolet** [comment]
Tối đa nếu ko dọn dẹp thì cũng chỉ có khoảng 30 file là cùng.
Ngoài ra thì nếu host không hỗ trợ tốt thì khi sao lưu DB mới sinh ra trắng trang thôi.

**Comment by NukeVietCMS** [comment]
![cau hinh sao luu csdl](https://cloud.githubusercontent.com/assets/8376014/8447515/5b6f4bfe-1fe4-11e5-84d1-9ed0d5c705c1.png)
![sao luu csdl](https://cloud.githubusercontent.com/assets/8376014/8447516/5b820fd2-1fe4-11e5-8b1a-f7e8ad5f9d25.png)
