### ISSUE TITLE
Đề xuất bổ sung thẻ heading từ h1-h6  khi thêm block

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1073]
Hiện tại việc seo theo thẻ heading cũng là một vấn đề mà nhiều bạn quan tâm. Tất nhiên chúng ta có thể tạo ra các template block cho các heading từ h1 tới h6 nhưng nó lại gặp vấn đề phát sinh quá nhiều file template không cần thiết. Nên đề xuất các bạn bổ sung tính năng này cho nó sẽ rất tiện cho việc seo 
![heading](https://cloud.githubusercontent.com/assets/6817130/8422845/1235c730-1f0b-11e5-9985-0ca686543943.jpg)

**Comment by RightPro** [comment]
Hiện H1 đang bị fix cứng là sitename, nên cho phép bổ sung H1-H6 + tùy biến người dùng trong admin về vấn đề thẻ H1 ở mỗi module. Một số trang do ko có nhu cầu hiển thị sitename, sau khi xóa phần fix cứng này thì dẫn tới việc thiếu H1, phải thêm một bước là sửa ở rất nhiều các module trong nhiều file tpl khác nhau để bổ sung thẻ này.

**Comment by vuthao** [comment]
Vẫn đềm mã sẽ sinh ra như thế nào.
Nếu block không dùng mã heading  thì sao.
Tứ trình bày giải pháp đầy đủ cho tất cả các vấn đề liên quan.
Hiện tại đến kho phát hành NukeViet chính thức, chúng tôi sẽ không thêm tính năng mới để có thể có bản nukeviet ổn định đề dùng đã, các tính năng đề nghị sẽ được xem xét ở bản 4.1

**Comment by dangdinhtu2014** [comment]
Nếu block không dùng mã heading thì sao.
thì để là no heading thôi

**Comment by dangdinhtu2014** [comment]
Hiện tại tôi đã hoàn thành tính năng này. Nếu được chấp thuận thêm luôn vào bản RC của hệ thống thì mình sẽ commit lên

**Comment by hoanglongvnpt** [comment]
Theo mình nên bổ sung chức năng như dangdinhtu2014 đã đề xuất trước khi phát hành bản RC1.

**Comment by vanhuonghn011291** [comment]
Nhiều khi chỉ vì 1 cái thẻ Heading cho 1 block mà phải tạo 1 template mới cho blocks thì thật bất tiện.. em nghĩ những cái cần thiết và có thể làm được ntn thì sao ko cho vảo bản RC1 luôn đi ạ?

**Comment by RightPro** [comment]
Lại điệp khúc chờ? Ngay đến việc phát hành bản RC1 cũng bị delay và đến hiện tại vẫn chưa có gì là chắc chắn 100% ngày ra mắt, vậy thì bao giờ sẽ ra mắt bản 4.1 và những tính năng đang chờ này sẽ chờ xem xét bao lâu, và cộng động lại phải chờ xem nó có được thông qua hay không ?

**Comment by thehung** [comment]
Em commit lên khó code để đội code kiểm tra nhé. Chấp nhận hay không phụ
thuộc vào việc giải pháp và code hoàn thiện hay chưa.

**Comment by thaotrinhj** [comment]
Làm như trên có thể dẫn đến lạm dụng H1-H6. h1-h6 là những "thẻ quý", nhiều khi tiêu đề block rất chung chung (Bài viết mới nhất, Bình luận mới nhất, Các chuyên mục, ...), ko có đặc trưng và ko quan trọng như từ khóa. nên dùng h1-h6 cho tiêu đề, chuyên mục, label, từ khóa.  
Trong các công cụ test seo, họ có giới hạn số lượng thẻ h1-h3, h1 chỉ duy nhất 1, các thẻ sau được tăng dần.
Theo w3.org thì H* được dùng trong 2 trường hợp:
1. dùng làm bố cục cho giao diện (tiêu đều block). 
2. dùng cho tiểu mục (phần nội dung)
Theo w3schools thì h1-h6 ko ủng hộ trong html5, khuyên dùng css thay thế.
Ngày nay h1-h6 được dùng cho mục đích seo và dùng css để thay đổi cỡ chữ.
Do đó tùy mục đích mỗi người, với mình thì ưu tiên nó cho nội dung, để có đặc trưng riêng so với web khác
Nếu dùng cách 1 thì bác Tứ nên cho thêm trường hợp null. Không nên cho H1 vào đây vì nó phát sinh  ít nhất 2 H1 trong trang, điều này rất kỵ.

**Comment by hoaquynhtim99** [comment]
Có một thực tế từ trước đến nay, giao diện thường theo một thiết kế sẵn, nội dung cũng cần cân nhắc kỹ, chỗ nào có thẻ heading chỗ nào không đã tính toán sẵn, quá nhiều chức năng đôi khi cần 1 cái gì đó đơn giản để làm lại không có, mọi thứ càng này càng trở nên phức tạp.
Ra lò một sản phẩm mới trước đó cần phải lên quá trình kỹ lưỡng, không ai hôm nay lại thay cái này bằng cái khác ngày mai lại thay cái khác nữa, nên thiết nghĩ cái này là thực sự không cần thiết.

**Comment by hoaquynhtim99** [comment]
@RightPro vội thế thì sao ko bắt tay vào làm ngay cho bản sắp tới nhỉ

**Comment by vuthao** [comment]
Tôi thấy template làm được việc này, và thường thì chỉ dùng 2 đến 3 cái là cùng. nên không cần thiết phải đưa thêm chức năng này vào NukeViet.
