### ISSUE TITLE
Lỗi thông báo duy trì đăng nhập khi xem trên mobile

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1074]
Khi xem trên mobile, mặc dù không đăng nhập nhưng lại có thông báo này
Phiên bản: 4.0.19 RC

![wp_ss_20150630_0002](https://cloud.githubusercontent.com/assets/6806295/8424117/6a51872e-1f1f-11e5-9dce-7c9b05032b1d.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/e49d7998442755fa47ee43c4119bf48446d1722c

**Comment by phongaz** [comment]
Sau khi update fle main.js ở o=commit này thì bị lỗi sau

![captureo](https://cloud.githubusercontent.com/assets/6806295/8448915/bc4a858a-1ff6-11e5-8f5c-3c2f4ae3308b.PNG)
