### ISSUE TITLE
Block global_site_mods của modules menu không xuất được menu cấp 2

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#1076]
global site mods của modules menu không xuất được menu con. Khi cài cái này thì cái nào có chuyên mục con là xuất hiện chữ "Array". Cái lỗi này đã có từ lâu rồi cho đến bản 4.0.19 vẫn còn tồn tại. 
global site mods sử dụng trên giao diện default để làm chuẩn.
Mong đội code sửa lại lỗi này.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/c4ac4c4dbbbd735d26cdd0de9a88f64723b7fa8a
