### ISSUE TITLE
Cảnh báo khi chọn thêm bài viết của module page

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1077]
Nên chú ý: Undefined index: description in file /modules/page/admin/content.php on line 163

do khi dùng 
<code>
$row['description'] = nv_htmlspecialchars( nv_br2nl( $row['description'] ) );
</code>
 chưa có khai báo $row['description'] tại chỗ kiểm tra không có $id

**Comment by thehung** [comment]
Anh thử trên bản mới nhất là NukeViet 67ec921005de47b8db07a7a4855200093fc9b598 không thấy nhé. Em check lại xem hết chưa @htuyen1994
