### ISSUE TITLE
Nên bỏ đi các thành phần không cần thiết

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1083]
- Module RSSfeed, Contact,  nên bỏ đi chức năng "Nội dung thông báo".
- Module RSSfeed không có phần cấu hình => cần ẩn nó đi khỏi Admin Control Panel.

**Comment by vuthao** [comment]
Việc này để cho việc cấu hình các thông báo được dễ dàng, có thể sử dụng block, nhưng dùng block nhiều khi hay chọn nhầm, chỗ nào nó cũng hiển thị không báo.

và cũng không nên lạm dụng block.
