### ISSUE TITLE
Lỗi hiển thị menu active

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1084]
NukeViet 67ec921005de47b8db07a7a4855200093fc9b598
![anh chup 225](https://cloud.githubusercontent.com/assets/1892900/8461509/75a9e312-2057-11e5-9057-500f6eaa926a.jpg)
Khi truy cập module News, có 2 menu được active. => Có thể tránh tình huống này bằng cách không ghi nhận active cho "Trang nhất"

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/392687ff67d94fa470c69619b33371d8f98eff92
