### ISSUE TITLE
Lỗi thừa code khi trình bày chi tiết bản tin

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1085]
NukeViet 67ec921005de47b8db07a7a4855200093fc9b598
Thừa \n"; ngay trên đầu bản tin.
![anh chup 226](https://cloud.githubusercontent.com/assets/1892900/8461664/7e0db0c8-2058-11e5-98db-4c5ceaa2357e.jpg)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/dc2e062d2ed6d24e55a69cc6d3a5b7d87975ab4f
