### ISSUE TITLE
Có thể tìm thấy bài viết ngay cả khi bài chưa đăng

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1086]
NukeViet 67ec921005de47b8db07a7a4855200093fc9b598
Trạng thái bài viết như sau
![anh chup 228](https://cloud.githubusercontent.com/assets/1892900/8461678/90d75c5e-2058-11e5-87b3-f62932ce927b.jpg)
Tuy nhiên khách truy cập vẫn tìm thấy bài viết khi tìm kiếm.
![anh chup 227](https://cloud.githubusercontent.com/assets/1892900/8461701/bd17ec02-2058-11e5-9ffb-02f8b7899767.jpg)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/8d1b183cc338e37cc4031e0bc65cbc11f1da20d9
