### ISSUE TITLE
Redirect sai link khi gõ thiếu ký tự kết thúc của đường link truy cập

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1088]
NukeViet 67ec921005de47b8db07a7a4855200093fc9b598 cài trên localhost sử dụng Vertrigo.
NukeViet được đặt tỏng thư mục "nukeviet4". Khi truy cập http://localhost/nukeviet4/users
Hệ thống trỏ về http://localhost/users/ (đường dẫn sai vì thiếu tên thư mục "nukeviet4")

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/49c9564e1037aece4d024e74eb89a1ecdfaa842c
