### ISSUE TITLE
Comment bị giới hạn thời gian dù hai bài viết khác nhau

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1089]
Khi bình luận phải đợi 6 phút sau mới được bình luận tiếp, dù đó là hai bài viết hoàn toàn khác nhau.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/1c1a055f1e4736d59c5e87604e234fd1186163ca
