### ISSUE TITLE
Cần tăng thêm tích cỡ của màn hỉnh hiển thị !

### ISSUE THREAD

**Issue by volong1012** [nukeviet/nukeviet#1091]
Hiện nay nukeviet đang để màn hình của waper là 1150px mặc dù là chia cột theo % nhưng để chia 1150  cho 24 col sẽ ra số lẻ là 47,91666... trong thiết kế thì không thể nào chia chính xác như vậy .. do đó nếu để ở 48px cho 1 cột thì tích cỡ hiển thị sẽ là 1152px.... chỉ cần thêm 2 px nhưng khi thiết kế chia cột sẽ thoải mái hơn là 1150 như hiện giờ

**Comment by vuthao** [comment]
Hiện tại đã cấu hình màn hình tối đa về 1080px để có thể chèn quảng cáo 120px mối bên.
