### ISSUE TITLE
Bỏ module about  và thay bằng module Page

### ISSUE THREAD

**Issue by thaotrinhj** [nukeviet/nukeviet#1093]
Hiện nay tồn tại mặc định 2 module giống nhau là about và page.
Ở phiên bản tới ta nên bỏ about và thay bằng page.
Hiện tại dữ liệu about đang có 2 bài mẫu giới thiệu về nukeviet, chúng ta có thể chuyển sang page cũng được.

**Comment by vuthao** [comment]
about là một module ảo của page. Chúng tôi để đó để demo giới thiệu tính năng ảo hóa của module.
