### ISSUE TITLE
Đề nghị cache file html các block module menu

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1095]
Hiện tại việc sử dụng vòng lặp đối với menu cấp 3 trở lên và số lượng danh mục nhiều. sẽ dẫn đến tình trạng chậm xuất hiện menu. xử lý vòng lặp đệ quy khá nhều gây tốn bộ nhớ.

**Comment by vuthao** [comment]
Do menu còn cần xác định các trạng thái active, nên ko cache được nhé bạn, nếu được tứ đưa ra phương án xử lý nhé.

**Comment by dangdinhtu2014** [comment]
Việc active menu có thể sử dụng javascript để active thông qua các tham số truyền vào các thẻ. cơ chế active hiện tại của hệ thống cũng không đạt hiệu quả nhiều nên nó ko đáng ngại

**Comment by vuthao** [comment]
thế Tứ xử lý thử một cái menu, nếu được anh sẽ đưa vào code NukeViet nhé.

**Comment by hoaquynhtim99** [comment]
Ý kiến cá nhân: Hầu như các site không nhiều menu tới mức gây ảnh hưởng tới máy chủ. Sử dụng javascript xử lý nhiều gây nặng nề cho trình duyệt người dùng đặc biệt là trên điện thoại di động cho nên cái này cần cân nhắc.

**Comment by dangdinhtu2014** [comment]
chắc cái này lại phải do nhà phát triển tự cân nhắc theo site mình làm rồi. nhưng nếu mà như hiện tại thì vẫn chưa phải là tối ưu. khi load block thì nó thường hiện chậm và làm tốn bộ nhớ.

**Comment by vuthao** [comment]
Nếu  do nhà phát triển tự cân nhắc, thì để người ta tự code thôi nhỉ, mình chỉ làm cho bản mặc đinh.
Bản mặc định sẽ không thể làm hết được các trường hợp được.
