### ISSUE TITLE
lỗi không hiện thị chi tiết bài viết

### ISSUE THREAD

**Issue by qeenlovelly** [nukeviet/nukeviet#1096]
Xin chào cả nhà. Em dang sử dụng demo web bằng bản 4.0.18 nhưng bị 2 lỗi là các menu đều bị sai link và không thẻ hiện thị chi tiết bài viết của module news. Anh chị nào hỗ trợ em với.
Link demo:http://doanhnhanvietnam.biz/vnpaco/

**Comment by hoaquynhtim99** [comment]
Cái này bạn xem lại file .htaccess thông số 
```#RewriteBase /
Nếu cua bạn nó phải là 
```#RewriteBase /vnpaco/
hoặc hosting của bạn có hỗ trợ rewrite không, có thể vào cấu hình chung để bật tắt chức năng rewrite cho phù hợp, nó không phải lỗi của NukeViet nhé.

**Comment by qeenlovelly** [comment]
Cũng không được bạn ơi. Nuke 4 không có file .htaccess

**Comment by hoaquynhtim99** [comment]
Nuke nào mà ko có .htaccess bạn, những vấn đề về sử dụng mời bạn lên diễn đàn http://forum.nukeviet.vn/ hoặc fanpage https://www.facebook.com/nukevietcms để thảo luận nhé
