### ISSUE TITLE
Không chọn được ảnh 

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1100]
NukeViet 5401d82361b7ffb50aae4b15116738c6b7341725
Khi thêm bài viết trong mục tin tức.Khi chọn ảnh không thể chọn được ảnh để thay thế ảnh cũ.

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/nukeviet/commit/4cd5ba07ae78f6ae0eb86630abedbf6cd94cb838
