### ISSUE TITLE
Lỗi Browse server

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1101]
NukeViet 5401d82361b7ffb50aae4b15116738c6b7341725
Trong mục Quản lý chuyên mục nút Browse server không thể ấn để chọn ảnh

**Comment by anhyeuviolet** [comment]
Mình test không thấy vấn đề này nhỉ :D

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/nukeviet/commit/4cd5ba07ae78f6ae0eb86630abedbf6cd94cb838
