### ISSUE TITLE
Lỗi chức năng tìm kiếm trong Quản lý Tags

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1102]
NukeViet 5401d82361b7ffb50aae4b15116738c6b7341725
Khi ấn Tìm kiếm trong Quản lý Tags Tự động nhảy về link /admin/index.php?language=vi&nv=siteinfo

**Comment by anhyeuviolet** [comment]
Không thấy vấn đề như này :D

**Comment by vuthao** [comment]
Nó đang lỗi thật đó @anhyeuviolet . đêm mình sẽ fix nó.

**Comment by anhyeuviolet** [comment]
Ủa kỳ ta ... em thử mấy lần ko thấy lỗi về các chức năng tìm kiếm.... Kể cả bản Dev.
:D Thôi chờ bản tiếp theo ra vậy.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/8985c83881302bd93291b80eab04222d0855dfa2

**Comment by thehung** [comment]
NukeViet https://github.com/nukeviet/nukeviet/commit/309075b2e596730d03df930d8e1d7d61c5e28d14 vẫn dính lỗi này.

**Comment by anhyeuviolet** [comment]
Kỳ lạ là em không thấy lỗi này ở bản tải từ link này.
https://github.com/nukeviet/nukeviet/tree/4.0.21

Nhưng bộ code develop hiện tại thì lỗi một cách hoàn chỉnh.
https://github.com/nukeviet/nukeviet/tree/develop

**Comment by hoaquynhtim99** [comment]
Phiên bản hiện tại có thay đổi rất nhiều về js của toàn mã nguồn nên có thể rất nhiều vấn đề xoay quanh js, mình sẽ kiểm tra vấn đề này

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/nukeviet/commit/a2ec46ba296490818ee6ac8ab4083caf9062aa4a
