### ISSUE TITLE
Lỗi tìm kiếm trong module Tài khoản

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1103]
NukeViet 5401d82361b7ffb50aae4b15116738c6b7341725
Khi nhập từ khóa tìm kiếm trong module Tài khoản.Sau đó ấn Tìm kiếm không hiển thị ra kết quả tìm kiếm mà mất hết thông tin các tài khoản

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/bc6094becb4b3f4c24660b5604f320d08e341fb3
