### ISSUE TITLE
Lỗi chức năng đăng ký ngoài site

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1104]
Nukeviet 5401d82361b7ffb50aae4b15116738c6b7341725
Lỗi đăng ký tài khoản mới ngoài Site. Khi đăng ký thành công thì ra trang trắng.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/b793467c5ba8ec2ae5274486d9db60d90ddea4ac
