### ISSUE TITLE
Lỗi khôi phục mật khẩu cho tài khoản ngoài Site

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1105]
Nukeviet 5401d82361b7ffb50aae4b15116738c6b7341725
Khi ấn chức năng vào Quên mật khẩu ngoài Site, khi ấn gửi yêu cầu ra trang trắng

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/b793467c5ba8ec2ae5274486d9db60d90ddea4ac
