### ISSUE TITLE
Lỗi cronjobs

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1106]
Một số lần chạy xuất hiên lỗi liên quan đến cronjobs
![selection_078](https://cloud.githubusercontent.com/assets/6407361/8505976/150268be-2227-11e5-8565-e14d048fb02f.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/e7e25584a2038cffc970b359bf1564758ac25571
