### ISSUE TITLE
Layout left-body-right:cột left bé hơn cột right 1 col

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1107]
Do cột left sử dụng col-md-4 lên block thống kê truy cập phần số bị đẩy xuống hàng dưới

![image](https://cloud.githubusercontent.com/assets/10300770/8506029/67952cfe-2229-11e5-82bf-fac11af6c4cf.png)

**Comment by anhyeuviolet** [comment]
Thực ra thì LEFT được định hình có width nhỏ hơn RIGHT mà.
Còn bị nhảy xuống dưới như kia, mình đoán là màn hình bạn dùng <1366px, hoặc ít nhất cửa sổ duyệt web nhỏ hơn thì nó mới dồn xuống như vậy.

**Comment by vuthao** [comment]
Cái này là do chúng tôi mới thu nhỏ màn hình nội dung của site xuống 1080 để trên các màn hình >=1366 có thể chèn được quảng cáo ở hai bên, mỗi bên 120px.

Mình sẽ sửa lại cột bên trái to thêm 1 cột nữa.

**Comment by mathagu** [comment]
Cái này mình toàn tự sửa lại trong file TPL, thậm chí khi chọn layout là left-body thì left cũng chỉ có col-md-4, cảm giác hơi chật chội!

**Comment by hongoctrien** [comment]
Mình cũng thấy hiện tại giao diện chật chội quá, hay nhìn thoáng quen rồi ^^.
Có cần phải ưu tiên cái quảng cáo 2 bên mà phải thu hẹp giao diện không anh @vuthao

**Comment by vuthao** [comment]
Giao diện mặc định thể hiện tất cả các tính năng có thể có.
Còn khi làm site mà các bạn điều chỉnh lại theo ý thích của mình.

Hiện tại mình đã điệu chỉnh block trái to thêm 1 cột nữa: https://github.com/nukeviet/nukeviet/commit/c81b4478fa53b36f3d176832fb42eb224dd60460
