### ISSUE TITLE
menu bootstrap khi reponses

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1108]
Hiện tại khi reponse menu boostrap thì tiêu đề hiện chữ Menu Site như vậy không hợp lý cho lắm, chuyển thành icon trang chủ ở vị trí đó

**Comment by hoaquynhtim99** [comment]
Hiện tại chữ đó phụ thuộc vào tên block, bạn có sửa block đó và thay tên của block bằng bất cứ từ gì bạn thích và dòng đó sẽ thay đổi
