### ISSUE TITLE
Lỗi user:Không hiển thị thông tin ip, lần đăng nhập cuối khi xem thông tin thành viên

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1110]
phiên bản 4.0.20

![image](https://cloud.githubusercontent.com/assets/10300770/8506083/e0cb0aaa-222c-11e5-9756-57377df1d5cf.png)

**Comment by anhyeuviolet** [comment]
Lỗi này hình như chỉ chạy Localhost mới dính.
