### ISSUE TITLE
Lỗi khi sửa ảnh đại diện của user:

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1111]
phiên bản: 4.0.20
sau khi chọn ảnh thì không hiện thêm gì, vẫn giữ nguyên màn hình chọn ảnh

**Comment by thehung** [comment]
Giống lỗi này https://github.com/nukeviet/nukeviet/issues/1100

**Comment by hongoctrien** [comment]
@htuyen1994 pull lại code xem hết chưa nhé.
Mình nghĩ có liên quan đến cái này (đã fix) https://github.com/nukeviet/nukeviet/commit/4cd5ba07ae78f6ae0eb86630abedbf6cd94cb838
