### ISSUE TITLE
Lỗi module user: phần thay đổi câu hỏi bảo mật

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1112]
Phiên bản 4.0.20

phần link không rewrite:
http://localhost/nukeviet-dev/index.php?language=vi&nv=users&op=editinfo&changequestion

phần nội dung bị lỗi layout:

![image](https://cloud.githubusercontent.com/assets/10300770/8506139/8344ffdc-222f-11e5-9206-04c17f514618.png)

**Comment by anhyeuviolet** [comment]
Link chưa Rewrite 
Còn layout thì mình thấy bình thường.
![1](https://cloud.githubusercontent.com/assets/6290970/8506208/aaae408e-2233-11e5-95f3-0636c0d44b59.PNG)

**Comment by hongoctrien** [comment]
``` html
<script type="text/javascript" data-show="after">
	$(document).ready(function() {
		$('#changeQuestionForm').validate();
	});
</script>
```
Ai code thiếu mất cái thẻ đóng </script> :v

Fixed: https://github.com/hongoctrien/nukeviet/commit/e6738a33999c1f74463fe7c791b94ffc853a0661

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/caafbe6b1ffffd0c8e2a9d76b85c972ad4eb0aab
