### ISSUE TITLE
lỗi chức năng tìm kiếm tại module tìm kiếm:

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1113]
Phiên bản 4.0.20

khi tìm kiếm tại module tìm kiếm thì click chọn tìm kiếm màn hình chuyển về trang chủ không hiển thị kết quả tìm kiếm

**Comment by anhyeuviolet** [comment]
Mình ko thấy lỗi này như của bạn. :D

**Comment by htuyen1994** [comment]
a vào chọn menu tìm kiếm trên menu thì sẽ thấy

**Comment by anhyeuviolet** [comment]
Tức là URL này phải ko bạn ?
/seek/

Nếu thế thì mình test cả trong modules đó cũng như cái ô tìm kiếm trên banner đều hoạt động mà.

**Comment by htuyen1994** [comment]
bản mới nhất a nhé

**Comment by anhyeuviolet** [comment]
:D thì mình đang test bản mới nhất mà ......
bạn ghi chú bên trên là 4.0.20 nên mình cài mới rồi kiểm thử mà :(

**Comment by hongoctrien** [comment]
Mình cũng không thấy lỗi gì @htuyen1994
