### ISSUE TITLE
Lỗi giao diện khi tìm kiếm nâng cao mục tin tức:

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1114]
phiên bản 4.0.20

trình duyệt: chrome

![image](https://cloud.githubusercontent.com/assets/10300770/8506174/abc85a10-2231-11e5-9a7e-a6b69e414922.png)

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/fe51a11d1957e132a468ecb92158924566a86449
