### ISSUE TITLE
Lỗi js khi vào chuyên mục của module news

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1117]
![image](https://cloud.githubusercontent.com/assets/10300770/8506360/1f5dfc7a-223a-11e5-946b-1b05446e71bf.png)

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/nukeviet/commit/4cd5ba07ae78f6ae0eb86630abedbf6cd94cb838
