### ISSUE TITLE
Lỗi cài đặt 

### ISSUE THREAD

**Issue by vinhntgroup** [nukeviet/nukeviet#1118]
Mình cài đặt tới bước 3 thì báo lỗi:
![image](https://cloud.githubusercontent.com/assets/9718682/8506597/a8be0684-2246-11e5-95be-c25369157955.png)

**Comment by thehung** [comment]
Bạn cung cấp thông tin môi trường thử nghiệm nhé. Xem hướng dẫn tại đây: https://github.com/nukeviet/nukeviet/blob/master/CONTRIBUTING.md

**Comment by hongoctrien** [comment]
Lỗi này do hệ thống tâp tin của bạn chưa được chmod đúng.
Bạn kiểm tra lại chmod ạ.

**Comment by vinhntgroup** [comment]
Mình đã tìm ra nguyên nhân rồi, k hiểu sao giải nén trong acp lại thiếu file .htaccess :)
