### ISSUE TITLE
Không chuyển đổi được giao diện mobi sang máy tính và ngượi lại.

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#1119]
NukeViet 4.0.19 lỗi không chuyển đổi được giao diện mobi sang máy tính và ngượi lại khi sử dụng trình duyệt Chrome trên di động Android. Trình duyệt mật định của máy thì vẫn chuyển được.
Web url thử nghiệm: http://thienkhiem.com

**Comment by thehung** [comment]
Lỗi này đã được fix rồi mà.
Anh test trên bản mới nhất ở đây nhé: https://github.com/nukeviet/nukeviet/tree/develop
(Chú ý ghi lại commit hoặc thời gian tải để tiện report).
