### ISSUE TITLE
Dùng từ tiếng anh chưa chuẩn

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1120]
ở file includes/class/optimezer.class.php
Chữ optimezer tiếng anh phải là optimizer mới đúng chính tả.
Đây không phải là lỗi nhưng mình xin góp ý để sửa nó cho chuẩn xác hơn. không chỉ người việt nam mình dùng mà quốc tế còn dùng nữa

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/fa106ebe82d59e16c68f1efc014ae740fce9934d
