### ISSUE TITLE
Không nhảy Đường dẫn liên kết của module trong Menusite

### ISSUE THREAD

**Issue by mrvik14** [nukeviet/nukeviet#1122]
![2015-07-04_175322](https://cloud.githubusercontent.com/assets/12641276/8507843/9296d690-227f-11e5-8f30-7c493e06951a.png)

**Comment by hongoctrien** [comment]
Bạn thử với những module khác xem được không ạ?
Nếu vẫn lỗi, bạn down lại code mới nhất rồi test lại nhé.
Mình đang test trên code mới nhất thì không thấy lỗi này.

**Comment by mrvik14** [comment]
Bản mới nhất trên github ạ, ko hiểu sao vẫn bị :(

**Comment by vuthao** [comment]
Bạn thử lại bản này xem còn lỗi không nhé:  https://github.com/nukeviet/nukeviet/archive/develop.zip

Nếu còn lỗi bạn hãy đọc hướng dẫn sau: 
https://github.com/nukeviet/nukeviet/blob/master/CONTRIBUTING.md
