### ISSUE TITLE
Đặt hàng vẫn bị giới hạn khi chọn 1 nhóm sp cụ thể , ko cập nhập đc giỏ hàng khi thay đổi số lượng

### ISSUE THREAD

**Issue by mrvik14** [nukeviet/nukeviet#1123]
1- Mình để chế độ đặt hàng không giới hạn số lượng rồi tuy nhiên lúc Đặt hàng ngoài site khi chọn 1 nhóm sản phẩm cụ thể vẫn bị báo hết hàng.
 3- Giỏ hàng ko cập nhập lại đc khi thay đổi số lượng 1 sản phẩm.

**Comment by thaotrinhj** [comment]
Nhầm chỗ rồi bạn. Bạn đang nhắc đến module shops thì vào chủ đề shop mà đắng ý kiến
https://github.com/nukeviet/module-shops/issues
