### ISSUE TITLE
Lỗi không chọn được ảnh cho bài viết trong quản lý ảnh

### ISSUE THREAD

**Issue by macsoftnet** [nukeviet/nukeviet#1124]
Khi mình up ảnh lên rồi như khi click chọn ảnh thì không chọn được.
Ở trong bài viết, page, block html đều không được.

**Comment by hongoctrien** [comment]
Lỗi này đã được fix tại https://github.com/nukeviet/nukeviet/commit/4cd5ba07ae78f6ae0eb86630abedbf6cd94cb838
Bạn dơwnload code mới nhất về test lại xem nhé.
