### ISSUE TITLE
Lỗi xuất hiện ký tự xuồng dòng trong phần giới thiệu ngắn gọn (v4.0.21)

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#1127]
Khi copy bài viết dưới dạng xuống dòng dán vào khung Giới thiệu ngắn gọn. Ra trang chủ xuất hiện ký tự xuống dòng (<br />)
![777](https://cloud.githubusercontent.com/assets/11238423/8510064/e0cf37a8-22f7-11e5-956f-4d2460e66ccf.png)
Mình tạm thời pix lỗi trên như sau:
Tạm thời đã pix lỗi mã thẻ <br /> ở giới thiệu ngắn gọn trong new
Mở file: module/new/admin/content.php tìm đoạn:
$rowcontent['hometext'] = $nv_Request->get_textarea( 'hometext', '', 'br', 1 );
và xóa biến: 'br'
![01](https://cloud.githubusercontent.com/assets/11238423/8510069/1b26e48c-22f8-11e5-9368-861165da9300.png)
Mong đội coder xem thêm. Thank!

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/f840192fb05e105a6e8e2b719f7a332ce10ad137

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/24ed5b783d87519cf6b1fb0323ee698f0d2c6570
