### ISSUE TITLE
Lỗi trắng trang khi thay câu hỏi bảo mật ngoài Front-end

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1128]
Phiên bản : 2d992a54ce2994e7590b449af72d4d6d29c1ea0c
Branch Develop
XAMPP 1.8.3

Lỗi trắng trang khi truy cập 
http://localhost/nuke/users/changequestion/

Thông báo lỗi : 
Warning: require(C:/xampp/htdocs/nuke/modules/users/funcs/changequestion.php): failed to open stream: No such file or directory in C:\xampp\htdocs\nuke\index.php on line 293

Fatal error: require(): Failed opening required 'C:/xampp/htdocs/nuke/modules/users/funcs/changequestion.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\nuke\index.php on line 293

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/3ceb5fcb6dbc89955f87af6b265e613e32729a8c
