### ISSUE TITLE
Thêm cấu hình block bật/tắt thời gian ở menu bootstrap

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1129]

**Comment by hoaquynhtim99** [comment]
Có nhất thiết phải rờm rà đến thế đâu

**Comment by hongoctrien** [comment]
Bữa giờ nhiều người hỏi về vấn đề bỏ thời gian ở menu đi lắm.  Cứ phải hướng dẫn sửa code.
Menu nhiều cái là cái tgian nó đẩy xuống. Chiếm diện tích.
