### ISSUE TITLE
 Module video-clip 3.4.07-và cài module-shops-4-rc

### ISSUE THREAD

**Issue by nvbqng1980** [nukeviet/nukeviet#1130]
Mình cài Module video-clip 3.4.07-07/07/2015 hoaquynhtim99 (phantandung92@gmail.com) trên nukeviet 4.0.21 RC khi vào trang quảng trị thì trắng trang. làm thế nào để hiển thị vây ace.
và cài module-shops-4-rc thông báo là cấu trúc thư mục không phù hợp.

**Comment by anhyeuviolet** [comment]
Nói chung là modules bạn cài sai phiên bản ( không tương thích ) với phiên bản NukeViet. Và bản RC còn chưa được phát hành, nên lỗi này là không tránh được.
Vui lòng đợi đến khi các modules trên có phiên bản cập nhật phù hợp cho NV4.x

**Comment by vuthao** [comment]
@nvbqng1980  bạn cứ kêu lỗi, bạn hãy đặt mình vào vị trí người hỗ trợ muốn kiểm tra có lỗi hay không thì sẽ phải làm ghì nhé.

Vui lòng đọc nội dung: Please review the guidelines for contributing to this repository. khi tạo issues, sau đó tạo issues khác nhé.
