### ISSUE TITLE
Nukeviet 4.0.21 Phần Thiết lập giao diện bị lỗi tab

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#1133]
Trong Nukeviet 4.0.21 Phần Thiết lập giao diện bị lỗi tap không chuyển đổi tab. 
Khi vào Phần Thiết lập giao diện có link 
/index.php?language=vi&nv=themes&op=config
Khi link vào các tab Toàn trang, Nội dung, Khối block, Đầu trang, Chân trang, CSS thì có link url dạng
/index.php?language=vi&nv=themes&op=config#tab1
/index.php?language=vi&nv=themes&op=config#tab2
/index.php?language=vi&nv=themes&op=config#tab3
/index.php?language=vi&nv=themes&op=config#tab4
/index.php?language=vi&nv=themes&op=config#tab5

Nói chung tất cả các tab điều chỉ nằm trên 1 trang, không phân trang như ở Nukeviet 4.0.20
Gặp lỗi trên môi trường
localhost Nukeviet 4.0.20 Bình thường
localhost Nukeviet 4.0.21 Bị lỗi
Hosting web  Nukeviet 4.0.20 Bình thường
Hosting web  Nukeviet 4.0.21 Bị lỗi
![thi t l p giao di n](https://cloud.githubusercontent.com/assets/8376014/8543165/1d79314e-24c5-11e5-85d4-808f782cdf38.jpg)

**Comment by NukeVietCMS** [comment]
Thời gian tải code là: 1:28 AM 7/7/2015

**Comment by anhtunguyen** [comment]
Lỗi này do bộ lọc các comment của JS chưa tốt.
Tôi sẽ fix bây giờ.

**Comment by vuthao** [comment]
Tạm thời bạn tắt tính năng tối ưu site đi.
Phiên bản tới chúng tôi sẽ sửa lại phần này.

**Comment by NukeVietCMS** [comment]
Tạm thời thì như vậy cũng được.
