### ISSUE TITLE
Bất cập khi thay đổi "Quyền hạn module hệ thống"

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1134]
ACP/Tài khoản/Quản trị/Quyền hạn module hệ thống.
Đang login bằng tài khoản tối cao, vô tình bỏ chọn module “authors” ở cột “Quản trị tối cao”, lưu lại thì không truy cập được, muốn kích họat lại phải vào thay đổi CSDL.
Đề xuất không cho tắt module này.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/6861dca6c233b66582de3191ab3876bc35159e2c
