### ISSUE TITLE
Trang request liên tục do không kết nối được với facebook hoặc google

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1135]
Trong trường hợp máy tính thuộc mạng LAN được phép truy cập internet nhưng có hạn chế truy cập các trang mạng xã hội, lúc này xảy ra hiện tượng hệ thống gởi request liên tục (favicon quay liên tục).

Thêm một lỗi nữa là khung request trang facebook.com là http nhưng facebook trả về một khung là https. -> xem hình
![https](https://cloud.githubusercontent.com/assets/6806295/8547179/6d85ea84-24e7-11e5-964b-3fa0a66dec3e.PNG)

**Comment by hoaquynhtim99** [comment]
Cái này hình như không liên quan đến NukeViet thì phải nếu mạng của bạn chặn mạng xã hội và bạn muốn website của bạn chị chạy trong bạn nội bộ thì bạn có thể vào cấu hình module news để bỏ chọn "Hiển thị các công cụ Like facebook, G+, Twitter khi xem bài viết"

**Comment by phongaz** [comment]
Ở đây có 2 đối tượng: 
1:  The frame requesting access là site của mình
2. the frame being accessed là Facebook
Nó yêu cầu cả thằng yêu cầu và và thằng đáp lại phải có cùng protocol thì mới access được.

Chả nhẽ tất cả các site phải mua SSL thì mới hết lỗi này nhỉ???
![protocol request unmatched](https://cloud.githubusercontent.com/assets/6806295/9011030/e6386e16-37d4-11e5-940f-a57914d794f3.PNG)
