### ISSUE TITLE
Lỗi khi quản trị chung của Site

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#1136]
![2015-07-08_13-55-58](https://cloud.githubusercontent.com/assets/8481170/8564736/1d34ad8a-2579-11e5-9d9a-31203efcea15.jpg)

Khi quản trị chung đăng nhập site và vào modules Thống kê(statistics)

 Thông báo từ Hệ thống
Lỗi cảnh báo	Lỗi cảnh báo: constant(): Couldn't find constant BROWSER_UNKNOWN in file /modules/statistics/theme.php on line 578
Lỗi cảnh báo	Lỗi cảnh báo: constant(): Couldn't find constant PLATFORM_UNSPECIFIED in file /modules/statistics/theme.php on line 617
PS: Site mới update từ NukeViet 4018 lên 4021. Lúc trước không thấy có lỗi đó

**Comment by vuthao** [comment]
Lỗi liên quan đến nâng cấp bạn thảo luận tại trang nâng cấp nhé.

**Comment by hongoctrien** [comment]
Lỗi này không liên quan đến nâng cấp.
NukeViet mới nhất đến thời điểm này cũng lỗi.

**Comment by hoaquynhtim99** [comment]
@hongoctrien kiểm tra giúp lỗi từ đâu, hiện tại bản dev mới nhất chạy trên window với php 5.5 không thấy lỗi
