### ISSUE TITLE
Bị lỗi trong phần admin

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#1137]
Khi nâng cấp từ 4.0.18 lên 4.0.21 trên localhost thì bình thường nhưng khi làm trên web bị lỗi như sau:
+ Không hiển thị hệ thống modules
![2015-07-08_15-11-42](https://cloud.githubusercontent.com/assets/8481170/8565947/6c8f3476-2584-11e5-9c86-75e1fc3c751f.jpg)
+ Không sửa, thêm mới được các block
![2015-07-08_15-12-52](https://cloud.githubusercontent.com/assets/8481170/8565953/81d2bc7c-2584-11e5-83c0-047c137461c7.jpg)
Đây là cấu hình php trên web
![2015-07-08_15-13-42](https://cloud.githubusercontent.com/assets/8481170/8565957/914b197e-2584-11e5-956b-08e459b4a6a0.jpg)

**Comment by anhyeuviolet** [comment]
Lỗi này anh gửi lên khu vực hướng dẫn nâng cấp có lẽ phù hợp hơn !
