### ISSUE TITLE
Lỗi cài đặt ( tự động chuyển ngữ khi cài đặt)

### ISSUE THREAD

**Issue by thucvinh** [nukeviet/nukeviet#1138]
Khi cài đặt, đã chọn ngôn ngữ tiếng việt, đến bước 4 tự động nó chuyển sang tiếng anh. Nếu tiếp tục cài đặt. Thì vẫn thành công, nhưng giao diện bị vỡ và toàn trang đều tiếng anh.

Link thử nghiệm: http://yeunuke.tieplua.net/

Môi trường thử nghiệm:

- Phiên bản NukeViet: 4.0.21
- Môi trường thử Nghiệm: hosting
- Máy chủ web:  PHP 5.3.27/ Apache 2.4.7/MySQL 5.5.35/ 

Trên localhost thì không chuyển ngữ tiếng việt được luôn. Cài đặt bằng tiếng anh thì giao diện không bị vở, nội dung site bằng tiếng anh

Môi trường thử nghiệm:

- Phiên bản NukeViet: 4.0.21
- Môi trường thử Nghiệm: hosting
- Máy chủ web: XAMPP 5.6.8, hệ điều hành win7

**Comment by vuthao** [comment]
Bạn có thể ghi lại video lúc cài đặt trên host được không.

**Comment by thucvinh** [comment]
https://www.youtube.com/watch?v=Tl5mzRWrkT0

**Comment by hoaquynhtim99** [comment]
Bạn tải bản mới nhất xem có lỗi không nhé

**Comment by thehung** [comment]
Tôi thử trên bản mới nhất https://github.com/nukeviet/nukeviet/commit/309075b2e596730d03df930d8e1d7d61c5e28d14 không thấy lỗi này. 

@thucvinh test giùm trên bản mới nhất xem có bị không, nếu có bạn gửi thông tin hosting và tài khoản thử nghiệm vào admin@nukeviet.vn để đội code test thử nhé.

Tạm thời tôi đóng issue này lại. Nếu bạn có thông tin mới hơn thì cập nhật lại trạng thái issue này thành open nhé!
