### ISSUE TITLE
Menu bootstrap vẫn responsive khi ở chế độ máy tính

### ISSUE THREAD

**Issue by buiqthong** [nukeviet/nukeviet#1140]
Hiện tại menu vẫn responsive khi hiển thị ở cả hai chế độ tự động và máy tính. Trên máy tính thì menu nên cố định.

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/nukeviet/commit/f8d8106e052f3bde1bcb117c08c9f870c87127e7
