### ISSUE TITLE
NV 4.0.21 không thấy tạo folder menu trong uploads

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/nukeviet#1141]
=> Browse ảnh không vào module menu mà ở upload
=> Khi save bị lỗi tên.

**Comment by vuthao** [comment]
bạn tao thư mục uploads/menu, sau đó kich lại nút cập nhật lại module để hệ thống nhận
fixed: https://github.com/nukeviet/nukeviet/commit/e668a0f446c7834a2e1329835621cd176514637d
