### ISSUE TITLE
Nút bình luận bị đơ không bấm được 4.0.21

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/nukeviet#1142]
Localhost
Apache Version	Apache/2.4.4 (Win32) PHP/5.4.16
Trinh duyet Chroom 
Win 8

**Comment by hoanglongvnpt** [comment]
Không xác nhận lỗi này. Mình vẫn dùng bình thường mà bạn.
![01](https://cloud.githubusercontent.com/assets/11238423/8610793/44db1cc0-26e1-11e5-9970-5cae8b9a4918.png)

**Comment by anhyeuviolet** [comment]
Mình cũng không thấy lỗi này, dù phần comment mình đã sửa nó banh che rồi.

**Comment by anhutbeo** [comment]
Mình down bản develop mới nhất thì bị, nhưng bản gốc 4.0.21 thì bình thường, bản mới nhất thì thấy tất cả các nút bấm đều không được chứ kg riêng gì bình luận. Thanks 2 bạn

**Comment by hoaquynhtim99** [comment]
@anhutbeo  Bạn tải lại bản dev sau commit này xem còn lỗi không https://github.com/nukeviet/nukeviet/commit/ff6fba1478edd5678833800c30472df658b5c95f

**Comment by hoaquynhtim99** [comment]
Cái này đã được sửa, mình xin được đóng báo lỗi này
