### ISSUE TITLE
url vẫn chưa hoàn thiện

### ISSUE THREAD

**Issue by nethoabinh** [nukeviet/nukeviet#1143]
em check bản mới nhất
tùy chọn chỉnh url về chữ thường của bài viết được rồi
nhưng mà tên của chuyên mục vẫn có chữ in hoa trên URL 
ảnh demo
mong các anh fix sớm
![repot](https://cloud.githubusercontent.com/assets/6945379/8604525/5493832e-26a9-11e5-9d2a-59c5ac208ef4.PNG)

**Comment by nethoabinh** [comment]
em đề xuất tiếp là có tùy chọn bỏ chữ /vi/ và tên modeul
chỉ để dạng tiêu đề domain.com/ten-baiviet.html
thanks

**Comment by nethoabinh** [comment]
Tại vì sao người ta dùng wordpress nhiều vì nó seo quá tốt và có tùy chỉnh url tùy biến, mong rằng nukeviet ngày càng phát triển :)

**Comment by nethoabinh** [comment]
Theo ý kiến em sẽ có tùy chọn URL như wordpress cho người dùng chọn
1- Domain.com/catagery/ten-bai-viet.html
2- domain.com/ten-bai-viet.html
3 - domain.com/vi -en/module/ten-bai-viet.html
làm như thế thì cho anh em thoải mái hơn trong việc lựa chọn url và cũng kích thích người dùng nukeviet , vì hiện tại đội ngũ support trong forum hơi nghèo nàn nên mình phải hoàn thiện sản phẩm đề người dùng thích luôn không chỉnh sửa nhiều nữa.
Em sẽ quay lại nukeviet và góp ý nhiều
không hứa giúp nuke tốt hơn wordpress nhưng sẽ ít nhất là ngang = wordpress để lôi kéo người dùng

**Comment by thehung** [comment]
VI đã có cấu hình bỏ được rồi (nếu bạn chỉ sử dụng một ngôn ngữ.

Đoạn có chữ in hoa là tên chuyên mục. Hoa hay thường người quản trị có thể
tùy chỉnh khi sửa chuyên mục.

**Comment by nethoabinh** [comment]
trời đã có cấu hình anh phải cho nó tự động chứ ạ, đã gọi tự động mà đi sửa bằng tay thì nói gì anh?

**Comment by hoaquynhtim99** [comment]
@nethoabinh : Cái chữ Tin-tuc của bạn là dữ liệu mẫu lúc cài đặt website, bạn có thể cài lại module để xóa toàn bộ dữ liệu mẫu và thêm lại, lúc này sẽ tùy theo cấu hình mà bạn chọn, hoặc là tự sửa bằng tay như @thehung trình bày ở trên. Cái này không liên quan gì đến tự động hay bằng tay gì như bạn hiểu.

Còn muốn dạng url như wordpress mời bạn sử dụng một module khác chẳng hạn như module bloghttp://nukeviet.vn/vi/store/modules/blog/ khi đó nếu bỏ tên module trên đường dẫn bạn sẽ có một URL dạng http://dungpt.vinades.net/mach-led-nhap-nhay-theo-nhac-28-vu-led.html còn cái này là module news nó sẽ như vậy không thể thay đổi.

**Comment by thehung** [comment]
Cái đó là người post dữ liệu demo cố tình để như thế làm demo.

**Comment by anhyeuviolet** [comment]
@nethoabinh 
Không phải cái gì tự động cũng tốt. 
Dữ liệu mà bạn đưa ảnh lên là dữ liệu demo. Bạn có thể cấu hình để tự động tạo các alias sau này dạng chữ viết thường. Chính như WP mà bạn nói, phần alias cũng cho phép chỉnh sửa alias của các chuyên mục, tags, taxonomy ... nói cách khác là nó cũng tự động ở mức như NV hiện tại mà thôi.

Nếu nói về bỏ URL trong link của WP, mình nói ko biết bao nhiêu lần rồi.
01/ Wordpress dùng cấu trúc đơn modules cho core của họ. Nên mặc định có thể xoá các phần tên ra khỏi URL. Nhưng nếu bạn cài thêm, như WooCommerce chẳng hạn ? Bạn có từng thử tìm cách xoá cái alias /product/ trong URL gian hàng của nó đi chưa và khả thi không ?
02/ Trước đây, NV có cho phép kích hoạt hoặc ko kích hoạt chức năng rewrite. Ngoài ra hiện phần URL end có thể chỉnh sửa được trong config_global. Cái này nếu đưa nó lại trong cấu hình chung thì hoàn toàn phù hợp và đủ cho ý kiến của bạn bên trên. Không phải NV không có mà là đã tối ưu sẵn cho người dùng khỏi rối mà thôi.
03/ Hy vọng bạn có thể hỗ trợ trên diễn đàn nhiều hơn. Đội ngũ phát triển hiện đang chuyên tâm vào phát triển. Sức mình thì có hạn nên hỗ trợ cũng có hạn. Hy vọng tương lai sẽ có nhiều người cùng đóng góp hơn nữa.

**Comment by nethoabinh** [comment]
cái này là em xóa tất cả bài viết, các chuyên mục em xóa hết. em add lại từng chuyên mục nhưng URL của nó không thu lại bình thường
 - không phải là Chuyên mục DEMO nha
Anh cứ thử thêm tên chuyên mục mới mà xem, dù rằng đã tích vào cấu hình module là thu về chữ thường rồi, tự nó vẫn sinh ra CHữ Hoa trên URL, cái này thì đơn giản thôi, nhưng từ những cái nhỏ mới ra cái lớn. em thấy chủ yếu phục vụ cho người mới làm web là chính chứ
- GÓP Ý THÊM LÀ CHỖ TIN TỨC NÊN ĐỂ MỘT CÁI NÚT ĐĂNG BÀI VIẾT MỚI Ở BÊN GÓC PHẢI, BÂY GIỜ CỨ ĐĂNG BÀI VIẾT MỚI LẠI DI CHUỘT RA BÊN GÓC TRÁI MẤT THỜI GIAN.

**Comment by anhyeuviolet** [comment]
Bạn chỉnh cái này chưa ?
![url](https://cloud.githubusercontent.com/assets/6290970/8614515/816411b4-2714-11e5-890c-339a3198c56e.PNG)

**Comment by nethoabinh** [comment]
- Mình chỉnh rồi nhé
Lỗi gì , bản mới nhất mà?
bạn mới dùng nukeviet à?
