### ISSUE TITLE
[Hỏi] Test như thế nào?

### ISSUE THREAD

**Issue by andytruong** [nukeviet/nukeviet#1144]
Em thấy các bác mới release 4 beta 7. Em không rõ các bộ test tự động các bác chứa ở đâu để em xem sơ qua ạ. 

Có vài câu khác em muốn hỏi:

- Dữ liệu người dùng upload lên, NV lưu trữ ở đâu ạ? Có hỗ trợ S3 không ạ?
- Sao NV không hỗ trợ composer?
- NV autoload class ntn? Có sử dụng PSR-4 không?
- NV có kệ hoạch hỗ trợ PSR-7 không?
- Có thể sử dụng NV làm backend cho mobile app được không?
- NV có chạy tốt với PHP 7 không?

Cảm ơn các bác ạ.

**Comment by vuthao** [comment]
Mình xin trả lời các câu hỏi của bạn như sau:
- Hiện tại NukeViet chưa có bộ test tự động.
- Dữ liệu người dùng upload lên, lưu trữ tại hosting.
-NukeViet là mộ bộ hoàn chỉnh, bạn checkout qua git hoặc download và dùng luôn, nên không cần composer
- NukeViet dùng hàm spl_autoload_register của PHP để autoload class, các class lưu trữ tại: includes/class/class_name.class.php
- Hiện tại NukeViet mới kiểm tra cho PHP 5.3, 5.4, 5.5, 5.6 (đang bị lỗi trong thư viện oAuthLib). PHP 7 chưa ra bản chính thức nên chúng tôi chưa kiểm tra.
- NV làm backend cho mobile app được không ? Việc này hòan toàn có khả năng, chúng tôi cũng dự định làm việc này cho các dự án triển khai trong thời gian tới.

**Comment by vuthao** [comment]
@andytruong bạn có thể hỗ trợ, hoặc hướng dẫn chúng tôi xây dụng bộ test tự động.
Trước kia tôi có làm bằng Autoit để test cho NukeViet 3.  Nhưng giờ NukeViet 4 đã thay đổi toàn bộ nên không dùng được nữa.

**Comment by andytruong** [comment]
Cảm ơn bạn nhiều.
