### ISSUE TITLE
Hỏi bộ đếm khi xem bài viết không thay đổi (New)

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#1145]
Mặc dù bài viết đã
 được xem nhiều lần và trên nhiều máy khác nhau, tuy nhiên nó không tăng lên, hoặc nếu có tăng cũng chỉ lên 1 hoặc 2 mà thôi.
![02](https://cloud.githubusercontent.com/assets/11238423/8610833/e7dd2166-26e1-11e5-9117-62177b209554.png)

**Comment by anhyeuviolet** [comment]
Bộ đếm có cơ chế đếm theo thời gian nhất định để tránh bị trùng. 
Bạn thử mở chế độ ẩn danh của trình duyệt, click xem tin xem nó có tăng lên ko nhé.

**Comment by hoanglongvnpt** [comment]
Đã kiểm tra nhưng số lượng view cao nhất vẫn là 2

**Comment by anhyeuviolet** [comment]
:d mình chịu !
Mình test bản NV của mình ko hề bị nhá !

**Comment by vuthao** [comment]
Bạn xem trong admin số đếm sẽ tăng nhé.
bên ngoài site không phải là admin, thì dữ liệu được cache, bạn thêm, sửa bài, hoặc xóa cách thì các dữ liệu này mới cập nhật lại.

**Comment by hoanglongvnpt** [comment]
Đã xem rất nhiều để test bộ đếm. Nhưng vẫn không thay đổi ngoài 2 con số: 1 và 2 kể cả ngoài site và trong admin
![1](https://cloud.githubusercontent.com/assets/11238423/8632012/4591a9aa-27b2-11e5-89a5-cef70ce01926.png)

**Comment by anhyeuviolet** [comment]
Tình hình là mới cài lại 4.0.21 sạch sẽ và thấy bộ đếm bình thường. :D

**Comment by thehung** [comment]
Tôi đã cài lại bản mới nhất https://github.com/nukeviet/nukeviet/commit/309075b2e596730d03df930d8e1d7d61c5e28d14 để test (trên local - VertrigiServ 2.30) nhưng không thấy lỗi như report. 

Tôi thử truy cập bài "Mã nguồn mở NukeViet giành giải ba Nhân tài đất Việt 2011" trực tiếp 1 lần, Open link in New Private Windows 1 lần, truy cập trong Chrome 1 lần, trong cửa sổ riêng tư của Chrome 1 lần, truy cập bằng Opera lần nữa, xem thống kê thấy 6 lần truy cập (gồm 1 lần truy cập có sẵn). Như vậy là hoàn toàn đúng.

Tôi sẽ đóng issue này lại nhé. Bạn nào có thông tin test mới hơn thì mở lại issue này và cung cấp thêm thông tin nhé!

**Comment by hongoctrien** [comment]
Em nghĩ vấn dề này cũng cần được khắc phục, nếu đã đếm rồi thì không thể theo cache được.
Có thể dùng jquery để cập nhật lại số lượt xem sau khi load xong trang.

**Comment by vuthao** [comment]
Cần đánh đổi giữa tốc độ của site và con số hiển thị bên ngoài site. 
- Nếu muốn số đó luộn cập nhật thì khỏi phải cache. bởi dùng ajax mà tính lại thì không còn ý nghĩ về cache.
- Con số đó phục vụ cho admin là chính.

**Comment by anhyeuviolet** [comment]
Cái này, tạm thời mình nghĩ nên giữ như cũ.
Cơ chế đếm của NV thực ra còn nhiều hạn chế, thông tin chỉ ở mức tham khảo do còn nhiều trường hợp đếm sai, chưa tách bạch bots và người truy cập thực tế. Ngoài ra thì họ truy cập ẩn danh cũng được tính chứ ko phân vùng được.

Thống kê thì đã có người dùng tuỳ chọn chức năng chèn Google Analytics rồi, nên họ nếu cần chuyên sâu và chính xác thì có thể thông qua GA.
Ngoài ra, nhiều mã nguồn mở như WP, Joomla tới phiên bản mà mình biết thì đã ngừng cung cấp bộ đếm như một chức năng đi kèm của core. WP thì cung cấp một bộ đếm khác thông qua máy chủ của họ ( plugin Jetpack thông qua server của Automattic, và cũng cùng JS để đếm lượt truy cập ). 
Nên hiện thời mình nghĩ modules statitics của NV cứ như sẵn có là được.

**Comment by hongoctrien** [comment]
@anhyeuviolet  cái này mình đang nói đến lượt đếm xem bài viết của module news.

@vuthao Thế thì có nên ẩn luôn với khách truy cập không anh, bỏ đi hoặc chỉ admin mới thấy. Vì nếu hiển thị ra như hiện tại mà cache thì cũng ko chính xác. Ở wp em thấy nó cũng gặp vấn đề này, họ có 1 plugin theo kiểu dùng jquery để cập nhật lại lượt xem sau khi load xong trang.

**Comment by anhyeuviolet** [comment]
@hongoctrien  Vậy tức là news dùng một cơ chế đếm khác với toàn trang ? @.@
Mình sẽ tìm hiểu lại cái này.

**Comment by thienhuu** [comment]
fdsfdsfds
