### ISSUE TITLE
Dữ liệu cài đặt cho phần _extension_files

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1146]
Hiện tại phần dữ liệu càì đặt cho bảng _extension_files rất thủ công.
Nên quy định các module cần đưa vào bảng này lúc cài đặt, sau đó quét file tự động theo cấu trúc của module để ghi vào. Để tránh việc mỗi lần thay đổi cấu trúc file, lại phải sửa lại phần dữ liệu này rất mất công.

**Comment by hoaquynhtim99** [comment]
Có lẽ nên xóa cả phần này trừ khi module hoặc ứng dụng gốc của mình có cấu trúc đặc biệt, vì hiện tại hệ thống hỗ trợ đóng gói và xóa các file của ứng dụng theo chuẩn cấu trúc như trước giờ.

**Comment by vuthao** [comment]
update: https://github.com/nukeviet/nukeviet/commit/d97c97713fb39ad41ac36a19d4f40e9b24e0ea79
