### ISSUE TITLE
Ngưng kích họat module nhưng khi thêm block, danh sách module vẫn thấy module đó

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1147]
Ngưng kích họat module nhưng khi thêm block, danh sách module vẫn thấy module đó trong khi ở danh sách block thì không hiển thị danh sách block.

**Comment by hoaquynhtim99** [comment]
Cái này trước giờ nó vẫn vậy mà, thêm vào để đảm bảo khi bật module lại thì block đó sẽ xuất hiện

**Comment by hongoctrien** [comment]
Có cách nào khác không?
Ngưng kích họat rồi mà vẫn còn ở đó là vô lý. Có ở đó nhưng khi chọn lại không hiển thị block lại vô lý nữa. Là chủ ý nhưng cứ như lỗi á. ^^

**Comment by hoaquynhtim99** [comment]
Từ xưa đến nay đâu có ai nhắc tới cái này

Vào 17:15 Ngày 11 tháng 07 năm 2015, Hồ Ngọc Triển <notifications@github.com
> đã viết:

> Có cách nào khác không?
> Ngưng kích họat rồi mà vẫn còn ở đó là vô lý. Có ở đó nhưng khi chọn lại
> không hiển thị block lại vô lý nữa. Là chủ ý nhưng cứ như lỗi á. ^^
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nukeviet/nukeviet/issues/1147#issuecomment-120601226>.
>



-- 
Programmer
Phone: +84 167 786 5866
Website: http://dungpt.vinades.net/
Facebook: https://www.facebook.com/tandung1912
