### ISSUE TITLE
bỏ đuôi index.php cho tên url

### ISSUE THREAD

**Issue by huynhlam088** [nukeviet/nukeviet#1148]
đề nghị bỏ đuôi index.php trong thư mục cũng như bài viết nhằm rút gọn url hơn và lỗi backup wa host khác là trang trắng link url ví dụ http://tanphivan.info/index.php/ve-quoc-te/

**Comment by hoaquynhtim99** [comment]
NukeViet trước giờ đã có thể bỏ cái đó lâu rồi, bạn kiểm tra lại hosting của bạn có hỗ trợ rewrite không? nếu không có thì không thể bỏ được cái đó
