### ISSUE TITLE
Cài lại module

### ISSUE THREAD

**Issue by vinhntgroup** [nukeviet/nukeviet#1149]
Tại sao khi thực hiện cài lại module lại không xóa hết các file đã upload từ trước luôn?

**Comment by anhyeuviolet** [comment]
thường khi cài lại thì nó chỉ drop bên Database mà thôi.
Muốn xoá hết cả file thì phải xoá modules đó trong quản lý modules, sau đó vào phần quản lý mở rộng và xoá nó đi mới được.

**Comment by hoaquynhtim99** [comment]
Xóa hết file UPLOADS thì cần xóa module trong phần quản lý module, còn vào phần quản lý ứng dụng để xóa thì nó xóa cả code của module đó luôn, cẩn thận
