### ISSUE TITLE
Xin góp ý về new của v4.0.21

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#1152]
Theo mình ở chế độ hiển thị Theo danh sách mới lên trên thì nên bỏ phần các tin khác, lý do đã có phân trang cho new. (vì các tin khác đã nằm ở page tiếp theo).
![1](https://cloud.githubusercontent.com/assets/11238423/8665048/a5a00626-2a09-11e5-839e-1b13680ef209.png)

**Comment by anhyeuviolet** [comment]
Có lẽ cấu hình bật tắt chắc là hợp lý.
Dù thế thì phần này mình thường cấu hình tin liên quan là 0.

**Comment by hoanglongvnpt** [comment]
Nếu được cấu hình cho phép trong cấu hình module thì quá hay.

**Comment by vuthao** [comment]
đây là chủ đích của người thiết kế, tối ưu việc hiển thị link, các bạn không thích tự sửa lại nhé.

**Comment by hoanglongvnpt** [comment]
Đúng là thừa code trong khi cần phát triển cái khác thì không?! @vuthao xem lại cách trả lời cho cộng đồng như thế! còn nếu mình không thích thì mình xóa quách cho xong, mất công góp ý làm gì cho mất time?!

**Comment by anhyeuviolet** [comment]
@hoanglongvnpt Bạn cứ bình tĩnh.
Anh @vuthao  nói đúng chứ ko sai.
Cái đó người dùng chỉnh lại trong theme.php rất đơn giản, có thể ghi đè thuộc tính của modules được.
Do đó chưa phải gấp rút thêm chức năng này, chưa kể đến việc có người dùng muốn có tính năng này thì sao ? :D

**Comment by hoanglongvnpt** [comment]
Chưa thì bảo chưa cần. Không nên trả lời với cộng đồng một câu nhạt như nước ốc vậy. Tớ xóa đoạn coder đó đi thì cần gì phải góp và chả ý.?

**Comment by vuthao** [comment]
@hoanglongvnpt @anhyeuviolet tôi chỉ nêu quan đểm cá nhân, và tôi đã ghi nhận góp ý của bạn, đánh dấu trạng thái là future, để xem xét trong bản kết tiếp.
Để tránh việc cãi nhau trên kho code, tôi đã xóa các comment không cần thiết trên kho code. Bỏi đây là nơi báo lỗi và ghi nhận ý tưởng tránh các việc không cần thiết.

**Comment by vuthao** [comment]
Do thiết kế của chức năng tại khu vực này là như thế.
Nếu bạn muốn cách đơn giản nhất là xoá template hiển thị đoạn code đó.
Bởi nếu đưa thêm cấu hình vào sẽ quá nhiều cấu hình trong news.
