### ISSUE TITLE
Module Thăm dò ý kiến

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#1153]
Sau khi bình luận và tiến hành xem kết quả thì hiển thị bảng thống kê chi tiết với tiêu đề from là Đặt hàng là sao ta?
![3](https://cloud.githubusercontent.com/assets/11238423/8666095/5df7b26c-2a16-11e5-8b2e-5f896ede41c8.png)

**Comment by thehung** [comment]
Bạn cho biết tên phiên bản, vị trí test nhé. Nếu có thể nên chụp ảnh full màn hình bao gồm cả địa chỉ trang. Mình nghi là lỗi này do bạn cài nhiều module hoặc block khiến nó truyền tham số khác vào đây vì mình test bản mặc định không thấy lỗi này.
