### ISSUE TITLE
Cần chỉ ra link dẫn đến trang "kích hoạt chức năng đa ngôn ngữ"

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1154]
NukeViet 4.0.20

Khi cài đặt ngôn ngữ mới trong trạng thái chưa kích hoạt chức năng đa ngôn ngữ sẽ nhận được thông báo:

 > Để thêm mới ngôn ngữ dữ liệu, bạn cần kích hoạt chức năng đa ngôn ngữ, để download ngôn ngữ mới truy cập website [Ngôn ngữ cho NukeViet 4] (http://translate.nukeviet.vn)

Cần chỉ chỗ cho người ta biết chức năng đa ngôn ngữ được kích hoạt ở đâu!

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/b8a84ace0d281cf79a991dec23d175be0a55813b
