### ISSUE TITLE
Vỡ logo NukeViet trên giao diện default; trên giao diện mobile logo bị chìm vào background.

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1155]
Ảnh logo NukeViet https://github.com/nukeviet/nukeviet/commit/309075b2e596730d03df930d8e1d7d61c5e28d14 có chiều cao nhỏ hơn 80px. Việc trình bày logo trên giao diện default kéo giãn tới 80px chiều cao khiến logo bị vỡ.

Trên giao diện mobile_default logo này bị chìm nghỉm trong background màu xanh.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/c30195e51ff440954e2e1f21f45d86916dea3d9f
