### ISSUE TITLE
Chức năng tự động nhận keyword nên có tùy chọn nhận keyword từ từ điển hay từ các keyword có sẵn

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1156]
Hiện tại nếu bài viết được tự động tạo keyword thì hệ thống sẽ tự động lấy keyword từ file [/includes/keywords/vi.php] (https://github.com/nukeviet/nukeviet/blob/develop/includes/keywords/vi.php), tuy nhiên từ điển này có nhiều từ không đặc trưng để sử dụng làm từ khóa vì vậy nên có tùy chọn nhận keyword từ từ điển hay từ các keyword có sẵn (tránh phát sinh thêm rác từ khóa đối với những site đã xây dựng được bộ từ khóa riêng).

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/8b11250c4f438a5157afb784e99df81bc04b184a
