### ISSUE TITLE
[Đề xuất] CDN cho các tập tin media

### ISSUE THREAD

**Issue by thaotrinhj** [nukeviet/nukeviet#1158]
Nukeviet 4x đã có Hosting CDN cho css, js
Mình đề xuất tính năng người dùng có thể cài thêm một ứng dụng cho Hosting CDN. Tận dụng các kho lưu trữ lớn như Dropbox, Google Drive, SkyDrive, Copy, Box, Bitcasa, SugarSync, imgur, ... 
Hosting CDN dạng này có rất nhiều nhà cung cấp. Do đó chẳng thể gom hết cùng lúc vào NV mặc định được.  Đội code thiết kế mở rộng thế nào để người dùng sau này có thể lựa chọn cài thêm một ứng dụng CDN mà họ muốn (nếu có).
Ví dụ như các plugin của WP như: Google Picasa Viewer, Google  Drive As WordPress CDN Plugin, jsDelivr - WordPress CDN Plugin, ImageShack Offloader, ... (wordpress.org/plugins/tags/cdn)

**Comment by jamesblackvn** [comment]
Mình có dùng CDN tại VCCLOUD, vào thiết lập chung, Tại mục "Hosting CDN cho javascript, css" mình điền domain CDN của VCCLOUD cung cấp thì thấy nó không thay thế đường dẫn cũ là nukeviet.jamesblackvn.com  thành đường dẫn mới của CDN là nukeviet-jamesblackvn.cdn.vccloud.vn cho các file js và css. 

Đồng thời trường "Hosting CDN cho javascript, css" không lưu giá trị nhập vào ở bước trên.

P/s: Đã thực hiện các thao tác Dọn dẹp hệ thống.

**Comment by vuthao** [comment]
@jamesblackvn 
Việc đường điền đường dẫn này để báo cho trình duyệt lấy các file này tại host CDN.
Còn việc đồng bộ thế nào sẽ phải do host CDN tự thực hiện.
Hoặc bản tải tất cả các file này, upload sang host CDN đó nếu có.

**Comment by vuthao** [comment]
@thaotrinhj 
Các host lưu trữ lớn như Dropbox, Google Drive, SkyDrive, Copy sẽ không cho Trình duyệt truy cập trực tiếp nên nhiều khả năng sẽ không thực hiện được nhé.

**Comment by jamesblackvn** [comment]
@vuthao 
- Việc lấy file đưa vào CDN thì các dịch vụ CDN họ tự động làm rồi, không cần upload gì cả.
- Vấn đề là khi lưu url của CDN vào thì không thấy NukeViet lưu lại và thay thế url tương ứng khi view source.
Ví dụ: Url trước khi dùng CDN là http://nukeviet.jamesblackvn.com/themes/default/css/jquery.metisMenu.css
Thì sau khi dùng CDN với nukeviet-jamesblackvn.cdn.vccloud.vn thì NukeViet phải thay thành url như ở dưới khi view source code.
http://nukeviet-jamesblackvn.cdn.vccloud.vn/themes/default/css/jquery.metisMenu.css

**Comment by vuthao** [comment]
@jamesblackvn 
bạn có thể tạo cho mình 1 tài khoản CDN ứng với site http://nukeviet.net để mình kiểm tra cụ thể hơn được không, nếu cần gửi tài khoản gửi dùm vào email thao a còng vinades chấm vn nhé.

**Comment by jamesblackvn** [comment]
@vuthao Đã gửi info nha bác

**Comment by vuthao** [comment]
Mình cấu hình mỗi  1 cái chạy luôn.

demo: http://nukeviet.net/

Trang admin cấu hình: ![screenshot from 2015-08-21 15-15-21](https://cloud.githubusercontent.com/assets/2491500/9404205/9827fbb2-4817-11e5-9672-f06a0d24aadf.png)

**Comment by jamesblackvn** [comment]
Của em thì điền thông tin vô xong lưu lại thì nó trống rỗng. Không lưu được :(

**Comment by vuthao** [comment]
mình cấu hình vào site của bạn được luôn.

Nhập cả: http://nukeviet-jamesblackvn.cdn.vccloud.vn

**Comment by vuthao** [comment]
Hiện tại đã tách phần cấu hình CDN thành plugin, và đã hỗ trợ CDN cho các file js, css, image.
@thaotrinhj  xem lại khái nệm CDN nhé, các kho lưu trữ lớn như Dropbox, Google Drive, SkyDrive, Copy ... sẽ không làm CDN được đâu.
