### ISSUE TITLE
Lỗi không thêm được block

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1159]
Khi thêm block chọn module để chọn block thì  bị redirect vào khu vực admin theo tên module 
admin/index.php?language=vi&nv=themes&op=blocks_func&module=news
last commit https://github.com/nukeviet/nukeviet/commit/8a79df27b1b8c814324f0672b39f1958470e23bc

**Comment by dangdinhtu2014** [comment]
Dọn dẹp hệ thống đã được admin xoá dùm

**Comment by dangdinhtu2014** [comment]
Dọn dẹp hệ thống đã được admin xoá dùm

**Comment by dangdinhtu2014** [comment]
Dọn dẹp hệ thống đã được admin xoá dùm

**Comment by dangdinhtu2014** [comment]
Lỗi tại đây
themes/admin_default/js/themes.js

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/11e04342a056ae14d536049b34dcf7c4ef3ac5d7
