### ISSUE TITLE
[Hỏi] Chức năng dọn dẹp block

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#1161]
Hiện tại đối với hệ thống block của giao diện, lúc nhà phát triển xóa tay thủ công các vị trí block ví dụ [MENU_SITE], [HEADER], nếu ở vị trí đó có block đã thêm thì trong CSDL dữ liệu của nó vẫn được lưu lại gây thừa dữ liệu.

Có nên thêm chức năng dọn dẹp block không? Hiện tại phần thiết lập lại vị trí block có thể dọn dẹp cái đó chưa?

**Comment by anhtunguyen** [comment]
Nên có chức năng này

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/f91b48c7a62bcd0bd8ef6855c27f6d599b58029f
