### ISSUE TITLE
Lỗi thiết lập block

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1162]
Phiên bản dev 4.0.21 mởi tải về tối nay bị lỗi: 
Khi thiết lập lại block thì không được.

**Comment by anhtunguyen** [comment]
Bạn mô tả lỗi kỹ hơn chút.

**Comment by nhimthulinh** [comment]
Khi anh thay đổi vị trí block trong admin , anh phải nhấn thiết lập lại các block để thực hiện công việc đó, và nó thông báo là erro, tất nhiên là sẽ ko lưu đc thiết lập đó anh

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/ea2c58dc5d8c45fa9b7bdcbcc9173736e61605ce
