### ISSUE TITLE
Lỗi cài đặt bản beta 7 (4.0.21)

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1165]
Lỗi cài đặt bước 5 không cài data vào được
SQLSTATE[HY000]: General error: 1017 Can't find file: 'ctypa_authors' (errno: 2 - No such file or directory)
---
Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - 
PHP extension: mysqli Documentation
PHP version: 5.6.8

**Comment by vuthao** [comment]
@nhimthulinh  có thể tạo 1 cái host để mình kiểm tra được không. Hiện tại mình kiểm tra không bị lỗi này.

**Comment by nhimthulinh** [comment]
lỗi này chỉ ngày hôm đấy thôi, nay tải bản mới về thì hết rồi anh
