### ISSUE TITLE
Link có thêm index.php

### ISSUE THREAD

**Issue by thuanthuyen** [nukeviet/nukeviet#1166]
http://thiendang.net/thiendang4/index.php/vi/

Vừa cài đặt xong nukeviet4 mình để trong Folder
- Cài đặt NV 2 ngôn ngữ khi xem link thí thấy cái đuôi thế này

Sử dụng host:
DirectAdmin Web Control Panel © 2012 JBMC Software

**Comment by hoaquynhtim99** [comment]
Cái này không phải lỗi nhé bạn, bạn xem thử host có hỗ trợ rewrite không, bạn có thể lên diễn đàn để tìm kiếm và trao đổi để hiểu thêm về cái này
