### ISSUE TITLE
Nên bổ sung thêm tùy chọn cấu hình chế độ mặc định xử lý sau khi login OpenID

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1167]
Hiện giờ sau khi login openid, hệ thống để cho user 3 tùy chọn:
![anh chup 241](https://cloud.githubusercontent.com/assets/1892900/8819236/91f8bb60-3074-11e5-80e9-bc92b91b41d2.jpg)

Nên bổ sung thêm tùy chọn cấu hình chế độ mặc định xử lý sau khi login OpenID. Sẽ có 3 chế độ xử lý trong cấu hình:
1. Cho user tự chọn hình thức xử lý (sẽ xuất hiện 3 tùy chọn cho user như hiện tại).
2. Đẩy user sang trang đăng ký tài khoản mới và gán openid vừa đăng nhập lần đầu vào tài khoản đó.
3. Đăng nhập tự động bằng một tài khoản tạm do hệ thống tự tạo.

Sẽ không có tùy chọn thứ 4: Đăng nhập bằng tài khoản mà user đã đăng ký trước đây. Lý do là vì mình không biết họ đăng đăng ký tài khoản trên hệ thống hay chưa (nếu cứ cố tình tạo thêm tài khoản mới thì sẽ sinh rác mà sau này không gộp tài khoản được). Trường hợp này có thể xử lý tối ưu hơn bằng cách bật popup hỏi xem user đã có tài khoản trên website chưa, nếu họ nhấn "có rồi" thì đẩy họ sang trang đăng nhập để gán openid vào tài khoản đó. Nếu họ nhấn "Chưa có" thì Đăng nhập tự động bằng một tài khoản tạm do hệ thống tự tạo để họ có thể tiếp tục thao tác như là thành viên đã đăng nhập hệ thống.

Ý nghĩa: Như vậy, thay vì để user tự xử lý dẫn đến các hành xử khác nhau (có khi không như ý muốn người quản trị site) Ví dụ mong muốn của người quản trị chỉ là cho phép login qua Facebook để xác thực các comment mà không mong muốn người ta phải đăng ký thành viên => chỉ cần cấu hình để chọn chế độ mặc định: Đăng nhập bằng một tài khoản do hệ thống tự tạo.

**Comment by vuthao** [comment]
update: https://github.com/nukeviet/nukeviet/commit/d598194c963fae55324545fceea98fa6e73948b9
