### ISSUE TITLE
Đóng gói js

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1168]
Có trường hợp của news, ngoài file news.js nó còn có thêm file themes/admin_default/js/news_content.js và sẽ có nhiều file js liên quan (Các thư viện,....)
Khi đóng gói sẽ không đóng gói được file news_content.js này.

Em thấy nên cho đóng gói hết những file có tiếp đầu tố là ten_module_****.js

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/8f9e4015fb09ecfcf0b7a99772038cdf10bc1df5
