### ISSUE TITLE
Lỗi thanh toolbar bật tắt kéo thả block

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1169]
NukeViet a6df92004906a7f133b15f6639304f182cff3880
Thanh toolbar không đẩy xuống dưới trang khi kéo thanh cuộn xuống trong trình duyệt Cốc Cốc và Chrome
![loitoolbar](https://cloud.githubusercontent.com/assets/9360175/8842926/e252bb2c-312a-11e5-972a-3a73d2e7fe34.png)

**Comment by anhtunguyen** [comment]
Fixed.
https://github.com/nukeviet/nukeviet/commit/f741cf02ca242c9cc684e6746c07340c529dea07
