### ISSUE TITLE
Lỗi chức năng tìm kiếm ngoài site

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1170]
Nukeviet a6df92004906a7f133b15f6639304f182cff3880
Khi tìm kiếm ngoài site không thể tìm kiếm và xuất hiện thông báo không có CSDL.

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/b13d38a92d1239ed08078ab40bd365683a89acd6
