### ISSUE TITLE
Lỗi vị trí toolbar khi reponsive website

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1171]
nukeviet a6df92004906a7f133b15f6639304f182cff3880
Khi thu nhỏ trang toolbar bật tắt kéo thả block chèn lên thanh menu
![loi2](https://cloud.githubusercontent.com/assets/9360175/8843149/f58af8e0-312e-11e5-81c3-6c3d8234b428.png)

**Comment by anhtunguyen** [comment]
Fixed.
https://github.com/nukeviet/nukeviet/commit/f741cf02ca242c9cc684e6746c07340c529dea07
