### ISSUE TITLE
Lỗi không hiển thị giống nhau trên các trình duyệt

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1172]
Nukeviet 4: https://github.com/nukeviet/nukeviet/commit/20c3d6bd7dbd1413075df4f0313578a83fe1eccf

![untitled](https://cloud.githubusercontent.com/assets/2491500/8850137/9bedf17a-316f-11e5-97da-4a60ae1e0662.png)

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/704527d6585bf3a4d14668ff4e8ae5c76990e6fd
