### ISSUE TITLE
Lỗi tìm kiếm ở môi trường localhost php 5.6.8

### ISSUE THREAD

**Issue by anhtunguyen** [nukeviet/nukeviet#1173]
Lỗi 404, xuất hiện khi tìm kiếm một số từ tiếng Việt có dấu như từ: "Nguyễn".
Xuất hiện ở tất cả các trình duyệt phổ biến.
Môi trường (XAMPP 5.6.8): PHP 5.6.8

**Comment by vuthao** [comment]
Đây có thể là vấn đề phát sinh trên Apache 2.4
Hiện tại em đã thử sửa file .htaccess
ví dụ sửa:
RewriteRule ^seek\/q\=(.*)$ index.php?nv=seek&q=$1 [L]

Thành
RewriteRule ^seek\/q\=([^?.]*)$ index.php?nv=seek&q=$1 [L]

anh Tú xem có phát sinh ghì không nhé.

**Comment by anhtunguyen** [comment]
Lỗi đúng là ở RewriteRule hỗ trợ UTF-8. Nhưng fix như em hướng dẫn sẽ sinh ra lỗi khi tìm cụm từ có chứa dấu chấm ở giữa. Tức là, bộ lọc các ký tự của mình chưa triệt để. Hiện anh thấy, nếu để dấu chấm ở cuối cụm từ tìm kiếm thì nó được xóa tự động, nhưng nếu ở giữa các ký tự khác thì nó vẫn được chấp nhận và sinh lỗi 404

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/0f037295d33d88a937874385235d2e1219262b33
