### ISSUE TITLE
Sai giờ hệ thống giữa site và admin

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#1174]
Sai giờ hệ thống giữa site và admin
![2015-07-24_15-50-15](https://cloud.githubusercontent.com/assets/8481170/8870945/084ae556-321c-11e5-8d72-caf4be4627a0.jpg)
![2015-07-24_15-50-54](https://cloud.githubusercontent.com/assets/8481170/8870948/104c82d2-321c-11e5-9b22-eda6b571eb7f.jpg)
![2015-07-24_15-53-35](https://cloud.githubusercontent.com/assets/8481170/8870976/34200ba2-321c-11e5-885e-bd70ea0a3278.jpg)

**Comment by vuthao** [comment]
Nếu chạy trên localhost hệ thống có thể xác định không đúng.
Bạn đưa website lên host xem chạy có đúng không.

Nếu vẫn sai, bạn có thể cấu hình tại phần: admin/index.php?language=vi&nv=settings&op=system
Múi giờ của site: Theo IP của nước truy cập hoặc chọn 1 thành phố cụ thể nếu chỉ dùng site cho một ngôn ngữ.

**Comment by HoanDateh** [comment]
Nếu điều chỉnh như vậy thì vẫn sai giữa giờ trên trang admin và site bên ngoài
Đang chạy trên host chứ không phải localhost

**Comment by HoanDateh** [comment]
![6](https://cloud.githubusercontent.com/assets/8481170/8872013/e921d542-3223-11e5-9bfa-3bf3bfd4645c.jpg)
![7](https://cloud.githubusercontent.com/assets/8481170/8872059/397a92f4-3224-11e5-98b5-5bacbb4654c7.jpg)
![8](https://cloud.githubusercontent.com/assets/8481170/8872063/403444d2-3224-11e5-9b2a-bdd7a01786f6.jpg)

**Comment by anhtunguyen** [comment]
Bạn thử làm như thế này trong file:  themes/admin_default/system/header.tpl theo hướng dẫn ở đây:
https://github.com/nukeviet/nukeviet/commit/dfbe55516bdbe416aa6443ca36a3ae69112983b1
Xóa cookie và đăng nhập lại ACP.

**Comment by vuthao** [comment]
Mình tóm tắt lại ý của anh Tú cho các site hiện tại
Sửa file  themes/admin_default/system/header.tpl 
Tìm dòng
var nv_my_ofs = '{NV_SITE_TIMEZONE_OFFSET}';
thay bằng:
var nv_my_ofs = {NV_SITE_TIMEZONE_OFFSET};

**Comment by vuthao** [comment]
HoanDateh bạn kiểm tra lại dùm sửa như thế có được ko nhé.

**Comment by HoanDateh** [comment]
Vẫn không được anh Thảo ơi

**Comment by vuthao** [comment]
anh Tú báo là do giờ máy chủ web của bạn bị sai nhé.
