### ISSUE TITLE
Lỗi đăng nhập qua facebook

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1175]
> Phiên bản NukeViet	4.0.21
Phiên bản PHP	5.5.25
Giao thức giữa máy chủ và PHP	Apache/2, litespeed
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 10.0.17-MariaDB
Môi trường: Hosting - http://mynukeviet.net

Click vào Icon facebook, nhấn OK ra trang trắng.
Một số bạn báo trên facebook, click vào nó tự nhảy về form đăng nhập, dù đã cấu hình đúng.

**Comment by vuthao** [comment]
Với những lỗi như thế này, cần có tài khoản host để kiểm tra. nếu không sẽ không thể fix được.

**Comment by nhimthulinh** [comment]
Lỗi này chuẩn rồi, mình bị như Triển

**Comment by thehung** [comment]
Anh dùng bản https://github.com/nukeviet/nukeviet/commit/5ef5a8e8032f61490449a12d758b82f2feaedae8 thì nó báo:

> Rất tiếc là OpenID-Server không cung cấp đủ các thông tin cần thiết để có thể đăng nhập vào website của chúng tôi

**Comment by hongoctrien** [comment]
@nhimthulinh dơwnload file này http://www.mediafire.com/download/4bzhipd1d78f70h/OAuth.zip
Chép vào thư mục modules/users/oAuthLib/OAuth rồi check lại giúp em xem hết lỗi không anh nha.

**Comment by nhimthulinh** [comment]
Phiên bản bạn đang sử dụng	4.0.21
ra trang trăng luôn triển ơi
http://ngochoionline.com/index.php?language=vi&nv=users&op=oauth&server=facebook

**Comment by hongoctrien** [comment]
Cái này anh gửi thông tin hosting qua anh @vuthao kiểm tra luôn được chứ

**Comment by nhimthulinh** [comment]
http://ngochoionline.com:2222/
user: ngochoi
pass: ngocanh
đây triển, host test nên thoái mái chỉnh sửa =)

**Comment by vuthao** [comment]
@nhimthulinh mình đã đổi pass nhé, xong sẽ đổi lại và thông báo lại sau.

**Comment by vuthao** [comment]
Hiện tại mình cài mới thử lại bản mới nhất cho các site báo lỗi đã chạy bình thường.
