### ISSUE TITLE
[Góp ý] Phần chẩn đoán site nên để kết quả mới nhất lên trên

### ISSUE THREAD

**Issue by xuanluchp** [nukeviet/nukeviet#1176]
Kết quả phần chẩn đoán site trong công site hiện tại đang hiển thị kết quả từ cũ đến mới, nếu để từ mới đến cũ thì tiện hơn, có thể xem được ngay, thay vì phải kéo xuống hết trang như hiện tại.

**Comment by truongemcom** [comment]
Còn nhiều cái phải sắp xếp ngược lại lắm, tốt nhất nên tự code lại cho riêng mình.

**Comment by vuthao** [comment]
ai cung như @truongemcom thì khi nâng cấp sẽ rất khổ nhé.
Thay vì như thế nếu sửa được bạn nên sửa, và đóng góp ngượi lại mã nguồn nhé.

Các đóng góp, ý kiến nếu sẽ được chúng tôi xem xét xử lý dần dần nhé, theo nguyên tắc lỗi, và những tính năng ảnh hưởng đến nhiều người dùng trước.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/86d05e7386ad62f42e0f954e85a2eb41b6cd1e31
