### ISSUE TITLE
Lỗi loại bỏ tên module trên url

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1178]
NukeViet dfbe55516bdbe416aa6443ca36a3ae69112983b1
Hiện nay bản nukeviet develop trong phần cấu hình chung. Tính năng loại bỏ module trên url chưa ổn định.
- Không thể loại bỏ module about
- Chọn bất kỳ một module loại bỏ nào cũng vẫn thấy đường link của module đó. Ví dụ như thành viên thì khi ra ngoài site ấn vào thành viên nó vẫn có link của module users
- Khi chọn module news làm module loại bỏ trên url thì khi truy cập vào trang chủ module news không thể truy cập được

**Comment by vuthao** [comment]
Module about, không loại bỏ được @nambmtk1993
Do module page là module đặc biệt của hệ thống luôn được loại bỏ module trên url. Nên nếu cần dùng tính năng này bạn hãy sử dụng trực tiếp  module page.

Lỗi thứ 2, 3 mình không thấy, Nam gửi  site bị lỗi này để anh kiểm tra nhé.

**Comment by nambmtk1993** [comment]
http://ictketnoi.vinades.net
tài khoản: admin
pass: 1236547

Vào 20:34 Ngày 25 tháng 07 năm 2015, Vu Thao <notifications@github.com> đã
viết:

> Module about, không loại bỏ được @nambmtk1993
> <https://github.com/nambmtk1993>
> Do module page là module đặc biệt của hệ thống luôn được loại bỏ module
> trên url. Nên nếu cần dùng tính năng này bạn hãy sử dụng trực tiếp module
> page.
>
> Lỗi thứ 2, 3 mình không thấy, Nam gửi site bị lỗi này để anh kiểm tra nhé.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nukeviet/nukeviet/issues/1178#issuecomment-124847531>.
>



-- 
Ký Tên:
*Nguyễn Lương Nam*
Khoa: Ct17-Đại học...

**Comment by vuthao** [comment]
Vấn đề: Chọn bất kỳ một module loại bỏ nào cũng vẫn thấy đường link của module đó. Ví dụ như thành viên thì khi ra ngoài site ấn vào thành viên nó vẫn có link của module users.

Nguyên nhân: Module trên trang chủ không phải là module cần loại bỏ

**Comment by thehung** [comment]
@nambmtk1993 báo lỗi chưa dễ hiểu, cách tốt nhất là em mô tả lại thao tác dẫn đến lỗi (nếu cảm thấy việc mô tả lỗi khó quá :D)

@vuthao: thao tác dẫn đến lỗi thứ 3 như sau: NukeViet dfbe55516bdbe416aa6443ca36a3ae69112983b1 mới cài, vào "Cấu hình chung" và để trống mục "Loại bỏ tên module trên url" (tắt chức năng loại bỏ tên module news trên URL) thì không có cách gì truy cập vào trang chủ module news vì đường dẫn mysitenukeviet.com/news/ hệ thống báo không tồn tại.

![screenshot from 2015-07-30 01 36 13](https://cloud.githubusercontent.com/assets/1892900/8966562/4426a53a-365c-11e5-8d81-c842fe8674f7.png)

Lỗi chỉ xảy ra trên site NukeViet cài mới, không bị lỗi nếu site đã sử dụng một thời gian.

**Comment by vuthao** [comment]
Mình test lại trên local, và 2 host khác nhau cũng không thấy lỗi này.
Đã nhờ anh Hùng và Nam kiểm tra cùng.

**Comment by thehung** [comment]
Ác thật. Cứ như ma làm í :D
