### ISSUE TITLE
Góp ý phần giao diện footer của di động

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1179]
Nukeviet dfbe55516bdbe416aa6443ca36a3ae69112983b1
Trong footer di động có dòng chữ "Chế độ giao diện đang hiển thị: Tự động - Máy Tính - Di động" => không tô đậm hoặc đánh dấu nên không biết là đang ở chế độ nào hoặc  đang được hiển thị ở chế độ nào

**Comment by vuthao** [comment]
Giao diện mobile đã được sửa lại: https://github.com/nukeviet/nukeviet/commit/18aeccffd665a2331c88d93fe10ad3a6c01ca0d5

Nếu cập nhật code, cần bật tính năng kéo thả block để thêm block footer nhé Nam.
