### ISSUE TITLE
Hàm function nv_block_counter_button() trong file global.counter_button.php kiểm tra không chuẩn

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#1180]
Trong hàm function nv_block_counter_button() khi kiểm tra tập tin global.counter.tpl nhưng phía dưới không gọi tập tin đó mà lại gọi tập tin global.counter_button.tpl

function nv_block_counter_button()
	{
		global $global_config, $db, $lang_global;

		if( file_exists( NV_ROOTDIR . '/themes/' . $global_config['module_theme'] . '/modules/statistics/global.counter.tpl' ) )
		{
			$block_theme = $global_config['module_theme'];
		}
		elseif( file_exists( NV_ROOTDIR . '/themes/' . $global_config['site_theme'] . '/modules/statistics/global.counter.tpl' ) )
		{
			$block_theme = $global_config['site_theme'];
		}
		else
		{
			$block_theme = 'default';
		}

		$xtpl = new XTemplate( 'global.counter_button.tpl', NV_ROOTDIR . '/themes/' . $block_theme . '/modules/statistics' );

**Comment by anhtunguyen** [comment]
OK.
Cảm ơn bạn.
https://github.com/nukeviet/nukeviet/commit/20b12b12204b8a85343bd8c92851c20011b47431
