### ISSUE TITLE
Minh họa hình sau khi crop thumb

### ISSUE THREAD

**Issue by RightPro** [nukeviet/nukeviet#1181]
Trong phần cấu hình cắt ảnh thumb, nên có thêm hình mình họa ảnh thumb sau khi đã crop, nằm bên cạnh ảnh trước khi crop.

**Comment by vuthao** [comment]
Bạn giải thích rõ hơn nhé, mình đọc xong chưa hiểu lắm.

**Comment by RightPro** [comment]
hiện tại phần cấu hình ảnh thumb có nhập thông số dài rộng và chất lượng hình ảnh nhưng không có hiển thị demo hình sau khi cắt. Ví dụ hiện thị hình demo kích thước 600x600 sau khi cắt kích thước ... tỉ lệ ... thì được hình như thumb bên cạnh.

**Comment by vuthao** [comment]
@RightPro  Nếu bạn thiết kế được giao diện mình sẽ code nhé, chứ hiện tại mình vẫn chưa hình dung ra trình bày như thế nào

**Comment by hoaquynhtim99** [comment]
Added: https://github.com/hoaquynhtim99/nukeviet/commit/f5516129d8a25356e057a8e3f086e1c610cf05b5
