### ISSUE TITLE
Đường dẫn đến Điều khoản sử dụng không chính xác 

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#1182]
Đường dẫn đến Điều khoản sử dụng khi cài đặt trong một thư mục không chính xác:
http://tên miền/index.php?language=vi&nv=siteterms mà đúng ra phải là
http://tên miền/thư mục cài đặt/index.php?language=vi&nv=siteterms

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/56add0539a31d69f4863fabe16ed04f0b2e32244

**Comment by HoanDateh** [comment]
Lỗi này vẫn bị trên giao diện mobi
