### ISSUE TITLE
Lỗi đăng ký tài khoản ngoài Site

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1183]
Nukeviet 5ef5a8e8032f61490449a12d758b82f2feaedae8
Em sử dụng chức năng đăng ký thành viên ngoài site ban đầu kéo xuống dưới để đọc những quy định đăng ký thành viên website. Sau khi đọc xong em muốn kéo lên về phần "Tên" hay "Họ tên" thì không được. Các anh chị fix lỗi này giùm em nha.

**Comment by anhtunguyen** [comment]
Fixed.
https://github.com/nukeviet/nukeviet/commit/fb85e6465f3651ee1d8742023172f46e8fdc88fc
Bạn kiểm tra lại xem còn bị thế nữa không?

**Comment by vuthao** [comment]
hiện tại vẫn còn lỗi, @hoaquynhtim99 xem chi tiết tại đây nhé: http://demo.nukeviet.vn/loi-dang-ky-thanh-vien.mp4

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 cần fix lại lỗi này và bỏ hết các mã html ra khỏi JS. Hiện tại nó lẫn lộn.
Block này đã không được kích hoạt mặc định vì đã có button "Đăng nhập / Đăng ký" trên toolbar.

**Comment by hoaquynhtim99** [comment]
Phần này có vẻ hơi quan ngại, hiện mấy cái đó hoàn toàn do bootstrap điều khiển, để đó em tìm cách

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/nukeviet/nukeviet/commit/24f727991aed15b0912def4bc425bca616be6e6a
