### ISSUE TITLE
[OG meta tags] Thuộc tính og:type của NukeViet 4.x bị sai

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1185]
Thuộc tính og:type của NV hiện tại là <meta property="og:type" content="WebPage" />
Tuy nhiên trên công cụ debug của FB thì thuộc tính này bị báo là không chính xác.
Hiện tại, tất cả các trang đều được set type là WebPage.

Nếu có thể, NV nên điều chỉnh tag này, tương ứng cho trang chủ là 
Website

Chuyên mục là 
Object

Và bài viết con là 
Article

**Comment by vuthao** [comment]
@anhyeuviolet  mô tả lại nhé, hiện tai mình đọc thấy nội dung mô tả không rõ lắm.

**Comment by anhyeuviolet** [comment]
:D Do em mô tả hơi cụt. 
Em lấy 1 link web em làm demo, khi dán vào công cụ debug của Facebook thì được KQ như sau : 
![og-error-1](https://cloud.githubusercontent.com/assets/6290970/8900930/bb6b20f2-346e-11e5-81b1-5d64859088af.PNG)
Tức là OG:TYPE mà NV sinh ra là WebPage. Thuộc tính này không đúng ( theo lỗi trong hình ).
Khi xem source của trang NV em làm demo thì nó tương ứng với dòng sau : 

![og-error-2](https://cloud.githubusercontent.com/assets/6290970/8900948/d9b899f4-346e-11e5-9d91-907880a2ae92.PNG)
Khi xem hết các func thì em thấy tất cả đều có og:type là WebPage.

Tham khảo một trang WP dùng bộ SEO Tools thì nó cấu hình như sau : 
Với bài viết chi tiết thì og:type là article ( Như hình dưới )
![og-error-3](https://cloud.githubusercontent.com/assets/6290970/8900997/56bda26e-346f-11e5-9d9f-2426e2c5e3b0.PNG)

Còn với trang chủ thì og:type là Website; trang chuyên mục con ( tương ứng func viewcat của NV ) thì og:type là Object.

Do đó em thấy mình nên điều chỉnh lại phần các thẻ og này tí để các trang muốn SEO share này nọ trên FB sẽ phần nào tiện hơn.

**Comment by vuthao** [comment]
Mình đã hiểu, tối nay mình sẽ fix lại các phần này.

**Comment by vuthao** [comment]
@anhyeuviolet  tôi không tìm thấy tài liệụ nào mô tả về  type là Object

Các tài liệu đã tham khảo.
https://developers.facebook.com/docs/sharing/best-practices
http://ogp.me/#types

**Comment by anhyeuviolet** [comment]
Có lẽ em nhầm xíu
https://developers.facebook.com/docs/reference/opengraph/object-type/object/

Với type là object thì ở đây hẳn plugin đó không chỉ định ra rõ ràng phần chuyên mục đó là loại gì. Đây là hình ảnh OG tags được crawl mà em debug thử cho 1 link chuyên mục.
![og-1](https://cloud.githubusercontent.com/assets/6290970/8928762/c0e13116-354a-11e5-9025-5d1680e88584.PNG)
![og-2](https://cloud.githubusercontent.com/assets/6290970/8928763/c0ef1ab0-354a-11e5-8b11-d344272ee534.PNG)


Có lẽ phần này để là website cũng vẫn hợp lý, thay vì để là object như trong hình.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/72447f963564bd4687c5b3bf3214d9704d8854cc
