### ISSUE TITLE
[Góp ý] Theme default Nukeviet 4.21 đang là thảm họa của Nukeviet từ trước tới giờ

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1187]
Đề nghị các bạn nên thiết kế lại. Tôi thực sự không hiểu thẩm mỹ của các bạn đang đến đâu khi làm ra cái giao diện hiện tại nhưng không chấp nhận được một tý nào. Phong cách quê mùa. Phối màu thì không chấp nhận được.

**Comment by dtsoncntt** [comment]
:-1:  Không thể tin được , xấu không thể tả nổi . Đề nghị nên xem xét thiết kế lại để bộ mặt của Nukeviet bản mới trông ấn tượng và dễ nhìn hơn .

**Comment by thehung** [comment]
Giao diện 4.0.21 là giao diện bản beta. NukeViet bản chính thức sẽ có giao diện khác.

**Comment by hoaquynhtim99** [comment]
Hình cái tit thấy phát hoảng, cứ như báo mạng

**Comment by hoanglongvnpt** [comment]
Đúng là càng nhìn càng oải, đóng góp ý kiến xây dựng thì tỏ vẻ ta đây là...nay miễn góp ý.

**Comment by dangdinhtu2014** [comment]
Từ nay tôi cũng miễn góp ý. Các bạn thích ta đây thì cứ việc. Chào thân ái !

**Comment by truongemcom** [comment]
Thấy không phù hợp thì dùng giao diện của riêng mình, mặc kệ nó có là "thảm hoạ" hay "thảm thê" đi. Góp y làm chi cho khổ????

**Comment by nhimthulinh** [comment]
=) giao diện lúa như 2 lúa ấy

**Comment by thehung** [comment]
Không rõ các em đang nói phiên bản nào?  4.0.21 hay bản Develop mới nhất?

Tôi đã nói rõ là đội code sẽ thay giao diện của bản 4.0.21 bằng giao diện khác. Hình như các bạn chưa hiểu? 

Nghe góp ý kiểu này đúng là hơi bị mất hứng.

**Comment by HoanDateh** [comment]
Hình như đang nói giao diện bản develop

**Comment by RightPro** [comment]
đúng là xấu ko tả nổi :+1:

**Comment by hoaquynhtim99** [comment]
Có bạn nào vui lòng cho mình nhìn thấy cái mà các bạn thấy được không?

**Comment by quangdieu05** [comment]
Nó là cái này phải k ạ?
![nuke](https://cloud.githubusercontent.com/assets/7751510/8936794/79905b3c-357e-11e5-897c-b102c7f484fd.png)
