### ISSUE TITLE
Cài đặt: Lỗi cài đặt thực hiện tại Bước 5

### ISSUE THREAD

**Issue by hungvntb** [nukeviet/nukeviet#119]
Chạy cài đặt đến bước 5 ấn thực hiện mà không chạy tiếp được nữa, đã đièn đầy đủ thông tin kiểm tra nhiều lần vẫn ko được.
Môi trường thử Nghiệm
- Hệ điều hành: Win7_32-bit
- Trình duyệt web: Mozilla Firefox 27.0, Chrome 32
- Máy chủ web: appserv 2.5.10 Nếu trên website cần có thêm thông tin
- công cụ quản lý hosting: cpanel
- Apache 2.4.7, MySQL 5.5.36, PHP 5.4.25

**Comment by thanhlink** [comment]
Mình chạy tới bước 5 thì không thể tiếp tục được mặc dù cả 4 bước trước không có vấn đề gì cả, một lúc thì chỉ trang trắng.
