### ISSUE TITLE
Ý kiến block đăng nhập

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1190]
Có nên cho fom lấy lại mật khẩu vào trong block này không nhỉ. Mình thì nghĩ nên cho vào luôn cho tiện dụng người dùng

**Comment by vuthao** [comment]
Hiện tại mình thấy đã có link Quên mật khẩu?
Và không nên cho cái này vào, bởi chức năng này ít dùng, cho vào nó nặng site.
