### ISSUE TITLE
[Lỗi giao diện] Dropdown phần chọn modules hiển thị sai kiểu

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1191]
NukeViet DEV
https://github.com/nukeviet/nukeviet/commit/d1666f979d5695fe2f28caab4eeb3c8817299f3c
XAMPP 1.8.3
Firefox Latest.

Như hình dưới : 
![search-select](https://cloud.githubusercontent.com/assets/6290970/8922785/ffa5b5cc-3511-11e5-8a56-bbdc2784e7f8.png)

Không biết có tính là lỗi không nữa :D 
Còn Chrome Latest thì ko bị lỗi này.
![search-select-2](https://cloud.githubusercontent.com/assets/6290970/8922808/43fe0986-3512-11e5-8e3a-84c881411581.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/1ec883a14885185d25cda948bac68b0602b51982
