### ISSUE TITLE
Cơ chế active menu

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1193]
Phiên bản NukeViet	4.0.21
Phiên bản PHP	5.6.8
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ	DARWIN
Phiên bản Database	mysql 5.6.24
------------
Mình thấy cơ chế active menu không đúng lắm.
Nếu module làm trang chủ thfi chúng ta active li-> trang chủ như ngày trước
Còn hiện nay active menu theo Loại bỏ tên module trên url
Giả dụ tôi Loại bỏ tên module trên url là sản phẩm mà trang chủ lại cho hiện about thì vô lý rồi
Vậy nên chuyển active menu  theo cấu hình Module mặc định trên trang chủ

**Comment by anhyeuviolet** [comment]
Hình như ko phải anh Nhím ui.
Bản này bỏ thuộc tính active của Trang chủ đi. Khi vào modules nào thì active modules đó thôi.
Em có thử nghiệm như anh mô tả. Lấy About làm trang chủ và Statistics làm rút gọn tên modules trong URL thì thấy nó vẫn active phù hợp với từng URL cũng như của trang chủ.

**Comment by nhimthulinh** [comment]
vậy có khả năng do lưu cache

**Comment by vuthao** [comment]
hiện tại chữ trang chủ, mình sửa nó không active. 
Bởi nó sẽ trùng với module khi có module đặt ở trang chủ, lúc đó sẽ xẩy ra 2 menu cùng active

**Comment by nhimthulinh** [comment]
Theo em nghĩ giống active như cũ có vẻ hợp lý hơn, mới vào mà nó active menu tận ở giữa.
Khi click vào module làm trang chủ thì nó sẽ ative module đó

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/2f4cb7188bc7d2c2bd25756921231b2c84be6796
