### ISSUE TITLE
Thông báo từ Hệ thống - Lỗi cảnh báo - Module statistics

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1194]
NukeViet https://github.com/nukeviet/nukeviet/commit/5ef5a8e8032f61490449a12d758b82f2feaedae8, truy cập http://ictketnoi.com/statistics/, nhận được thông báo:

> Thông báo từ Hệ thống
> Lỗi cảnh báo Lỗi cảnh báo: constant(): Couldn't find constant BROWSER_UNKNOWN in file /modules/statistics/theme.php on line 578
> Lỗi cảnh báo Lỗi cảnh báo: constant(): Couldn't find constant PLATFORM_UNKNOWN in file /modules/statistics/theme.php on line 617

Trình duyệt: FireFox 39.0
HĐH: Windows 8.1

**Comment by anhtunguyen** [comment]
Riêng module này cần phải nâng cấp database vì một số trình duyệt cũ kỹ, hệ điều hành cổ đã bị loại ra khỏi danh sách nhận dạng. Cách đặt tên trình duyệt, HDH cũng khác. Lỗi mà Hùng viết hình như chỉ xảy ra với site nâng cấp chứ ko phải cài mới?

**Comment by thehung** [comment]
Site này cài mới anh ạ.

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/1797817e4765b5bcb12f31ea463a7d354ce6e2a0
