### ISSUE TITLE
Lỗi không thể thay đổi chữ Nhãn của ảnh trong bài viết

### ISSUE THREAD

**Issue by xuanluchp** [nukeviet/nukeviet#1195]
Lần trước ở phiên bản 4.0.13, mình đã đề nghị đội code lấy tự động phần chú thích ảnh khi chèn và nội dung bài viết bằng cách đánh dấu vào tùy chọn "Ảnh có chú thích" để lấy chú thích của ảnh khi tải lên. Ở phiên bản 4.0.21 phần chú thích lại hiển thị chữ "Nhãn" mặc dù đã đánh dấu tích. Nhưng quan trong hơn là chỉ hiển thị chữ Nhãn mà không thể xóa hoặc sửa được. Đành phải bỏ dấu tich và enter xuống phía dưới để chèn chú thích thật bất tiện.

Mình sử dụng hosting. 
Tên miền: http://hotruong.net.

**Comment by vuthao** [comment]
Cái này em đã sửa vào ckeditor không hiểu sao không được trộn vào kho code gốc của ckeditor, đến khi cập nhật tính năng này lại mất.

**Comment by xuanluchp** [comment]
Vấn đề là code hiện tại không thể xóa được chữ Nhãn, dán phần chú thích thay chữ Nhãn cũng không được, không biết lỗi tại sao nữa.

**Comment by vuthao** [comment]
@xuanluchp em đã sửa đưa lên kho code gốc của ckeditor như lại bị từ chối rồi.
https://github.com/ckeditor/ckeditor-dev/pull/204

Và đã được 3 develop ở đây từ chối.
Yes, unfortunately figcaption is a different thing. Generally speaking alt is here you give concise description of the image, whereas figcaption is used for giving supplementary text (explaination of non-obvious things, legends etc.). Because of that we shouldn't reuse alt in figcaption.

Có lẽ chúng ta nên đi theo cộng đồng thế giới để nhập cho chính xác.

Hoặc bác nào giỏi tiếng anh vào đó thuyết phục được ckeditor nhập vào kho code gốc. Hoặc chúng ta sẽ dùng theo thế giới nhé.

**Comment by anhyeuviolet** [comment]
Cái này em test lại trên 4.0.18 thì thay được label và chú thích mặc định cũng được đưa xuống làm caption. Anh @vuthao có thể giải thích cho em phần code anh pull cho họ được ko ?
Em cũng muốn tham gia thuyết phục họ xem thế nào ...

**Comment by anhyeuviolet** [comment]
Cập nhật ... bản DEV mới nhất hiện tại
https://github.com/nukeviet/nukeviet/commit/df45d9bbe97d9d9319580ea2692d3c7edff8b062
Dù nó ko tự nhận phần ALT xuống làm caption, nhưng chữ "Nhãn" hoàn toàn có thể click để sửa hoặc xoá được ...

**Comment by vuthao** [comment]
@anhyeuviolet Đoạn code đó khi chọn Captioned image, nó sẽ lấy Alternative Text  để làm ,mặc định. (Dành cho người không muốn gõ lại)

**Comment by vuthao** [comment]
Hiện tại đúng là không sửa được "Nhãn" trên Firefox. 
Ngay cả trên ckeditor cũng lỗi. http://sdk.ckeditor.com/samples/captionedimage.html
Tạm thời chấc phải chuyển sang Google Chrome nếu muốn dùng tính năng này.

**Comment by anhyeuviolet** [comment]
Ah ! Em hiểu rồi.
Lúc chiều test trên FF thì ko sửa được. Giờ về nhà dùng GC thì sửa được caption.

**Comment by vuthao** [comment]
Theo như ckeditor, thì lỗi này từ Firefox, và lỗi này chấc chắn phải chờ mozilla sửa.

**Comment by thehung** [comment]
Gay cấn nhỉ. Mấy ông developer của Ckeditor không biết report cho Firefox
chưa!

**Comment by anhyeuviolet** [comment]
Dạ.
The fact that with Firefox the label cannot be edited is a recent Firefox regression (see https://bugzilla.mozilla.org/show_bug.cgi?id=1181130) and Mozilla is working on a solution for it. So if that was a reason for making this change, then it won't be necessary.

—
Kiểu này chắc có rồi. :D Vậy thì họ sẽ ko fix nên phải dùng theo họ thôi.
