### ISSUE TITLE
Lỗi : icon số lượng bình luận bị đẩy xuống dưới

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1196]
trình duyệt coccoc

![image](https://cloud.githubusercontent.com/assets/10300770/8948364/b9995cc2-35d0-11e5-9bea-7da09179270d.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/37cd0b6457ddc7fbe165417ebeb6dd62d0340dcd
