### ISSUE TITLE
Phần tiêu đề của đánh giá chữ cái đầu chưa viết hoa

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1197]
![image](https://cloud.githubusercontent.com/assets/10300770/8948468/b93594d4-35d1-11e5-9b5a-417abeb0c1cd.png)

**Comment by vuthao** [comment]
Fixed: https://github.com/nukeviet/nukeviet/commit/734429f658072441f95554dc3c9f2656477e284a
