### ISSUE TITLE
Lỗi chuyển hướng op khi chọn module của op thiết lập layout 

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1198]
Trình duyệt cốc cốc

khi click chọn module thì tự động nhảy sang phần quản lí block của module vừa chọn

![image](https://cloud.githubusercontent.com/assets/10300770/8949914/2cb78d60-35e4-11e5-9705-d400532c5734.png)

như hình bên dưới

![image](https://cloud.githubusercontent.com/assets/10300770/8949936/89c6528e-35e4-11e5-825b-672c5ea03a2c.png)

**Comment by HoanDateh** [comment]
Cái này bị cả trên trình duyệt Google Chrome (Bản develop mới nhất)

**Comment by anhyeuviolet** [comment]
Firefox bị tương tự. Có lẽ ko phải do lỗi trình duyệt rồi ...

**Comment by vuthao** [comment]
Lỗi này do xung đột javascript khu Dũng chuyển javascript viết inline trong file tpl vào file js của modulle.

fixed: https://github.com/nukeviet/nukeviet/commit/272ec6b0374a8e3257d6fe833f04ad13fc7523ec
