### ISSUE TITLE
Chức năng kiểm tra thứ hạng site không hoạt động (4.0.21)

### ISSUE THREAD

**Issue by xuanluchp** [nukeviet/nukeviet#1200]
Hiện tại chức năng kiểm tra thứ hạng site không hoạt động, chức năng cứ load mà không cho ra kết quả.

![1438176892617_1422](https://cloud.githubusercontent.com/assets/10148636/8958826/6359f34c-3631-11e5-8e9c-3596336de0da.png)

Tên miền sử dụng http://hotruong.net
Trình duyệt: firefox 3.9.0
Trình duyệt chrome cũng vậy.

**Comment by vuthao** [comment]
Em dự định sẽ bỏ tính năng này đi, do google thay đổi code luôn tục, sửa mất nhiều công quá anh.

**Comment by anhyeuviolet** [comment]
Cái này mất đi thì cũng hơi tiếc. Chắc để làm dạng một plugin hay module hỗ trợ, sau này có nâng cấp thì tiện hơn.

**Comment by hongoctrien** [comment]
Giữ lại cái này làm plugin cũng đựoc, nhưng trc mắt đã bỏ ra khỏi module

**Comment by vuthao** [comment]
Hiện tại tính năng này đã được đưa ra khỏi hệ thống, @hongoctrien xem viết plugin nhỉ.
