### ISSUE TITLE
Lỗi tại bước 5 của quá trình cài đặt

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1201]
tại bước 5 của quá trình cài đặt, nếu chọn loại CSDL khác, thì bật ra cửa số thông báo download thêm file về.

Tuy nhiên không làm thế nào để đóng của sổ này lại được để chọn lại loại khác.

**Comment by hoaquynhtim99** [comment]
Trình duyệt nào vậy anh?

**Comment by hoaquynhtim99** [comment]
Cái này đáng lẽ ra phải add bootstrap vào nó mới pro, em thử rồi nhưng mà giao diện cả trang install vỡ quá chắc phải sửa khá lâu, nên tạm viết cái modal kiểu vậy dùng tạm, có thời gian add bootstap sau.

Fixed https://github.com/nukeviet/nukeviet/commit/80d5c8136259b5c92806814d046f7d4eb4138be9
