### ISSUE TITLE
form đăng ký bị lệch nút đồng ý trên giao diện mobile

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1202]
![wp_ss_20150730_0001](https://cloud.githubusercontent.com/assets/6806295/8980676/ac1c2f54-36dc-11e5-931e-59dca32d09cb.png)
![wp_ss_20150730_0003](https://cloud.githubusercontent.com/assets/6806295/8980685/b3693270-36dc-11e5-92bb-c6a64c93bf49.png)

**Comment by anhtunguyen** [comment]
Sao tôi vào bằng mobile vẫn thấy bình thường nhỉ. Bạn vào bằng máy nào? Dùng trình duyệt nào?

**Comment by phongaz** [comment]
Mình dùng Điện thoại lumia 820, window phone 8.1, Trình duyệt internet explorer theo máy

**Comment by anhtunguyen** [comment]
Ok. Cảm ơn bạn. Tôi sẽ fix sớm.

**Comment by phongaz** [comment]
Mình nghĩ, khi chưa check vào tôi đồng ý thì nút đăng ký bị disabled. khi check vào thì nó sáng lên để click thì tốt hơn là để dấu sao vào nó

**Comment by phongaz** [comment]
Thêm nữa, khi dùng Safari trên iphone 5, sau khi click vào block này, dù ở tab đăng nhập hay đăng ký thì khi dùng tay vuốt nhẹ lên thì block bị đóng lại luôn.

Cùng trên thiết bị đó, nhưng dùng chrome thì không sao.

**Comment by anhtunguyen** [comment]
fixed
https://github.com/nukeviet/nukeviet/commit/90c6edae5f0abe8103a5b6e5eb1ce4cfb98b400e
Bạn thử cài mới từ đầu và kiểm tra hộ xem còn lỗi ko nhé

**Comment by phongaz** [comment]
Đã cài lại site, lỗi lệch nút tôi đồng ý thì đã ok trên thiết bị này.

Tuy nhiên còn lỗi form bị biến mất khi duyết trên safari iphone 5 thì vẫn còn.

Xem video clip: https://drive.google.com/open?id=0BySLP6070LzdQjUwNFRzUjRyY0tLYTMwQlpENlNYVDdad3JR

**Comment by anhtunguyen** [comment]
Bạn thử như thế này: Mở file: themes/default/js/main.js, tìm đến dưới cùng có 2 con số 50, bạn thay bằng 200 và kiểm tra xem còn bị ko?

**Comment by phongaz** [comment]
Ok. đã sữa:

$(window).on("resize", function() {
	winResize();
	fix_banner_center();
	if (200 < cRangeX || 200 < cRangeY) tipHide(), ftipHide()
});

HẾT LỖI RỒI

**Comment by anhtunguyen** [comment]
Cảm ơn bạn.
Tiếp tục kiếm lỗi nhé!

**Comment by anhtunguyen** [comment]
https://github.com/nukeviet/nukeviet/commit/bd10a088f3906d485c14523463a3933bd2f7eaec
