### ISSUE TITLE
Lỗi Button_counter hiển thị không giống nhau trên 2 trình duyệt

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1203]
Test Chrome Version 44.0.2403.125 và IE 11.0.9600.17905
Kết quả hiển thị không giống nhau

![button_counter](https://cloud.githubusercontent.com/assets/6806295/8987480/9312d7ea-370b-11e5-8091-aae172387b2a.PNG)

**Comment by vuthao** [comment]
@phongaz bạn mô tả thông tin trình duyệt thứ 2, (Trình duyệt, hệ điều hành) 
Và chế độ kiểm tra trình duyệt thứ 2 hình như là giao diện tùy biến đúng không nhỉ.

**Comment by phongaz** [comment]
Trình duyệt thứ 2 là : Chrome Version 44.0.2403.125, duyệt trên giao diện responsive và co kích thước lại.
Cả hai dùng trên hệ điều hành window 8.1

Hôm nay thì không thấy hiện tượng trên nữa. xóa cache, và refresh lại cũng không bị.

**Comment by anhtunguyen** [comment]
OK. Lỗi đó đã được fix ở đây rồi:
https://github.com/nukeviet/nukeviet/commit/14a0b92645dbc337e861843afa62c2124e1155f5
Chắc do bạn chưa cập nhật.
Tiếp tục tìm lỗi nhé !
