### ISSUE TITLE
Nút tìm kiếm chèn lên khối khác khi ngưng kích hoạt menu boostrap.

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1204]
Nút tìm kiếm chèn lên khối khác khi ngưng kích hoạt menu boostrap. và thanh điều hướng breadcrumb cũng không thấy
![breadcrumb](https://cloud.githubusercontent.com/assets/6806295/8987894/7da611ae-370d-11e5-8db3-00b46caf3436.PNG)

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/2f4cb7188bc7d2c2bd25756921231b2c84be6796
