### ISSUE TITLE
Lỗi không reload số lượng khi xóa danh mục freecontent ở admin

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1205]
Sau khi xóa hệ thống không reload số lượng khi xóa danh mục freecontent ở admin
![ajax freecontent](https://cloud.githubusercontent.com/assets/6806295/8988067/571d0b40-370e-11e5-95aa-6a5054a7936f.PNG)

Ba bài viết nhưng số lượng là 4.

Sau đó refresh thì mới cập nhập

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/21dfe683f8592d62580e79b5caa2d211bbd62f97
