### ISSUE TITLE
Icon "Đăng nhập - đăng ký" chưa phù hợp

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1206]
![anh chup 244](https://cloud.githubusercontent.com/assets/1892900/8988278/652bbb90-370f-11e5-84b7-099a96126a4a.jpg)

Nên đổi icon này thành biểu tượng khác cho phù hợp hơn.

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/67490e3f313e1db1a396f8922c0b46979997075d
