### ISSUE TITLE
Lỗi link trong block global menu footer 

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1207]
Link của module đầu tiên ở cột thứ 2 luôn bị trỏ về trang chủ cho dù đã cho hiển thị tên module trên đường link dẫn tới sai đường dẫn truy cập.

![anh chup 245](https://cloud.githubusercontent.com/assets/1892900/8988348/d077515c-370f-11e5-8803-55f1a1d36aba.jpg)

**Comment by vuthao** [comment]
Module này do đã cấu hình: Loại bỏ tên module trên url

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/a88baf5b23d4f88267d63dce04fcb2e67b8436dc
