### ISSUE TITLE
Không cho phép tích chọn login bằng FB, Google nếu chưa khai báo thông số kết nối

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1208]
Hiện giờ Facebook và Google bắt buộc phải khai báo mới cho phép site sử dụng tài khoản của họ để đăng nhập, do đó chỉ nên cho phép người sử dụng kích hoạt khi họ đã khai báo thông số kết nối. Tránh trường hợp hệ thống báo lỗi không đáng có cho người dùng cuối:
![anh chup 246](https://cloud.githubusercontent.com/assets/1892900/8988431/437780d2-3710-11e5-9802-cbb0bb25dcbb.jpg)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/4998d26409f639b4a4719079d74a0f202c44265a

**Comment by phongaz** [comment]
Cái này đúng là lỗi đã báo ở đây nhưng lại close https://github.com/nukeviet/nukeviet/issues/1135

**Comment by thehung** [comment]
Hai cái này khác nhau đấy anh Phong.

Anyway, nếu bị close issue mà thấy chưa thỏa đáng thì các bác cứ comment
tiếp, thậm chí là mở lại nó nhé (hình như mọi người đều có quyền này(?))

**Comment by hoaquynhtim99** [comment]
Hình như người tạo issue và admin là close được :dancers:
