### ISSUE TITLE
Lỗi khi xem bài viết trong Module News

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#1209]
Do thay đổi một số thư mục lên khi xem một bài viết trong module News không load được 2 file sau:
link href="{NV_BASE_SITEURL}editors/ckeditor/plugins/codesnippet/lib/highlight/styles/github.css" rel="stylesheet"
script type="text/javascript" src="{NV_BASE_SITEURL}editors/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js"

**Comment by vuthao** [comment]
mình đã sửa lại: https://github.com/nukeviet/nukeviet/commit/dce9072b551c6d6a9a8531674b602e2ae761bf14
