### ISSUE TITLE
Thiếu dấu } ở file detail.tpl của mobile_default ở dòng 247

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1212]
https://github.com/nukeviet/nukeviet/blob/develop/themes/mobile_default/modules/news/detail.tpl#L247

nhẽ ra nó phải là:
<script type="text/javascript" src="{NV_BASE_SITEURL}{NV_EDITORSDIR}/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js"></script>

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/c072aec164bb97081ac9fbdf64dbea1e4f3157d7
Tks @phongaz
