### ISSUE TITLE
Không thoát tài khoản ra dù đã đổi mật khẩu

### ISSUE THREAD

**Issue by coolboysorry** [nukeviet/nukeviet#1213]
Tình hình là thế này, mình đã từng đăng nhập vào một máy tính khác, sau đó vì bảo mật mình đã đổi mật khẩu  ở máy tính của mình nhưng sau đó không ngờ là máy tính kia vẫn đang làm việc bình thường với cái mật khẩu cũ dù mình đã đổi mật khẩu rồi. mong được hổ trợ giúp. Xin cảm ơn!

**Comment by thehung** [comment]
Bổ sung chức năng kiểm soát các phiên đăng nhập hiện hữu và "thoát tất cả
các phiên đăng nhập khác".

**Comment by coolboysorry** [comment]
help me!

**Comment by thehung** [comment]
Chức năng này hình như chưa có.
Bạn muốn thì có thể làm thủ công: xóa hết session trong thư mục session đi.

**Comment by vuthao** [comment]
@coolboysorry Bạn xem lại quy định báo lỗi nhé.
Khi tạo 1 thông báo lỗi sẽ có dòng: Please review the guidelines for contributing to this repository.

https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md

Cái cần thiết để phán đoán ở đây là bạn sử dụng phiên bản nào.

**Comment by coolboysorry** [comment]
Theo mình biết thì cả 2 phiên bảng nukeviet 3 và 4 đều không có chức năng này.
còn môi trường mình đang sử dụng là: 
Phiên bản NukeViet: NukeViet 4.0.13
Môi trường thử Nghiệm: cloud.cpm-vietnam.com.vn
Hệ điều hành: win7-64 bit
Trình duyệt web: tất cả trình duyệt

mong được giúp. xin cảm ơn!

**Comment by vuthao** [comment]
Với bản 3, đã có gói cập nhật để fix lỗi này khoảng 1 tháng.
Với bản 4 hiện tại cũng đã khắc phục lỗi này bạn.
