### ISSUE TITLE
sai path upload hình ảnh cho module ảo của new

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/nukeviet#1214]
mình tạo module ảo của news khi upload hình ảnh bị sai đường dẫn cụ thể là module members là module ảo của news

![pathupload](https://cloud.githubusercontent.com/assets/8604866/9008132/2b194072-37c2-11e5-8e41-d3794857b7ba.png)

**Comment by vuthao** [comment]
@webvangvn bạn nhớ khi thông báo lỗi, sẽ có dòng:

Please review the guidelines for contributing to this repository.

Có link tới trang: https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md

Không có những thông tin đó thì chúng tôi không biết thế nào mà kiểm tra.

Phiên bản đang phát triển hiện tại không bị lỗi như bạn thông báo.

**Comment by webvangvn** [comment]
oke, mình update từ 4.0.16 lên 4.0.21 thì bị lỗi này, tạo mới module ảo thì không bị, chỉ là các module ảo đã tạo trước khi nâng cấp thì sẽ bị lỗi như vậy, chưa biết cách sữa lỗi, tìm chưa ra value của biến $module_upload trong file news/admin/content.php
