### ISSUE TITLE
Sai đường dẫn hình ảnh khi tạo rss

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#1216]
Sai đường dẫn hình ảnh rss.png trong tập tin rss.xsl
img height="16" hspace="5" vspace="0" border="0" width="16" alt="RSS feed" src="/images/rss.png" align="left" /

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/e0199679f0b2466fdf62bae4afad1e73a01d6736
(Hiện tại để tránh lỗi cần cài đặt site ở thư mục gốc của site)

**Comment by phongaz** [comment]
Vậy nếu chạy site theo addon-domain thì sao nhỉ?
Trước đây mình dùng goddady. Domain chính nằm ở thư mục root. còn các addon domain hoặc subdomain thì thạo một một directory ngang hàng với file index.php. sau đó upload mã nguồn rồi tiến hàng cài đặt.

**Comment by vuthao** [comment]
Hiện tại nếu đặt site ở gốc domain, subdomain thì không bị lỗi:
ví dụ: http://nukeviet.vn hoặc http://demo.nukeviet.vn  thì bình thường.

Nhưng đặt:http://nukeviet.vn/demo sẽ bị lỗi hiển thị cái ảnh logo của rss (Không lỗi ảnh minh họa của bài viết). Và cái này chỉ bị trên IE, Google Chrome. và lỗi này đã có 5 năm qua nhưng chưa ai phát hiện ra.

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/1a223c12f309395ad9010678de81d06cdd7c217c
