### ISSUE TITLE
Lỗi cảnh báo: constant(): Couldn't find constant PLATFORM_UNKNOWN in file /modules/statistics/theme.php on line 187

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1217]
Lỗi xảy ra khi click xem thống kê theo Hệ điều hành.
![Uploading statistics.PNG…]()

Môi trường thử nghiệm:
hệ điều hành window 8.1
host vps plesk 12, centos 6.6
php 5.4.8
Phiên bản https://github.com/nukeviet/nukeviet/commit/40e7bce485fe750b345e4d734894a1879006e016
trinh duyet chrome Version 44.0.2403.125 m

Tương tự Lỗi xảy ra khi click xem thống kê theo Trình Duyệt

Lỗi cảnh báo: constant(): Couldn't find constant BROWSER_UNKNOWN in file /modules/statistics/theme.php on line 242

**Comment by anhtunguyen** [comment]
Bạn thử cài đặt mới và kiểm tra lại. Tôi không thấy lỗi này

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/1ab44b72103dd58f7eff4e156ce4a0181e557829
