### ISSUE TITLE
Thêm link sửa/xóa bài viết của các bài trong module about khi admin truy cập ở bên ngoài site

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1218]
Nên thêm link sửa/xóa bài viết trong module about khi admin truy cập ở bên ngoài site (trang chi tiết bài viết, vị trí tương tự như đối với các bài viết của module news) để nhất quán các tính năng.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/5b2ee97290098d951f62efd56f7783fceefc370b
