### ISSUE TITLE
Thay đổi css

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#1219]
Hiện tại ở bản develop không còn chế độ tối ưu hoá nhưng sao thay đổi css mà phải dọn dẹp hệ thống mới có thể thấy được sự thay đổi vậy

**Comment by hoaquynhtim99** [comment]
Mình thay đổi rồi ấn F5 vẫn cập nhật bình thường mà, riêng module news cần đăng nhập admin nhứ trước giờ

**Comment by HoanDateh** [comment]
Mình thử xoá cái ảnh nền mà F5 lại không thay đổi. Phải dọn dẹp hệ thống nó mới nhận

**Comment by vuthao** [comment]
Nguyên nhân là do trình duyệt cache file.
