### ISSUE TITLE
Đưa submenu vào breakcum?

### ISSUE THREAD

**Issue by levietpro** [nukeviet/nukeviet#1220]
xin các bro cho em hỏi cách đưa submenu vào trong breakcum?
cụ thể tức là như chức năng hiện tại mỗi khi vào 1 menu hay submenu cụ thể thì breakcum sẽ là :" Home >> menu/submenu hiện tại đang truy cập" . ý em muốn khi bấm vào menu News mà trong news đang có 4 submenu a,b,c,d thì khi vào menu news , breakcum sẽ là dạng "home >> News | A, B, C, D" tức là hiện các sub của news. thì có làm đc ko ? monbg các bro hướng dẫn?

**Comment by vuthao** [comment]
Hiện tại breakcum không do module menu mà do module điều khiển.
Module menu độc lập với module news, và nó chỉ có chức năng cấu hình link tùy chỉnh.
Với module News hiện tại breakcum sẽ theo phần quản lý chủ đề, và phụ thuộc vào chủ đề chính của bài viết, và nó đã hiên thị theo các cấp của chủ đề.

![cau -hinh-chu-de](https://cloud.githubusercontent.com/assets/2491500/9025664/203f8b58-3938-11e5-846e-6b629fc0c073.png)
![breakcum](https://cloud.githubusercontent.com/assets/2491500/9025665/23063292-3938-11e5-9950-d46fc5d29519.png)

**Comment by levietpro** [comment]
![submenu-breakcum](https://cloud.githubusercontent.com/assets/13252230/9025838/3215aa52-3941-11e5-8031-18243489d284.png)
ý em là như này.... có thể làm được ko a. như hình trên của e là e đang ở main của "Xã hội" nhưng nó show ra các sub của mục đó :@@

**Comment by thehung** [comment]
breadcrumbs khác với menu, đừng sử dụng lẫn lộn thế chứ @levietpro  
Xem thêm: http://dautuseo.com/breadcrumbs-la-gi/

**Comment by anhtunguyen** [comment]
Breadcrumbs cũng dùng tốt cho SEO. Google nhạn diện nó và cho hiển thị title thay cho url. Breadcrums chỉ ra vị trí của trang đang xem so với thư mục gốc, cho nên nó không phải là menu bạn nhé

**Comment by levietpro** [comment]
vâng e cám ơn  các bác, e xem khối menu kia bị nhầm cái kia là breadcum :3
