### ISSUE TITLE
Lỗi breadcum trong bản 4.0.22

### ISSUE THREAD

**Issue by levietpro** [nukeviet/nukeviet#1221]
1. Bị lỗi khi vào module news thì breadcum ko hiện là Home>Tin tức mà fai vào sub của news nó mới hiện.
2. khi đặt 1 module khác news làm mặc định thì khi truy cập trang chủ breadcum lại cứ hiện "home> tên module mặc định.
Kết lại: lúc cần hiện thì ko hiện (vào main news). lúc ko cần hiện thì lại hiện (trang chủ) ?

**Comment by vuthao** [comment]
HIện tại việc hiển thị  breadcum  còn phị thuộc vào phần:      Cấu hình ->      Cấu hình chung  : Loại bỏ tên module trên url

Nếu tính năng Loại bỏ tên module trên url, thì trên breadcum  cũng loại bỏ, bạn kiểm tra lại xem đúng chưa.

**Comment by levietpro** [comment]
e làm như a nói thì được rồi ah!!! nó đã gq đc 2 vấn đề ở trên tuy nhiên e lại có thắc mắc:
1. tính năng loại bỏ tên module trên url đó để bổ trợ cho seo chứ sao cái breadcum lại lquan đến tính năng đó ah? theo e nên tách biệt 2 cái đó ra thì sẽ ok hơn. vì e chủ ý muốn bỏ tên trên 1 module nào đó mà nó lại ảnh hưởng sang cái bread thì nó ko ổn lắm :(
2. có cách nào để em đang ở trang chủ cái bread nó ko hiện gì ko? khi vào các menu thì nó mới hiện ấy. hiện tại nó hiện là "trang nhất" :( với lại e thấy cái bread cũ nv3.4 nhìn đẹp hơn, cái mới này nhìn to quá ^^
3. các bác ko thiết kế để có thể bỏ tên nhiều / tất cả tên modul trên url; nhỉ ^^ bỏ đc là e bỏ tất nhìn dài lê thê, nhất là news vs shops :(

**Comment by vuthao** [comment]
vấn đề 1, 2 bạn có sửa trong giao diện (themes/my_theme/theme.php)
Vấn đề 3, chúng tôi sẽ không thực hiện.
