### ISSUE TITLE
Lỗi logo

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1222]
Phiên bản NukeViet	4.0.22
Phiên bản PHP	5.6.8
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ	DARWIN
Phiên bản Database	mysql 5.6.24
------------------------------
Cấu hình chọn logo là hình png nhưng ra trang chủ không hiệu lực nó chỉ chạy logo.svg
mà định dạng .svg không phải ai cũng biết làm.
Đây không biết có phải lỗi hay không nữa.

**Comment by anhtunguyen** [comment]
Bạn xóa file svg đi nó sẽ hiển thị png. Đó là dụng ý chứ không phải lỗi
