### ISSUE TITLE
Lỗi tìm kiếm trên giao diện mobi

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#1223]
Khi chuyển về giao diện mobi, nhấp vào menu gõ từ tìm kiếm là nuke 
![2015-08-02_20-06-38](https://cloud.githubusercontent.com/assets/8481170/9026272/8091442c-3953-11e5-99f3-c4596aa33ea5.png)
Thì được báo lỗi 404
![2015-08-02_20-16-08](https://cloud.githubusercontent.com/assets/8481170/9026276/943a8132-3953-11e5-9cd2-1a895c2f751a.png)

**Comment by anhtunguyen** [comment]
Hiện các bạn chưa test theme mobile vội. Nó vẫn đang được hoàn thiện

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/013b093144ca4a007cbf2e3e2c1bc9687024cb0e
