### ISSUE TITLE
Về biến bodyhtml trong module Page và các module ảo

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#1224]
Trong phần cài đặt cơ sở dữ liệu của module Page không có biến bodyhtml nhưng trong phần cài đặt dữ liệu của modules siteterms thấy báo lỗi
[Sun, 02 Aug 2015 19:59:14 +0700] [127.0.0.1] [Notice(8): Undefined variable: bodyhtml] [FILE: /modules/page/language/data_vi.php] [LINE: 30]
[Sun, 02 Aug 2015 19:59:14 +0700] [127.0.0.1] [Notice(8): Undefined variable: bodyhtml] [FILE: /modules/page/language/data_vi.php] [LINE: 35]
[Sun, 02 Aug 2015 20:38:14 +0700] [127.0.0.1] [Notice(8): Undefined variable: module] [FILE: /admin/modules/check_sample_data.php] [LINE: 20]
[Sun, 02 Aug 2015 20:38:18 +0700] [127.0.0.1] [Notice(8): Undefined variable: bodyhtml] [FILE: /modules/page/language/data_vi.php] [LINE: 23]

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/ffc3f0f73621cc130b57abb5cd851ba5230d2364
