### ISSUE TITLE
Lỗi tiền tố của cookie, session

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1225]
Các tiền tố này vẫn được để là nv3

```
	private $cookie_prefix = 'NV3';
	private $session_prefix = 'NV3';
	private $cookie_key = 'nv3';
```

nên chuyển nó thành nv4 cho đúng với bản 4

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commits/develop
