### ISSUE TITLE
Việc cài đặt bản develop mới nhất

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#1227]
Việc cài đặt bản develop mới nhất không thực hiện được
![2015-08-04_06-56-56](https://cloud.githubusercontent.com/assets/8481170/9050256/101d2bf6-3a76-11e5-8be0-a1ed7d2f9259.jpg)

**Comment by hoanglongvnpt** [comment]
Tải lại code đi bạn, có thể lúc bạn tại thì đội code đang chỉnh sửa code.
Mình cài thấy tạm ổn rồi.
![001](https://cloud.githubusercontent.com/assets/11238423/9050587/7300f3b2-3a79-11e5-86db-4604409f4f11.png)

**Comment by anhyeuviolet** [comment]
:D bác @hoanglongvnpt  đề nghị không show hàng trên đây.

**Comment by HoanDateh** [comment]
@hoanglongvnpt Mình tải code mới nhất mà

**Comment by levietpro** [comment]
đúng rồi. em cũng vừa tải code xong về cài cũng bị báo lỗi như thế này. "NV_FILES_DIR 	Không tồn tại" ...như nào bây giờ :3

**Comment by vuthao** [comment]
mình đã sửa lại tại: https://github.com/nukeviet/nukeviet/commit/343ccb4d73809092b97ab108f88b2b89d5c60fde
Các bạn cập nhật code nhé.
