### ISSUE TITLE
Hỏi? cách đưa đồng hồ vào theme!

### ISSUE THREAD

**Issue by levietpro** [nukeviet/nukeviet#1228]
Các bro cho em hỏi đưa đồng hồ ra ngoài theme như nào mà em thấy bản 3.4 có đồng hồ mà sang bản mới này ko thấy đồng hồ đâu, em thêm {NV_DIGICLOCK} mà cũng ko thấy gì ?!?!

**Comment by thehung** [comment]
Những nội dung hỏi - đáp thế này bạn lên forum nhé, đừng lạm dụng trang báo lỗi.

**Comment by levietpro** [comment]
có cái khó là trên 4rum chưa có topic hỗ trợ cho các phiên bản develope này bác ah? nên hỏi ở đó cũng khó nên e fai mang qua đây hỏi vì vđề này nó thuộc về NV4.0.22 mới bị mất đồng hồ chứ bản RC thì vẫn có đổng hồ bác ah :(

**Comment by thehung** [comment]
Bạn cũng có thể qua đây để thảo luận: http://fb.com/groups/nukeviet/
