### ISSUE TITLE
Vấn đề các button share bản tin của news

### ISSUE THREAD

**Issue by anhtunguyen** [nukeviet/nukeviet#1229]
Các button này được chạy đồng thời với HTML trước khi các file javascript của hệ thống chạy. Việc này khiến cho các lệnh thực thi tức thời của JS bị đình trệ lại, dẫn đến trang thể hiện không đúng như mong muốn. Đặc biệt khi các máy chủ của các button share đó bị die thì việc load trang của mình cũng gặp rắc rối. Vì vậy nên viết lại để các nút này chỉ được hiển thị sau khi các js hệ thống chạy xong.

**Comment by nhimthulinh** [comment]
thêm cấu hình hiện thị hoặc tắt đi cho tiện

**Comment by thehung** [comment]
Cấu hình bật tắt thì có rồi, quan trọng là bật mà phải nhanh nhé @nhimthulinh

**Comment by anhtunguyen** [comment]
Mọi người chưa hiểu hết vấn đề tôi nêu ra.
Thực tế mấy cái nút đó link đến javascript ở máy chủ của facebook, google... Nó đang được chạy đồng thời với mã HTML. Mà hiện tại chúng ta đã quy định là: Tất cả mã javascript đều được chạy sau khi html load xong (Mọi người view source sẽ thấy tất cả js đều đc kéo xuống dưới footer). Nếu các nút share này chạy ngon lành thì mất khoảng 2 giây. Nhưng nếu máy chủ của chúng có vấn đề thì site nukeviet sẽ bị đứng khoảng 30 giây, tất cả các js hệ thống của mình đều bị đình trệ, html bị hiển thị méo mó.
Tôi biết là có thể bật/tắt mấy nút đó. Nhưng trường hợp tôi vẫn muốn bật chúng, nhưng lại không muốn nó ảnh hưởng đến tốc độ hiển thị html thì sao?

**Comment by hoaquynhtim99** [comment]
Cái này làm y như cái google MAP trong block company info chắc là ổn đó anh. JS được load ra và chạy từ

```javascript
$(window).load(function(){
   // Run ......
});
```

**Comment by anhtunguyen** [comment]
Dũng xử lý luôn đi

**Comment by hoaquynhtim99** [comment]
Đã xử lý tại: https://github.com/nukeviet/nukeviet/commit/6db739469bb8e8f29182c7ff095f4bf5c0fd423d

**Comment by anhtunguyen** [comment]
Tks em

**Comment by vuthao** [comment]
@hoaquynhtim99 Nếu không có property fb:app_id vẫn có thể share-button và like được nhé.

**Comment by anhtunguyen** [comment]
Dũng kiểm tra lại. Giờ thì bật chúng như không. Không thấy đâu cả (nút facebook)

**Comment by hoaquynhtim99** [comment]
appid là thông số require đối với xfbml nếu không có nó báo lỗi:
```
Invalid App Id: Must be a number or numeric string representing the application id.
FB.getLoginStatus() called before calling FB.init().
```
Cần thiết thì sửa lại cho hiện lên thôi anh

**Comment by anhyeuviolet** [comment]
Nếu không có AppID thì dùng
//connect.facebook.net/{FACEBOOK_LANG}/sdk.js#xfbml=1&version=v2.3
Còn có thì dùng
//connect.facebook.net/{FACEBOOK_LANG}/all.js#xfbml=1&appId={FACEBOOK_APPID}

cái này là để tách bạch với chuyện không có FB ID thì vẫn dùng các nút share like hoặc thêm ô comment được. Chứ trước đây thì cứ tắt cái nút share là nó tắt luôn cái ô comment FB mới thêm vào. Cũng khá bất tiện.

**Comment by hoaquynhtim99** [comment]
Mình đã thử code của bạn và vẫn có thông báo
```
Invalid App Id: Must be a number or numeric string representing the application id.
```

**Comment by anhyeuviolet** [comment]
Thực ra chỉ cần 
```
//connect.facebook.net/en_US/all.js#xfbml=1

Là đủ để có nút share và Like.
Dòng trong main.js mình sửa thành
```
 a.src = "//connect.facebook.net/" + $('[property="og:locale"]').attr("content") + "/all.js#xfbml=1", d.parentNode.insertBefore(a, d));
```

Thì nó vẫn hiện khá bình thường

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/a3138d9128c9e14028f5ef9d35553e731e7553a5
