### ISSUE TITLE
Lỗi nghiêm trọng: Không phân trang tìm kiếm trong module shops và lọc sản phẩm

### ISSUE THREAD

**Issue by 0zozozo** [nukeviet/nukeviet#1230]
Hiện mình sử dụng các block sau:
- module block_filter_product (lọc sản phẩm)
- global block_search (tìm kiếm sản phẩm )

Khi dùng chỉ hiển thị 12 sản phẩm ở trang chủ mà không có phân trang. Lỗi này làm ảnh hưởng rất lớn đến hoạt động của module shops.
Mình cũng đã cố gắng sửa nhưng không được. 
Mong các bạn giúp đỡ. Tks nhìu !

**Comment by vuthao** [comment]
Khi tạo  thông báo lỗi có dòng: 

Please review the guidelines for contributing to this repository.

Bạn vui lòng đọc lại quy đinh báo lỗi đó, và đăng vào đúng khu vực, Với module shop bạn đăng tại đây: https://github.com/nukeviet/module-shops
