### ISSUE TITLE
Góp ý block category của new

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1231]
Hiện tại button xổ xuống các menu con mũi tên quay sang trái

![image](https://cloud.githubusercontent.com/assets/10300770/9077864/a9842636-3b5d-11e5-8283-9c2b4c24ce91.png)

và khi bấm xổ xuống thì mũi tên quay xuống

![image](https://cloud.githubusercontent.com/assets/10300770/9077878/cd0f2fd8-3b5d-11e5-89f6-93c4dc45cce6.png)

như vậy không đúng.

nên để khi không xổ thì mũi tên quay xuống để người dùng biết là bấm vào sẽ xổ xuống các menu con
còn khi bấm xổ xuống thì hiển thị mũi tên quay lên trên để người dùng biết là bấm lên để đóng

**Comment by anhtunguyen** [comment]
Fixed https://github.com/nukeviet/nukeviet/commit/54ab0188087669a7c15153a1090d29e697d653f6
