### ISSUE TITLE
Lỗi tpl block global.counter.tpl 

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1232]
![image](https://cloud.githubusercontent.com/assets/10300770/9077925/7ee22134-3b5e-11e5-90db-69707bf25dc1.png)

block này dùng html giống với global.counter_button.tpl nên khi hiển thị bị lỗi như thế này

**Comment by anhtunguyen** [comment]
Fixed https://github.com/nukeviet/nukeviet/commit/54ab0188087669a7c15153a1090d29e697d653f6
