### ISSUE TITLE
Lỗi xung đột Global block_catalogs giữa Module News với Shops Nukeviet 4.022

### ISSUE THREAD

**Issue by thanhhaionline** [nukeviet/nukeviet#1234]
Lỗi xung đột Global block_catalogs giữa Module News với Shops Nukeviet 4.022, khi kéo Global block_catalogs của Shops ra thì Catalogs bị trắng, hạn chế ký tự, không thu gọn được +, buộc phải kéo Global block_catalogs của News ra thì Catalogs của Shops mới sd được, Mong đc fix sớm
![loi](https://cloud.githubusercontent.com/assets/13663581/9091625/74edb978-3bcb-11e5-8d5a-5fd89205ce29.jpg)
![loi2](https://cloud.githubusercontent.com/assets/13663581/9091716/fc5bb22a-3bcb-11e5-959d-1bb8f0c42492.jpg)

**Comment by vuthao** [comment]
Lỗi của module shops bạn báo lỗi ở đúng kho code của nó nhé: https://github.com/nukeviet/module-shops

**Comment by thanhhaionline** [comment]
Module shop vẫn sd bình thường với các phiên bản <4.022 mà a

**Comment by nhimthulinh** [comment]
kiểm tra trong file block.catalogsv.tpl xem đúng đường dẫn css và js chưa là đc

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-shops/commit/dac36ac7969b1504ff1ac9c98ba77badf40981b1

**Comment by thanhhaionline** [comment]
a ơi, lỗi ko xóa được sản phẩm trong Shops
