### ISSUE TITLE
Lỗi khi Breadcrumbs

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#1235]
Trong bản develop mới nhất
Nếu trong cấu hình chung phần Loại bỏ tên module trên url để trống thì phần hiển thị ngày tháng năm không sao
Nếu phần Loại bỏ tên module trên urlrl là module News thì hiển thị trên main như sau
![1](https://cloud.githubusercontent.com/assets/8481170/9092319/b02a8814-3bcf-11e5-9109-2e000fd2287f.jpg)
Các funs khác hiển thị (của module News) như sau
![2](https://cloud.githubusercontent.com/assets/8481170/9092340/d6c507b0-3bcf-11e5-830a-d73e6ec79413.jpg)
Các module khác 
![3](https://cloud.githubusercontent.com/assets/8481170/9092479/a5475606-3bd0-11e5-830e-2027e370c670.jpg)

**Comment by anhtunguyen** [comment]
Ngày tháng năm chỉ hiển thị khi ở trang chủ hoặc các trang chính của module. Đó không phải lỗi mà là nó phải nhường chỗ cho breadcrumbs
