### ISSUE TITLE
Lỗi cảnh báo khi vừa cài đặt xong

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1237]
Bản DEV : 
https://github.com/nukeviet/nukeviet/commit/950a9b5b302f9c9fe1b64134c3c5fdacff55bfd1
Môi trường: 
Windows 10
ApacheFriends XAMPP Version 5.6.8
Firefox latest.
Lỗi : 
 Lỗi cảnh báo: getimagesize(D:/xampp/htdocs/dev/data/tmp/news_10_nukeviet-nhantaidatviet2011_400-.jpg): failed to open stream: No such file or directory in file /includes/core/filesystem_functions.php on line 783

Khi dọn hệ thống xong thì không thấy nữa.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/791e1508dca52322229647fe5bb8078243ecf858
