### ISSUE TITLE
Lỗi Captcha khu vực liên hệ

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1238]
![captcha](https://cloud.githubusercontent.com/assets/6290970/9101450/4122a040-3c11-11e5-937a-d5d75274d70b.PNG)
-------------------
Bản DEV :
950a9b5
Môi trường:
Windows 10
ApacheFriends XAMPP Version 5.6.8
Firefox latest.

**Comment by vuthao** [comment]
Mình kiểm tra môi trường giống bạn nhưng không bị
Cho mình teamview vào máy bạn để kiểm tra nhé, nhắn qua nic facebook: thaonukeviet

**Comment by anhyeuviolet** [comment]
Em bị lỗi chỗ này.
Chỉ mất hình khi mở debug trong mainfile.php
Xin phép close ạ !
