### ISSUE TITLE
Hình ảnh của block Global Free Content thiếu thẻ ALT

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1239]
![blck-free-content](https://cloud.githubusercontent.com/assets/6290970/9103540/74b5e986-3c29-11e5-9f2f-bb01547ab2ba.PNG)
Hai ảnh này còn thiếu ALT

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/ac1fa1343d33ede51ade17717f78f0bebc8a0aed
