### ISSUE TITLE
[Module Comment] Nút ẩn hiện comment không hoạt động

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1240]

**Comment by vuthao** [comment]
Mình thấy nút: Ẩn/Hiện ý kiến vẫn hoạt động mà 
(Nó chỉ hoạt động khi có nội dung bình luận nhé.)

**Comment by anhyeuviolet** [comment]
Ah vậy ạ . Hiz
Em nhầm. Trước chính sao mà click là nó ẩn toàn bộ khối comment luôn, tưởng giờ vẫn như thế.
