### ISSUE TITLE
[Góp ý] Thứ tự nạp CSS

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1241]
Trích một đoạn thứ tự CSS như sau : 
1/ dev/themes/default/css/mangaka.css
2/ dev/themes/default/css/font-awesome.min.css
3/ dev/themes/default/css/bootstrap.non-responsive.css
4/ dev/themes/default/css/style.css
5/ dev/themes/default/css/style.non-responsive.css

Trong đó CSS nạp trên cùng là của module. 
Không rõ ý đồ thiết kế là thế nào, nhưng module của mình có một số CSS ghi đè lên global CSS, và chỉ kích hoạt trong module đó. 
Nhưng nếu thứ tự nạp như thế này thì điều đó là không thể làm được.
Vậy liệu có thể hay không việc nạp các CSS hệ thống trước, sau đó tới CSS module và cuối cùng là CSS tuỳ chỉnh trong cấu hình theme ?

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/d8f5b583cbb2dfceeade54ab33c32e749fff7bf8
