### ISSUE TITLE
[CSS] Module ngoài hệ thống không nạp được CSS

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1242]
Tag : 4.0.22
Module : mangaka
Cấu trúc CSS : 
```
themes\default\css\mangaka.css
themes\default\css\mangaka_tab.css
```

Tuy vậy khi cài lại khá nhiều lần thì CSS của module này vẫn không được nạp. 
Cho tới phiên bản https://github.com/nukeviet/nukeviet/commit/950a9b5b302f9c9fe1b64134c3c5fdacff55bfd1 thì vẫn nạp CSS bình thường.

Không biết trong cấu trúc module có cần thay đổi gì để nạp được CSS của module không.

**Comment by hoaquynhtim99** [comment]
Cái này có vẻ nghiêm trọng
```php
$html_links += nv_html_links( false );
```
Em sửa thành 
```php
$html_links = array_merge_recursive( $html_links, nv_html_links( false ) );
```
Cơ mà lỡ phát hành mất, anh @vuthao  xem thế nào

**Comment by anhtunguyen** [comment]
Đây đúng là lỗi khá lớn.
Cần phải sửa ở 3 file: user_function.php và 2 file theme.php của 2 theme trong hệ thống.
Anh sẽ fix nó sớm.

**Comment by anhtunguyen** [comment]
https://github.com/anhtunguyen/nukeviet/commit/b0d06556240c174e157224c1428d79513277a59d
