### ISSUE TITLE
Lỗi unserialize 

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#1243]
Khi cài mới hệ thống chuyển từ admin sang site thấy thông báo lỗi
Thông báo từ Hệ thống
Nên chú ý Nên chú ý: unserialize(): Error at offset 163 of 205 bytes in file /includes/core/user_functions.php on line 108
Cấu hình máy chủ (Localhost)
Phiên bản NukeViet	4.0.22Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.5.27
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Win32) OpenSSL/1.0.1m PHP/5.5.27, apache2handler
Hệ điều hành máy chủ	WINDOWS NT
Phiên bản Database	mysql 5.6.25

**Comment by vuthao** [comment]
Bạn thử cài đặt xem phiên bản hiện tại đã hết lỗi đó chưa nhé.

**Comment by vuthao** [comment]
Phiên bản hiện tại tại nhánh develop lỗi này đã được sửa.
