### ISSUE TITLE
Đề xuất công cụ ping

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1244]
Hiện tại công cụ ping chỉ được dùng cho module news, trong khi thực tế người quản trị muốn ping nội dung cho nhiều module khác sau khi cập nhật nội dung (dơwnload, page, shops,....).
Để tiện trong việc lập trình, em nghĩ đến đưa công cụ này vào công cụ seo, lập trình lại module (sau lệnh cập nhật thành công), muốn ping thì chuyển đến func ping (truyền vào url cần ping) của module seotools.

**Comment by vuthao** [comment]
Công cụ này đã lập trình theo hướng dùng cho tất cả các module.

Các module muốn làm cần tham khảo module news để áp dụng.
