### ISSUE TITLE
[Lỗi Rewrite] Không nhận cấu hình rewrite ở Sub domain

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1245]
Hiện tại mình có một cái host bên namecheap.
Dùng Cpanel X11, cấu hình PHP thay từ 5.2 cho tới 7.0
Tại tag 4.0.22, khi clean install từ sub domain dạng
dev.tradacongnghe.com thì bị báo không tương thích rewrite.
Nếu cài từ tradacongnghe.com/dev/ thì lại nhận rewrite bình thường.
Chỉnh trong host thế nào cũng không được.
Không biết phần này phải xử lý thế nào. Đã thử với tag 4.0.21 cũng không hề khả quan. :(

**Comment by vuthao** [comment]
dev.tradacongnghe.com --> upload lại code và cài mới lại xem bạn.

**Comment by anhyeuviolet** [comment]
Em cài mới anh ơi.
Tải commit này
https://github.com/nukeviet/nukeviet/commit/f569b09449199ef5bf78a982e6d175660f033e46

**Comment by vuthao** [comment]
Gửi cho mình tài khoản qua email thao a còng vinades chấm vn mình kiểm tra xem thế nào.

**Comment by anhyeuviolet** [comment]
Em gửi mail rồi. Anh ktra hộ em với.
Vào 07-08-2015 16:43, "Vu Thao" <notifications@github.com> đã viết:

**Comment by vuthao** [comment]
Mình đã nhận được, tối mình kiểm tra.

**Comment by anhyeuviolet** [comment]
Sau khi up lại và xả code 3 lần thì tự nhiên nó nhận.
Cái này chắc để test thêm vài lần nữa rồi sẽ khẳng định lại lỗi sau ạ.
