### ISSUE TITLE
Lỗi cài đặt NV4022

### ISSUE THREAD

**Issue by yeunukeviet** [nukeviet/nukeviet#1247]
- Phiên bản NukeViet: 4.0.22
Môi trường thử Nghiệm:  hosting

- Các thông tin khác về phần mềm webserver, PHP và cơ sở dữ liệu:  	
Phiên bản PHP 	5.3.10-1 ubuntu 3.19
Giao thức giữa máy chủ và PHP 	Apache/2.2.22 (Ubuntu), cgi-fcgi
Hệ điều hành máy chủ 	LINUX
Phiên bản Database 	mysql 5.5.44-0 ubuntu 0.12.04.1

Cài thử trên host.
Chỉ có 1 điều kiện không tương thích:

Magic Quotes GPC
Nên tắt
Không tương thích
(Đề nghị cho biết phải làm gì với không tương thích này)

Cài xong, vào trang chủ thấy báo lỗi:

Thông báo từ Hệ thống

Lỗi cảnh báo Lỗi cảnh báo: include(/hp/mv/www/nv/nv4022/modules/voting/language/vi.php) [function.include]: failed to open stream: No such file or directory in file /modules/voting/blocks/global.voting_random.php on line 73

Nên chú ý Nên chú ý: Undefined variable: lang_module in file /modules/voting/blocks/global.voting_random.php on line 98

Nên chú ý Nên chú ý: Undefined variable: lang_module in file /modules/voting/blocks/global.voting_random.php on line 102

Nên chú ý Nên chú ý: Undefined variable: lang_module in file /modules/voting/blocks/global.voting_random.php on line 103

Sau đó web vẫn hoạt động bình thường.
Đề nghị cho biết phải làm gì với không tương thích khi cài đặt!

**Comment by vuthao** [comment]
Bạn kiêm tra trên host có file /modules/voting/language/vi.php không.
Nhiều khả năng là do upload thiếu file.

**Comment by yeunukeviet** [comment]
Đúng là thiếu file /modules/voting/language/vi.php 
Cảm ơn bạn đã trả lời nhanh chóng và chính xác
