### ISSUE TITLE
Cho hỏi Module freecontent

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#1248]
Cấu hình máy chủ
Phiên bản NukeViet	4.0.22Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.5.27
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Win32) OpenSSL/1.0.1m PHP/5.5.27, apache2handler
Hệ điều hành máy chủ	WINDOWS NT
Phiên bản Database	mysql 5.6.25

Khi vào modules  freecontent tạo khội thứ 2
![1](https://cloud.githubusercontent.com/assets/8481170/9140794/d55c0f2e-3d5d-11e5-9f62-48209bceeb68.png)
Tạo nội dung cho khối mới
![2](https://cloud.githubusercontent.com/assets/8481170/9140804/f071c092-3d5d-11e5-98d5-400180a694bb.png)
Nhưng vào cả hai khối thì thấy nội dung cả hai khối như nhau và khi thêm nội dung mới không thể lựa chọn nội dung đó thuộc khối nào
![3](https://cloud.githubusercontent.com/assets/8481170/9140827/22730d4e-3d5e-11e5-8a81-007c66f8a145.png)
![4](https://cloud.githubusercontent.com/assets/8481170/9140828/28a0335e-3d5e-11e5-9b01-75a6327ece48.png)

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 xem lại

**Comment by anhtunguyen** [comment]
Fixed https://github.com/anhtunguyen/nukeviet/commit/8a26c91b247bca3c2ce5617eb986be472d79274c
