### ISSUE TITLE
[Giao diện] Thiếu class clear trong detail của news

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1250]
Trong theme default,
https://github.com/nukeviet/nukeviet/blob/develop/themes/default/modules/news/detail.tpl
Khoảng dòng 201-202 thiếu 
```
<div class="clear">&nbsp;</div>
```
Khi đó xem tin chi tiết, dòng "Những tin cũ hơn" sẽ không xuống dòng gây mất thẩm mỹ.

**Comment by anhtunguyen** [comment]
https://github.com/anhtunguyen/nukeviet/commit/73ffa5ff54857b4a434973abcfcbce030189db15
