### ISSUE TITLE
[Lỗi] Chức năng CHMOD trong cấu hình site

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1252]
![image](https://cloud.githubusercontent.com/assets/6290970/9152943/9b7f200a-3e68-11e5-9802-79e9b3016443.png)
Bên trên là hình ảnh của khu vực Thông tin => Cấu hình Site.
Khi click vào  (Chmod lại thư mục cần thiết) thì khi chạy xong cũng không có hiệu lực, các thực mục bên trong data/cache/ vẫn chưa được CHMOD.

Tuy vậy, sau khi CHMOD thủ công thì trong ACP cũng vẫn báo là Cần chmod để PHP ghi được file.
![image](https://cloud.githubusercontent.com/assets/6290970/9152951/0ff4354c-3e69-11e5-8c16-cc41601aa55f.png)

---------------------------
Phiên bản NukeViet	4.0.22
Phiên bản PHP	5.4.33
Giao thức giữa máy chủ và PHP	Apache, cgi-fcgi
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.5.42-cll-lve

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/d12276442a429fbd0974a1c6562a9dc251cb5d71
