### ISSUE TITLE
Tùy chọn ẩn block trên PC

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1253]
> Ẩn trên thiết bị:	 Ẩn trên mobile   Máy tính bảng

Muốn ẩn block trên PC thì không biết làm sao.

**Comment by anhtunguyen** [comment]
Theo anh thì Thảo nên sửa lại thế này: bỏ "ẩn" đi mà thay bằng: Hiển thị (tích để chọn): Mobile - tablet - robot - các trường hợp khác - tất cả (Mặc định là tất cả ). Như thế sẽ universal hơn

**Comment by vuthao** [comment]
Tính năng này được viết ra nhằm mục đích các thiết bị như mobile Máy tính bảng có thể không cần load các block này, cho việc tải mã html là ít nhất.
Nếu ẩn trên PC, thì  tắt luôn block đó đi.

**Comment by hongoctrien** [comment]
Vẫn sẽ phải tính đến trường hợp hiện trên mobile nhưng ẩn trên Pc nữa chứ a

**Comment by vuthao** [comment]
hê hê, được voi đòi hai bà trưng nhé @hongoctrien  :)
Theo ý của anh sẽ sửa lại thành: Hiển thị (tích để chọn): Mobile - tablet - PC
(không phải là mobile, tablet , thì là pc)

**Comment by anhtunguyen** [comment]
Mobile - tablet - others - all

**Comment by hongoctrien** [comment]
(y) :D

**Comment by nhimthulinh** [comment]
ẩn tất cả - Mobile - tablet  :v:

**Comment by vuthao** [comment]
update: https://github.com/nukeviet/nukeviet/pull/1279
