### ISSUE TITLE
Lỗi phần maps trong block company info ?

### ISSUE THREAD

**Issue by levietpro** [nukeviet/nukeviet#1254]
khi nhập địa chỉ hệ thống thả ghim đúng địa chỉ rồi nhưng sau khi lưu cấu hình block ấn vào nó lại dẫn ra tận giữa...thái bình dương @@ xong ấn vào sửa block để cấu hình lại thì ghim bản đồ lại thả vào 1 điểm khác khác cả 2 điẻm ở trên, ?!!? ở phiên bản nv4.0.21 ko có lỗi này :3

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 xem lại

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/e4190051b0828b3f2ff5eb018166bce85e376f2c

**Comment by levietpro** [comment]
@hoaquynhtim99 mình chép đè file js đã fix bug đó lên file cũ, xong ra mở block info nó ko load đc các trường để điền thtin là sao?
