### ISSUE TITLE
Lỗi (định dạng) sử dụng code trong editor

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1257]
VD chèn một đoạn code vào editor

```html
<div class="form-group">
	<label class="col-sm-5 col-md-3 control-label"><strong>{LANG.description}</strong></label>
	<div class="col-sm-14 col-md-21">
		<textarea class="form-control" name="description" rows="4">{ROW.description}</textarea>
	</div>
</div>
```
Khi lưu lại sẽ mất định dạng (ký tự tab)
```html
<div class="form-group">
<label class="col-sm-5 col-md-3 control-label"><strong>{LANG.description}</strong></label>
<div class="col-sm-14 col-md-21">
<textarea class="form-control" name="description" rows="4">{ROW.description}</textarea>
</div>
</div>
```

**Comment by vuthao** [comment]
Tạm thời các bạn có thể sửa:
includes/class/optimizer.class.php
sửa lại dòng 261:
return preg_replace( '/^\s+|\s+$/m', '', $this->_content );

thành  $this->_content;

**Comment by hongoctrien** [comment]
Nó sẽ còn 1 vấn đề này nữa a.
https://github.com/nukeviet/nukeviet/issues/1259

**Comment by anhyeuviolet** [comment]
Hôm qua còn vợt lên thì bị. Còn tưởng là còn vợt sai nên làm mấy lần luôn :(

**Comment by vuthao** [comment]
Fixed: https://github.com/vuthao/nukeviet/commit/37c82cadff6c84335c82d547d74f1110dedda77b
