### ISSUE TITLE
Không chuyển giao diện từ mobile sang PC được khi đăng nhập quản trị.

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1258]
NueViet 4.0.22

Không chuyển giao diện từ mobile sang PC được khi đăng nhập quản trị do công cụ admin che đi.
Dẫn tới việc không chuyển sang giao diện PC được để cấu hình

**Comment by anhtunguyen** [comment]
Anh sẽ trình bày admin toolbar trộn lẫn với nút user trên thanh công cụ khu vực header. Khi đã là admin thì tất cả các tính năng cho admin được hiển thị trong popup khi click vào button user. Chắc hợp lý?

**Comment by anhtunguyen** [comment]
https://github.com/anhtunguyen/nukeviet/commit/df686bb2c2d9b0f34aee75154f62ac4588c01325
