### ISSUE TITLE
Không chèn được các link dạng <link /> <script>...

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1259]
```html
<link rel="stylesheet" type="text/css" href="/themes/default/css/jquery.metisMenu.css" />
```

Khi chèn dòng này vào editor, class optimizer nó hiểu luôn là dòng này của giao diện, nên gom lên đầu trang luôn, kết quả là mất luôn dòng này trong editor và đưa vào trong head.

**Comment by anhtunguyen** [comment]
Chèn vào nội dung hiển thị hả?

**Comment by hongoctrien** [comment]
Vâng a. Trường hợp muốn hiểu thi ra màn hình

**Comment by anhtunguyen** [comment]
Vậy đây là lỗi bảo mật đấy Thảo

**Comment by vuthao** [comment]
em kiểm tra không thấy bị.
Đây là mã html khi hiển thị ra ngoài site:

<code class="language-html">&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/themes/default/css/jquery.metisMenu.css&quot; /&gt;</code></pre>

Triển mô tả rõ module nào nhé.

**Comment by anhtunguyen** [comment]
Triển viết cụ thể xem ở module nào bị như vâyj?

**Comment by hongoctrien** [comment]
oh, không, có vẻ như cái này do module của em viết.
Cụ thể là em lưu dòng đó vào textarea (em mã hóa textarea để có thể lưu ký tự đặc biệt vào CSDL), và khi hiển thị lên thì nó gom lên head như em nói.
Còn dùng trong editor thì vẫn hiển thị tốt. 
Em close nhé :D

**Comment by anhtunguyen** [comment]
Dọa anh em quá!

**Comment by hongoctrien** [comment]
hihi.
Có gIải pháp nào giúm em không @anhtunguyen ơi. :D
http://developers.mynukeviet.net/code/Code-tim-kiem-hien-thi-du-lieu-su-dung-select2-4/#tab_code_html
Ở đây em có chèn 2 dòng là 
```
<link rel="stylesheet" href="/js/select2/select2.min.css">
<script type="text/javascript" src="/js/select2/select2.min.js"></script>
```
Nó gom hết lên head và footer luôn :v

**Comment by anhtunguyen** [comment]
Cái này anh Thảo rành hơn anh.
Quan trọng nhât là khi lưu content đuợc lấy từ editor vào CSDL em cần gọi nó kiểu như:
$bodytext = $nv_Request->get_editor( 'bodytext', '', NV_ALLOWED_HTML_TAGS );
còn khi lấy nó ra thì thế này:
$bodytext = htmlspecialchars( nv_editor_br2nl( $row['bodytext'] ) );

Em mở module News hoặc Page ra tham khảo

**Comment by hongoctrien** [comment]
Vâng. Em cảm ơn nhé.
