### ISSUE TITLE
Lỗi khi ở giao diện mobile /tablet không có chức năng chuyển giao diện?

### ISSUE THREAD

**Issue by levietpro** [nukeviet/nukeviet#1262]
Khi ở giao diện mobile ko có nút chức năng chuyển giao diện rất bất tiện. đề nghị bổ sung :|

**Comment by anhtunguyen** [comment]
Có. Click vào góc trái bên dưới, tìm đến gần dòng copyright

**Comment by levietpro** [comment]
ah  e thấy rồi . nhưng cái block contact ở mobile và destop ko lấy cùng nội dung cho đỡ fai cấu hình nhiều nhỉ !??!

**Comment by anhtunguyen** [comment]
Block contact nào bạn?
P/S: Nếu là câu hỏi mới thì bạn nên tạo riêng issue chứ đừng viết chung nhé.

**Comment by levietpro** [comment]
cái thông tin công ty ở phía trên chỗ chuyển giao diện bác nói ấy?
