### ISSUE TITLE
Lỗi không hiển thị hình ảnh đại diện của chuyên mục trong module news

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#1263]
Hiện tại khi thêm ảnh đại diện vào chuyên mục trong module news ko thể hiển thị ngoài site, kiểm tra code html chưa có đoạn mã để xuất icon đó và trong themes.php cũng chưa có

**Comment by nhimthulinh** [comment]
đây không phải lỗi mà do ko hiện ra mà thôi, tùy theo nhu cầu mà lấy ra. chứ mặc định nó ẩn vì ko cần thiết lôi ra :3

**Comment by trinhthinhhp** [comment]
@nhimthulinh không có code lấy ra kiểu gì vậy?

**Comment by nhimthulinh** [comment]
thì viết thêm thôi bạn :v lấy được tên chuyên mục, lấy đc nội dung miêu tả chẳng lẽ ko lấy đc hình ảnh ra

**Comment by tuyenclub** [comment]
Nhím nói thế không hợp lý cho lắm. Nếu người dùng tay ngang thì sao viết được???
Đã có chức năng trong admin mà không cho người ta khả năng hiển thị ra ngoài trang thì thà bỏ đi cho đỡ rườm rà.

**Comment by hongoctrien** [comment]
Hiện nó mới dùng cho thằng `og:image`, để mình thêm cho nó hiển thị ra.
