### ISSUE TITLE
Lỗi trên giao diện mobile

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1264]
không gửi bình luận được trên giao diện mobile.
Không gửi đặt hàng được 
Bị lag hoặc giật giật khi kéo thanh điều hướng xuống dưới.
ví dụ nhất là trong phần đặt hàng, kéo miết xuống ko được

**Comment by anhtunguyen** [comment]
"Không gửi đặt hàng được" là của shops? Nếu đúng vậy thì bản NV4.0.22 hiện chưa hỗ trợ shops. Chắc các bạn phải đợi thời gian nữa

**Comment by nhimthulinh** [comment]
giao diện pc chạy bình thườnga nh, đặt hàng cmt bình thường còn trên mobile thì bị

**Comment by vuthao** [comment]
@nhimthulinh hiện tại chúng tôi đang tập trung làm cho NukeViet xong mới quay lại làm tiếp shop. (Do không đủ người để làm tất cả cùng lúc)

**Comment by anhyeuviolet** [comment]
Hiện tại em test thì mobile của shops cũng đặt hàng được. Nhiều khả năng anh @nhimthulinh  dính vấn đề giống cái này https://github.com/nukeviet/nukeviet/issues/1271; do đó mà JS ko nạp ổn định dẫn tới không đặt hàng được.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/42685e4d465ce64d6b0f66661a87caf0e292122a
