### ISSUE TITLE
Lỗi chèn được block trong bài viết news

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1265]
![nh ch p man hinh 2015-08-11 luc 20 06 25](https://cloud.githubusercontent.com/assets/5910584/9198178/7eda7140-4064-11e5-98df-29af0a45f716.png)
trong bài viết tin tức , gải sử chúng ta cho vào nội dung là
[MENU_SITE] ,[CONTACT_DEFAULT],[LEFT] thì khi xem bài viết đều hiện nội dung của các blcok này ra. Sẽ rất tiện ích khi dùng chức năng này chèn quản cáo hay video, hoặc 1 đoạn mã nào đó vào.
Nhưng nếu ai thông thuộc nuke mà vào post kiểu này sẽ ko ổn

**Comment by anhtunguyen** [comment]
Theo anh thì không nên cho phép thêm block bằng cách này vào nội dung bài viết. Khi lưu nội dung cần lọc và xóa tất cả các khóa mà hệ thống dùng để chèn block.

**Comment by nhimthulinh** [comment]
vẫn cho chèn nhưng mà phải cấu hình gì thêm vào đấy cho hệ thống nhận dạng block đó được chèn vào bài viết :+1:

**Comment by anhtunguyen** [comment]
Cách chèn này hơi "du kích" và tiềm ẩn nhiều rủi ro

**Comment by vuthao** [comment]
Cái này mình sẽ xem và xử lý.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/4ae71c6bc0753be7b4146b58b1c6bde845e1774b
