### ISSUE TITLE
[JS] Lỗi gọi global.js tại trang Admin

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1267]
Lỗi
```
<script type="text/javascript" src="/dev//js/global.js?t=1"></script>
```
Tại trang
```
/admin/index.php
```

Phiên bản tại Commit này
https://github.com/nukeviet/nukeviet/commit/55505c5a4a73431f2fc73c7d870feca36c04de3f

Test trên XAMPP 1.8.3
Firefox 40

**Comment by anhtunguyen** [comment]
Không thấy có lỗi này

**Comment by anhyeuviolet** [comment]
![global](https://cloud.githubusercontent.com/assets/6290970/9216240/05aa3acc-40e0-11e5-88b0-5be9892701b1.png)
Sau khi cài xong, click vào phần xem trang quản trị thì bị anh ạ.

**Comment by anhyeuviolet** [comment]
Khi login thành công thì như sau : 
![login-success](https://cloud.githubusercontent.com/assets/6290970/9216244/2eb0cc56-40e0-11e5-91b7-85af76df7d8e.png)

**Comment by vuthao** [comment]
em cũng thấy lỗi này, để em fix nó.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/6c4b7edf0a76a2bde42e57ec29fd275758666991
