### ISSUE TITLE
Quá Nhiều lỗi trên module news

### ISSUE THREAD

**Issue by thucvinh** [nukeviet/nukeviet#1269]
Môi trường thử nghiệp:

- Phiên bản NukeViet: 4.0.22
Môi trường thử Nghiệm: Localhost
- Máy chủ web: (Ví dụ: XAMPP v3.2.1)

- Lỗi không xóa được chuyên mục
- Không upload được hình ảnh khi thêm bài viết mới
- Không lấy được alisa theo tên chuyên mục, bài viết
-

**Comment by anhyeuviolet** [comment]
Sao mình không thấy bất kỳ lỗi nào bên trên nhỉ ?

**Comment by vuthao** [comment]
@thucvinh  xem lại môi trường thư nghiệm nhé, không có  XAMPP v3.2.1 đâu

**Comment by thucvinh** [comment]
Mình đã fix được rồi. Thank các bạn. Sai đường dẫn js trong admin

**Comment by anhyeuviolet** [comment]
Bá đạo quá :|
