### ISSUE TITLE
Về việc bỏ thanh công cụ quản trị

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1273]
Không hiểu lý do gì lại bỏ thanh công cụ quản trị ở dưới đi và thêm vào block thành viên.
Việc đưa vào block thành viên là khá bất tiện.
- Vì nhu cầu riêng, không phải site nào cũng cần kích họat block thành viên.
- Không phải module, hay op nào cũng kích họat block thành viên, khi này muốn có liên kết phải quay về khu vực có block thành viên, rất bất tiện.
- Với 1 hành động, thay vì 1 click chuột, nay thao tác cần phải 2 click chuột (trên default)
........

**Comment by anhtunguyen** [comment]
Anh sẽ làm cái này.

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/anhtunguyen/nukeviet/commit/bb8818cc9999d758bfd4563102ffdfef848dd7a8
