### ISSUE TITLE
Lỗi không tạo được ảnh thumb

### ISSUE THREAD

**Issue by PhamQuocTien132** [nukeviet/nukeviet#1274]
Hiện tại em gặp lỗi: không tự động tạo ảnh thumb với ảnh định dạng bmp.
Ví dụ ảnh: http://www.upes1.edu.vn/DesktopModules/Followmesoft.Newspaper/ResourceDownload.aspx?ResourceID=6115

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/f14b4df8b9fa27c47dadf6b1ced6e4b441eaa341
