### ISSUE TITLE
Lỗi đăng nhập bằng OpenID

### ISSUE THREAD

**Issue by anhtunguyen** [nukeviet/nukeviet#1275]
Khi lần đầu đăng nhập bằng openid, chọn "Đăng nhập bằng tài khoản mà bạn đăng ký trước đây", chọn tài khoản đã có => ra trang trắng.

**Comment by anhtunguyen** [comment]
Test bằng OpenID của NukeViet

**Comment by nhimthulinh** [comment]
em thấy OpenID của NukeViet và yahoo chạy ok rồi anh, có facbook là ko tích hợp được

**Comment by vuthao** [comment]
facbook không tích hợp được chắc là @nhimthulinh  chưa đăng ký đúng, mình tạo 1 cái được ngay, và cũng đã thử trên hosting của nhím vẫn hoạt động bình thường.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/5ce01060701b9dc64ead5fa78ae262ca9ada659c
