### ISSUE TITLE
Đề nghị thay đổi Font và cỡ chữ trong giao diện admin

### ISSUE THREAD

**Issue by dtsoncntt** [nukeviet/nukeviet#1276]
Cỡ chữ và font quá nhỏ , nhòm nhòm mà đau hết cả mắt . lò dò toàn lick nhầm :( :(
hiện tại như sau.
font-family: 'Roboto', sans-serif
font-size : 12px

**Comment by vuthao** [comment]
hiện tại mình đã tăng cỡ chữ lên 1 site: https://github.com/nukeviet/nukeviet/commit/286eaed0f15939204e24614033a6ed18133ec4ce
