### ISSUE TITLE
Module quản lý bình luận vẫn xuất hiện icon Xem ngoài site

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1280]
NukeViet d3ed661ad3b8fdb116999401c3526a72cbc05270

Module quản lý bình luận không có trang xem bên ngoài site nhưng trong Admin Control Panel vẫn xuất hiện icon Xem ngoài site.
![anh chup 275](https://cloud.githubusercontent.com/assets/1892900/9259428/587db37c-422b-11e5-83d4-b733ff235adf.jpg)

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/e179a3b6c1bff33ee0398dd70af2dd98185859cc
