### ISSUE TITLE
Lỗi trắng trang khi truy cập module contact

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1281]
NukeViet d3ed661ad3b8fdb116999401c3526a72cbc05270
Truy cập module contact bị lỗi trang trắng!

Môi trường thử nghiệm: Localhost Vertrigo 2.3
Packages:

    Apache 2.2.26
    PHP 5.3.27
    Mysql 5.5.34
    Smarty Smarty-3.1.15
    SQLite 3.8.1
    PhpMyAdmin 4.0.9
    SQLiteManager 1.2.4
    Xdebug 2.2.3

Loaded PHP extensions:

    Core, bcmath, calendar, ctype, date, ereg, filter, ftp, hash, iconv, json, mcrypt, SPL, odbc, pcre, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, bz2, SimpleXML, wddx, xml, xmlreader, xmlwriter, apache2handler, openssl, curl, gd, mbstring, mysql, mysqli, Phar, pdo_mysql, pdo_sqlite, SQLite, mhash, xdebug,

**Comment by anhtunguyen** [comment]
Trong ACP hay ngoài site?

**Comment by thehung** [comment]
Ngoài site anh ạ.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/fb4bcff273ea933f6d176303e499167b54665402
