### ISSUE TITLE
Lỗi đăng xuất tài khoản quản trị

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1283]
> Phiên bản NukeViet	4.0.22
Phiên bản PHP	5.5.25
Giao thức giữa máy chủ và PHP	Apache/2, litespeed
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 10.0.17-MariaDB

![selection_105](https://cloud.githubusercontent.com/assets/6407361/9264421/8acfc12e-4250-11e5-84b1-914ae9c0523b.png)

**Comment by vuthao** [comment]
Phiên bản tại nhánh develop hiện tại lỗi này không còn.
