### ISSUE TITLE
[CSS] Về việc trùng class mặc định của Bootstrap

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1284]
Hiện trong style.css có một đoạn CSS như sau : 
```
.info:before {
    content:" \f05a ";
    display:inline-block;
    font-family:FontAwesome;
    font-size:20px;
    line-height:1;
    vertical-align:middle;
    margin-right:5px;
}
```
Cái đáng chú ý là dòng
```
    content:" \f05a ";
```
Khi đó, các class .info xuất ra hình ảnh sẽ như sau : 
![class-info](https://cloud.githubusercontent.com/assets/6290970/9265173/ba86b54a-4259-11e5-8dfe-d9355423f414.PNG)

Mặc định, bootstrap dùng class .info cho một số table và cell của nó.
http://getbootstrap.com/css/#tables-contextual-classes

Như vậy nếu ai dùng các class mặc định, mà ở đây là .info, thì sẽ được tặng thêm cái icon i to đùng.
Hy vọng có thể điều chỉnh để tránh tình trạng này xảy ra.

**Comment by anhtunguyen** [comment]
Đúng là tôi quên không để ý cái này. Ok. Sẽ thay tên khác cho class này

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/anhtunguyen/nukeviet/commit/c6c6f28550b8f274c94b5602dde632a3950a2426
