### ISSUE TITLE
Lỗi ping bài viết

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1285]
![selection_106](https://cloud.githubusercontent.com/assets/6407361/9265319/d4faa6d2-425b-11e5-9476-5f5c516d11ce.png)

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/3ddafc0ddc55f712748dc66fc6d0fa71952d4a5c
