### ISSUE TITLE
Lỗi Setup ở bản develop

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#1287]
Cấu hình máy chủ
Phiên bản NukeViet	4.0.22Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.5.27
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Win32) OpenSSL/1.0.1m PHP/5.5.27, apache2handler
Hệ điều hành máy chủ	WINDOWS NT
Phiên bản Database	mysql 5.6.25

Lỗi cài đặt khi LỰA CHỌN NGÔN NGỮ (Bước 1)  là Tiếng Anh thì bị lỗi trang trắng ở Bước 5 còn Ngôn ngữ tiếng Việt và tiếng Pháp vẫn cài đặt bình thường

**Comment by vuthao** [comment]
Mình đã sửa lỗi ở phiên bản hiện tại của nhánh develop
