### ISSUE TITLE
[ Lỗi news ] Hỏng nội dung khi thêm/sửa bài viết.

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1288]
Commit
https://github.com/nukeviet/nukeviet/commit/3509b2a367dbe4e1e452ffc7a3e747b312fa3501
XAMPP 1.8.3
Chrome Latest
-----------------

Bài viết khi đăng
```
<strong>Dưới đây là nội dung chi tiết được in đậm.</strong>
```
Sau khi nhấn sửa và lưu lại : 
```
{:strong:}Dưới đây là nội dung chi tiết được in đậm.{:/strong:}
```
Đã thử vài lần thì kể cả đăng bài hay sửa bài đều bị.

**Comment by vuthao** [comment]
MÌnh đã sửa lại vấn đề này tại: https://github.com/vuthao/nukeviet/commit/1afe05decd3c8db4d5f58a2e27ac7d27595afd4b

**Comment by anhyeuviolet** [comment]
Giờ nó hỏng hình ảnh anh ơi.
Bài demo kèm NV, sau khi sửa nó thành ra thế này
```
<div>&nbsp;</div>

<div align="[:center:]">&nbsp;</div>

<div align="[:left:]">Cơ cấu Giải thưởng của Nhân tài Đất Việt 2011 trong lĩnh vực CNTT bao gồm 2 hệ thống giải dành cho “Sản phẩm có tiềm năng ứng dụng” và “Sản phẩm đã ứng dụng rộng rãi trong thực tế”. Mỗi hệ thống giải sẽ có 1 giải Nhất, 1 giải Nhì và 1 giải Ba với trị giá giải thưởng tương đương là 100 triệu đồng, 50 triệu đồng và 30 triệu đồng cùng phần thưởng của các đơn vị tài trợ.</div>

<div align="[:center:]">&nbsp;</div>

<div align="[:center:]">
<div align="[:center:]"><img _fl="[::]" align="[:middle:]" alt="[::]" src="[:http://dantri4.vcmedia.vn/xFKfMbJ7RTXgah5W1cc/File/2011/03_f19bd.jpg:]" width="[:350:]" /></div>
```
Còn ngoài trang chi tiết thì nó ra thế này
![request](https://cloud.githubusercontent.com/assets/6290970/9287514/ba860a84-4342-11e5-8e9d-c4863efe34e1.PNG)

**Comment by anhyeuviolet** [comment]
https://github.com/nukeviet/nukeviet/issues/1307

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/4d33ad52ed8e8978a0f34bc1adaaa06a4b7a80bb
