### ISSUE TITLE
[CSS news ] Ảnh Tooltips tràn ra bên ngoài khối chứa

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1289]
Commit
https://github.com/nukeviet/nukeviet/commit/3509b2a367dbe4e1e452ffc7a3e747b312fa3501
XAMPP 1.8.3
Chrome Latest
-----------------
Khi mô tả ngắn gọn thật sự " ngắn" thì tooltips xảy ra tình huống như sau : 
![ttls-](https://cloud.githubusercontent.com/assets/6290970/9268159/77b99396-4285-11e5-874d-1a55095a64e3.png)
Có thể tạm fix bằng cách bổ sung : 
```
 height: auto;
 overflow: auto;
```
cho class
```
.tooltip-inner 
```

**Comment by anhtunguyen** [comment]
OK. Cảm ơn bạn. Tôi sẽ fix lỗi này

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/anhtunguyen/nukeviet/commit/8cd8a83bdc6ae4b0408a0cf10f7fc52ec2927f7b
