### ISSUE TITLE
Undefined index: active

### ISSUE THREAD

**Issue by anhtunguyen** [nukeviet/nukeviet#1290]
[Notice(8): Undefined index: active] [FILE: /admin/themes/block_content.php] [LINE: 515]
[Notice(8): Undefined index: active] [FILE: /admin/themes/block_content.php] [LINE: 538]

**Comment by anhyeuviolet** [comment]
Ak, có thấy lỗi này mà quên mất chưa báo

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/d6b856e97dc9e190915f3fc974fddde241b45281
