### ISSUE TITLE
Form gửi phản hồi không hiển thị

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1291]
NukeViet 3509b2a367dbe4e1e452ffc7a3e747b312fa3501
Site vừa cài mới hoàn toàn.
Trình duyệt FireFox 39.0.3
Localhost Vertrigo 2.30

Trên giao diện PC, click vào nút gửi phản hồi ở chân site chỉ hiển thị một ô trống:
![anh chup 276](https://cloud.githubusercontent.com/assets/1892900/9268836/24cb9a50-428d-11e5-82c1-3c2713dee774.jpg)

Trương tự trên giao diện mobile
![anh chup 277](https://cloud.githubusercontent.com/assets/1892900/9268847/4e4edffe-428d-11e5-959b-f2b2067702b2.jpg)

**Comment by anhtunguyen** [comment]
Không hiểu nổi tại sao nữa. Còn ai bị như vậy nữa không nhỉ?

**Comment by anhyeuviolet** [comment]
Em ko bị lỗi này. @.@

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/fb4bcff273ea933f6d176303e499167b54665402
