### ISSUE TITLE
Lỗi sau khi đăng "bài viết không có nội dung"

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1294]
> Phiên bản NukeViet	4.0.22
Phiên bản PHP	5.5.25
Giao thức giữa máy chủ và PHP	Apache/2, litespeed
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 10.0.17-MariaDB

![selection_107](https://cloud.githubusercontent.com/assets/6407361/9272291/1374d8b6-42ab-11e5-9cc1-b1e60dca7e14.png)

Click vào link nó quay về trang chính của news luôn.

**Comment by vuthao** [comment]
Mình kiểm tra trên local mã html của nó là <a href="javascript: history.go(-1)">Quay lại trang sửa bài viết</a>

Triển kiểm tra lại xem của mình có giống thế không.

**Comment by anhyeuviolet** [comment]
Có lẽ do trình duyệt của @hongoctrien .

**Comment by hongoctrien** [comment]
Giờ thử lại thì ko thấy lỗi click vào url. Nhưng vẫn thấy lỗi js như trong hình. 
@vuthao và @anhyeuviolet cũng thấy lỗi js chứ?

**Comment by anhyeuviolet** [comment]
Lỗi JS thì tương tự như @hongoctrien.

**Comment by vuthao** [comment]
Cái này FF không bị, trên Google Chrome Nó báo lỗi ở dòng:

<link rel="shortcut icon" type="image/x-icon" href="http://localhost/nukeviet/themes/default/favicon.ico">

Nên mình cũng chưa biết sửa thế nào.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/71e3575ef8195af01441ac6c34c6a1f426b1c931
