### ISSUE TITLE
Lỗi khi đăng bài vài không giữ nguyên định dạnh khi coppy paste từ 1 bài trang web khác

### ISSUE THREAD

**Issue by nethoabinh** [nukeviet/nukeviet#1298]
PHiên bản 4.0.22
Test localhost
- Em coppy 1 bài viết trên 1 trang báo điện tử về post vào nuke việt xong ra màn hình thì nhìn thấy 1 đống lộn xộn
không giữ nguyên được dịnh danjng khi em coppy
mong sớm khắc phục ạ

![nuke-loi](https://cloud.githubusercontent.com/assets/6945379/9287017/19bcffaa-432d-11e5-8d72-70361cdc1676.png)

**Comment by vuthao** [comment]
Bạn lấy lại file tại: https://github.com/nukeviet/nukeviet/blob/develop/includes/class/request.class.php

**Comment by nethoabinh** [comment]
thanks bác em sửa được rùi, còn 1 lỗi sảy ra là auto save ảnh về localhost. lúc pub ra nó không hiện ạ? hay phải cho lên host thì nó mới tự động lưu về host online ạ?

**Comment by vuthao** [comment]
@nethoabinh, mối lỗi tạo một issues nhé, nếu không sẽ kéo dài đến vô tận, ko ai có thể theo dõi đâu nhé.
