### ISSUE TITLE
Lỗi khi up lên hosting của mắt bão !!

### ISSUE THREAD

**Issue by aptx1987** [nukeviet/nukeviet#1300]
Mình up cả code đã chỉnh sửa lẫn code gốc của nukeviet 4.0.21 lên vẫn bị lỗi. Tưởng code bị gì lên down cả bản 4.0.22 vẫn bị luôn ko hiểu tại sao nữa.
Lỗi khi up bản 4.0.21:
Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in /home/ban57a8c/public_html/mainfile.php on line 33

Lỗi khi up bản 4.0.22
Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in /home/ban57a8c/public_html/includes/mainfile.php on line 30

Môi trường thử nghiệm: hosting của mắtbão
Máy chủ: Linux
Cpanel

domain của mình là banghuynhquang.net

**Comment by vuthao** [comment]
@aptx1987 xem lại quy định tại: https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md

Nếu là PHP 5.2 sẽ không sử dụng được nhé. Nếu PHP 5.3 bạn có thể gửi tài khoản hosting qua email thao a còng vinades.vn để tôi kiểm tra kỹ hơn nhé.

**Comment by anhyeuviolet** [comment]
MB dạo này khoá khá nhiều hàm. Thậm chi CHMOD cũng hạn chế. @aptx1987 xác nhận lại với bên MB xem sao.

**Comment by aptx1987** [comment]
Mình đã xác nhận lại bên mắtbão hiện h họ đang xem xét lại cho mình rồi. Thnks nếu ko có gì thì mình xin cảm ơn
