### ISSUE TITLE
lỗi autosave ảnh về host - khi pub ra thì bị lỗi 

### ISSUE THREAD

**Issue by nethoabinh** [nukeviet/nukeviet#1302]
còn 1 lỗi sảy ra là auto save ảnh về localhost. lúc pub ra nó không hiện ạ? hay phải cho lên host thì nó mới tự động lưu về host online ạ?

**Comment by vuthao** [comment]
Nếu bạn làm trên local với địa chỉ truy cập: http://localhost/thumucsite/
Thì khi đưa lên site cũng phải là địa chỉ http://domain.com/thumucsite/
Nếu đưa lên http://domain.com/ thì ảnh trong nội dung bài viết chắc chắn lỗi.

Do bạn không mô rả rõ nên tôi không  dám chắc cái gì.

**Comment by nethoabinh** [comment]
em coppy 1 bài viết online trên mjang về
domain em để là localhost/thumucsite  bài viết là localhost/thumucsite/bai-viet1.html nó bị báo lỗi ảnh không hiện ảnh trong bài viết

**Comment by vuthao** [comment]
@nethoabinh đọc nội dung của bạn tôi vẫn không hiểu, bạn mô tả rõ lại nhé, nếu có thể quay luôn video cho nhanh.

**Comment by nethoabinh** [comment]
:( có nghĩa là em coppy 1 bài viết trên mạng --> viết bài viết mới trên localhot, khi public ra bài viết thì không hiện ảnh trong bài viết đại ca ạ. :(((((((((((((((((

**Comment by vuthao** [comment]
Quay dùm anh cái video đi, vẫn không thấy lỗi như mô tả (Thử trên bản mới nhất xem sao nhé)

**Comment by tuyenclub** [comment]
Lỗi của thánh này là giống lỗi này bạn @vuthao ạ :https://github.com/nukeviet/nukeviet/issues/1334

**Comment by vuthao** [comment]
Minh đóng lỗi này lại do trùng với https://github.com/nukeviet/nukeviet/issues/1334
