### ISSUE TITLE
Lỗi thay đổi vị trí block

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1304]
- Giữ lại chức năng kích hoạt hoặc không kích hoạt block như các phiên bản cũ. 
Bây giwof muốn tắt block lại phải vào sửa rất mất thời gian

Thay đổi vị trị left sang right thì hiện thông báo thành công, nhưng nó ko sang block right đc mà hiện trắng. 
Có nghĩa là nó hiểu block nào để di chuyển
![nh ch p man hinh 2015-08-15 luc 18 12 09](https://cloud.githubusercontent.com/assets/5910584/9288609/3497d538-4379-11e5-98da-d1c641f0e6fb.png)

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/4e7acd673b837e06f6ffa3fb74c1333f1957361f
