### ISSUE TITLE
Chmod mặc định file NukeViet

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1305]
Trong source NukeViet, mặc định thư mục chmod 700 và file là 664. Quyền này một số hosting linux báo không truy cập được file (ngay cả file /index.php). Nên mặc định thư mục là 755 và file là 644 (không tính các thư mục cần 777).
![selection_135](https://cloud.githubusercontent.com/assets/6407361/9289094/88003b38-438e-11e5-849e-04a25571d518.png)

**Comment by vuthao** [comment]
Với mỗi hosting khác nhau, thì người cài đặt cầm kiểm tra chmod sao cho PHP có thể ghi file.
Với mỗi hosting thì việc mod này sẽ khác nhau.

**Comment by hoaquynhtim99** [comment]
Cái mặc định này là lúc upload lên nó tự chmod ý chớ không phải do định sẵn của NukeViet đâu triển ơi

**Comment by hongoctrien** [comment]
@hoaquynhtim99 ak uk :D
