### ISSUE TITLE
Góp ý block html

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1306]
nên di chuyển global.html.php vào themes/default/block
đã có rất nhiều người hỏi block html này nằm ở đâu/.
Hơn nữa nếu ko sài module page thì ko có block này mà sài

**Comment by vuthao** [comment]
Việc này tôi cũng đã cân nhắc khá nhiều khi di chuyển vào page:

Nếu di chuyển vào theme default, khi tạo giao diện, sẽ phải copy code này, dẫn đến việc cập nhật code sau này nếu có sẽ không thực hiện được. Và nó sẽ phát sinh rất nhiều code trùng lặp.

Module Page là module đặc biệt của hệ thống, sẽ không thể bỏ module này. Ngoài ra các bạn có thể chọn nó từ bất kỳ module nào là module ảo của page.
