### ISSUE TITLE
lỗi thêm block html

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1307]
Khi chèn 1 hình ảnh thì hiện ra
<img alt="[::]" height="[:104:]" src="[:http://www.npa.org.vn/Uploads/2015/1/2/HCMA-banner1.jpg:]" width="[:668:]">
![nh ch p man hinh 2015-08-15 luc 23 54 38](https://cloud.githubusercontent.com/assets/5910584/9289925/1d948b30-43a9-11e5-9d1e-86ffa5c13f70.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/4d33ad52ed8e8978a0f34bc1adaaa06a4b7a80bb
