### ISSUE TITLE
Ảnh trong bài viết không tự động responsive, tràn ra ngoài nếu ảnh lớn.

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1312]
> Phiên bản NukeViet	4.0.22
Phiên bản PHP	5.5.25
Giao thức giữa máy chủ và PHP	Apache/2, litespeed
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 10.0.17-MariaDB
Trình duyêt: Firerox, Chrome

![selection_137](https://cloud.githubusercontent.com/assets/6407361/9293725/052b8014-4460-11e5-9e8a-9bce25029562.png)

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/5ddfdc9c6b2d3351e64e4074b12a6e1bbdf2fae2
