### ISSUE TITLE
Lỗi avartar trong admin

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1319]
> phần avartar trong admin
> khi thêm tài khoản thì là chọn ảnh từ máy tính
> khi sửa thì lại là chọn ảnh crop
> khi lưu lại rồi mà sửa tài khoản thì đưỡng dẫn ảnh avatar lại mất

Thấy 1 bạn báo thế này :3

**Comment by thehung** [comment]
Nhím gửi kèm theo link của bạn ấy report (trên facebook?) nhé!

Anh kiểm tra bản mới nhất (NukeViet 27c1d6edaa9d54abba157482705be1833752b89e) thấy đúng là có lỗi: Tạo tài khoản mới từ Admin Control Panel có chọn avatar, khi sửa tài khoản này thì không thấy ảnh avatar đâu.

Cách xử lý avatar trong admin control panel cũng chưa thống nhất (Khi tạo tài khoản mới thì việc chọn và xử lý avatar khác với khi sửa tài khoản).

**Comment by anhtunguyen** [comment]
OK. Cái này anh sửa nhé

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/anhtunguyen/nukeviet/commit/e3241e31406e34a9fc39c3fdefe0982581899f15
