### ISSUE TITLE
Lỗi sao chép block trong admin

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#1320]
Hiện tại ở nuke 22 khi sao chép block trong admin không hoạt động, sao chép xong báo thành công nhưng ra ngoài site ko thấy sao chép sang

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/fe3d7f99505486951b89df9d2b72b0d140f26453
