### ISSUE TITLE
Sai cấu trúc link khi tìm kiếm với từ khóa có [dấu cách] ở module tìm kiếm

### ISSUE THREAD

**Issue by dinhnghia** [nukeviet/nukeviet#1323]
Em xin phép đi thẳng vào vấn đề như sau:
Demo lỗi : http://bacdannamkhang.com
Em tìm kiếm với từ khóa "Bạc" thì kết quả show ra với phân trang "đúng link"
Em thực hiện tìm kiếm thêm với từ khóa "Bạc Đạn" thì bị sai cấu trúc link ở phân trang.
Mong các anh giúp đỡ. Thân chào và chúc các anh buổi tối vui vẻ.

**Comment by vuthao** [comment]
Bạn vui lòng đọc kỹ dòng: Please review the guidelines for contributing to this repository., tức là đọc link: https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md
ở đây chúng tôi chỉ thảo luận Xem xét các lỗi của Nukeviet nhé.
