### ISSUE TITLE
Nên chú ý: unserialize()

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1324]
Thông báo từ Hệ thống
Nên chú ý Nên chú ý: unserialize(): Error at offset 94 of 218 bytes in file /includes/core/user_functions.php on line 108

**Comment by vuthao** [comment]
Bạn vui lòng đọc kỹ dòng: Please review the guidelines for contributing to this repository., tức là đọc link: https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md
