### ISSUE TITLE
Social icon

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1325]
Lỗi không hiện thị Social icon
khi f5 thì Social icon hiện thị 2 giây sau thfi mất hẳn

**Comment by vuthao** [comment]
Bạn vui lòng đọc kỹ dòng: Please review the guidelines for contributing to this repository., tức là đọc link: https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md
