### ISSUE TITLE
Editor không làm việc ngoài site

### ISSUE THREAD

**Issue by anhtunguyen** [nukeviet/nukeviet#1326]
- Khi ở ngoài site nó không nhận biết được biến nv_lang_interface (vì nó không đc định nghĩa )
- Khi tạo trường dữ liệu cho module users là editor, dữ liệu được lưu ở dạng textarea đơn thuần (chấp nhận mỗi tag br

**Comment by anhtunguyen** [comment]
Cái 1 anh đã sửa.
Cái 2 Thảo xem lại nhé

**Comment by vuthao** [comment]
Vâng anh, em sẽ xem phần này.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/df088b1d0481bacc7800dd69c0c72cb2380f2f5b
