### ISSUE TITLE
Lỗi tắt kéo thả block ngoài Site

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1331]
Khi bật chức năng kéo thả block lên block contactDefault bị khuất sau block menu site
![image](https://cloud.githubusercontent.com/assets/9360175/9380667/efb5b412-475b-11e5-917c-cc1fb36183cc.png)

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/anhtunguyen/nukeviet/commit/e6abb501a365f9f258ffea85e92a6dda42f0d62f
