### ISSUE TITLE
block gửi liên hệ: button chưa căn giữa

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1333]
![image](https://cloud.githubusercontent.com/assets/10300770/9380825/e7b52774-475c-11e5-93b9-25ef90ac548c.png)

**Comment by vuthao** [comment]
Cái này là thăm dò ý kiến chứ @htuyen1994

**Comment by htuyen1994** [comment]
:D e nhầm

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/anhtunguyen/nukeviet/commit/e4db851202b6a5e9cee457d57bb631dfa2b98b3c
