### ISSUE TITLE
Lỗi chức năng dán bài viết tải hình ảnh về trong module about bị lỗi

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1334]
Nukeviet 5f6cbf1f8ceff42cb184419715636e5ec42426df
Khi sử dụng chức năng bài viết tải hình ảnh về trong module about và module page phần nội dung không tải được hình ảnh về như hình sau
![image](https://cloud.githubusercontent.com/assets/9360175/9380841/060c28d0-475d-11e5-8071-c1b4b598c678.png)

**Comment by vuthao** [comment]
Mình sẽ kiểm tra phần này lại xem sao.

**Comment by hongoctrien** [comment]
Đang sửa

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/7e085a9f5ff2c6137a9be76a9d2d76ce0b4f0da0
