### ISSUE TITLE
Khi xem thông tin thành viên. không thấy button hay link nào đến sửa thành viên

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1335]
![image](https://cloud.githubusercontent.com/assets/10300770/9380952/d0956a8a-475d-11e5-8c7e-b74bf32fd30a.png)

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/anhtunguyen/nukeviet/commit/ade8bd60d3a17e668010725da57c47341b641cbe
