### ISSUE TITLE
Sửa thông tin thành viên: ô ngày tháng năm sinh không có icon lịch,nên để icon lịch vào để biết đây là ô nhập ngày tháng

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1336]
![image](https://cloud.githubusercontent.com/assets/10300770/9380996/1fc2942a-475e-11e5-9f00-1fbe19aa81f4.png)

**Comment by anhtunguyen** [comment]
Anh cho rằng cái icon đó không còn thiết vì mình có cho khai báo thủ công đâu. Anh có muốn khai thủ công cũng không đc. Click vào ô là lịch hiện ra thì hợp lý

**Comment by anhtunguyen** [comment]
Cái xác minh email em chưa hiểu hết nguyên lý. Khi có đề nghị thay đổi email thì hệ thống sinh ra 1 key ngẫu nhiên và gửi đến email mới đồng thời lưu session. Việc này kiểm tra xem email này có thực hay ko và người đề nghị có phải là chủ nhán hay không.
Nếu người đề nghị nhập đúng MÃ XÁC MINH (không phải mã xác nhận) thì email mới mới có táccdung.
Không thể gửi mã xác minh đến email cũ vì thông thường email cũ có vấn đề thì người ta mới thay email mới.
Kích hoạt bằng phương pháp cho trả lời câu hỏi bảo mật không đảm bao email mới là có thật

**Comment by htuyen1994** [comment]
thêm icon chủ yếu cho đẹp và rõ ràng hơn thôi a

**Comment by anhtunguyen** [comment]
Nó phải trong một tổng thể bạn nhé

**Comment by anhtunguyen** [comment]
Chiều theo ý bạn nhé:
https://github.com/anhtunguyen/nukeviet/commit/fa092b51c8da71f3d2eba3384a9267558869cca1
