### ISSUE TITLE
Phần sửa thông tin thành viên: phần thay đổi email chưa hợp lí

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1337]
Nếu mã xác nhận được gửi tới mail mới thì bất cứ ai có mật khẩu cũng có thể thay đổi dc email, như vậy đâu cần phải gửi mã xác minh làm gì..

Nên gửi mã xác nhận cho email cũ và không hiện email hiện tại, hoặc là bắt xác nhận qua câu hỏi bảo mật

![image](https://cloud.githubusercontent.com/assets/10300770/9381057/8ef217d0-475e-11e5-969d-870b27ecbe50.png)

**Comment by anhtunguyen** [comment]
Khai báo mật khấu là bắt buộc. Mã xác minh gửi đến mail không có nghĩa là địa chỉ mail đã thay đổi. Chỉ khi nào nhập mã xác minh đc xác thực thì lúc đó email mới mới có hiệu lực.
Xem lại cái này nhé

**Comment by anhtunguyen** [comment]
Mã xác minh và xác nhận là hoàn toàn khác nhau nhé

**Comment by anhtunguyen** [comment]
Cái xác minh email em chưa hiểu hết nguyên lý. Khi có đề nghị thay đổi email thì hệ thống sinh ra 1 key ngẫu nhiên và gửi đến email mới đồng thời lưu session. Việc này kiểm tra xem email này có thực hay ko và người đề nghị có phải là chủ nhán hay không.
Nếu người đề nghị nhập đúng MÃ XÁC MINH (không phải mã xác nhận) thì email mới mới có táccdung.
Không thể gửi mã xác minh đến email cũ vì thông thường email cũ có vấn đề thì người ta mới thay email mới.
Kích hoạt bằng phương pháp cho trả lời câu hỏi bảo mật không đảm bao email mới là có thật

**Comment by htuyen1994** [comment]
Nhưng nếu như vậy bất cứ ai có mật khẩu cũng đổi được email, trường hợp cho mượn tài khoản là có thể mất toàn bộ mọi thông tin, từ câu hỏi bảo mật tới email

**Comment by anhtunguyen** [comment]
Sao bạn vẫn chưa hiểu nhỉ?
Bạn có mật khẩu cũng không đổi được.
Bạn đổi được khi nào bạn khai báo đúng cả mật khẩu và cả mã xác minh.
Đọc kỹ lại nhé.

**Comment by vuthao** [comment]
ý của anh Tú đúng đó Tuyên.
Nếu cho ai mượn tài khoản, thì người dùng càn bật tính năng: Chế độ an toàn
