### ISSUE TITLE
Trang login thành viên không có link đăng lý tài khoản mới.

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1338]
Trang:
http://nukeviet.my/users/login/
Nếu người dùng muốn đăng ký tài khoản mới, thì không có (Các block có thể bị tẳt trên các giao diện)

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/anhtunguyen/nukeviet/commit/ade8bd60d3a17e668010725da57c47341b641cbe
