### ISSUE TITLE
Sửa thông tin tài khoản: phần chế độ an toàn không biết là đang bật và tắt, và nó sẽ hoạt động như thế nào, nên mô tả rõ hơn

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1339]
![image](https://cloud.githubusercontent.com/assets/10300770/9381229/a88ff1ac-475f-11e5-9cad-1e9cbcb02d3d.png)

**Comment by vuthao** [comment]
do ở đây có hai nút: Gửi mã xác minh, và Chấp nhận, nên không biết phải click cái nào nữa @anhtunguyen

**Comment by anhtunguyen** [comment]
OK. Anh sẽ cho cái nút gửi mã xác minh cùng dòng với ô khai báo mã xác minh

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/anhtunguyen/nukeviet/commit/ade8bd60d3a17e668010725da57c47341b641cbe
