### ISSUE TITLE
Lỗi giao diện User ngoài site đa ngôn ngữ tiếng anh

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1340]
Các nút bên ngoài site đa ngôn ngữ tiếng anh phần Edit User info không nhìn thấy như hình sau
![image](https://cloud.githubusercontent.com/assets/9360175/9381793/c58e6860-4764-11e5-8e24-d3fd82125b3c.png)

**Comment by anhtunguyen** [comment]
Do chưa dich xong ngôn ngữ bạn.
Khi nào dịch đủ ngôn ngữ thì nó sẽ hiển thị

**Comment by vuthao** [comment]
Em sẽ cập nhật phần này lên site.

**Comment by vuthao** [comment]
update: https://github.com/nukeviet/nukeviet/commit/1ca77a488b7e6328a5f038a48d7ca7c163e847e7
