### ISSUE TITLE
Lỗi reponsive block global slimmenu của module menu

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1344]
Khi em sử dụng block global slimmenu trong module menu khi reponsive thì tên block của module slimmenu không bị mất. Nó như hình sau ạ
![error](https://cloud.githubusercontent.com/assets/9360175/9386271/e5540266-4784-11e5-92d8-8ae09c7bbe86.png)

**Comment by anhyeuviolet** [comment]
Block đó bạn phải chỉnh là no_title chứ nhỉ ?

**Comment by nambmtk1993** [comment]
Mình đã chỉnh no_title nhưng reponsive nó vẫn hiện

**Comment by anhyeuviolet** [comment]
![menu](https://cloud.githubusercontent.com/assets/6290970/9400776/d3ba605c-47ef-11e5-98c2-7ce6f87f6951.PNG)
Uầy ! Xác nhận. Và block này ko click vào menu được.

Firefox latest
XAMPP 1.8.3
Commit : https://github.com/nukeviet/nukeviet/commit/7e1bdbbb03513647172201716af90c7e0ab3fa9c

**Comment by anhtunguyen** [comment]
OK. Cái này anh sẽ "thịt" nhé

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/bbe62571766a2ddece67149341dd9ecf8fd0d510
