### ISSUE TITLE
Lỗi cảnh báo khi đình chỉ bộ phận của module liên hệ

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1349]
Khi đình chỉ hết các bộ phận thì ở module liên hệ ngoài site đưa ra cảnh báo
Thông báo từ Hệ thống
Nên chú ý Nên chú ý: Undefined offset: 0 in file /modules/contact/funcs/main.php on line 43

**Comment by vuthao** [comment]
Mình sẽ xem và xử lý cái này

**Comment by anhtunguyen** [comment]
@ThinhNguyenVB bắt lỗi quá chuẩn !

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/ace0f97e1c0ba389f932a6e7336a18044bca4006
