### ISSUE TITLE
Lỗi phân quyền xem module

### ISSUE THREAD

**Issue by PhamQuocTien132** [nukeviet/nukeviet#1350]
Mô tả lỗi: 

Em tạo 1 nhóm thành viên là: test 
Tạo 1 module ảo của tin tức: tin-tuc
 Khi thiết lập module có phần cấu hình chọn nhóm dc xem, e cấu hình như hình dưới
![nkv](https://cloud.githubusercontent.com/assets/6023707/9400958/eb04e07a-477c-11e5-83f9-e0cf73c2f683.png)

Sau đó đăng 1 bài viết cho module ảo mới thêm.
Truy cập vào website bằng trình duyệt ẩn danh (Quyền truy cập lúc này là khách) thì vẫn xem được module này . Hoặc truy cậpu luôn bằng tài khoản quản trị cũng xem được

**Comment by PhamQuocTien132** [comment]
Cũng module ảo tin-tuc tạo trên và cấu hình chỉ có thành viên được xem thì khi truy cập dưới quyền là khách thì hệ thống không thông báo gì cả mà chuyển trang sang trang đăng nhập luôn -> cái này chưa được hợp lý lắm vì người dùng sẽ chẳng hiểu vì sao.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/ae705af61925995dd9726830836bf237c30a7c32
