### ISSUE TITLE
Lỗi chức năng tìm kiếm trong module tài khoản

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1351]
Em sử dụng chức năng nhóm thành viên trong module tài khoản. Vào nút tìm kiếm, ban đầu tìm theo tên tài khoản nó ra như hình sau
![errors](https://cloud.githubusercontent.com/assets/9360175/9401371/59331992-47f8-11e5-9a6d-b1f286b66d69.png)
Tiếp đến em cũng tìm tên tài khoản đó nhưng nó báo không tìm thấy kết quả

**Comment by anhtunguyen** [comment]
Cái này anh hoàn toàn chưa động đến.
Sẽ kiểm tra và cập nhật

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/9a3fe2f9bdb638791b6b9136363e8a2fcb1d539a
