### ISSUE TITLE
Module Users: Khi dùng chức năng đăng nhập có truyền biến nv_redirect

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1353]
Module Users: Khi dùng chức năng đăng nhập có truyền biến nv_redirect
Nhưng sau khi đăng nhập xong không chuyển về trang  cần xem, mà lại chuyển về module users.

**Comment by anhtunguyen** [comment]
Anh bỏ cái biến nv_redirect rồi. Sẽ có form dành cho việc đăng nhập từ bất kỳ vị trí nào của site và refresh đúng trang đó. Anh chưa kịp viết nó. Ý em nói là module News và Banners?

**Comment by vuthao** [comment]
@anhtunguyen, Ở đây nó nằm bên ngoài tất cả các module, khi module yêu cầu đăng nhập thành viên thì nó chuyển trang:

Đoạn code đang sử lý việc đó ở file index.php ở root site dòng 327, 328
```
			$redirect =  NV_BASE_SITEURL . 'index.php?' . NV_LANG_VARIABLE . '=' . NV_LANG_DATA . '&' . NV_NAME_VARIABLE . '=users&' . NV_OP_VARIABLE . '=login&nv_redirect=' . nv_base64_encode( $client_info['selfurl'] );
			nv_info_die( $lang_global['site_info'], $lang_global['site_info'], "<br />" . $lang_global['logininfo']. " \n <meta http-equiv=\"refresh\" content=\"3;URL=" . $redirect . "\" />" );

```

**Comment by anhtunguyen** [comment]
OK. Cái đó anh sẽ xử lý

**Comment by vuthao** [comment]
fixed: https://github.com/anhtunguyen/nukeviet/commit/b31d3fb374b71a4c4c9a6949df10b897cebf0425
