### ISSUE TITLE
Lỗi không thoát được trên block login và không chuyển trang sau khi login

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1354]
Hiện tại khi dùng global.login.php không dùng global.login_button.php
- nút thoát ở ngoài site không hoạt động và debug thì nó là "ReferenceError: bt_logout is not defined"
- Đăng nhập thông qua block thì hiển thị lỗi ở tài khoản admin (khi sao chép themes mặc định thành themes mới )
![untitled-1](https://cloud.githubusercontent.com/assets/13896524/9404710/fca21dbc-481b-11e5-929d-1dd83a0a7be4.png)
và lỗi báo ở debug "nv_validCheck"

**Comment by hongoctrien** [comment]
Khi không có block Feedback sẽ xảy ra lỗi này.

Lý do: Hàm nv_validCheck dùng trong themes/default/users.js dùng của contact.js, nên khi tắt block Feedback đi thì không gọi contact.js => không tồn tại hàm.

**Comment by anhtunguyen** [comment]
Các bạn bắt đúng lỗi đấy. Thực ra có hàm tương tự trong users.js (validCheck). Anh sẽ sửa.
CẢm ơn

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/anhtunguyen/nukeviet/commit/df0c938fa505ba5701abbc2a7e5a47d5318cc3aa
