### ISSUE TITLE
Lỗi khi nâng cấp

### ISSUE THREAD

**Issue by huenv** [nukeviet/nukeviet#1355]
Khi tôi cập nhật các bản vá lỗi thì bị lỗi này
User Error
Error! Language variables is empty!
(Code: aa4e9d2bbb74ed974e151be073bfca9e)
If you have any questions about this site,
please contact the site administrator for more information
Làm sao để sửa được ah?

**Comment by vuthao** [comment]
Với các bản beta nếu bạn có thể tự sửa được thì hãy nâng cấp nhé.
Do bản beta mới chỉ dùng cho các nhà phát triển, và sẽ được thay đổi thường xuyên.

Với thông báo thì theo mình bạn đã ghi đè file:
data/config/config_global.php
hoặc file data/config_global.php tùy theo phiên bản.

**Comment by huenv** [comment]
Có cach nào để khắc phục vấn đề này ko bạn

**Comment by anhyeuviolet** [comment]
@huenv  trước khi nâng cấp thì bạn phải sao lưu lại code cũ.
Còn nếu đã chép đè thì chịu. Cài lại site thôi.
