### ISSUE TITLE
Cập nhât hàm modalShow()

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1358]
Hàm modalShow() chưa **tự động điều chỉnh** được kích thước modal so với nội dung bên trong. Nên cập nhật thêm để viêc sử dụng modal đơn giản hơn.

![selection_138](https://cloud.githubusercontent.com/assets/6407361/9421907/95d2a042-48a8-11e5-93ea-ec54102e0411.png)

**Comment by anhtunguyen** [comment]
Cái này theo bootstrap. Nó fix 3 loại: bình thường, Small Modal và Large Modal.
http://www.w3schools.com/bootstrap/bootstrap_modal.asp
Nếu em có phương án sửa cho nó tùy biến theo nội dung thì gửi cho anh

**Comment by hongoctrien** [comment]
https://github.com/nukeviet/module-shops/blob/develop/themes/default/modules/shops/detail.tpl#L339
Hôm trước làm trên shops em có viết đoạn này để điều chỉnh với ảnh. Còn nội dung thì em chưa thử.

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/18b5165c4157b91c57883ffac0f975fd2b3e3560
