### ISSUE TITLE
Đề xuất thêm cấu hình vào module.block_newscenter.php

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1359]
Hiện tại block module.block_newscenter.php đang bị cố định số lượng bài viết hiển thị và cố định hometext. Vì vậy cần tách ra và cho vào cấu hình block cho tiện, thay vì phải vào trong php chỉnh lại số bài hiển thị và nvclear60 cho hometext

**Comment by anhutbeo** [comment]
Mình cũng góp ý thêm xíu nữa. Mặc định là tin mới, nên cho nó tùy chọn có thể lấy tin theo chuyên mục, theo chủ đề ... Cảm ơn đội code

**Comment by vuthao** [comment]
update: https://github.com/vuthao/nukeviet/commit/94c2e4dfc820b36c810ac6661ee69c8754b4ca81
