### ISSUE TITLE
Lỗi block chưa hiển thị được đúng kiểu metismenu

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1360]
Hiện tại trong html của metismenu còn thếu class dẫn đến không hiển thị được menu dạng metismenu khi sử dụng block metismenu

**Comment by vuthao** [comment]
@ThinhNguyenVB Em xem sửa cái này nhé.

**Comment by ThinhNguyenVB** [comment]
Fixed: https://github.com/ThinhNguyenVB/nukeviet/commit/f246bc80a0f2479a238d71201fc06cc8cf7d2cae
