### ISSUE TITLE
Báo lỗi phần gửi thông tin liên hệ

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#1361]
Như tiêu đề. Hiện mình đang test bản dev mới nhất, nhưng ở form 'GỬI Ý KIẾN PHẢN HỒI' không thể gửi được. Lỗi nhập mã bảo mật chưa đúng (mặc dù đã nhập đúng)
![1](https://cloud.githubusercontent.com/assets/11238423/9422627/3bd82a3a-48c6-11e5-8d57-75bf10ad17e5.png)

**Comment by anhtunguyen** [comment]
Cảm ơn @hoanglongvnpt !
Tôi sẽ fix lỗi trong lần cập nhật tới

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/anhtunguyen/nukeviet/commit/df0c938fa505ba5701abbc2a7e5a47d5318cc3aa
