### ISSUE TITLE
Không có dấu (*) đánh dấu các trường dữ liệu bắt buộc nhập khi thêm bài viết trong module news

### ISSUE THREAD

**Issue by PhamQuocTien132** [nukeviet/nukeviet#1363]

**Comment by anhtunguyen** [comment]
Dấu (*) không nên viết vào đó mà đơn giản trong input hay textarea thêm thuộc tính class: required

**Comment by vuthao** [comment]
update: https://github.com/nukeviet/nukeviet/commit/e28ecaa762e81917223c71244053066d1f0d88b1
