### ISSUE TITLE
Modal defaut: Có đến 3 vị trí đóng modal

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1364]
![selection_143](https://cloud.githubusercontent.com/assets/6407361/9423055/18aabc82-48dd-11e5-94d1-5f99c4fbfc40.png)

Nên bỏ bớt modal footer khi không cần thiết.

**Comment by anhtunguyen** [comment]
OK.

**Comment by hongoctrien** [comment]
Liên quan đến cái này @anhtunguyen  xem giúp em luôn cái này nhé https://github.com/nukeviet/nukeviet/issues/1358

**Comment by anhtunguyen** [comment]
Anh đã xóa footer của modal mặc định rồi nhé.
