### ISSUE TITLE
Lỗi sau mỗi lần thêm block mới ở ngoài site

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1369]
Sau mỗi lần thêm 1 block thì sinh ra 1 đường link mới và ra trang 404 thay vì quay về trang chủ sau khi thêm block dù kiểm tra trong quản lý block thì block đó đã được lưu lại
hình ảnh
![untitled-1](https://cloud.githubusercontent.com/assets/13896524/9431419/0ff64106-4a3b-11e5-99ba-86df1305f6e2.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/09d8ea1254829f3b75717febaaef91825df9b8b8
