### ISSUE TITLE
Lỗi upload tệp tin

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1380]
NukeViet https://github.com/nukeviet/nukeviet/commit/d598194c963fae55324545fceea98fa6e73948b9
Trình duyệt: FireFox 40.0.2

Khi thực hiện upload tệp tin từ phần quản lý upload trong Admin Control Panel, có một số lỗi sau:

1. Điền địa chỉ đường link không có phần đầu là HTTP://, khi ấn nút "upload file" thì hệ thống trơ ra, không có hiện tượng gì, cũng không thông báo đường dẫn phải có http:// (có lẽ việc này không cần, hệ thống nên tự kiểm tra và tự điền vào nếu thiếu).

2. Upload từ internet file này: http://www.lamdong.gov.vn/vi-VN/a/ict2015/bctl/Documents/thamluan/150818_BC_tham_Luan_CNC_thong_minh.ppt, hệ thống thông báo: "System does not recognize the mime type of uploaded file" mặc dù file được các hệ thống khác (ví dụ http://mime.ritey.com) kiểm tra đúng là mime-type là  application/vnd.ms-powerpoint.

3. File docx http://www.lamdong.gov.vn/vi-VN/a/ict2015/bctl/Documents/thamluan/So%20KHCN%20Dong%20Nai-%20huong%20den%20mo%20hinh%20NNTM%20tai%20trung%20tam%20ung%20dung%20sinh%20hoc%20tinh%20Dong%20Nai.docx được thông báo là không được phép tải lên mặc dù cấu hình upload file đã cho phép tải lên documents: 
![anh chup 294](https://cloud.githubusercontent.com/assets/1892900/9460456/5a3dc6bc-4b30-11e5-9543-1c0ef2a1ca8b.jpg)

4. Sau khi nhận được thông báo lỗi, hệ thống không cho upload lên file khác nếu không F5 lại trình duyệt.

**Comment by anhtunguyen** [comment]
1. Đã fix https://github.com/nukeviet/nukeviet/commit/3b52563a53ba984244091889c950c3217918e2be
2 & 3: Thảo xem llại
4. Không thấy hiện tượng này. Vẫn upload như thường

**Comment by hongoctrien** [comment]
Xác nhận lỗi 3.

**Comment by vuthao** [comment]
Lỗi 2 và 3 em thấy vẫn còn tồn tại trên 1 số hosting.

**Comment by anhtunguyen** [comment]
Cái này để sau đi em. Cứ phát hành bản beta đi
