### ISSUE TITLE
Module contact và phần notification chưa đồng bộ

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1384]
Module contact trong acp. Khi đã xem thu moi gửi đến rồi nhưng cái nút báo thư mới bẫn đỏ
ko click vào cái nút thông báo đó mà vào thẳng module contact để xem
Về logic thì khi xem thư thì cần xóa thông báo

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/67d367f22aad412edf5e19f781ac4c0be790fbdf

**Comment by anhtunguyen** [comment]
Còn trường hợp không xem mà xóa thư nữa Thảo

**Comment by hongoctrien** [comment]
Cái này để em sửa tiếp

**Comment by hongoctrien** [comment]
> Còn trường hợp không xem mà xóa thư nữa Thảo

Fixed: https://github.com/hongoctrien/nukeviet/commit/6bc9a2a0315a68590072cd95302007fd60e7620f
