### ISSUE TITLE
Định dạng lại giao diện gửi liên hệ

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1388]
Sau khi gửi xong thì nó đứng mãi thế này một tgian lâu. Nhìn cái hộp thông báo chồng lên không được đẹp cho lắm.
Mình nghĩ cho nó reset nhanh hơn, và vị trí hộp thông báo thay đổi.
![selection_139](https://cloud.githubusercontent.com/assets/6407361/9483808/3b8b1a3c-4bce-11e5-87d1-4b7a40ed5cfd.png)

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/9219c173ae973062763dc1e9ea87ef06e0a0e001
