### ISSUE TITLE
lỗi trang trắng sau khi lưu block nv 4.0.23

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/nukeviet#1392]
![loi-luu-block](https://cloud.githubusercontent.com/assets/8604866/9484931/d4376728-4bdc-11e5-8dd0-2c3127722bd9.jpg)

khi nhấn cấp nhận lưu block thì bị lỗi này

![loi-luu-block2](https://cloud.githubusercontent.com/assets/8604866/9484934/dd379bfe-4bdc-11e5-9b6e-01c5f6994ad5.jpg)

Server : Centos 5.10
Apache : 2.2
mysql 5.5
php: 5.5
cpanel: Koloxo (mod php 5.5)

**Comment by hoanglongvnpt** [comment]
Đồng ý có phát sinh lỗi như trên

**Comment by anhtunguyen** [comment]
Khi thêm khối block mới hay cập nhật block đã có?

**Comment by anhtunguyen** [comment]
Có phải ý bạn nói là lỗi ở phần thêm thêm block trong khu vực Admin?

**Comment by webvangvn** [comment]
vào block rồi nhấn sữa block, cập nhật nội dung block xong lưu lại thì thông tin vẫn lưu nhưng ra trang trắng. và không refesh lại trang quản lý block

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/7a54dbc573866fdd8c8ab8fe0a6d8f522ee1953f
Mọi người kiểm tra xem còn lỗi không nhé
