### ISSUE TITLE
Việt hóa nội dung thông báo upload file

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1393]
- Đang dùng tiếng việt nó lại thông báo tiếng anh, thế thì nữa tây nữa ta.
- "8388608 bytes" cho convert về KB hay MB gì đó dễ đọc hơn.

![selection_140](https://cloud.githubusercontent.com/assets/6407361/9485126/45c12666-4bdf-11e5-9a7c-7629ccde8179.png)

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/f3f48b4cea71b89b0c4a69c7caa9f7f0e7e423db
