### ISSUE TITLE
lỗi số điện thoại trên theme global.company_info.php

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/nukeviet#1394]
![loi-so-dt](https://cloud.githubusercontent.com/assets/8604866/9485250/0c95e532-4be1-11e5-872d-2caa04df89ba.jpg)

Số điện thoại hiển thị bị sai so với hướng dẫn

**Comment by anhtunguyen** [comment]
OK. Cái này anh sửa

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/af7993cba9b4f7b8c31f38129bc43650c833e117
