### ISSUE TITLE
Cập nhật giao diện xem chi tiết bài viết

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1395]
Vị trí này có khoảng thừa ra khi không có bài viết trong danh sách ở đây
![selection_141](https://cloud.githubusercontent.com/assets/6407361/9485257/233ea24c-4be1-11e5-9414-49528cce8e29.png)

**Comment by anhtunguyen** [comment]
Anh làm cái này cho

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/05355da44b69b664d81fec5256651f064797e967
