### ISSUE TITLE
Vuốt màn hình trên giao diện mobile bị đơ

### ISSUE THREAD

**Issue by nethoabinh** [nukeviet/nukeviet#1396]
Em gửi các bác
em gửi vào giao diện mobile vuốt thì bị đơ, khi vuốt xuống thì nó lại bị giữ nguyên vị trí trên header. em đang nghi là lỗi JS gì đó
thanks các bác :(

**Comment by hongoctrien** [comment]
Xác nhận lỗi này.
Lỗi androi - chrome mình không thấy.
Sang Windown Phone bị lỗi.

Nguyên nhân do class **wrap** có sử dụng
```
    overflow-x:hidden;
    overflow-y:auto;
```
Không họat động trên mobile. 
Chưa tìm ra hướng khắc phục.

**Comment by PhamQuocTien132** [comment]
Hiện tại không gặp lỗi này, đã test trên window phone nhưng không có lỗi.

**Comment by hungga** [comment]
![2015-11-01-23-18-55](https://cloud.githubusercontent.com/assets/9975118/10869917/1d77c926-80f0-11e5-8692-d1231c3150f5.jpg)

mobile version trên điện thoại android 4.1.2 của em, vuốt xuống dưới nó ko chịu chạy mà trở lại vị trí đầu trang demo mynukeviet.net

**Comment by hongoctrien** [comment]
Xác nhận có lỗi này trên androi @PhamQuocTien132

**Comment by hongoctrien** [comment]
@PhamQuocTien132 anh Tiến dùng windown phone test lại cái này xem còn lỗi không em với.
NukeViet RC2 https://web124.vinades.net/
@nethoabinh @hungga hai bạn thử lại với địa chỉ trên xem có lỗi không mình với ạ.

**Comment by lyhuutrong** [comment]
https://web124.vinades.net/
cái này trên iphone trong trình duyệt tất cả đều bị hết nhé bạn.

**Comment by hoaquynhtim99** [comment]
Hiện giao diện mobile đã fix lỗi này
