### ISSUE TITLE
lỗi không xem info trên mobile

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/nukeviet#1398]
![loi-vut-tren-dien-thoai1](https://cloud.githubusercontent.com/assets/8604866/9486051/72e6221a-4bec-11e5-9fce-40024c992253.jpg)
![loi-vut-tren-dien-thoai2](https://cloud.githubusercontent.com/assets/8604866/9486052/76dad8d4-4bec-11e5-846f-a913b86ee053.jpg)

vút lên xem thông tin tiếp bên dưới thì lại mất luôn thông tin, và có background mờ
![loi-vut-tren-dien-thoai3](https://cloud.githubusercontent.com/assets/8604866/9486056/7abb2292-4bec-11e5-8e27-1e02f825fc2c.jpg)

**Comment by anhtunguyen** [comment]
Theme mobile hiện tại chưa tương thích bạn. Sẽ hoàn thiện nó trong nukeviet 4 final

**Comment by hongoctrien** [comment]
Chắc do sắp hết pin đó @webvangvn, đỏ lòm rồi kìa =))

**Comment by lyhuutrong** [comment]
mình thấy cái lỗi này và lỗi vuốt bị đơ thì nên cần sửa gấp trên android và window phone và ios trên tất cả các trình duyệt ạ.
Vì nukeviet là mã nguồn phổ biến hiện tại cho các trang nhà nước và kể cả giáo dục ạ. Nên cần fix gấp việc này để mọi người có thể dể dàng xem trên mobile ấy mấy pro.
Hiện tại thì phiên bản này khá đẹp và hay nên ko cần chỉnh sửa gì hết. Chỉ bị như thế và module còn rất ít ạ.
Điều đặc biệt là khó thêm code quảng cáo ví dụ như google adsen ạ.

**Comment by hoaquynhtim99** [comment]
Hiện tại các lỗi trên đã được khắc phục
