### ISSUE TITLE
Lỗi đăng nhập không chuyển hướng khi tồn tại nv_redirect trên url

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1405]
Nukeviet https://github.com/nukeviet/nukeviet/commit/bbe62571766a2ddece67149341dd9ecf8fd0d510
Nguyên nhân là chả có gì xuất chuyển hướng cả

**Comment by anhtunguyen** [comment]
Bạn chép lên đây xem biến nv_redirect mà bạn nói được thiết lập như thế nào

**Comment by dangdinhtu2014** [comment]
Xin lỗi tôi nhầm $nv_redirect đã sử dụng phương thức mã hóa khác 
nv_redirect_encrypt
