### ISSUE TITLE
Tab phần thông tin tài khoản

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1406]
Hiện tại phần tab thông tin ở phần thông tin thành viên, khi chọn tab thì url không tự thay đổi để tự động nhận diện tab cần active khi truy cập trực tiếp từ URL.

Ví dụ: Form bắt buộc người dùng cần đăng ký vào nhóm ABC trước khi bình luận, thì sau khi đăng nhập xong luôn chuyển về Tab thông tin thành viên, chứ không ở luôn Tab Nhóm.

**Comment by anhtunguyen** [comment]
Nếu url thay đổi thì mất thêm 1 lần load trang không cần thiết.
Để link đến tab group trực tiếp (đối với thành viên):
_http://nukeviet.demo/users/editinfo/group/
Nếu không phải thành viên thì cho link đến trang đăng nhập + nv_redirect là trang trên

**Comment by hongoctrien** [comment]
Không anh ạ, ý em là khi click vào tab, URL sẽ tự thêm tham số tab đang active (không load lại trang). Nếu ngưòi dùng copy URL này dán sang nơi khác, thì tab đang chọn sẽ active,chứ ko nhảy về tab đầu tiên.

Cái này thì cũng không quan trọng lắm, nhưng nếu có thêm thì trải nghiệm người dùng cũng được tăng lên phần nào.

**Comment by anhtunguyen** [comment]
Đã thêm. Em test xem có OK không nhé:
https://github.com/nukeviet/nukeviet/commit/66e43e8c9f806e343385899074f571d3b639eeb0

**Comment by hongoctrien** [comment]
Hoan hô anh :D.
Ổn rồi anh, ý em nó như thế. hì

**Comment by anhtunguyen** [comment]
Có 1 cái anh chưa giải quyết được là khi click vào nút back của trình duyệt thì url trả về đúng, nhưng nội dung trang thì đứng nguyên

**Comment by vuthao** [comment]
Cái: "Có 1 cái anh chưa giải quyết được là khi click vào nút back của trình duyệt thì url trả về đúng, nhưng nội dung trang thì đứng nguyên"

Để lại sau nhé anh.
