### ISSUE TITLE
Module menu chưa nạp được menu cấp 3 trở đi 

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1407]
Nukeviet https://github.com/nukeviet/nukeviet/commit/bbe62571766a2ddece67149341dd9ecf8fd0d510
Nạp menu từ các module khác hiện tại chỉ dừng lại ở cấp 2 chưa thể thực hiện ở đến cấp 3 trở đi
ví dụ 
demo 1
=>demo 2
==> demo 3
Thì menu sẽ không nạp danh mục demo 3

**Comment by anhtunguyen** [comment]
Có đấy bạn. Chỉ là thiếu cái icon

**Comment by dangdinhtu2014** [comment]
Tôi đã tạo và nạp khi ấn vào menu cấp 2 thì sẽ chuyển sang trang tạo menu chứ không chuyển tới danh mục tiếp theo test trên module menu

**Comment by anhtunguyen** [comment]
Vấn đề chỉ là cái icon cùng màu với màu nền nên không biết click vào đâu để submenu hiện ra vậy thôi. Tôi sẽ sửa cho nó rõ

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/92c11dc1fa502b1bdab24ee7153606630d2c8a5d

**Comment by dangdinhtu2014** [comment]
có thể bác đã hiểu lầm ý em gửi bác cái video để bác hiểu vấn đề
https://www.youtube.com/watch?v=600RzNvpbM8

**Comment by anhtunguyen** [comment]
À. Đúng là thế. Cái này chuyển sang @vuthao

**Comment by vuthao** [comment]
nhà em đang mất điện, mất mạng, nên cái này để xem sau.
