### ISSUE TITLE
Module giới thiệu sản phẩm trình bày cẩu thả

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1408]
Cách trình bày không hợp lý. hover các đối tượng không có thông báo cụ thể ở dạng tooltip rất khó phân biệt chức năng đó là gì
![demo2](https://cloud.githubusercontent.com/assets/6817130/9488395/004e2ed8-4c04-11e5-9685-a54cecb896d8.jpg)

**Comment by anhtunguyen** [comment]
Chắc lại thêm một lần nhầm nữa rùi. 3 cái button đều có title cả.

**Comment by dangdinhtu2014** [comment]
Có title nhưng sẽ không hiện lên ngay lập tức mà phải ngồi đợi nó hiện. như thế là bất hợp lý. Nên chèn tootlip vào để hiển thị tường minh hơn. Việc bố trí lại các phần cũng nên xem xét lại nhìn không ổn chúc nào. Tôi đã quay lại video cho các bạn tiện xem luôn
https://www.youtube.com/watch?v=nVQPIUzgGZQ&feature=youtu.be

**Comment by anhtunguyen** [comment]
This video is private.

**Comment by dangdinhtu2014** [comment]
đã public

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 xem và chỉnh lại những chỗ nào chưa hợp lý nhé

**Comment by hoaquynhtim99** [comment]
Tôi chẳng thấy cái gì cẩu thả ở đây cả, ai thấy cẩu thả tự xử lý tôi chỉ có khả năng làm ra cỡ đó mà thôi há

**Comment by anhtunguyen** [comment]
Cái này gọi là: được voi đòi Hai Bà Trưng :+1:

**Comment by hoaquynhtim99** [comment]
Tôi nói thẳng 1 câu, anh @dangdinhtu2014 anh có kỳ thị gì với đội phát triển của NukeViet? @dangdinhtu2014 chắc mới đi tẩy não nên thành người khác với @dangdinhtu2011 2010 nhỉ, và anh cũng được đào tạo bài bản về khả năng ngôn từ làm người khác phải sôi sục phải khó chịu anh mới vừa lòng à?

Anh nhìn lại hàng loạt issue của anh có khác với mọi người không? Trong khi cái vấn đề của anh tôi nhận xét là nó CHẢ CÓ GÌ CẢ, anh thích tooltip tôi không thích, tôi làm ra nó không có anh thích anh cho vào chẳng lẽ tôi anh Tú hay anh Thảo từ chối anh, thay vì anh show lên này sao anh không bỏ một chút thời gian sửa giùm chỗ đó, anh có nhiều thời gian mà, anh dạo một vòng, cho vài cái issue rồi còn tự tin khoe thành tích của mình trên group facebook trong khi ngày ngày còn có nhiều người hơn anh họ test, cho issue và tất cả đều hài lòng. 

Không ai phủ nhận đóng góp của anh cho NukeViet cả và tôi cũng vậy, nhưng cá nhân tôi cảm giác anh thiếu một sự "đền đáp" để rồi nó biến hóa ra như thế này.

Tôi là người thẳng tính, tức nước thì vỡ bờ, tôi nói ra suy nghĩ của tôi mạnh dạn cũng như anh mạnh dạn dùng những "thán từ" mạnh mẽ như vậy để tô hoa điểm nguyệt cho những issue của mình.

**Comment by vuthao** [comment]
@hoaquynhtim99 Tiến nó nói, đừng có động vào "Lâm tặc", hí hí.

**Comment by dangdinhtu2014** [comment]
Em xin chân thành cám ơn nhưng lời góp ý chân thành, thẳng thắn của các bác
Từ nay em sẽ không giám thế nữa ạ :D. Các bác nóng tính quá hihi
