### ISSUE TITLE
User Notice

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1409]
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-1' for key 'bid'] [FILE: /modules/news/admin/block.php] [LINE: 58]

**Comment by vuthao** [comment]
@dangdinhtu2014 em mô tả quá trình gây là lỗi đó nhé. Chứ như thế này ngồi tìm bao giờ ra lỗi.

**Comment by dangdinhtu2014** [comment]
khi nạp lại block sẽ xảy ra tình trạng các block có rồi bị đè sẽ dẫn tới lỗi trùng lặp. 
có thể khắc phục bằng cách sử dụng câu truy vấn INSERT IGNORE để trống lỗi block đã tồn tại hoặc select kiểm tra trước khi insert thì sẽ không bị lỗi này. Với module upload cũng vậy. Nhiều trường hợp vì lý do nào đó một folder hay file nào đó bị mất. sẽ dẫn tới lỗi trùng lặp và làm gián đoạn quá trình upload file

**Comment by vuthao** [comment]
Mình đăng ký "Thịt" cái này
