### ISSUE TITLE
Module news admin Lỗi tìm kiếm

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1410]
Có vẻ không hợp lý nhỉ ? Đã sumit form tìm kiếm
![untitled](https://cloud.githubusercontent.com/assets/6817130/9488816/9f28b42c-4c06-11e5-8d69-5ef6cf8b3cca.jpg)

**Comment by vuthao** [comment]
Mình đăng ký "Thịt" cái này
