### ISSUE TITLE
Module upload lỗi updoad file khi đường dẫn admin có chứa @

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1413]
mặc định http://siteban/admin/ thì không sao
nhưng http://siteban/admin@demo/ sẽ gặp lỗi như trong hình

![untitled](https://cloud.githubusercontent.com/assets/6817130/9489306/548424fc-4c0a-11e5-8485-0d559986fe0a.png)

**Comment by vuthao** [comment]
Đăt thư mục thư thế quá ác nhé @dangdinhtu2014 
Cái này để bản 4.1 rồi fix tiện thể.

**Comment by dangdinhtu2014** [comment]
Lỗi do member dính lỗi em test thì tìm ra vấn đề thế thôi chứ mấy khi đổi tên chi cho mệt

**Comment by hoaquynhtim99** [comment]
Cái này không cần sửa, cần ghi chú người dùng không đặt tên thư mục có chứa các ký tự đặc biệt https://github.com/hoaquynhtim99/nukeviet/commit/ba4a7f085736040525777c06b83a5f0165d86771
