### ISSUE TITLE
Warning 

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1414]
Lỗi xảy ra khi tải file từ module upload

[Warning(2): preg_replace(): Compilation failed: invalid range in character class at offset 7] [FILE: /includes/class/download.class.php] [LINE: 206]
[Warning(2): preg_replace(): Compilation failed: invalid range in character class at offset 7] [FILE: /includes/class/download.class.php] [LINE: 218]
[Warning(2): preg_replace(): Compilation failed: invalid range in character class at offset 7] [FILE: /includes/class/download.class.php] [LINE: 255]
[Warning(2): preg_replace(): Compilation failed: invalid range in character class at offset 7] [FILE: /includes/class/download.class.php] [LINE: 269]

**Comment by vuthao** [comment]
Mình đăng ký "Thịt" cái này.
