### ISSUE TITLE
Bố trí các nút chưa hợp lý 

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1415]
đường dẫn admin/index.php?language=vi&nv=themes&op=blocks_func&module=users
![untitled](https://cloud.githubusercontent.com/assets/6817130/9489902/76e17136-4c0e-11e5-90e6-a73caa75a54c.png)

**Comment by anhtunguyen** [comment]
OK

**Comment by vuthao** [comment]
Oái  hai cái này có giao diện khác nhau:

admin/index.php?language=vi&nv=themes&op=blocks
admin/index.php?language=vi&nv=themes&op=blocks_func&module=users

Nếu sửa anh tú bổ sung luôn cái chức năng khác nhé.

**Comment by anhtunguyen** [comment]
Chỉ nó nó sang trái gần với mấy cái nút checkbox thôi em. Còn lại không sửa gì cả

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/f4a7a1736c0c89c33d811229300bd4bb6a2a333c
