### ISSUE TITLE
Lỗi 404 khi bật/tắt kéo thả block

### ISSUE THREAD

**Issue by tuanchung24** [nukeviet/nukeviet#1425]
Mình mới cài đặt phiên bản beta mới nhất thì bị lỗi này. K biết là do phiên bản xampp hay do Nukeviet

https://www.youtube.com/watch?v=QfQydoLy7OA

**Comment by anhtunguyen** [comment]
Liệu đây có phải do localhost:888 không @vuthao

**Comment by anhtunguyen** [comment]
Đúng là lỗi.
Anh sẽ sửa

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/e60ea9cc61b13ac05dc8ba0ddc20fb20b7bcdb40
