### ISSUE TITLE
kéo thả block bị lỗi

### ISSUE THREAD

**Issue by trungnghia1102** [nukeviet/nukeviet#1426]
Chào đội code.bản 4.0.23 kéo thả block bị lỗi.lúc đầu click vào kéo thả block nó sẽ nhảy tới localhosst/..../jW_nKeNT3UWYg_cqF0QyNVBpRX9fHcYN08XwmlfkgV0,

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/e60ea9cc61b13ac05dc8ba0ddc20fb20b7bcdb40
