### ISSUE TITLE
Vấn đề về chữ hoa, chữ thường trên window

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#1427]
Trong admin, nếu đánh tên thư mục là viết hoa ví dụ http://dev.nukeviet4.my/ADMIN/ thì vẫn truy cập được nhưng các file image, css, js lại không load được làm vỡ trang

**Comment by vuthao** [comment]
@anhtunguyen khi này nó xác định site NV_BASE_ADMINURL, và NV_BASE_SITEURL

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/2707c940033e2f6754aded71237659b370740d86
