### ISSUE TITLE
Cập nhật giao diện “Cấu hình giao diện”

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#1429]
Cái này em viết trước lúc NukeViet dùng bootstrap nên form nó xấu quá.
Giờ nên chuyển luôn sang tab và form của bootstrap cho nó chẹp :D

![11953059_416559658551993_5155541388936500809_n](https://cloud.githubusercontent.com/assets/6407361/9512526/a367565e-4cad-11e5-960e-58dcaa032721.jpg)

**Comment by anhtunguyen** [comment]
:)

**Comment by vuthao** [comment]
Cái này lúc nào rảnh thì làm nhé, chứ bây giờ tại thời để đó đã @hongoctrien

**Comment by hongoctrien** [comment]
ok a

**Comment by hoaquynhtim99** [comment]
Trên NukeViet 4.3.01 đã sửa cái này sang Bootstrap và hỗ trợ Responsive
