### ISSUE TITLE
[Lỗi cài đặt] Báo lỗi Charset khi Database name toàn là số

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1431]
Cái này qua nhiều phiên bản vẫn còn.

Cấu hình DB như sau : 
Name 423
Charset utf8mb4_unicode_ci

Khi tiến hành cài đặt, bước 5 sẽ có lỗi
```
Error character set database
```

cái này ở các phiên bản trước thì nó báo lỗi khác. Phiên bản này thì mới báo như trên.
Nếu DB bắt đầu bằng số, có kèm chữ và ký tự khác thì ko vấn đề gì, dù cấu hình DB y chang.

NV : https://github.com/nukeviet/nukeviet/commit/e60ea9cc61b13ac05dc8ba0ddc20fb20b7bcdb40

XAMPP 1.8.3

**Comment by vuthao** [comment]
mô tả rõ lại nhé @anhyeuviolet , chắc hôm qua mình thức khuya nên hôm nay đọc cái này 3 lần vẫn chưa biết  làm thế nào để nó hây lỗi.

**Comment by anhyeuviolet** [comment]
Em làm trong video
https://youtu.be/XHOaNAaYh00

Anh @vuthao  xem thử nhé.

Mô tả lại : 
- Tạo Database có tên : 423; Collation là 	utf8mb4_unicode_ci/	utf8mb4_general_ci	
- Tiến hành cài NukeViet dev
- Tới bước 5 của quá trình cài, sẽ nhận thông báo lỗi
Error character set database

- Nếu là NV từ 4.0.15-4.0.22 ( nhớ là khoảng này ) thì báo lỗi
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes.
Khi đó trong DB ghi được các trường 
![image](https://cloud.githubusercontent.com/assets/6290970/9518591/0044d930-4ce2-11e5-9fe7-54cfed14a324.png)


Em ko chắc là có nhiều trường hợp như này ( Tên DB toàn là số ) nhưng chắc cũng nên xử lý tránh phát sinh vấn đề về sau.

**Comment by anhyeuviolet** [comment]
Chỉ cần tên có chứa thêm chữ/ký tự khác thì sẽ ko bị nữa. Còn toàn số thì sẽ như trên.

**Comment by vuthao** [comment]
Ngoài lỗi CSDL tên toàn là số ra, thì hiện tại mình kiểm tra thì vẫn chưa tương thích với character utf8mb4. Cái này sẽ để nghiên cứu sau chứ hôm nay không fix kịp.

**Comment by anhyeuviolet** [comment]
Ừm !
Trước em có xem post này của anh @vuthao , về lưu ý Collation của DB chứa NV.
https://www.facebook.com/photo.php?fbid=1023159044361028&set=gm.1013340182041415&type=1&theater

Nhưng cái localhost chọn như hình anh đăng thì nó cứ tự đưa về utf8mb4_xxx_xx
Chắc phải xem lại vụ này, vì kiểu như phpMyAdmin ép dùng sang utf8mb4 hay sao ấy.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/b730332cff6cf46781fa28c117b73406abba954b
(Để tránh các lỗi phát sinh, tên CSDL cần bắt buộc ít nhất có 1 ký tự a-z)
