### ISSUE TITLE
[Lỗi giao diện] Trang đăng nhập Admin mất viền khung

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1432]
Như hình ảnh : 
![admin_login_page](https://cloud.githubusercontent.com/assets/6290970/9513547/77a51df4-4cbb-11e5-8920-103972c2c9c7.PNG)

NV : https://github.com/nukeviet/nukeviet/commit/e60ea9cc61b13ac05dc8ba0ddc20fb20b7bcdb40
XAMPP 1.8.3

Các trình duyệt
Firefox 40.
Chrome Latest
MS Edge

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/a88b6f90565e41ec91fb4ce1a8029b127f098170
