### ISSUE TITLE
Lỗi khi sửa block ở trang chủ

### ISSUE THREAD

**Issue by mathagu** [nukeviet/nukeviet#1434]
Môi trường thử nghiệm:
Phiên bản NukeViet: 4.0.23 (sửa lại phiên bản)
Môi trường thử Nghiệm: localhost
Trình duyệt web: Google Chrome
Hệ điều hành: Win 8.1
Máy chủ web: Open Server 5.2.2 Ultimate

Mô tả: Ở trang chủ, bật kéo thả block, chọn sửa block global_boostrap, chuyển thành global_slimmenu, các thông tin khác giữ nguyên. Sau khi bấm chấp nhận, một hộp thoại "Cập nhật thành công" hiện ra, sau đó sẽ chuyển để cửa sổ Block Content, chứ không phải là trang chủ nữa (muốn về trang chủ phải bấm back, rồi thêm một lần Refresh thì việc sửa block mới thực thi).

**Comment by anhyeuviolet** [comment]
Xác nhận là mình ko bị lỗi này nhá ! 
Bạn báo đúng phiên bản NV chưa ?

**Comment by mathagu** [comment]
À... Nhầm, là phiên bản mới nhất 4.0.23 ạ!

**Comment by vuthao** [comment]
@mathagu  Bạn check lại dùm phiên bản hiện tại https://github.com/nukeviet/nukeviet/archive/develop.zip xem còn lỗi đó không nhé. (Nếu download trước 1h chiều hôm nay bạn download lại dùm )

**Comment by mathagu** [comment]
Xác nhận: Ở bản tải về lúc 17:06 thì lỗi này không còn xuất hiện nữa!
