### ISSUE TITLE
Lỗi kéo thả block

### ISSUE THREAD

**Issue by vanthankhue** [nukeviet/nukeviet#1435]
Khi thêm các khối block khu vực CONTACT_DEFAULT, SOCIAL_ICONS, PERSONALAREA bị tràn xuống block Menu site thì không thể sửa hoặc thêm block khu vực Menu site (giao diện default) hoặc block khu vực TOP (giao diện mobile). Chỉ sửa được trong ACP

**Comment by vuthao** [comment]
Bạn mô rả rõ hơn được không, mình đọc thông báo của bạn khó hiểu quá.
Nếu có thể chụp cái hình để dễ hình dung nhé.

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/4c89d454157739fd7e493dc5e7f6d14b740e9844
