### ISSUE TITLE
Upload file dung lượng lơn hơn lên host

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1440]
Trong hệ thống đã có cấu hình: Dung lượng tối đa của file tải lên
Và chương trình quản lý upload cũng đã biết được dung lượng của file
Tuy nhiên nếu file quá lớn vẫn cho upload lên, sau đó báo lỗi làm người dùng rất ức chế.

**Comment by anhtunguyen** [comment]
Cài này anh chỉ chỗ cho mọi người sửa nhé:
1.Trong file themes/admin_default/modules/upload/main.tpl tìm đến đoạn định nghĩa một số biến của js thêm vào nv_max_size = '{NV_MAX_SIZE2}' (assign cái NV_MAX_SIZE2 ở trong file admin/upload/main.php nhé, để đúng định dạng kiểu string, ví dụ: '2mb'
2.Trong file assets/js/upload.js, tìm dòng NVUPLOAD.uploader = new plupload.Uploader({ và thêm xuống dưới: max_file_size : nv_max_size,
Hết

**Comment by vuthao** [comment]
vâng cái này sẽ sửa sau anh, nó chưa cháy nhà chế người.

**Comment by vuthao** [comment]
Tính năng này đã được cập nhật tại: https://github.com/vuthao/nukeviet/commit/e94324ffb1ee465581bc0d97be948b5f3c5086fd
Ngoài ra, module upload đã được cấu hình thêm tính năng Resize images ngay tại trình duyệt trước khi gửi tới máy chủ, để việc upload các file ảnh lớn được nhanh hơn (Nếu không Resize images trước, đưa lên máy chủ vẫn phải Resize, và dung lượng trong quá trinh upload lớn dẫn đến việc upload chậm)

**Comment by hqmdokkai** [comment]
Dùng github large đấy up được file lớn luôn. Lưu ý up file lớn lên kho lữu trữ sẽ làm giảm đi hiệu suất của kho lưu trữ
