### ISSUE TITLE
Hướng dẫn không đúng với thực tế

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1443]
Khi cài đặt site, phần khai báo mật khẩu tài khoản admin hướng dẫn yêu cầu là tối thiểu 6 ký tự, có cả chữ và số. Nhưng nếu sử dụng mật khẩu chỉ toàn chữ thì hệ thống vẫn không báo lỗi gì.

**Comment by vuthao** [comment]
Cái đó là hướng dẫn cho người ta thiết lập an toàn.
Sẽ thiết lập thêm cái mật khẩu này, kiểm tra cả các mật khẩu cấm dùng.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/08a801d73e15a474e5147ff13d998cdb19b798fa
