### ISSUE TITLE
[Bootstrap JS/CSS] Không chạy được hiệu ứng Carousel

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1445]
Mặc định, Bootstrap hỗ trợ hiệu ứng Carousel
Link :http://www.w3schools.com/bootstrap/bootstrap_carousel.asp

Nhưng bộ Bootstrap đang dùng thì không hỗ trợ dù cho mình cấu hình như thế nào. Mình thử thay thế bằng JS/CSS của Bootstrap 3.3.5 trên Getbootstrap (cả JS và CSS mới được ).
Đội code xác nhận cái này dùm mình được không ?
Vì với chức năng này thì làm theme sẽ tiện thêm được mấy phần.

**Comment by anhyeuviolet** [comment]
Link từ Bootstrap về phần Carousel
http://getbootstrap.com/javascript/#carousel

**Comment by vuthao** [comment]
Do tích hợp Carousel vào không phải giao diện nào cũng dùng.
Nên khi tuỳ chình giao diện mình đã bỏ nó đi dể site load nhẹ.

Nếu cần dùng thì bạn có thể tại: http://getbootstrap.com/customize/
file config.json lấy tại giao diện: (tuỳ theo giao diện)
themes/default/config.json
themes/mobile_default/config.json

**Comment by vuthao** [comment]
Để cho tiện, mình sẽ đưa nó vào luôn bản tới để các bạn dễ làm cái này.

**Comment by anhyeuviolet** [comment]
Cảm ơn anh @vuthao !
Do cái này em nghĩ là tích hợp như bản gốc của BT thì thiết kế theme, block hiệu ứng sẽ tránh được việc include quá nhiều thư viện vào code, mà vẫn đảm bảo mức độ nhất định các hiệu ứng.

Hơn nữa thì em đang xem phương án dùng cái này cho shops, show nhiều ảnh SP dưới dạng Carousel như này thì tiện hơn cho người dùng cuối, có một trang sản phẩm vừa đủ dùng.
