### ISSUE TITLE
[Module Comment] Admin quản lý bình luận cho module chưa có HD cách tạo mới admin

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1448]
Hiện thời phần này phải qua phân quyền cho module dùng comment trước, sau đó quay lại phân quyền quản lý comment cho module đó mới có. Nếu không thì phần này trắng xoá.

Mình nghĩ nên bổ sung một dòng yêu cầu tạo người quản lý module ( như đang làm trong news chẳng hạn ) để việc này được rõ ràng hơn.

Thông tin chung : 
NV : https://github.com/nukeviet/nukeviet/commit/0600c3d121d3880059ecd34c61f40e9e22a2d80e
XAMPP 1.8.3

**Comment by vuthao** [comment]
như thế này đã đúng chưa nhỉ @anhyeuviolet 

![untitled](https://cloud.githubusercontent.com/assets/2491500/10462149/4a216f42-7207-11e5-80a8-1850ef3bfca2.png)

**Comment by vuthao** [comment]
update: https://github.com/vuthao/nukeviet/commit/812ab9a0af118f392d25661304a31e391562634e

**Comment by anhyeuviolet** [comment]
Dạ chính xác rồi anh ! 
Thêm dòng đó cho dễ hiểu.
