### ISSUE TITLE
[Module User] Khi đình chỉ user, user không còn hiển thị trong danh sách tài khoản

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1449]
Tạo mới 1 user bất kỳ.
Tại trang quản lý tài khoản (/admin/index.php?language=vi&nv=users) ta uncheck vào checkbox Hoạt động để đưa về trạng thái "Đình chỉ" đối với user đó.

Sau khi hoàn tất, ta F5 và không thể thấy user đó đâu nữa. Chỉ có thể tìm thấy trong trang admin thông quá chức năng "Thêm quản trị".
Do đó nếu lỡ tay đình chỉ user thì user này sẽ bị "ra đảo" khá lâu.

NV : https://github.com/nukeviet/nukeviet/commit/0600c3d121d3880059ecd34c61f40e9e22a2d80e
XAMPP 1.8.3

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/5da0c96ac3126dca2b400b6453c7d1100b6409d4

Ngoài ra để bạn có thể thay đổi trạng thái  ---Trạng thái tài khoản---
![untitled](https://cloud.githubusercontent.com/assets/2491500/9565086/f5032e32-4ee4-11e5-8e6c-f4960018b11b.png)
