### ISSUE TITLE
[Module User] Sai trạng thái hoạt động của Điều hành chung/Quản lý module

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1450]
https://github.com/nukeviet/nukeviet/issues/1449

Tạo user bất kỳ. Phân quyền quản lý một module, ở đây chọn News để thử nghiệm.
Sau khi tiến hành các bước như #1499, User này bị đình chỉ và biến mất khỏi danh sách User.
Tuy vậy khi sang Danh sách quản trị (admin/index.php?language=vi&nv=authors) thì user này vẫn hiển thị ở tình trạng hoạt động.
Cái này có lẽ là vấn đề, vì khi huỷ quyền hoạt động một user thì họ sẽ ko login được, tương đương là họ vẫn là quản trị, nhưng trạng thái phải là Đình chỉ thì mới hợp lý.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/48c91ff4dc2fd01edee1c215dc2360c7f0c4c09b
