### ISSUE TITLE
[Module Contact] Vẫn cho phép chọn gửi liên hệ đến các Quản trị bị đình chỉ

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1451]
Trong module contact, func department, vẫn cho phép chọn các user là Quản trị/điều hành bị đình chỉ. Cái này e là chưa ổn lắm.
https://github.com/nukeviet/nukeviet/issues/1449
https://github.com/nukeviet/nukeviet/issues/1450

**Comment by vuthao** [comment]
Theo mình vẫn cho chọn chử nhỉ, (Chỉ không gửi mail nữa là được) Không cho đăng nhập thì cũng không sao.
Nếu sau này tài khoản đó vẫn làm việc thì không cần cấu hình lại.

**Comment by anhyeuviolet** [comment]
Cái này thì tại em nghĩ theo hướng của các forum. Tức là mất quyền user ( quyền cơ bản ) thì các quyền cao hơn sẽ bị mất đi tương ứng.
Tuy vậy thì điều chỉnh theo cách anh nói cũng là một giải pháp. Nhưng em nghĩ có thêm thông báo lưu ý khi chọn phần này, ví dụ, bên cạnh user sẽ có 1 dấu hiệu hoặc ghi chú là "Đình chỉ" để dễ làm việc hơn.

**Comment by thehung** [comment]
Theo tôi chỉ cần bổ sung thêm dấu hiệu để chỉ ra các quản trị bị đình chỉ
để tránh việc bị hiểu nhầm là đủ. Không cần thiết phải ẩn đi, tránh trường
hợp rắc rối phát sinh về phân quyền khi kích hoạt/ ngưng kích hoạt 1 quản
trị.

**Comment by vuthao** [comment]
update: https://github.com/vuthao/nukeviet/commit/99792ee53bfb7fa9c0082b15f84bfd86b405c28f
