### ISSUE TITLE
Vấn đề alias khi sửa bộ phận liên hệ

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1452]
Khi sửa bộ phận liên hệ, sửa tên bộ phận, sửa xong thì đồng thời input alias cũng thay đổi theo.
Đúng ra cái này tự động bắt alias chỉ khi thêm, còn khi sửa sẽ không tự động đổi, nếu người dùng muốn thì nhấn icon.

**Comment by vuthao** [comment]
fixed
