### ISSUE TITLE
Module contact: Lỗi sử dụng block trên module ảo của contact

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1454]
Ví dụ block global.contact_default.php (các block khác chưa kiểm tra)

Trong câu truy vấn block này sử dụng
```
$sql = 'SELECT id, alias, phone, email, others FROM ' . NV_PREFIXLANG . '_' . $site_mods['contact']['module_data'] . '_department WHERE act=1 AND is_default=1';
```

**$site_mods['contact']['module_data']** sẽ luôn lấy dữ liệu từ module_name = contact
Khi sử dụng block này trên module lien-he (module ảo của contact) thì nó lấy dữ liệu của contact. Xóa module contact đi thì tèo luôn @@

**Comment by vuthao** [comment]
fixed
