### ISSUE TITLE
[Module Author] Công cụ tìm kiếm User chưa hợp lý

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1455]
Khi nhấn tìm thành viên trong phần Author để phân quyền, nếu ko điền thông số gì, mình nghĩ nên show danh sách user ra, thay vì trả về KQ như này.
![image](https://cloud.githubusercontent.com/assets/6290970/9561121/d955d1d0-4e62-11e5-8813-361f80db4346.png)

Thứ hai, khi chọn được User rồi, phần chỉ định thành viên nên hiển thị là tên đăng nhập của thành viên, thay vì ID như vầy ( vì thông tin tìm thì là tên đăng nhập, chọn rồi thì lại là ID user )
![image](https://cloud.githubusercontent.com/assets/6290970/9561130/0c155852-4e63-11e5-90f7-785c7b24f87f.png)

**Comment by vuthao** [comment]
Mình đang xử lý cái này.
