### ISSUE TITLE
Góp ý cơ chế đăng nhập

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1456]
Hiện tại Nukeviet cho phép đăng nhập bằng địa chỉ email rồi, tuy nhiên có một bất cập là hệ thống có phân biệt kí tự viết hoa và viết thường trong địa chỉ email 

Ví dụ: Nếu user có địa chỉ email là: abc@gmail.com thì khi đăng nhập là: Abc@gmail.com lại không được, trong khi cả hai cách viết chỉ là một địa chỉ email duy nhất.

Do đó mình đề xuất là: khi đăng ký thành viên, tài khoản thành viên không được chứa ký tự @
Khi đăng nhập bằng địa chỉ email thì kiểm tra xem có phải là email không, sau đó chuyển hết về ký tự thường rồi mới so với email của tài khoản đó trong table users.

**Comment by vuthao** [comment]
fixed
