### ISSUE TITLE
Module contact chưa hợp lý:

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1457]
Khi click vào module contact, thì thấy show ra form liên hệ và danh sách các department, Tuy nhiên trong admin thì chỉ được mặc định một department.

Vậy khi người dùng muốn liên hệ với bộ phận khác thì phải làm thế nào.
Do đó mình đề xuất hiện thêm selection box để chọn bộ phần cần liên hệ đến

**Comment by vuthao** [comment]
Bản hiện tại đã thay đổi cơ chế liên hệ:
- 1 phòng ban có thể làm nhiều việc, nên chia ra thành: "Các chủ đề liên quan" trong mỗi phòng ban.
- Khi liên hệ, hệ thống sẽ liệt kê ra các chủ đề đẻ khách hàng lựa chọn.

Chúng ta cẩn phân biệt giữa chữ: Chủ đề và Bộ phận.

**Comment by phongaz** [comment]
Chủ đề thì rõ ràng rồi. Nó là vấn đề mà khách hàng liên hệ với site, còn bộ phận là phân công trách nhiệm xử lý. ví dụ mặc định ở admin là customer care dept thì trong thời gian mặc định đấy tất cả các vấn đề khách hàng liên hệ đều gửi đến bộ phận customer care (kể cả liên hệ về mặt kỹ thuật) vậy tồn tại bộ phận kỹ thuật cũng chẳng có ý nghĩa. Do đó nếu cơ chế này thì chỉ cần một bộ phận là đủ, chứ tạo ra nhiều bộ phận khác nhau nhưng khách hàng chỉ liên hệ đến một bộ phận duy nhất trong thời gian bộ phận đó được mặc định thôi.

**Comment by vuthao** [comment]
@phongaz 
vậy tồn tại bộ phận kỹ thuật cũng chẳng có ý nghĩa ---> Việc này để phân quyền những ai quản lý bộ phận đó.

**Comment by phongaz** [comment]
Ok. Issues của bộ phận nào thì hệ thống tự nhận dạng và trả về đúng bộ phận đó.
Nếu đã phân quyền như thế này thì ngoài form nên kiểm tra khách chọn ít nhất một chủ đề (không kể chủ đề id=0) thì không cần thêm cái mặc định nữa.

Thêm nữa, trong phần issue của các bộ phận nên kiểm tra không nhập trùng issue (ví dụ ở customer care có issue: Bug Reports, trong technical dept cũng nhập được issue: Bug Reports

Kết quả là ngoài form có 2 issues: Bug Reports

![duplicated issues](https://cloud.githubusercontent.com/assets/6806295/9567170/974284a2-4f4b-11e5-8a5e-2f99a8d6951a.png)

**Comment by vuthao** [comment]
@anhtunguyen xem lại dùm em cái này nhé, em chưa nghỉ đến việc tên trùng nhau.

**Comment by anhtunguyen** [comment]
Ок

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/95858cc5c57825409a1b72b6c4af4f3e1ca676d9
