### ISSUE TITLE
Bình luận Facebook

### ISSUE THREAD

**Issue by tasequaylai2020** [nukeviet/nukeviet#1458]
Em nghĩ nên thêm chức năng bình luận mở qua hệ thống Facebook để giúp website được nhảy lên mạng xã hội nhiều hơn ạ

**Comment by anhyeuviolet** [comment]
Cái này NV tích hợp sẵn SDK và FB App ID rồi. Nếu thích có thể bổ sung qua block/theme rất dễ dàng.

**Comment by tasequaylai2020** [comment]
Anh có thể hướng dẫn em làm được không?
Facebook App ID em tích hợp rồi. Giờ em ko biết cho nó xuất hiện kiểu gì ạ

**Comment by hongoctrien** [comment]
Bạn kích họat block facebook comment của module comment đó bạn.

**Comment by tasequaylai2020** [comment]
Nhưng mà nó ko xuất hiện ở phía trên cạnh chỗ bình luận hệ thống được ạ.
Của e đây ạ: http://svydtb.edu.vn

**Comment by vuthao** [comment]
Nếu thế bạn sửa lại template thôi.
