### ISSUE TITLE
Thiếu chức năng in trang hoặc tải về khi bài viết ở chế độ đăng chờ duyệt hoặc hẹn giờ đăng

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1459]
Với các bài viết đang ở Chế độ đăng chờ duyệt hoặc hẹn giờ đăng, admin không tạo được bản in hoặc bản tải về mặc dù các nút này vẫn hiển thị.

**Comment by vuthao** [comment]
Mình sẽ fix cái này.
