### ISSUE TITLE
Lỗi block html

### ISSUE THREAD

**Issue by vanthankhue** [nukeviet/nukeviet#1460]
Khi sử dụng block html để chèn hình ảnh hoặc video thì hình ảnh, video trong block không tự động co giãn theo kích thước trình duyệt 
https://drive.google.com/file/d/0B6YxA-jAKrEWVDRXTmE5XzZ3dk0/view?usp=sharing
https://drive.google.com/file/d/0B6YxA-jAKrEWZU53Qm1YOC1SWGc/view?usp=sharing

**Comment by vuthao** [comment]
@vanthankhue  khi bạn tạo issues, vui lòng đọc. Please review the guidelines for contributing to this repository. Nếu lần sau bạn không đúng quy định chúng tôi sẽ đóng luôn issues.

Để làm việc này hiện tại bạn phải sửa lại mã html theo các hướng dẫn sau:
http://getbootstrap.com/css/#images
http://codepen.io/ncerminara/pen/zbKAD/

**Comment by vanthankhue** [comment]
Sorry bạn, mình hiểu nhầm code
