### ISSUE TITLE
Lỗi khi thêm hoặc sửa block

### ISSUE THREAD

**Issue by thangbv** [nukeviet/nukeviet#1461]
Bấm nút lưu block sau khi báo thành công thì bị chuyển vào trang hiển thị block. Chứ không phải trang chủ site.

**Comment by vuthao** [comment]
@thangbv phiên bản hiện tại anh không thấy lỗi đó.
Em kiểm tra lại xem đã hết chưa nhé: https://github.com/vuthao/nukeviet/archive/develop.zip

Hiện tại anh đã ghi chú để nâng cấp site từ bản 4.0.23 lên bản 4.0.24 tại: https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.0.24

**Comment by anhutbeo** [comment]
Mình xác nhận có lỗi này bị trên locahost, nhưng khi mình upload lên host thì kg thấy bị. 
Môi trường thử nghiệm:
localhost
Wamsever . Apache/2.4.9 .  PHP/5.5.12 Win 8 64bit

**Comment by hongoctrien** [comment]
Tương tự https://github.com/nukeviet/nukeviet/issues/1488
Xác định lỗi này. Hôm qua gặp chưa kịp xem hôm nay mở lại hết lỗi :D
