### ISSUE TITLE
lỗi block_newscenter sau khi cài đặt nv 4.0.23 tải từ develop trên github ngày 31/08/2015

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/nukeviet#1467]
![loi_block_newscenter](https://cloud.githubusercontent.com/assets/8604866/9571960/443f79a0-4fd1-11e5-986e-b95b4464f657.jpg)

webserver: apache 2.4
mysql : 5.5
php : 5.6
cpanel : directadmin

**Comment by anhyeuviolet** [comment]
Cái này kiểu như data mẫu ko đầy đủ so với cấu hình block nên bị thế thì phải.

**Comment by webvangvn** [comment]
chắc vậy, mới install xong ra trang chủ bị luôn, chứ chưa cấu hình gì hết

**Comment by hoanglongvnpt** [comment]
Lỗi data mẫu

**Comment by hongoctrien** [comment]
Hiện tại mình thấy không còn lỗi này. Mỗi lần tai về bản mới, nếu có lỗi gì các bạn cài lại hệ thống để cập nhật mới CSDL nhé.
