### ISSUE TITLE
Module page khi đưa lên host bị trắng trang

### ISSUE THREAD

**Issue by trungnghia1102** [nukeviet/nukeviet#1468]
Chào đội code.mình đang sài bản Nukeviet 4.0.23.
khi ở localhost thì module page hoạt động bình thường.nhưng khi mình up lên host thì module page bị trắng trang.Đội code fix chỗ này giùm mình với.cảm ơn đội code.làm việc vui vẻ ! .

**Comment by trungnghia1102** [comment]
site của mình là ngôn ngữ tiếng anh nha đội code

**Comment by vuthao** [comment]
Lôi bạn thông báo đã được fix trước đó: https://github.com/nukeviet/nukeviet/commit/b119d7552a01304052385bdf1ad85f7fac10fd76
