### ISSUE TITLE
Lỗi tooltip

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1469]
Trong file main.js của theme có đoạn này luôn được gọi đến
```
$("[data-rel='tooltip'][data-content!='']").removeAttr("title").tooltip({
		container: "body",
		html: !0,
		title: function() {
			return ("" == $(this).data("img") ? "" : '<img class="img-thumbnail pull-left" src="' + $(this).data("img") + '" width="90" />') + $(this).data("content")
		}
	});
```
trường hợp tắt tooltip trong cấu hình module new nhưng tooltip vẫn hiện, không tắt

**Comment by anhyeuviolet** [comment]
Cái này thì phải vào TP,  đưa các phần data-rel, data-content vào trong khu
```
BEGIN tooltips
```
Mà tưởng news hoàn tất cái này rồi mà ?

**Comment by htuyen1994** [comment]
vừa được bỏ đi xong

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/730eeb53c907726ac40026048a165a2e5302a0c6
