### ISSUE TITLE
Notifications from the system

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1470]
Nukeviet: https://github.com/nukeviet/nukeviet/commit/37aa9ba7affbea457761b72bb20ccc932aa928aa
Attention Attention: Undefined index: act_block in file /includes/core/user_functions.php on line 246
Attention Attention: Undefined index: act_block in file /includes/core/user_functions.php on line 252

**Comment by vuthao** [comment]
Hiện tại phần này là do thiếu ngôn ngữ ở các gói ngôn ngữ khác tiếng viêt.
Trước khi phát hành phiên bản tiếp theo chúng tôi sẽ hoàn thiện.

**Comment by vuthao** [comment]
update: https://github.com/vuthao/nukeviet/commit/8a018269f8517ae7fdf7c59ec07632326b4ea933
