### ISSUE TITLE
Lỗi tìm kiếm khi trong từ khoá có ký tự '/'

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1477]
Khi gõ từ khoá có ký tự '/', nếu kết quả có nhiều hơn 3 thì khi bấm xem tất cả sẽ bị lỗi Not found.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/c96201713e6dfb39e105bf022a8a451f885337c2
