### ISSUE TITLE
Tìm kiếm bị lỗi SQL Injection khi chọn phiên bản PHP 5.5

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1478]
Khi chọn phiên bản PHP 5.5 thì tìm kiếm sẽ không tìm được gì, nếu gõ từ khoá: on in or '1'=='1' sẽ bị lỗi
Khi chọn phiên bản PHP 5.6 thì trắng trơn, không hiển thị gì.

**Comment by vuthao** [comment]
hiện tại tôi kiểm tra không thấy lỗi như thông báo:

demo: http://php56.vinades.net/seek/q=on%20in%20or%20'1'=='1'

@truongemcom bạn cung cấp môi trường thử nghiệm chính xác để chúng tôi kiểm tra nhé: 

https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md

**Comment by truongemcom** [comment]
Đã kiểm tra lại, nguyên nhân là do Mod security chặn lại. Tắt đi thì OK
