### ISSUE TITLE
Thêm cấu hình vị trí chèn logo

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1479]
Mặc định NukeViet chỉ chọn chèn logo ở vị trí: dưới phải
Nên thêm vào các vị trí khác như là: Giữa, Trái, phải, trên, dưới

**Comment by hoaquynhtim99** [comment]
Mình sẽ làm phần này

**Comment by hoaquynhtim99** [comment]
Đã thêm chức năng này: https://github.com/hoaquynhtim99/nukeviet/commit/d362f9097890783e9e1503936d59c0c7c7e9a252

**Comment by truongemcom** [comment]
Thanks

**Comment by truongemcom** [comment]
Có thể làm thêm một chút nữa là cấu hình vị trí chèn logo cho từng module riêng không?

**Comment by vuthao** [comment]
Dừng lại thôi. Có voi đòi luôn hai bà. Vấn đề là rất ít người. Dùng cái này
Vào 14-10-2015 11:12, "Truong Em" <notifications@github.com> đã viết:

**Comment by hoaquynhtim99** [comment]
"Thật sự không thể tin được" @@

**Comment by truongemcom** [comment]
Góp ý để hoàn thiện tính năng cho code mà bị xem là vòi vĩnh, tầm nhìn của chú này kém đến mức thật sự kô thể tin được.
Sorry nhé, cái này mình có thể tự chế được nhưng post lên đây để cho mọi người nâng cấp hoàn thiện thêm tính năng thôi.

**Comment by vuthao** [comment]
@truongemcom Tự chế được mà không đóng góp người lại mà nguồn, mà suốt ngày đi kêu. Nhất ban đó.

**Comment by truongemcom** [comment]
Tại vì mình tự chế theo cách không giống ai, kô chuyên nghiệp như đội Coder Nuke

**Comment by webvangvn** [comment]
bạn fork lại rồi bạn code đoạn tính năng đó rồi gửi lại vào kho code, đội code sẽ duyệt qua đoạn của bạn, nếu hợp lý thì sẽ merge vào kho code chính. Mỗi người một tay lập trình tính năng thì phiên bản mới hoàn thiện.
