### ISSUE TITLE
Giải quyết chức năng siteterms trong module users

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1480]
Mục "Nội quy site" (siteterms) trong module users không quản lý "Quy định đăng ký thành viên" thể hiện ra bên ngoài site khi đăng ký thành viên.

Hiện giờ, đã bổ sung module siteterms, do đó cần xử lý bằng 1 trong 2 hình thức sau: 

Cách 1: Bỏ đi phần siteterms trong module users. => Đưa "Quy định đăng ký thành viên" về module siteterms.

Cách 2: Giữ nguyên chức năng siteterms trong module users nhưng đổi tên thành rules (cho đúng với bản chất). => Đưa nội dung "Quy định đăng ký thành viên" về quản lý trong rules của module users.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/b0f2acb6564e3e0f8232809101b150caf8b49c70
