### ISSUE TITLE
Trình bày giao diện danh sách bộ phận không đẹp

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1483]
Cách bố trí không đẹp lắm, hiển thị khá lộn xộn.
![selection_184](https://cloud.githubusercontent.com/assets/6407361/9654383/bc855eea-5254-11e5-855a-aff363d7b3cd.png)

**Comment by ThinhNguyenVB** [comment]
@hongoctrien  như này dc rồi mà nhỉ, dễ xài ko lằng nhằng như video hay là album

**Comment by hongoctrien** [comment]
Nó ép nhau kìa anh. VD như cái cột thao tác, quá rộng, chứ thao tác nằm bên trái trong khi nội dung bên dưới ở giữa.

**Comment by ThinhNguyenVB** [comment]
ok. để coi theo bootstrap xem chỉnh thế nào :dancer:

**Comment by hongoctrien** [comment]
@ThinhNguyenVB cái này sao rồi a

**Comment by ThinhNguyenVB** [comment]
@hongoctrien  từ từ bình tĩnh, đang làm cái kia gấp quá chưa kịp đụng vô chỉnh cụ thể

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/894d7137f0f5592259873056ef7a50016a1c8db1
