### ISSUE TITLE
Đường link hướng dẫn cài đặt cho cơ sở dữ liệu sqlite2 không hiệu lực

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1484]
Khai cài đặt, nếu chọn cơ sở dữ liệu sqlite2 thì hệ thống hiện popup hướng dẫn tải thư viện bổ sung, tuy nhiên click vào link thì ra link https://github.com/nukeviet/nukeviet/wiki/NukeViet-database-types chưa có dữ liệu.

Hiện giờ đã có NukeViet Store, các thành phần bổ sung sau này nên phân phối tự động qua kho này, tránh mỗi thứ một nơi, dẫn link lung tung khó bảo trì. (Cả việc cài ngôn ngữ bổ sung cũng thế!)

**Comment by hoaquynhtim99** [comment]
Thực ra thì nó không phải là một cái để tải về, mà trước em với anh thảo trao đổi rằng bởi vì mình chưa có chỗ để tải về cũng như chưa có chức năng để tải một cách tự động nên dẫn nó đến tạm một bài hướng dẫn về cái đó, tạm thời chưa có ai viết nên chưa có nội dung
