### ISSUE TITLE
Cập nhật block login

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1485]
Thông báo đăng nhập thành công rồi mà vẫn còn “Quên mật khẩu” => không hợp lý.
![selection_185](https://cloud.githubusercontent.com/assets/6407361/9674921/fd1f9e52-52e0-11e5-8845-75e0b7f9f301.png)

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/14d9c8945f2fa12078f9f76f18b61377b84c27ec
