### ISSUE TITLE
Cập nhật lại chức năng bật/tắt block

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#1486]
Phần này hiện tại chuyển ra ngoài site, khi bật kéo thả block mới thấy bật/tắt block.

Nếu trường hợp ngoài site không dùng được (Lỗi gì đó làm trắng trang, ....) thì không có cách nào sử dụng chức năng bật/tắt block này.

Trước trong quản lý block có checkbox bật tắt, trong cửa sổ thêm block cũng có, nhưng lại bị bỏ đi rồi.

**Comment by thehung** [comment]
Sao bản mới nhất anh lại thấy vấn đề này nhỉ :D

**Comment by anhtunguyen** [comment]
Đã giải quyết ở [NukeViet 4.6](https://github.com/nukeviet/nukeviet/commit/e5019bb19c3852baf7b9a2803fd9143188ecab40)
