### ISSUE TITLE
Chức năng chỉnh sửa block ở home bị lỗi thì phải

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/nukeviet#1488]
Bản dev mới nhất khi bật thả block ở home mà chỉnh sửa xong nó redirect về admin để thêm block mới.

**Comment by vuthao** [comment]
@phamdinhhau hiện tại tôi kiểm tra không bị như thế.
bạn vui lòng cung cấp môi trường thử nghiệm để chúng tôi kiểm tra.

**Comment by phamdinhhau** [comment]
Windows 10.
Chrome 45.
-> Test trên Edge không bị.

**Comment by thehung** [comment]
Xác nhận bị lỗi không thêm được block ở cột block bên trái. Các cột khác không bị. Test trên local và sử dụng nhiều trình duyệt.

**Comment by vuthao** [comment]
Các "Thánh" cứ báo lỗi nhưng có đặt mình vào vị trí của người kiểm tra lỗi không nhỉ.
Giờ muốn làm môi trường thử nghiệm cũng không có thông tin.
Các bạn vui lòng đọc ký lại: https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md

**Comment by thehung** [comment]
Hé hé, quên mất:

Packages:

    Apache 2.4.16
    PHP 5.5.28
    MySQL 5.6.26
    Smarty 3.1.27
    SQLite 3.8.11.1
    PhpMyAdmin 4.4.13.1
    Xdebug 2.3.3

Loaded PHP extensions: Core, bcmath, calendar, ctype, date, ereg, filter, ftp, hash, iconv, json, mcrypt, SPL, odbc, pcre, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, bz2, SimpleXML, wddx, xml, xmlreader, xmlwriter, apache2handler, openssl, gd, mbstring, mysql, mysqli, Phar, pdo_mysql, pdo_sqlite, mhash, 

Windows 10 + FireFox vs Chrome

**Comment by vuthao** [comment]
Hiện tại mình kiểm tra lại vẫn không thấy có lỗi. Các bạn kiểm tra lại trên phiên bản mới nhất nhé.
Nếu vẫn còn thì mở issues mới.
