### ISSUE TITLE
Lỗi sau khi sửa block trong quản lý block

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1489]
Sau khi thay đổi thông số cấu hình của block và click chấp nhận thì bị đẩy sang trang  Access forbidden! Error 403 của trình duyệt
![loi403](https://cloud.githubusercontent.com/assets/13896524/9698108/7649412e-53d2-11e5-82d8-feefe1a6ac3b.png)

**Comment by vuthao** [comment]
Lỗi này cập nhật lên phiên bản mới nhất sẽ hết nhé @ThinhNguyenVB

**Comment by ThinhNguyenVB** [comment]
@vuthao  ok anh thảo, cái này do lúc trộn có vấn đề gây ra, copy đè file hệ thống là hết
