### ISSUE TITLE
Chuyên mục nhiều qúa làm breakcrum lỗi

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1490]
![selection_209](https://cloud.githubusercontent.com/assets/6407361/9698396/eb117f52-53dd-11e5-94d8-a7f10c725062.png)

**Comment by vuthao** [comment]
cái breakcrum không biết có nên hiển thị 4 cái cuối cùng để không lỗi. 
Hiện tại mình cũng chưa có giải pháp cho cái này.
Cái này cũng là vấn đề trên mobile.

**Comment by anhtunguyen** [comment]
Anh định dùng css và js giải quyết vấn đề này như sau:
- Dùng JS đo chiều rộng từng thành phần của breadcrumbs. Nếu tổng chiều rộng breadcrumbs dài hơn chiều rộng của khối chứa breadcrumbs này thì cho ẩn thành phần đầu tiên. Tiếp tục đo. Nếu vẫn dài hơn thì ẩn tiếp thành phần thứ 2...
- Khi có thành phần ở chế độ ẩn thì xuất hiện hình < ở phía trái breadcumbs. Click vào nó thì thành phần cuối cùng trong danh sách ẩn sẽ hiển thị, đồng thời thành phần cuối cùng trong danh sách hiển thị sẽ bị ẩn. Lúc này sẽ xuất hiện hình > ở bên phải của breadcrumbs.
Mọi người nghĩ sao?

**Comment by hoaquynhtim99** [comment]
Lúc thành phần cuối cùng của phần hiển thị ẩn đi và thành phần đầu tiên của phần ẩn hiện lên thì em nghĩ chưa chắc chiều rộng của các thành phần hiển thị lúc bây giờ đã phù hợp với chiều rộng của khối chứa breadcrumbs.

Theo ý em làm thế này: Chiều cao của các thành phần breadcrumbs là cố định do đó cố định luôn chiều cao của khối chứa breadcrumbs và cho thuộc tính nó là overflow="hidden"; dùng javascript đo tổng chiều rộng của các thành phần breadcrumbs nếu lớn hơn chiều rộng của thành phần chứa nó thì có thể hiện dấu ... vào cuối, khi rê chuột vào con trỏ chuột đổi thành <-> và có thể kéo trượt sang hai bên để xem các thành phần bị ẩn

**Comment by vuthao** [comment]
@hoaquynhtim99 Tham khảo cái anh Tú làm xem có được không nhé. (Đã gửi qua tin nhắn trước đó)

**Comment by hoaquynhtim99** [comment]
Hiện tại đã sửa cho giao diện di động, giao diện desktop chắc là không kịp làm trong hôm nay https://github.com/hoaquynhtim99/nukeviet/commit/0995e162c3113fd1d23fb75ea1e915850cb353e5

**Comment by truongemcom** [comment]
chuyên mục nhiều quá thì nó xuống hàng chứ có gì đâu mà lỗi. Để vậy củng ổn kô cần phải sửa

**Comment by hoaquynhtim99** [comment]
@truongemcom Hiện tại mình đã sửa cho di động và đang làm cho giao diện desktop, nó sẽ không xuống hàng nữa với mọi độ dài Breadcrumbs, mời bạn trải nghiệm ở phiên bản sắp tới

**Comment by hoaquynhtim99** [comment]
Đã xong
