### ISSUE TITLE
Lỗi sau khi tách block

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1491]
1. Sau khi tách nhóm của 1 block, kéo block đó ra chỗ khác thì block bị điều khiển lại là block cũ chứ không phải block mới bị tách.

2. Sau đó chức năng tách nhóm bị lỗi, không tách nhóm các block khác được nữa.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/18d638eb93f35fefc27ae2b55498729b3479dd5b
