### ISSUE TITLE
Trường tùy biến dữ liệu của Module User chưa hợp lý

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/nukeviet#1493]
Nếu chọn loại dữ liệu là ngày ví dụ làm ngày sinh. Nhưng từ ngày chỉ có 1/1/2005 -> 31/12/2025.

**Comment by hongoctrien** [comment]
Cái này cũng ko phải lỗi, mặc định của datepicker nó như thế, chọn 2025 nó sẽ nhảy ra các năm tiếp theo.
Nhưng mà fix luôn tránh hiểu nhầm https://github.com/hongoctrien/nukeviet/commit/1de5ed20fbc01a74f22a73a913dbdea80cfad7c4
