### ISSUE TITLE
Có nên sử dụng sqlsrv thay cho mssql

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/nukeviet#1494]
AE cho ý kiến nha :)

**Comment by vuthao** [comment]
MÌnh thì dùng PDO_SQLSRV Driver Cho PHP 5.4 để chuyển các site Chạy mssql sang MySQL

http://msdn.microsoft.com/en-us/library/cc296170%28v=sql.105%29.aspx

Còn để mà chạy NukeViet trên mssql sẽ có nhiều việc phải làm

**Comment by phamdinhhau** [comment]
Mình cũng đang chạy PDO SQLSRV và đang test khả năng tương thích của mssql. Hiện tại không tương thích rất nhiều.

**Comment by vuthao** [comment]
Chúng tôi sẽ không phát triển NukeViet trên mssql, mà chỉ có kế hoạch trên Oracal. Nên nếu bạn dự định làm thì tự phát triển nhé.
