### ISSUE TITLE
Lỗi ở NV_GROUPS_GLOBALTABLE, NV_USERS_GLOBALTABLE

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/nukeviet#1496]
define( 'NV_GROUPS_GLOBALTABLE', $db_config['dbsystem'] . '.' . $db_config['prefix'] . '_groups' );
define( 'NV_USERS_GLOBALTABLE', $db_config['dbsystem'] . '.' . $db_config['prefix'] . '_users' );

Khi thêm $db_config['dbsystem'] -> Lỗi

**Comment by vuthao** [comment]
báo lỗi của bạn không đúng quy định: https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md
