### ISSUE TITLE
PDO::PARAM_STR truyền biến lentgh không insert, update đc dữ liệu trên mssql

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/nukeviet#1497]
Như tiêu đề

**Comment by hoaquynhtim99** [comment]
Hình như NukeViet chỉ mới test sử dụng trên Oracle với MySQL

**Comment by vuthao** [comment]
Trên Oracle sẽ cần việc này. Chúng tôi sẽ không hỗ trợ mssql bởi CSDL này không chạy đươc trên các hệ điều hành khác nhau.
