### ISSUE TITLE
Lỗi cảnh báo Lỗi cảnh báo:  file /includes/core/filesystem_functions.php on line 783

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#1498]
Thông báo từ Hệ thống
Lỗi cảnh báo Lỗi cảnh báo: getimagesize(/home/...../domains/nhanghiduthom.com/public_html/uploads/news/http://m.f17.img.vnecdn.net/2013/11/28/chesua-1317-1385613803.jpg): failed to open stream: No such file or directory in file /includes/core/filesystem_functions.php on line 783
![on line 783](https://cloud.githubusercontent.com/assets/8376014/9714820/fb225936-5584-11e5-8433-a46723ad7c01.png)

Lỗi này xuất hiện khi đăng tin trong News phần [Hình minh họa] không up ảnh lên host mà dáng url hình ảnh từ 1 url ngoài vào.

**Comment by NukeVietCMS** [comment]
![on line 783](https://cloud.githubusercontent.com/assets/8376014/9714806/e18e6208-5584-11e5-9d8c-45918546304a.png)

**Comment by hongoctrien** [comment]
@vuthao có vẻ hàm **is_image** có vấn đề khi ảnh không tồn tại.

Trong hàm is_image có sử dụng hàm **getimagesize()**. Để tránh những lỗi cảnh báo thế này thì truwowcs khi dùng hàm is_image phải kiểm tra xem ảnh có tồn tại hay không. Vào đây gặp hàm getimagesize() trong khi url ảnh không đúng (VD khi sản phẩm không có ảnh minh họa) thì sẽ gây lỗi cảnh báo.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/a5f70e4b2bae5bd43d38617c7a9f8dbb008c6207
