### ISSUE TITLE
NV 4.0.23 bỏ phẩn subcatmore của category?

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/nukeviet#1500]
Như tiêu đề

**Comment by hongoctrien** [comment]
Nói cụ thể nhé @phamdinhhau , nó ở rất nhiều chổ.

**Comment by phamdinhhau** [comment]
ở Main module News đó em.

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/5c76b7c7067127b1b1162ccb94b2aa1a08a4c84e
