### ISSUE TITLE
Tắt comment cho module new nhưng vẫn hiện hit comment.

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/nukeviet#1501]
Ảnh đính kèm sau khi đã tắt comment của module. Phần này ko đc hợp lý lắm.
![tim ki m thong tin li t si - bchqs b c k n](https://cloud.githubusercontent.com/assets/1614842/9757066/6e098dd2-5708-11e5-95b7-626a5b91ba66.png)

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/eca95477b543816fb52b846ddd0db0e0807e0f3f
