### ISSUE TITLE
Đăng hình trong bài viết

### ISSUE THREAD

**Issue by hpleduit** [nukeviet/nukeviet#1502]
Chào mọi người cho mình hỏi tí cái này đã khắc phục được chưa mà mình dùng mới phát hiện ra:
1. Đăng hình ảnh minh họa cho bài viết ở phần "Trình bày hình trong bài viết" chọn chế độ Hiển thị dưới phần mở đầu đăng xong ra xem thì hình ảnh nằm trên cùng không nằm dưới phần mở đầu như phiên bản 3.4.
2. Phần chèn hình ảnh vào bài viết ở trình soạn thảo lại có hiện tượng nếu ta canh giữa hình ảnh trong bài viết thì xuất hiện đoạn code sau style="display:inline-block" trong thẻ <figure class="image" style="display:inline-block">, nếu dùng style="display:inline-block" thì reponsive sẽ ảnh hưởng đến hình ảnh bị vỡ trong những màn hình có độ phân giải nhỏ. mình test nếu xóa được đoạn style="display:inline-block" thì hình sẽ auto theo chiều rộng trong mọi kích thước màn hình.
Monh anh em có thể hướng dẫn cách khắc phục và cho ra phiên bản mới hoàn thiện hơn. Cảm ơn.

**Comment by hongoctrien** [comment]
1. Fixed: https://github.com/hongoctrien/nukeviet/commit/d9556e3234372baffb5f64dec7f3649414283f78
