### ISSUE TITLE
Lỗi xát định điều hướng editor trong module news

### ISSUE THREAD

**Issue by trungnghia1102** [nukeviet/nukeviet#1503]
Chào admin.trong bản Nukeviet 4.0.23,mình thêm vào 1 trường images_orther
khi thêm tin tức click vào xuất bản thì nó hiện ra bảng thông báo là Trang này yêu cầu bạn xác nhận rằng bạn muốn rời đi - dữ liệu mà bạn đã nhập có thể sẽ không được lưu.mình click vào xát nhận thì tin vẫn thêm vào bình thường.Nhưng mỗi lần thêm tin tức mà lại hiển thị xát định chuyển hướng thì rất phiền ak.
Phiên bản NukeViet: 4.0.23
Môi trường thử Nghiệm: Localhost/ hosting
Hệ điều hành: win8 32bit
Trình duyệt web: Mozilla Firefox 27.0,Chorme Phiên bản 45.0.2454.85 m
Máy chủ web: XAMPP 1.8.3

**Comment by vuthao** [comment]
Nếu bạn lập trình thêm, thì bạn cần sửa để nó tương thích nhé.
Với phần này thì mình không giúp ghì được.
