### ISSUE TITLE
Lỗi không nén được javascript 

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1504]
@anhtunguyen Xem lại dùm em các site sau không nén  được bằng http://closure-compiler.appspot.com do cách viết javascript:

/themes/mobile_default/js/main.js
/themes/default/js/main.js

**Comment by anhtunguyen** [comment]
Fixed
https://github.com/nukeviet/nukeviet/commit/859902c5765f1cb7d32225b8e78069c6a54f72f5

**Comment by anhtunguyen** [comment]
ở đây không phải do cách viết, mà đơn giản là lỗi thừa một dấu phẩy
