### ISSUE TITLE
Sử dụng prefix tên db trước NV_GROUPS_GLOBALTABLE và NV_USERS_GLOBALTABLE mssql không chạy

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/nukeviet#1506]
define( 'NV_GROUPS_GLOBALTABLE', $db_config['dbsystem'] . '.' . $db_config['prefix'] . '_groups' );
define( 'NV_USERS_GLOBALTABLE', $db_config['dbsystem'] . '.' . $db_config['prefix'] . '_users' );

-> mssql không chạy

**Comment by vuthao** [comment]
NukeViet tôi sẽ không phát triển cho mssql.
Tạm thời bạn có thể sửa lại hai dòng trên như sau, Tôi sẽ sửa lại dòng này cho các bản tới.
```
    define( 'NV_GROUPS_GLOBALTABLE', $db_config['prefix'] . '_groups' );
    define( 'NV_USERS_GLOBALTABLE', $db_config['prefix'] . '_users' );
```

**Comment by phamdinhhau** [comment]
Trả lời hơi thiếu trách nhiệm. Tuy nhiên, NV không phát triển cho mssql cũng không sao vì tôi cũng tự phát triển cho phù hợp được.
