### ISSUE TITLE
Lỗi khi cảnh báo sau khi kích họat đa ngôn ngữ

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1508]
ACP, sau khi kích hoạt đa ngôn ngữ (kích họat thôi chứ chưa cài ngôn ngữ dữ liệu), tại góc phải xuất hiện chọn 3 ngôn ngữ là Việt, Anh và Pháp. Click vào Pháp và Anh lỗi

```
Notice: Undefined index: site_domain in /media/hongoctrien/DATA/MyHost/NukeViet/nukeviet4.vn/includes/mainfile.php on line 330

Notice: Undefined index: name_show in /media/hongoctrien/DATA/MyHost/NukeViet/nukeviet4.vn/includes/functions.php on line 663
```

Cùng vấn đề 
https://github.com/nukeviet/nukeviet/issues/1471
https://github.com/nukeviet/nukeviet/issues/1472

**Comment by vuthao** [comment]
https://github.com/vuthao/nukeviet/commit/a52f8e28318d0ea76805ffd9aa7d0d06c821022d
