### ISSUE TITLE
Thông báo từ Hệ thống  user_functions.php on line 108

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#1509]
Thông báo từ Hệ thống
Nên chú ý Nên chú ý: unserialize(): Error at offset 202 of 212 bytes in file /includes/core/user_functions.php on line 108

Cái này xuất hiện khi chạy module ảo của news làm module trang chủ và giao diện sử dụng là mobile_default (chạy chế độ mobile) trên máy tính.

**Comment by vuthao** [comment]
Lỗi này xẩy ra do việc cấu hình blocks lưu vào bị lỗi CSDL, bạn cần kiểm tra từng block xem sao.
Hiện tại mình không thấy có lỗi này

**Comment by hongoctrien** [comment]
Xác nhận không thấy lỗi này.
