### ISSUE TITLE
Lỗi đăng ký/tạo thành viên mới trong nukeviet 4.0.23/nukeviet-dev

### ISSUE THREAD

**Issue by vinatec789** [nukeviet/nukeviet#1511]
Phiên bản sử dụng: nukeviet 4.0.23/nukeviet -dev
System: linux
Trình duyệt: Google chrome, firefox, microsoft egde
Khi tạo thành viên mới bằng tài khoản quản trị tối cao(chức năng thêm thành viên) hoặc đăng ký thành viên mới ở trang chủ thì đều báo lỗi : Email không đúng quy định
Mặc dù email gõ vào không lỗi gì
Rất mong ban quản trị xem và khắc phục dùm

**Comment by vuthao** [comment]
Email bạn nhập là email nào, nếu có cung cấp link demo nhé, chứ cái này mình hôm qua đã có 60 người dùng chức năng này chưa ai bị.

**Comment by vinatec789** [comment]
Nhờ vuthao kiểm tra dùm 
http://nsc.edu.vn/admin/index.php?language=vi&nv=users&op=user_add
Tai khoan quan tri:
ten dang nhap:trongtuan.vina@gmail.com
pass:$newstar2015$
Thong tin thanh vien can dang ky
ten dang nhap:phongkinhdoanh
pass:$phongkinhdoanh2015$
email dang ky thanh vien moi: phongkinhdoanhnewstar@gmail.com
Cảm ơn vuthao

**Comment by NukeVietCMS** [comment]
Bạn xem lại thử cấu hình host thử thế nào chứ mình sử dụng đâu thấy bị lỗi này.

**Comment by hongoctrien** [comment]
@vinatec789 bạn kiểm tra lại ở phiên bản mới nhất lần nữa nhé. 
Nếu vẫn bị vui lòng gửi lên email bạn nhập, mọi người xem thử.

**Comment by phonglqdo** [comment]
Mình cũng dính lỗi này các bạn. xin vào trang emtuhoc.com đăng ký thành viên sẽ thấy lỗi. Xin kiểm tra giúp dùm. 

Thanks
