### ISSUE TITLE
Lỗi đăng nhập bằng block

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1512]
Phiên bản NukeViet	4.0.23
Phiên bản PHP	5.6.8
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ	DARWIN
Phiên bản Database	mysql 5.6.24
-----
Đăng nhập thành viên nó chỉ hiện ra đoạn này
{"status":"ok","input":"","mess":"\u0110\u0103ng nh\u1eadp h\u1ec7 th\u1ed1ng th\u00e0nh c\u00f4ng","redirect":""}

**Comment by vuthao** [comment]
@nhimthulinh Có thể upload lên host để xem demo không nhỉ, mình kiểm tra  bản hiện tại không thấy có lỗi này.

**Comment by dangdinhtu2014** [comment]
Lỗi này bác Tú Nguyễn mới fix rồi
