### ISSUE TITLE
Chức năng hiển thị file trong module upload

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1513]
Các module như file khi hiển thị sẽ không cần hiển thị ảnh thumb, do đó nên trình bày theo danh sách các file sẽ tiện nhìn hơn

**Comment by hoaquynhtim99** [comment]
Đã thêm chức năng này https://github.com/hoaquynhtim99/nukeviet/commit/42b1c71af6ca2d059593cfdb9ebb8c57c9090390
