### ISSUE TITLE
Lỗi cài đặt phiên bản NukeViet 3.4.03

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1515]
Phiên bản NukeViet 3.4.03 https://github.com/nukeviet/nukeviet/commit/f2cd2d5343cc1cddc733769ea0cc289714cc58a7 bị lỗi ngay khi cài đặt mới:

![anh chup 346](https://cloud.githubusercontent.com/assets/1892900/9831256/324dd5fa-5979-11e5-9e70-997b870e74c3.jpg)

Môi trường thử nghiệm: Windows 10 + VertrigoServ 2.35

**Comment by vuthao** [comment]
NukeViet 3.4.03 chỉ chạy được cho PHP 5.3 thôi.
Giờ tập trung cho NukeViet 4 thôi. Chứ sửa cho tương thích lại mất vài ngày.
