### ISSUE TITLE
Lỗi trùng lặp file Css module menu

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1517]
Nếu một block menu mà sử dụng nhiều lần sẽ dẫn tới tình trạng lặp lại file Css 
![untitled](https://cloud.githubusercontent.com/assets/6817130/9842357/41e79dc0-5ad7-11e5-8f2e-67a5ed3d517c.jpg)

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/bbd7606880cccebe70034a6e3ed3c4729aebf2c4
