### ISSUE TITLE
col-md trong trường hợp chỉ có 1 bài viết và trường hợp có nhiều bài viết khác

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1519]
Như trường nếu có tin khác thì nó sẽ co lại tin chính về kích thước col-md-16 và sẽ có padding bên trái bên phải nhưng khi không có tin khác thì nó sẽ dãn hết nhưng lúc này sẽ padding sẽ = 0 như vậy thì trường hợp ko có tin khác thì nó sẽ dài hơn về kích thước
if( $a > 1 )
{
	$xtpl->assign( 'WCT', 'col-md-16 ' );
}
else
{
	$xtpl->assign( 'WCT', '' );
}

như vậy thì câu lệnh chỗ này phải là 
if( $a > 1 )
{
	$xtpl->assign( 'WCT', 'col-md-16 ' );
}
else
{
	$xtpl->assign( 'WCT', 'col-md-24' );
}

thay vì để rỗng

**Comment by anhyeuviolet** [comment]
cái này đúng :D.
Chỉnh trong theme.php nhỉ.

**Comment by ThinhNguyenVB** [comment]
đã fix rồi à, nhanh thế, đẻ thí mình đẩy lên kho code cho, như kia ko dc chấp nhận vào kho đâu vì tên tiêu đề

**Comment by anhyeuviolet** [comment]
Ủa vậy hả ? :D đó giờ mình toàn để tiêu đề vậy mà.

**Comment by ThinhNguyenVB** [comment]
hihi, ko sao, lần sau có commit để tiếng anh ngắn gọn nhưng nói dc vấn đề là ok luôn :dancer:
