### ISSUE TITLE
[HỎI] Lỗi không đăng nhập được thông qua facebook

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1525]
Rất tiếc là OpenID-Server này không cung cấp đủ các thông tin cần thiết để có thể đăng nhập vào website của chúng tôi
Em gặp lỗi này khi đăng nhập bằng facebook các bác có thể cho em biết nguyên nhân tại đâu không ạ ?

**Comment by thehung** [comment]
Hi @dangdinhtu2014 

Em đã cấu hình thành công chức năng này bao giờ chưa? Chụp lại cấu hình và màn hình báo lỗi nhé. Và gửi link demo càng tốt!

**Comment by vuthao** [comment]
Chủ thới không trả lời, xin phép đóng
