### ISSUE TITLE
Chức năng cấu hình oauth  module users chưa hợp lý

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1527]
Trường hợp nếu nhà phát triển có nhiều nguồn thì file config trong admin module cũng theo đó mà tăng lên như vậy là không hợp lý các nguồn đều dùng. Mình đề xuất nên tạo cơ chế chỉ cần sử dụng 1 file config cho tất cả các nguồn

**Comment by dangdinhtu2014** [comment]
Vấn đề nữa là không hỗ trợ thêm nguồn mới tự động

**Comment by vuthao** [comment]
Nghiên cứu thêm nhé @dangdinhtu2014
