### ISSUE TITLE
Đăng nhập với Facebook bị lỗi

### ISSUE THREAD

**Issue by tasequaylai2020** [nukeviet/nukeviet#1528]
Em đăng ký tài khoản thông qua Facebook được rồi, tuy nhiên em ko thể đăng nhập lại lần nữa.
Khi tích hợp Facebook em không sử dụng tài khoản tự tạo trên hệ thống mà mình tự tạo.
và lần sau em kick vào đăng nhập thì bị lỗi trắng trang.
Đây là liên kết tới website của em ạ:
http://svydtb.edu.vn em đang sử dụng bản 4.0.22

**Comment by vuthao** [comment]
Trước tiên bạn cần xem cái sau:

http://wiki.nukeviet.vn/nukeviet:admin:news:facebookapi

Sau đó vào phần quản trị: my_domain.com/admin/index.php?language=vi&nv=users&op=config
để cấu hình phần: Các nhà cung cấp Oauth, OpenID được chấp nhận
