### ISSUE TITLE
Góp ý sử dụng cáu hình mô tả ngắn gọn của module news

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1529]
Hiện tại phần "Hiển thị phần Giới thiệu ngắn gọn khi xem bài viết" và hiển thị giới thiệu ngắn gọn khi đăng đang xung đột hoạt động không hợp lý
Do vậy phần cấu hình này cho về khi đăng bài viết thành nút button và "Trình bày hình trong bài viết" làm mờ không cho chọn, khi tích vào nút button để show mô tả ngắn gọn thì mới hiện các tùy chọn để xử lý tiếp tránh việc tắt trong cấu hình module mà tùy chọn trong bài viết vẫn chọn mà không hiện ngoài site
-> "Hiển thị phần Giới thiệu ngắn gọn khi xem bài viết" cho từng bài thay vì dùng chung

**Comment by vuthao** [comment]
@ThinhNguyenVB không hợp lý ở chỗ nào cần chỉ rõ nhé.

Đang trong module new sao lại có sản phẩm. Em viết xong cần đọc lại nhé.

**Comment by hongoctrien** [comment]
@ThinhNguyenVB đọc em không hiểu gì luôn :D
Mô tả lại em xí

**Comment by vuthao** [comment]
Xin phép đóng issues, do người viết không trả lời.
