### ISSUE TITLE
[Module] NV không nhận diện được các module mà tên có - hoặc _

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1533]
Như tiêu đề. Mình thử đóng gói  một số module với - và _ thì không nhận diện được trong quản lý module. Ví dụ : nv-photos hoặc nv_photos.

Nếu là dấu _ thì ko nói nhưng hy vọng dấu - có thể được nhận diện trong hệ thống; chứ chỉ cho viết liền thì tên module nhiều khi kỳ cục lắm.

**Comment by vuthao** [comment]
@anhyeuviolet  kiểm tra lại nhé, mình thường dùng module có dấu gạch ngang.

Với gạch dưới thì chắc chắn là không được nhé, do đã cấu hình thế. Nguyên nhân bạn copy link module có dấu gạch dưới, sau đó copy vào work, sau đó enter sẽ thấy.

**Comment by anhyeuviolet** [comment]
Ah. Xác nhận. Em đóng gói module chưa chuẩn nên nó không nhận diện.
Còn gạch dưới thì ko cần thiết, vì URL under score cũng ko tốt. Cảm ơn anh @vuthao  :D
