### ISSUE TITLE
Module contact link đến bộ phận không hoạt động.

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1538]

**Comment by hongoctrien** [comment]
Cái này em ko hiểu lắm a @vuthao

**Comment by vuthao** [comment]
Trong cấu hình: Các bộ phận, có phần Liên kết tĩnh để làm link tới từng bộ phận ở ngoài site. Hiện tại anh Tú mới xây dựng lại là gửi theo: Các chủ đề
Không biết sẽ phải làm cái này thế nào nữa.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/95858cc5c57825409a1b72b6c4af4f3e1ca676d9
