### ISSUE TITLE
Block global.block_category.php cần đưa html ra khỏi php

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1539]
Hiện tại block này trong php có chứa html, html cần cho ra tpl để có thể chỉnh sửa tùy biến html mà không phải động tới html trong file php

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/d0db60ba949972c388734600f325528f16d12103
