### ISSUE TITLE
Lỗi trang trắng khi cài đặt ở bước 5

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1540]
Phiên bản NukeViet 6e5b7d26facd9732d9e2bab1243810b8d4eaf47d bị lỗi trang trắng khi cài đặt tại bước 5.

Môi trường thử nghiệm: Windows 10 + VertrigoServ 2.35

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/95858cc5c57825409a1b72b6c4af4f3e1ca676d9
