### ISSUE TITLE
Lọc  Nhật ký hệ thống

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1541]
Nhật ký hệ thống Lọc theo module chưa thể hiện tên module, và chưa lọc được module ảo của mố module như law

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/11344d13a4b4314bae4843812a2d4738a73d9dc6

> và chưa lọc được module ảo của mố module như law

Cái này em thấy vẫn lọc được module ảo. Test trên module news và laws
