### ISSUE TITLE
Lỗi: Dữ liệu mẫu trên module ảo.

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1542]
Tạo module tin-tuc từ news (có dùng dữ liệu mẫu). => đường dẫn ảnh minh họa không tồn tại.

**Comment by vuthao** [comment]
Việc này phải nhận thôi, hoặc cần đưa cả file upload vào module sẽ gây nặng module.
Theo ý kiến cá nhân của mình, thì không cần sửa.

**Comment by thehung** [comment]
Đóng gói dữ liệu mẫu thì cần bao gồm cả database và file.

Tuy nhiên cái này sửa sau đi.

**Comment by vuthao** [comment]
đã fix cho module news, các module khác cần làm tương tự: https://github.com/vuthao/nukeviet/commit/1d7abf8cee9ae5107c529545bcd8c93e70efacf4
