### ISSUE TITLE
Cập nhật hàm loginForm()

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1543]
Hiện tại hàm này mở popup đăng nhập, sau khi đăng nhập quay lại trang hiện tại.
Nên có thêm tham số để chuyển đến trang khác sau khi đăng nhập.

**Comment by daivietpda** [comment]
Ôi tôi cũng mới báo cáo cái này ở đây https://github.com/nukeviet/nukeviet/issues/1545
Mà chỉ là trên chrome mobile mới bị

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/392dcf017f8d7e4970733af9aef0d4a9e42445d2
Cái này mình chỉ có ý cập nhật hàm thôi :D.
Còn sáng nay test kỹ phần này mới thấy lỗi như bạn nói.
