### ISSUE TITLE
[4.0.23] Chrome Mobile Không nhập được khung login 

### ISSUE THREAD

**Issue by daivietpda** [nukeviet/nukeviet#1545]
Chào admin !
Tôi thử test nukeviet 4.0.23 trên trình duyệt chrome trên điện thoại android khi click vào chỗ đăng nhập thì nó hiện ra popup form nhập nick và mật khẩu nhưng khi nhấn vào ô textbox để nhập thì cửa sổ popup thì lại bị trở lại về ban đầu , tức là jquery có vấn đề với trình duyệt chorme trên android , tôi thử trình duyệt android mặc định thì không bị .
Đã thử trên một số trang nukeviet 4 đều bị 
Mong admin kiểm tra và fix lỗi

**Comment by vuthao** [comment]
Giao diện bạn nhắc tới là giao diện mobile hay giao diện tuỳ biến nhỉ, để chúng tôi có thể kiểm tra nhanh.

**Comment by hongoctrien** [comment]
Giao diện mobile đó anh. Và test trực tiếp trên mobile mới thấy.

**Comment by hongoctrien** [comment]
Mình đang xử lý vấn đề này

**Comment by anhtunguyen** [comment]
https://github.com/nukeviet/nukeviet/commit/c1da527f0e6a8ae320d79560dc8f58334e1fc0e5

**Comment by vuthao** [comment]
vẫn còn giao diện mobile nữa anh.

**Comment by anhtunguyen** [comment]
Anh sua roi ma.

Timur Nguyen

Phone/Viber/WhatsApp: +84933777637
Vào 09-11-2015 14:41, "Vu Thao" <notifications@github.com> đã viết:

**Comment by vuthao** [comment]
Vâng anh em kiểm tra thấy OK rồi.
