### ISSUE TITLE
Không đăng nhập, đăng ký được trên giao diện mobile

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1546]
![selection_234](https://cloud.githubusercontent.com/assets/6407361/10211016/b0a29366-6818-11e5-8f98-30bb71071a87.png)

Chuyển sang thẻ **Đăng ký**, không chọn được câu hỏi bảo mật, click nút “Đăng ký” không có tác dụng.

**Comment by vuthao** [comment]
Giao diện mobile anh tú đang làm lại giao diện mới, giao diện này có thể sẽ bỏ đi.

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/e22c0786e6b6019a815c7cd34ef0432ce127bbac
