### ISSUE TITLE
Lỗi đăng ký trên PC

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1547]
> Phiên bản NukeViet	4.0.23Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.6.8
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.6.24

Đăng ký xong không thấy thông báo gì, cũng không chuyển trang.

![selection_235](https://cloud.githubusercontent.com/assets/6407361/10211104/c2fc6f72-6819-11e5-9009-423662d7c309.png)

**Comment by vuthao** [comment]
Hiện tại mình kiểm tra không thấy bị, @hongoctrien kiểm tra lại trên bản mới nhất xem sao nhé.
