### ISSUE TITLE
PC: Cập nhật lại giao diện khôi phục mật khẩu

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1549]
Nó nằm lọt ở giữa, nhìn không bắt mắt lắm. Tương tự giao diện đăng nhập, đăng ký,...

![selection_237](https://cloud.githubusercontent.com/assets/6407361/10211182/aaa2d44c-681a-11e5-9916-71fbe129fe11.png)

**Comment by vuthao** [comment]
Cái này là ý đồ của người thiết kế muốn thế, chứ cho rộng ra cũng không ổn.
Thiết lập các trang này dùng giao diện 3 côt chắc sẽ ổn hơn chút nhỉ @hongoctrien

**Comment by anhyeuviolet** [comment]
Cái khu vực này kiểu như nhét cái block vào giữa hay sao ấy. Hình như bên contact cũng hiển thị kiểu vậy.
