### ISSUE TITLE
Cập nhật thông báo lỗi mật khẩu khi đăng ký

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1550]
Lỗi ở đây là mật khẩu không đúng quy tắc. Trong khi cứ thông báo như hình.
Tương tự cho **Câu hỏi bảo mật**

![selection_238](https://cloud.githubusercontent.com/assets/6407361/10211221/0f492234-681b-11e5-9ae6-918cf8ab61aa.png)

**Comment by vuthao** [comment]
Hiện tại mình kiểm tra không thấy bị, @hongoctrien kiểm tra lại trên bản mới nhất xem sao nhé.
