### ISSUE TITLE
Có nên có tùy chọn đăng ký xong - đăng nhập luôn?

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1551]
Trường hợp chức năng yêu cầu người dùng phải đăng nhập => chuyên đến form đăng nhập => người dùng chưa có tài khoản => click vào đăng ký => đăng ký xong lại quay về trang đăng nhập => rất nhiều bước.

Vậy có nên tùy chọn đăng ký xong, tự động đăng nhập luôn không?

**Comment by hoaquynhtim99** [comment]
Mình sẽ làm chức năng này.

**Comment by hongoctrien** [comment]
(y)

**Comment by hoaquynhtim99** [comment]
Đã thêm chức năng này https://github.com/hoaquynhtim99/nukeviet/commit/850a6734f952cb4872ee6d66ac626aa331fd44c9
