### ISSUE TITLE
Lỗi khi thêm block ngoài site 

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1553]
sau khi thêm block và submit thì của sổ báo thành công nhưng trang gốc bị chuyển hướng đến link dạng
/admin/index.php?language=vi&nv=themes&op=block_content&selectthemes=template100&blockredirect=o-hoRwPFBkaU3OGgQJS0iDNhVQOJIvIl2R3Ua6zqmKU,

**Comment by dangdinhtu2014** [comment]
Trong admin thì không bị

**Comment by vuthao** [comment]
Gửi cho mình tài khoản demo qua email thao a còng vinades chấm vn để kiểm tra nhé. chứ mình thử chán cái này không thấy có.

**Comment by dangdinhtu2014** [comment]
Để em tìm nguyên nhân luôn. có thông tin gì em báo lại sau

**Comment by vuthao** [comment]
Bac nào hay bị cái này, cập nhật lại phiên bản NukeViet mới nhất  trên nhánh develop xem sao nhé.
Nếu vẫn còn quay lại màn hình dùm em, chứ em đã bỏ cả tiếng ra test trên các môi trường khác nhau vẫn không thấy có.

**Comment by hongoctrien** [comment]
Cái này nó khùng khùng sao ý :D
Vô tình em có gặp, giờ cố tình thì lại không thấy nữa =))

**Comment by vuthao** [comment]
MÌnh đóng thông báo lỗi này lại, nếu bản phát hành tới còn lỗi sẽ tính tiếp.

**Comment by dangdinhtu2014** [comment]
Lỗi này em đã phát hiện ra. Nguyên nhân là do những tên miền có đuôi không thuộc hệ thống đuôi tên miền quốc tế sẽ bị lỗi ví dụ http://abcefg.dt khi qua hàm nv_is_url sẽ trẻ về giá trị false nên bị sai đường dẫn khi submit block vì hàm nv_redirect_decrypt sẽ trả về giá trị rỗng

**Comment by vuthao** [comment]
Để mình sẽ fix nó.
