### ISSUE TITLE
Lỗi module shops bản 4.0.17 ở nuke 4.0.23

### ISSUE THREAD

**Issue by daoduytung** [nukeviet/nukeviet#1554]
Module shops: Lỗi chức năng đặt hàng, yêu thích, so sánh, sắp xếp hiển thị ngoài site lẫn trong admin, chức năng đánh giá không xóa được trong admin và không hiển thị được ngoài sản phẩm

**Comment by vuthao** [comment]
Với Module shop bạn vui lòng đăng tại: https://github.com/nukeviet/module-shops/issues
