### ISSUE TITLE
Đề xuất module user có thêm cấu hình bật tắt câu hỏi bí mật

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1555]
Khi đăng ký thành viên mới. nhiều website có thể tối giản các thao tác đăng ký để tiện dùng, vì vậy nên có cấu hình bật tắt 2 trường này khi đăng ký

![untitled](https://cloud.githubusercontent.com/assets/6817130/10264745/9208dffe-6a3f-11e5-9556-6cc6215bc4a5.png)

**Comment by vuthao** [comment]
@dangdinhtu2014 làm tính năng này rồi mình sẽ trộn nhé. 
Hoặc để đến phiên bản 5 mình sẽ làm. bởi đây không là công việc ưu tiên.

**Comment by hoaquynhtim99** [comment]
Hiện NukeViet 4.3.00 trở lên đã chuyển phần này sang quản lý ở trường dữ liệu và đã có thể bật tắt
