### ISSUE TITLE
Đề xuất thêm cấu hình bật tắt captcha khi đăng ký thành viên

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1556]

**Comment by vuthao** [comment]
Tính năng này đã có:

bạn vào qua link: http://my_domain/admin/index.php?language=vi&nv=settings&op=security

**Comment by dangdinhtu2014** [comment]
chức năng này hình như là dùng chung cho hệ thống phải không anh. Nếu như thế thì khá bất tiện. Nhiều khu vực muốn hiện thì sao ạ

**Comment by vuthao** [comment]
chức năng cấu hình này dùng chung cho cả hệ thống nếu bạn nào muốn khác
thì  cần viết riêng
Vào 07-10-2015 10:27, "Đặng Đình Tứ" <notifications@github.com> đã viết:

**Comment by thehung** [comment]
Cái này đánh dấu để xem xét trong phiên bản sau.

**Comment by vuthao** [comment]
@dangdinhtu2014  hiện tại chức năng này mới đang thiết lập cho các khu vực lập trình theo nó.

Còn tuỳ theo từng module mà việc lập trình sẽ do người lập trình quyết định.

Thí dụ module contact: Luôn có captcha
