### ISSUE TITLE
Phần In của News bị thêm trang trắng

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1558]
Khi bấm in một bài biết có nửa trang giấy, nhưng nukeviet tự động thêm một trang trắng vào thành 2 trang.

**Comment by truongemcom** [comment]
Phiên bản hiện tại bấm in thì bị chạy ra Index

**Comment by hoaquynhtim99** [comment]
Đã sửa lỗi chuyển về index https://github.com/hoaquynhtim99/nukeviet/commit/3ca60dcd93547672c2db8a575342047a32288908, còn lỗi thêm 1 trang vào mình không thấy, bạn cho xem cái ảnh thử thế nào

**Comment by vuthao** [comment]
@hoaquynhtim99 Khi xem trên web thì không thấy thêm 1 trang.
Nhưng lúc in lại có thêm 1 trang ở cối, em cài thêm máy in pdf để in thử ra sẽ thấy.

**Comment by phongaz** [comment]
![capture](https://cloud.githubusercontent.com/assets/6806295/10409453/f252ef66-6f4a-11e5-85e9-e760f6d984d5.PNG)

**Comment by hoaquynhtim99** [comment]
Đã sửa: https://github.com/hoaquynhtim99/nukeviet/commit/204e06f8c0a2b31d6d6e68a14beed735f37ae457

**Comment by truongemcom** [comment]
Vẫn chưa được hoaquynhtim99 nhé!

**Comment by vuthao** [comment]
Mình thấy cái đó ổn rồi nhé, bạn cài lại bản mới, xoá cache nhé.

**Comment by truongemcom** [comment]
Chỉ ổn được cái: Bấm in thì không chuyển về Index thôi, còn bị lỗi thêm trang trắng vẫn không sửa được.
Thêm nữa khi in nó tự chèn thêm phần (url) trong dấu ngoặc, nó bị dư.

**Comment by hoaquynhtim99** [comment]
Không biết bạn test ở đâu, demo online bên trên của bạn là code cũ chưa cập nhật mới.

**Comment by truongemcom** [comment]
Mình tải bản develop về và test thôi
