### ISSUE TITLE
Cập nhật thông báo Cấu hình file robots.txt

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1559]
Trình bày không đẹp
![selection_243](https://cloud.githubusercontent.com/assets/6407361/10313557/6fc7960a-6c7a-11e5-9d8c-27002d3c413b.png)

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/fb40db5a371563afc78f5932611659bbc500f621
