### ISSUE TITLE
Lỗi thiết lập module ảo

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1561]
Module chính chưa thiết lập
**Thêm module ảo** từ module chính => thiết lập module ảo
Xong quay lại **Thiết lập module mới** cho module chính thì không thấy module chính đâu (mà phải xóa module ảo vừa thiết lập đi rồi mới thấy module chính)

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/4c28ddf1cce59b7de1096018b9b1fe9c875e70b8
