### ISSUE TITLE
Lỗi bài viết chưa có dữ liệu

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1562]
Khi phần nội dung chi tiết chỉ upload ảnh sau đó bấm đăng, quay trở lại quản trị bấm sửa -> Lưu thì hiện ra thông báo: Lỗi bài viết chưa có nội dung, và không thể nào lưu được.

**Comment by vuthao** [comment]
Mục đích của chúng tôi, yêu cầu bài viết cần có chữ.
Nếu là ảnh cũng cần có mô tả.

**Comment by vuthao** [comment]
Hiện tại mình đã sửa lại:
- Cần nhập text
- hoăc ảnh cần Có alt

Update: https://github.com/vuthao/nukeviet/commit/bb73be42234696a41b9ecd61f2ac0578ad666975
