### ISSUE TITLE
Cập nhật hàm nv_site_mods

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1564]
https://github.com/nukeviet/nukeviet/blob/develop/includes/functions.php#L1650

Có đối số là $module_name nhưng nội dung hàm không sử dụng.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/4a0a3704d6aca80dc0eaa1b731b4ea3af070b9bb
