### ISSUE TITLE
Cần điều chỉnh lại module menu 

### ISSUE THREAD

**Issue by volong1012** [nukeviet/nukeviet#1566]
Hiện nay module menu trong phần lựa chon "Liên kết đến module" nếu là menu cấp chỉ có 1 2 và 3 ở dạng ít mục thì lựa chọn không có vấn đề gì, tuy nhiên nếu từ cấp 3 trở lên và nhiều mục thì lựa chọn rất mệt và rất dễ bị nhầm lẫn khi lựa chọn, vì phải kéo và xem nó thuộc về thành phần nào nhất là với tin tức.

Do đó để dễ phân biệt dễ dàng hơn em đề nghị thêm gạch phía trước các thành phần (chuyên mục con khi lựa chọn) và thành phần mẹ (chuyên mục ngoài cùng nên bold lên cho dễ nhìn)

Ngoài ra còn 1 phương án khác (ý kiến của riêng e)  không biết có làm được không nhưng nếu dược thì sẽ trực quan hơn rất nhiều đó là tạo box lựa chọn cho thành phần hiển thị
![untitled-1012](https://cloud.githubusercontent.com/assets/6147555/10357632/89f08714-6dae-11e5-936e-64364b184f8a.jpg)

Ví dụ khi lựa chọn 1 module nào đó trong phần liên kết đến module thì sẽ hiển thị như ảnh : bật ra 1 cửa sổ box có liệt kê toàn bộ thành phần (chuyên mục) trong đó người sử dụng muốn hiển thị thành phần nào chỉ cần tích vào ô (màu xanh) và hệ thống sẽ import chuẩn theo dạng phân cấp vốn có của nó... ngoài ra cái này sẽ tiện lợi ở vấn đề là nhanh và chính xác vì lựa chọn trực tiếp vậy người sử dụng sẽ dễ điều khiển hiển thị theo ý muốn của mình cũng như loại bỏ hoặc thêm vào các chuyên mục cần thiết mà không phải thiết lập từ tổng rồi xóa dần từng cái 1 cho đến khi ưng ý

**Comment by vuthao** [comment]
Hiện tại cái menu dang dùng select nên ý tưởng của sơn sẽ không thực hiện được.
Cái này sẽ để bản NukeViet 5 vây thôi.

Hiện tại đã bổ sung tìm kiếm trong select, và có thể nạp lại menu của một module nào đó.

**Comment by truongemcom** [comment]
Cũng muốn chia menu ra dạng bảng hoặc cột, nhưng chưa edit được. Mình thiệt là tệ quá đi hic hic

**Comment by vuthao** [comment]
Phần này, có thể  thêm  cấu hình 

1. cách quản lý menu (1: Như hiện tại, 2 hiển thi hết ...). 
2. Các chọn các thành phần trong menu như  @volong1012  đã nêu ở trên

**Comment by anhtunguyen** [comment]
Đã điều chỉnh ở NukeViet 4.6 như hình
![ảnh](https://user-images.githubusercontent.com/5074710/208303614-bc9a691d-58cb-4f30-9786-d2503d93d5cc.png)
