### ISSUE TITLE
Khai báo “Cho phép” truy cập robots.txt 

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1571]
http://nukeviet4.vn/admin/index.php?language=vi&nv=seotools&op=robots
Ở đây chỉ có chặn, và không hiển thị. 
Trường hợp muốn cho phép Allow thì chưa thêm đuợc.
**Ví dụ:**
Disallow: /modules/
Allow: /modules/news/js/user.js

**Comment by vuthao** [comment]
update: https://github.com/vuthao/nukeviet/commit/fe3f61767aba0a13a98aa4e9bd8cc273553bfc6d
