### ISSUE TITLE
[Module statictics] Chưa khai báo một số hằng hệ điều hành, trình duyệt

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1585]
https://github.com/nukeviet/nukeviet/blob/develop/modules/statistics/theme.php#L616
```
$key = defined( $const ) ? constant( $const ) : $lang_global['unknown'];
```
Một số hằng chưa khai báo tương ứng với các trình duyệt mới, nên bảng thống kê xuất hiện nhiều trừong “Không xác định”
![selection_244](https://cloud.githubusercontent.com/assets/6407361/10443801/16ef3db2-7189-11e5-9107-4f0148bf9b18.png)

**Comment by vuthao** [comment]
Cái này là do em nâng cấp  từ phiên bản cũ lên không nâng cấp hết nên nó mới thế.
Cài mới site chắc chắn sẽ không bị thế.

**Comment by hongoctrien** [comment]
Không anh. Cái này em đã test lại trên NukeViet

Em ví dụ với loại trình duyệt là netscape, khi cái này có dữ liệu thì ở thống kê báo là “Không xác định”, tương tự cho một số loại khác.

**Comment by vuthao** [comment]
netscape giờ này làm ghì còn để mà test, phải dùng trình duyệt để chạy, thì nó mới ra thống kê.
Nếu đưa dưa liệu vào CSDL mà không thông qua chương trình chắc chắn sẽ sai.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/a2e9a0e0ac3fcc1bf51e9726e7913c11f7b6f4c4
