### ISSUE TITLE
Thêm trang danh sách các thông báo

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1587]
Hiện tại các thông báo (notification) chỉ đang hiển thị ở block nhỏ phía trên (ACP).
Cái này cần thêm một trang (func thuộc module siteinfo) hiển thị danh sách đầy đủ.
Tại đây có thể quản lý, tìm kiếm,... thông báo theo module.

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/2d08fefb992a63b4d5b14a254cf5aacaa450e6ac and https://github.com/hoaquynhtim99/nukeviet/commit/c75cdf3d8186b015cb5227a307afac0d7b7e38b9
