### ISSUE TITLE
Trạng thái bản tin thành viên gửi đến

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1589]
Tại danh sách bài viết (ACP), bài viết thành viên gửi đến (chờ duyệt) có trạng thái là “Ngưng hiệu lực” - không hợp lý.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/aacc2a4031b35f05a51c5f05898ec04d29c3d9bc
