### ISSUE TITLE
Có nên cho thêm thuộc tính width 100% vào trong chi tiết cho ảnh ??

### ISSUE THREAD

**Issue by volong1012** [nukeviet/nukeviet#1591]
E đề nghị thêm trong phần editor của ảnh có thêm thuộc tính width 100% để ảnh có thể giãn ra cho phù hợp với khung, hiện nay người sử dụng ảnh to rất nhiều cho bài viết của mình với 100% chiều dãn (width)... mà trong editor của mình hiện giờ sử dụng px nếu muốn căn ảnh full sẽ phải đo cột bao nhiêu px rất mệt, rồi lại mỗi lần ấn phải chỉnh chỉnh ... mất time trong khi cái kia chỉ cần quy định cái là được

**Comment by truongemcom** [comment]
Hồi Nuke 2 có chức năng bấm vào ảnh sẽ hiển thị lên kích thước thật của ảnh rất hay. Nhưng ở các bản sau chức năng này đã bị bỏ đi, tiếc thật.

To: Volong1012 nếu thêm chức năng width 100% trong editor sẽ làm cho hình ảnh bị choáng hết khung văn bản, rất khó chịu, Nuke có chức năng resize ảnh bạn cứ đăng kích thước lớn ra ngoài tin tức sẽ tự căn lại phù hợp với trang web.

**Comment by vuthao** [comment]
Bản hiện tại vẫn có nút, Kích thước gốc
![untitled](https://cloud.githubusercontent.com/assets/2491500/10459681/dc351bc0-71fa-11e5-9e1a-609b15110e0a.png)
Muốn có công cụ quản lý ảnh giống bản 3, bạn tự cấu hình và tải về quản lý ảnh bạn cài lại http://ckeditor.com/addon/image (Hiện tại NukeViet 4 cài ckeditor.com/addon/image2)

**Comment by volong1012** [comment]
Quên mất e chưa note là trong module about ạ ! Trong module thì khi hiển thị kích thước gốc sẽ được co lại trùng với khung nhưng trong module about thì không :D e đã kiểm tra rồi, không biết có ai bị như vậy không.. nhưng của e nếu để kích thước gốc thì tràn ra luôn

**Comment by truongemcom** [comment]
Trước đây nó là đoạn code này:


        <div style="width:{DETAIL.image.width}px;margin:10px auto;">
            <img alt="{DETAIL.image.alt}" src="{DETAIL.image.src}" width="{DETAIL.image.width}" height="{DETAIL.image.height}" />
            <p style="text-align: center;">
                <em>{DETAIL.image.note}</em>
            </p>
        </div>
        

Sau này thì đã bỏ đi, tiếc ơi là tiếc!

**Comment by hoaquynhtim99** [comment]
@volong1012 Việc ảnh tràn hiện mình đã xử lý thêm một chút theo commit này: https://github.com/hoaquynhtim99/nukeviet/commit/b732042c6fba279a522a5588636259d465db0d5f
