### ISSUE TITLE
Lỗi mảng khi sử dụng block_newscenter của module ở module ảo

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1593]
Dòng 112 của block module.block_newscenter.php không sinh ra được mảng dù câu lệnh sql đã lấy được giá trị 
$list = nv_db_cache( $db->sql(), 'id', $module_name );
dẫn đến không if được điều kiện $list

Lỗi trên module ảo

**Comment by vuthao** [comment]
Anh kiểm tra thấy block đó vẫn hoạt động bình thường.
Chú ý ở đây block có chữ: Không hiển thị trong các chuyên mục

**Comment by ThinhNguyenVB** [comment]
Vâng
sao trên module ảo của em nó lại không có dữ liệu ra
