### ISSUE TITLE
Đề xuất thêm icon awesome vào module menu

### ISSUE THREAD

**Issue by RightPro** [nukeviet/nukeviet#1594]
Hiện trong số các block menu đã có menu bootstrap cho phép hiển thị icon nhưng là icon upload từ local lên. Nên có thêm icon awesome song song với icon upload, như vậy có thể vừa nhẹ host hơn nữa tiết kiệm thời gian thiết kế hay tìm icon cho menu.

**Comment by hoaquynhtim99** [comment]
Bạn có thể sử dụng trường "Tên lớp CSS" để nhập vào trên class, và sửa một chút ở menu của bạn muốn là đc

**Comment by RightPro** [comment]
Ý mình là 1 trường bên cạnh upload icon chứ không phải là ngồi code thêm :) Không phải người dùng cuối nào cũng có thể "sửa một chút" như Dev để làm việc này.

**Comment by hoaquynhtim99** [comment]
Cái này không code gì cả bạn, trường lớp css đẻ ra là để làm việc đó rồi

Vào 01:00 Ngày 15 tháng 10 năm 2015, RightPro <notifications@github.com> đã
viết:

> Ý mình là 1 trường bên cạnh upload icon chứ không phải là ngồi code thêm
> :) Không phải người dùng cuối nào cũng có thể "sửa một chút" như Dev để làm
> việc này.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nukeviet/nukeviet/issues/1594#issuecomment-148136888>.
>



-- 
PHAN TAN DUNG
Staff of Department of Network Administration and Communication
The University of Danang - Campus in Kontum
Mobile: (+84) 1677 865 866
Website: www.kontum.udn.vn
