### ISSUE TITLE
Cần sửa lại editor trong module new

### ISSUE THREAD

**Issue by volong1012** [nukeviet/nukeviet#1599]
Hiện này editor có rất nhiều thành phần không hoạt động chính xác so với tính năng của nó, vì vậy thành ra khi viết trong admin 1 kiểu ra ngoài site lại 1 kiểu khác rất khó chịu, để sửa 1 bài viết tạm chấp nhận được thì rất lâu.... mong lỗi này sẽ được fix lại trong thời gian sớm nhất

**Comment by vuthao** [comment]
@volong1012 Viết cụ thể nhé, viết như thế này không ai ngồi tìm ra đâu.

**Comment by hoaquynhtim99** [comment]
Cái này liên quan đến css của site, của module, và của các thành phần gọi riêng bên ngoài site, không thể trong admin gọi nó vào hết được.
