### ISSUE TITLE
Lỗi các thẻ tiêu đề

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1602]
http://demo.mynukeviet.net/Tin-tuc/Cong-bo-du-an-NukeViet-3-0-sau-1-thang-ra-mat-VINADES-JSC-2.html

h1 luôn là tiêu đề site trong khi h3 là tiêu đề bài viết

**Comment by hoaquynhtim99** [comment]
Đã sửa https://github.com/hoaquynhtim99/nukeviet/commit/a37d43d1f01b0df1d8fece442a548e0535ddf3ce
