### ISSUE TITLE
Module news: Lỗi đến đường dẫn thư mục file khi sửa

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1603]
1 bài viết có hình ảnh minh họa nằm ở thư mục news/07/2015/
Tại thời điểm hiện tại, khi chọn lại hình ảnh thì vị trí thư mục truy cập vào ko phải 07/2015 mà là 10/2015 (tháng hiện tại)

Chưa kiểm tra với các module khác tương tự news

**Comment by vuthao** [comment]
Việc lưu trữ sẽ căn cứ theo thời gian upload, chứ không căn cứ theo thời gian của bài viết.
Mục đích để tiện việc backup phân mảnh.
Nếu muốn khác cần viết một cơ chế khác.

Nếu là lỗi cần chỉ ra rõ

**Comment by hongoctrien** [comment]
Lỗi ở đây là khi sửa bài viết, chọn lại ảnh minh họa thì không vào khu vực file ảnh minh họa cũ, mà nó cứ nhảy sang thư mục mới nhất. 

Em đang xử lý

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/8cc43beebd9e1dc5a2a22c41652fcaf57e24ed0f
