### ISSUE TITLE
Footer của admin trong Admin xem giao diện mobile.

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1606]
![12107109_881903168561042_204149378681783345_n](https://cloud.githubusercontent.com/assets/2491500/10507754/02c4cf62-734d-11e5-9847-116ecf8a5f3c.jpg)

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/b221557ad3ce003924bde0fccffe5e46a846ccd4
