### ISSUE TITLE
Lỗi không tồn tại jquery.timeago.fr.js khi sử sử dụng nút Browse server để chọn ảnh trong module news

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1608]
Khi đăng bài mà chọn đăng ảnh đại diện trong module news thì sẽ có cảnh bão đường dẫn  .../assets/js/jquery/timeago/locales/jquery.timeago.fr.js không tồn tại dẫn đến không hiện popup

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/7971140dd3a16fd69568c4836ab959f99afeb408
@hongoctrien language của javascript đưa nó bào /assets/js/language để còn đóng gói nhé.

**Comment by hongoctrien** [comment]
ok a.
