### ISSUE TITLE
Lỗi khi chỉnh sửa Quy định đăng ký

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1609]
Vào Admin Control Panel/ Quy định đăng ký => Toàn bộ khung soạn thảo bị trống.
URL: /admin/index.php?language=vi&nv=users&op=siteterms

Sửa và "lưu thay đổi" xong, khi quay trở lại thì nội dung này vẫn bi trống (mặc dù ra ngoài site xem "Quy định đăng ký thành viên" thì đã thấy nội dung mới).

**Comment by hoaquynhtim99** [comment]
Bản mới nhất hiện không thấy lỗi này, anh cài trên ngôn ngữ nào
