### ISSUE TITLE
[Module News] Đăng bài ngoài site (content) thiếu phần nhóm tin (groups)

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1611]
Khi đăng bài ngoài trang chủ qua chức năng content, thì phần 
Nhóm tin liên quan
Lại hiển thị các dòng sự kiện.
Còn phần chọn các nhóm tin ( tin tiêu điểm, tin mới nhất ) thì không xuất hiện.
![123](https://cloud.githubusercontent.com/assets/6290970/10533379/7dc610c2-73f2-11e5-9781-fc7a02dae0fa.PNG)

**Comment by vuthao** [comment]
Việc đăng bài ở ngoài site chỉ có những tính năng tối thiều. Nếu cần làm thêm tính năng đó bạn có thể phát triển thêm, sau đó đóng góp lại mã nguồn.
Hiện tại chúng tôi chưa có kế hoạch phát triển thêm tính năng đó.

**Comment by thanlongweb** [comment]
Vậy coi như phần post bài từ bên ngoài ko tác dụng gì :(

**Comment by vuthao** [comment]
@thanlongweb không có tính chất xây dựng ghì cả.

**Comment by anhyeuviolet** [comment]
Vậy sửa lại tiêu đều cho phần đó là được. Tiêu đề là nhóm tin liên quan, nhưng thực ra chức năng lại là theo dòng sự kiện. 
Ngoài ra thì nếu số lượng CTV lớn, khi đó cần có cách phân quyền nhanh hơn cho người quản lý. Cơ chế check để phân quyền hiện nay rất là cực. 
https://github.com/nukeviet/nukeviet/issues/1617

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/7ccc90437ed1d1cefeaee97de94a6abacc85c2fa
