### ISSUE TITLE
lỗi khi đăng bài ở module ảo của news bằng tiếng pháp bị lỗi cảnh báo không xác định và lỗi gọi về news.js

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1613]
Khi login hoàn toàn bằng tiếng pháp sẽ xảy ra lỗi như hình sau
Vào module news vào phần đăng bài sẽ hiển thị ra lỗi "Uncaught SyntaxError: Unexpected identifier"
Bấm vào nút chọn ảnh thì sẽ lỗi "Uncaught ReferenceError: CFG is not defined" và gọi về news.js và nút ảnh ko hiện popup
![untitled-1](https://cloud.githubusercontent.com/assets/13896524/10538967/7eacfab2-7426-11e5-9ec3-2e3c11b63898.jpg)

**Comment by hoaquynhtim99** [comment]
Đã sửa https://github.com/hoaquynhtim99/nukeviet/commit/00bc86a151529ea1c26e6112bdb2b23775538dd1
