### ISSUE TITLE
Cần thay đổi cho trường hợp không nhập dường dẫn logo

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1618]
Trong trường hợp không muốn gọi đến đường dẫn logo thì cần phải để trống khi xuất ra ngoài site
Hiện tại khi để trống nó sẽ lấy mặc định "../assets/images/logo.png" từ core, cần tách ra và chuyển về themes để có thể tùy biến trong mọi trường hợp

**Comment by vuthao** [comment]
Logo site ngoài dùng ở trên banner sẽ được dùng rất nhiều chỗ  khác, nên nếu không được định nghĩa sẽ gây ra lỗi.
Nếu theme của em cần xác định không nhập, thì không hiển thị, em có thể kiểm tra là nếu đường dẫn logo = ../assets/images/logo.png thì không hiển thị.
