### ISSUE TITLE
Công nghệ nén trang mới mà nukeviet nên áp dụng để phát triển

### ISSUE THREAD

**Issue by nethoabinh** [nukeviet/nukeviet#1619]
Theo gời gian thì vẫn thích dùng nuke và vẫn thích đóng góp cho em này
- Cách nén trang view source Ctrl + u trang này ra chỉ hiện 1 dòng duy nhất quá đỉnh
 demo: http://fdisoft.com/

Các bác view source nó ra mà xem chỉ có 1 dòng load trang chưa tới 1s, nuke nên áp dụng
thanks anh em đã xem
- Hôm nào đi đá bóng vậy ạ :))

**Comment by hoaquynhtim99** [comment]
NukeViet đã từng sử dụng rất nhiều biện pháp nén khác nhau, từ các extension của php cho đến code tự phát triển tuy nhiên hiệu quả mang lại không nổi bật và cách hiện tại là lựa chọn tốt nhất.
Nén theo demo bạn đưa cũng là một cách, tuy nhiên tốc độ không phải do nén trang mà do tốc độ máy chủ cũng như các mod mà máy chủ đó sử dụng. Nén trang theo cách một dòng như thế không quyết định tốc độ load trang nhanh được.

**Comment by anhyeuviolet** [comment]
Tốc độ tải trang nằm ở cả đường truyền và xử lý máy chủ, máy trạm. Cái này thì giảm tải về vđề đường truyền, máy trạm khi nhận dữ liệu, nhưng tất nhiên sinh ra gánh nặng cho máy chủ. Nên tối ưu từ khi lập trình thì vẫn tốt hơn là dồn hết cho server/core xử lý.

**Comment by hoaquynhtim99** [comment]
Xin phép được đóng cái này lại nhé

**Comment by nethoabinh** [comment]
Ông hoaqunhtim trả lời ko thông minh. Xin ý kiến của an thảo ạ

**Comment by vuthao** [comment]
@nethoabinh 
NukeViet đã áp dụng gzip để nét mã html trong quá trình truyền từ máy chủ tới trình duyệt. Việt xem mã html trên trình duyệt là sa khi đã được trình duyệt giải nén.

Việt dồn tất cả vào một dòng, không tiết kiệm thêm được bao nhiêu, nhưng CPU sẽ phải xử lý nhiều hơn. Ngoài ra dồn tất cả vào một dòng sẽ dẫn đến việc chèn các đoạn code vào trang web sẽ bị lỗi.

Cân nhắc giữa cái lợi và cái hại, nên tôi đã bỏ việc dồn mà html này. Nếu bạn nào vấn thích làm thì viết 1 plugin làm việc này.

**Comment by nethoabinh** [comment]
dạ vầng em cảm ơn anh nhiều
