### ISSUE TITLE
Seo của nukeviet nên xem lại không biết lỗi ở đâu ạ

### ISSUE THREAD

**Issue by nethoabinh** [nukeviet/nukeviet#1620]
em làm trang này cũng hơn 1 năm rồi 
http://kingsmen.vn
mà tìm từ khóa domain "kings men" không ra tên miền
seo đặc biệt kém, và hiện tại em cũng đang sài 1 code nuke nữa
và em cũng nhận định seo cũng kém, em nghĩ nên chú trọng vào seo 1 ít hic

**Comment by hoaquynhtim99** [comment]
Chung chung thế này đội code không thể nào sửa cho bạn được. Hiện tại NukeViet 4 mới nhân đang áp dụng tối đa các khía cạnh để SEO tốt nhất có thể, vấn đề còn lại là ở người quản trị trang tin sử dụng nó như thế nào cho hiệu quả

**Comment by nethoabinh** [comment]
Cái ông này đóng topic hấp tấp. Seo mà ko lên ma nó dùng nukeviet à. Chính vì wordpress seo nhanh ng ta mới dùng
Lần sau topic của tôi ông đừng vào góp ý nhé. Trình ông còn kém lắm chỉ code thôi.
Anh thảo vào cho ý kiến với ạ

**Comment by vuthao** [comment]
@nethoabinh Không ai là giỏi tòan diện cả, Ngay cả tôi không phải cái ghì cùng biết, chả qua là làm NukeViet nhiều hơn các bạn chút thôi, và nhất là bây giờ đã già rồi, sức sáng tạo cũng có hạn.


Có nhưng cái liên quan đến SEO onpage khi làm bản 4 đã làm rất kỹ, nhưng theo thời gian các bạn khác đã sửa và làm hỏng nó, nên giờ đến lúc này có ghì bạn chỉ ra cụ thể để chúng ta cùng sửa. (Có rất nhiều người kêu với tôi, nó lỗi, tôi yêu cầu chỉ ra lỗi ở chỗ nào, làm sao tôi gạp phải lỗi đó và không chỉ được)


Các bạn là ngưòi dùng , nếu cái ghì không đúng cần chỉ rõ thì chũng tôi mới biết mà chỉnh sửa. Chứ chỉ một từ lỗi không, chả ai là ngưòi muốn tìm nó tại sao đâu.
chúng ta dùng NukeViet là cùng nhau làm để sản phẩm tốt hơn.

**Comment by hoaquynhtim99** [comment]
Xin lỗi bạn đã đọc quy định báo lỗi chưa? https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md
Lần sau nếu bạn báo lỗi thế tôi sẽ còn đóng nữa.

**Comment by nethoabinh** [comment]
Hiện tại em đang chạy 1 site nữa là http://hoanghuyinternational.com
cho công ty em, lại 1 lần nữa tình trạng mà nó không thể search ra trang chủ
nếu mà em biết chính xác nó lỗi ở đâu thì em gõ lên làm gì
Nhưng em đội ngũ nukeviet cần xem xét kĩ lại thật cẩn thận + Hiện tại em biết là mình có trúng thầu về phát triển nukeviet cho các tỉnh thành cơ quan nhà nước
- Nhưng mà  hiện tại em thấy là các thành viên chú trọng đến chức năng của nukeviet cũng là đúng nhưng mà em nghĩ nên nghiêm túc xem xét lại code của Nukeviet có ảnh hưởng hay là bị gì không mà các từ khóa nó cứ tụt một cách đột ngột ( ở đây từ khóa đang top1 mà search không ra trang chủ + trang 2, trang 3 không ra............"
Và đây là lần thứ 2 em làm trang web bằng nukeviet...........tình trạng search không ra trang chủ với từ khóa gắn liền với domain em nghĩ là "chắc chắn là có lỗi mà bot google bị cấm, mà đặc biệt em nghĩ là chức năng cấu hình file bot trong quản trị em nghĩ nên bỏ đi" có khi nó là chức năng bị lỗi mà làm cho google không search được và thi thoảng gặp lỗi
------cái này nghiêm túc. cứ phát triển chức năng mà gặp lỗi chặn bot google như này thì người ta dùng wordpress mãi thôi.............................

**Comment by nethoabinh** [comment]
@hoaquynhtim99 cứ đọc lại các góp ý của mình cho nukeviet đi , bạn biết là mình đóng góp chân thật như nào đối với SEO và chức năng của nukeviet

**Comment by hoaquynhtim99** [comment]
À, ờ, thôi không đủ trình, không dám manh động nữa :))

**Comment by nethoabinh** [comment]
Thanks
