### ISSUE TITLE
Thêm tùy chỉnh tiêu đề site trong new bị lỗi nếu cuối cùng tiêu đề kết thúc bằng html

### ISSUE THREAD

**Issue by thucvinh** [nukeviet/nukeviet#1621]
Trên bản mới nhất Nuke đã thêm chứ năng tùy chỉnh tiêu đề title cho chuyên mục. Rât tốt cho seo. Tuy nhiên hiện tại đang bị lỗi.Khi mình thêm dữ liệu ở trường này. Thì tiêu đề site hiển thị chữ Page ( không hiển thị đúng) Và trên breadcrumbs cũng hiển thị Page. breadcrumbs nên hiển thị theo tên chuyên mục

**Comment by hoaquynhtim99** [comment]
Mình kiểm tra không thấy lỗi này

**Comment by thucvinh** [comment]
![image](https://cloud.githubusercontent.com/assets/12856625/10686334/40e49a8e-798d-11e5-9092-ab99ef54ed76.png)


Sau khi thêm:

![image](https://cloud.githubusercontent.com/assets/12856625/10686311/00a849d4-798d-11e5-8f2c-5420599fb204.png)

**Comment by hoaquynhtim99** [comment]
Chuyên mục của bạn là module news trong khi khu vực bạn truy cập ngoài site là module page hai cái này khác nhau đâu có liên quan

**Comment by thucvinh** [comment]
Ủa sao lại không liên quan ạ. Trong admin em cấu hình chuyên mục như sau:

Tiêu đề : Học Html
Tùy chỉnh tiêu đề site là: Giáo trình học html cơ bản và nâng cao toàn tập.

Thì ngoài site khi mở chuyên mụ đó,đáng ra nó phải hiển thị như trên.đằng này nó hiển thị:

Tiêu đề: Page
url: Page

Thế em mới báo lỗi chứ

**Comment by hoaquynhtim99** [comment]
Bạn chụp giúp mình phần cấu hình => Cấu hình site của bạn mình xem, nếu có thể bạn quay giúp mình cái video quá trình lỗi thử thế nào, quá trình bạn đăng nhập admin, vào cấu hình các chuyên mục và ra ngoài site xem thông tin dẫn tới lỗi đó.
Cảm ơn bạn vì phức tạp như vậy nhưng mà tại vì lỗi này chưa thấy xảy ra

**Comment by thucvinh** [comment]
Video: mới làm lại vẫn bị.

https://www.youtube.com/watch?v=NibhHyOUObc

**Comment by vuthao** [comment]
Bạn vào module menu, xóa các menu đi rồi tạo lại menu nhé.

**Comment by thucvinh** [comment]
menu là site mod mà anh

**Comment by hoaquynhtim99** [comment]
Xem video mình thấy bạn nhập có đoạn học html cho cái liên kết hoc-html, khi add thêm cái đuôi hoc-html.html thì bị xóa mất chữ html. Mình sẽ kiểm tra lại cái này, cảm ơn bạn.

**Comment by vuthao** [comment]
@hoaquynhtim99 xử lý cái này nhé, nếu trục trặc ghì gọi lại mình.

**Comment by hoaquynhtim99** [comment]
Cảm ơn @thucvinh , lỗi đã được sửa https://github.com/hoaquynhtim99/nukeviet/commit/b8367f93e5aa03ed38bbc4bb4c6ea4b941d676d4
