### ISSUE TITLE
Undefined variable: module_upload] [FILE: /modules/news/language/data_vi.php] [LINE: 65]

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1623]
Nuke https://github.com/nukeviet/nukeviet/commit/eb95aca7a53279889c8f5fedd6e39eb267748b04

[Fri, 23 Oct 2015 17:23:42 +0700] [127.0.0.1] [Notice(8): Undefined variable: module_upload] [FILE: /modules/news/language/data_vi.php] [LINE: 65]
[Fri, 23 Oct 2015 17:23:42 +0700] [127.0.0.1] [Notice(8): Undefined variable: module_upload] [FILE: /modules/news/language/data_vi.php] [LINE: 68]
[Fri, 23 Oct 2015 17:23:42 +0700] [127.0.0.1] [Notice(8): Undefined variable: module_upload] [FILE: /modules/news/language/data_vi.php] [LINE: 71]
[Fri, 23 Oct 2015 17:23:42 +0700] [127.0.0.1] [Notice(8): Undefined variable: module_upload] [FILE: /modules/news/language/data_vi.php] [LINE: 74]
[Fri, 23 Oct 2015 17:23:42 +0700] [127.0.0.1] [Notice(8): Undefined variable: module_upload] [FILE: /modules/news/language/data_vi.php] [LINE: 77]
[Fri, 23 Oct 2015 17:23:42 +0700] [127.0.0.1] [Notice(8): Undefined variable: module_upload] [FILE: /modules/news/language/data_vi.php] [LINE: 80]
[Fri, 23 Oct 2015 17:23:42 +0700] [127.0.0.1] [Notice(8): Undefined variable: module_upload] [FILE: /modules/news/language/data_vi.php] [LINE: 83]
[Fri, 23 Oct 2015 17:23:42 +0700] [127.0.0.1] [Notice(8): Undefined variable: module_upload] [FILE: /modules/news/language/data_vi.php] [LINE: 86]
[Fri, 23 Oct 2015 17:23:42 +0700] [127.0.0.1] [Notice(8): Undefined variable: module_upload] [FILE: /modules/news/language/data_vi.php] [LINE: 89]
[Fri, 23 Oct 2015 17:23:42 +0700] [127.0.0.1] [Notice(8): Undefined variable: module_upload] [FILE: /modules/news/language/data_vi.php] [LINE: 92]
[Fri, 23 Oct 2015 17:23:42 +0700] [127.0.0.1] [Notice(8): Undefined variable: module_upload] [FILE: /modules/news/language/data_vi.php] [LINE: 95]

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/cf9185925c10ed0ff0f09af5c6715513721fcac8
