### ISSUE TITLE
Lỗi không chọn được các block

### ISSUE THREAD

**Issue by phuongnamit** [nukeviet/nukeviet#1624]
Phiên bản đang sử dụng	4.0.23
Apache Version	Apache/2
Apache API Version	 20051115
Giao diện default của nukeviet 4.0.23
Em hiện đang sử dụng hosting cài DirectAdmin 1.4.3
Lỗi không thể tạo block mới. Mong các bác giúp đỡ
![capture](https://cloud.githubusercontent.com/assets/15308954/10715320/1cd747ea-7b45-11e5-953e-1f8756277d60.PNG)

**Comment by vuthao** [comment]
Muốn giúp bạn cũng không biết phải làm thế nào, bạn ghi lại video việc gây lỗi nhé.

**Comment by phuongnamit** [comment]
Em restore lại bản backup cũ rồi ạ. Em còn bị lỗi 500 nữa ạ trong khi vẫn vào được admin.  Đã tắt hết các block vẫn bị lỗi.
Em restore lại là ok rồi, khi nào có lỗi em sẽ report ạ.
Cảm ơn bác
