### ISSUE TITLE
[Hệ thống] Cấu hình cho phép chạy NukeViet từ 1 folder

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1626]
Một số CMS khác đã làm được, mình có áp dụng thử cách của WP, thu hoạch được đôi chút nhưng website chưa chạy hoàn chỉnh được.
Mô tả như sau : 

NV dev - XAMPP 1.8.3 - Windows 10 - Firefox 41
Quá trình thực hiện : 
Chuyển toàn bộ source code của NV vào 1 thư mục mang tên sub.
Cấu trúc gốc : 
D:\xampp\localhost\htdocs\dev\

Sau khi chuyển vào sub
D:\xampp\localhost\htdocs\dev\sub\

Bước 2 : Copy file index.php trong root code của NukeViet ra thư mục bên ngoài.
Khi đó ta có 
D:\xampp\localhost\htdocs\dev\index.php
D:\xampp\localhost\htdocs\dev\sub\ - chứa phần còn lại của code.

Bước 3 : chỉnh sửa file index.php
sửa dòng định nghĩa NV_ROOTDIR như sau : 
```
define( 'NV_ROOTDIR', pathinfo( str_replace( DIRECTORY_SEPARATOR, '/', __file__ ), PATHINFO_DIRNAME ).'/sub/' );
```
Trong đó, thêm phần /sub/ là thư mục con chứa code.

Bước 4 : Sửa mainfile.php
Sửa dòng định nghĩa NV_BASE_SITEURL.

```
define( 'NV_BASE_SITEURL', $nv_Request->base_siteurl . '/sub/' );

```
Trong đó, thêm phần /sub/ là thư mục con chứa code.

Khi đó, trang chủ sẽ hiển thị bình thường.

Nhưng vấn đề là các trang của từng Modulesẽ bị mất giao diện. Ví dụ 
```
http://localhost/dev/sub/index.php?language=vi&nv=voting
```
và trang chi tiết của module thì sẽ không thể truy cập được.
Liệu NV có phương án nào để người dùng có thể tuỳ chọn hay chưa ?

**Comment by vuthao** [comment]
Chúng tôi không thiết kế cho việc này.
Nếu làm sẽ phát sinh rất nhiều thứ, code sẽ mất cả tuần đó bạn.
Sao không làm đơn giản là cho nó hết vào một thư mục.

**Comment by anhyeuviolet** [comment]
Anh đánh lebel wontfix vội vàng quá !

cái mô tả bên trên là cách em thử để " Chạy nukeviet từ một subfolder". Ví dụ như domain là abced.com, với thư mục là nukeviet, thì khi đó truy cập vào domain, nó vẫn truy xuất được code trong sub. 
cái này có ý nghĩa khi anh chạy 1 host với nhiều website. Mỗi web có 1 thư mục thì sẽ dễ quản lý hơn.
![sub](https://cloud.githubusercontent.com/assets/6290970/10810475/fe06c984-7e33-11e5-9213-e2925bd5fd0d.PNG)

Anh thử xem trong hình. Các domain khác thì "quy hoạch" gọn gàng. Còn riêng cái root domain thì code nằm theo phong cách riêng.
Còn nếu cho hết vào 1 thư mục thì khi đó chạy phải là
abcde.com/sub/index.php
Nó mới chạy được. Đây mới là cái đang nói.
Code nằm trong sub, nhưng chạy thì từ root domain vẫn được, kể cả link rewrite cũng được.

**Comment by vuthao** [comment]
Với cách này của bạn có thể tạo 1 file php redirect nó vào trong thư mục là xong mà.

Tôi đánh wontfix, để các bạn khác trong đội code không sửa vào cái này, bởi còn nhiều cái cần phải làm hơn cái này rất nhiều.
NukeViet có mấy khi từ chối code các bạn đóng góp đâu. Nếu bạn sửa để tương thích, tôi sẽ kiểm tra và trộn code ngay.

Chính vì lý do này, nên tôi chưa close ý kiến của bạn.

**Comment by anhyeuviolet** [comment]
Cảm ơn anh ! 
Vậy nếu có đủ sức thì em làm thử và gửi code lên :)

Còn nếu redirect thì nhiều khả năng là anh chưa hiểu chính xác cách thức hoạt động mà em mô tả rồi. Nó vẫn sẽ mang subfolder trong URL.
Anh có thể đối chứng với một số CMS khác để tiện phát triển sau này.

**Comment by phongaz** [comment]
Cái này hay đấy. khi mình thuê hosting ở godaddy thì tạo addon domain hoặc sub domain thì các sub /addon nằm trong folder con như thế. Nếu gom mỗi site thành một folder thì dễ quản lý hơn.

**Comment by hoaquynhtim99** [comment]
Vấn đề này cũng khá hay, và tôi xin đóng góp chút ý kiến nhỏ còn quyết định sao ở cấp trên tôi không đủ trình để quyết.

Tôi đã sửa thế này và chưa thấy lỗi gì. Đây chỉ là cách làm ăn liền còn nếu muốn sửa vào code của NukeViet thì cần thêm một hằng nữa vào file constants.php

Trong ví dụ của tôi. Code toàn bộ tôi đặt trong thư mục `vinades/onlineprocedures.vinades.my`, thư mục này nằm trong htdocs của tôi `locahost` là tên miền trỏ vào htdocs. 

Tại htdocs tôi tạo file .htaccess có nội dung như sau

```
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule ^$ vinades/onlineprocedures.vinades.my [L]
    RewriteRule (.*) vinades/onlineprocedures.vinades.my/$1 [L]
</IfModule>
```

Trong bộ code của NukeViet đặt ở vinades/onlineprocedures.vinades.my tồi tìm kiếm và thay thế tất cả các dòng 

```php
$base_siteurl = pathinfo( $_SERVER['PHP_SELF'], PATHINFO_DIRNAME );
```

Thành 

```php
$base_siteurl = '';
```

Tôi cũng gợi ý luôn là có 3 file có dòng trên: robots.php, mainfile.php, request.class.php.
Sau khi làm như trên website của tôi có thể chạy bằng tên miền http://localhost/ và code của website thì nằm trong thư mục `vinades/onlineprocedures.vinades.my`. Tôi test và chưa thấy lỗi, dĩ nhiên tôi đang demo cho thư mục gốc và chưa phải sub domain có thêm thư mục /sub/.

Tôi cũng không khuyến khích việc sửa code của NukeViet để chạy theo ý này, việc này không đại trà và nếu muốn thì webmaster có thể sửa vào code để chạy.

**Comment by thehung** [comment]
Nếu lý do sửa code là phục vụ mục đích quy hoạch thư mục trên host thì bạn nên sử dụng các chức năng mà hosting cung cấp. Nó có đủ chức năng này như anh @phongaz đã nói. NukeViet sẽ không thêm chức năng này nếu chỉ để giải quyết mục đích mà hệ thống đã có sẵn.

**Comment by anhyeuviolet** [comment]
Cảm ơn các anh @vuthao  và @thehung !
Cảm ơn bạn @hoaquynhtim99 . Tôi sẽ thử áp dụng phương cách này cho bộ code của mình. Nếu trong quá trình phát triển có ý tưởng nào tốt hơn, tôi sẽ phản hồi.

Về phần issue này : 

Subdirectory cho Joomla : 
https://docs.joomla.org/Moving_the_site_among_directories/sub-directories

Subdirectory cho Wordpress : 
https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory

Nếu có chút thời gian rảnh, mời anh @thehung xem một số bài liên quan đến chức năng này của issue. Mong anh không hiểu nhầm chức năng mà issue đề nghị, cũng như ý kiến bên trên của @phongaz . Có vẻ như anh đã hiểu nhầm ý của bạn ấy. 
Ngoài ra, nếu theo nhận định của anh bên trên thì các bạn không dùng WHM sẽ rất vất vả khi "quy hoạch".
Cảm ơn mọi người !

**Comment by vuthao** [comment]
@anhyeuviolet @hoaquynhtim99 
Kiểm tra lại với các ảnh mới upload lên nhé:
- ảnh minh hoạ
- ảnh trong trình soạn thảo lúc upload.
