### ISSUE TITLE
[Page] vẫn hiển thị tin khác trong khi trong quản trị đã ngưng hoạt động bài viết

### ISSUE THREAD

**Issue by PhamQuocTien132** [nukeviet/nukeviet#1628]
Ví dụ: http://ictketnoi.com/about/Huong-dan-tham-gia.html

Nếu ngưng hoạt động bài viết: Giới thiệu về chương trình ICT Kết Nối 2015 
trong trang quản trị thì ở ngoài site vẫn hiển thị link.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/460582d338217b5a36c7aacb2f5bfb9acc70eb8b
