### ISSUE TITLE
Lỗi khi thêm bộ phần contact ở tiếng pháp

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1631]
khi thêm bộ phận contact ở ngôn ngữ tiếng pháp thì sẽ có thông báo Lỗi: Tiêu đề hoặc liên kết tính đã tồn tại

**Comment by vuthao** [comment]
@ThinhNguyenVB cài lại module đó xem sao.

**Comment by ThinhNguyenVB** [comment]
@vuthao  ok anh, bị sự cố từ hom ổ cứng hết đâm ra gây ra lỗi mất file

**Comment by vuthao** [comment]
Đã bổ sung thêm 20GB ổ cứng cho VPS đó.
