### ISSUE TITLE
Phân quyền xoá sửa bài cho Quản trị

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1632]
Hiện tại các quản trị có thể xoá, sửa bài của nhau kể cả bài của Quản trị tối cao.
Cần sửa lại là: Bài của quản trị nào thì chỉ người quản trị đó mới có quyền sửa, xoá 
Chỉ Admin tối cao mới có quyền xoá sửa bài của quản trị cấp dưới mà thôi.

**Comment by vuthao** [comment]
Có nên cứng nhắc như thế này không nhỉ các bạn.
Ví dụ giao cho một nhân viên với mới quản lý nội dung, thế người này mỗi lần nửa bài mới lài gọi quản trị tối cao sửa hay sao.
Hiện tại NukeViet 4 đã có phân quyền cho quản lý module có quyền làm ghì rồi nhé.
@truongemcom bạn hãy đưa ra giải pháp toàn diên hơn nhé

**Comment by anhyeuviolet** [comment]
Ở Xenforo, thậm chí mình edit được bài của cả Admin, dù mình là Mod.
Cái này nằm cách bạn phân quyền thôi. Phân ra kiểu như SMOD và MOD ấy, nhóm nào thì cho sửa xoá bài, nhóm nào thì chỉ sửa. Nếu bạn cho người ta làm biên tập viên thì họ sửa bài chéo cho nhau cũng bình thường lắm !

**Comment by truongemcom** [comment]
Cái này mình học của WP. Thấy chức năng này quản lý quyền riêng tư của các admin rất hay (tránh việc admin này xoá nhầm bài của admin kia và mỗi admin có trách nhiệm của riêng mình).

Nếu, BQT code nếu thấy không hợp lý thì không đưa vào. Mình chỉ góp ý mà thôi, quyền quyết định thuộc về các bạn.

**Comment by anhyeuviolet** [comment]
Về phân quyền trong WP, mình thấy theo link https://codex.wordpress.org/Roles_and_Capabilities#Roles

Thì cấp Editor trở lên là sửa/xoá được bài của user khác mà. Đó là mặc định. Còn trong trường hợp ghi đè phân quyền bằng Plugin nào đó thì nó lại khác.

**Comment by truongemcom** [comment]
WP phân quyền Editor (chỉnh sửa) là sửa, xoá là đúng rồi.
WP phân quyền Author kia mới đáng ghi nhận. Các Author không thể xoá, sửa bài của nhau.

**Comment by anhyeuviolet** [comment]
Cái này bạn đang đề cập đến sửa bài từ bên trong ACP hay từ phần đăng tin ngoài site nhỉ ?

**Comment by truongemcom** [comment]
Đã được đánh dấu là wontfix rồi, thì kô nên bàn nữa. Closed tại đây đi.

**Comment by truongemcom** [comment]
Một lần nữa góp ý lại tính năng này:
- Quản trị tối cao: Là người có quyền cao nhất: Sửa, xoá, giới hạn quyền của quản trị cấp dưới
- Quản trị viên: Chỉ có quyền hạn với những gì được quản trị tối cao phân phát, được quyền sửa, xoá bài của thành viên, bài của mình và không được sửa, xoá những gì của Quản trị tối cao.
Với mô hình phân quyền này: 
- Sẽ hạn chế tối đa sự phá phách của một ai đó từng là quản trị viên.
- Tập trung quyền hạn vào một người chính và bản thân mỗi người phụ có trách nhiệm với mình hơn.
- Hạn chế tối đa việc các quản trị viên sửa, xoá nhầm bài của nhau.

**Comment by vuthao** [comment]
Trong NukeViet đã có sẵn tính năng phân quyền theo chủ đề rồi @truongemcom, hãy sử dụng nó trước khi cần chỉnh sửa code nhé.
Hiện tại đến lúc phát hành, sẽ không chỉnh sửa module này nữa. Nếu cần thiết sẽ để sang bản 4.1. issues này sẽ được mở lại để tiếp tục theo dõi. (Hiện tại tôi đang thử nghiệm chạy thử khi site có khoảng 1 triệu bài viết để kiểm tra hiệu năng, hiện tại đã có những vấn đề cần sửa code khi dữ liệu lớn)

**Comment by truongemcom** [comment]
Khi dữ liệu lớn, load trang hơi chậm thôi

**Comment by truongemcom** [comment]
Vấn đề cốt lõi ở đây là các Quản trị có thể sửa, xoá bài của nhau.

- Nên sửa lại là: Chỉ có Quản trị tối cao mới có quyền sửa, xoá bài của mọi quản trị và thành viên
- Các Quản trị viên chỉ có thể sửa, xoá bài của mình và thành viên và module, chủ đề được quản trị tối cao cấp phát. 
- Các quản trị viên không thể sửa xoá bài của nhau và bài của Quản trị tối cao.

* Còn phần quyền theo chủ đề không giải quyết được vấn đề trên.

**Comment by anhyeuviolet** [comment]
Hiện giờ NV có 3 cấp độ : God Admin, Admin và Moderator.
Để tránh tình trạng như anh nói thì phân quyền dạng Moderator là được.
Còn Admin thì hẳn nhiên chỉ thua God Admin ở một số chức năng như cài thêm module, theme và các tính năng phân quyền. Nếu tận dụng tốt thì đâu có gì phát sinh.

**Comment by truongemcom** [comment]
@anhyeuviolet bạn đọc kỹ lại đi, vấn đề là các Admin, Moderator có thể sửa, xoá bài của nhau. Chỉ nên dành điều này cho Quản trị tối cao là người quản lý cao nhất mới có quyền đó. Còn các Admin thì chỉ có thể sửa xoá bài của thành viên và bài của chính mình kô có quyền sửa xoá bài của Admin khác.

**Comment by anhyeuviolet** [comment]
Cái này em đã đọc rất kỹ từ khi issue được mở rồi.
Phân tích và ví dụ thì em cũng nêu ra rồi. Hiện tại em thấy NV phân quyền ổn và chưa có vấn đề gì.

**Comment by truongemcom** [comment]
@anhyeuviolet có lẽ site của bạn có ít người quản trị viên, site lớn nhiều quản trị viên thì sẽ thấy vấn đề ngay.

**Comment by hoaquynhtim99** [comment]
Hiện tại module news đã có phân quyền admin đến từng chủ đề, trong mỗi chủ đề có định cụ thể quyền thêm, sửa, xóa.
Ngoài ra trên bản 4.3 đã có bổ sung chức năng lock, chiếm quyền sửa bài viết khi có người đang sửa sẽ giải quyết được việc nhiều người cùng sửa bài.
Duy phần xóa bài viết vẫn còn đang để tự do xóa nếu có người sửa, phần này sẽ được bổ sung ở bản 4.3.01, và được ghi nhận tại #2418 
Xin được đóng Issue này tại đây
