### ISSUE TITLE
Cần bổ sung css khi gặp thẻ IMG của module news

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1638]
Hiện tại nếu để ở dạng có left-body-right mặc định mà đăng hình cỡ lớn trong bài viết nó sẽ bị che mất bên phải, vì vậy cần bổ sung css của thẻ img luôn để width: 100% để nó tự hiển thị đầy đủ không bị che

**Comment by vuthao** [comment]
@ThinhNguyenVB kiểm tra lại dùm anh, trên bản mới nhất vấn đề này đã được xử lý.

**Comment by ThinhNguyenVB** [comment]
@vuthao vẫn còn anh ơi em để kích thước 800 là dính, vì khi đính kèm thằng editor nó ko đính kèm thẻ img-thumbnail vào trong
![untitled-1](https://cloud.githubusercontent.com/assets/13896524/11025244/611fc38c-86cb-11e5-8532-086ac5c063ef.jpg)

**Comment by hoaquynhtim99** [comment]
Không biết quá trình thao tác của bạn thế nào chứ phần ảnh nội dung của news và page đã được xử lý bằng javascript lúc load trang và lúc độ rộng trang thay đổi (onresize), mình check không thấy cái này

**Comment by vuthao** [comment]
@ThinhNguyenVB kiểm tra lại dùm anh, trên bản mới nhất vấn đề này đã được xử lý. Nếu còn đưa link demo để kiểm tra.
