### ISSUE TITLE
Module banners: Sắp xếp quảng cáo

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1649]
Mặc định khi thêm quảng cáo, quảng cáo thêm sau nó cứ nhảy lên đầu, cứ phải vào chọn sắp xếp lại.
Cái này mình nghĩ nên thêm sau thì cứ cho nó hiển thị dưới cùng.

**Comment by macsoftnet** [comment]
Thế cái kiểu banner thì sao bác?
Trình tự lần lượt hay random ấy. Random ko được?

**Comment by vuthao** [comment]
update: https://github.com/vuthao/nukeviet/commit/a79c362f612114fe51f3a87612abd980b0225ca9
