### ISSUE TITLE
Module voting không có kết quả trong admin

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1650]
Module voting không có kết quả bình chọn trong admin

**Comment by truongemcom** [comment]
Nên sửa lại cái block voting là cho nó hiện lên trên thay vì hiện thụt xuống dưới như vậy, nếu người dùng không bấm Close thì không thể chuyển sang mục khác được.

**Comment by vuthao** [comment]
đọc cái này không hiểu ghì luôn @truongemcom

**Comment by truongemcom** [comment]
à, phiên bản mới đã hiện lên trên rồi, do @truonngemcom dùng phiên bản cũ.
