### ISSUE TITLE
4.0.24 cài bị lỗi ở bước 6

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1651]
OS: CentOS 6.6 (Final)
Plesk version: 12.0.18 Update #70 , last updated at Oct 29, 2015 06:12 AM
webserver
php 5.4.41
mysql 5.5.43-29.el6.art

https://drive.google.com/file/d/0BySLP6070LzdYjgxYTJrVy1fQzhBNV9DOTZRaDhiRE9TX0U4/view?usp=sharing

**Comment by vuthao** [comment]
Tôi đã kiểm tra trên hosting anh gửi.

Server đó có cấu hình vấn đề nên không dùng được collation utf8mb4, thử bằng phpmyadmin lưu các ký tự đặc biệt vào cũng không được, ví dụ: 𝌆   (💩) 

Để khắc phục, cần cấu hình vào file install\config.php trước khi cài đặt.
tìm đến đoạn: 
```
$db_config['collation'] = '';//utf8_general_ci
```
sửa lại thành 
```
$db_config['collation'] = 'utf8_general_ci';//utf8_general_ci,
```

**Comment by phongaz** [comment]
Nukeviet hướng đến người không cần biết code mà vẫn cài đặt và quản trị được site.

Do đó, Cái này nên thiết kế lại. Khi cài đặt phải kiểm tra xem collation có tương thích không rồi, tự chuyển đổi về utf8_general_ci, chứ phải vào file /install/config.php thì có phải ai cũng biết dâu?

Người dùng chỉ cần click chuột qua 6 bước là cài xong site thì tốt nhất.

**Comment by vuthao** [comment]
Vấn đề này mình đã thử nhưng mỗi server 1 kiểu, Nên mình đã lựa chọn để tốt nhất cho các website sau này.
Nếu quá trình cài đặt có lỗi sẽ cần cấu hình lại. Việc cài đặt chỉ một lần, còn việc dùng sẽ lâu dài.
