### ISSUE TITLE
Các lỗi về ngôn ngữ ENG

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1652]
Các lỗi về Anh ngữ được mô tả khá rõ trong các link forum do 1 thành viên tên schavlev - người nước ngoài đăng lên.
Mình chuyển lên đây để nhóm code dễ theo dõi.

http://forum.nukeviet.vn/viewtopic.php?f=183&t=36799
http://forum.nukeviet.vn/viewtopic.php?f=183&t=36808
http://forum.nukeviet.vn/viewtopic.php?f=183&t=36819
http://forum.nukeviet.vn/viewtopic.php?f=183&t=36798

Hầu hết là về lỗi chính tả, cú pháp và cách hành văn.

**Comment by vuthao** [comment]
Bác nào tiếng anh kha khá kiểm tra lại dùm cái nhỉ.
