### ISSUE TITLE
Soạn thảo không lưu được kí tự đặc biệt như mặt cười,các biểu tượng cảm xúc

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1653]
Khi đến chỗ nào có kí tự đặc biệt mặt cười văn bản sẽ dừng lại tại đó
[Phương-Phan_học-tiếng-Đức-2015-11-13.docx](https://github.com/nukeviet/nukeviet/files/36614/Ph.ng-Phan_h.c-ti.ng-D.c-2015-11-13.docx)

**Comment by vuthao** [comment]
Phiên bản mới nhất đã hỗ trợ CSDL utf8mb4, và việc này còn tùy thuộc vào máy chủ có hỗ trợ hay không.

Demo:
![anh minh hoa](https://cloud.githubusercontent.com/assets/2491500/12135381/82f79ef6-b46d-11e5-8a07-9c230ded9c5b.png)
