### ISSUE TITLE
Lỗi tính năng hiển thị trên các thiết bị của block

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1654]
Nukeviet 569c6cde65b736f4e71127a94ae01fd49fdd3502
Tính năng hiển thị block trên các thiết bị của block bị lỗi. Tích vào bất cứ thiết bị nào ngoại trừ tất cả ra để không thấy block đó mất đi hay không hiển thị trên thiết bị đó
![image](https://cloud.githubusercontent.com/assets/9360175/11232217/ed0277f0-8de2-11e5-886f-a7e7f6aa154c.png)

**Comment by vuthao** [comment]
Mình kiểm tra lại phiên bản mới nhất không có lỗi như bạn thông báo.
Lỗi này có thể xẩy ra, do lúc bạn nâng cấp từ các phiên bản cũ lên không nâng cấp hết CSDL.
