### ISSUE TITLE
Bổ sung thêm trường hợp lấy ảnh từ thư mục themes

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#1655]
Hiện tại chỉ có lấy đường dẫn ảnh trong database và ảnh đại diện khi không có ảnh trong module mà thiếu đi trường hợp lấy ảnh gốc từ thư mục của themes đó. Hiện tại code đang để rỗng khi tìm được các ảnh

**Comment by vuthao** [comment]
@ThinhNguyenVB, vui lòng trình bày rõ ràng: cái gì,  ở đâu, khi nào nhé.

**Comment by ThinhNguyenVB** [comment]
trong block đều có đoạn này

**Comment by vuthao** [comment]
Cái này là quan điểm của mỗi một người khác nhau.
Quản trị không cấu hình thỉ làm ghì nhỉ.

Một ý khác. Có khi muốn cấu hình, không có ảnh thì không hiển thị ảnh minh họa.
