### ISSUE TITLE
Một số ý kiến về module banners

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#1656]
> 1. There is a problem created by the user to login. There is a conflict of choice complexity login and password. I think that a user (client) must be created in the Users section in customer groups, rather than the banners module, then the conflict will not be. And customers in the page Banner module, select users from user groups.
> 2. When entering the section "Statistic" active at a time and the button "client_info"
> 3. Error tab "Statistic" ../banners /stats/. Displayed a badge without statistics.
> 4. In the administration panel under Advertising is necessary to create a column clicks

Mình mới đọc qua chứ chưa test lại thử.
http://forum.nukeviet.vn/viewtopic.php?f=183&t=36867

**Comment by vuthao** [comment]
Hiện tại lỗi ngôn ngữ đã được cập nhật, Tuy nhiên các chức năng của module hiện tại chưa có kế hoạch thay đổi.

**Comment by hoaquynhtim99** [comment]
Hiện phần tài khoản đã gắn theo user thay vì tài khoản riêng, issue tạm đóng nếu cần vấn đề gì khác sẽ cần tạo issue mới
