### ISSUE TITLE
Không dùng được một số biến trong cronjobs

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1657]
https://github.com/nukeviet/nukeviet/blob/develop/includes/mainfile.php#L370
Cronjobs được gọi ở vị trí này nên khi viết cronjobs không dùng được các tài nguyên được khai báo bên dưới nó. Ví dụ như biến **$site_mods**,....

**Comment by dangdinhtu2014** [comment]
if( empty( $site_mods ) )
{
	include_once ( NV_ROOTDIR . "/includes/core/user_functions.php" );
	$site_mods = nv_site_mods();
}

**Comment by dangdinhtu2014** [comment]
cronjob được viết ở vị trí này nhằm mục đích giảm thiểu việc load các thư viện. cũng như chức năng không cần thiết để đảm bảo nó hoạt động trơn tru nhất

**Comment by vuthao** [comment]
Sau khi tham khảo ý kiến của @hoaquynhtim99  mình thấy dữ nguyên như hiện tại.
