### ISSUE TITLE
Module page: Thêm cấu hiển thị hình ảnh

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1658]
Chọn ảnh minh họa, trong trường hợp không muốn ảnh hiển thị trong bài viết thì không có cách nào.

**Comment by truongemcom** [comment]
Nên thêm resize hình cho block global about

**Comment by vuthao** [comment]
Cái page nếu không cẩn thận sẽ trở thành cái news thứ 2 nhỉ. 
@truongemcom, hiện tại tôi kiểm tra block global about không có hiển thị ảnh. Bạn mô tả rõ hơn nhé.

**Comment by truongemcom** [comment]
Thì up ảnh trong Ckeditor của block, nhưng ra ngoài nó kô resize như news.

**Comment by vuthao** [comment]
Mô tả cụ thể, hoặc có demo đi @truongemcom, giờ mình già rồi nên chậm hiểu lắm, thông cảm nhé.

**Comment by truongemcom** [comment]
Trong module About có block global html, khi thêm block này vào site, nếu trong nội dung có chèn hình ảnh thì hình ảnh đó không tự động resize.

**Comment by vuthao** [comment]
Cái này mình nghĩ cho người dùng chèn thêm thẻ html cho nó quen dần:
http://getbootstrap.com/css/#images

**Comment by hongoctrien** [comment]
Đang sửa...

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/538fcda20440574122036baeaa01738e246a7d87
