### ISSUE TITLE
Vấn đề với meta cho phép bot truy cập 

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1659]
Hiện tại tất cả các trang đang để:

```
<meta name="robots" content="index, archive, follow, noodp" />
<meta name="googlebot" content="index,archive,follow,noodp" />
<meta name="msnbot" content="all,index,follow" />
```

Với một số trang cần tài khoản đăng nhập, hoặc một số module cấu hình riêng thì không làm được việc này.

Tương tự như thế cần kiểm tra lại một số chỗ để rel="nofollow" cho các trang đăng nhập.

**Comment by hoaquynhtim99** [comment]
Đã xử lý
