### ISSUE TITLE
Lỗi cấu hình fpt

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1661]
Cấu hình fpt đúng, nhưng khi lưu vẫn báo thông số remote path không đúng.

https://github.com/nukeviet/nukeviet/blob/develop/admin/settings/ftp.php#L58
Danh sách thư mục ở đây vẫn chưa được cập nhật nên sinh ra lỗi này.

**Comment by thehung** [comment]
FTP chứ :D

**Comment by hongoctrien** [comment]
hì, lại nhầm :D

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/8f80ce183691c066b684ecf02fcce875605e31a6
