### ISSUE TITLE
[Module News]Sai Admin function khi xem danh sách topic

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1662]
Khi truy cập 
```
news/topic/
```
Ta sẽ có một danh sách các topic ( Chủ đề ).
Tuy vậy, nút sửa và xoá chủ đề lại sửa/xoá các bài viết con có trùng id với topic đó.
Nguyên nhân do dùng chung hàm 
```
nv_link_edit_page
```
https://github.com/nukeviet/nukeviet/blob/develop/modules/news/theme.php#L970

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/104c241fea40bdc1a12442f2078e70c080714f0d
