### ISSUE TITLE
Lỗi cảnh báo

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1663]
> Phiên bản NukeViet	4.0.23Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.5.26
Giao thức giữa máy chủ và PHP	Apache/2, cgi-fcgi
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.5.41

Đang ở đây **/admin/index.php?language=vi&nv=authors**

> Lỗi cảnh báo: preg_match(): Unknown modifier ']' in file /includes/class/browser.class.php on line 1418

**Comment by vuthao** [comment]
@hongoctrien kiểm tra lại dùm phiên bản mới đã hết lỗi này chưa nhé.

**Comment by hongoctrien** [comment]
ok đã hết
