### ISSUE TITLE
Lỗi upload hình lên server

### ISSUE THREAD

**Issue by lyhuutrong** [nukeviet/nukeviet#1665]
![image](https://cloud.githubusercontent.com/assets/15257128/11429404/ed64d922-94a9-11e5-8f30-28c0dadb7717.png)
cho mình hỏi lỗi này bị gì ạ ? khắc phục sao ạ ? vì mình chạy trên nukeviet develop nó để bản 4.0.24 Not Relase và Module shop develop ạ.
nhờ các bạn khắc phục dùm mình với.hichic.up hình lên mà chả thấy hình đâu hichic

**Comment by hongoctrien** [comment]
Những vấn đề thế này bạn post lên forum nhé.
Cách giải quyết: http://mynukeviet.net/su-dung-nukeviet/sua-loi-khong-hien-thi-anh-thumb-trong-quan-ly-tap-tin-nukeviet-81.html

**Comment by lyhuutrong** [comment]
À cái này mình có tìm hiểu và làm theo nhưng mình làm thì nó báo lỗi ko xác
định được đường dẫn hã gì đó bạn ơi. Nên mình lưu cấu hình ko được hichic.
Mong bạn giúp đỡ ạ

Vào Thứ Sáu, ngày 27 tháng 11 năm 2015, Hồ Ngọc Triển <
notifications@github.com> đã viết:

**Comment by hongoctrien** [comment]
Lỗi này được báo tại https://github.com/nukeviet/nukeviet/issues/1661
Tạm thời bạn chmod thủ công cho **/uploads/news** và các thư mục bên trong, sau đó bỏ qua bước cấu hình FTP và làm tiếp nhé.

**Comment by lyhuutrong** [comment]
Bạn làm ơn có thể chỉ mình chmod các file và folder được ko ạ? Vì mình
chmod upload 777 hết rồi mà vẫn bị thế vậy bạn?

Vào Thứ Sáu, ngày 27 tháng 11 năm 2015, Hồ Ngọc Triển <
notifications@github.com> đã viết:

**Comment by lyhuutrong** [comment]
bạn cho mình hỏi là chmod thủ công sao ạ ? bạn có thể chỉ mình với ko ạ ?
xin cảm ơn

Vào 17:31 Ngày 27 tháng 11 năm 2015, Trọng Lý Hữu <daigjabaclieu@gmail.com>
đã viết:

**Comment by vuthao** [comment]
Bạn cài mới 1 website trên hosting sẽ biết các thư mục cần chmod thủ công nhé.

**Comment by lyhuutrong** [comment]
Chào bạn. Mình có làm theo các mục cần chmod nhưng vẫn như vậy bạn ạ.

Vào Thứ Hai, ngày 30 tháng 11 năm 2015, Vu Thao <notifications@github.com>
đã viết:

**Comment by vuthao** [comment]
Thế thì bạn phải tìm hiểu thêm về các kiến thức về chmod.
Ngoài ra đẻ chúng tôi có thể đoán lỗi, bạn vui lòng đọc lại quy định thông báo lỗi:
Please review the guidelines for contributing to this repository., có link https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md

**Comment by lyhuutrong** [comment]
Bạn cho mình hỏi cái nhé.
Ví dụ như module mình bị lỗi. Mình muốn xóa module đó đi và xóa luôn dữ
liệu của module đó để upload module mới hơn thì làm sao ạ ?
Xin cảm ơn bạn nhiều lắm ạ

Vào 15:32 Ngày 30 tháng 11 năm 2015, Vu Thao <notifications@github.com> đã
viết:
