### ISSUE TITLE
Tạo tài khoản mới ko đc 

### ISSUE THREAD

**Issue by minhlaoleu** [nukeviet/nukeviet#1667]
Xin chào mọi người, mình đang xài bản dev 4.0.24, lúc tạo thêm tài khoản trong module user thì mình nhập email đúng nhưng validate cứ báo là sai, mình có chụp hình kèm theo. Cái này mình upload lên host rồi.
![1](https://cloud.githubusercontent.com/assets/2928316/11442203/f016f582-9545-11e5-9dbe-64fe1cef811c.jpg)
![2](https://cloud.githubusercontent.com/assets/2928316/11442204/f02015ea-9545-11e5-878b-d43a67405daa.jpg)

**Comment by vuthao** [comment]
Mình kiểm tra không thấy lỗi như bạn thông báo, vui lòng đọc lại:
https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md

**Comment by vuthao** [comment]
Không thấy ngưòi báo lỗi phản hồi, nên mình xen phép đóng câu hỏi.
