### ISSUE TITLE
Vấn đề cài đặt dữ liệu mẫu

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1671]
Trường hợp của shops (Các ngôn ngữ dùng chung bảng dữ liệu)
Ví dụ ngôn ngữ tiếng việt đã có dữ liệu, sau đó nguời dùng sang tiếng anh, cài thêm shops nhưng vô tình chọn "Chỉ cài lại module" thì dữ liệu của tiếng việt cũng bị xóa sạch luôn.
Nên thêm thông báo "cảnh báo" cho trường hợp này, hoặc ẩn luôn tùy chọn cài đặt đi.

**Comment by vuthao** [comment]
Cài lại module là mất là đúng rồi còn ghì nữa.

**Comment by hongoctrien** [comment]
Nếu như dữ liệu độc lập thì không nói làm gì, em nói trường hợp của shops ý anh. Đôi khi người ta không biết (chắc chắn là không ai lường trước dc với lần đầu thực hiện) bấm cài trắng thì dữ liệu ở tất cả ngôn ngữ cũng bị xóa luôn. Trong trường hợp này em nghĩ cần thông báo cho ng ta biết, hoặc không cho cài trắng trong trường hợp này.

**Comment by vuthao** [comment]
Em làm cái này thì đề xuất phương án xử lý nhé.
