### ISSUE TITLE
PHP HỖ TRỢ THƯ VIỆN MÃ HÓA MCRYPT

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1673]
https://github.com/nukeviet/nukeviet/commit/d955c5d9375c547c068c1950e63c4edc76928b25

Nếu phiên bản php là 5.4.16  thì phần PHP HỖ TRỢ THƯ VIỆN MÃ HÓA MCRYPT bị lỗi không tương thích, nhưng khi chuyển sang php là 5.6.15 thì không bị lỗi này khi cài đặt ở bước 4

**Comment by vuthao** [comment]
vấn đề này không phải do NukeViet gây ra bạn, Là do  server cấu hình chưa chuẩn nên việc chuyển đổi bị thiếu thư viện.
