### ISSUE TITLE
Góp ý cơ chế bỏ tên module

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1678]
hiện tại nukeviet đã cho phép bỏ tên module ở URL.

Tuy nhiên có vấn đề như sau: Trong bài viết thường chèn textlink như sau: domain.com/news/chuyen-mục/bai-viet-1.html

Tuy nhiên khi bỏ tên module thì link ở các bài viết domain.com/news/chuyen-mục/bai-viet-1.html bị lỗi 404. và phải sửa tất cả các bài viết chứa link về định dạng URL mới. Cái này rất tốn công.

Vậy có cách nào nhận dạng link có module name trước khi bỏ khỏi URL để trả về link không có module name theo cấu hình mới không nhỉ?

vì dụ khi gặp link domain.com/news/chuyen-mục/bai-viet-1.html thì tự chuyển về domain.com/chuyen-mục/bai-viet-1.html

**Comment by vuthao** [comment]
bạn có thể  sử dụng .htaccess. hoặc xuất dữ liệu ra file sql tìm kiếm và thay thế.

**Comment by phongaz** [comment]
Bạn @vuthao giúp mình đoạn .htaccess được không?

Từ lúc chuyển lên nukeviet 4 thì traffic bị giảm kinh khủng, thứ tự alexa cũng tụt 600k
Lúc trước mỗi giây có mấy chục lược truy cập nhưng bây giờ thì chỉ 1 hoặc 2 thôi.

Mình muốn chuyển từ domain/vi/news/chuyên-mục/tên bài viết/
sang domain/chuyên-mục/tên bài viết.html
