### ISSUE TITLE
Cấu hình site ko cho upload swf

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/nukeviet#1680]
Không upload được file flash trong cấu hình logo site

![upload-logo-flash](https://cloud.githubusercontent.com/assets/8604866/11646293/2bd1a0da-9d8f-11e5-8fbb-7370cef42347.jpg)

server: Cenos 6.5
apache: 2.4
mysql: 5.5
php: 5.6
Cpanel: Directadmin

**Comment by hoaquynhtim99** [comment]
Bạn vào cấu hình upload chọn lần lượt từ bình thường đến yếu xem đến cái nào thì không bị, cái kiểm tra định dạng file không hoàn toàn đúng 100%, nó còn tùy thuộc vào máy chủ, các thành phần enabled  hay disabled khác nữa.
