### ISSUE TITLE
Không sửa được block cũ và không tạo được block mới

### ISSUE THREAD

**Issue by vandien** [nukeviet/nukeviet#1681]
![loi nukeviet](https://cloud.githubusercontent.com/assets/16202653/11649199/0f0ee6ae-9daf-11e5-90c3-a933cdd04eb2.jpg)
Hình ảnh này hiển thị khi mình tạo mới bất kỳ một block rồi lưu lại. Còn nếu sửa block cũ rồi lưu lại thì sẽ bị báo lỗi kết nối máy chủ 500.

Mình gặp lỗi này từ khi update Nukeviet 4.0.22 lên 4.0.23 cho website http://tgktrans.com. Quá trình update mình sử dụng công cụ tại địa chỉ: http://mynukeviet.net/su-dung-nukeviet/huong-dan-nang-cap-nukeviet-4-0-22-len-4-0-23-116.html
Bây giờ website vẫn hoạt động bình thường nhưng khi thay đổi cấu hình chung, cấu hình site hay dọn dẹp hệ thống thì không truy cập được trang chủ nữa (trang admin vẫn vào được) và không thể thêm mới block hay sửa các block cũ.
Rất mong được hỗ trợ.
Trân trọng.

**Comment by anhyeuviolet** [comment]
Dòng báo lỗi đó thể hiện là DB chưa được nâng cấp hoàn tất, dẫn tới một số hàm, lệnh truy vấn vào DB không được, gây trắng trang.

**Comment by vandien** [comment]
Vậy bây giờ mình phải xử lý thế nào để hoàn thiện quá trình trên ạ.

**Comment by anhyeuviolet** [comment]
Cái này mình chịu ! Quá trình này, nếu là mình thì mình dò trong DB ra và sửa, xoá các trường dư hoặc thiếu mà thôi. Muốn làm hoàn thiện thì chờ người viết gói nâng cấp.

**Comment by vandien** [comment]
Vâng. Cảm ơn anh đã góp ý. Mình sẽ nghiên cứu xem sao.

**Comment by hongoctrien** [comment]
Trc mắt bạn cứ khôi phục lại code trước khi nâng cấp đi ạ.

**Comment by inngochuong** [comment]
code đó chủ thớt đã khắc phục được chưa. Em đang định làm lại cái web http://inngochuong.com và dùng code của NuKeviet xem sao.

**Comment by vandien** [comment]
Vẫn chưa khắc phục được bạn à, giờ không thể can thiệp được vào các khối block.
Giờ không biết phải làm thế nào cả. Chỉ còn cách là chờ đợi bản nâng cấp chính thức thôi, vì lúc nâng cấp mình không sao lưu,nên không khôi phục được,hic.

**Comment by vuthao** [comment]
Vấn đề này phát sinh do bạn nâng cấp module. các bản cài đặt sẽ không bị như thế. Bạn cần biết về CSDL để so sánh và sửa.
