### ISSUE TITLE
lỗi đăng kí thành viên email không hợp lệ

### ISSUE THREAD

**Issue by koxsmile** [nukeviet/nukeviet#1684]
lỗi đăng kí thành viên email không hợp lệ, khi bỏ hàm kiểm tra email thì đăng kí được nhưng khi phân quyền quản trị xong đăng nhập không được

**Comment by vuthao** [comment]
Báo lỗi không hợp lệ, bạn vui lòng xem dòng chữ: Please review the guidelines for contributing to this repository.
Bạn hãy đặt mình vào vị trí của người kiểm tra lỗi nhé.

**Comment by vuthao** [comment]
đã 18 ngày, không thấy tác giả phản hồi, mình xin phép đóng issues
