### ISSUE TITLE
Lỗi mất phần "giới thiệu ngắn gọn" khi ẩn hình đại diện

### ISSUE THREAD

**Issue by thanhvu7411** [nukeviet/nukeviet#1685]
Em xài nukeviet phiên bản 4.24 (develop). Khi đăng bài phát hiện 1 vấn đề:
khi chọn "không hiển thị" Ảnh đại diện thì cả phần giới thiệu ngắn gọn cũng bị mất! Không biết đây là lỗi của bản này hay em chưa chỉnh ạ?

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/309d330d253c7aab0ac6f6d10bb1b7b53890b229
(Nếu code không phải là bản mới nhất, bạn chỉ sửa  file themes/default/modules/news/detail.tpl
)
