### ISSUE TITLE
Lỗi Oauth Facebook

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#1686]
Hiện tại mình đăng nhập bằng facebook vướng phải lỗi
![16-12-2015 9-51-31 sa](https://cloud.githubusercontent.com/assets/2421714/11830793/d34e80e8-a3da-11e5-917a-15a855b3b992.png)

**Comment by vuthao** [comment]
Kiểm tra lại dùm phiên bản mới nhất xem nhé @hoaquynhtim99
