### ISSUE TITLE
Lỗi 500 khi chạy trên php7

### ISSUE THREAD

**Issue by nhancon111** [nukeviet/nukeviet#1687]
Xin chào 
Tôi đang thử nghiệm bản 4.0.23 trên php7.0 nó báo lỗi 500

**Comment by vuthao** [comment]
Bạn vui lòng đọc dòng chữ khi tạo issues: Please review the guidelines for contributing to this repository. trong đó có link: https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md

Không có nhưng thông tin đó chúng tôi muốn kiểm tra thì cũng không biết phải làm sao.

Hiện tại bản NukeViet 4 trên kho code https://github.com/nukeviet/nukeviet/archive/develop.zip đã chạy tốt với PHP 7. Demo: http://demo.nukeviet.vn/

**Comment by vuthao** [comment]
Đã 12 ngày  không có phản hồi. Mình xin phép đóng issues
