### ISSUE TITLE
Lỗi không hiển thị link và hình ảnh khi share facebook

### ISSUE THREAD

**Issue by vandien** [nukeviet/nukeviet#1689]
Mình gặp đúng trường hợp như bài này: https://github.com/nukeviet/nukeviet/issues/619

Và đã thay $meta_property['fb:app_id'] thành $meta_property['fbid'] nhưng không khắc phục được tình trạng trên. Mặc dù Facebook App ID đã nhập trong cấu hình chung.
Có điều lạ là tất cả các trang của http://vietnamcoffee.asia thì không được, nhưng trang http://vietnamcoffee.asia/vn thì lại được.
Không hiểu lý do gì ạ.

**Comment by Lovestar716** [comment]
Lỗi này không chỉ riêng nuke mà các CMS khác củng bị

**Comment by truongemcom** [comment]
Cái fb nó củ chuối, chứ G+ hiện tốt lắm

**Comment by hongoctrien** [comment]
Gần đây facebook nó thay đổi cái gì hay sao mình thấy rất nhiều site bỗng dưng gặp lỗi này, truớc đó vẫn hiển thj tốt.

**Comment by anhyeuviolet** [comment]
Xác nhận. :( Bữa còn chê bạn kia xấu trai nên ko hiện.
Giờ thì các site bị hàng loạt ko nhận OG.

**Comment by hoaquynhtim99** [comment]
Cũng như cái này, cả Oauth Facebook cũng tèo luôn và chưa có giải pháp, đợi thôi.

**Comment by vuthao** [comment]
Oauth Facebook trên bản mới nhất đã được fix. Còn cái hình ảnh cần nghiêm cứu thêm.

**Comment by vuthao** [comment]
Mình thử kiểm tra 1 link: http://demo.nukeviet.vn/TheGioi/Nga-lan-dau-dong-cua-Quang-truong-Do-vao-dem-giao-thua-833999.html

Dùng debug 4 lần mới được
https://developers.facebook.com/tools/debug/og/object/
Chắc facebook làm việc khổ quá nên lúc được lúc không.

**Comment by hoangblue** [comment]
Mình dùng trang debug lúc nào cũng được. Mọi người có thể áp dụng cách này để fix.
