### ISSUE TITLE
Lỗi hiển thị tên thành viên trong comment

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1690]
Khi thành viên đăng nhập gửi bình luận thì hiển thị Họ tên, nhưng khi thành viên trả lời bình luận đó thì lại hiển thị tên đăng nhập.
Vậy nên sửa lại là: Khi trả lời cũng hiển thị Họ tên

**Comment by truongemcom** [comment]
Đều sử dụng post_name để hiển thị mà sao khi bấm trả lời post_name lại hiển thị tên đăng nhập nhỉ?

**Comment by vuthao** [comment]
@truongemcom cho xem demo nhé, hiện tại mình kiểm tra không thấy như thông báo.

**Comment by truongemcom** [comment]
Bản trước comment trả lời thụt vào trong rất đẹp và hợp lý. Bản này sao để ngang hàng vậy rất khó theo dõi?

http://demo.nukeviet.vn/KinhTe/Co-the-doi-boi-thuong-danh-du-neu-bong-dung-mac-no-ngan-hang-859734.html

**Comment by truongemcom** [comment]
Ở bản này tìm kiếm với từ khoá: http://demo.nukeviet.vn/seek/q='or'=='1'
Sẽ ra 404? Có phải là do phiên bản PHP kô nhỉ?

**Comment by vuthao** [comment]
Với tìm kiếm, nếu dùng nginx các bạn có thể tham khảo dòng 99 đến 130
https://github.com/nukeviet/ConfigLoadBalancing/blob/master/module/nginx.sh
