### ISSUE TITLE
Cần nâng cấp quản lý Plugin

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#1693]
Plugin hiện tại còn rất nhiều hạn chế khiến việc mở rộng chức năng trở nên khó khăn.
Mình nghĩ nên chuyển phần cài đặt plugin sang cho Mở rộng. Khi truy cập vào Cấu hình chung / Quản lý plugin sẽ hiển thị danh sách các plugin đã cài đặt, chọn plugin sẽ hiển thị ra các tùy chọn thuộc về plugin đó.

Như Xenforo, khi cài thêm một addon (plugin) thì addon sẽ chạy cùng hệ thống, đồng thời nó có thêm giao diện quản trị để thay đổi các tùy chọn.

**Comment by hongoctrien** [comment]
@vuthao cái này rất quan trọng, em đề xuất lưu tâm phát triển luôn trong phiên bản sắp tới.

**Comment by mynukeviet** [comment]
Càng ngày càng thấy cái này quan trọng rất nhiều, đôi khi muốn viết thêm plugin cho module mà nó vướng quá @@

**Comment by hoaquynhtim99** [comment]
Plugin hiện tại 4.6 đã thành Hook
