### ISSUE TITLE
Chức năng hay của ckeditor bị mất

### ISSUE THREAD

**Issue by thanhvu7411** [nukeviet/nukeviet#1698]
Ở các bản beta trước em thấy khi đăng bài có 1 chức năng là "dán và tải hình ảnh về máy chủ" nhưng bản mới nhất không thấy nữa.
Mong nukeviet phục hồi lại chức năng rất hay này!

**Comment by vuthao** [comment]
Hiện tại mình kiểm tra vẫn thấy có bạn, bạn kiểm tra lại dùm xem nhé. 
https://github.com/nukeviet/nukeviet/archive/develop.zip

Nếu không có vui lòng báo rõ các thông tin về môi trường thử nghiệm để chúng tôi có thể kiểm tra lại.
https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md
