### ISSUE TITLE
Không reponsive khi thêm mới khối block

### ISSUE THREAD

**Issue by vandien** [nukeviet/nukeviet#1699]
Mình tạo thêm một số khối block trong Nukeviet V 4.0.23 và các block này hoạt động bình thường trên giao diện Destop, tuy nhiên trên giao diện Mobile thì không Reponsive. Xin mọi người cho ý kiến và cách khắc phục.
Demo: http://vietnamcoffee.asia
Dưới đây là hình ảnh các khối block lỗi:
![l1](https://cloud.githubusercontent.com/assets/16202653/12001051/9f04d720-ab13-11e5-84f5-1692a4b09402.png)
![l2](https://cloud.githubusercontent.com/assets/16202653/12001050/9f044a30-ab13-11e5-9a56-83a564139eb5.png)

Trân trọng.

**Comment by hoaquynhtim99** [comment]
Khối ảnh slide của bạn đang để `col-xs-6 col-md-18` có nghĩa với giao diện di động nó sẽ rộng 6 / 24 chiều rộng màn hình trong khi đó khối menu là `col-xs-18 col-md-6` thì giao diện < 768px nó sẽ rộng cả 18 / 24 chiều rộng. Tiến cử là bạn bỏ đi col-xs-6 và col-xs-18 luôn, thay md bằng sm. Cái slide của bạn mình thấy nó cũng không hỗ trợ responsive hoàn chỉnh mà chỉ ở mức overflow hidden cho khỏi vỡ giao diện thôi, bạn nên kiếm 1 cái slide khác.

Khối block giao diện tin tức bạn cũng đang để css như sau `col-xs-8 col-md-8` , tiến cử là bạn xóa đi thành phần `col-xs-8` đi.

P/S: Bạn đã có công post mình xem giúp chứ đáng nhẽ ra chỉ cần vào Close Issue này của bạn lại. Nội dung này không phải là một Issue

**Comment by vandien** [comment]
Cảm ơn bạn hoaquynhtim99 đã phản hồi nhé. Thực hiện như bạn nói thì mọi thứ đã ổn cả rồi.
(Mình áp dụng theo hướng dẫn ở http://getbootstrap.com/css/#grid nên gặp một số khó khăn trên.)
Trân trọng.

**Comment by hoaquynhtim99** [comment]
Ok bạn vậy mình Close cái Issue này.
