### ISSUE TITLE
Thiếu file autoload.php trong thư mục vendor

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1700]
Thiếu file autoload.php trong thư mục vendor dẫn đến lỗi không cài đặt được nukeviet

**Comment by vuthao** [comment]
Bạn cần dùng composer để lấy thêm file và các thư viện.
Vào 26-12-2015 09:48, "Nukeviet-develop" <notifications@github.com> đã viết:

Thiếu file autoloadphp trong thư mục vendor dẫn đến lỗi không cài đặt được
nukeviet

—
Reply to this email directly or view it on GitHub
<https://github.com/nukeviet/nukeviet/issues/1700>.

**Comment by vuthao** [comment]
Hiện tại mình đã cập nhật thêm code để những bạn không biết sử dụng composer cũng có thể lấy được code.
