### ISSUE TITLE
Lỗi đánh giá bài viết trên module tên có dấu gạch ngang

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1701]
https://github.com/nukeviet/nukeviet/blob/develop/modules/news/funcs/rating.php#L30

Session không dùng tên có dấu gạch ngang (-). VD tên module là **tin-tuc** thì trong trường hợp này không ghi session được => đánh giá thoải mái.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/cf9202b740d8fd64c1f008c85bab03db5c993602
