### ISSUE TITLE
Đề nghị xem xét tạo group cho module trong quản trị site 

### ISSUE THREAD

**Issue by volong1012** [nukeviet/nukeviet#1703]
Đây là ý kiến mới e vừa mới nảy ra - cụ thể như sau :
Hiên nay thì phía bên tay trái của quản trị site là list liệt kê module và khi click vào thì được đưa lên đầu nhưng thành phần này chỉ phù hợp với dạng site sử dụng ít module

Tuy nhiên đối với các site sử dụng rất nhiều module thì nhìn vào sẽ loạn mắt - chắc cũng có trường hợp này rồi. Do đó e đề nghị có thêm tính năng tạo group cho module - cái này giống như tạo group cho layout trong photoshop vậy - phân ra được thành khúc sẽ dễ tìm và sử dụng hơn rất nhiều

**Comment by vuthao** [comment]
Có tính năng sắp xếp các module rồi sao không dùng, nếu có group thì cũng thế thôi.
