### ISSUE TITLE
Lỗi mất thông số của ảnh khi dùng chức năng chèn logo vào ảnh

### ISSUE THREAD

**Issue by thangbv** [nukeviet/nukeviet#1719]
Các ảnh có thông số ảnh như: title, subtile... Khi dùng chức năng này sẽ bị mất. Lỗi sảy ra ở mọi phiên bản

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/423b15988dbc577c68115b18f2a3db4619326e33
