### ISSUE TITLE
Lỗi đi đăng ký thành viên báo email không hợp lệ

### ISSUE THREAD

**Issue by cxnam** [nukeviet/nukeviet#1720]
Khi mình thực hiện đăng ký thàng viên nhập email thì bị báo như trên http://i.imgur.com/UD99tf2.png
Mình đang sử dụng phiên bản NUKEVIET 4.0.24

Các bạn xem giúp mình, vấn đề này nằm ở chỗ nào, không biết có cần thêm module nào nữa không nhỉ?
![2016-01-11_0-10-52](https://cloud.githubusercontent.com/assets/5145416/12222755/29e65e68-b7f8-11e5-9ebe-54e8c16f7216.png)

Tks.

**Comment by vuthao** [comment]
Bạn có thể sửa bằng 1 trong hai cách sau: (Nên làm cả hai)
1) Yêu cầu nhà cung cấp hosting cấu hình chức năng mbstring của PHP
2) Cập nhật file /includes/utf8/lookup.php bằng nội dung của file https://raw.githubusercontent.com/nukeviet/nukeviet/develop/includes/utf8/lookup.php
(Áp dụng với tất cả các phiên bản của NukeViet 4)

**Comment by cxnam** [comment]
Ok tks bạn, mình sẽ kiểm tra lại
