### ISSUE TITLE
Lỗi tìm kiếm tiếng việt

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1727]
Bình thường nếu muốn tìm từ không dấu và có dấu đều như nhau không ảnh hưởng gì, Nhưng có một lỗi là nếu từ cần tìm là chữ đ:

Giả sử trong tiêu đề có: tôi được đi học
Nhưng đánh vào tìm kiếm là toi duoc di hoc sẽ không ra kết quả.

**Comment by anhtunguyen** [comment]
Vấn đề đã được giải quyết ở NukeViet 4.6
