### ISSUE TITLE
Cấu hình ngôn ngữ hiển thị cho thành viên

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1728]
(Tổng hợp lại ý kiển của các bạn đã góp ý khi làm NukeViet 4)
Thêm tính năng ngôn ngữ hiển thị cho thành viên. Cài này do thành viên tự cấu hình. Hệ thống sẽ hiển thị ngôn ngữ trên site theo cấu hình của thành viên đó khi vào site

**Comment by anhtunguyen** [comment]
@vuthao 
Có vấn đề anh cần làm rõ trước khi viết: Khi trong URL có biến language thì hệ thống sẽ ưu tiên nghe theo biến language này hay là nghe theo cấu hình ngôn ngữ của user?

**Comment by vuthao** [comment]
@anhtunguyen 

Hiện tại trong quản trị mình phân biệt:
- Ngôn ngữ giao diện
- Ngôn ngữ CSDL

Nhưng bên ngoài site mình đang coi hai cái trên này là 1, và căn cứ chính theo Ngôn ngữ CSDL

Việc cần làm giờ cần tách bên ngoài site tương tự trong quản trị.
- biến ngôn ngữ trên URL sẽ là ngôn ngữ theo CSDL
- ngôn ngữ theo thành viên cấu hình, sẽ là ngôn ngữ giao diện
- Ngôn ngữ user cấu hình cũng sẽ ghi đè phần "Ngôn ngữ mặc định" tại (/admin/index.php?language=vi&nv=language) của  user luôn
- khi vào trang chủ (nếu chưa xác định được ngôn ngữ), thì ngôn ngữ CSDL và giao diện sẽ dùng luôn theo ngôn ngữ cấu hình nếu có

**Comment by anhtunguyen** [comment]
Đã thêm vào [NukeViet 4.6](https://github.com/nukeviet/nukeviet/commit/a80bb9e2b62f2f08a8511077f2deb498526d91f9)
