### ISSUE TITLE
Nukeviet 4.0.24  Thông báo từ Hệ thống ....user_functions.php on line 109

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#1732]
Thông báo từ Hệ thống
Nên chú ý Nên chú ý: unserialize(): Error at offset 58 of 236 bytes in file /includes/core/user_functions.php on line 109
![user_functions php on line 109](https://cloud.githubusercontent.com/assets/8376014/12271648/c651395c-b98e-11e5-839a-32167a54f7d9.png)

**Comment by vuthao** [comment]
Bạn báo lỗi không đúng quy định, vui lòng đọc lại dòng Please review the guidelines for contributing to this repository.https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md

**Comment by vuthao** [comment]
Lỗi này nhiều khả năng do dữ liệu của bạn gây nên.
