### ISSUE TITLE
Góp ý: đa dạng hóa giao diện cần bổ sung block user có khung đăng nhập truyền thống

### ISSUE THREAD

**Issue by TrustNguyen** [nukeviet/nukeviet#1734]
Để tăng thêm tính đa dạng hóa giao diện nukeviet cần bổ sung block user có khung đăng nhập truyền thống thay vì phải nhấn vào button để hiện lên popup đăng nhập (Việc nhấn button hiện popup còn bị hạn chế khi kéo thả vào những vị trí khác sẽ không thể hiển thị button).

**Comment by yeunukeviet** [comment]
Tán thành ý kiến này

**Comment by HoanDateh** [comment]
Cái này vẫn có mà. Các bạn bật block chọn Modules User chon block global login

**Comment by TrustNguyen** [comment]
Bạn HoanDateh đang nói nukeviet bản nào vậy? Bản dev mới nhất chưa có nhé. Vẫn còn hiện popup nhé.

**Comment by hoaquynhtim99** [comment]
Hiện tại bản mới nhất đã thêm tùy chọn này cho block global user_login
