### ISSUE TITLE
Cài 4.0.24 bị lỗi

### ISSUE THREAD

**Issue by hpleduit** [nukeviet/nukeviet#1736]
![loi cai dat nk24](https://cloud.githubusercontent.com/assets/4101710/12323531/903685dc-baee-11e5-8439-4900ad9cb8bb.jpg)

Help cài phiên bản 4.0.24 bị lỗi như thế này thì xử lý như thế nào anh em? Phiên bản webserver đang dùng vertrigo v2.38
>   Apache 2.4.18
>   PHP 5.5.30
>   MySQL 5.6.28
>   SQLite 3.9.2
>   Smarty 3.1.28
>   PhpMyAdmin 4.5.2
>   Xdebug 2.3.3
>   SQLiteManager -

Anh em nào biết cách khắc phục không ạ

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/1e0d88f6d6fa276bfef1024948093d3c8d4f1a6c

Nguyên nhân: Do trên phiên bản này những cột đánh index, CSDL dùng utf8mb4 cũng không được quá  4 byte. Nên do đó cũng cần điều chỉnh như những cột UNIQUE KEY.
