### ISSUE TITLE
Giao diện Máy Tính bị lỗi

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1739]
Lỗi vỡ giao diện Máy Tính trên các màn hình kích cỡ nhỏ:
![nukeviet4024-anh01](https://cloud.githubusercontent.com/assets/1892900/12370373/12d9fffc-bc41-11e5-88ed-e0963ddc2985.jpg)
![nukeviet4024-anh02](https://cloud.githubusercontent.com/assets/1892900/12370374/12dc8132-bc41-11e5-8ab2-5644cca16830.jpg)
Test trên NukeViet 9582067d32544500ed011e614ff19ff51f0d86a8
Môi trường localhost/ Vertrigo v2.35/ Windows 10
Trình duyệt: FireFox v43.0.4

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/0a83b4365f86f53ca9c23a2e05f2881d5c4291c4
