### ISSUE TITLE
Load website cực kỳ chậm

### ISSUE THREAD

**Issue by cxnam** [nukeviet/nukeviet#1741]
Cho mình hỏi hiện tại mình đang có website http://thoitrangchuyensi.com/ sử dụng nukeviet 3.x nhưng load phải nói rất chậm. Mình đã check log của server thì như sau:

[Tue Jan 19 20:48:19 2016] [error] [client xxx.xxx.xxx.xxx] Script timed out before returning headers: index.php, referer: http://thoitrangchuyensi.com/
[Tue Jan 19 20:50:15 2016] [error] [client xxx.xxx.xxx.xxx] Script timed out before returning headers: index.php, referer: http://thoitrangchuyensi.com/
[Tue Jan 19 20:53:25 2016] [error] [client xxx.xxx.xxx.xxx] Script timed out before returning headers: index.php, referer: http://thoitrangchuyensi.com/
[Tue Jan 19 20:53:46 2016] [error] [client xxx.xxx.xxx.xxx] Script timed out before returning headers: index.php, referer: http://thoitrangchuyensi.com/
[Tue Jan 19 20:53:54 2016] [error] [client xxx.xxx.xxx.xxx] Script timed out before returning headers: index.php, referer: http://thoitrangchuyensi.com/
[Tue Jan 19 20:53:57 2016] [error] [client xxx.xxx.xxx.xxx] Script timed out before returning headers: index.php, referer: http://thoitrangchuyensi.com/
[Tue Jan 19 21:00:15 2016] [error] [client xxx.xxx.xxx.xxx] Script timed out before returning headers: index.php

mình có cấu hình server tăng php max time, cả apache, cũng như mysql, nhưng vẫn rất chậm. Các bạn có thể giúp mình detect chính xác nguyên nhân lỗi từ đâu được không? vì mình k giành PHP lắm. Cảm ơn nukeviet

**Comment by thehung** [comment]
Bạn vui lòng gửi yêu cầu support lên forum.nukeviet.vn
Đây là khu vực báo lỗi, không phải chỗ support!
