### ISSUE TITLE
#GÓP Ý chức năng đóng gói block.

### ISSUE THREAD

**Issue by koxsmile** [nukeviet/nukeviet#1742]
THIẾT NGHĨ CÁC BÁC CÓ THỂ THÊM CHỨC NĂNG ĐÓNG GÓI BLOCK CHO BẢN RC NÀY KHÔNG Ạ! 
- Nó rất cần thiết: Vì chủ yếu nuke cho người Viet ( dân không chuyên) dùng mà động vào cái gì cũng không bằng wp thì cũng khó để nuke vươn xa ạ
- Nếu làm được sẽ rất tiện lợi

**Comment by vuthao** [comment]
Phiên bản NukeViet 4 sẽ không tính năng này được bạn. Theo quy trình đến lúc này sẽ không có tính năng nào mới đưa thêm vào lúc này.

Chắc chắn sẽ phải đề sang 4.1 mới tính đến phát triển tiếp. Giờ cần cho NukeViet để ổn định để dùng đã.

**Comment by vuthao** [comment]
@hoaquynhtim99 hiện tại tính năng này đã có chưa nhỉ. Nếu làm thì hướng xử lý thế nào nhỉ.

**Comment by hoaquynhtim99** [comment]
@vuthao  Phần này có thể làm ở bản hiện tại với điều kiện cài ứng dụng từ NukeViet Store hoặc từ các Package đúng chuẩn thông qua tiện ích lưu danh sách các file ứng dụng khi cài, khi đóng gói sẽ đóng gói các file này.

Do hiện ích hiện tại "quên" ghi loại ứng dụng là block vào bảng setup_extensions nên bỏ qua mất ứng dụng là block

**Comment by vuthao** [comment]
@hoaquynhtim99 Thế em lên kế hoạch sửa lại nó nhé.
Ngoài ra các block cũng có thể đóng gói được theo quy luật đó:  thường có như sau:
- 1 file php
- 1 file .ini
- 1 file .tpl có thể nằm cùng với hai file trên hoặc trong giao diện của module. Nếu vẫn ko tìm thấy đọc file php là có thể biết được tên file tpl ở đâu (Khả năng này chính xác khoảng 90%)

**Comment by hoaquynhtim99** [comment]
Em đã kiểm tra lại, hiện có thể đóng gói block, chỉ có chút lỗi ở phần tìm kiếm, đã fix ở https://github.com/hoaquynhtim99/nukeviet/commit/a9591e452078194dfa45a1c6476eda1ac57ff72e

**Comment by hoaquynhtim99** [comment]
Bài hướng dẫn về cách đóng gói ứng dụng tại https://wiki.nukeviet.vn/programming4:thematic:packageextensions
