### ISSUE TITLE
URL đăng nhập chưa rewrite

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1746]
Xin chào test,

Tài khoản của bạn tại website NukeViet đã được kích hoạt. Dưới đây là thông tin đăng nhập:

Tên tài khoản: test

Bạn hãy click vào đường dẫn dưới đây để đăng nhập và đổi mật khẩu:
URL: http://demo2.nukeviet.vn/index.php?language=vi&nv=users

Đây là thư tự động được gửi đến hòm thư điện tử của bạn từ website NukeViet. Nếu bạn không hiểu gì về nội dung bức thư này, đơn giản hãy xóa nó đi.

Quản trị site

**Comment by vuthao** [comment]
fixed:https://github.com/vuthao/nukeviet/commit/9f5ae8b865581600a564304b81669f395dca1232
