### ISSUE TITLE
Gộp menu Công cụ web và công cụ SEO trong trang quản trị

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1747]
Công cụ web và công cụ SEO nên gộp vào trong 1 menu có tên là "Công cụ".

**Comment by thehung** [comment]
Không gộp vào sẽ vỡ giao diện Admin Control Panel ở một số khu vực đấy!

**Comment by vuthao** [comment]
Dự định sẽ bỏ cái đoạn thời gian ở dòng menu đi. Và chủ để cáu thời gian ở chỗ cấu hình múi giờ.

**Comment by vuthao** [comment]
Đã bỏ cái thời gian ở dòng menu: https://github.com/vuthao/nukeviet/commit/01db1e279147a384634665e41e1ee7a3748c0dc6
