### ISSUE TITLE
Lỗi khi nâng cấp NukeViet

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1751]
Khi thực hiện nâng cấp NukeViet từ bản 4.0.24 lên bản 4.0.25 thì bước cuối cùng có dòng sau:
```
Nâng cấp thành công, dưới đây là những thông tin bạn cần lưu ý.
Thông tin phiên bản 	Giá trị
Phiên bản hiện tại 	4.0.24
Phiên bản mới nhất 	- 
```
(Không tìm thấy được thông tin bản mới nhất)

Và đòng cuối cùng
{LANG.update_package_not_deleted}
Xem trang chủ - Chuyển đến trang quản trị

**Comment by vuthao** [comment]
Cập nhật xong không cập nhật phiên bản mà phải xóa cache mới thấy phiên bản thay đổi.

**Comment by vuthao** [comment]
@hoaquynhtim99 kiểm tra lại phần này dùm anh nhé.

**Comment by vuthao** [comment]
Hiện tại còn như sau:
Khi thực hiện nâng cấp NukeViet từ bản 4.0.24 lên bản 4.0.25 thì bước cuối cùng có dòng sau:
Phiên bản hiện tại   4.0.24
Phiên bản mới nhất   - 

(Không tìm thấy được thông tin bản mới nhất)

Khi thực hiện xóa gói nâng cấp, click vào thực hiện, nó không đóng của sổ lại được, đóng của sổ nó vẫn còn của sổ thông báo, click thêm lần nữa sẽ báo lỗi do đã thực hiện xóa gói nâng cấp rồi

**Comment by hoaquynhtim99** [comment]
Đã sửa: https://github.com/hoaquynhtim99/nukeviet/commit/77dbfbaac820ea6694312316ab6407957408efc9  và  https://github.com/hoaquynhtim99/nukeviet/commit/7bb7fbc3ec7aebb76e55dd8f5d03f22b2d8e0441
