### ISSUE TITLE
Module Version download

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/nukeviet#1757]
Lắp cái động cơ NukeViet 4.0rc1 NukeViet. Cài đặt module dùng cho phiên bản 4.0.19 (21/01/2016 18:29).
Kiểm tra phiên bản chỉ ra rằng có một phiên bản mới hơn. Loại bỏ các mô-đun và thiết lập tải 4.0.19 tải về phiên bản: 4.0.25.
Bộ nhớ cache sạch. Tuy nhiên, kiểm tra phiên bản một lần nữa hiển thị thông báo: module cài đặt tải về phiên bản 4.0.19.
Trong các module ứng dụng và cho thấy phiên bản chính xác của các phiên bản mô-đun tải: 4.0.25.

Установил движок nukeviet nukeviet4.0rc1. Установил модуль download версии 4.0.19 (21/01/2016 18:29).
Проверка версии показала, что есть более новая версия. Удалил модуль download 4.0.19 и установил download версия: 4.0.25.
Почистил кэш. Однако проверка версии вновь показывает сообщение: установлен модуль download версии 4.0.19.
В разделе модули и приложения показывает правильную версию модуля download версия: 4.0.25.

**Comment by vuthao** [comment]
@hoaquynhtim99 em kiểm tra và trả lời cho NukeVlad nhé

**Comment by NukeVlad** [comment]
Bạn cấp quyền truy cập vào bảng điều khiển quản trị?
Вам предоставить доступ в панель администратора ?

**Comment by NukeVlad** [comment]
Исправлено
https://github.com/hoaquynhtim99/nukeviet/commit/59805642ba6418a694780426320f7dc0b03058f2

**Comment by hoaquynhtim99** [comment]
Исправлено : translate : Fixed :heart_eyes:

**Comment by NukeVlad** [comment]
nhất định :heart_eyes:

**Comment by vuthao** [comment]
@hoaquynhtim99 cái này đã xử lý xong chưa nhỉm nếu xong rồi đóng issues dùm anh nhé.
