### ISSUE TITLE
[News] Lỗi khá nặng khi xử lý phân trang main của News

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1759]
Tag: 4.0.25
https://github.com/nukeviet/nukeviet/tree/4.0.25

Nếu phân trang tại Main, kiểu như : 
 > localhost/425/page-2/

thì nó phi về
 >  http://localhost/425/Other/

và trắng trang.

Sau khi cày trọc cả đầu thì phát hiện do functions.php của module bị thiếu một đoạn xử lý pagination của main.

Có vẻ là sau cái này https://github.com/nukeviet/nukeviet/commit/72496d06a535d817770d0271489b8cd1fffac3d2
Đội code fix sớm dùm mình ạ.

**Comment by thangbv** [comment]
Fixed

**Comment by vuthao** [comment]
@thangbv chưa thấy   Pull requests     về lỗi này.

**Comment by thangbv** [comment]
Em quên đẩy sang kho nukeviet

**Comment by vuthao** [comment]
fixed: https://github.com/thangbv/nukeviet/commit/dbacfd853ecdc70c1d76126a0c100344f1c2f365
