### ISSUE TITLE
Lỗi cảnh báo khi cài đặt ứn dụng

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1760]
Lỗi cảnh báo: ftp_delete(): /var/www/vhosts/danangspace.com/danabook.vn/data/tmp/config.ini: No such file or directory in file /vendor/vinades/nukeviet/Ftp/Ftp.php on line 481

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/85c130e82be73a02e5acb9831300b62279c12d78
