### ISSUE TITLE
[News] Lỗi đặt liên kết tĩnh cho tag 

### ISSUE THREAD

**Issue by kedangghet** [nukeviet/nukeviet#1763]
http://localhost/nukeviet/vi/news/tag/b%E1%BB%99-gd&%C4%91t
Các tag có liên kết tĩnh có ký tự & sẽ không được hiển thị. Nên lọc lại ký tự như **chuyên mục**

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/977d51076b78cb65ab7e1bed67756113f58a1c10
