### ISSUE TITLE
Lỗi show tooltip ở module news

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#1767]
Hiện tại khi bật tootltip trong cấu hình module news lên bị lỗi tooltip ko lấy đúng dữ liệu
![untitled](https://cloud.githubusercontent.com/assets/6928431/12608510/19a7b6a4-c50f-11e5-8d3a-53e5fe6886c5.png)

**Comment by trinhthinhhp** [comment]
Lỗi này ở module khi bật tootltip trong admin

**Comment by vuthao** [comment]
Đây là đoạn code gây sai:
```
if ($module_config[$module_name]['showtooltip']) {
                        $xtpl->assign('TOOLTIP_POSITION', $module_config[$module_name]['tooltip_position']);
                        $array_row_i['hometext'] = nv_clean60($array_row_i['hometext'], $module_config[$module_name]['tooltip_length'], true);
                        $xtpl->parse('main.listcat.related.loop.tooltip');
                    }
                    $xtpl->assign('OTHER', $array_row_i);
```
Về nguyên tấc cần $xtpl->assign('OTHER', $array_row_i); trước khi gọi $xtpl->parse('main.listcat.related.loop.tooltip');

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/45327dfee1a1ccc81c40ff79540f1c5e4558bdaa
