### ISSUE TITLE
Lỗi không tự auto chuyển theme

### ISSUE THREAD

**Issue by nguyengiakt** [nukeviet/nukeviet#1768]
Bản 4.0 RC1 này không auto chuyển theme pc sang mobile khi chạy trên mobile, mong BQT giải quyết những lỗi cơ bản này.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/e2e5a10c241fc0628db76d2dbdc94c5b054c4b27
