### ISSUE TITLE
Module Contact: Cần bổ sung chức năng quản lý việc hiển thị thông tin của bộ phận

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1770]
- Hiện tại: bộ phận không có thông tin vẫn cho hiển thị tên ra => rất xấu. Trường hợp không có thông tin nên cho ẩn đi.
- Hiện tại không có chức năng tùy chọn cho hiển thị 1 bộ phận ra trang chính contact hay không => cần bổ sung tùy chọn này.
- Tên bộ phận cần gắn với link (URL) của bộ phận đó.

**Comment by vuthao** [comment]
update: https://github.com/vuthao/nukeviet/commit/0b5a61d090ed4f7b13e8159221de27bd22d1a90d
