### ISSUE TITLE
Lỗi module contact khi gửi thư trả lời từ trang quản trị

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1773]
**1. Cần sửa lại:** Khi admin gửi thư trả lời từ trang quản trị, ngoài việc email cho người trả lời, hệ thống cần phải gửi thư cho hòm thư của bộ phận (Dạng CC), của chính người trả lời (dạng CC, trong trường hợp người trả lời có tiếp nhận liên hệ qua email) và tất cả những người còn lại trong bộ phận (dạng CC, nếu họ được phép nhận liên hệ qua email). Tránh trường hợp bộ phận nhiều người quản lý và có người trả lời quan trang quản trị mà những người kia không biết.

**2. Lỗi:** Khi khách liên hệ trả lời email mà admin gửi từ trang quản trị thì địa chỉ nhận lại là của chính khách liên hệ. (Xem ảnh chụp và mô tả bên dưới)

Email khách nhận được khi admin trả lời từ Admin Control Panel 
![nukeviet4024-anh1](https://cloud.githubusercontent.com/assets/1892900/12652892/7ccdf7aa-c61f-11e5-92a4-c70e5a411018.jpg)

Khi nhấn nút "Trả lời" thì Gmail lại trả lời vào hòm thư của khách:
![nukeviet4024-anh2](https://cloud.githubusercontent.com/assets/1892900/12652893/7cd28432-c61f-11e5-89cc-6ddac049ee69.jpg)

**Comment by hongoctrien** [comment]
Đang sửa

**Comment by vuthao** [comment]
Lỗi 1 đã được sửa: https://github.com/vuthao/nukeviet/commit/6b61347203be1dc4dd0966d47e5688f190061a52
