### ISSUE TITLE
Lỗi chức năng đánh dấu thư chưa đọc ở module contact

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1774]
Nút này không có tác dụng:
![nukeviet4024-anh17](https://cloud.githubusercontent.com/assets/1892900/12653164/d0679460-c620-11e5-844b-22312b8e1059.jpg)

**Comment by hongoctrien** [comment]
Đang fix

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/42cb55dbd06db2d1e4f3548b129a1f315b90f118
