### ISSUE TITLE
Thông báo đăng nhập không rõ ràng.

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1775]
Khi đăng nhập bằng facebook trên site nukeviet.vn nhận được thông báo:

Email của OpenID mà bạn vừa khai báo đã được gắn trước đó vào một tài khoản. Nếu tài khoản này là của bạn, hãy xác nhận bằng cách khai báo mật khẩu đăng nhập.

Nên thông báo rõ là tài khoản nào.

**Comment by vuthao** [comment]
Khi đăng nhập từ diễn đàn, sau đó login bằng facebook xong.

Hệ thống không chuyển về trang xác thực để chuyển trả lại Forum. 

@hoaquynhtim99 xem cái này nhé.

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/7e7cd9ba4555fdd992e2254ab687f38456b7c29a
