### ISSUE TITLE
Thêm sắp xếp thứ tự ngôn ngữ

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1776]
/admin/index.php?language=vi&nv=language
Ngôn ngữ cần sắp xếp thứ tự, thuận tiện cho người thiết kế khi thiết kế website đa ngôn ngữ, sắp xếp ngôn ngữ nào hiển thị trước, hiển thị sau.

**Comment by hoaquynhtim99** [comment]
Added: https://github.com/hoaquynhtim99/nukeviet/commit/921e2a53cc6530e395c65741e516611eadc4a1b6
