### ISSUE TITLE
SQLSTATE [23000]

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/nukeviet#1778]
Trong khi cài đặt NukeViet CMS khi bạn nhấp chuột vào nút Gửi để tạo ra một cơ sở dữ liệu nhận lỗi:
SQLSTATE [23000] Integnite constraint violation: 1062 Duplicate entry "4" for key "PRIMARY" 
và tiến hành các bước tiếp theo của quá trình cài đặt..
Ông thấy rằng các cơ sở dữ liệu được tạo ra tự động với mã hóa khác với utf8mb4_unicode_ci, sửa chữa cài đặt mã hóa và chuyển sang bước tiếp theo.
Latest official version 	Version Number 4.0.25, updated on 20/01/2016 20:00
PHP version 	5.6.17
OS server 	LINUX
Database Version 	mysql 5.5.45-cll-lve
http://www.icq.com/files/0gMcAyDORe2z2RGeq1nier56aa45851af

(Во время установки CMS nukeviet при нажатии на кнопку Отправить для создания базы данных получаю ошибку:
SQLSTATE [23000] Integnite constraint violation: 1062 Duplicate entry "4" for key "PRIMARY"  и не переходит на следующий шаг установки.
Увидел, что автоматически база данных создается с кодировкой отличной от utf8mb4_unicode_ci, поправил кодировку и установка перешла на следующий шаг.

**Comment by hongoctrien** [comment]
Đang xem

**Comment by NukeVlad** [comment]
@hongoctrien hongoctrien Xin lỗi, tôi đã tạo ra các vấn đề chính mình, sau khi tạo một cơ sở dữ liệu bằng cách sử dụng SQL và nó không được tạo ra với một khẩu súng trong bảng mã. Vấn đề có thể được đóng lại.
