### ISSUE TITLE
Missing argument

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1779]
Missing argument 1 for NukeViet\Http\Http::__construct(), called in vendor\vinades\nukeviet\Http\Http.php on line 437 and defined] [FILE: /vendor/vinades/nukeviet/Http/Http.php] [LINE: 43]

**Comment by vuthao** [comment]
Lỗi này xẩy ra khi nào và môi trường thử nghiệm như thế nào @dangdinhtu2014 

https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/b116bc3e4e1f7e0facf52d00af396df063410909
