### ISSUE TITLE
[Mở rộng] Không cài đè được ứng dụng để cập nhật qua NV Store

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1780]
![how-to-update](https://cloud.githubusercontent.com/assets/6290970/12691985/cfe41050-c723-11e5-865c-1bb9baf65e17.PNG)
Nếu có ver mới thì có vẻ ko cập nhật thẳng từ NV Store được.

**Comment by vuthao** [comment]
@hoaquynhtim99 xem lại vấn đề này nhé.

**Comment by hoaquynhtim99** [comment]
Theo em thì cái này vẫn nên để như thế, việc cài mới và cài đè nó khác nhau, nếu cài đè chỉ có phần code được thay mới còn CSDL thì vẫn là cũ. Nếu ứng dụng đã được cài rồi muốn cập nhật phải vào phần kiểm tra phiên bản để cập nhật chức năng cập nhật này đã có.

Nếu muốn cài mới thì phải thực hiện theo thao tác: Xóa ứng dụng nếu đang cài => Vào quản lý ứng dụng xóa ứng dụng này khỏi hệ thống => Cài mới ứng dụng.

**Comment by hoaquynhtim99** [comment]
Hiện tại đã thêm hướng dẫn rõ hơn nếu ứng dụng đã có: https://github.com/hoaquynhtim99/nukeviet/commit/b3e05d66095c70770c4b1c7f8653f8b502dbbf34
