### ISSUE TITLE
Kiểm tra lại phần nhận diện thiết bị

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1783]
Mọi lần kiểm tra trên cốc cốc nó nhận các loại thiết bị bio kiểm tra thấy phần nhận diện thiết bị không hoạt động. tính năng hiển thị trên các loại thiết bị của block lỗi

**Comment by htuyen1994** [comment]
@hongoctrien a kiểm tra sớm giúp e với, đang cần

**Comment by hongoctrien** [comment]
A chưa hiểu lắm. 
Em xem có phải như thế này không https://github.com/nukeviet/nukeviet/issues/1768

**Comment by htuyen1994** [comment]
không phải a. a thử cấu hình hiển thị block trên di động, rồi dùng cốc cốc xem, n vẫn không hiện, trước nó vẫn hiện được a ạ.

**Comment by vuthao** [comment]
lối này đã được sửa trước đó rồi nhé.
