### ISSUE TITLE
Lỗi module block_newscenter 

### ISSUE THREAD

**Issue by tuanthanhth** [nukeviet/nukeviet#1786]
Khi dùng news hay module ảo của nuke RC bật block (module block_newscenter ) thì bị lỗi 404 nguyên module đó.

**Comment by hongoctrien** [comment]
@tuanthanhth bạn vui lòng đọc quy định thông báo lỗi ạ https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md
Bạn cài mới RC1 chứ?
Khi cài mới mặc định đã có block này rồi, bạn mô tả rõ lỗi hơn đuợc chứ

**Comment by tuanthanhth** [comment]
Hiện tại mình chạy web này
http://thuochotrosuckhoe.com/nha-thuoc/
Bản Rc1, 
Block module block_newscenter đã có nhưng ko chạy...khi bật lên thì cả module http://thuochotrosuckhoe.com/nha-thuoc/ không hiển thị.
Lỗi máy chủ
500

**Comment by hongoctrien** [comment]
@tuanthanhth bạn có thể gửi thông tin (quản trị + hosting) vào mail hongoctrien@nukeviet.vn để mình kiểm tra nhanh hơn nhé.

**Comment by hongoctrien** [comment]
Lỗi này của bạn không phải do block newscenter nhé.
Do block của module shops làm sai lệch thông tin.
Fixed: https://github.com/hongoctrien/module-shops/commit/3a6985102cd48a6294e73650eb6b62a70ca9c004

**Comment by tuanthanhth** [comment]
Hi Mr Ngọc Triển, MÌnh cài mới bản Rc2 mà ko biết module shops nào tương thích với phiên bản này, lên diễn đàn cũng chưa thấy trao đổi nên mình viết mail nhờ giúp đỡ. Thanks==================== 04.02.2016, 16:28, "Hồ Ngọc Triển" <notifications@github.com>:Lỗi này của bạn không phải do block newscenter nhé. Do block của module shops làm sai lệch thông tin. Fixed: hongoctrien/module-shops@3a69851—Reply to this email directly or view it on GitHub.   -- Nguyễn Tuấn Thành (Mr)Phòng Kinh Doanh0901.339.777 – 0916.888.747=================Công Ty Cổ Phần Đầu Tư Thương Mại Sài Gòn Asia A. 21/5 Trường Sơn, P.4, Q.Tân Bình, TP.HCM T. ĐT: (08) 66536644 - Fax:  (08) 66536644 E. Email:  tuanthanh@asiaco.vn Y. Y!M: tuan.thanhth - Skype: tuanthanhth E. Website: www.asiaco.vn
