### ISSUE TITLE
Lỗi Xung đột Jquery của module quảng cáo

### ISSUE THREAD

**Issue by nguyengiakt** [nukeviet/nukeviet#1787]
Module quảng cáo khi chèn vào thì những module news center hoặc những block khác sẽ mất link, ko click vào được.

**Comment by vuthao** [comment]
Vạn gửi link demo được không.

**Comment by nguyengiakt** [comment]
![a](https://cloud.githubusercontent.com/assets/2918834/12747286/afddcad0-c9d5-11e5-82b3-ceb34f2ee8c6.jpg)
Mình gửi hình ảnh, chỗ newscenter và cái link facebook chỗ fan page link nó bị mất ko click vào nữa, cả tooltip cũng hoạt động.

**Comment by nguyengiakt** [comment]
![b](https://cloud.githubusercontent.com/assets/2918834/12747334/03cad07a-c9d6-11e5-96b6-ee183ee94354.jpg)
Khi mình sửa thành block html thì chạy ok, tooltip hiện lại, nên mình nghĩ xung đột jquery

**Comment by hongoctrien** [comment]
@nguyengiakt banner đó là file ảnh hay flash đó bạn?
Block global banner không dùng thêm thư viện js nào, nên xung đột là không phải.

**Comment by nguyengiakt** [comment]
nó là hình ảnh bạn ơi. khi mình gắn vào là đột ngột mất link

**Comment by hongoctrien** [comment]
Bạn cài mới NukeViet bản mới nhất rồi test lại giúp mình nhé. Theo như hình thì khả năng do div nào đó đè lên mọi thứ, nên không rê chuột dc vào link.
Nếu lỗi trên default thì sẽ xử lý ở đây, còn nếu lỗi do cái ảnh hay do giao diện của bạn đã chỉnh sửa thì mình chuyển sang forum xử lý.

**Comment by nguyengiakt** [comment]
cảm ơn bạn, mình sẽ kiểm tra thêm về lỗi này
