### ISSUE TITLE
Lỗi nguồn tin bài viết

### ISSUE THREAD

**Issue by nguyengiakt** [nukeviet/nukeviet#1789]
Khi bấm vào nguồn tin có sẳn ở bài viết trước thì hiện ra mình chọn, khi click thì nó mất, bắt buộc nhập lại.
![c](https://cloud.githubusercontent.com/assets/2918834/12747401/68c96eb4-c9d6-11e5-9dc8-25b1ac14bb45.jpg)

**Comment by hongoctrien** [comment]
Bạn bật debug xem có thông báo lỗi nào về js không nhé.
Mình test cũng không thấy lỗi như bạn nói.

**Comment by anhyeuviolet** [comment]
Cái này hình như do bạn lưu nguồn tin bị sai nên như vậy hay sao ấy. Mình test ko thấy lỗi.

**Comment by nguyengiakt** [comment]
có thể là do lúc mình nâng cấp từ 3.4 lên bảng rc, chỗ nguồn tin nó lưu nó lỗi. Mình xóa nguồn tin và làm lại thì ok

**Comment by hongoctrien** [comment]
Github chỉ là nơi báo lỗi cho mã nguồn NukeViet mới cài, chưa can thiệt gì thôi, còn mọi vấn đề khác bạn post tại diễn đàn nhé.

**Comment by anhyeuviolet** [comment]
@hongoctrien xem lại cái báo lỗi bên forum hộ mình cái.
Mất hết post mất hứng quá.

**Comment by vuthao** [comment]
Mình đã cập nhật lại số lượng bài viết rồi nhé.
Vào 05-02-2016 10:50, "Kenny Nguyen" <notifications@github.com> đã viết:

**Comment by anhyeuviolet** [comment]
@vuthao tài khoản của em vẫn lỗi anh ơi.
User anhyeuviolet ( Kenny Nguyễn ).
https://nukeviet.vn/vi/forum/profile/Kenny-Nguyen-34044/

Em có 20xx bài ( hơn 2 nghìn ) mà giờ đếm có 3 bài thôi. Giờ các bài cũ của em gán tên Nguyễn phi long gì đó.
https://nukeviet.vn/vi/forum/profile/Nguyen-phi-long-32902/

**Comment by vuthao** [comment]
Để tối mình kiểm tra lại. Giờ đang đi trên đường.
Vào 05-02-2016 13:10, "Kenny Nguyen" <notifications@github.com> đã viết:

**Comment by nguyengiakt** [comment]
khi nào có bản rc 2 a thảo :D thất hẹn 2 ngày roài

**Comment by vuthao** [comment]
Hiện tại các lỗi phát sinh đã được xử lý xong. 
về cơ bản code của Nukeviet đã xử lý xong, chờ anh Hùng thông báo.
