### ISSUE TITLE
lỗi tích chọn hiển thị trên block

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#1791]
Khi tích chọn các thiết bị khác mà không tích chọn các hiển thị thì trên điện thoại thiết bị đó vẫn hoạt động

**Comment by hongoctrien** [comment]
Sửa theo đây thử anh https://github.com/vuthao/nukeviet/commit/e2e5a10c241fc0628db76d2dbdc94c5b054c4b27

**Comment by trinhthinhhp** [comment]
Mới cập nhật bản mới nhất nhánh develop xong ko thấy động tĩnh, test vẫn thế

**Comment by vuthao** [comment]
mô tả rõ ra nhé @trinhthinhhp, không có quay lại video lỗi.
vấn đề em viết mà anh đọc cũng không hiểu là nó lỗi khi nào.

**Comment by trinhthinhhp** [comment]
@vuthao trong block cấu hình tích chọn hiển thị "Các thiết bị khác" hoặc "máy tính bảng", chuyển qua điện thoại vẫn thấy hiện

**Comment by trinhthinhhp** [comment]
Lỗi do csdl chưa nâng cấp một số thay đổi ở bản 25
