### ISSUE TITLE
Nên chú ý: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#1794]
Khi đăng mới hoặt sửa 1 bài viết trong news, page
Nên chú ý: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'uploads/news/PTcms25' for key 'name'
Lỗi cảnh báo	Lỗi cảnh báo: is_dir(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/**/***/:/**:/var/tmp:/usr/local/lib/php/:/usr/local/php55/lib/php/) in file /includes/core/filesystem_functions.php on line 384

**Trong phần Quản lý Files** -> upload 
Tính năng dùng chuột phải (sửa,xóa,cắt,thay đổi tên file,...) bị mất tác dụng hoàng toàn.

Thông tin chung:
nukeviet: 4.0.25, cập nhật vào: 21/01/2016 00:00
Hosting: Linux
DirectAdmin
Apache 2.4.12
MySQL 5.5.45
Php 5.5.28

Host này sử dụng nukeviet: 4.0.24 thì chạy tốt không bị lỗi

**Comment by hongoctrien** [comment]
@NukeVietCMS bạn nói rõ hơn về quy trình gây lỗi mình với, đây là site bạn mới cai và chưa chỉnh sửa gì chứ ạ?

**Comment by NukeVietCMS** [comment]
Domain: http://thongboncaubinhduong.com
Cài mới hoàn toàn.
Có chỉnh 2 chồ là: vi&nv thành vi&phattrien và đổi tên thư mục admin.
Những cái mà mình chỉnh sửa này thì trên tất cả các Phiên bản trước điều chạy ổ định. 
Có lẽ không phải do chỉnh sửa mà ra rồi.
**Còn phần: Quản lý Files -> upload** thì lỗi ở Chrome. Coccoc thì không bị lỗi này.

**Comment by vuthao** [comment]
bạn thử xóa hết log, sau đó thực hiện reload lại thư mục upload xem sao:
![untitled](https://cloud.githubusercontent.com/assets/2491500/12870175/69348b5c-cd6b-11e5-95aa-31456ce6146a.png)

Nếu vẫn còn, bạn có thể cài mới 1 site từ https://github.com/nukeviet/nukeviet/archive/develop.zip, sao đó gửi lại tài khoản hosting và tài khoản qua email webmaster acòng nukeviet.vn để tôi có thể kiểm tra kỹ hơn, bởi các môi trường chúng tôi có không thấy lỗi trên.

**Comment by NukeVietCMS** [comment]
Đã xóa hết log, reload lại thư mục upload.
Nhưng vẫn vậy thôi không có kết quả sai khác. 
Không hiểu vì sao nửa. Trong khi web khác cùng 1 code trên server này vẫn chạy bình thường.

**Comment by vuthao** [comment]
thế thì bạn tự kiểm tra nguyên nhân lỗi thôi, chứ mình chưa thấy site nào bị lỗi này.
