### ISSUE TITLE
#Đề xuất bổ sung chức năng xóa thư mục trong module Upload

### ISSUE THREAD

**Issue by thucvinh** [nukeviet/nukeviet#1798]
Hiện tại trong các thư mục con chỉ cho phép tạo mà không xóa được. Xin được bổ sung chức năng xóa cho các thư mục con.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/62980cef341f3a9247f86e7f37b8f247532d2612

Hiện tại tôi đã sửa theo hướng:
- Quản trị từ điều hành chung có thể xóa mọi thư mục trong module.
- Không được xóa thư mục upload của module (upload/tenmodle)
- Quản trị module sẽ không được xóa các module có chứ thư mục con.
