### ISSUE TITLE
[Blocks] Biến $blockID không hoạt động trong các block của theme

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1799]
Ver 4.0.25 thì biến $blockID ko dùng được. Một số theme sẽ bị trùng id, dẫn tới xung đột JS.

**Comment by vuthao** [comment]
Tôi kiểm tra thì biến $blockID vấn hoạt động, ví dụ block users\blocks\global.user_button.php.
Bạn chú ý nếu sử dụng 1 biến trong function cần global biến đó.
Còn nếu sử dụng trong template có thể sử dụng luôn {BLOCK_ID}

**Comment by anhyeuviolet** [comment]
Em báo block của theme mà. Anh test global của module ah ?
Vào 07-02-2016 06:41, "Vu Thao" <notifications@github.com> đã viết:

**Comment by vuthao** [comment]
Tôi đã kiểm tra các trường hợp: Bạn chú ý nếu sử dụng 1 biến trong function cần global biến đó.

**Comment by anhyeuviolet** [comment]
@vuthao em theo dõi và để xuất để cái biến $blockID được tạo ra mà. Nên chắc ko nhầm lẫn vụ phải global cho nó đâu.
Anh đã test trên các theme không phải default chưa ?
Đơn giản nhất là copy default ra thành 1 theme khác, kích hoạt luôn.
Kết quả trả về là NULL khi var_dump.

**Comment by anhyeuviolet** [comment]
https://github.com/nukeviet/nukeviet/commit/e5924f63f926bf0a5483c5e4c356af8a488b9686

**Comment by anhyeuviolet** [comment]
Thế lỗi này đóng luôn hay sao ạ @vuthao

**Comment by vuthao** [comment]
@anhyeuviolet tôi đã kiểm tra kỹ cái này, không thấy như bạn báo, nên không mở lại.

Bạn cài dùm 1 site demo và gây lỗi đó chỉ rõ lỗi ở file block nào nhé, sau đó gửi dùm qua email webmaster acòng nukeviet chấm vn. Nếu không có host báo để tôi gửi hosting.

**Comment by anhyeuviolet** [comment]
Tiến hành như sau : 
Tải NV 4.0.26 về. Cài như bình thường.
Trong thư mục themes, copy theme default thành một theme khác. Ví dụ : abc.

Trong ACP, tiến hành cấu hình theme abc như bình thường.

Tiến hành chỉnh sửa \themes\abc\blocks\global.company_info.php

Sửa dòng 167 thành
```
global $global_config, $lang_global, $blockID;
```

Thêm vào bên dưới
```
        $xtpl->assign('DATA', $block_config);
```

```
        $xtpl->assign('blockID', $blockID);
	var_dump($blockID);
```

Giao diện trang chủ trả về NULL.
Nếu xuất ra TPL thì là kết quá rỗng.
Anh @vuthao làm thử xem sao nhé.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/177534a51264e32bc2495e334c2aa6c00d154c00
Thank @anhyeuviolet
