### ISSUE TITLE
[Block Company Info] Bị sai maps nếu kích hoạt nhiều block với bản đồ khác nhau.

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1800]
Các block này dùng id cố định, thêm vào đó JS gọi map lại nằm trong main.js.
Cách này không hay cho lắm do id sẽ bị trùng => 10 block nhưng cũng chỉ 1 map mà thôi.
=> Nên đưa JS của riêng phần này vào trong TPL, hoặc dùng prefix ( suffix ) trong JS để nhận diện phần tử gọi block.
Với TPL thì nên xuất HTML linh hoạt hơn, tránh trùng id khi dùng nhiều block.

**Comment by hoaquynhtim99** [comment]
Đã sửa : https://github.com/hoaquynhtim99/nukeviet/commit/49552be3c1ae14136ad09982f8b2647f1229c2eb
