### ISSUE TITLE
Lỗi ckeditor

### ISSUE THREAD

**Issue by thanhvu7411** [nukeviet/nukeviet#1802]
![error](https://cloud.githubusercontent.com/assets/7390481/12877184/d3f2c0ae-ce41-11e5-98e0-4067b652bb98.png)
Lỗi các icon của ckeditor không hiển thị đúng vị trí! Lỗi này đã xuất hiện ở mấy bản beta và được khắc phục nhưng bản RC1 lại gặp lại!

**Comment by vuthao** [comment]
@thanhvu7411 bạn chỉ rõ dùm những icon nào bị lỗi, và lỗi trên trình duyệt nào nhé.

**Comment by hongoctrien** [comment]
@thanhvu7411 bạn xóa cache trình duyệt xem sao nhé.
