### ISSUE TITLE
Lỗi biến mất khung soạn thảo của CKeditor

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1803]
Ckeditor biến mất nếu sau khi ấn nút "Phóng to khung soạn thảo" mà tiếp tục ấn nút "Switch toolbar" (xem ảnh)
![ckeditor](https://cloud.githubusercontent.com/assets/1892900/12908401/7307b7ac-cf29-11e5-9a60-e2f6315ab6f6.jpg)
Lỗi tương tự nếu ấn nút "Switch toolbar" sau đó ấn nút "Phóng to khung soạn thảo" rồi tiếp tục ấn nút "Switch toolbar" (để phục hồi lại thanh toolbar cũ).

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/417c3e515fd091edd85c06b825395bf2f4e844c5
