### ISSUE TITLE
Lỗi xóa tài khoản quản trị

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1804]
Xóa Quản trị website => Không gửi thông báo => Nhập mật khẩu => Nhấn Xóa Quản trị website => Lỗi 500 nhưng vẫn xóa thành công.

**Comment by vuthao** [comment]
@hongoctrien mình kiểm tra không thấy lỗi như thông báo.

Cập nhật thông tin để kiểm tra lại nhé: https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md

**Comment by hongoctrien** [comment]
Rõ ràng hôm trc bị, giờ test lại cũng không thấy lỗi.
Em đóng nhé.
