### ISSUE TITLE
Lỗi đường dẫn news

### ISSUE THREAD

**Issue by nguyengiakt** [nukeviet/nukeviet#1805]
Sau khi nâng cấp module news bị lỗi này, khi cập nhật bài viết xong thì click vào xem thì nó bị đường dẫn ko truy cập đc, thêm chữ other
![a](https://cloud.githubusercontent.com/assets/2918834/12979603/c2af67a4-d10a-11e5-9b49-9de1fcd5a308.jpg)

**Comment by nguyengiakt** [comment]
Thông báo từ Hệ thống Nên chú ý: Undefined index: newday in file /modules/news/funcs/main.php on line 78

![b](https://cloud.githubusercontent.com/assets/2918834/12979812/f12a451c-d10b-11e5-8583-767207c73756.jpg)

**Comment by nguyengiakt** [comment]
Đi kèm với cái này
![c](https://cloud.githubusercontent.com/assets/2918834/12980131/a75f1cd0-d10d-11e5-8307-3fa716c183aa.jpg)

**Comment by nguyengiakt** [comment]
mình nghĩ chỗ cat có vấn đề, upload lại bản rc 1 ok

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/5f5878669806ce75d0301449aeee1bdd42db44b7

Để khắc phục tạm, các bạn có thể sửa như sau:
Thay thế file modules/news/admin/content.php bằng file https://github.com/nukeviet/nukeviet/blob/develop/modules/news/admin/content.php

vào quản trị, sửa lại bài viết bị lỗi.
