### ISSUE TITLE
Lỗi tìm kiếm nâng cao news

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#1806]
Thông báo từ Hệ thống
Nên chú ý Nên chú ý: Undefined variable: img_src in file /modules/news/funcs/search.php on line 183
Phiên bản nuke rc2

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/0fe2044076a008d5651668643c174acfb7c3c201
