### ISSUE TITLE
Lỗi Undefined index (Thiếu ngôn ngữ tiếng Pháp)

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1807]
Khi bấm vào cấu hình chèn logo thì hiện ra một list như bên dưới:

Notifications from the system
Attention	Attention: Undefined index: logoposbottomright in file /admin/upload/config.php on line 16
Attention	Attention: Undefined index: logoposbottomleft in file /admin/upload/config.php on line 17
Attention	Attention: Undefined index: logoposbottomcenter in file /admin/upload/config.php on line 18
Attention	Attention: Undefined index: logoposcenterright in file /admin/upload/config.php on line 19
Attention	Attention: Undefined index: logoposcenterleft in file /admin/upload/config.php on line 20
Attention	Attention: Undefined index: logoposcentercenter in file /admin/upload/config.php on line 21
Attention	Attention: Undefined index: logopostopright in file /admin/upload/config.php on line 22
Attention	Attention: Undefined index: logopostopleft in file /admin/upload/config.php on line 23
Attention	Attention: Undefined index: logopostopcenter in file /admin/upload/config.php on line 24

**Comment by vuthao** [comment]
@truongemcom xem laij quy định báo lỗi tại: https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md

Lỗi này xẩy ra do thiếu ngôn ngữ:
- Ngôn ngữ tiếng Việt Nukeviet 4 RC1, không bị lỗi này
- Ngôn ngữ tiếng Anh xẩy ra lỗi ở Nukeviet 4 RC1, RC2 đã khắc phục.
- Ngôn ngữ tiếng Pháp vẫn còn lỗi.

**Comment by truongemcom** [comment]
Xem lại rồi, nhưng quy định tùm lum thứ làm biếng ghi.
Còn nhiều lỗi nữa hôm nào rảnh rỗi mới post theo cái quy định đó được.
