### ISSUE TITLE
[News] Bài viết hết hạn - Link bài bị sai

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1809]
Phiên bản 4.0.26
Lấy một bài viết từ News, ví dụ Hãy trở thành nhà cung cấp dịch vụ của NukeViet!
Chọn sửa. Chỉnh ngày hết hạn lại, ví như test vào ngày 15 thì chỉnh lại là 14 13 gì đó ...
Lưu lại. Khi đó bài viết sẽ là hết hạn và có màu đỏ.
Liên kết sẽ thành 
http://localhost/426/Other/hay-tro-thanh-nha-cung-cap-dich-vu-cua-nukeviet-6.html

Tất nhiên đó là liên kết hỏng.
Không biết có tính là lỗi không nữa. 
Cái này là chủ động sửa cho bài viết hết hạn. Chưa thử với bài viết tự bị hệ thống cho hết hạn.
// Bài viết được hệ thống cho hết hạn thì ko bị như trên.

**Comment by hongoctrien** [comment]
@anhyeuviolet test lại trên develop giúp mình nhé. Mình test trên develop không thấy lỗi này.
https://github.com/nukeviet/nukeviet/commit/5f5878669806ce75d0301449aeee1bdd42db44b7

**Comment by anhyeuviolet** [comment]
@hongoctrien Xác nhận. Cái này bị lỗi ở Tag 4.0.26 về trước thôi. Dev thì ko bị nữa. Đóng thôi :D
