### ISSUE TITLE
Lỗi giao diện mobile siteterms

### ISSUE THREAD

**Issue by nguyengiakt** [nukeviet/nukeviet#1812]
Hiện giao diện mobile khi truy cập vào phần siteterms bị báo lỗi ko tồn tại. Cái này ko biết phải lỗi ko, hay phải viết giao diện mobile cho siteterms

**Comment by nguyengiakt** [comment]
![10654055_1146567242028875_1589003168_n](https://cloud.githubusercontent.com/assets/2918834/13082419/389992e0-d503-11e5-8146-1a040eb16f01.jpg)

**Comment by nguyengiakt** [comment]
Chỗ module trong siteterm là mình đã set giao diện desktop và mobile rồi nhé

**Comment by hongoctrien** [comment]
@nguyengiakt ạn vào ACP/Quản lý giao diện/Thiết lập layout, chọn giao diện là **mobile_default** rồi nhấn **Lưu tất cả thay đổi*  ở cuối xem nhé. NukeViet mặc định không bị lỗi này ạ.

**Comment by nguyengiakt** [comment]
mình thử rồi vẫn ko đc, thật ra nukeviet mặc định mình chỉ chỉnh sửa css ra màu xanh thôi bạn ơi. cái siteterm nó đang bị lỗi

**Comment by hongoctrien** [comment]
Bạn test lại trên NukeViet develop mình với nhé, nếu lỗi trên đó thì mình kiểm tra lại.
Hiện tại mình không thấy lỗi này ạ.

**Comment by vuthao** [comment]
Mình kiểm tra bản mặc định cũng không thấy lỗi.

**Comment by nguyengiakt** [comment]
cảm ơn 2 bạn, mình thực hiện cài lại nó đã ok :dancer:

**Comment by nguyengiakt** [comment]
rồi mình biết lỗi đâu rồi, nếu để chỗ hiển thị mặc định thì nó ok, nếu mình chọn left-body thì nó ko hiển thị.
![c](https://cloud.githubusercontent.com/assets/2918834/13166979/f236d268-d700-11e5-8c13-d168494f05f3.jpg)

**Comment by vuthao** [comment]
@hongoctrien như thế là vấn đề đó. Với giao diện mobile nếu không có layout sẽ dùng layout body
fixed: https://github.com/nukeviet/nukeviet/commit/d211ba14859f9798ee85060588fe23bfd62e9f32
