### ISSUE TITLE
Lỗi không lưu loại mime bị cấm trong cấu hình upload

### ISSUE THREAD

**Issue by stormlove** [nukeviet/nukeviet#1814]
Không lưu cấu hình "Loại mime bị cấm", đánh dấu chọn các mime, ấn Cập nhật nó không lưu mà lại chọn vào "Loại files cho phép" hoặc "Phần mở rộng bị cấm".

Lỗi trên phiên bản 4.0.25,  4.0.26
Windows 10 Home 64bit
Wamp Server 2.5 64bit
PHP 5.5.12
MySQL 5.6.17
Web browse:  Chrome

**Comment by hongoctrien** [comment]
Đang kiểm tra

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/3c0ac5fe655823dbfce164ceee00402cd3558368
