### ISSUE TITLE
Canh đều các dòng chữ trong giao diện đầu tiên

### ISSUE THREAD

**Issue by binhminhs11** [nukeviet/nukeviet#1815]
Các dòng chữ nhìn trong giao diện đầu tiên khá lộn xộn, chưa canh đều cho đẹp. Cần sửa lại cho đẹp !
![nukeviet-4-rc1](https://cloud.githubusercontent.com/assets/8745219/13108968/189be26c-d5a9-11e5-9f8e-0c14a0743736.png)

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/8e409f5392d84824154c802ffdfd908f2dd3393f

**Comment by vuthao** [comment]
Theo ý của @binhminhs11 mình hiểu là cần căn đều hai bên cho phần giới thiệu bài viết, còn @hongoctrien đang giới hạn lại số ký tự của phân nay. Không biết có đúng không các bạn.

**Comment by hongoctrien** [comment]
https://nukeviet.vn/vi/forum/Canh-deu-cac-dong-chu-trong-giao-dien-dau-tien-t37427/
Cái này chắc là của bạn.

@vuthao ý bạn ý là tất cả các đọan văn đều canh đều hai bên ý. Em thấy không cần thiết, căn tất cả hai bên có khi xấu hơn.

@binhminhs11 mình sẽ hỗ trợ trên diễn đàn nhé.

**Comment by binhminhs11** [comment]
@vuthao <https://github.com/vuthao> ý bạn ý là tất cả các đọan văn đều canh
đều hai bên ý. Em thấy không cần thiết, căn tất cả hai bên có khi xấu hơn.

mình thấy các site khác họ đều canh hai bên

2016-02-19 10:52 GMT+07:00 Vu Thao <notifications@github.com>:

**Comment by binhminhs11** [comment]
ý mình là canh đề các đoạn text
