### ISSUE TITLE
Lỗi phân quyền hệ thống

### ISSUE THREAD

**Issue by stormlove** [nukeviet/nukeviet#1816]
1. Các tài khoản quản trị khi mất quyền làm việc với module siteinfo thì sẽ lỗi 404 khi truy cập index của admin, kể cả Quản trị tối cao.
2. Tài khoản Quản lý module dù được cấp quyền làm việc với module siteinfo cũng không thể truy cập đc.
** Thắc mắc nhỏ: tại sao Quản trị tối cao là tài khoản duy nhất mà vẫn phân quyền cho tài khoản này làm gì ?

Nukeviet 4.0.26
Windows 10 Home 64bit
Wamp Server 2.5 64bit
PHP 5.5.12
MySQL 5.6.17
Web browse:  Edge, Chrome

**Comment by hongoctrien** [comment]
> Các tài khoản quản trị khi mất quyền làm việc với module siteinfo thì sẽ lỗi 404 khi truy cập index của admin, kể cả Quản trị tối cao.

>Tài khoản Quản lý module dù được cấp quyền làm việc với module siteinfo cũng không thể truy cập đc.

Mình đã bỏ việc phân quyền cho module siteinfo, nó luôn được kích hoạt. https://github.com/hongoctrien/nukeviet/commit/bc7fc6dc9494d6ae62585d87933f8a8d0a7a4f7a

> Thắc mắc nhỏ: tại sao Quản trị tối cao là tài khoản duy nhất mà vẫn phân quyền cho tài khoản này làm gì ?

Là quản trị tối cao nhưng đôi khi cũng không dùng hết các chức năng hệ thống.
Ví dụ: Sau khi bàn giao site cho khách hàng, bàn giao cả tài khoản tối cao, nhưng với người dùng thông thường thì các chức năng hệ thống mang tính kỹ thuật không cần thiết với họ, nên tắt đi để tránh người ta "nghịch" lung tung.
