### ISSUE TITLE
Không hiển thị bình luận cũ khi cập nhật từ Nukeviet 3.4 lên bản Nukeviet 4 RC1

### ISSUE THREAD

**Issue by timacleo** [nukeviet/nukeviet#1819]
![1](https://cloud.githubusercontent.com/assets/17309352/13135513/caf56740-d643-11e5-95e3-8c18dcee98ff.png)

Sau khi update từ bản 3.4 lên 4 RC1, tôi không thấy hiển thị bình luận cũ. Như trong ảnh là bài viết có 1 bình luận, nhưng khi click vào bài viết thì k hiển thị được bình luận đó đâu.

**Comment by vuthao** [comment]
Báo lỗi của bạn không đúng khu vực, mình đã chuyển nó sang:
https://github.com/nukeviet/module_c34to40/issues/12
