### ISSUE TITLE
Chỉnh sửa hàm nv_info_die

### ISSUE THREAD

**Issue by thangbv** [nukeviet/nukeviet#1821]
Hàm này thông báo lỗi không truy cập được đường dẫn. Tuy nhiên không trả về bảng mã lỗi. Nó cần được trả về mã lỗi 404 kèm theo thông báo

**Comment by hongoctrien** [comment]
Hàm này em thấy đâu đại diện cho trang 404, nó chỉ là hàm tạo nội dung thông báo, lập trình chủ động sử dụng. Nếu muốn thì cũng cỏ thể thêm mã lỗi vào biến tiêu đề.
Còn nếu tạo trang báo lỗi thì người dùng tự khai báo đên trang thông báo lỗi, máy chủ chuyển đến đường dẫn tương ứng khi gặp lỗi.
Em nói thế không biết đúng ý anh không

**Comment by thangbv** [comment]
Nếu như nó không chỉ đại diện cho  lỗi 404 thì nó cũng phải có 1 mã lỗi được trả lại cho trình duyệt. Anh thấy hầu như các module (Trong đó có news) rất hay sử dụng hàm này để thông báo lỗi truy cập. Tuy nhiên nếu không thông báo mã lỗi nó sẽ hiểu mặc định là mã 200.
Vậy hàm này anh nghĩ sẽ nên có 1 tham số để truyền thêm mã lỗi nữa cho các module sử dụng tiện hơn.

**Comment by hongoctrien** [comment]
dạ em hiểu rồi. https://github.com/hongoctrien/nukeviet/commit/6309ec4c0a1eb8e7cdbffce80bf07c6eab1dbcfc
