### ISSUE TITLE
Không hiển thị danh sách tài khoản

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1828]
https://github.com/nukeviet/nukeviet/tree/9d482a8a1fb8ad9b62ddeb34b7398a0c4b3f67dd
Truy cập /admin/index.php?language=vi&nv=users không hiển thị danh sách tài khoản như trước
![image](https://cloud.githubusercontent.com/assets/6407361/13172335/2375978c-d72a-11e5-80cc-701a79352ad1.png)

**Comment by vuthao** [comment]
Xóa cache hoặc chọn lại cái sau em:
![untitled](https://cloud.githubusercontent.com/assets/2491500/13173186/d9aba966-d72e-11e5-9c55-f21623bdb839.png)

**Comment by hongoctrien** [comment]
Dạ, dc rồi :)
