### ISSUE TITLE
Lỗi step 6 cài trên hosting GLTEC

### ISSUE THREAD

**Issue by stormlove** [nukeviet/nukeviet#1829]
Cài đến bước 6 lỗi trắng trang
Cấu hình máy chủ
Phiên bản NukeViet	4.0.25, 4.0.26
Phiên bản PHP	5.4.28
Giao thức giữa máy chủ và PHP	Apache, apache2handler
Hệ điều hành máy chủ	LINUX
Phiên bản MySQL	5.5.36

**Comment by vuthao** [comment]
bạn tạo dùm 1 tài khoản để chúng tôi có thể cài, và kiểm tra lỗi nhé. Thông tin gửi qua email webmaster acòng nukeviet chấm vn

**Comment by vinhntgroup** [comment]
Mình cũng bị lỗi này đây :)

**Comment by vuthao** [comment]
Tạm thời các bạn có thể khắc phục như sau:
Mở file install\config.php Sửa  lại dòng:
```
$db_config['collation'] = '';//utf8_general_ci, utf8mb4_unicode_ci, utf8mb4_vietnamese_ci
```

Thành 
```
$db_config['collation'] = 'utf8_general_ci';//utf8_general_ci, utf8mb4_unicode_ci, utf8mb4_vietnamese_ci
```

Xóa tất cả các file /data/tmp/config_*.php

Sau đó cài lại từ bước 1

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/d67d48d0617688b46675cc7fdece2e7e2315a70c
