### ISSUE TITLE
Cài đặt Nukeviet 4 trên webserver Apache 8.1.0 bị lỗi

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1832]
Chào các bạn,

Mình cài đặt Nukeviet 4.0rc1 trên máy chủ web chạy AppServ 8.1.0 (PHP 5.6.18, MySQL 5.7.10). Khi cài đặt đến bước cấu hình cơ sở dữ liệu thì bị lỗi này nên không cài đặt tiếp được:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'virtual tinyint(1) NOT NULL DEFAULT '0', basename varchar(50) NOT NULL DEFAULT ' at line 6

Mong hướng dẫn xử lý lỗi này. Mình cám ơn.

https://nukeviet.vn/vi/forum/Cai-dat-Nukeviet-4-tren-webserver-Apache-8-1-0-bi-loi-t37424/

**Comment by vuthao** [comment]
Lại có thêm từ khóa mới trong phiên bản mysql là: virtual. Cái này để anh kiểm tra và thay thế cho @hongoctrien

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/b35c1b40a6d5070b80ef2126ae00ef752630731e
