### ISSUE TITLE
Không thể login vào Admin panel trên PHP version 5.5.22

### ISSUE THREAD

**Issue by hkvietnam** [nukeviet/nukeviet#1835]
Em install bản version 25, nhưng khi login vào thành Công, đến màn hình chờ để vào trang quản trị thì nó lại redirect ra ngoài trang login lại. 
CÓ ai bị giống em ko? 
 Em testing trên hosting với environment: 
Apache 2.4
Php: 5.5.22
Mysql: 5.5

PS: Em đã setting những folder cần thiết về 777 rồi.

**Comment by vuthao** [comment]
Cái lại mới bản NukeViet 4.0.27 xem sao bạn: https://github.com/nukeviet/nukeviet/archive/4.0.27.zip

Nếu vẫn còn lỗi gửi tài khoản hosting về email webmaster acòng nukeviet chấm vn để mình kiểm tra kỹ hơn.
