### ISSUE TITLE
Bổ sung chức năng xác thực 2 yếu tố cho phần đăng nhập trang quản trị

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1836]
Xác thực 2 yếu tố ngày càng trở lên cần thiết nhằm chống lại tình trạng ăn cắp mật khẩu đang ngày càng trở lên phổ biến: https://www.twilio.com/blog/2013/04/add-two-factor-authentication-to-your-website-with-google-authenticator-and-twilio-sms.html

Chức năng xác thực 2 yếu tố (two factor authentication) hiện được Google cung cấp miễn phí cho mọi website. 
- Thư viện code mẫu:
  - https://github.com/PHPGangsta/GoogleAuthenticator
  - https://github.com/chregu/GoogleAuthenticator.php
  - https://github.com/sonata-project/GoogleAuthenticator
- Phần mềm sinh mã sử dụng Google authenticator (sử dụng chung cho mọi website do Google hỗ trợ, hiện đã được hỗ trợ cho Gmail, Github, Dropbox, Evernote, Outlook...) cho phép người sử dụng tải miễn phí tại đây: 
  - Android: https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2
  - iOS: https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8

**Comment by vuthao** [comment]
@hoaquynhtim99 xem lại việc khi tắt chế độ này đi nhé. (Hiện tại tắt quá đơn giản: không hỏi bất cứ cái ghì). Theo mình cần tối thiểu hỏi lại mật khẩu. Xem xét thêm thằng google nó làm thế nào nhé.

**Comment by vuthao** [comment]
Module Users: cần có liên kết đến tính năng xác thực 2 bước.

**Comment by hoaquynhtim99** [comment]
Đã bổ sung việc xác nhận mật khẩu khi truy cập vào khu vực xác thực hai bước https://github.com/hoaquynhtim99/nukeviet/commit/e27e556697737071da54708c4e69c87cf0c8b6bd

**Comment by hoaquynhtim99** [comment]
Đã bổ sung liên kết đến tính năng xác thực hai bước https://github.com/hoaquynhtim99/nukeviet/commit/cb8f3a3e9258932deb7a9f19e9d8c573187b89e9

**Comment by ntnhut79** [comment]
Bật tính năng xác thực hai bước cả hai khu vực, thì khi đăng nhập yêu cầu xác thưc hai bước, nhập mã q-code, quét bằng Google authenticator thì báo là không nhận dạng được mã khóa, còn một chuỗi ký tự nhập thủ công, cũng không biết phải nhập thế nào????

**Comment by hoaquynhtim99** [comment]
@ntnhut79 Cảm ơn bạn, lỗi này đã được ghi nhận, đã sửa ở https://github.com/nukeviet/nukeviet/commit/5a7e71fcb3587ca5d4e095752eaa8f7b88cba37b và sẽ được cập nhật ở phiên bản chính thức
