### ISSUE TITLE
[Tag 4.0.27] Block - Lỗi unlink khi có block hết hạn

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1838]
Thiết lập 1 block, giả dụ là HTML của module page.
Thiết lập cho block hết hạn.
Sau đó dọn hệ thống và ra trang chủ.
Sinh lỗi : 
```
 Thông báo từ Hệ thống

Lỗi cảnh báo Lỗi cảnh báo: unlink(vi_asz-acm_acm_1c219f0c2ccc4a0d73215ef8c1f1f922.cache): No such file or directory in file /includes/core/user_functions.php on line 242
```
Xoá block đi thì hết.

**Comment by anhyeuviolet** [comment]
Chỉ có thể vào ACP mà xoá thôi chứ ngoài trang chủ ko thấy nó đâu.
Làm mó mẫm 2 hôm nay :cry:

**Comment by vuthao** [comment]
Mình đã fix phần xóa cache: https://github.com/nukeviet/nukeviet/commit/4b77e6acd53b3777aca6a108aefd38783ccc60ee

Chỉ có thể vào ACP mà xoá thôi chứ ngoài trang chủ ko thấy nó đâu.  --> Nguyên tắc khi xây dựng block đã như thế, chỉ có block hiệu lực mới hiển thị ra ngoài site

**Comment by anhyeuviolet** [comment]
Fix phần lỗi cache là được rồi anh :smile: 
Tại em ko thể hiểu lý do báo lỗi nên tìm rất là thê thảm :cry: 
Căn bản là vì ngoài trang chủ ko hiện nên ko biết cách để xoá nó. Chứ giờ ko báo lỗi nữa là ổn.
