### ISSUE TITLE
Lỗi block module block_newscenter khi update từ bản nukeviet 4.0.25 lên 4.0.27

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#1839]
Sau khi nâng cấp sẽ nhân được thông báo "Nên chú ý: Undefined index: length_othertitle in file /modules/news/blocks/module.block_newscenter.php on line 181"
Do thiếu đẩy vào csdl thông số cho block module

**Comment by vuthao** [comment]
Uống thuốc không đọc hướng dẫn sử dụng: 

    Nếu đang kích hoạt block_newscenter của module news, tiến hành xóa block và thêm lại.
