### ISSUE TITLE
Khi xóa block newscenter cập nhật lại thì lỗi

### ISSUE THREAD

**Issue by nguyengiakt** [nukeviet/nukeviet#1843]
update lên bản 4.0 27 Khi xóa block newscenter cập nhật lại thì lỗi
![a](https://cloud.githubusercontent.com/assets/2918834/13282464/b89e68e4-db1b-11e5-8cf9-9f6e7d5420be.jpg)

**Comment by nguyengiakt** [comment]
mình dời về bản 4.0 26 thì phát hiện lỗi này cũng có trước giờ ko thêm nên ko để ý

**Comment by nguyengiakt** [comment]
xóa block đi thì ok, những block cũ thì vẫn hoạt động bình thường, còn thêm những block trong news đều bị lỗi

**Comment by hoaquynhtim99** [comment]
Mình check không thấy lỗi, ban thử debug lỗi bằng cách mở includes/mainfile.php xóa 2 đoạn sau

```php
error_reporting(0);
```

```php
// Ket noi voi class Error_handler
$ErrorHandler = new NukeViet\Core\Error($global_config);
set_error_handler(array(
    &$ErrorHandler,
    'error_handler'
));
```

rồi xem thông báo lỗi là gì

**Comment by nguyengiakt** [comment]
nó ko ra lỗi bạn, cứ thêm block newscenter với headline là server error

**Comment by hoaquynhtim99** [comment]
Hiện tại mình check không thấy lỗi này. Khả năng bạn dùng các block không từ bản mặc định

**Comment by nguyengiakt** [comment]
ko bạn, mình đang test nhiều cái. cơ bản là ok, mình nghĩ do mình ko đặt mấy thẻ div clear nên nó đụng block sao nó bị lỗi.
