### ISSUE TITLE
Lỗi sắp xếp trong các nhóm tin

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#1844]
Khi vào phần "Các nhóm tin" của module news thì có hiện tượng sắp xếp không đúng như hình
![untitled-1](https://cloud.githubusercontent.com/assets/6928431/13292409/38de1112-db4e-11e5-81de-6f40566909a8.jpg)

**Comment by hoaquynhtim99** [comment]
Lỗi này do dữ liệu mẫu bị sai, đã sửa lại https://github.com/hoaquynhtim99/nukeviet/commit/31d820da3c74487b5c0c105034c421d43c976728
