### ISSUE TITLE
Thông báo không đúng trạng thái bài viết

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1845]
NukeViet 4.0.27, Module News, bài viết đã cho hết hạn nhưng khi ra ngoài site (dưới tư cách của god admin) thì hệ thống lại báo:

>  Chú ý: Bài viết này chưa được xuất bản, chỉ có những người có quyền thao tác mới có thể xem được nội dung.

**Comment by hoaquynhtim99** [comment]
Em thấy nó cũng đâu đến mức không hợp lý lắm, đơn giản là câu thông báo chú ý vậy được rồi. Vì đằng nào admin cũng đã biết trước trạng thái của bài viết trước khi có thể ấn vào link rồi

**Comment by thehung** [comment]
Quan trọng là chính xác. Vì rất có thể sau này có nhiều trạng thái khác nhau. Nhiều người qản trị khác nhau,  nếu ko chính xác có thể gây nên những hiểu nhầm.
