### ISSUE TITLE
Đề xuất các gói cập nhật 

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1847]
Các gói cập nhật nên có các bước kiểm tra truy vấn xem đã tồn tại hay chưa. Nếu không dễ rơi vào tình trạng lỗi mà không có thông báo tới người dùng nếu việc update xảy ra lỗi

**Comment by hoaquynhtim99** [comment]
Cái này do chính gói cập nhật đó giải quyết thông qua việc sử dụng 

```php
try {
} catch () {
}
```

để trả về status. Về hệ thống update đã có cơ chế lưu lại tiến trình đã thành công hay chưa thành công tới bước nào để lần chạy sau sẽ không thực hiện lại nữa.
