### ISSUE TITLE
ảnh đại diện

### ISSUE THREAD

**Issue by vinhntgroup** [nukeviet/nukeviet#1848]
Ở phiên bản mobile không thể thêm ảnh đại diện cá nhân được.
Phiên bản NukeViet: NukeViet 4.0.27
Môi trường thử Nghiệm: Hosting
Hệ điều hành: (IOS 9.2.1)
Trình duyệt web: (Safari)

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/abaf61be6c9d4b1c0d2b04cb70b7a806b825f5e1
