### ISSUE TITLE
Lỗi không bình luận được khi truy cập bằng điện thoại

### ISSUE THREAD

**Issue by timacleo** [nukeviet/nukeviet#1849]
Tôi nâng cấp từ bản 3.4 lên bản 4RC1, sau đó nâng cấp lên 4RC2, sau khi truy cập website bằng điện thoại thì không thể bình luận được, mặc dù đã nhập đầy đủ thông tin như tên, email, mã số, nhưng click vào gửi thì không được.

**Comment by hoaquynhtim99** [comment]
Hiện tại lỗi này đã được fix
