### ISSUE TITLE
Lỗi cảnh báo: gzinflate(): data error in file /vendor/vinades/nukeviet/Http/Encoding.php

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1851]
Lỗi cảnh báo: gzinflate(): data error in file /vendor/vinades/nukeviet/Http/Encoding.php on line 41

**Comment by thehung** [comment]
Lỗi xuất hiện khi nào? Ở đâu? Phiên bản và môi trường nào @dangdinhtu2014 ?

**Comment by hoaquynhtim99** [comment]
Cái này xuất hiện khi vào phần ứng dụng có request tới store, đây chỉ là cảnh cáo và cũng chưa có cách giải quyết

**Comment by hoaquynhtim99** [comment]
Lỗi này đã được ẩn không thống báo với người quản trị, vẫn savelog theo commit này https://github.com/hoaquynhtim99/nukeviet/commit/fcaef47c1abebd0dfcc2cf8fa1a6ffd858e98f31
