### ISSUE TITLE
Tổng hợp góp ý về nukeviet

### ISSUE THREAD

**Issue by hoangvantruong92** [nukeviet/nukeviet#1852]
Xin chào anh em phát triển của nukeviet.
Trước hết xin cám ơn mọi người đã chung tay phát triển nukeviet đến ngày nay.
Thứ hai là mình xin góp ý một số vấn đề trong phát triên NV tiếp theo:
+ Sửa đổi cấu trúc cơ sở dữ liệu một chút, sao cho khi mọi người di chuyển bài viết và chuyên mục chỉ cần thêm dữ liệu vào bảng category và new. Thống nhất sao cho tất cả các site cũng chỉ có số lượng bảng cố định và giống nhau, chứ bây giờ mỗi module 1 bảng thì hơi nhiều.
+ Cải thiện cấu trúc nukeviet, nên tách giữa giao diện và xử lý một cách rạch ròi hơn. Ai phát triển giao diện cứ phát triển, ai làm chức năng cứ làm.

**Comment by anhyeuviolet** [comment]
Thực ra mình thấy ý mà tách giao diện với xử lý thì NV vẫn đang như vậy mà. Gói theme riêng đó thôi.
Còn vụ module có bao nhiêu bảng thì lại là vả vấn đề. Nó là chuyện của người viết module nữa chứ đâu chỉ mình NV.
Mà gom cả nùi vào 1 bảng wp_options của Wordpress chắc gì đã tốt. :smile:

**Comment by thehung** [comment]
Các góp ý về việc này các bạn tạo topic trên forum để tiện thảo luận nhé. Mình tạm thời đóng chủ đề này lại.
