### ISSUE TITLE
Lỗi Bad request 400 in google webmaster tool

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1853]
Mình kiểm tra trên google webmaster tool thì thấy xuất hiện lỗi này.

Không biết có bị hack không? tìm trên site thì không thấy file nào tương tự

![bad request url](https://cloud.githubusercontent.com/assets/6806295/13399415/c320c546-df35-11e5-9c86-97d648ac4536.PNG)

![bad request all](https://cloud.githubusercontent.com/assets/6806295/13399432/d8d22d26-df35-11e5-9faa-e014f983d2cd.PNG)

**Comment by anhyeuviolet** [comment]
Vậy link đó bạn có vào được ko ?

**Comment by thehung** [comment]
Anh @phongaz copi các link đó lên đây nhé.
Ngoài ra anh kiểm tra xem các link đó xuất hiện ở đâu, tại sao Google lại crawl nó được nhỉ?

**Comment by phongaz** [comment]
[aneedz-com_20160301T154613Z_CrawlErrors.xlsx](https://github.com/nukeviet/nukeviet/files/153054/aneedz-com_20160301T154613Z_CrawlErrors.xlsx)

Đây tất cả các lỗi từ khi nâng cấp lên 4.0
Các bác xem giúp nhé

**Comment by thehung** [comment]
Cái này là lỗi dẫn đến link không tồn tại, có thể xuất phát do nhiều nguyên nhân: link trong bài đăng không còn tồn tại, link lỗi do nâng cấp lên phiên bản mới đường link thay đổi mà việc nâng cấp không đảm bảo chuyển từ ink cũ sang được, lỗi do code tạo ra đường link tương đối bị sai...
Muốn biết chính xác thì anh @phongaz vào Google webmaster tool kiểm tra xem các link đó xuất hiện từ trang nào rồi tìm nguyên nhân để sửa.

**Comment by phongaz** [comment]
Ngoài những lỗi 404 từ module ảo tin-hoc do mình chuyển lại module news và module onlinetest không dùng nữa nên các link đó không còn tồn tại nữa. 

Còn các link sau có ký tự % kia thì ở đâu ra không biết nữa, và mình cũng chưa bao giờ tạo bài viết có dạng link như thế

**Comment by anhyeuviolet** [comment]
Hiện tại, em chính thức đã dính lỗi này......

**Comment by phongaz** [comment]
Lỗi này đã tăng lên gấp đôi rồi, và đã có 2 trang của mình đã bị lôi này
