### ISSUE TITLE
Lỗi bình luận trên giao diện mobile

### ISSUE THREAD

**Issue by sanvu88** [nukeviet/nukeviet#1857]
- Không gửi được bình luận trên giao diện điện thoại. Bấm vào nút bình luận không có hiện tượng gì.
- Thông tin máy chủ:

1. Server version: Apache/2.2.15
2. Php version: PHP 5.6.19 (cli)
3. Mysql version: 5.7.11
4. phpMyAdmin version: 4.5.5.1
5. PHP extension: mysqli
6. Disable_functions: apache_child_terminate,apache_get_modules,apache_get_version,apache_getenv,apache_note,apache_setenv,virtual,mb_send_mail,link,chgrp,leak,syslog,openlog,mysql_list_dbs,ini_restore,symlink,escapeshellarg,escapeshellcmd,ini_alter,dl,exec,passthru,parse_ini_file,pcntl_exec,pfsockopen,popen,posix_kill,posix_mkfifo,posix_setuid,proc_close,proc_open,proc_terminate,shell_exec,system,leak,posix_setpgid,posix_setsid,proc_get_status,proc_nice,show_source

- Phiên bản Nukeviet: 4.0.27
- Môi trường thử Nghiệm: Localhost / vmware
- Hệ điều hành: Centos 6.7
- Giao diện web: Mobile Default
- Trình duyệt: Chrome, firefox

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/5a36d230671df3f9d38a9146a11e9cb3f5748639

**Comment by vuthao** [comment]
Dũng kiểm tra lại nhé, chứ nếu không có js ở giao diện nó sẽ gọi ở giao diện mặc định mà
file /includes/core/user_functions.php dòng 623
```php
// module js
    if (file_exists(NV_ROOTDIR . '/themes/' . $module_info['template'] . '/js/' . $module_file . '.js')) {
        $return[] = array( 'ext' => 1, 'content' => NV_BASE_SITEURL . 'themes/' . $module_info['template'] . '/js/' . $module_file . '.js' );
    } elseif (file_exists(NV_ROOTDIR . '/themes/default/js/' . $module_file . '.js')) {
        $return[] = array( 'ext' => 1, 'content' => NV_BASE_SITEURL . 'themes/default/js/' . $module_file . '.js' );
    }
```

**Comment by hoaquynhtim99** [comment]
@vuthao cái đó áp dụng cho module là đúng rồi ành còn module comment do được gọi include từ mỗi module khác nhau nên không lấy js từ đoạn code đó mà xử lý riêng qua hàm ```nv_theme_comment_module``` thế nên hoặc là sửa lại đoạn 

```php
        // Check call module js file
        if (file_exists(NV_ROOTDIR . '/themes/' . $template . '/js/comment.js')) {
            $xtpl->parse('main.header.jsfile');
        }

        // Check call module css file
        if (file_exists(NV_ROOTDIR . '/themes/' . $template . '/css/comment.css')) {
            $xtpl->parse('main.header.cssfile');
        }
```
hoặc là theo nguyên tắc có giao diện thì có js

**Comment by vuthao** [comment]
@hoaquynhtim99 thế sửa lại cái nv_theme_comment_module để nó giống các chỗ khác, chứ không nên copy file thừa.

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/c1b1d23ca596988243a48d1725de365a4e166ab3
