### ISSUE TITLE
Lộ địa chỉ trang quản trị khi admin trả lời email được gửi qua phần liên hệ

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1858]
NukeViet 4.0 RC2

Khi user gửi liên hệ qua module contact, một email được gửi tới admin qua email kèm theo đường link đến trang quản trị. Khi admin trả lời thư này sẽ khiến đường link tới trang quản trị bị lộ.

Ngoài ra đường link này cũng bị sai (chỉ có đường dẫn tương đối) 

=> Nên bỏ đường link này đi.

**Comment by hoaquynhtim99** [comment]
Đã sửa https://github.com/hoaquynhtim99/nukeviet/commit/71f8c5e89e5baf7ad1e952847ab4f1bf6367b19a
