### ISSUE TITLE
Không hiển thị ảnh quảng cáo

### ISSUE THREAD

**Issue by sanvu88** [nukeviet/nukeviet#1859]
Khi thêm quảng cáo thì không hiển thị được hình ảnh mà là một khoảng trắng. Ngay cả khi truy cập vào link ảnh trực tiếp trong thư mục /uploads/banners thì cũng không xem được ảnh trong thư mục này (Trắng tinh), trong khi đó ảnh ở các thư mục khác thì vẫn hiển thị bình thường.
Ở phần footer có mục quảng cáo, khi click vào thì sẽ ra link dạng domain.com/banners và không hiển thị gì cả. Khi mình tạo thêm folder banners ngang hàng index và tạo file index trong đó thì cũng không truy cập được.

**Thông tin server:**

Server version: Apache/2.2.15
Php version: PHP 5.6.19 (cli)
Mysql version: 5.7.11
phpMyAdmin version: 4.5.5.1
OS: Centos 6.7
**
Thông tin thêm**
Giao diện web: default
Trình duyệt: Chrome, firefox
NukeViet phiên bản 4.0.27

**Comment by vuthao** [comment]
Bạn cho xem demo trang bị lỗi ?
