### ISSUE TITLE
Bộ gõ trong nukeviet RC27 không cho phép chèn ảnh

### ISSUE THREAD

**Issue by thucvinh** [nukeviet/nukeviet#1860]
Bộ gõ trong nukeviet RC2 không cho phép chèn ảnh?

Môi trường thử nghiệm: Local host, bản mơi  nhất RC2

**Comment by thehung** [comment]
Bạn cung cấp ảnh chụp và mô tả ro hơn về cách bạn chèn mà không được nhé.
Ngoài ra, vì môi trường như trình duyệt cũng ảnh hưởng nhiều đến web, bạn cũng cần cung cấp rõ thông số môi trường thử nghiệm như hướng dẫn ở đây: https://github.com/nukeviet/nukeviet/blob/develop/CONTRIBUTING.md
Vì không ai gặp lỗi này, tôi tạm thời đóng issues này lại cho đến khi có thông tin chi tiết hơn từ bạn.
