### ISSUE TITLE
Lỗi encoding khi viết bài mới trong module News

### ISSUE THREAD

**Issue by thai6070** [nukeviet/nukeviet#1861]
Phiên bản NukeViet: NukeViet 4.0.27 RC2
Môi trường thử Nghiệm: Localhost
Hệ điều hành: Windows 7
Trình duyệt web: Mozilla Firefox 44.0.2
Máy chủ web: XAMPP

Tài khoản Admin thì viết bài được, nhưng thành viên thì không thể viết bài, dù đã cấu hình cho thành viên viết/xóa rồi.

**Comment by hoaquynhtim99** [comment]
Hiện tại mình check không thấy lỗi, bạn mô tả kỹ hơn nhé
