### ISSUE TITLE
Cần gửi kèm usename trong email "Hướng dẫn khôi phục mật khẩu"

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1862]
Email Hướng dẫn khôi phục mật khẩu hiện giờ chỉ gửi mật khẩu mà không có username, trường hợp người sử dụng quên tên đăng nhập thì không có cách gì tìm lại được => Cần bổ sung tên đăng nhập trong email Hướng dẫn khôi phục mật khẩu.

**Comment by phongaz** [comment]
Chế độ đăng nhập bây giờ có cả email mà nhỉ, Trên ô đăng nhập chỉ cần sữa text placeholder thành: Tên đăng nhập hoặc email là người dùng có thể đăng nhập bằng email thay cho username rồi.

Mà nếu quên cả email thì bó tay rồi.
