### ISSUE TITLE
Lỗi link thông báo trong email "Request to join group"

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1863]
NukeViet 4.0 RC2
Email "Request to join group" (tiếng Anh) thông báo có thành viên mới đăng ký nhưng click vào link bị trỏ về module users. Truy cập link http://....com/en/users/groups/ cũng không được. Chỉ truy cập được đối với trang tiếng Anh.

**Comment by hoaquynhtim99** [comment]
Anh check lại xem em thấy bản mới không còn lỗi nữa
