### ISSUE TITLE
Không chuyển sang giao diện chế độ hiển thị tự động

### ISSUE THREAD

**Issue by nguyengiakt** [nukeviet/nukeviet#1865]
Giao diện mặc định cho Mobile chọn giao diện hiển thị cho pc, dọn dẹp hệ thống, kiểm tra nó vẫn chưa tự động xác lập chế độ hiển thị tự động là default

**Comment by hoaquynhtim99** [comment]
Ở đây chữ mặc định có nghĩa là nếu không có tùy chỉnh gì khác thì nó sẽ mang giá trị đó, phần giao diện ngoài site các cách hiển thị được lưu ở máy client nên muốn thay đổi, client phải xóa cookie.

Vì site cho phép chuyển đổi giao diện tùy ý ngừoi dùng nên vậy, nếu cần cố định giao diện không cho người dùng tự ý đổi cần tắt mục **Cho phép chuyển đổi giao diện mobile, desktop** tại trang cấu hình site

**Comment by nguyengiakt** [comment]
đã xử xong rồi bạn, do mình ko cho mặc định trong module nữa
