### ISSUE TITLE
Lỗi Block Menu Bootstrap

### ISSUE THREAD

**Issue by hoangloctn** [nukeviet/nukeviet#1866]
Có bao nhiêu menu, sub menu bị hiện ra hết.

![zalo_screenshot_11_3_2016_1842185](https://cloud.githubusercontent.com/assets/7695226/13701224/020f8f0e-e7b9-11e5-8060-14a21a6d10d8.png)

**Comment by anhyeuviolet** [comment]
Có dùng chung với JS nào không bạn ?

**Comment by hoangloctn** [comment]
Cài xog thì nó bị rồi. Chưa cài thêm gì.

**Comment by vuthao** [comment]
@hoangloctn kiểm tra lại giao diện mặc định có bị lỗi không nhé. Nếu bạn đã chỉnh sửa nó thì phải tự tìm cách fix thôi.
Mình kiểm tra giao diện mặc định không bị lỗi.
