### ISSUE TITLE
Lỗi cơ chế xử lý javascript của Omtimizer Class

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#1868]
Hiện tại Omtimizer Class đang cắt tất cả javascript để cho về phía cuối chân trang tuy nhiên việc này lại nảy sinh vấn đề đối với các site chèn quảng cáo từ bên thứ 3:

Thông thường hầu như các code quảng cáo được chèn theo kiểu gọi ra 1 table, div, tiếp theo đó gọi script rồi xuất kết quả ngay cái dòng gọi script đó

Khi chèn vào NukeViet, script bị đưa về cuối site dẫn đến việc quảng cáo nhảy hết về phía cuối trang.

**Comment by vuthao** [comment]
Cái này chắc các site quảng cáo tự xử thôi, chứ giờ sửa cũng không biết thế nào.

Tạm thời site nào bị vấn đề này xử lý như sau:

sửa file includes/functions.php
Tìm đến đoạn
```php
    $optimizer = new NukeViet\Core\Optimizer($buffer,  NV_BASE_SITEURL);
    return $optimizer->process();
```

Thay bằng
```php
    return $buffer
```

**Comment by hoaquynhtim99** [comment]
Tạm thời để không mất đi các phần tối ưu cần thiết em đề xuất sửa như sau
Mở file vendor/vinades/nukeviet/Core/Optimizer.php

Xóa

```php
        $jsRegex = "/<\s*\bscript\b[^>]*>(.*?)<\s*\/\s*script\s*>/is";
        if (preg_match_all($jsRegex, $this->_content, $jsMatches)) {
            $this->_jsMatches = $jsMatches[0];
            $this->_content = preg_replace_callback($jsRegex, array(
                $this,
                'jsCallback'
            ), $this->_content);
        }
```

Tìm 

```php
        if (! empty($meta)) {
            $head .= implode($this->eol, $meta) . $this->eol;
        }
```

Thêm lên trên

```php
        $head = '<script src="' . $this->base_siteurl . NV_ASSETS_DIR . '/js/jquery/jquery.min.js"></script>' . $this->eol;
```
 
Xóa

```php
            $_jsAfter = '<script src="' . $this->base_siteurl . NV_ASSETS_DIR . '/js/jquery/jquery.min.js"></script>' . $this->eol . $_jsAfter;
            $this->_content = preg_replace('/\s*<\/body>/', $this->eol . $_jsAfter . $this->eol . '</body>', $this->_content, 1);
```

**Comment by hoaquynhtim99** [comment]
Vấn nề này đã giải quyết tại  https://github.com/hoaquynhtim99/nukeviet/commit/ee5853f90e871cbedfeb495be626d31308d03cd4

Xem hướng dẫn https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.0.30#l%C6%B0u-%C3%BD-%C4%91%E1%BB%95i-v%E1%BB%9Bi-vi%E1%BB%87c-ch%C3%A8n-qu%E1%BA%A3ng-c%C3%A1o
