### ISSUE TITLE
Lỗi trong admin của module user

### ISSUE THREAD

**Issue by xuanluc73** [nukeviet/nukeviet#1869]
Phần thành viên đợi kích hoạt bị lỗi sau, đội code xem hình để fix lỗi này nhé.

Phần họ tên chỉ lấy mỗi tên, giá trị của email bị rỗng và đẩy sang phần ngày đăng ký, các phần còn lại bị đẩy ra cột sau:
![loi nukeviet 4 0 27](https://cloud.githubusercontent.com/assets/951683/13777942/979382f4-eae5-11e5-99ae-027ef84e18b7.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/7095280c19ea0626947ae799ad54b47133b3ae3d

Tuy nhiên có lỗi liên quan đến việc không lick được các link trên header của bảng, @hoaquynhtim99  đang xem vấn đề này.
