### ISSUE TITLE
Module news: lỗi tìm kiếm với ký tự đặc biệt

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1872]
> Phiên bản PHP 	5.6.19
Giao thức giữa máy chủ và PHP 	Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.19, apache2handler
Hệ điều hành máy chủ 	WINDOWS NT
Phiên bản Database 	mysql 5.5.5-10.1.10-MariaDB

domain/news/search/
VD tìm với cụm từ **19/KH-BGDĐT** (có trong nội dung) thì không tìm thấy.

**Comment by anhyeuviolet** [comment]
Mới fix bên cái laws xong. =_= 
Cái này thay cách escape ký tự đi mới tìm được.

**Comment by vuthao** [comment]
Mình đã kiểm tra lại nhưng không đúng như chủ thớt thông báo.
![untitled](https://cloud.githubusercontent.com/assets/2491500/14070509/b49d9c0e-f4d1-11e5-8ac2-fb72a7db8b04.png)

**Comment by hongoctrien** [comment]
domain/news/search/
Tìm kiếm ở module tin tức ý anh, chứ không phải seek

**Comment by anhyeuviolet** [comment]
Anh thử đặt cái nội dung như trên vào tiêu đề xem tìm có được không. Trong hometext và bodytext thì vẫn tìm được, title thì ko.
