### ISSUE TITLE
[Core] statimg lỗi đường dẫn ảnh

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1873]
Log ghi lại thì lỗi dòng 26
```
$image = ImageCreateFromPNG(NV_ROOTDIR . '/images/banner88x31.png');
```

Hình như sai đường dẫn ảnh, vì ảnh đó vào assets rồi mà.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/eac11cf377f6bbc4ab85834701ca252ce02e28fd
