### ISSUE TITLE
NukeViet 4 dùng chung các cột 

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#1875]
NukeViet 4 có một cái bất tiện là dùng chung các cột (col-md) cho các vị trí khác nhau.
Cái này nên tách ra từng nhóm cột: Top-col, Mid-col, Rig-col, Lef-col, Bot-col, Fot-col sẽ thuận tiện hơn.

**Comment by hoangloctn** [comment]
cái này quy định của bootstrap mà

**Comment by anhyeuviolet** [comment]
Cái này của CSS Framework, mà nó cũng có gì mà bất hợp lý đâu.

**Comment by vuthao** [comment]
Cái này chắc @truongemcom tìm hiểu thêm về bootstrap nhé.
bootstrap  dùng trong NukeViet được dùng nguyên http://getbootstrap.com/ có tùy chỉnh thêm từ 12 cột thành 24 cột (getbootstrap cho phép làm việc này). để việc chia độ rộng các block trên màn hình máy tính thuận tiện hơn.

**Comment by truongemcom** [comment]
Các chú hiểu thế nào mà lại nói vậy? Các chú có hiểu từ "dùng chung" hay không? Mặc định của bootstrap liên quan gì? Các chú có thấy các cột ở footer dùng chung với cột ở module news không? Khi chỉnh sửa độ rộng của cột ở footer thì nó ảnh hưởng đến các vị trí dùng chung khác. Vì vậy nên tách ra mỗi vị trí dùng một cột riêng biệt thôi, ko nên dùng chung như thế.

**Comment by hoangloctn** [comment]
bác nghiên cứu bootstrap đi đã nhé.
