### ISSUE TITLE
[Hỏi], tài khoản admin khi đăng nhập sai nhiều lần 

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1876]
Khi admin đăng nhập nhiều lần không thành công sau đó hệ thống không cho phép đăng nhập nữa,

Dùng god admin kiểm tra thì không thấy trạng thái bị khóa gì cả.
Nhưng hệ thống không cho đăng nhập quyền admin của user đó.
Mặc dù xóa tài khoản quản trị (giữ tài khoản thành viên) sau đó bổ nhiệm lại chức năng quản trị cũng không cho đăng nhập

Vậy god admin muốn gỡ trạng thái đó thì vào đâu để xử lý

**Comment by thehung** [comment]
Anh sử dụng phiên bản NukeViet nào? 
NukeViet cài mới hay nâng cấp?

**Comment by phongaz** [comment]
Mình sử dụng phiên bản 4.0.24 (bản Vinades dùng để phát triển module elearning cho mình ý

**Comment by thehung** [comment]
Vậy anh liên hệ đội chăm sóc khách hàng bên VINADES để được trợ giúp kiểm tra nhé. Nếu đây là lỗi chung của NukeViet thì sẽ được đội chăm sóc khách hàng đưa sang cho nhóm phát triển NukeViet.

**Comment by htuyen1994** [comment]
Anh truy cập vào bằng tài khoản admin tối cao, vào cấu hình chung, sửa chỗ chế độ đóng cửa site, hiện tại chắc site để chỉ admin tối cao đăng nhập đấy ạ.

**Comment by vuthao** [comment]
Xác nhận hiện tại NukeViet 4 chưa có tính năng chống đăng nhập nhiều lần như bản 2

**Comment by thehung** [comment]
Là như thế nào nhỉ anh @vuthao, theo thông tin anh @phongaz cung cấp thì hình như nó là sự cố khác (tài khoản admin bị khóa sau khi đăng nhập nhiều lần không thành công).

**Comment by xuanluc73** [comment]
Xem lại xem có bị khóa IP không?

**Comment by vuthao** [comment]
Site của anh Phong là do chế độ đóng của site.

Còn hiện tại chưa có tính năng bảo vệ nếu đăng nhập thất bại nhiều sẽ khóa IP lại trong 1 khoảng thời gian.

Tạm thời các site nên bập capchar để bảo vệ.

**Comment by vuthao** [comment]
@hoaquynhtim99 em xử lý dùm anh cái này như sau:
- Khi login (cả admin, ngoài site). Nếu không thành công ghi logo lại theo IP. Nếu sai 5 lần (Cấu hình vào file  constants.php) trong 5 phút thì không cho đăng nhập từ IP đó nữa trong  24h (Cấu hình thông số này vào file constants.php)

**Comment by hoaquynhtim99** [comment]
Added: https://github.com/hoaquynhtim99/nukeviet/commit/29b60f8bb27f3c06eb8a572f043b5dae85fec2cb
