### ISSUE TITLE
Module upload: Lỗi chức năng "Cập nhật lại" ảnh minh họa

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#1882]
Trường hợp muốn tạo lại ảnh minh họa của news với dung lượng lớn (đang test với 6GB) thì khi click vào icon refresh, hệ thống vẫn tiến hành tạo nhưng được một lúc thì phát sinh lỗi do quá thời gian xử lý.

![selection_474](https://cloud.githubusercontent.com/assets/6407361/14138179/fa0615c6-f695-11e5-815d-79c98d368166.png)

**Comment by vuthao** [comment]
Hiện tại mình đã thêm  set_time_limit  khi xử lý việc này
https://github.com/vuthao/nukeviet/commit/2597b8c179ab929c166f184f47d6fe9373fc5a65

Nhưng việc này sẽ không đảm bảo chạy trên mợi server. Nếu phải tạo lại nhiều ảnh minh họa thì các bạn cần viết tool chuyên biệt, mối lần chỉ xử lý khoảng 50 ảnh
