### ISSUE TITLE
[Thắc mắc] Hình như chẩn đoán site không cập nhật được Bing indexed

### ISSUE THREAD

**Issue by xuanluc73** [nukeviet/nukeviet#1884]
Đội code cho ý kiến nhé, có phải là bing index không được cập nhật không?

Mình thấy Bing index của Seoquake là 468 còn của Nukeviet thì bằng 0, cái này mình không rành nên không biết có phải là lỗi không?
![quan tri nukeviet](https://cloud.githubusercontent.com/assets/951683/14370592/c738b73c-fd59-11e5-903d-059383c5a8c7.png)
![bing index](https://cloud.githubusercontent.com/assets/951683/14370594/ccd2d77c-fd59-11e5-8235-123250b4083b.png)

**Comment by anhyeuviolet** [comment]
Em cũng bị tương tự. Mà công cụ này, trên web em ngừng từ hôm 04/04 là hết cập nhật rồi :dancer:

**Comment by thehung** [comment]
Chắc API sử dụng cho việc cập nhật số liệu lại bị chặn.

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/4d8e4c5899e8ac67e64c490d7f2473d2b042e8b6

Hiện tại việc check backlink tư google, alexa, bing là không còn khả dụng nữa vì tool đó đã bị remove ra khỏi trình tìm kiếm mặc định của nó và đưa vào webmaster tool, anh @vuthao xem thế nào về việc xóa 3 cột đó đi. Hoặc có thể lấy từ một số trang khác, tuy nhiên các nguồn đó là "Không chính thức"

**Comment by anhyeuviolet** [comment]
Công cụ Google PageRank cũng đã hỏng rồi. :D bỏ đi ạ.

**Comment by thehung** [comment]
cái thống kê số lượng backlink google, alexa, bing nếu nó không hỗ trợ nữa thì nên bỏ đi. Không nên sử dụng các nguồn không chính thức.

**Comment by vuthao** [comment]
@anhtunguyen bỏ cả chức năng chẩn đoán site đi nhé.

**Comment by anhtunguyen** [comment]
OK.
Nó bây giờ vô tác dụng rồi.

С уважением,
Тимур Нгуен

---------------------------
TIMUR TRAVEL Co., LTD
«С нами в солнечный Вьетнам!»
Hotline: +84 903 777 637
Mobile, Viber, WhatsApp: +84 933 777 637
Skype: timurtravelcom
ICQ: 213999

СЛУЖБА ЗАКАЗА ЭКСКУРСИЙ:
E-mail: contact@timurtravel.net
Website: http://timurtravel.net

СЛУЖБА ЗАКАЗА ТРАНСФЕРА:
E-mail: contact@vietnamtransfer.ru
Website: http://vietnamtransfer.ru
22 апр. 2016 г. 16:22 пользователь "Vu Thao" <notifications@github.com>
написал:

**Comment by vuthao** [comment]
@hoaquynhtim99 xem tách tính này thành plugin của module (Không rõ có thể hỏi Triển dùm anh nhé). Sau đó xóa tính năng này ở bản NukeViet mặc định nhé.

**Comment by hoaquynhtim99** [comment]
Đã tách
