### ISSUE TITLE
Thông báo lỗi không đúng

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1886]
Khi đăng ký thành viên, nhập mật khẩu 6 ký tự bằng chữ thường, hệ thống thông báo không đúng: 
> Mật khẩu đăng nhập chwua được khai báo!

Test tại: https://nukeviet.net/users/register/

**Comment by vuthao** [comment]
Lỗi xẩy ra như sau:
Quy định tài khoản hoặc mật khẩu cần nhập 6 ký tự, nếu nhập 2 ký tự nó báo chưa khai báo.

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/346df538eda8c59a2305886ef05e941a65648a16
