### ISSUE TITLE
Chức năng random trong module banner

### ISSUE THREAD

**Issue by nguyengiakt** [nukeviet/nukeviet#1888]
Chức năng random hiện tại là random lên xuống trong 1 hàng, giờ mình muốn random trong 1 vị trí duy nhất, cứ refesh là đổi thì mình có thể code ở đâu?

**Comment by nguyengiakt** [comment]
ok mình đã xử xong, thêm mấy cái này cho các bạn muốn random div
<script>
$(function(){
    var random = Math.floor(Math.random() * $('.item').length);
    $('.item').eq(random).show();
});
</script>
<style>
.item{
    display: none;
}
</style>

**Comment by nguyengiakt** [comment]
`<script>
$(function(){
    var random = Math.floor(Math.random() * $('.item').length);
    $('.item').eq(random).show();
});
</script>
<style>
.item{
    display: none;
}
</style>`

**Comment by vuthao** [comment]
Hiện tại NukeViet đang lập trình cho việc hiển thị tất cả các banner.
Nếu theo ý của @nguyengiakt có thể phát triển thêm như sau:

Khi chọn Kiểu thể hiện: sẽ có thể chọn
- Hiển thị tất cả tuần tự (Như cũ).
- Hiển thị tất cả ngẫu nhiên (Như cũ).
- Hiện thị N banner, F5 mới thay đổi.
- Hiện thị N banner, tự động thay đổi sau A giây

**Comment by nguyengiakt** [comment]
Idea này rất hay. Hiện thị N banner, tự động thay đổi sau A giây. Code thôi

**Comment by hoaquynhtim99** [comment]
Hiện tại đã phát triển để có thể hiển thị:
- Tất cả banner được hiển thị với tần suất 100% và vị trí sắp xếp ngẫu nhiên
- Các banner được hiển thị lần lượt với tần suất chia đều
- Các banner được hiển thị với tần suất 100% và vị trí tuần tự
