### ISSUE TITLE
Sai vị trí báo lỗi khi đăng ký thành viên

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1889]
![sai-vi-tri](https://cloud.githubusercontent.com/assets/6290970/14479652/128cc9ea-014b-11e6-952f-fdc1a4c05473.PNG)
Demo : https://nukeviet.net/users/register/

**Comment by vuthao** [comment]
Lỗi này chỉ xẩy ra trên site https://nukeviet.net/users/register/ do site này đã sửa lại.
Bạn nhập đầy đủ thong tin sẽ không bị lỗi.
