### ISSUE TITLE
[DB] Cơ chế xuất file DB tự sao lưu dễ bị lỗi khi Import

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1891]
XAMPP 1.8.3
NV 4.0.27

Khi dùng DB trong mục dump backups, DB có kèm dòng sau
```
SET SESSION `character_set_client`='utf8';
SET SESSION `character_set_results`='utf8';
SET SESSION `character_set_connection`='utf8';
SET SESSION `collation_connection`='utf8mb4_unicode_ci';
SET NAMES 'utf8';
ALTER DATABASE DEFAULT CHARACTER SET `utf8` COLLATE `utf8mb4_unicode_ci`;
```
Các dòng này thường sinh lỗi khi import DB vào SQL.
```
Error

SQL query:

ALTER DATABASE DEFAULT CHARACTER SET `utf8` COLLATE `utf8mb4_unicode_ci`;

MySQL said: Documentation
#1253 - COLLATION 'utf8mb4_unicode_ci' is not valid for CHARACTER SET 'utf8' 
```

Trong khi dùng phpMyAdmin thì như này

```
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
```
Import rất tiện. 
Mình nghĩ nên điều chỉnh lại. Vấn đề này gặp cả khi dùng chức năng tải về trong ACP.

**Comment by vuthao** [comment]
Bạn cho biết thông tin phiên bản NukeViet

Và các thông số sau trong file config.php
```php
$db_config['collation'] 
$db_config['charset']  
```

**Comment by anhyeuviolet** [comment]
NukeViet 4.0.27
$db_config['collation'] = 'utf8mb4_unicode_ci';
$db_config['charset'] = 'utf8mb4';

**Comment by vuthao** [comment]
Em kiểm tra lại các cái sau:
Xem có file này không: /themes/my_theme/system/dump.tpl
Nếu có hãy so sánh nó với file /themes/default/system/dump.tpl, hoặc xóa cái /themes/my_theme/system/dump.tpl
Nếu vấn ko được liên hệ với anh qua chat facebook để anh kiểm tra kỹ hơn nhé.

**Comment by anhyeuviolet** [comment]
Đúng rồi anh. Hoá ra do cơ chế này nằm trong system nên sinh lỗi.
Có cách nào dùng 1 file dump cho cả hệ thông ko nhỉ ?
Em clone theme xài từ bản 4.0.25 rồi up lên. Vậy là ko phải do hệ thống.
Cơ mà hướng dẫn update bị thiếu. Hehe :dancer:

**Comment by vuthao** [comment]
@anhyeuviolet @hoaquynhtim99 có nên di chuyển cái file /themes/default/system/dump.tpl sang theme admin_default để khỏi phải copy nó khi tạo theme mới không nhỉ.

**Comment by anhyeuviolet** [comment]
Em nghĩ nên làm. 
Vì theme vẫn ưu tiên gọi TPL theo theme đang dùng, mà cái này áp dụng mặc định cho toàn hệ thống nên chắc mình cố định nó thì hay hơn.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/01561677d4ec8e032fc4c3a1c4a701914b4db801
