### ISSUE TITLE
[SEO] một số vấn đề về URL và Google bot Crawl

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1897]
01/ Các URL với ký tự "lạ" xuất hiện : 
```
http://seoera.info/%BF%C3B%86%EE%08%87Z%9E%E0%A2%F6%FE1%82&A3w%D9V%C5%1Da%E3%C6oWEfQ%A5%F8%DA%E8M%C97%B4%EB%BEAk%1B%E0%0F%C6%1A
```
Site này có khoảng 50 lỗi như này. Phản hồi mà Google báo là 500 hoặc 404.
Mà lỗi 400 thì ko giải quyết bằng .htaccess được. 

02/ Các URL chuyển giao diện, bị phản hồi lỗi 503.

```
http://seoera.info/index.php?language=vi&nv=news&nvvithemever=d&nv_redirect=PGptAobPWLigrBRE_KZvqN_Rl3GGTt9FnI89gJFfP6TOsYTbmsYqotAdvPjS7cHS
```

**Comment by thehung** [comment]
Confirm có lỗi 2, lỗi 1 mình chưa gặp.

**Comment by anhyeuviolet** [comment]
![400](https://cloud.githubusercontent.com/assets/6290970/14728769/0589cf9a-0862-11e6-856e-be049e70c169.PNG)
![404](https://cloud.githubusercontent.com/assets/6290970/14728768/0589b85c-0862-11e6-8b79-f7610e797249.PNG)
Mấy cái link print cũng tiềm tàng lỗi. Em có 3 trang đang hoạt động, dùng NukeViet tới 4.x.
Nhưng lỗi "lạ" thì hình như bản 4.0.27. Còn 1 trang bản cũ hơn thì lại ko bị.

**Comment by thehung** [comment]
Mình quản lý mấy trang sử dụng bản 4.27 không bị.
Mình nghi lỗi do giao diện hoặc module/ block nào đó sinh ra các form submit hoặc link ngẫu nhiên, mà nó có thể lặp đi lặp lại (giống như link chuyển đổi theme) nên mới có thể tạo ra số lượng backlink lỗi lớn đến như vậy.

**Comment by anhyeuviolet** [comment]
Em mới chỉ phỏng đoán thôi.
Có điều, 1 trang thì có module ngoài thì không nói.
Trang seoera.info là chỉ dùng news và dowload nhưng vẫn sinh lỗi. 
Có thời gian chắc em cài thêm vài site để thử nghiệm xem thế nào ... Chứ dạo này SEO không nổi. :(

**Comment by phongaz** [comment]
mình có 2 site đã verified google webmaster tool. đều bị lỗi, và xu hướng tăng dần lên

https://github.com/nukeviet/nukeviet/issues/1853

**Comment by anhyeuviolet** [comment]
Cái khó là phần Linked from của các link này ko thể bấm được, nên cũng ko dò được các trang nào gây lỗi.
Em đang test thêm 1 trang nữa, nhưng chắc phải từ 5 ngày sau mới có thể biết được.

**Comment by vuthao** [comment]
Vấn đề số 1 sẽ cần phải theo dói thêm.
Vấn đề số 2: các bạn có thể fix nhanh bằng cách add thêm  thẻ rel="nofollow" vào link chuyển giao diện: https://github.com/vuthao/nukeviet/commit/ee3d3994fee008351165652d92476cd366739c1b

**Comment by vuthao** [comment]
Xin phép đóng issues này do vấn đề tồn tại cùng với issues: https://github.com/nukeviet/nukeviet/issues/1853
