### ISSUE TITLE
Lỗi Bình Luận Trên Module News của mobile

### ISSUE THREAD

**Issue by lyhuutrong** [nukeviet/nukeviet#1899]
chào ad. Ad xem giúp mình lỗi không thể comment tại module news trên giao diện mobile nhé ad. Mong ad khắc phục sớm sớm ạ.
Với lại ad thêm chức năng chỗ bình luận của thành viên đi ạ. Thêm các tính năng như chỉnh phong chữ , in đậm in nghiêng và chèn tệp như kiểu trong admin đăng tin tức vậy đó. Có gì dễ chèn tệp hoặc hình ảnh vào dễ dàng ạ.

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/5a36d230671df3f9d38a9146a11e9cb3f5748639

**Comment by lyhuutrong** [comment]
Pro ơi cho mình hỏi là cái module video đó mình muốn làm kiểu thêm đường
link để làm trang web phim lẻ phim bộ đó ạ. Pro cho hỏi là module đó thêm
sao vậy ạ? Mong pro chỉ giáo ạ. Hiện tại module đó chỉ tải lên được 1
module hoặc 1 link video từ youtube thôi ạ. Mong pro giúp cách thêm nhiều
link video vào 1 tập phim ạ.

Vào Thứ Sáu, ngày 22 tháng 4 năm 2016, Phan Tan Dung <
notifications@github.com> đã viết:

**Comment by vuthao** [comment]
Lỗi ở module video  bạn post ở kho code của module đó nhé.
