### ISSUE TITLE
Lỗi cảnh báo: gzinflate()

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1900]
Lỗi cảnh báo: gzinflate(): data error in file /vendor/vinades/nukeviet/Http/Encoding.php on line 41

/admin/index.php?language=vi&nv=extensions&mode=newest

Phiên bản NukeViet	4.0.27Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.6.14
Giao thức giữa máy chủ và PHP	Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.14, apache2handler
Hệ điều hành máy chủ	WINDOWS NT
Phiên bản Database	mysql 5.5.5-10.1.8-MariaDB-log

**Comment by hoaquynhtim99** [comment]
#1851
