### ISSUE TITLE
Thêm tính năng ảnh đại diện nhóm của thành viên và lỗi không đưa thành viên vào nhóm tuỳ ý.

### ISSUE THREAD

**Issue by lyhuutrong** [nukeviet/nukeviet#1902]
Chào các pro. Hiện tại mình thấy có phần thêm ảnh đại diện cho nhóm nhưng khi thêm ok rồi thì ra ngoài mình vẫn không thấy được ảnh đại diện của nhóm ạ. Mong các pro chỉ mình cách cho tất cả thành viên hiện ảnh nhóm ra ngoài bình luận và bài viết để dễ dàng nhận biết thành viên thuộc nhóm nào ạ. Và lỗi không đưa thành vào nhóm theo ý muốn của admin được ạ. Mong các pro sớm thêm tính năng và sửa lỗi dùm mình ạ. 
Xin cảm ơn nukeviet rất nhiều ạ. Vì nukeviet đã tạo ra tiền đề để những người không rành về code hoặc biết code mà không có thời gian để code. Mình sẽ luôn theo nukeviet. Nukeviet hơn hẳn các mã nguồn khác mình nghĩ tầm vài năm nữa nukeviet sẽ sánh vai cùng các mã nguồn thế giới. Mình luôn tin dùng nukeviet.

**Comment by vuthao** [comment]
@hoaquynhtim99 cân nhắc việc xử lý tính năng này, nếu xư lý được thì xử lý sơm.

Hiện tại các issues em xác định luôn là xử lý trong giai đoạn nào nhé:
![untitled](https://cloud.githubusercontent.com/assets/2491500/14805571/4de838ca-0b97-11e6-8c2f-e7dc7535ba41.png)

**Comment by hoaquynhtim99** [comment]
@vuthao Em add cái này là tương lai, cái ảnh đại diện nhóm có lẽ nên sử dụng cho từng nhu câu riêng thay vì đưa vào bản mặc định.

Còn chọn thành viên vào nhóm lúc trước đã lập trình rồi. Có hai cách: 
1 là vào quản lý nhóm, tìm thành viên và thêm vào nhóm
2 là sửa thành viên, chọn các nhóm của thành viên, nếu chọn hơn 2 nhóm sẽ có tùy chọn nhóm nào là nhóm mặc định

**Comment by vuthao** [comment]
@hoaquynhtim99 theo như mình hiểu như sau: (chưa code vội nhé, để làm rõ đã)

1. Nhóm thành viên hiện tại đã có Ảnh đại diện nhóm
2. Việc thêm thành viên vào nhóm đã xong.
3. Nhưng các chức năng chử làm được việc của nó

- Chưa hiển thị ảnh đại diện của nhóm ở phần quản lý nhóm.
- Giả sử nhóm đã có ảnh đại diện, tài khoản đã ở trong 1 nhóm này, tài khoản chưa có ảnh đại diện khi đó sẽ dùng ảnh đại diện của nhóm làm avata

@lyhuutrong xem dùm có đúng ý của bạn không nhé.

**Comment by lyhuutrong** [comment]
Vậy bạn cho mình hỏi là có thể làm avatar riêng và ảnh nhóm riêng được ko
ạ. Như vậy dể phát triển thêm được bằng tính năng forum khi dùng module
news ảo ạ. Vì mình có thử rồi. Chỉ thiếu chỗ bình luận của thành viên cần
phải có in nghiêng in đậm và gửi tệp và như của quản trị đăng bài viết có
công cụ đầy đủ cho thành viên đó bạn.

Vào Thứ Ba, ngày 26 tháng 4 năm 2016, Vu Thao <notifications@github.com> đã
viết:

**Comment by lyhuutrong** [comment]
Bạn cho mình hỏi các lỗi đã fix thì code đã fix ở đâu vậy ạ? Cho mình xin
link tải với bạn. Với lại giao diện bị đơ ở iphone nữa nhé bạn.

Vào Thứ Ba, ngày 26 tháng 4 năm 2016, Trọng Lý Hữu <daigjabaclieu@gmail.com>
đã viết:

**Comment by vuthao** [comment]
@lyhuutrong bạn đọc lại nội dung trên https://github.com/nukeviet/nukeviet/issues/1902 nhé.
Việc cập nhật code sẽ có khi có thông báo phát hành.

**Comment by lyhuutrong** [comment]
Anh thảo cho thêm công cụ ở thành viên bình luận và gửi tệp và hình ảnh này
nọ như admin luôn được ko a thảo

Vào Thứ Tư, ngày 27 tháng 4 năm 2016, Vu Thao <notifications@github.com> đã
viết:

**Comment by vuthao** [comment]
@lyhuutrong về mặt code thì có thể làm được.
Nhưng về mặt an ninh an toàn thì không, nên chúng tôi sẽ không phát triển tính năng đó. Nếu cần làm bạn cần làm riêng. Hoặc để đến phiên bản 4.1 sẽ làm thêm tính năng cấu hình cho phép dùng trình soạn thảo ở bình luận.

**Comment by lyhuutrong** [comment]
Dạ thanks a nhiều nhé

Vào Thứ Tư, ngày 27 tháng 4 năm 2016, Vu Thao <notifications@github.com> đã
viết:
