### ISSUE TITLE
Lỗi Tùy biến dữ liệu Users

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1903]
Loại dữ liệu: date
Các tùy chọn dữ liệu ngày tháng
Từ ngày: - Tới Ngày là không cần thiết và hiện tại đang báo lỗi sai kiểu dữ liệu mặc đù chọn đúng
Thuộc tính class html: không cho phép dấu - như vậy là sai

**Comment by dangdinhtu2014** [comment]
Lựa chọn thả xuống (selectbox)
Lựu chọn dữ liệu : Tự nhập
Giá trị các tùy chọn có thể là chuỗi kí tự tiếng việt hiện tại đang chỉ cho phép a-z, 0-9, and _ only
như vậy là không đúng

**Comment by hoaquynhtim99** [comment]
Phần giá trị hiện tại mang ý nghĩa khóa nên báo thế, đã sửa lại ngôn ngữ hiển thị cho phù hợp
Các phần khác đã sửa: https://github.com/hoaquynhtim99/nukeviet/commit/0a2648a6a55cd5466e8d2085f0ad591b916d2705
