### ISSUE TITLE
[Hỏi] Chức năng refresh của module uploads

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1906]
Chức năng refresh của module uploads khi refresh lại thì đường dẫn thư mục lại cho phép chọn ảnh từ module khác kể cả thư mục uploads gốc. Đây có phải là lỗi của hệ thống hay do đội code cố tình làm như vậy. Vì nguyên tắc từ trước đến giờ là module nào uploads ảnh module đó

**Comment by dangdinhtu2014** [comment]
Chi tiết xem demo : https://www.youtube.com/watch?v=o8BF2hsA2Uk

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/696b1db98fc16d83af17a25ba6afe9de5a893e6a
