### ISSUE TITLE
Đề xuất cập nhật fontawesome

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1911]
Lỗi không decode  được font phiên bản cũ 4.5.0
Failed to decode downloaded font: http://demo.vn/themes/default/fonts/fontawesome-webfont.woff2?v=4.5.0
 Đề nghị cập nhật lên phiên bản mới nhất để tránh gặp lỗi này

**Comment by vuthao** [comment]
update: https://github.com/vuthao/nukeviet/commit/668191985e7b40952acb5ab4ee4441df19c9b06c
