### ISSUE TITLE
KIểm tra cập nhật các thư viện javascript

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1912]
jquery.Jcrop: https://github.com/tapmodo/Jcrop
jquery_lazyload: https://github.com/tuupola/jquery_lazyload

**Comment by hoaquynhtim99** [comment]
@vuthao em đang làm cái này nhé

**Comment by hoaquynhtim99** [comment]
Update Jcrop: https://github.com/hoaquynhtim99/nukeviet/commit/c7dc9ad61aa35784a704023dcbaffb94385868ce
Update lazyload: https://github.com/hoaquynhtim99/nukeviet/commit/a4c0a64cf08a63b2fee0cee993ee21757cd0c2e0
