### ISSUE TITLE
Cải tiến: Ô đăng nhập

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1914]
Hiên tại ô đăng nhập có 2 vấn đề sau:

1. Ngôn ngữ trong placeholder: Tên đăng nhập -> cái này nên sửa lại là Tên đăng nhập hoặc email
2. Khi nhập địa chỉ email vào ô đăng nhập nếu có ký tự viết hoa thì không đăng nhập được. Cái này chưa thích hợp vì địa chỉ email không phân biệt ký tự hoa thường.

**Comment by hoaquynhtim99** [comment]
"địa chỉ email không phân biệt ký tự hoa thường" Cái này không biết thông tin chính thức từ đâu nhưng đã gặp trường hợp email phân biệt chữ hoa chữ thường ở các trường bên Đài Loan (Gửi hồ sơ du học)

**Comment by vuthao** [comment]
Hiện tại phiên bản NukeViet 4 RC 3 email đã được lower

**Comment by vuthao** [comment]
@hoaquynhtim99 để anh sửa nốt cái lang này nhé.

**Comment by phongaz** [comment]
@hoaquynhtim99 http://email.about.com/od/emailbehindthescenes/f/email_case_sens.htm

Phần tên miền thì không phân biệt rồi.
Còn phần phía trước có phân biệt nhưng không phổ biến. do đó, cần lower hết để tránh rắc rối

**Comment by vuthao** [comment]
các mỗi đăng nhập đã được sửa trước đó.
Ngôn ngữ đã được thay thế tại: https://github.com/vuthao/nukeviet/commit/ee25e1a1ac1e29149582018975ed5f5753e048d4
