### ISSUE TITLE
Cải tiến - Mục Topics

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1917]
Nên cho phép sắp xếp lại thứ tự các bài viết trong mỗi topic.

Thông thường theo dòng sự kiện thì theo trật tự thời gian. Đối với các site tin tức thì không vấn đề. Tuy nhiên cũng có những sự kiện ngắt quãng bị thì có thể sắp xếp. biên tập lại cho phù hợp thì tốt hơn.

**Comment by vuthao** [comment]
Hiện tại cái này đang sắp xếp theo ID, mình sẽ sửa lại sắp xếp theo thời gian đăng mới nhất lên trên.

Do module này làm chuyên cho tin tức, và số lượng bài viết lớn và rất lớn, nên việc hiển thị sắp xếp lại sẽ ảnh hướng nhiều đến tốc độ xử lý. nên vấn đề "có những sự kiện ngắt quãng bị thì có thể sắp xếp. biên tập lại cho phù hợp thì tốt hơn." sẽ không được xử lý

**Comment by vuthao** [comment]
update: https://github.com/nukeviet/nukeviet/commit/adf0edde2077f1d4d4c30fd9d5691004edcdffe6
