### ISSUE TITLE
[Ứng dụng - Mở rộng] Các thông tin khi cài bản mới hơn của module ko được cập nhật

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1918]
Như tiêu đề. Giả như phiên bản đã cài vào là 1.0.10.
Sau đó cài gói mới có số phiên bản là 2.0.01. Rõ ràng bước gửi file lên và tiến hành thì có đọc dữ liệu trong config.ini và version.php.
Nhưng cài xong thì trong quản lý ứng dụng/quản lý module vẫn là ver cũ 
=> khi đóng gói xuống thì file config.ini cũng lệch nốt.

**Comment by hoaquynhtim99** [comment]
Để cập nhật các thông tin trên, cần viết gói nâng cấp cho ứng dụng, việc ghi đè code sẽ không có tác dụng, ví dụ về gói nâng cấp: https://nukeviet.vn/vi/store/download/video-clip/448/
Hiện tại phần mở rộng ứng dụng cũng không cho phép cài đặt khi ứng dụng đã tồn tại trên hệ thống

**Comment by anhyeuviolet** [comment]
Gói nâng cấp khác như thế nào với module gốc nhỉ @hoaquynhtim99 . Mình xem gói tải về theo link trên thì ko thấy gì khác một module hoàn chỉnh. Trừ khi là khác cái tên.

**Comment by hoaquynhtim99** [comment]
Về gói nâng cấp có thể xem tại: http://wiki.nukeviet.vn/programming:moduleupdate
