### ISSUE TITLE
voting: Thêm mã captcha để bảo vệ

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1923]
Để tránh tự động và số liệu ảo, nên có cấu hình bật captcha khi người dùng bấm voting

**Comment by hoaquynhtim99** [comment]
Added: https://github.com/hoaquynhtim99/nukeviet/commit/27e427b2ce1da86a410e4fc393c81a0dea689509 and https://github.com/hoaquynhtim99/nukeviet/commit/bebf88345418c4469d3731e4c642bd8a7cace64b
