### ISSUE TITLE
[hỏi] module voting, mục liên kết tới trang

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#1925]
Trong câu hỏi khảo sát, ở mỗi phương án trả lời có cột Liên kết tới trang.

Không biết ô này để làm gì. mình thử nhập một trang lên đó là example.com hay abc gì đó.

Ra ngoài site click vào phương án có chứa liên kêt là Domain.com/voting/example.com hoặc domain.com/voting/abc. và trả về lỗi not found. và thực tế là url khi click vào luôn chứa domain.com/voting/trang-liên-kết-do-mình-nhập-vào. trang này mãi mãi không tồn tại

**Comment by vuthao** [comment]
url đó @phongaz  cần nhập chính xác (có cả http://).
Hienenj tại mình đã bổ sung thêm điều kiện kiểm tra, nếu nhập url không đúng sẽ bị loại bỏ.
