### ISSUE TITLE
Lỗi không nhận full theme khi sử dụng biến $nv_redirect

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1926]
Khi tạo link chuyển tới module user để đăng nhập có sử dụng biến $nv_redirect để quay trở lại trang vừa chuyển thì giao diện đăng nhập không nhận full theme mà nhận theo kiểu block.
```
$full = empty($nv_redirect) && empty($nv_header);

include NV_ROOTDIR . '/includes/header.php';
echo nv_site_theme($contents, $full);
include NV_ROOTDIR . '/includes/footer.php';
```

**Comment by vuthao** [comment]
@htuyen1994 cái này do @anhtunguyen cố tình làm như thế đó.

Anh Tú xem dùm em nếu sửa file modules/users/funcs/login.php

từ 
```php
$full = empty($nv_redirect) && empty($nv_header);
```

Thành 
```php
$full = empty($nv_header);
```
Có được không.

**Comment by vuthao** [comment]
update: https://github.com/vuthao/nukeviet/commit/ba1fdf8a9b99e761f6e753187867a439e8f890a9
