### ISSUE TITLE
Lỗi hiển thị ảnh trong phần tin tức

### ISSUE THREAD

**Issue by xuanluc73** [nukeviet/nukeviet#1927]
Mô tả lỗi: Xem ảnh đính kèm
Trong trang quản trị, phần ảnh đính kèm được cấu hình ảnh là vị trí ở giữa,
![admin](https://cloud.githubusercontent.com/assets/951683/14936721/2b66ba30-0f1e-11e6-92aa-b4022359be3a.png)

Tuy nhiên khi hiển thị chi tiết phần đọc tin như sau:
![l i hi n th](https://cloud.githubusercontent.com/assets/951683/14936726/3eef2e34-0f1e-11e6-988e-8c845ba5d002.png)

view code:
![view code](https://cloud.githubusercontent.com/assets/951683/14936771/11b6c1b0-0f1f-11e6-8237-59219c213e4d.png)

Phiên bản sử dụng: 4.0.28 RC3
demo: http://hotruong.net/Tin-tuc-Su-kien/co-mot-lang-que-nhu-the-1100.html

**Comment by thehung** [comment]
Anh thử lại bằng cách xóa sạch định dạng xem sao?

**Comment by xuanluc73** [comment]
Gần 1000 bài, nếu xóa sạch định dạng để sửa lại bài viết thì khối lượng công việc là không hề nhỏ, chắc phải làm mất mấy tháng quá.

**Comment by hongoctrien** [comment]
Cái này chỉnh lại css xí là được thôi anh.

@xuanluc73 thêm css này vào themes/ten-theme/css/news.css
```
.bodytext figure.image {
	width: 100%
}
```
Fixed: https://github.com/nukeviet/nukeviet/pull/1928/commits/f3fb962ecba2d9603e2bd1d5281cc4a4381ff64c

**Comment by xuanluc73** [comment]
Ok, báo lỗi để sửa luôn code của mã nguồn. Cảm ơn @hongoctrien
