### ISSUE TITLE
Lỗi: Failed to decode downloaded font

### ISSUE THREAD

**Issue by quangcuong** [nukeviet/nukeviet#1929]
Failed to decode downloaded font: http://thptnguyenthaibinh.lamdong.vn/ntb/themes/default/fonts/fontawesome-webfont.woff2?v=4.6.1
(index):1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
![loifont](https://cloud.githubusercontent.com/assets/14310636/14940261/8173b024-0f99-11e6-9700-f62881081903.jpg)

**Comment by vuthao** [comment]
@quangcuong update Font Awesome Version 4.6.2 sẽ hết  lỗi.
http://fortawesome.github.io/Font-Awesome/

fixed: https://github.com/vuthao/nukeviet/commit/e784cfdf709ed18d34635fc00284fb3a43149053
