### ISSUE TITLE
Báo lỗi The localhost page isn’t working

### ISSUE THREAD

**Issue by duongGitHub** [nukeviet/nukeviet#1930]
Sau khi copy các file để update thủ công, vào admin không được, nó báo lỗi:
The localhost page isn’t working

localhost is currently unable to handle this request.
HTTP ERROR 500

**Comment by anhyeuviolet** [comment]
Bạn chắc là copy các thư mục bên trong thư mục /install/ và đẩy lên host, thay vì đẩy nguyên thư mục /install/ lên phải không ?

**Comment by duongGitHub** [comment]
Đúng roi, minh giải nén và Upload các file trong gói update với cấu trúc của NukeVie (tuc la copy tung file mot theo cau truc cua Nukeviet ay)

**Comment by anhyeuviolet** [comment]
Vậy bạn xem trương hợp tương tự bên này nhé.
https://github.com/nukeviet/update/issues/8
