### ISSUE TITLE
Localhost bao loi line 357 

### ISSUE THREAD

**Issue by duongGitHub** [nukeviet/nukeviet#1931]
Thông báo từ Hệ thống
Nên chú ý Nên chú ý: Undefined index: ad_block_cat in file /modules/news/theme.php on line 357

**Comment by anhyeuviolet** [comment]
Cái này bạn cập nhật lên hay là cài mới ?

**Comment by duongGitHub** [comment]
Minh nang cap thu cong từ NukeViet 4.0 RC2 lên NukeViet 4.0 RC3

**Comment by anhyeuviolet** [comment]
Cái này do chưa cập nhật Database. Bạn kiểm tra xem có sót bước nào không ?
