### ISSUE TITLE
Lỗi copy hình ảnh vỡ khung khi xem trên giao diện desktop và mobile

### ISSUE THREAD

**Issue by lyhuutrong** [nukeviet/nukeviet#1934]
A thảo có thể thêm ở phần news để cho tiện ích và đỡ bị vỡ khung khi copy bài viết từ nguồn khác về thì hình ảnh được đưa tự động vào mục upload của website của mình được ko ạ? Vì khi copy bài viết có nhiều hình ảnh thì khá khó khăn khi phải dowload nhiều hình ảnh để upload vào thư mục upload của website ạ. Vì nếu để nguyên hình ảnh từ nguồn khác sẽ làm vỡ khung trên tất cả giao diện ạ. Và hình ảnh từ website lấy nguồn bị die hoặc mất thì sẽ làm cho website mình bị mất ạ. Tuy rằng làm như thế sẽ khiến cho website nặng dung lượng nhưng tiện lợi là giữ được hình ảnh ạ. Mong anh thảo và đội code hỗ trợ phần này vào nukeviet final ạ. chúc anh và đội code có nhiều sức khoẻ ạ.

**Comment by xuanluc73** [comment]
Copy từ nguồn khác thì cũng bỏ công chỉnh sửa tý đi bạn, chỉ cần click đúp vào ảnh, mỗi cái chỉ mất ấy giây thôi, đặt lại kích thước chiều rộng và chiều cao theo ý bạn là ok ngay thôi mà. Nếu copy rồi dán luôn mà không chịu khó chỉnh sửa thì vỡ giao diện hoặc hình bé tý là chuyện bình thường.

**Comment by vuthao** [comment]
@lyhuutrong  tính năng đã có sẵn trong trình soạn thảo (Cái nút có quyển sách ấy)

**Comment by lyhuutrong** [comment]
Vâng ạ. Cái nút đó trong trình soạn thảo của nukeviet khi mình paste bài
viết ctrl+A là nó tự động hình ảnh chuyển vào website riêng của mình nằm ở
upload hã a thảo? Tại vì chỉnh sửa thì khi copy cũng phải chỉnh sửa rồi a.
Nhưng mà ví dụ như 1 bài viết mà có hơn mấy chục hình thì cũng hơi cực ạ.
Vì download về rồi upload lên rồi trỏ đường link nên tốn khá nhiều thời
gian cho 1 bài viết ạ. E cảm ơn a rất nhiều và cả đội code nữa ạ

Vào Thứ Tư, ngày 04 tháng 5 năm 2016, Vu Thao <notifications@github.com> đã
viết:

**Comment by vuthao** [comment]
@lyhuutrong  thử đi.

**Comment by lyhuutrong** [comment]
a thảo ơi. e đã thử rất tiện ít ạ. Không bị vỡ khung nữa ạ và nó tự đưa lên mục uploads và đúng module nhưng khi ra trang chủ thì mở hình ảnh và xem hình ảnh thì nó không đi theo đường link trong mục uploads/news website của mình mà nó nằm ở liên kết nguồn mình lấy ạ. Mong a thảo và đội code khắc phục dùm e ạ. E xin cảm ơn a và đội code rất nhiều. Chúc a và đội code có nhiều sức khỏe ạ.

**Comment by vuthao** [comment]
@lyhuutrong bạn thay thế lại file admin/upload/download.php
Bằng file sau và thử lại nhé: https://raw.githubusercontent.com/vuthao/nukeviet/develop/admin/upload/download.php
