### ISSUE TITLE
Lỗi 500 khi tham gia nhóm

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#1935]
Khi user thường tham gia nhóm bị lỗi 500, users/editinfo/group/

**Comment by vuthao** [comment]
@htuyen1994 đang sửa module users thì sửa luôn lỗi đó nhé.

**Comment by vuthao** [comment]
@htuyen1994 Sửa như sau nhé:
tìm đến đoạn sau trong file modules/users/funcs/editinfo.php khoảng dòng 704:
```php
if (nv_groups_add_user($gid, $user_info['userid'], $approved, 1, $module_data)) {
```

Sửa thành
```php
if (nv_groups_add_user($gid, $user_info['userid'], $approved, $module_data)) {
```
