### ISSUE TITLE
Đề xuất lại cách gọi của layout cho chính xác

### ISSUE THREAD

**Issue by volong1012** [nukeviet/nukeviet#1936]
Trong folder layout của giao diện hiện nay được chia thành : left - body - right.... thường thì phần body (id body trong nuke sẽ bao gồm tất cả các (cột - left - body - right) ) do đó việc gán tên body (nhỏ) cho 1 cột trong body (to) e thấy đọc không ổn lắm ->> sao mình ko đổi cột body thành "content" khi đó sẽ tránh nhầm lẫn khi gọi các layout.

**Comment by thehung** [comment]
Hợp lý, tuy nhiên hình như việc gọi tên body cũng chỉ mang tính quy ước thì phải?

**Comment by hoaquynhtim99** [comment]
Có khi bây giờ đổi lại nó gây nhầm lẫn cũng nên :dancer:

**Comment by anhyeuviolet** [comment]
Cái này là tên gọi quy ước thôi mà nhỉ. Đâu liên quan gì tới HTML.
Giờ đổi chắc loạn hết cả.

**Comment by volong1012** [comment]
Thì nó là tên gọi quy ước đó ! khi giải thích với khách hàng hoặc cho những đồ họa khác sẽ rất mệt vì họ định nghĩa riêng body là body còn content là content, vì vậy mới phải đề xuất sửa lại cách gọi mà thôi ! Kiểu như lúc trước nói body là tổng thể rồi lại layout left body right dc -> sẽ gây nhầm lẫn

**Comment by vuthao** [comment]
Để cho tránh bị nhầm lẫn sau khi đã trao đổi với anh @anhtunguyen  sẽ đổi: body -> center
Khi đó sẽ là: left-center-right

**Comment by thehung** [comment]
Cũng không ổn, vì nếu đổi cột thì nó thành center-left-right à?

**Comment by anhtunguyen** [comment]
Đúng rồi em. 3 cái đó đều chỉ vị trí, đồng nhất về mặt ngữ nghĩa.

**Comment by phongaz** [comment]
Theo mình thấy ở nukeviet thì cột nào to nhất là cột chính chứa nội dung bài viết. Nếu dùng từ center thì cũng gây nhầm lẫn; nên dùng main-left-right, left-main-right,...

**Comment by vuthao** [comment]
+1 cho từ main
Vào 07-05-2016 11:58, "Cao Thế Phong" <notifications@github.com> đã viết:

**Comment by vuthao** [comment]
update: https://github.com/vuthao/nukeviet/commit/8da3724de4d3d797edcaa55aa990c7811238d575
