### ISSUE TITLE
Chưa thấy được ảnh đại diện nhóm từ bình luận

### ISSUE THREAD

**Issue by lyhuutrong** [nukeviet/nukeviet#1937]
a thảo  và đội code xem dùm e cách hiển thị ảnh đại diện nhóm với ạ. Vì e có để ảnh đại diện nhóm vào RC3 nhưng khi bình luận vẫn chưa thấy ảnh đại diện của nhóm ạ

**Comment by vuthao** [comment]
Trước giờ đối với các diễn đàn nó cũng chỉ sử dụng cái ảnh nhóm làm "huy hiệu' 
chứ lấy nó làm ảnh đại diện của thành viên không nên.

Nếu bạn vẫn muốn sửa thì sửa nó ở trong file
modules/comment/funcs/main.php

ở các đoạn sau:
1) Lấy dữ liệu nhóm thành viên khoảng dòng 92
```php
        $db_slave->select('a.cid, a.pid, a.content, a.post_time, a.post_name, a.post_email, a.likes, a.dislikes, b.userid, b.email, b.first_name, b.last_name, b.photo, b.view_mail');
```

2) Xứ lý ảnh hiển thị khoảng dòng 340
```php
            if (! empty($comment_array_i['photo']) && file_exists(NV_ROOTDIR . '/' . $comment_array_i['photo'])) {
                $comment_array_i['photo'] = NV_BASE_SITEURL . $comment_array_i['photo'];
            } elseif (is_file(NV_ROOTDIR . '/themes/' . $global_config['module_theme'] . '/images/users/no_avatar.png')) {
                $comment_array_i['photo'] = NV_BASE_SITEURL . 'themes/' . $global_config['module_theme'] . '/images/users/no_avatar.png';
            } else {
                $comment_array_i['photo'] = NV_BASE_SITEURL . 'themes/default/images/users/no_avatar.png';
            }
```

**Comment by lyhuutrong** [comment]
À ý e không phải như thế a thảo ơi. Ý e là khi e cài đặt ảnh nhóm rồi nhưng
khi bình luận hay vào thông tin cá nhân thì vẫn không thấy ảnh nhóm a ạ.

Vào Thứ Sáu, ngày 06 tháng 5 năm 2016, Vu Thao <notifications@github.com>
đã viết:

**Comment by vuthao** [comment]
Hiện tại ảnh đại diện nhóm mới làm cho module forum.
Các module khác không dùng đến.
Phần bình luận hay vào thông tin cá nhân: dùng ảnh đại diện của từng thành viên.
Nếu bạn muốn sửa thì theo hướng dẫn trên nhé, cái này sẽ không sửa vào NukeViet mặc định nhé bạn.

**Comment by lyhuutrong** [comment]
Vậy là mong a thảo và đội code sớm cho ra đời module forum khi ra bản final
ạ.

Vào Thứ Sáu, ngày 06 tháng 5 năm 2016, Vu Thao <notifications@github.com>
đã viết:
