### ISSUE TITLE
Tràn trang hiển thị số trang trong module news trên đện thoại

### ISSUE THREAD

**Issue by xuanluc73** [nukeviet/nukeviet#1939]
Lỗi ảnh đính kèm: Thiết bị hiển thị: Samsung Galaxy A7 
![screenshot_2016-05-06-05-59-01](https://cloud.githubusercontent.com/assets/951683/15059907/5d094cb6-1350-11e6-889c-11fd0e5fae1e.png)
Đề xuất nên để  dạng
![zalo_screenshot_6_5_2016_68792](https://cloud.githubusercontent.com/assets/951683/15060065/a98eac7e-1351-11e6-8411-234a442a77a5.jpg)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/82107796179c3c8ef2493d06b90042fda6c3353a
Demo: https://mangvn.com/XaHoi/page-7/
