### ISSUE TITLE
webtools: Lỗi khi nâng cấp tự động

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#1940]
Khi nâng cấp site tự động thì lỗi như sau:
- Sau khi : Hãy click Vào đây để tiến hành nâng cấp  
- Thình thoảng bị: Có một lỗi không xác định đã xảy ra.
- Khi tải được, chuyển sang trang nâng cấp lại chuyển ra ngoài site, kiểm tra file trong thư mục nâng cấp không thấy có file nâng cấp

**Comment by vuthao** [comment]
@hoaquynhtim99  khi kiểm tra phần này kiểm tra luôn phần: https://github.com/nukeviet/nukeviet/issues/1918

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/8cac53da95280d8026a9b105b3f1b469c6145b1d
