### ISSUE TITLE
Có ai gặp lỗi khu đăng ký thành viên bằng google với facebook không ạ

### ISSUE THREAD

**Issue by songnhien** [nukeviet/nukeviet#1942]
demo tại http://hiepduc.net
google lỗi thế này:
400. That’s an error.

Error: redirect_uri_mismatch

Application: Đăng nhập

You can email the developer of this application at: hiepducnet@gmail.com

The redirect URI in the request, http://www.hiepduc.net/index.php?language=vi&amp;nv=users&amp;op=oauth&amp;server=google, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/838175440342-0agm0co2j777266buvtoca0k0vn0d82p.apps.googleusercontent.com?project=838175440342 to update the authorized redirect URIs.

Learn more

**Comment by vuthao** [comment]
Mình đã kiểm tra lại không có lỗi code.

Bạn có thể thử lại:
https://nukeviet.vn/vi/users/
Chấc bạn khai báo sai thông số nào đó

**Comment by songnhien** [comment]
em vào đây click vào tài khoản google rồi nó quay suốt ạ
http://hiepduc.net/index.php?language=vi&nv=users&op=oauth&server=google

**Comment by vuthao** [comment]
@songnhien nếu có thể tạo dùm mình 1 website khác trên cùng server đó để mình kiểm tra chi tiết. Thông tin cụ thể gửi dùm qua email thao a còng vinades.vn

**Comment by vuthao** [comment]
@songnhien  đã gửi tài khoản site, Mình sẽ kiểm tra cái này.

**Comment by vuthao** [comment]
@songnhien mình cấu hình website của bạn sang PHP 5.5 là chạy ngay.

**Comment by songnhien** [comment]
Cam ơn anh đã giúp đỡ. vậy là do phiên bản php sau này ai có gặp trường hợp
này mình cũng có kinh nghiệm.


*Song Nhiên Digital*
*ĐC: Tân An- Hiệp Đức - Quảng Nam*
*ĐT: 05103 683 683 -0984 191 073*
*WEB: songnhien.com.vn <http://songnhien.com.vn>*
*ĐƯỜNG ĐI: Click vào đây
<https://www.google.com/maps/place/C%C3%B4ng+ty+TNHH+Song+Nhi%C3%AAn/@15.5809469,108.1068508,17z/data=!4m2!3m1!1s0x3169f9d768360575:0x4fc85ba606c01314>*

2016-05-16 11:29 GMT+07:00 Vu Thao <notifications@github.com>:
