### ISSUE TITLE
[Giao diện Admin] Lỗi hiển thị khi sửa nguồn tin

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1947]
![001](https://cloud.githubusercontent.com/assets/6290970/15136866/8257df02-16af-11e6-97f0-3ad6533d1e17.PNG)
![002](https://cloud.githubusercontent.com/assets/6290970/15136867/8257e63c-16af-11e6-8486-9adc3dc8d037.PNG)

Khi còn 1 nguồn tin, nhấn sửa.
Khi đó chả hiểu sao không cuộn trang được nữa.
NV 4.0.28

**Comment by hoaquynhtim99** [comment]
Cái này không rõ lắm là gì @anhyeuviolet mô tả kỹ hơn chút được không

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/27bf11e5327dfda12d6837fc1e7c238c08efaa93

**Comment by anhyeuviolet** [comment]
Ủa sửa gì đâu đã đóng lại ròi :(

**Comment by anhyeuviolet** [comment]
@hoaquynhtim99  vào xem lại giúp mình cái này cái.

**Comment by hoaquynhtim99** [comment]
Đã sửa ở https://github.com/hoaquynhtim99/nukeviet/commit/27bf11e5327dfda12d6837fc1e7c238c08efaa93

**Comment by anhyeuviolet** [comment]
@hoaquynhtim99  mình áp dụng các sửa đổi đó vào site đang thử nghiệm thì vẫn lỗi.
Còn nếu bỏ #edit khỏi link chỉnh sửa trong phần admin functions thì mới hết lỗi.

**Comment by vuthao** [comment]
Cái này không đến độ "cháy nhà chết người" nên để lại khi nào tìm được hướng xử lý sau vậy, chứ hiện tại cũng ko biết phải sửa cái nà thế nào
