### ISSUE TITLE
Cần bổ sung thêm link đến trang chi tiết của thành viên

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1950]
Trong trang danh sách thành viên ở Admin Control Panel module Users: Cần bổ sung thêm link đến trang chi tiết của thành viên (ngoài site) 
Phía ngoài site: cần bổ sung link cho phép Admin sửa/ xóa thông tin thành viên.

**Comment by hoaquynhtim99** [comment]
Added: https://github.com/hoaquynhtim99/nukeviet/commit/0e9ed223392cbc4768f7c2ce11da42dce2be26ea
