### ISSUE TITLE
Module news: cấu hình hiển thị nguồn bài viết tại chi tiết tin

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1951]
"Cấu hình hiển thị nguồn bài viết tại chi tiết tin" đã chọn là "hiển thị link của nguồn tin" nhưng kết quả lại hiển thị website của nguồn tin mà không phải là link của nguồn tin đã điền vào bản tin.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/43d658e3adb8063d30a8eb233043ed3fa0e389fb
