### ISSUE TITLE
Cách đặt mã quảng cáo từ adsense

### ISSUE THREAD

**Issue by lyhuutrong** [nukeviet/nukeviet#1957]
A thảo và đội code cho e hỏi là đặt mã quảng cáo của google adsense vào nukeviet rc3 sao vậy ạ ? nào giờ e chưa biết về cách đặt mã trong nukeviet rc3 ạ.

**Comment by hoaquynhtim99** [comment]
Bạn đặt câu hỏi trên diễn đàn nhé, khu vực này không hỗ trợ những vấn đề thế này.
