### ISSUE TITLE
Dữ liệu mẫu module news tiếng anh đang bị lỗi

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#1960]
Một số ảnh không tồn tại trong bài viết

**Comment by vuthao** [comment]
@thehung xem có làm lại dữ liệu mẫu Tiếng Anh không nhỉ.

**Comment by thehung** [comment]
Giữ nguyên CSDL cũ thôi.
Ảnh trong bài viết thiếu thì thay bằng ảnh online trên nukeviet.vn cho nó
nhẹ bộ cài.
