### ISSUE TITLE
Bổ sung tính năng chèn mã google adsense vào nukeviet

### ISSUE THREAD

**Issue by lyhuutrong** [nukeviet/nukeviet#1961]
A thảo và đội code cố gắng thêm tính năng chèn mã google adsense để mọi người cùng nhau kiếm thêm ít thu nhập và đóng góp vào quỹ nukeviet ạ. Mong rằng a và đội code làm thêm tính năng này nữa chắc nukeviet sẽ phát triển mạnh mẽ hơn ạ.

**Comment by thehung** [comment]
Bạn có thể làm thêm block để quản lý cái này. 
Vì không phải mọi site sử dụng Adsense cho nên chúng tôi sẽ không đưa những block như thế này vào bản mặc định. 
Vui lòng vào forum để thảo luận thêm nếu bạn cần hỗ trợ.
