### ISSUE TITLE
Chức năng nhóm thành viên chưa được cập nhật cho giao diện mobile_nukeviet

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#1962]

**Comment by vuthao** [comment]
@hoaquynhtim99 có phải cái này đã được xử lý ở đây rồi : https://github.com/vuthao/nukeviet/commit/2c6bb321aa24e21419f00e003a669b70e88fb2d5
Nếu phải đóng dùm anh issues này nhé
