### ISSUE TITLE
[Plugins] rewrite_obsolute.php  - kích hoạt làm sai sitemap

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#1963]
Như hình
![plugin_url](https://cloud.githubusercontent.com/assets/6290970/15308135/2f1ef5be-1c04-11e6-9a49-53e1f7c27b8c.PNG)

Cấu hình như sau : 
![pugin_config](https://cloud.githubusercontent.com/assets/6290970/15308147/48d7edda-1c04-11e6-9468-dc43fb7f1c08.PNG)

NV4.0.28.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/pull/1967/files
