### ISSUE TITLE
Lỗi: Không chèn được tài liệu từ google

### ISSUE THREAD

**Issue by quangcuong** [nukeviet/nukeviet#1968]
Không chèn được tài liệu từ google bằng nút google docs trong trình soạn thảo
![tai lieu google docs](https://cloud.githubusercontent.com/assets/14310636/15326210/52683b20-1c77-11e6-970e-6ae29264b691.jpg)

**Comment by vuthao** [comment]
Cái này cần đưa site lên host để google có thể truy cập file đó mới hiển thị được nhé bạn

**Comment by quangcuong** [comment]
Mình chạy trên host vẫn bị báo lỗi

**Comment by thehung** [comment]
Bạn vào cấu hình chung, kiểm tra lại khai báo lại địa chỉ domain xem chính xác chưa?

**Comment by vuthao** [comment]
@quangcuong quay lại video quá trình bạn thực hiện xem

**Comment by quangcuong** [comment]
Vi deo đây anh @vuthao 
https://youtu.be/3oN8Km4_E34

**Comment by vuthao** [comment]
Bạn cần upload file lên website sau đó chọn file đó.

**Comment by quangcuong** [comment]
Vậy chức năng của nó là chèn tài liệu ừ site lên google docs chứ không phải là chèn từ google docs lên site.

**Comment by thehung** [comment]
Thực ra nó là chức năng view file bằng Google docs và chèn vào bài viết!

**Comment by quangcuong** [comment]
Đã hiểu. Xin cảm ơn!
