### ISSUE TITLE
Giao diện mobile không hiện gì nếu đặt phương án hiển thị tin "Không hiển thị" trên destkop

### ISSUE THREAD

**Issue by vanhuonghn011291** [nukeviet/nukeviet#1971]
Phiên bản Nukeviet 4.0.28
Nếu muốn đặt không hiển thị tin đế sử dụng các block thì trong giao diện mobile không hiển thị tin nhưng cũng không có kéo thả block ở phần content để thêm block
Demo: http://mamnon2016.esy.es/

**Comment by vanhuonghn011291** [comment]
Có tạo block được nhưng hình như bật block bị lỗi ko thêm được block.

**Comment by vanhuonghn011291** [comment]
![image](https://cloud.githubusercontent.com/assets/10495040/15344290/01ed47a4-1cd0-11e6-82e6-0d0f58e6c290.png)

**Comment by vuthao** [comment]
Với giao diện mobile tạm thời bạn vào trong quản trị để thêm block nhé.

**Comment by vanhuonghn011291** [comment]
Vâng, em thêm block bên trong quản trị a..

**Comment by xuanluc73** [comment]
Nên tách phương án hiển thị tin tức trên decktop và trên mobile riêng biệt, như vậy sẽ tiện hơn cho việc bố trí giao diện. Như hiện tại nếu chọn phương án  chuyên mục tin khác nằm bên phải hoặc bên trái thì việc hiển thị trên mobile không ổn lắm, mobie nên để theo dạng grid hoặc danh sách - tin mới lên trên thì hay hơn. Theo ý tôi việc chọn phương án hiển thị mobile khác với decktop thì sẽ co động hơn, hiện tại tôi cũng đang chọn phương án cấu hình bằng block trên cae decktop và mobile

**Comment by vuthao** [comment]
@xuanluc73 Nên tách góp ý này ra thành issues riêng anh.
Bởi nếu lỗi này được fix đóng góp của anh cũng sẽ bị Close lại luôn.

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/d4bdbbe19a5c5949c753b3d568f977ad9d56237d
