### ISSUE TITLE
cài mới yêu cầu php bản 5.5

### ISSUE THREAD

**Issue by nguyengiakt** [nukeviet/nukeviet#1976]
Khi down bản nukeviet mới nhất về để cài đoạn này báo ko cho tiếp tục. PHIÊN BẢN PHP: 5.4.27	Bắt buộc hỗ trợ >= 5.5.0	Không tương thích.
Có nhiều server đang chạy bản php 5.4 ổn định, đôi khi up php lên mới nhất nhiều phần mềm chạy sẽ bị lỗi chung, ban quản trị xem xét lại

**Comment by vuthao** [comment]
Trước khi nâng yêu cầu của PHP tôi đã tham khảo một số thông tin.
Hiện tại  PHP 5.4 đã bị ngưng hỗ trợ: http://php.net/supported-versions.php
Các bạn nên dùng  PHP 5.6 (Nếu có PHP 7.0 thì nên dùng cái mới này, tốc độ xử lý nhanh gấp đôi so với các bản trước)

Còn nếu buộc phải dùng PHP 5.4 (PHP 5.2, 5.3 sẽ không chạy được luôn nên không phải thử). Các bạn có thể ép nó xuống như sau:
Sửa file /includes/ini.php tìm đến dòng:
```php
if (version_compare(PHP_VERSION, '5.5.0') < 0) {
```
Sửa số 5.5.0 thành 5.4.0

Tương tự với file /install/ini.php tìm đến dòng:
```
$sys_info['php_required'] = '5.5.0';
```
Sửa số 5.5.0 thành 5.4.0

Khi dùng PHP  5.4.0 sẽ có khả năng một số lỗi trên 1 số server:
- Không login được tài khoản bằng facebook
- Gửi mail không ổn định
- Nếu có lỗi bảo mật của PHP, phiên bản 5.4 sẽ không được php.net hỗ trợ.
