### ISSUE TITLE
Lỗi trạng thái bài viết trong module giới thiệu

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#1980]
Khi thay đổi trạng thái bài viết sang "**Ngưng hoạt động**" trong module giới thiệu. Nhưng bài đó vẫn hiển thị ở ngoài trang chủ

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/2dece805fd3a196718f199ab02f688a4374a427f
