### ISSUE TITLE
Thiếu nút checkall khi phân quyền quản lý chuyên mục cho admin news

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#1986]
Không có nút check all, khi cần phân quyền cho site nhiều chuyên mục sẽ rất mệt.

**Comment by anhyeuviolet** [comment]
Cái này em thấy nên áp dụng tại mọi khu vực phân quyền, vì khi có nhiều nhóm thì check phê lắm.

**Comment by hoaquynhtim99** [comment]
Trùng https://github.com/nukeviet/nukeviet/issues/1617
