### ISSUE TITLE
Lỗi admin thêm thành viên không tạo được ảnh đại diện

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1994]
Phiên bản NukeViet   4.0.29Kiểm tra phiên bản NukeViet
Phiên bản PHP    7.0.4
Giao thức giữa máy chủ và PHP   Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.4, apache2handler
Hệ điều hành máy chủ   WINDOWS NT
Phiên bản Database   mysql 5.5.5-10.1.10-MariaDB

**Comment by vanhuonghn011291** [comment]
E xác nhận lỗi tương tự!

**Comment by vuthao** [comment]
Tôi kiểm tra thì không thấy lỗi như @dangdinhtu2014  và @vanhuonghn011291 báo. 
Các bạn hãy xóa cache của trình duyệt và thử lại nhé

ps: 
Nếu ko muốn xóa cache của trình duyệt hãy bật plugin cdn_js_css_image.php Trước khi website gửi nội dung tới trình duyệt
