### ISSUE TITLE
Lỗi backup CSDL khi nâng cấp phiên bản

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#1995]
![13248584_841182756014100_5873349133227063906_o](https://cloud.githubusercontent.com/assets/6817130/15423445/ac3fc294-1ea7-11e6-8892-756437034058.jpg)

Phiên bản NukeViet	4.0.28
Phiên bản PHP	5.6.14
Giao thức giữa máy chủ và PHP	Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.14, apache2handler
Hệ điều hành máy chủ	WINDOWS NT
Phiên bản Database	mysql 5.5.5-10.1.8-MariaDB-log

**Comment by vanhuonghn011291** [comment]
![13256468_841183709347338_2418384716624693659_n](https://cloud.githubusercontent.com/assets/10495040/15423519/0a80e202-1ea8-11e6-8a48-02ad8fffceae.jpg)
Khi Backup bị File not exist...

**Comment by vuthao** [comment]
Lỗi này sẽ tự hết khi nâng cấp các bản sau các bạn nhé

**Comment by dangdinhtu2014** [comment]
Nhưng sẽ phải backup bằng phpmyadmin nếu vậy nên có ghi chú cho bà con đỡ bức xúc

**Comment by vuthao** [comment]
@dangdinhtu2014 hãy kiểm tra lại việc nâng cấp của bạn chắn chắn sai ở chỗ nào đó.
Tôi đã kiểm tra lại không có lỗi như bạn nói.

Theo như ảnh chụp của bạn nâng cấp NukeViet 4.0.28, thì NukeViet 4.0.28 sẽ không thể có biến NV_CHECK_SESSION như hình chụp.

Việc ở đây bạn bức xúc là do bạn đừng đổ cái đó là trách nhiệm của chúng tôi. Nếu kiểm tra lại vẫn có lỗi vui lòng ghi lại dùm tôi video quá trình thực hiện để tôi tiện kiểm tra xem bạn làm lỗi ở bước nào nhé.
