### ISSUE TITLE
Lỗi  phần " giới thiệu" và modul photo  khi nâng cấp lên nuke 4.0.29 từ 4.0.28

### ISSUE THREAD

**Issue by songnhien** [nukeviet/nukeviet#1996]
Em bị lỗi khi nâng cấp từ bản 4.0.29 lên bản 4.0.29 ở trang giới thiệu và modul photo 
lối " Lỗi xử lý giao diện
Lỗi, hệ thống không tồn tại giao diện, bạn cần liên hệ với quản trị site để sửa lại"
mong các anh giúp đỡ
trang lỗi http://hiepduc.net

**Comment by songnhien** [comment]
em cài lại modul nó chạy rồi nhưng mất hết dữ liệu
còn modul photo em nhờ các bác giúp

**Comment by anhyeuviolet** [comment]
https://github.com/anhyeuviolet/module-photos/issues

Photos thì qua bên kia báo lỗi. Bạn báo nhầm chỗ rồi, không ai giải quyết đâu.
