### ISSUE TITLE
[Modules User] ACP - tạo mới tài khoản không có thông báo thành công

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2000]
NV 4.0.29 ( Bản nâng cấp ) - XAMPP 1.8.3 - Trình duyệt: FF 40.x
Mô tả:
Vào link:

```
 /admin/index.php?language=vi&nv=users&op=user_add
```

Điền đầy đủ toàn bộ thông tin. 
Upload avatar, cắt ảnh. 
Chọn đầy đủ các nhóm có sẵn.

Nhấn Thêm tài khoản.
Tại bước này, chắc chắn tài khoản mới đã được tạo. Tuy nhiên không có thông báo như mọi khi:
" Đã tạo xong tài khoản mới, bạn có muốn chọn làm quản trị .. blah blah ..."

Nếu nhấn Thêm tài khoản cái nữa sẽ có:
"Tên người dùng này đã được tài khoản khác sử dụng. Hãy chọn tên khác".

Nếu không có bước tạo Avatar thì không bị.

**Comment by vuthao** [comment]
em vào module CSDL xuất cấu trúc giữ liệu ra gửi qua mail thao a còng vinades chấm vn anh kiểm tra cho.

**Comment by anhyeuviolet** [comment]
Em gửi mail ròi. Anh @vuthao xem hộ em với.

**Comment by vuthao** [comment]
@anhyeuviolet mình kiểm tra thấy cấu trúc dữ liệu của bạn ko sai.
Bạn thử xóa cache của trình duyệt đi nhé, hoặc bật plugin cdn_js_css_image trước khi thêm gửi dữ liệu cho trình duyệt nhé.

**Comment by anhyeuviolet** [comment]
Em đã mở plugin và vẫn bị lỗi.
Lưu ý là lỗi xảy ra khi chọn Avatar, tiến hành cắt và lưu avatar mới bị.
```
Nếu không có bước tạo Avatar thì không bị.
```

Anh thử làm theo các bước em mô tả xem sao.

**Comment by vuthao** [comment]
@anhyeuviolet site cài mới có bị không.
Quay dùm cái video quá trình thực hiện để mình kiểm tra lại nhé.

**Comment by anhyeuviolet** [comment]
Cài mới thì không bị lỗi. Video to quá em up mãi chưa xong.
Để tối về em gửi link anh.

**Comment by anhyeuviolet** [comment]
https://youtu.be/1p0lKZJZ_dE

Anh xem Video xem sao nhé.

Em nhận thấy chỉ bị với site nâng cấp.

Thử trên 2 site nâng cấp đều bị, cài mới ko bị.

---------------


On 25/05/2016 11:36 AM, Vu Thao wrote:
>
> @anhyeuviolet <https://github.com/anhyeuviolet> site cài mới có bị không.
> Quay dùm cái video quá trình thực hiện để mình kiểm tra lại nhé.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nukeviet/nukeviet/issues/2000#issuecomment-221471023>
>

-- 
*Kenny Nguyễn*
*Skype* : nguyentiendat07
*Email* : nguyentiendat713@gmail.com <mailto:nguyentiendat713@gmail.com>
*Website *: iseotech.info <http://iseotech.info> - tradacongnghe.com 
<http://tradacongnghe.com>

**Comment by anhyeuviolet** [comment]
Do tắt chức năng xử lý lỗi của NukeViet. Nếu có lỗi, Ajax sẽ không xử lý được và không trả về kết quả. 
Sẽ kiểm tra và phản hồi lại nếu lỗi vẫn tồn tại.
