### ISSUE TITLE
Lỗi không hiện hình đại diện tượng trưng nhóm

### ISSUE THREAD

**Issue by lyhuutrong** [nukeviet/nukeviet#2001]
Anh thảo và đội code xem lại dùm mình sao mình cài hình đại diện tượng trưng cho nhóm trong admin rồi ạ. Xếp thành viên vào thì nó ko hiển thị hình ảnh tượng trưng cho nhóm ạ. Mong anh thảo và đội code xem lại dùm mình ạ.

**Comment by vuthao** [comment]
@lyhuutrong cái này mình nhớ đã nói với bạn rồi.

hình đại diện tượng trưng cho nhóm hiện tại chưa dùng chỗ nào trong các module mặc định của  nukeviet 4. (Hiện tại chỉ có duy nhất module forum đang dùng trên site https://nukeviet.vn)

Bạn cần phân biện hình đại diện tượng trưng cho nhóm với avata của thành viên.

**Comment by lyhuutrong** [comment]
Đúng rồi ạ. Vậy giờ chưa có module forum hã a

Vào Thứ Tư, ngày 25 tháng 5 năm 2016, Vu Thao <notifications@github.com> đã
viết:

**Comment by vuthao** [comment]
chúng tôi đang phát triển module này và đang chạy thử nghiệm tại: https://nukeviet.vn/vi/forum/

**Comment by lyhuutrong** [comment]
E thấy ok lắm a ạ. Chủ yếu là thấy được tên ảnh tượng trưng cho nhóm và
viết soạn thảo có công cụ là ok rồi ạ. Với quyền cho nhóm nào được xem và
nhóm nào ko được xem là ok rồi ạ.
Chúc a và đội code sớm thành công module forum ạ.
Vào Thứ Năm, ngày 26 tháng 5 năm 2016, Vu Thao <notifications@github.com>
đã viết:
