### ISSUE TITLE
TSL or TLS type

### ISSUE THREAD

**Issue by duongkai** [nukeviet/nukeviet#2002]
In file: admin/settings/smtp.php
19:$smtp_encrypted_array[2] = 'TSL';

Should it be TLS rather than TSL?

**Comment by vuthao** [comment]
Thank @duongkai 
fixed: https://github.com/nukeviet/nukeviet/commit/15c0d012df8cb56794115e51f88237bcf9c5cf7e

**Comment by vuhung** [comment]
lolz :)
