### ISSUE TITLE
Using random incorrectly in Encryption core

### ISSUE THREAD

**Issue by duongkai** [nukeviet/nukeviet#2004]
In https://github.com/nukeviet/nukeviet/blob/ac3b3a3388bc519fbb3ab42ddeec051a6e36eb09/vendor/vinades/nukeviet/Core/Encryption.php

You are using unsafe function to create random string (salt)
line 56:         

```
    $salt = substr(str_shuffle('abcdefghijklmnopqrstuvwxyz0123456789'), 0, 8);
```

line 72:

```
        $salt = substr(str_shuffle(str_repeat('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789', 4)), 0, 4);
```

using str_shuffle to generate random data for cryptographic purpose is wrong. Besides that the source string (alphanumeric) to generate random data is not enough entropy for security

Should switch to use secure random function which using /dev/urandom as random source.

**Comment by vuthao** [comment]
Thank @duongkai 

Ở phiên bản NukeViet 4 đang mã hóa mật khẩu để tương thích với mã hóa mật khẩu mà LDAP có hỗ trợ. Phiên bản tới sẽ thay đổi mã hóa mật khẩu mặc định dùng SSHA512
