### ISSUE TITLE
Compare string wrong in Encryption core

### ISSUE THREAD

**Issue by duongkai** [nukeviet/nukeviet#2005]
In https://github.com/nukeviet/nukeviet/blob/ac3b3a3388bc519fbb3ab42ddeec051a6e36eb09/vendor/vinades/nukeviet/Core/Encryption.php

Line: 101-104

        if ($hash == $validate_hash) {
            return true;
        }
        return false;

Compare string like this will lead to timing attack for guessing hash value. 
Using operator == when comparing string especially hash value is unreliable in security manner.

Should switch to use hash_equals function.

**Comment by vuthao** [comment]
Thank @duongkai 

fixed: https://github.com/vuthao/nukeviet/commit/2b917e6f7729143742c9ed05fdb1879f9d27b144
