### ISSUE TITLE
Useless code in Encryption core

### ISSUE THREAD

**Issue by duongkai** [nukeviet/nukeviet#2006]
To get the code in Encryption core clean

Function __construct, line 28 - 34

```
    if (isset($key{64})) {
        $key = pack('H32', $this->_key);
    }
    if (! isset($key{63})) {
        $key = str_pad($key, 64, chr(0));
    }
```

These lines are not necessary because length of $key is always 40 character in hex mode (SHA1 will produce 160 bit string which equals 40 character string in hex mode).

Function aes_encrypt, line 119-122:

```
    $key = "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0";
    for ($a = 0; $a < strlen($ky); $a++) {
        $key[$a % 16] = chr(ord($key[$a % 16]) ^ ord($ky[$a]));
    }
```

Because 0 ^ A = A (A is whatever you want) so this loop is useless. It is equivalent  to this line of code:

```
    $key = $ky[0:16]
```

line 126:

```
        return mcrypt_encrypt($enc, $key, $val, $mode, mcrypt_create_iv(mcrypt_get_iv_size($enc, $mode), MCRYPT_DEV_URANDOM));
```

Because you are using ECB Mode for AES encryption (**it is NOT SAFE encryption mode**) so you don't need to create random IV (through mcrypt_create_iv) because ECB DO NOT need IV.

**Comment by vuthao** [comment]
@duongkai 
Hiện tại mình dang dự định không sử dụng thư viên mcrypt mà chuyển sang dùng openssl_encrypt, openssl_decrypt (Dùng để mã hóa và giải mã)

Bạn có thể tư vấn khi dùng openssl_encrypt, chọn methods nào không nhỉ
