### ISSUE TITLE
Module users: lỗi dữ liệu mẫu

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#2007]
Trong bảng nv4_users, trường **in_groups**

Với userid = 1 (admin), mặc định khi cài mới thì trường này rỗng, đúng ra ở đây là 1 (nhóm quản trị tối cao)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/pull/2010/commits/ef83a8e056b00e4e01a969ecf4023b863969e567
