### ISSUE TITLE
lỗi nguồn tin ở module ảo module news

### ISSUE THREAD

**Issue by ngoccb** [nukeviet/nukeviet#2011]
Ở module ảo của module news khi chuyển sang trang của phần nguồn tin em bị trắng trang

**Comment by vuthao** [comment]
Bạn vui lòng đọc: https://github.com/nukeviet/nukeviet/blob/master/CONTRIBUTING.md

**Comment by anhyeuviolet** [comment]
Anh @vuthao xem dúp em dòng này.
https://github.com/nukeviet/nukeviet/blob/master/modules/news/admin.functions.php#L514

Dòng này làm cho các module có tên là dấu gạch ngang (-) bị hiểu nhầm URL thành gạch dưới (_), khi đó chuyển sang trang sau sẽ sinh lỗi. 
Ví dụ:
```
tin-tuc
```
sẽ thành 
```
tin_tuc
```

**Comment by vuthao** [comment]
thank @anhyeuviolet để mình kiểm tra và sửa lại các chỗ đó.

**Comment by anhyeuviolet** [comment]
@vuthao Bạn này hôm trước em có teamview xem thử thì cũng ko bị trắng trang, chỉ bị 404 thôi.
Có lẽ lý do khác trong code của bạn ấy gây lỗi.
