### ISSUE TITLE
Lỗi tìm kiếm khi cài module Faq

### ISSUE THREAD

**Issue by quangcuong** [nukeviet/nukeviet#2012]
Môi trường thử nghiệm: localhost
Sever: vertrigo
Phiên bản nukeviet: 4.0.29 (Official)
Phiên bản Module faq: 4.0.29 (FAQ 4 Official)
Khi tìm kiếm trên toàn site báo lỗi: "The localhost page isn’t working
localhost is currently unable to handle this request.
HTTP ERROR 500"

**Comment by vuthao** [comment]
Bạn vui lòng post đúng khu vực của module: https://github.com/nukeviet/module-faq/issues
Lỗi bạn gặp phải đã được fix tại: https://github.com/nukeviet/module-faq/commit/4719810d9f4b5ba981616108d12ca74520f18559

**Comment by sonbbui** [comment]
vẫn chưa fix được ợ. chán nhỉ
