### ISSUE TITLE
Lỗi phân quyền khi đăng bài viết ngoài site

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#2013]
Cấu hình cho thành viên được đăng bài, sửa bài viết
Khi thành viên đăng thành công hiện thông báo đăng thành công bài viết
Sau đó bấm vào sửa: button bị thay đổi thành đăng bài viết, thông báo chuyển thành bạn đã gửi bài viết tới quản trị.
Sau đó xem danh sách bài viết thì lại có quyền xóa bài viết
Tiếp tục bấm xóa thì button thì button lại hiện như lúc đầu

**Comment by anhyeuviolet** [comment]
Cái này, theo mình hiểu là khi bài chưa được duyệt, thì có quyền xoá. Xem như ko gửi bài chờ duyệt nữa.
Nếu Admin duyệt thì sau đó, ko được phép xoá nữa. Cái đó có vẻ hợp lý mà.

**Comment by vuthao** [comment]
@htuyen1994 xem lại nhé, có cần sửa ko, nếu sửa thì sửa như thế nào cho hợp lý.
Nếu thấy @anhyeuviolet đã trả lời phù hợp thì đóng issues này lại nhé.
