### ISSUE TITLE
Tách biệt thẻ Description và thẻ hometext trong module news

### ISSUE THREAD

**Issue by thangbv** [nukeviet/nukeviet#2014]
Hiện tại NukeViet đang nhầm lẫn giữa 2 thẻ này và dùng nó cho cả 2 việc. Dẫn tới việc khó tùy biến được phần mô tả cho đúng ngữ văn cho người đọc cũng như vừa đáp ứng được các đòi hỏi của SEO trong thẻ meta description.
Do vậy đề nghị tách ra như sau:
1. Trường description dùng textarea hoặc thẻ input cho nhập tối đa khoảng 160 ký tự.
2. Trường hometext có thể thêm tùy trọn editor theo nhu cầu chung hoặc không tùy ý.
Trong trường hợp thẻ description không nhập sẽ tự động cắt 160 ký tự từ hometext (đã loại bỏ html) để làm description.

**Comment by vuthao** [comment]
+1 với ý kiến của @thangbv 

Nếu theo ý kiến của bạn cần làm như sau:

1) Thêm cột description, sử dụng kiểu varchar 255 ký tự vào bảng vi_news_detail để lưu trữ mô tả phục vụ mục đích SEO

2) Khi lập trình thêm dữ liệu description, nếu không nhập cứ để trống, khi hiển thị sẽ loại bỏ html tự động cắt 160 ký tự từ hometext 

3) Thêm cấu hình có sử dụng editor cho phần mở đầu bài viết không.

**Comment by vuthao** [comment]
@thangbv em xem đăng ký xử lý phần này được không.

**Comment by yeunukeviet** [comment]
Tôi đề nghị thêm editor cho phần mở đầu bài viết. Riêng tôi thấy nếu có sẽ rất tiện và nên dùng.

**Comment by vuthao** [comment]
@thangbv xem có nhận làm việc này được không nhỉ.

**Comment by hoaquynhtim99** [comment]
Added: https://github.com/hoaquynhtim99/nukeviet/commit/303baf7720d6ca78402cd3a656a6b3f6bc90cf90
