### ISSUE TITLE
[Hỏi] Chức năng gửi mail của nukeviet 

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#2019]
Chức năng gửi mail của nukeviet có phần để khách hàng phần hồi không muốn nhận email và hệ thống theo dõi các mail đã unsubcribed không để tự động lần sau không gửi lại cho email đó

**Comment by vuthao** [comment]
Trong NukeViet mặc định chưa có chức năng gửi mail hàng loạt cho khách hàng, nên phần này chắc chắn chưa có @phongaz
