### ISSUE TITLE
Giao diện mobile_default bị lỗi trên iphone 5, iphone 5s

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#2020]
Khi duyệt web ở iphone 5, iphone 5s.
trình duyệt safari
hệ điều hành ios 9.3.2; 9.3.3

phiên bản nukeviet 4.0 final
Bấm vào menu ở góc trái bên dưới như hình, menu bật lên, khi đưa tay vuốt để tìm đến các mục con thì menu tự biến mất.
![mobile-default](https://cloud.githubusercontent.com/assets/6806295/15651857/57fa8cc0-26ac-11e6-8ac6-d631dc337a93.png)

**Comment by leagentran** [comment]
Tôi cũng bị... như cửa sổ hiện tại của trình duyệt bị vô hiệu hóa hoàn toàn.

**Comment by vuthao** [comment]
Hiện tại mình iphone 5 để test. Bạn nào có tìm cách sửa và đóng góp lại đoạn code đó nhé. Hoặc đợi cái điện thoại đang dùng hỏng cái mới mua mới được :)

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/f25408e3e9e72b1177f1f07bb1c6cfa170d44a1e
