### ISSUE TITLE
[Module Menu] Cơ chế link xuất ra trang chủ linh hoạt hơn

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2021]
Hiện tại, các link được tạo thành trong module là thông qua JS:
```
$('input#link').val(nv_base_siteurl + 'index.php?' + nv_lang_variable + '=' + nv_lang_data + '&' + nv_name_variable + '=' + new_status);

```
Kết quả trả về thường như sau nếu làm trên localhost chẳng hạn.
```
/folder/index.php?language=vi&nv=contact
```

Còn nếu làm 1 domain, thì khi đó link là:
```
/index.php?language=vi&nv=contact
```

Vậy, sẽ phát sinh yêu cầu điều chỉnh, khi mà chuyển site từ localhost lên hosting dùng domain. Khi đó sẽ phải đi sửa từng cái một, do chức năng Nạp lại của module Menu chỉ hỗ trợ sub chứ không hỗ trợ main menu.

Cái này cũng nhỏ nhưng sẽ khá phiền phức khi chuyển site lên xuống. 
Nếu có cách nào đó cải thiện thì tốt hơn.

**Comment by vuthao** [comment]
Trên local dùng domain ảo nhé. Trên site là nukeviet.vn thì domain ảo dùng
nukeviet.my
Vào 01-06-2016 11:06, "Kenny Nguyen" <notifications@github.com> đã viết:
