### ISSUE TITLE
Đề xuất tính năng định dạng bài viết cho module news

### ISSUE THREAD

**Issue by ngoccb** [nukeviet/nukeviet#2022]
Em thấy nếu có tính năng định dạng bài viết kiểu wordpress thì hay hơn và tiện hơn rất nhiều ạ. Có thể tùy chọn bài viết dạng video hoặc hình để dễ dàng quản lý mà không cần phải dùng thêm nhiều module ạ

**Comment by hoaquynhtim99** [comment]
Trùng #800
