### ISSUE TITLE
Lỗi không đăng ký đựoc thành viên

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#2023]
Không đăng ký được thành viên do checkbox agree bị ẩn đi.

https://github.com/nukeviet/nukeviet/blob/master/modules/users/theme.php#L184

```
	if (defined('NV_IS_USER') and !defined('ACCESS_ADDUS')) {
	    $xtpl->parse('main.agreecheck');
	}
```

Có vẻ như cái **defined('NV_IS_USER')** đang sai, đúng là **!defined('NV_IS_USER')**. Chưa lần ra hằng **ACCESS_ADDUS** làm gì nên thôi đưa lên đây.

**Comment by hoaquynhtim99** [comment]
Lỗi này đã được fix tại đây rồi @hongoctrien xem lại thử nhé https://github.com/nukeviet/nukeviet/commit/30dffaf767a14132223977379675ec19295fc4b7

**Comment by hongoctrien** [comment]
oh :). ok
