### ISSUE TITLE
Lỗi menu bootstrap

### ISSUE THREAD

**Issue by hunterlovevnvnn** [nukeviet/nukeviet#2025]
Chào các bạn,

Mình cài bản Nukeviet 4 Official, mình vẫn để nguyên Menu Site và block global bootstrap nhưng khi mình đổi vị trí khác như HEADER, TOP thì Menu Site không còn giữ nguyên được kiểu hiển thị như khi để ở vị trí MENU SITE (mặc định), nó không hover hoặc show ra các menu con cấp 2,3 nữa, ở bản NukeViet 4.0 Official này mình thấy như vậy còn ở bản 4.0.28 thì bình thường, các bạn check lại giúp mình nhé.

Xin cảm ơn!

**Comment by vuthao** [comment]
block  global bootstrap được thiết kế ở vị trí đó bạn, việc từng block di chuyển qua các chỗ khác nhau sẽ rất khó để có thể tương thích hết được.
Cái này bạn cần sửa lại css trong từng trường hợp cụ thể.
