### ISSUE TITLE
Hỏi: thêm plugin cho nukeviet

### ISSUE THREAD

**Issue by quangcuong** [nukeviet/nukeviet#2026]
Theo tôi tìm hiểu, nukeviet có plugin (tạm gọi là chức năng thêm plugin), tức là một tiến trình tự động của nukeviet, thật sự tôi không hiểu vấn đề này. Tôi có đọc qua một số hướng dẫn, nhưng không rõ lắm về cơ chế làm việc, nếu có thể đội code cho một hướng dẫn(có ví dụ cụ thể) để sáng rỏ hơn về plugin của nukeviet không nhỉ?

**Comment by thehung** [comment]
Thảo luận về lập trình mời bạn vào diễn đàn nhé!

**Comment by vuthao** [comment]
Chúng tôi sẽ viết bài này trên wiki của nukeviet trong tuần này nhé bạn.
