### ISSUE TITLE
[Admin] Thời gian phiên làm việc cho Admin/Đăng nhập cùng lúc

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2028]
- Admin không hoạt động một thời gian tại trang admin là bị kích. Nói cách khác nếu Admin đăng nhập và làm việc ngoái trang chủ, ko đụng vào trang Admin thì thi thoảng vẫn bị kích, dù là vẫn đang hoạt động. 
  Thời gian này được quy định thế nào, có được cấu hình lại không ?
- Tính năng đăng nhập cùng lúc trên nhiều trình duyệt/ thiết bị đã được hỗ trợ hay chưa ?
  Nếu có thì quản lý nhiều phiên như thế nào ? Phiên sau có thể "kick" phiên trước hay không ? ( Log-out toàn bộ thiết bị khác).

**Comment by vuthao** [comment]
Mình trả lời ở dưới câu hỏi nhé bạn.
 Admin không hoạt động một thời gian tại trang admin là bị kích. Nói cách khác nếu Admin đăng nhập và làm việc ngoái trang chủ, ko đụng vào trang Admin thì thi thoảng vẫn bị kích, dù là vẫn đang hoạt động.
    Thời gian này được quy định thế nào, có được cấu hình lại không ?

**Có: admin ->  Quản trị -> Cấu hình**

    Tính năng đăng nhập cùng lúc trên nhiều trình duyệt/ thiết bị đã được hỗ trợ hay chưa ?
    Nếu có thì quản lý nhiều phiên như thế nào ? Phiên sau có thể "kick" phiên trước hay không ? ( Log-out toàn bộ thiết bị khác).

**Không, cái sau cùng sẽ đẩy cái trước ra**

**Comment by anhyeuviolet** [comment]
Cảm ơn anh !
Về thời gian đăng nhập, sao mình không cho phép tắt chức năng tự đẩy Admin ra nhỉ ?
Ví

**Comment by vuthao** [comment]
Về thời gian đăng nhập, sao mình không cho phép tắt chức năng tự đẩy Admin ra nhỉ ?
**Do thiết kế ban đầu, vì lý do an ninh tác giả muốn chỉ có 1 người dùng trong 1 thời điểm.**

Ví dụ thời gian set là 0 phút thì là huỷ kích hoạt.
**Do thiết kế ban đầu, hiện tại tối thiểu là 2 phút**

Còn việc hỗ trợ đa phiên thì có thể xem xét hỗ trợ hay không ? 
**Sẽ xem xét trong tương lai, nguyên nhân: để nukeviet 4 ổn định để dùng, chứ phát triển mãi người dùng cuối sẽ rất nản**
