### ISSUE TITLE
Module news: Lỗi quản lý Theo dòng sự kiện (topics) với CSDL lớn

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2029]
> Phiên bản NukeViet  4.0.29
> Phiên bản PHP    5.6.8
> Giao thức giữa máy chủ và PHP   Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
> Hệ điều hành máy chủ   LINUX
> Phiên bản Database   mysql 5.6.24

Em đang test trên CSDL có 31,573 bài viết và 1000 chủ đề.

Khi vào quản lý Theo dòng sự kiện (/admin/index.php?language=vi&nv=news&op=topics) thì trình duyệt "xoay liên tục" rồi báo lỗi 

```
Fatal error: Maximum execution time of 30 seconds exceeded in ...../includes/xtemplate.class.php on line 895
```

**Comment by vuthao** [comment]
Hiện tại phần này chưa được phân trang @hongoctrien.
Để khắc phục em viết thêm phần phân trang cho phần đó nhé.
Ngoài ra việc đếm số lượng bài viết nên lưu luôn vào CSDL để tránh phải count toàn bộ CSDL

**Comment by nguyenphuongdong** [comment]
fix chỗ này ạ. Đang cần

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/8c08cbcefd64efee21d0369f39a192f2fd786c08
