### ISSUE TITLE
Module news: sửa bản tin, không lấy được Theo dòng sự kiện

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#2030]
https://github.com/nukeviet/nukeviet/blob/master/modules/news/admin/content.php#L777
```
->limit(100);
```

Chổ này giới hạn 100 Sự kiện đầu tiên, nếu bài viết dùng sự kiện thứ > 100 thì khi sửa bài viết Sự kiện không có trong danh sách chọn.

**Comment by vuthao** [comment]
Chỗ đó được cố tình thiết kế như thế ban.
Nếu có 10.000 sự kiện sẽ làm treo trình duyệt.
Do đó chúng tôi lấy 100 cái mới nhất, thường là những cái sẽ thường dùng.
Những cái khác khi gõ vào nó sẽ tự động auto điền.

**Comment by hongoctrien** [comment]
Em đọc code vẫn chưa tìm ra.

**Khi sửa bài viết**, nếu Theo dòng sự kiện không nằm trong danh sách 100 cái được load lên, nếu lưu bài viết lại mà không chỉnh sửa gì thêm, thì bài viết này sẽ mất luôn Dòng sự kiện.

**Comment by vuthao** [comment]
@hongoctrien Cái này đã được sửa rồi đúng ko nhỉ. nếu OK rồi đóng dùm anh issues này nhé
