### ISSUE TITLE
Không nhận diện được di động trên một số thiết bị

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2032]
https://www.facebook.com/groups/nukeviet/permalink/1198972173478214/

Khi truy cập vào một số thiết bị thì hệ thống không tự chuyển sang giao diện di động mà vẫn ở nguyên giao diện PC.

Danh sách thiết bị phản ánh: Blackberry, PassPort, MS edge,....

**Comment by vuthao** [comment]
@hongoctrien  lấy dùng agent của trình duyệt nhé, từ đó mới có mẫu phân tích sửa tiếp.

Nếu dùng php để lấy thì lấy dùm anh biến $_SERVER['HTTP_USER_AGENT']

**Comment by hongoctrien** [comment]
Em không có thiết bị, hôm trước mượn máy Blackberry của bạn truy cập thì không tụw chuyển.
Em test lại trên môi trường giả lập của chrome thì riêng con Blackberry cũng không tự chuyển luôn.

**Comment by hoaquynhtim99** [comment]
Hiện việc kiểm tra Blackberry đã được fix ở https://github.com/hoaquynhtim99/nukeviet/commit/529df52a178466ec63c1271b544ab3232e43eed2 Nếu còn có thiết bị nào khác chưa kiểm tra được @mynukeviet tạo thêm Issue mới nhé.

**Comment by mynukeviet** [comment]
ok

**Comment by vuthao** [comment]
@mynukeviet để có thể sửa được cái này, cần lấy được USER_AGENT của trình duyệt

code để lấy có thể tham khảo ở đây

```php

<?php

/**
 * @Project NUKEVIET 4.x
 * @Author VINADES.,JSC (contact@vinades.vn)
 * @Copyright (C) 2014 VINADES.,JSC.
 * All rights reserved
 * @License GNU/GPL version 2 or any later version
 * @Createdate 31/05/2010, 00:36
 */

define('NV_SYSTEM', true);

// Xac dinh thu muc goc cua site
define('NV_ROOTDIR', pathinfo(str_replace(DIRECTORY_SEPARATOR, '/', __file__), PATHINFO_DIRNAME));

require NV_ROOTDIR . '/includes/mainfile.php';

echo '<b>USER_AGENT: </b> ' . NV_USER_AGENT . '<br>';

echo '<b>client_info</b><br>';
echo '<pre>';
print_r($client_info);
echo '<pre>';
```
Có các thông tin này sẽ dễ kiểm tra hơn.

**Comment by mynukeviet** [comment]
ok anh @vuthao
