### ISSUE TITLE
Lỗi cài đặt nukeviet 4 official trên host iPage

### ISSUE THREAD

**Issue by Actionmankaefer** [nukeviet/nukeviet#2034]
Dear đôi code:
Mình tên Nam, tham gia diễn đàn NukeViet đã lâu rồi. Đã tạo nhiều template và chạy một số site. Đa số cài trên Host Pa
Nhưng hôm nay mình thử cài trên host iPage do đang khuyến mãi để kiểm nghiệm.
Vướng mắc mình gặp phải là đến bước 5 không thể kết nối với SQL database.

Mình đã thử up code site mình đang chạy ở Host PA vẫn bị tình trạng tương tự.

Rất mong mọi người có thể giúp đỡ.
Link mình đang test là : muoitom-tayninh.com/nukeviet
Mail mình là "tran gạch dưới namkaefer a còng yahoo.com".

Chân thành cám ơn mọi người đã đọc mail và giúp đỡ.
Nam!

**Comment by vuthao** [comment]
bạn gửi tài khoản hosting qua email thao a còng vinadeses chấm vn mình kiểm tra nhé
