### ISSUE TITLE
Vấn đề code

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#2035]
Đội code kiểm tra đoạn này có vẻ bất hợp lý thì phải
https://github.com/nukeviet/nukeviet/blob/develop/modules/users/funcs/active.php#L103

**Comment by vuthao** [comment]
@dangdinhtu2014  giải thích kỹ hơn dùm mình nhé
@htuyen9x  kiểm tra cái này có phải do em viết gây ra ko nhé.

**Comment by dangdinhtu2014** [comment]
Truy vấn xóa từ bảng users chứ không phải bảng users_reg mà lại xóa bằng userid của bảng users_reg

**Comment by htuyen1994** [comment]
func này e không viết anh ạ. 
Nhưng theo em hiểu là đoạn này viết đúng mục đích nhé anh @dangdinhtu2014 
Cụ thể func này xử lí kích hoạt tài khoản, đối với trường hợp kích hoạt qua mail,
sau khi đã thêm tài khoản vào bảng users thì cần thêm userid đó vào bảng info. 
Nếu không thêm được vào thì xóa hẳn userid đó tại bảng user đi anh nhé.
Nếu không xóa thì có thể gây lỗi đối với dữ liệu tùy biến
```
if ($db->exec('INSERT INTO ' . NV_MOD_TABLE . '_info (' . implode(', ', array_keys($query_field)) . ') VALUES (' . implode(', ', array_values($query_field)) . ')')) {
                $db->query('UPDATE ' . NV_MOD_TABLE . '_groups SET numbers = numbers+1 WHERE group_id=4');
                $db->query('DELETE FROM ' . NV_MOD_TABLE . '_reg WHERE userid=' . $row['userid']);
                $check_update_user = true;

                nv_insert_logs(NV_LANG_DATA, $module_name, $lang_module['account_active_log'], $row['username'] . ' | ' . $client_info['ip'], 0);
            } else {
                $db->query('DELETE FROM ' . NV_MOD_TABLE . ' WHERE userid=' . $row['userid']);
            }
```

**Comment by dangdinhtu2014** [comment]
Vậy mới nói là sai mà lại. Hiểu đúng nhưng truyền biến sai 
$row['userid'] của bảng reg chứ không phải là $userid của bảng user. Làm như này có thể gây họa xóa thành viên ở bảng user có userid là userid của bảng reg. Lỗi chết người đấy
function user_waiting.php trong admin cũng lỗi tương tự dòng 97
