### ISSUE TITLE
Cải tiến chức năng chọn trạng thái khi lưu bài viết trong news

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2037]
Module News hiện tại chỉ có chế độ lưu nháp và đăng bài với người có đủ quyền. Cần hiện đầy đủ tùy chọn trạng thái đăng bài cho admin với những quyền mà người đó được cấp.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/049d876587b88e41e316f58c2ee71e17d6df4ae2
