### ISSUE TITLE
Tùy chọn xóa hoặc không xóa ảnh gốc

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2038]
Hiện tại, ảnh sau khi cắt sẽ bị xóa ảnh gốc. Cần bổ sung tùy chọn cho admin xóa hoặc không xóa vì không phải lúc nào người ta cũng muốn xóa ảnh gốc.

**Comment by hoaquynhtim99** [comment]
Đã thêm tại https://github.com/hoaquynhtim99/nukeviet/commit/e76b24ab51d3d8df9da8636ff27e1534c37e4c2a
