### ISSUE TITLE
[Breadcrumb] lỗi thứ tự chuyên mục khi có sub-category - PHP7

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2039]
http://nukeviet.xyz/thong-cao-bao-chi/nukeviet-4-0-co-gi-moi-18.html

Nhìn breadcrumb sẽ là:
Trang chủ > Thông cáo báo chí > Tin tức
Nhưng Tin tức là thư mục chứa Thông cáo báo chí.
Lỗi này chỉ bị trên PHP 7.x
Các bản 5.x test ko thấy lỗi.

```
SORT( $array_mod_title, SORT_NUMERIC );
```

---

Phiên bản NukeViet   4.0.29
Phiên bản PHP    7.0.6
Giao thức giữa máy chủ và PHP   Apache/2.2.15 (CentOS), apache2handler
Hệ điều hành máy chủ   LINUX
Phiên bản Database   mysql 5.5.49

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/26030187e25c5f1dc5340d098b040e7694da0764
