### ISSUE TITLE
[Lỗi] Cấu hình cookie session

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2040]
/admin/index.php?language=vi&nv=settings&op=variables

Cái Thời gian tồn tại session sửa kiểu nào nó cũng về 0.
Có tính là lỗi không ạ ?
Và 
```
cookie secure 	
cookie httponly
```

Hai cái đó có Lang cho nó ko hay mặc định vậy luôn ạ ?

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/ffb822bf51acb161a1f7d9a62c9fbc9241e97142

Hai cái kia là có lang nha bạn nhưng mà lang đó vẫn để theo tiếng anhm dịch ra tiếng việt sẽ khó hiểu hơn
