### ISSUE TITLE
[News] Sai $op khi chỉnh sửa nhóm tin (groups).

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2042]
Mặc định cài mới News có 2 nhóm tin là Tin mới và Tin cập nhật ( Hoặc cái gì đó gần như vậy ).
Vào ACP, nhấn thay đổi Chọn mặc định khi tạo bài viết hoặc Số liên kết.
Sau đó nhấn sửa => Wrong URL.

https://github.com/nukeviet/nukeviet/blob/master/modules/news/admin.functions.php#L462

**Comment by hoaquynhtim99** [comment]
Thanks, fixed: https://github.com/hoaquynhtim99/nukeviet/commit/6b98553589f1977403d8804c7ae368f0616df571
