### ISSUE TITLE
Module news: Chia sẽ chủ đề theo dòng sự kiện không hiển thị ảnh

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#2043]
Chia sẽ chủ đề theo dòng sự kiện không hiển thị ảnh đúng như ảnh chọn trong quản lý theo dòng sự kiện.

Chưa thấy có og:image

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/cc78c1fa14499d517137bccaedf8c24c0ac3d9c7
