### ISSUE TITLE
Module news: Thêm hộp thoại xác nhận xóa Dòng sự kiện

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2044]
/admin/index.php?language=vi&nv=news&op=topics

Khi xóa Dòng sự kiện ở đây thì nó xóa luôn chẳng thấy hỏi han gì.

**Comment by vuthao** [comment]
Nếu không có bài viết nào nó sẽ xóa luôn, còn nếu có bài viết trong sự kiện nó sẽ hỏi cẩn thận @hongoctrien
