### ISSUE TITLE
Module news: đánh giá bài viết không tự cập nhật điểm

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#2046]
Khi đánh giá xong bài viết, không thấy thông báo thành công cũng không tự cập nhật dòng **Tổng số điểm của bài viết là: 5 trong 1 đánh giá**, phải khi reload trang mới thay đổi

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/2dc5e3298c48995aafd5eacb286ef64acfeaa323
