### ISSUE TITLE
Tối ưu lại cache

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2048]
Khi sử dụng `Memcached` hoặc `Redis` thì các code check cache kiểu 

```php
filemtime(NV_ROOTDIR . '/' . NV_CACHEDIR . '/' . $module_name . '/' . $cacheFile) >= $pa
````

sẽ không còn hợp lý do đó cần viết thêm chế độ hết hạn (Time To Live - TTL) cache với `Memcached` và `Redis`, đối với Files cache cần đưa tham số TTL vào phần get cache để check.

**Comment by vuthao** [comment]
Thế thì phải đưa thêm tham số đó vào em, mặc định để 24h nhé.

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/cfffc34fe9ac0181ebdb7f43a971e6f9665b2962
