### ISSUE TITLE
Lỗi 404 khi nhấp vào modul mới cài .

### ISSUE THREAD

**Issue by songnhien** [nukeviet/nukeviet#2049]
Bây giờ em cài modul doanh bạ doanh nghiệp trên nuke 4.0.29 . Em muốn chỉ có thành viên trong nhóm mới xem được.
Em đưa modul ra menu và  vào " Quản lí modul - Chon mudul cần sửa - " các nhóm được xem" em tick vô " quản lý modul"
- XOng em quay ra trang chính và thoát tài khoản admin. Bây giờ truy cập vào modul nuke hiện ra trang 404.
Nếu em thiết lập modul là " Quản trị tối cao" thì khi thoát khỏi  admin nhấp vào modul thì nike trả về trang " Thông báo từ hệ thống Khu vực chỉ dành cho Người quản trị Về trang chủ"
Em muốn khi nhấp vào tên menu của modul thì nuke trả về trang đăng nhập để nhập user, pass để vào trang chi tiết modul .
Link test: http://songnhien.net/danh-sach-khach-hang/
Mong các anh chị giúp đỡ.

**Comment by hoaquynhtim99** [comment]
Cái đó bạn phải tự điều hướng ở module của bạn nhé, hệ thống không tự làm việc đó.
