### ISSUE TITLE
Lỗi thêm plugin

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2050]
Cấu hình / Cấu hình plugin

Thêm một plugin (bất kỳ) ở vị trí **Trước khi gửi nội dung đến trình duyệt** thì lỗi 500

**Comment by vuthao** [comment]
@một plugin sẽ chỉ phù hợp với từng khu vực khác nhau, nên không thể chố nào cũng cắm vào được.

Chắc sẽ phải quy định cách ặt tên để lựa chọn vào từng vị trí.

**Comment by hongoctrien** [comment]
> Chắc sẽ phải quy định cách ặt tên để lựa chọn vào từng vị trí.

Thì đúng là phải có quy định đầu vào anh ạ, chứ thêm vào, nó lỗi 500, site và qủan trị đều không truy cập được luôn. Phải vào bảng _plugin xóa và xóa ở config_global.php mới xóa nó đi được.

**Comment by vuthao** [comment]
Mình dự định như sau:
Với mối plugin  thêm 1 file .ini để khai báo vị trí cho phép cấu hình.

Ví dụ cdn_js_css_image.php sẽ có file cdn_js_css_image.ini với nội dung
```xml
<?xml version="1.0" encoding="utf-8"?>
<plugin>
    <info>
        <name>Plugin cdn_js_css_image</name>
        <author>Vũ Thảo</author>
        <website>http://nukeviet.vn</website>
        <description></description>
    </info>
    <positions>
		<position>
			<id>3</id>
			<note>Trước khi website gửi nội dung tới trình duyệt</note>
		</position>				
    </positions>
</plugin>
```
Nếu plugin chạy được nhiều vị trí thì sẽ có nhiều position, trong position chỉ bắt buộc có id

**Comment by anhtunguyen** [comment]
Theo anh không cần thiết phải kết nối thêm một file ini nữa, vì như vậy sẽ lại mất thêm một chút ít thời gian cho việc kết nối, phân tích. Theo anh nên đơn giản thế này:
Căn cứ vào tên của file plugin để xác định vị trí.
Ví dụ, có tắt cả 4 trường hợp: Trước khi kết nối CSDL, Trước khi gọi các module, Sau khi gọi các module, Trước khi website gửi nội dung tới trình duyệt. Ta đặt tên cho chúng lần lượt là: A, B, C, D.
Khi đặt tên cho file plugin, bắt buộc phải bắt đầu bằng "A_", hoặc "B_", hoặc "C_", hoặc "D_". Nếu không sẽ không chấp nhận.
Khi include các file plugin này, ta phân tích tên của chúng. Nếu có ^A_ thì cho chay Trước khi kết nối CSDL, có ^B_ thì cho chạy Trước khi gọi các module v.v...

**Comment by vuthao** [comment]
Có những plugin  có thể chạy được nhiều vị trí anh, bằng cách thêm nhiều lượt.
Và việc đặt tên file có chữ A, B, C ... nhìn ko có nghĩa lắm.

Hiện tại em định xử lý việc này chỉ trong admin, ngoài site sẽ không cần can thiệp vào. nên ko ảnh hướng đến hiệu suất.

**Comment by anhtunguyen** [comment]
AB_, AC_, ABCD_...

**Comment by anhtunguyen** [comment]
ABCD ở đây là ví dụ. Em nghĩ ra tên gì có nghĩa hơn và đặt cho nó

**Comment by anhtunguyen** [comment]
Nếu theo cách của em mà không tăng thêm thời gian load trang ở khu vực ngoài site thì cũng OK. Cũng tốt, bài bản.
