### ISSUE TITLE
Lỗi khi đăng ký thành viên mới

### ISSUE THREAD

**Issue by thangbv** [nukeviet/nukeviet#2051]
Trang đăng ký thành viên ngoài website hiện tại không đăng ký được. Cụ thể có báo về mã lỗi từ ajax:

> {"status":"error","input":"agreecheck","mess":null,"redirect":""}

**Comment by mrbemp** [comment]
mình cũng thấy lỗi này

**Comment by hoaquynhtim99** [comment]
Anh kiểm tra lại xem có phải đang bật block headline không? Nếu đang bật sửa theo cái này xem hết không https://github.com/nukeviet/nukeviet/commit/0e563f42f1f118cb32f1c193e38d646862afcde8 và bản anh sử dụng là bản phát hành chính thức hay bản đang dev nào

**Comment by hpleduit** [comment]
Mình cũng bị lỗi này... anh nào fix lỗi này chưa ạ

**Comment by hoaquynhtim99** [comment]
Module users hiện đang được chỉnh sửa và chưa hoàn thiện mọi người tạm thời dùng bản phát hành không dùng bản dev, nếu lỗi đăng ký thành viên tham khảo cách xử lý ở đây https://nukeviet.vn/vi/forum/Khong-dang-ky-duoc-thanh-vien-moi-t38835/

**Comment by hoaquynhtim99** [comment]
Hiện tại lỗi này đã được fix ở bản phát triển
