### ISSUE TITLE
mở chiều rộng của website

### ISSUE THREAD

**Issue by nguyengiakt** [nukeviet/nukeviet#2052]
Dear mọi người!

Hiện nay cái website khi dùng những màn hình độ phân giải rộng, thì 2 bên website nó bị dư rất nhiều. Cho mình hỏi cách tăng chiều rộng website ra là chỉnh ở file nào, mình có mò file bootstrap mà ko đc. Mong được giúp đỡ. Cảm ơn rất nhiều

Trân trọng!

**Comment by anhyeuviolet** [comment]
Cái này bạn nên mang lên forum thì hợp lý và mau được trả lời hơn.
