### ISSUE TITLE
Xem xét Facebook Instant Articles cho NukeViet

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2055]
@quoctiepkt 
https://nukeviet.vn/vi/forum/Hepl-Facebook-Instant-Articles-bai-viet-tuc-thoi-tren-nukeviet-t39139/

**Comment by vuthao** [comment]
Tĩnh năng này hiện tại đã phát triển xong, sẽ được cập nhật cho phiên bản tới
