### ISSUE TITLE
Báo lỗi: Theme của Module new 

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#2056]
Trong file theme của module new xuất hiện 2 lần **$global_array_cat**
ở function:
function viewcat_page_new($array_catpage, $array_cat_other, $generate_page)
ngay tại vị trí: 
global $site_mods, **$global_array_cat**, $module_name, $module_file, $module_upload, $lang_module, $module_config, $module_info, **$global_array_cat**, $catid, $page;

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/a223fb9fc55306356bf4e0342455d46ee77a604a
