### ISSUE TITLE
Đầu ngữ cookies nv3

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#2057]
![cookies](https://cloud.githubusercontent.com/assets/6806295/17553984/f274d8dc-5f32-11e6-933e-823e320c3298.PNG)

phiên bản 4.0.29 - official

**Comment by vuthao** [comment]
Vẫn đề này đã xử lý ở bản 4.0.29 rồi anh Phong.

Anh thử xóa hết cookies đi rồi chạy lại xem nó còn tạo lại không nhé.

**Comment by phongaz** [comment]
Sau khi xóa cookies, không nhìn thấy nữa
