### ISSUE TITLE
Cho phép sắp xếp thứ tự bài viết "Theo dòng sự kiện"

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2062]
"Theo dòng sự kiện" có thể vận dụng để viết bài theo chuỗi, VD như seria bài giảng từ bài 1 đến bài 10. Khi muốn chèn thêm bài viết ở giữa thì không làm dược vì không thể sắp xếp.

Nên đề xuất **Cho phép sắp xếp thứ tự bài viết "Theo dòng sự kiện"**

**Comment by vuthao** [comment]
Module Tin tức vận hành theo cơ chế quản lý hiển thị theo ngày tháng.

Nếu muốn quản lý tin sắp xếp sang thứ tự, bạn chuyển sang dùng nhóm tin nhé.

**Comment by hongoctrien** [comment]
Có thể thêm sắp xếp vào chổ danh sách tin trong dòng sự kiện không anh?
`admin/index.php?language=vi&nv=news&op=topicsnews&topicid=8`
Viết mỗi chủ đề tạo 1 nhóm tin thì không ổn lắm

**Comment by vuthao** [comment]
Cơ CSDL không thiết kế cho việc này, nếu làm sẽ phải sửa lại rất nhiều ở phần này

**Comment by thucvinh** [comment]
Cái  này em cũng đang quan tậm. Đang viết
