### ISSUE TITLE
Lỗi không chọn được phần " không hiện thị trong chuyên mục" trong module block_newcenter

### ISSUE THREAD

**Issue by trungtuan2** [nukeviet/nukeviet#2068]
help me check lại phần check chức năng "không hiện thị trong chuyên mục" trong module block_newcenter không hoạt động. thanks 

ps: tôi đang sử dụng nukeviet 4 offical

**Comment by hoaquynhtim99** [comment]
Mình check không thấy lỗi này

**Comment by vuthao** [comment]
Mình kiểm tra cũng không thấy lỗi này, nếu bạn vẫn còn lỗi này vui lòng quay lại màn hình quá trình thao tác gây lỗi, và tạo lại issues mới dùm nhé
