### ISSUE TITLE
Hiển thị số trang nhiều hơn

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2072]
Danh sách phân trang hiện nó ít quá nhìn xấu, đề xuất cho nhiều hơn xí nữa, có cấu hình thì tốt :D

![selection_603](https://cloud.githubusercontent.com/assets/6407361/18271888/e2fd9c86-745e-11e6-862b-9b31500a157c.png)

**Comment by vuthao** [comment]
Nếu làm việc này cần tính đến việc hiển thị trên mỗi thiết bị khác nhau. Hiện tại phân trang này đã tính tối ưu cho mobile

**Comment by hongoctrien** [comment]
Tối ưu cho mobile nhưng trên PC nhìn thiếu thiếu, mình có biến phân biệt PC và mobile rồi nên em thấy kiểm tra ở đây luôn.

**Comment by hoaquynhtim99** [comment]
Hiện tại đã show 3 link mỗi đoạn
