### ISSUE TITLE
Kiểm soát quyền xem nội dung website

### ISSUE THREAD

**Issue by mrbemp** [nukeviet/nukeviet#2076]
Hiện tại mình đang xây dựng 1 thư viện dựa trên Nukeviet 4. Tất cả nội dung trên website này mình muốn đặt ở chế độ riêng tư. Nghĩa là **khi vào website thì việc trước tiên bạn phải làm là đăng ký thành viên hoặc đăng nhập** thì mới vào đc website. Mặc định khi khách vãng lai (người dùng chưa đăng nhập) sẽ k vào được bất kỳ trang nào trên website mà chỉ hiện ra bảng thông báo đăng nhập (login page)
Ở Nukeviet 4 hiện có làm được điều này không ạ? Nếu có xin hướng dẫn mình với, Thanks!

**Comment by thehung** [comment]
Đừng đụng vào cấu hình, bạn chỉ cần vào quản lý module và cấu hình cho tất cả các module là chỉ có thành viên được truy cập là ok. (Duy nhất module thành viên là phải cho phép khách truy cập để còn đăng ký).
P/S: Mình khóa report này lại vì đây không phải chỗ để thảo luận hoặc hướng dẫn sử dụng. bạn vui lòng truy cập forum.nukeviet.vn để gửi câu hỏi và thảo luận nhé!

**Comment by mrbemp** [comment]
Không cấu hình module chỉ cho thành viên truy cập đc. Mình đã thử qua cách này rồi. Có 2 vđề:
1. Đặt module news làm trang chủ thì không cấu hình chỉ cho thành viên truy cập đc. Mặc định module đặt làm trang chủ thì ai cũng có quyền xem.
2. Các module khác nếu cấu hình chỉ cho tv truy cập thì khi khách vãng lai truy cập sẽ báo lỗi 404. Liên kết k tồn tại. Ý mình muốn bắt họ phải login cơ.
Sr mình k post vào 4rum là vì 4rum hầu như k có ai support. Mà mình nghĩ đây cũng là 1 chức năng cải tiến thêm trong phần quản trị website của nukeviet4. Mong bạn hỗ trợ giúp. Thanks!

**Comment by thehung** [comment]
Cái này đơn giản thôi: Đưa module users ra trang chủ & đặt thêm thông báo về việc chỉ có thành viên mới được quyền truy cập lên trang chủ là xong.
