### ISSUE TITLE
Cần thêm 1 nút chức năng cho phép xem lại ảnh minh họa trong bài viết của module tin tức

### ISSUE THREAD

**Issue by volong1012** [nukeviet/nukeviet#2085]
Việc xem lại và thay ảnh minh họa cho bài viết rất khó khăn nếu như có quá nhiều ảnh trong folder - lúc đó sẽ phải tìm kiếm mất thời gian. Do đó em nghĩ cần thêm 1 nút bên cạnh đó để có thể xem được ảnh minh họa đang sử dụng cho bài viết đó (bao gồm : kích thước, dung lượng ảnh).

**Comment by hoaquynhtim99** [comment]
Đã sửa
