### ISSUE TITLE
Module contact: lỗi hiển thị nội dung thông báo

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#2087]
ACP / Liên hệ / Nội dung thông báo, nhập nội dung:

```
<div style="line-height: 25px">
<div><span style="font-size:13px;"><span style="font-size:14px;"><strong><span style="color:rgb(255, 0, 0);">Shop</span> – <span style="color:rgb(255, 0, 0);">Đồ chơi trẻ em</span></strong></span><br />
<span style="color:rgb(0, 0, 255);"><strong>Cung cấp đồ chơi&nbsp;</strong></span><br />
<strong>Địa chỉ</strong>: xxxxxxxxxxxxxxx<br />
<strong>Điện thoại</strong>: xxxxxxxxx</span></div>
</div>
```

Chrome, xem trang liên hệ, nội dung này hiển thị đúng.

![image](https://cloud.githubusercontent.com/assets/6407361/18743472/627f960e-80e3-11e6-85c4-4431e84f3b78.png)

Firefox, nội dung sai, mất hết `br`

![image](https://cloud.githubusercontent.com/assets/6407361/18743550/b9e3190c-80e3-11e6-8521-9d716ec6f811.png)

Vấn đề ở đây không rõ nguyên nhân https://github.com/nukeviet/nukeviet/blob/develop/modules/contact/funcs/main.php#L255

Dùng hàm **nv_editor_br2nl** bị lỗi này.

**Comment by NukeVietCMS** [comment]
Cái này tôi cũng bị như thế

**Comment by thucvinh** [comment]
đã khắc phục mà

**Comment by hoaquynhtim99** [comment]
Chỗ đó nên bỏ hàm đó, cái đó để xuất ra editor (nội dung nằm trong textarea) còn xuất ra hiển thị thì cần xuất trực tiếp không gọi hàm

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/47e1a1cc5b022534a4b9f0bbdf932f31b3768ef3
