### ISSUE TITLE
Lỗi cache sau khi kích họat tài khoản

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#2088]
- Đăng nhập ACP, thấy báo **Công việc chờ xử lý từ các module / Số tài khoản đợi kích họat : 1**
- Click vào link này, chọn Kích họat
- Nhưng khi quay ra lại trang chính vẫn thấy thông báo này, xóa cache đi mới mất

![image](https://cloud.githubusercontent.com/assets/6407361/18992582/52658ee2-8749-11e6-8b90-1f518822ce31.png)

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/8efb2e022ad00e857be9f9a4e87d5f22905ec251
