### ISSUE TITLE
Lỗi  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php/session) failed: Permission denied (13) in file /vendor/vinades/nukeviet/Core/Request.php on line 385

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#2091]
Phiên bản: Nukeviet 4.0.29 final
OS: ‪CentOS Linux 7.1.1503 (Core)‬
Plesk version: 12.5.30 Update #48 ,

**Comment by vuthao** [comment]
Lỗi này liên quan đến việc chmod thư mục lưu trữ session trên server.

Việc này cần sửa trên server, chứ NukeViet không can thiệp được nhé @phongaz

**Comment by phongaz** [comment]
Mục session của server hay của nukeviet vậy bạn?
Mình mò nhưng không thấy

**Comment by hongoctrien** [comment]
Thư mục này đây bạn `/var/lib/php/session`

**Comment by phongaz** [comment]
@hongoctrien cảm ơn bạn. mình thấy mục session đang chmod là 733. có phải chmod lại thành 777 không?
