### ISSUE TITLE
Lỗi cài đặt site

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2097]
Không cài đặt site được qua bước 5 khi SQL_MODE STRICT

**Comment by vuthao** [comment]
Để bật SQL_MODE STRICT, sửa file: D:\xampp\mysql\bin\my.ini
Thêm dòng 
```
sql_mode="STRICT_ALL_TABLES"
```
 vào sau dòng: 
```
[mysqld]
```

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/fb1c2f8a1c019ed39d732012432aa4f330b1bf00
