### ISSUE TITLE
[NV 4.1-Module Users] Về việc sửa Avatar của Thành viên trong ACP

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2098]
Hiện trong ACP, nếu thành viên đã có avatar thì không click vào đó để chọn ảnh khác được mà cần nhấn Xoá, sau đó click chọn ạnh mới.
Vì chưa hiểu rõ lắm ý đồ thiết kế là gì, nên liệu bước này có thể bổ sung phần "click" vào ảnh để chọn ảnh mới hay không ?

**Comment by hoaquynhtim99** [comment]
Đã bổ sung ở https://github.com/hoaquynhtim99/nukeviet/commit/d548e86130a28e75da919113bfad354b7dfa14d8
