### ISSUE TITLE
NUKEVIET 4.0.29 - BỊ LỖI SAI MÃ BẢO MẬT - GỬI PHẢN HỒI TRONG GIAO DIỆN MOBILE

### ISSUE THREAD

**Issue by ntnhut79** [nukeviet/nukeviet#2099]
Trang web của mình tài địa chỉ: http://phanmemthanthien.com ; mình cài đặt bằng mã nguồn Nukeviet 4.0.29; khi mình dùng thiết bị di động truy cập và thử tính năng gửi phản hồi (trong giao diện mobile) thì luôn nhận thông báo là "nhập sai mã bảo mật", mình đã thiết mã bảo mật mặc định nhưng vẫn không được. Mong được hỗ trợ. Xin cám ơn!

**Comment by hoaquynhtim99** [comment]
Chào bạn, mình check thấy gửi bình thường.

**Comment by ntnhut79** [comment]
Cám ơn bạn. Vừa rồi mình đặt lại mã bảo mật 6 kí tự thì ok.
Còn đặt 2 kí tự thì bị lỗi trên ngay liền. Luôn bị báo sai mã
bảo mật.
Vào 09-10-2016 07:03, "Tan Dung Phan" <notifications@github.com> đã viết:

**Comment by ntnhut79** [comment]
Mình đặt lại mã bảo mật 2 kí tự là xuất hiện lỗi trên. Chưa biết tại sao?

**Comment by hoaquynhtim99** [comment]
Mình sẽ check lại vấn đề này

**Comment by hoaquynhtim99** [comment]
Hiện mình check với cả Cool PHP Captcha và Captcha mặc định đều không thấy lỗi, nếu site của bạn có lỗi gửi thông tin FTP và tài khoản quản trị vào hộp thư dungpt a còng vinades chấm vn mình kiểm tra.

**Comment by hoaquynhtim99** [comment]
Cảm ơn bạn, lỗi đã được fix ở đây https://github.com/hoaquynhtim99/nukeviet/commit/5dcde8465922acb996582782b92dcf97c88586c3 nó sẽ được cập nhật ở phiên bản 4.1 chính thức
