### ISSUE TITLE
Lỗi chức năng 2FA

### ISSUE THREAD

**Issue by mrbemp** [nukeviet/nukeviet#2100]
Chức năng 2FA bị lỗi:
- Lần đầu tiên bật 2fa thì ok, quét ok, đăng nhập ok. Xong tắt 2fa tài khoản admin thử ok, bật lại ok, xong tắt đi.
- Lần 2 tạo thử 1 tài khoản khác ở trình duyệt ẩn danh, vào bật 2fa quét qrcode để cài đặt 2fa quét thì quét đc nhưng nhập code thì báo sai code không cho cài đặt, đã thử nhiều lần vẫn k đc.
- Sang trình duyệt cũ (đang login tk admin), cài lại 2fa, lúc này quét code trên app báo qrcode lỗi, refesh lại vẫn báo lỗi. (_lỗi này chắc do dấu "=" trong mã bí mật trong hình bên dưới_)
- Bó tay.

**Comment by mrbemp** [comment]
![1](https://cloud.githubusercontent.com/assets/11897444/19164964/327ad5f0-8c2c-11e6-9faa-c83c9ff446ba.PNG)

Hình như lỗi quét qrcode là do có ký tự "=" này.

**Comment by hoaquynhtim99** [comment]
Chào bạn, lỗi này đã được ghi nhận tại #2096

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/5a7e71fcb3587ca5d4e095752eaa8f7b88cba37b

**Comment by huyhoangytn** [comment]
vậy là hiện ko dùng được tính năng này cho tới khi có bản update phải ko bạn?

**Comment by hoaquynhtim99** [comment]
Vẫn dùng được chỉ có điều có khả năng nó tạo mã lỗi dẫn đến lỗi, tỉ lệ 1/33, bạn cũng có thể sửa theo commit https://github.com/hoaquynhtim99/nukeviet/commit/5a7e71fcb3587ca5d4e095752eaa8f7b88cba37b rất đơn giản để dùng ngay mà không gặp lỗi gì
