### ISSUE TITLE
Bất cập trong tính năng 2FA

### ISSUE THREAD

**Issue by mrbemp** [nukeviet/nukeviet#2101]
Chức năng 2fa này nên để cho admin có thể tự xử lý được trong phần quản trị thành viên. 
Admin có thể tắt 2fa cho tv, hoặc thêm 2fa cho tv. Chứ không lỡ tv mất 2fa, mất cả 10 code dự phòng, thì tv đăng nhập kiểu gì? Admin không xử lý được. 
Nhưng chức năng 10 code dự phòng rất hay, nên giữ.

**Comment by hoaquynhtim99** [comment]
Chào bạn, những chức năng này sẽ được thêm trong tương lai #2067

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/63be5dd2d1ae9e5d12c42483e0d50cd231199e87
