### ISSUE TITLE
[Lỗi JS] Vấn đề từ main.js

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2103]
Cả bản cũ và bản mới (v 4.1) đều báo lỗi này.
Nhưng bản cũ là 3 dòng, còn bản mới là 2 dòng.
![ccc](https://cloud.githubusercontent.com/assets/6290970/19177802/9e493656-8c76-11e6-8b83-aa6cd6a1b180.PNG)

**Comment by hoaquynhtim99** [comment]
Lỗi gì bạn nhỉ, theo cái ảnh đó là do không tồn tại file ảnh trong thư mục upload thôi

**Comment by anhyeuviolet** [comment]
Cảm ơn @hoaquynhtim99.
Mình không nhắc tới phần lỗi 404.
Bạn có thể vui lòng chú ý đến các lỗi TypeError ( 3 dòng liên tục ). 
Các lỗi này không biến mất sau khi đã sửa giao diện theo khuyến cáo.

Nếu đưa jQuery bản 4.0.29 vào chạy thì không có lỗi này.

**Comment by hoaquynhtim99** [comment]
Bạn cho xem demo hoặc gửi cái giao diện đó đây mình mới check được.
