### ISSUE TITLE
Quản lý Files phần cắt ảnh bị lỗi

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#2104]
**Quản lý Files**  phần **cắt ảnh** bị lỗi không thể thực hiện được.
Bị ẩn hết công cụ cắt ảnh.
Khi bấm chọn **Lưu thay đổi** thì hiện thông báo

>  Thông báo 
> Bạn không được cấp quyền thực hiện thao tác này

Khi thực hiện trên phiên bản: **4.1.00**
Tài khoảng quản trị: **Quản trị tối cao**

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/45386d2232ca799191e524214c8a6cb5f52b8c97
