### ISSUE TITLE
Lỗi cài đặt ở bước 5: Field 'description' doesn't have a default value

### ISSUE THREAD

**Issue by vuathongtin** [nukeviet/nukeviet#2105]
SQLSTATE[HY000]: General error: 1364 Field 'description' doesn't have a default value

**Comment by hoaquynhtim99** [comment]
Phần này bạn có thể tạm thời khắc phục bằng cách mở my.ini (file config của MySQL) tìm 

```
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES 
```

Nếu có xóa đoạn

```
NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES 
```

Chỉ để lại

```
sql_mode=
```

**Comment by hoaquynhtim99** [comment]
#2097

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/nukeviet/nukeviet/commit/fb1c2f8a1c019ed39d732012432aa4f330b1bf00
