### ISSUE TITLE
Không tắt được xác thực hai bước

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#2106]
> Phiên bản NukeViet	4.0.29Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.6.8
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.6.24

Bật xác thực 2 bước ở khu vực đăng nhập quản trị => sử dụng ổn.

Vào tắt đi rồi, nhưng khi đăng nhập lại nó vẫn yêu cầu điền mã bảo mật từ điện thoại

**Comment by hoaquynhtim99** [comment]
Tr mô tả thêm quá trình. Bật là bật như thế nào, đơn giản thành viên tự vào thiết lập bật lên hay là quản trị vào phần cấu hình an ninh để bật?

Tắt là tắt thế nào? Quản trị vào cấu hình an ninh chọn không yêu cầu xác thực hay chỉ đơn giản là thành viên tự tắt đi ?

**Comment by hongoctrien** [comment]
Đăng nhập quản trị => Thiết cập an ninh > Yêu cầu xác thực đăng nhập hai bước tại > Tất cả các khu vực => Ok đã xác thực 2 bước thành công

Đăng nhập quản trị => Nhập mã xác minh từ điện thoại => Đăng nhập thành công => Thiết cập an ninh > Yêu cầu xác thực đăng nhập hai bước tại > Không yêu cầu => Lúc này thoát ra, đăng nhập lại vào khu vực quản trị nó vẫn bắt nhập mã xác thưc, mặc dù đã tắt.

**Comment by hoaquynhtim99** [comment]
Đúng rồi Tr cái đó nó vẫn yêu cầu thôi, vì tài khoản vẫn đang bật xác thực hai bước, cái Tr thiết lập an ninh kia là bắt buộc hoặc không bắt buộc thôi. Muốn hết thì thành viên phải vào phần thiết lập tài khoản =>xác thực hai bước => Tắt (chú ý không thể tắt nếu trong thiết lập an ninh là Tất cả các khu vực)

**Comment by hongoctrien** [comment]
ak ra thế.
