### ISSUE TITLE
Lỗi tạo module ảo

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#2107]
> Phiên bản NukeViet 4.0.29Kiểm tra phiên bản NukeViet
Phiên bản PHP 5.6.8
Giao thức giữa máy chủ và PHP Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ LINUX
Phiên bản Database mysql 5.6.24

Tạo module ảo `gioi-thieu-ve-du-lich-s-viet-nam` từ module `news`

Sau khi cài đặt xong, vào trang danh sách bài viết lỗi cảnh báo

```
Nên chú ý: Undefined index: gioi-thieu-ve-du-lich-s-viet-nam in file /modules/news/global.functions.php on line 15
```

> $module_info nó cắt chỉ còn là `gioi-thieu-ve-du-lich-s-v`

**Comment by hongoctrien** [comment]
Trong bảng `nv4_vi_module` trường `title varchar(55)`, trong khi trong bảng `nv4_config` trường `module varchar(25)` nên bị cắt => tên module khác nhau giữa hai bảng

**Comment by vuthao** [comment]
Mình sẽ sửa lại vấn đề này trong bản tới.

Các bạn lập trình cần lưu ý giới hạn các thông số sau của MySQL
```
Database: 63
Table: 63
Column: 64 
Index: 64 
Constraint: 64 
Stored Function or Procedure: 64 
Trigger: 64 
View: 64 
Compound Statement Label: 16
```
http://dev.mysql.com/doc/refman/5.0/en/identifiers.html

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/bb98bf3b1bcaaf3d3274b892b0f6124700fc9135
