### ISSUE TITLE
Thêm checkbox chọn tất cả trong sao chép block

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2109]
Thêm cái checkbox chọn tất cả chứ cả đống khối block chọn từng cái lâu quá @@

![image](https://cloud.githubusercontent.com/assets/6407361/19332555/68195e94-9117-11e6-8706-d326f3d5df5f.png)

**Comment by hoaquynhtim99** [comment]
Added: https://github.com/hoaquynhtim99/nukeviet/commit/125d51a3d0423ebc8e64cd19d53116da09092fe2
