### ISSUE TITLE
Lỗi block đăng ký khi không thể đăng ký và lỗi khi edit avata ở module user của bản 29

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#2110]
Hiện tại 2 lỗi không đăng ký được trên block login và module user bị lỗi lặp thuộc bản 4.0.29 bản chính thức. Không biết bản tiếp theo đã fix chưa?

**Comment by ThinhNguyenVB** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13896524/19337412/2abb7b40-913f-11e6-9df4-d831ebac27b4.png)

**Comment by hoaquynhtim99** [comment]
Các lỗi này hiện đã được fix
