### ISSUE TITLE
Vấn đề với mã 6 số khi đăng nhập

### ISSUE THREAD

**Issue by lhanh1981** [nukeviet/nukeviet#2112]
Sau khi upgrade lên V4.1, nhiều thành viên đăng nhập website có phản hồi là bắt nhập mã 6 số mà không thấy hiện mã 6 số ở đâu khi đăng nhập nên không đăng nhập được. Mặc dù trong phần THIẾT LẬP AN NINH, admin đã để là KHÔNG yêu cầu đăng nhập 2 bước

**Comment by hoaquynhtim99** [comment]
Bạn chụp cái ảnh thiết lập trong admin mình xem thử

**Comment by hoaquynhtim99** [comment]
Phần này bạn kiểm tra lại nhé, nếu vẫn còn lỗi tạo issue khác và mô tả rõ giúp mình
