### ISSUE TITLE
Lổi bước tạo cơ sở dữ liệu

### ISSUE THREAD

**Issue by hpleduit** [nukeviet/nukeviet#2114]
Mình cài đặt mới phiên bản 4.1 nhưng cài đến bước thứ 5 thì lỗi thế này.
SQLSTATE[HY000]: General error: 1364 Field 'description' doesn't have a default value
Ai biết hướng dẫn fix giúp

**Comment by vuthao** [comment]
@hpleduit bạn vui lòng cho chúng tôi biết máy chủ bạn thử nghiệm, để chúng tôi có thể xây dựng môi trường thử nghiệm giống bạn.

Nếu là hosting bạn có thể gửi chúng tôi  tài khoản hosting để test qua địa chỉ email: webmaster@nukeviet.vn để chúng tôi có thể thư nghiệm và fix lỗi

**Comment by hpleduit** [comment]
Mình đang chạy trên localhost dùng vetrigo 2.44
    Apache/2.4.20 (Win32) PHP/5.6.21
    Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
    PHP version: 5.6.21

**Comment by vuthao** [comment]
Lỗi bạn thông báo hiện tại đã được fix, bạn có thể thử lại trên phiên bản mới tại: https://github.com/nukeviet/nukeviet/archive/develop.zip
