### ISSUE TITLE
Lỗi block global html module page và module ảo của page khi kích hoạt đa ngôn ngữ

### ISSUE THREAD

**Issue by thucvinh** [nukeviet/nukeviet#2115]
Khi kích hoạt đa ngôn ngữ và sử dụng block global html thì trình soạn thảo trên ngôn ngữ khác không hiển thị.

Console báo lỗi: 

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
plugin.js?t=G87E10:7 Uncaught TypeError: Cannot read property 'title' of undefined

Trên ngôn ngữ tiếng việt thì bình thường

Môi trường test:

Phiên bản: Nukeviet 4.1

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/839c25ca41c7a1270a651bbbbc69b7ff2cfef202, cần xóa cache trình duyệt để loại lại plugin
