### ISSUE TITLE
[Hỏi] Cái chức năng tự động reload nó vô duyên quá :((

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2116]
Lần này lại bị chơi khăm, đang viết vài dòng lại bị reload. hiu hiu

Có thể đặt cái biến để quy định func nào không tự reload không @hoaquynhtim99 @vuthao 

Ví dụ như khi vực viết bài thì không reload làm gì?

**Comment by hoaquynhtim99** [comment]
Cái này là tự động out luôn chứ chả reload gì nữa, D cũng thấy chỗ này khá bất cập

**Comment by anhyeuviolet** [comment]
Nhiều khi làm việc trên nhiều Tab thì nó cũng reload và kích ra hàng loạt.
Hơi dở là nó ko nhận diện phiên làm việc ở các chỗ khác  nên cứ thích là kích ra.

**Comment by vuthao** [comment]
Phần này theo thiết kế nó như sau:

- Trước khi timeout nó sẽ nổi lên thanh công cụ thông báo sẽ tự động logout , và đếm lùi 1 phút.

- Nếu hết thời gian sẽ out luôn ra, chuyển đến cửa sổ đăng nhập.

- Để cấu hình tham số này trong ACP: Quản trị -> Cấu hình chỉnh thông số: Thời gian kiểm tra lại mật khẩu, nếu admin không sử dụng trình duyệt

- Các "Hơi dở ",  "dở Hơi " mình sẽ kiểm tra và fix vào ngày mai.

**Comment by vuthao** [comment]
Mình đã fix lại khi làm việc trên nhiều Tab  https://github.com/nukeviet/nukeviet/commit/0a9bac2a1648e7bd9207c972c61c7ed179b255d8
