### ISSUE TITLE
Cần cho phép chỉnh sửa và xóa các nhóm tài khoản

### ISSUE THREAD

**Issue by lyhuutrong** [nukeviet/nukeviet#2118]
Chào đội code. Hiện tại mình thấy ở module tài khoản thì cần cho phép chỉnh sửa và xóa như new user,... nhiều khi cũng cần cái tên khác mà nó cứ mặc định vào nhóm ấy hoặc có thể xóa và thêm nhóm khác ạ. Mà bỏ hiệu lực nhóm thành viên thì cũng chả được ạ.

**Comment by vuthao** [comment]
@lyhuutrong các nhóm thành viên không có chức năng xóa nguyên nhân là các nhóm đó thuộc hệ thống quản lý ( Do code lập trìn kiểm tra chặt các nhóm đó để tránh việc sai logic)

Các nhóm khác các bạn có thể sửa được
![untitled](https://cloud.githubusercontent.com/assets/2491500/21676053/cbff252e-d366-11e6-9e7a-511df3ade09c.png)

Nếu không đúng như trên, bạn kiểm tra lại phiên bản mới, còn lỗi vui lòng mô tả sang issues mới nhé.
