### ISSUE TITLE
Báo lỗi email không đúng quy định với domain .top

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#2119]
Khi cài đặt đến bước nhập thông tin website thì phần email báo lỗi **email không đúng quy định** khi điền email như: **info@cameraip.top**
Đổi địa chỉ email tên miền ***.com thì bình thường.
Trong module users không thể sử dụng email dạng abc@abc.top báo lỗi email không đúng quy định.
Tên miền sử dụng là: [cameraip.top](url)
Phiên bản: NV 4.1.00.

**Comment by vuthao** [comment]
bạn có thể sửa lại theo https://github.com/vuthao/nukeviet/commit/e4af5f0b754dc52feafaa6da4c9ed8695a6e5941 hoặc đợi đến bản cập nhật 4.1 sắp tới

**Comment by NukeVietCMS** [comment]
Đã làm theo hướng dẫn và ok rồi. Cảm ơn anh nha
