### ISSUE TITLE
[Góp ý] Thêm chức năng test email

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2120]
Khu vực cấu hình email, mỗi lần cấu hình xong không biết đã cấu hình thành công hay chưa, muốn kiểm tra có phương án khác nhưng hơi rườm rà.

Nếu có thêm nút "Kiểm tra" xem cấu hình thành công hay chưa thì tiện hơn.

**Comment by vuthao** [comment]
Việc kiểm tra email có gửi được không, chỉ có cách quy nhất là gửi mail và kiểm tra xem email có đế hay không.

Ở phiên bản hiện tại đang phát triển đã có sẵn tính năng này "Gửi phản hồi" trong module liên hệ.

**Comment by mynukeviet** [comment]
Cái này em nghĩ không phức tạp, nhưng nếu có thêm một nút test ngayy tại chổ cấu hình nó sẽ hay hơn
