### ISSUE TITLE
Site lỗi không truy cập được khi kích hoạt ssl

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#2121]
Sau khi cài đặt letsencrypt cho trên máy chủ và domain. login admin vào quản trị site và kích hoạt ssl toàn site nhưng sau sau đó site không truy cập được nữa.

Kiểm tra giá trị ssl https trong config table đã được đổi sang 1

File .htaccess cũng được cấu hình để chạy ssl rồi
`#Options +FollowSymLinks

<IfModule mod_rewrite.c>
RewriteEngine On
#RewriteBase /
RewriteCond %{SERVER_PORT} !^443$
RewriteRule (.*)  https://%{SERVER_NAME}%{REQUEST_URI} [L,R]`

Máy chủ: 
CPU	Intel(R) Xeon(R) CPU X5650 @ 2.67GHz (3 core(s))
Version	Plesk v12.5.30_build1205150826.19 os_CentOS 7
OS	CentOS Linux 7.1.1503 (Core)

**Comment by vuthao** [comment]
@phongaz bạn cấu hình như sau nhé:

1) Cấu hình ssl để cho truy cập được site đã, sau đó truy cập site bao giờ được  trên địa chỉ: https://mydomain.com

2) Sau khi đã cấu hình xong ssl thì mới cấu hình kích hoạt ssl toàn site  (Chức năng này của NukeViet chỉ điều hướng không có https sang https)
