### ISSUE TITLE
Lỗi khi đăng ký thành viên trên nukeviet

### ISSUE THREAD

**Issue by songnhien** [nukeviet/nukeviet#2122]
demo http://songnhien.com.vn
Em đã copy mục uer ở module/user và theme/module/user từ bản 4.1 vào mà vẫn lỗi. Em nâng  cấp từ 4.0.29 lên.

**Comment by hongoctrien** [comment]
Lỗi này không thảo luận ở đây được nha @songnhien . Bạn đưa lên forum hoặc diễn đàn ạ.

**Comment by songnhien** [comment]
ủa . cũng là lỗi đăng nhập mà anh. Chắc lỗi 
hệ thống

**Comment by hongoctrien** [comment]
Chừng nào nó lỗi trên default thì mới xử lý ở đây được. Lỗi này xuất phát từ giao diện của bạn dang dùng.

**Comment by hoaquynhtim99** [comment]
Phần này bạn thảo luận ở diễn đàn nhé
