### ISSUE TITLE
[Góp ý] Tùy chỉnh giao diện hàm nv_info_die

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2123]
https://github.com/nukeviet/nukeviet/blob/develop/includes/core/theme_functions.php#L94

Hàm này hiện tại fix giao diện là `info_die.tpl`, đề xuất thêm 1 tham số là **$theme = ‘info_die.tpl’** để lập trình có thể tự thay đổi giao diện thông báo khi họ muốn.

**Comment by hoaquynhtim99** [comment]
Hiện tại trong theme.php của giao diện có thêm hàm `nv_error_theme` đây là hàm tùy biến giao diện riêng cho nv_info_die
