### ISSUE TITLE
Vấn đề về SEO module news: Tags và keywords

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2125]
Vấn đề mô tả tại https://nukeviet.vn/vi/forum/Ket-qua-thu-nghiem-NK-tu-cuoc-thi-SEO-AWARD-t40427/

**Comment by vuthao** [comment]
HIện tại mình đã tách riêng keywords và tags:
1) Thêm trường keywords cho mỗi bài viết và nhập tương tự tags 
2) Có cấu hình cho toàn module: Nếu không nhập keywords  thì sử dụng keywords  chính là các tags

Code sửa đổi tại: https://github.com/vuthao/nukeviet/commit/39d6b8ddf4cabc0d11f2f82f28d50331ec1b6355

Hướng dẫn nâp cấp:
1) cập nhật lên bản 4.3.01
2) Sửa lại giao diện theo hướng dẫn ở đây:
 https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.3#c%E1%BA%ADp-nh%E1%BA%ADt-keywords-cho-module-news-v%C3%A0-c%C3%A1c-module-%E1%BA%A3o-c%E1%BB%A7a-n%C3%B3
