### ISSUE TITLE
Lỗi thể hiện không thể thông tin User

### ISSUE THREAD

**Issue by suppotiin** [nukeviet/nukeviet#2129]
Nhờ mọi người xem giúp, mình có thêm vài trường trong tùy biến dữ liệu User và đã nhập thông tin vào nhưng khi vào xem chi tiết thông tin thành viên thì lại ko đc.
![user2](https://cloud.githubusercontent.com/assets/8897135/20470390/bd39c918-afda-11e6-9cfd-80ac48dc9d3b.png)
![user1](https://cloud.githubusercontent.com/assets/8897135/20470391/bd3fcaf2-afda-11e6-9305-c5a6d601e467.png)

**Comment by vuthao** [comment]
@suppotiin  Bạn vui lòng cho biết phiên bản NukeViet bạn đang sử dụng.

Nếu bạn dùng bản NukeViet 4.0.29 Bạn kiểm tra lại dùm phiên bản tại https://github.com/nukeviet/nukeviet/archive/develop.zip có còn lỗi không. Nếu hết lỗi chúng tôi sẽ phát hành bản NukeViet 4.1.01 thay thế.
