### ISSUE TITLE
Chỉnh sửa chế độ mặc định hiển thị ảnh của bản tin trong news bên dưới phần mở đầu bản tin

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2132]
Hiện chế độ hiển thị ảnh minh họa bên trái phần mô tả ngắn gọn không còn phổ biến nữa do đó cần chuyển sang chế độ hiển thị mặc định là "hiển thị ảnh minh họa dưới phần mô tả ngắn gọn" theo kiến nghị của nhiều người sử dụng.

**Comment by vuthao** [comment]
Phần này đã được sửa trước đó.
