### ISSUE TITLE
Không cài được site, nukeviet 4.1 beta

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#2133]
Cài đặt đến bước 2, click vào bước tiếp theo thì lại chuyển sang bước 1

web admin Plesk, 12.5.30 Update #44 , 
OS: ‪CentOS Linux 7.2.1511 (Core)‬
PHP: 5.6.28
Máy chủ: Localhost via UNIX socket
Kiểu máy chủ: MariaDB
Phiên bản máy phục vụ: 5.5.50-MariaDB - MariaDB Server
Phiên bản giao thức: 10
Người dùng: admin@localhost
Bảng mã máy chủ: UTF-8 Unicode (utf8)
browser: chrome Version 54.0.2840.99 m

Thêm một lỗi các site khác (phiên bản nukeviet 4.0) khi chuyển về host này thì admin không đăng nhập được, mặt dù có thông báo đăng nhập thành công.
Thành viên đăng nhập bình thường

**Comment by vuthao** [comment]
@phongaz Lỗi này liên quan đến việc cài đặt server, bạn liên hệ với quản trị server để cấu hình lại session nhé.
