### ISSUE TITLE
Sửa lại thẻ heading cho module new để tối ưu SEO

### ISSUE THREAD

**Issue by locthanh0410** [nukeviet/nukeviet#2134]
Trong module news có 2 vấn đề em muốn sửa liên kết:
- Chuyên mục trong module news mặc định đang là thẻ h4, Bài viết hiển thị trong chuyên mục là H3
- Các tin liên quan kông có thẻ heading nào nên để là h4 hoặc h3
Em nhờ A Triền hướng dẫn fix: https://mynukeviet.net/hoi-dap/Ho-tro-su-dung-NukeViet/Xin-huong-dan-cach-sua-the-heading-trong-module-news-vi-no-chua-chan-SEO-155/

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/9d7dddb20e58776920aadf19904cb0eebdb9a671
