### ISSUE TITLE
[Module users] Lỗi quản lý tùy biến dữ liệu

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2135]
> Phiên bản NukeViet	4.1.00Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.6.8
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.6.24

Trên danh sách, check vào **Trường dữ liệu bắt buộc** nó load lại rồi mất cái danh sách luôn

![image](https://cloud.githubusercontent.com/assets/6407361/20737189/bfd1daee-b6dd-11e6-9a1b-dc530accd7f2.png)

**Comment by vuthao** [comment]
ở đây phần lập trình như lúc trước chỉ có chức năng hiển thị, click vào nó chuyển sang phần sửa đổi.

Mình đã sửa lại các nút cho đúng với chức năng: https://github.com/vuthao/nukeviet/commit/0f3d798426a2e189e1c4e5f8ac204799ca0d6b2d
