### ISSUE TITLE
[Module users] lỗi chọn nhóm thành viên mặc định

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2136]
Phần tô màu. Khi thêm thành viên, chọn nhóm thành viên thì chổ tô màu đó không hiện để chọn nhóm mặc định, nhưng khi sửa thì nó mới xuất hiện

![image](https://cloud.githubusercontent.com/assets/6407361/20744588/5e5a418e-b70f-11e6-832a-a03452985c50.png)

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/1706013cefe64c5feedf77baf9a96008bcfaf7ca
@hongoctrien kiểm tra lại dùm mình xem đã chuẩn chưa nhé: https://github.com/vuthao/nukeviet/archive/develop.zip
Về nguyên tắc cái: Là nhóm mặc định chỉ hiển thị khi chọn >=2 nhóm thành viên
