### ISSUE TITLE
[Module news] Không cập nhật được số lượt xem bài viết do cache

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2137]
Nguyên nhân là nó nó lưu cache (với quản trị ko lưu cache thì nó cập nhật tức thời), còn với khách hệ thống lưu cache nên nó ko cập nhật ngay dc lượt xem

**Comment by vuthao** [comment]
Để giảm tải truy vấn vào CSDL thì việc này cần thiết.

Để cho số lượt xem có thể cập nhật lại, có thể viết thêm cronjobs tự động xóa cache của module news và các module ảo sau 1 tiếng hoặc 1 ngày.

**Comment by hongoctrien** [comment]
Dạ, biết là thế nhưng nếu không ai hiểu thì họ cứ nghĩ là lỗi, nên em cứ đưa lên đây. :D

**Comment by vuthao** [comment]
Hiện tại mình đã sửa lại cache của news sẽ được dùng trong vòng 1 tiếng.
Update: https://github.com/vuthao/nukeviet/commit/22f9d529ef4b01d7b06e12b297416d4e1414dc5f
