### ISSUE TITLE
Lỗi hàm nv_is_url

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#2138]
Những đường link VD như https://1drv.ms/u/s!Auc_7P8QuDYpgV7CbudSljZG8f-g nó trả về **false**

**Comment by nammtcn** [comment]
trong url có ký tự "=" module quảng cáo báo sai đường dẫn
Vidụ: http://thitranaitu.quangtri.gov.vn/vi/nvlaws/search/q=&cat_id=2&organ_id=2

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/a4144a289639c40dd256b1d78468310336500960

**Comment by nammtcn** [comment]
Thanks
