### ISSUE TITLE
Mã Google Analystics không nằm trong thẻ <Head>

### ISSUE THREAD

**Issue by thangbv** [nukeviet/nukeviet#2141]
Hiện tại phiên bản chính thức mới nhất mã này nằm trong thẻ body chứ không phải thẻ head. trong khi quy định của google mã này phải nằm trong head để dùng đồng bộ cả webmaster tool và google analytics

**Comment by vuthao** [comment]
Mình đã kiểm tra lại với site mới, việc để như cũ vẫn được cả với webmaster tool và google analytics

Tuy nhiên để đúng với quy định mình đã sửa lại tại: https://github.com/vuthao/nukeviet/commit/04a8c0191b436b597693f27bdc193f01cf537835
