### ISSUE TITLE
Cài đặt giao diện không thiết lập các block theo cấu hình

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2142]
> Phiên bản NukeViet	4.0.29Kiểm tra phiên bản NukeViet
> Phiên bản PHP	5.6.28
> Giao thức giữa máy chủ và PHP	Apache, cgi-fcgi
> Hệ điều hành máy chủ	LINUX
> Phiên bản Database	mysql 5.6.34

Trong tập tin cấu hình (themes/ten-theme/config.ini) có 8 block

![image](https://cloud.githubusercontent.com/assets/6407361/21124052/297417a6-c10f-11e6-9b97-aabab504f638.png)

Sau khi chọn **Thiết lập giao diện theo cấu hình mặc định** ở **Quản lý giao diện** thì không cài đặt được hết các cấu hình này  mà chỉ cài được 1 cái

![image](https://cloud.githubusercontent.com/assets/6407361/21124105/70e740d6-c10f-11e6-9414-8744f1f1a46a.png)

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/5acff39cba6d3f0d68b27417518d089f8d89b4ef
