### ISSUE TITLE
Tính năng xác thực 2 bước không hoạt động

### ISSUE THREAD

**Issue by huyhoangytn** [nukeviet/nukeviet#2144]
Hôm nay, tôi bật tính năng xác thực hai bước nhưng gặp lỗi:
Sau khi sử dụng Google Authenticator để quét mã QR trên website, nhưng khi xác nhận 6 số nhận được trên điện thoại vào website thì báo lỗi mã số không đúng.
Link site: https://www.sinhhoc.edu.vn/biology 
Bản nuke đang sử dụng: 4.1.0

**Comment by hoaquynhtim99** [comment]
#2096 Fixed
