### ISSUE TITLE
[Góp ý] Chuyển hàm change_captcha vào hàm hệ thống

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2146]
Captcha là chức năng hệ thống, hàm `change_captcha` hiện đặt ở giao diện **themes/default/js/main.js** không hợp lý lắm.

**Comment by vuthao** [comment]
Có nhưng site không dùng đến module users, chỉ ở dạng cho người dùng view thông tin nên captcha có thể sẽ không dùng đến. Khi đó javascrip có thể lược bỏ. Nên khi thiết kế mình đã di chuyển nó vào giao diện.
Việc di chuyển phần này vào hệ thống là không khả thi ở thời điểm hiện tại, do khi nâng cấp sẽ phải sửa nhiều giao diện làm khó các webmaster nâng cấp site.
