### ISSUE TITLE
không thêm được domain

### ISSUE THREAD

**Issue by jbminhtan** [nukeviet/nukeviet#2148]
có nhiều domain mới không thể thêm vo được trong phần domain chạy site như .boutique .shop .fashion mong nukeviet hổ trợ khẩn

**Comment by vuthao** [comment]
Hiện tại code về việc này chúng tôi đã sửa lại, bạn đợi đến bản phát hành chính thức của NukeViet 4.1 hoặc sửa tạm theo https://github.com/nukeviet/nukeviet/commit/e4af5f0b754dc52feafaa6da4c9ed8695a6e5941
