### ISSUE TITLE
Cần giải pháp cho phần chọn function quá dài trong thiết lập block !

### ISSUE THREAD

**Issue by volong1012** [nukeviet/nukeviet#2149]
Thường thì function của từng module sẽ ko có nhiều nên có thể dễ dàng lựa chọn ! Tuy nhiên cũng có trường hợp 1 module có quá nhiều function thì việc kéo rất phiền phức... 

Ví dụ : 
**Đây là phần 1**
![1](https://cloud.githubusercontent.com/assets/6147555/21414116/4156e12e-c82f-11e6-86cc-1a0bcb94ecd4.jpg)

**Đây là phần 2**
![2](https://cloud.githubusercontent.com/assets/6147555/21414119/5234ea68-c82f-11e6-90ec-17d34a9242d9.jpg)

**Đây là phần 3**
![3](https://cloud.githubusercontent.com/assets/6147555/21414125/5e3e0146-c82f-11e6-91ec-ad4abb2283f0.jpg)

Để chọn được detail em phải kéo khá dài mới được...

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/f287ba2d4c5ae893c12b867f8eecffae193cf3d2
