### ISSUE TITLE
Lỗi thêm thành viên từ ACP

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2162]
> Phiên bản NukeViet	4.1.00
Phiên bản PHP	5.6.8
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.6.24

ACP / Tài khoản / Thêm tài khoản mới. Khi thêm thành viên từ ACP thì CSDL trường groupid không ghi nhận dc nhóm thành viên. Còn khi đăng ký từ ngoài site thì vẫn ghi nhận bình thường.

![image](https://cloud.githubusercontent.com/assets/6407361/21561279/57c2861a-ce9d-11e6-86a0-edb103ceb9a4.png)

**Comment by vuthao** [comment]
Mình kiểm tra thì không thấy lỗi này ở phiên bản hiện tại. @mynukeviet kiểm tra lại dùm xem lỗi này còn bị không nhé

**Comment by mynukeviet** [comment]
> Phiên bản NukeViet	4.1.00Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.6.8
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.6.24

Em vừa pull lại code mới nhất, vẫn bị lỗi này. Thêm thành viên từ khu vực admin nha anh, chứ ko phải đăng ký thành viên 

![image](https://cloud.githubusercontent.com/assets/6407361/21684040/9e2bca6c-d38e-11e6-8c60-16eb9177b1ea.png)

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/191257f0644e276f28d92a82a6134204bd7f4d74
