### ISSUE TITLE
Bổ sung weight cho module freecontent

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#2164]
Nhu cầu thay đổi vị trí các khối content rất nhiều khi tùy biến dạng block

**Comment by hoaquynhtim99** [comment]
Cá nhân mình cho rằng không làm cái này nữa. Module đó sinh ra là để hiển thị random các khối (rất ít khối). Chỉ đơn giản như thế, không nên làm thêm bất kỳ tính năng nào nữa.

**Comment by vuthao** [comment]
Nhu cầu thay đổi vị trí các khối content rất nhiều khi tùy biến dạng block --> cái này có thể dùng module quảng cáo đã có sẵn tính năng order.
