### ISSUE TITLE
bỏ function nv_sendmail để sử dụng class NukeViet\Core\Sendmail

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2166]
function nv_sendmail chỉ có 1 số tham số nhất định, không dùng hết chức năng của PHPMailer

Trong  NukeViet\Core\Sendmail đã viết mở rộng cho PHPMailer

Nên các chức năng khác cần viết lại để nhất quán.

**Comment by hoaquynhtim99** [comment]
Do có thêm nv_sendmail_async, nv_sendmail_from_template, nv_sendmail_async_from_template nữa nên không sửa như mô tả mà hiện tại đã sửa các hàm đều dùng code của NukeViet\Core\Sendmail và thống nhất tất cả các chỗ chỉ dùng hàm
