### ISSUE TITLE
Bổ sung thêm button gửi chờ duyệt khi thêm bài viết

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#2172]
Hiện tại module news khi thêm bài chỉ hiện lưu nháp và đăng bài viêt
Các quyền khác như gửi chờ duyệt, đăng nhưng không publish  chưa có button để chọn
Đề nghị bổ sung full các quyền tương ứng với tài khoản để có thể lựa chọn

**Comment by thehung** [comment]
Cái tính năng này chưa hoàn chỉnh so với thiết kế chức năng (cho bản 4.0).
Cứ làm theo mô tả yêu cầu chức năng ban đầu là sẽ giải quyết được vấn đề:
https://docs.google.com/document/d/162U9qG7S6PZLWXJRH9ZXZ1uZlGwdDMi7-qinHB5XVwI/edit
https://docs.google.com/document/d/1GSLLjnkegx2l9JnfbmY17rnSqGCmsD0jRqYo3i7AfT4/edit
https://docs.google.com/document/d/1hA30Bq2Fcp7s5bMqnFi_T4mAV70YtDrpY2EdhUaIw3o/edit
https://docs.google.com/document/d/1-5XJG9jLZoncvSVhGtyDlapqlVoRMyk1BNQ3g1va73s/edit

**Comment by vuthao** [comment]
Chức năng này có khi phân quyền quản lý cho tài khoản quản lý module.
