### ISSUE TITLE
[Module Users] Trường safemode không tồn tại.

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2185]
Dòng này:

Còn dùng trường safemode
https://github.com/nukeviet/nukeviet/blob/develop/modules/users/funcs/login.php#L207-L213

Nhưng NV 4.1 BETA thì xem trong phpmyAdmin không tồn tại trường này.

**Comment by vuthao** [comment]
@anhyeuviolet vẫn có mà bạn

https://github.com/nukeviet/nukeviet/blob/develop/modules/users/action_mysql.php#L77

**Comment by anhyeuviolet** [comment]
Anh xem lại kỹ dùm em !
`NV_MOD_TABLE . '_openid`
Còn link anh đưa là 
`$db_config['prefix'] . "_" . $module_data`

Nó là _users chứ ?!

**Comment by anhyeuviolet** [comment]
Log lỗi thu được như sau:
`Notice: Undefined index: safemode in /home/tradacon/public_html/SEOERA/includes/core/user_functions.php on line 605`

**Comment by vuthao** [comment]
@anhyeuviolet mô tả dùm mình lỗi gặp phải khi nào để mình chạy lại xem

**Comment by anhyeuviolet** [comment]
Em tích hợp với Xenforo.
https://github.com/anhyeuviolet/nv4-xenforo-integrate

Khi đăng nhập bằng OpenID thì nhận được báo lỗi trên.
Sau đó dù màn hình xuất thông báo thành công, trang được redirect nhưng User ko login .
