### ISSUE TITLE
[Module User - Hỏi] Về login user bằng Open ID khi tích hợp forum

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2186]
Khi xử lý user login bằng OID thì thấy như sau:
https://github.com/nukeviet/nukeviet/blob/develop/modules/users/funcs/login.php#L228-L234

Vậy trong file set_user_login.php thường phải xử lý như thế nào và trả về giá trị gì để login được User ?

Hiện mình đang tích hợp một số mã nguồn forum vào NukeViet, riêng phần này chưa biết xử lý ra sao.
Trước đây tồn tại thuộc tính `NV_IS_USER_LOGIN_FORUM_OK` ( NukeViet 3) thì dùng thuộc tính này để xác định. Hiện tại thuộc tính này ko còn trong bộ mã NukeViet 4, mình hơi bí cách xử lý.

**Comment by hoaquynhtim99** [comment]
Bản chất xử lý ở file set_user_login.php là lưu được SESSION or COOKIE của thành viên có ID $user_id. Còn việc xử lý thế nào thì tùy vào forum tích hợp

**Comment by anhyeuviolet** [comment]
Bạn @hoaquynhtim99  có file mẫu nào dùng cho Nv4.x để làm mẫu không ?
Mình cho login bằng OpenID thì Forum login, còn nukeViet thì thông báo thành công, reload trang login và thấy là vẫn chưa vào. ❌

**Comment by hoaquynhtim99** [comment]
Cái này @anhyeuviolet mang lên diễn đàn để thảo luận nhé, mình xin Close Issue này tại đây
