### ISSUE TITLE
[Module User] Nuke 4.1 Beta - Báo lỗi cảnh báo

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2187]
Thông báo từ Hệ thống 

Nên chú ý: Undefined index: openid_processing in file /modules/users/admin/config.php on line 327 

Khu vực ACP: /admin/index.php?language=vi&nv=users&op=config

**Comment by hoaquynhtim99** [comment]
@anhyeuviolet check lại  từ bản cài đặt mới nhất xem có lỗi không nhé, lỗi này mình không check thấy lỗi này

**Comment by anhyeuviolet** [comment]
Có lẽ là do phần tích hợp cả openid và forum.
Mình sẽ test thêm và phản hồi sau vậy.
