### ISSUE TITLE
Module Contact trường địa chỉ chưa có trong admin

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2191]
@thuvp1995 khi em thêm trường địa chỉ ở ngoài site để lấy thông tin, nhưng trong admin chưa có chỗ nào hiển thị nó.

Em cập nhật code mới sau đó thêm trường địa chỉ trong admin nhé.

**Comment by thuvp1995** [comment]
code em gửi đã có chỗ hiển thị trong phần admin rồi ạ

Vào 09:26 11 tháng 2, 2017, Vu Thao <notifications@github.com> đã viết:
