### ISSUE TITLE
Thêm chức năng "Tạo lại ảnh thumb"

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2208]
Sau khi thay đổi kích thước ảnh thumb thì cần tạo lại ảnh thumb (nếu quản trị có nhu cầu). Đề xuất thêm chức năng này cho module upload (thêm menu khi click chuột phải vào thư mục ở popup filemanage) 

- Xóa tất cả thumb thuộc thư mục đó và tạo lại theo cấu hình mới
- Có cơ chế tạo thumb với số lượng lớn tránh time out

**Comment by vuthao** [comment]
Mình đang làm cái này nhé.
