### ISSUE TITLE
Lỗi Error Class

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2212]
Mô tả:

Môi trường windows server 2012

Lỗi: Class không ghi được log, lỗi 500 khi dùng lệnh 

```php
trigger_error('Sorry! Could not connect to data server', 256);
```

**Comment by vuthao** [comment]
@hoaquynhtim99  Chạy thử đoạn code sau bằng cmd với quyền admin thử xem nhé.

Grant modify permissions For NukeViet 4.1
```
icacls D:\ThuMucChuaWeb\assets /grant IUSR:(OI)(CI)(M)
icacls D:\ThuMucChuaWeb\data /grant IUSR:(OI)(CI)(M)
icacls D:\ThuMucChuaWeb\uploads /grant IUSR:(OI)(CI)(M)
```
