### ISSUE TITLE
Lỗi chức năng cài lại module không hoạt động khi module ngưng hiệu lực.

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2213]
![untitled](https://cloud.githubusercontent.com/assets/2491500/23352198/6095868c-fcf8-11e6-971f-5e13ab6072a3.png)

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/06f53621c3f49783c0e534fcebc4c5bccc8bf899
