### ISSUE TITLE
[Hỏi] báo lỗi 404 khi xem bài viết module page

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2215]
Chẳng biết có phải là lỗi không hay do thiết lập, em tìm mãi chưa ra nguyên nhân. Check với nkv cài mới thì không thấy lỗi, nhưng site đang dùng (đã qua tùy chỉnh) thì lỗi này.

Chuyện là em thêm 1 bài viết ở module page, nhưng khi xem ở ngoài thì báo lỗi 404.

![selection_992](https://cloud.githubusercontent.com/assets/6407361/23387938/11e37f86-fd92-11e6-97e5-f687313a43fd.png)

![selection_993](https://cloud.githubusercontent.com/assets/6407361/23387937/11e277b2-fd92-11e6-9875-3c3dbdb4987e.png)

![image](https://cloud.githubusercontent.com/assets/6407361/23387954/2d8073ca-fd92-11e6-8ab0-d3bb87d52a19.png)

**Comment by hoaquynhtim99** [comment]
Module page và các module ảo của nó không được phép "Loại bỏ tên module khỏi url", NukeViet mới nhất đã tự động chặn cái này trong thiết lập.

**Comment by mynukeviet** [comment]
Ở đây mình đang chọn module Tin tức để loại bỏ. Có nguyên nhân nào nữa không @hoaquynhtim99

**Comment by hoaquynhtim99** [comment]
Module tin tức để loại bỏ thì làm sao có cái đường dẫn kiểu domain.com/ten-bai-viet.html nhỉ?

**Comment by mynukeviet** [comment]
Hình như page nó có quy tắc rewite riêng. Chắc chắn là đang chọn Tin tức (news) luôn đó @hoaquynhtim99

**Comment by mynukeviet** [comment]
Phiên bản NukeViet	4.1.00
Phiên bản PHP	5.5.26
Giao thức giữa máy chủ và PHP	Apache/2, cgi-fcgi
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.5.41

**Comment by vuthao** [comment]
@hoaquynhtim99  đúng là module page có rule riêng như thế.

@mynukeviet: Check với nkv cài mới không bị thì bạn phải kiểm tra kỹ site của mình thôi

**Comment by mynukeviet** [comment]
Site mình mới xây dựng cũng không có chỉnh sửa j về code, chỉ có thay đổi cấu hình này nọ. Nhìn mãi chưa thấy nguyên nhân nào gây ra việc này

**Comment by mynukeviet** [comment]
Đã xác định nguyên nhân.

Trong bảng nv4_config, nếu thay đổi giá trị `rewrite_endurl` thành giá trị `.html` thì sẽ gặp trường hợp này.

Cái này nên kiểm tra và sửa lại link liên kết ở chổ danh sách bài viết luôn @vuthao

**Comment by vuthao** [comment]
Cái đó bạn thay thì phải kiểm tra thôi, những chức năng không có công cụ quản trị, tốt nhất bạn không nên thay đổi do nó chưa được test tất cả các trường hợp.

**Comment by mynukeviet** [comment]
Ok anh
