### ISSUE TITLE
[NukeViet Dev] Users - Không click được phần sửa User.

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2219]
Như nút trong hình bên dưới click mãi ko vào.
![edit-user](https://cloud.githubusercontent.com/assets/6290970/23543070/020e5692-0023-11e7-8fb3-8f0fd6010cc4.PNG)

**Comment by hoaquynhtim99** [comment]
@anhyeuviolet Cung cấp thêm thông tin nhé! - Trình duyệt đang sử dụng

**Comment by anhyeuviolet** [comment]
Firefox mới nhất thôi ah.

**Comment by hoaquynhtim99** [comment]
Thanks @anhyeuviolet. Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/8ad2b02e8c5b62719784fe61ad5e654cc366ecaa
