### ISSUE TITLE
[NukeViet Dev][Thiết lập an ninh] Về phần chú ý của reCaptcha

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2220]
reCaptcha có hoạt động trên localhost nhé !
![recaptcha](https://cloud.githubusercontent.com/assets/6290970/23543651/b3f5ad72-0025-11e7-9373-45806d6a94bf.PNG)

![recaptcha-2](https://cloud.githubusercontent.com/assets/6290970/23543555/497b7bc0-0025-11e7-8330-0887ae9a4a75.PNG)
![recaptcha-3](https://cloud.githubusercontent.com/assets/6290970/23543556/497cd380-0025-11e7-8e91-83e9bcbc4e7d.PNG)

**Comment by hoaquynhtim99** [comment]
Thanks @anhyeuviolet. Updated: https://github.com/hoaquynhtim99/nukeviet/commit/b267d274746feffc5c57cf0564e4a18a5d5828c8
