### ISSUE TITLE
[NukeViet Dev][News] Sai chính tả phần ghi chú Instant RSS

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2221]
Khu vực này:
/admin/index.php?language=vi&nv=news&op=setting

> Chú ý: **URL này là URL chứa toàn bộ bài viết của module, để lấy URL của nguồn cấp cho từng chuyên mục. Sau khi kích hoạt sử dụng tính năng bài viết tức thời xong**, di chuyển vào phần quản lý chuyên mục, nhấp chọn nút hiển thị URL của nguồn cấp RSS bài viết tức thời tại mỗi chuyên mục tương ứng.

Mình nghĩ phải là:

**URL này là URL chứa toàn bộ bài viết của module. Để lấy URL của nguồn cấp cho từng chuyên mục, sau khi kích hoạt sử dụng tính năng bài viết tức thời xong**, di chuyển vào phần quản lý chuyên mục, nhấp chọn nút hiển thị URL của nguồn cấp RSS bài viết tức thời tại mỗi chuyên mục tương ứng.

**Comment by hoaquynhtim99** [comment]
Thanks @anhyeuviolet . Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/f9cd23237f15e0fbfa7e5312787a72df0eb3dfc2
