### ISSUE TITLE
[NukeViet Dev] Cải tiến Cấu hình Meta-Tags

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2222]
Chỗ này nên chấp nhận phần giá trị ( Nội dung (**) ) có thể rỗng khi nhấn lưu lại. Tất nhiên rỗng thì ko xuất ra HTML, nhưng người quản trị có thể lưu lại các loại meta để dành sau này dùng lại.

Ngoài ra một số meta phổ biến nên được điền sẵn với nội dung rỗng để làm mẫu, tiện hơn cho người dùng.
Ví dụ:
Kiểu Nhóm name
Tên Nhóm (*) google-site-verification

**Comment by anhtunguyen** [comment]
@anhyeuviolet Cảm ơn bạn. Trong NukeViet 4.6 đã thêm vào những tính năng mà bạn nêu trên.
