### ISSUE TITLE
[NukeViet Dev][Quản lý Module] Thêm module ảo

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2223]
Dịch chưa hết ( Có lẽ không nên dùng nhiều tiếng Anh ở khu vực tiếng Việt khi dùng được tiếng Việt).

Tên module mới: (*) 
	**(Max: 50 characters)**

**Comment by hoaquynhtim99** [comment]
Thanks @anhyeuviolet. Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/e8e31ff965005313ad607d6229fd5eec0e127a70
