### ISSUE TITLE
[NukeViet Dev][News] Về việc khoá (chiếm quyền ???) khi có thành viên khác đang sửa bài

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2224]
Tạo  1 tài khoản B bất kỳ. Phân quyền là Admin. Gọi God Admin là A.

Vấn đề 1:
Bạn B vào sửa bài trước.
Bạn A vào sau, click sửa bài. Nhưng thông báo lại là "Bạn bị chiếm quyền ... " ????

Vấn đề 2:
Bạn B nhấn sửa bài, để đó không nhấn lưu. Nhấn vào Logo về trang chủ Admin.
Bạn A chờ tới mùa quýt vẫn bị chiếm quyền =]]

Vấn đề 3:
Bạn B nhấn sửa bài, để đó không nhấn lưu. Nhấn vào Logo về trang chủ Admin.

Del acc bạn B, bạn A vẫn bị thông báo lại là "Bạn bị chiếm quyền ... " ????

Sơ bộ mới chỉ kiểm thử 3 vấn đề trên. Chưa nghĩ ra thêm.

**Comment by hoaquynhtim99** [comment]
Mình sẽ kiểm tra lại vấn đề này

**Comment by vuthao** [comment]
Lỗi này cũng đã được ghi nhận trước đó tại: https://github.com/nukeviet/nukeviet/issues/2182

**Comment by anhyeuviolet** [comment]
Bên 2182 thì sai về nội dung thông báo. 
Còn phần này em thiên về một lỗi khác hơn nữa ạ.

**Comment by vuthao** [comment]
thanh @anhyeuviolet mình sẽ sửa lỗi này trong ngày hôm nay

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/d4fa3061fd14f6fb0766c3a2322659e05c2fed0b
