### ISSUE TITLE
[Góp ý] Đề xuất bỏ câu hỏi bảo mật

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2229]
Câu hỏi bảo mật không còn là một giải pháp thông dụng, có nó làm phức tạp thêm cái form đăng ký tài khoản. Đề xuất bỏ đi hoặc cho vào cấu hình bật/tắt

**Comment by huyhoangytn** [comment]
trước ở vbb hay dùng để tránh spam đăng kí, bỏ nó đi thay bằng cái capcha kiểu mới, môi lần ra ngẫu nhiên 1 hình ảnh và yêu cầu nhìn chuyên nghiệp hơn mà vẫn chống được spam :)

**Comment by tanviet12** [comment]
Nên bỏ phần cân hỏi bảo mật đi. Giờ không ai dùng nó cả.

**Comment by hoaquynhtim99** [comment]
Hiện tại NukeViet 4.3 đã đưa câu hỏi bảo mật vào cấu hình hiển thị/không hiển thị, ẩn/hiện khi đăng ký
