### ISSUE TITLE
[Rewrite IIS] Tag xuất hiện lỗi khi tắt chức năng đa ngôn ngữ/xoá ký tự ngôn ngữ

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2234]
URL dạng `/vi/news/tag/tu-khoa` vẫn hoạt động với IIS.
Còn nếu tắt chức năng đa ngôn ngữ đi `/news/tag/tu-khoa` thì sẽ phát sinh lỗi. Không chỉ với news mà cả nhiều module khác (shops chẳng hạn).

Đã mò rất nhiều mà chưa có cách giải quyết.

Thêm vào đó, cơ chế nhận Alias của tag lại khác hoàn toàn so với func groups trong news. Không hiểu vì sao funtion tag này phải có thêm rewrite (thật sự không hiểu). Nó cũng dùng nv_request dạng get để bắt alias chứ ko lấy từ array_op.
Liệu có nên cải tiến phần này không ?

**Comment by vuthao** [comment]
@anhyeuviolet kiểm tra lại dùm bản sau lỗi đó đã fix được chưa nhé: https://github.com/vuthao/nukeviet/archive/develop.zip

**Comment by anhyeuviolet** [comment]
@vuthao Cảm ơn anh.
Em đã thử với IIS 10 và Windows 10.
Hiện tại các vấn đề về Rewrite trên IIS đã được giải quyết.

**Comment by vuthao** [comment]
Mình cũng đã thử với ISS trên windows server 2012 cũng được.
Thank @anhyeuviolet đã tìm ra lỗi này.
