### ISSUE TITLE
Lỗi Function mcrypt_get_iv_size() trên PHP 7 NukeViet

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#2241]
Lỗi NukeViet trên PHP 7 
Function mcrypt_get_iv_size() is deprecated in file /vendor/vinades/nukeviet/Core/Encryption.php on line 142

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/cdf0e5842481996e9594c1885484f80e72f553c7
