### ISSUE TITLE
js chưa được sử dụng

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2244]
Dòng này https://github.com/nukeviet/nukeviet/blob/develop/themes/default/js/main.js#L635 có thấy sử dụng `.fb-share-button` mà trong html chưa thấy có sử dụng

**Comment by hoaquynhtim99** [comment]
Thanks @mynukeviet  Đã xóa ở https://github.com/hoaquynhtim99/nukeviet/commit/2c57c066f1d57affcd4cab4ed554aa16838ec0d4
