### ISSUE TITLE
Module Upload ->Quản lý Files ->Upload từ máy tính không ổn định

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#2247]
Khi vào Module Upload ->Quản lý Files ->**Upload từ máy tính** không ổn định lúc được lúc không.
Phần Upload file từ internet thì được bình thường.
Phiên bản: 4.1.01

**Comment by vuthao** [comment]
@NukeVietCMS muốn sửa, muốn kiểm tra chúng tôi sẽ phải làm như thế nào.

Vui lòng xem lại quy định báo lỗi để chúng tôi có thể kiểm tra và sửa lại.

Ví dụ file không được có rất nhiều nguyên nhân:
- Dung lượng có quá kích thước không
- Loại file là ghì 
- Cấu hình tại phần:      Cấu hình upload  -> Kiểu kiểm tra file tải lên

**Comment by NukeVietCMS** [comment]
Khi chọn Upload từ máy tính thì phần **popup** không bung lên được để chọn file. Lúc được lúc không. Phần này không liên quan đến loại file hay dung lượng, kích thứơc file

**Comment by vuthao** [comment]
Bạn vui lòng đọc lại quy định báo lỗi : https://github.com/nukeviet/nukeviet/blob/develop/.github/CONTRIBUTING.md

**Comment by NukeVietCMS** [comment]
Phiên bản NukeViet	4.1.01Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.5.37
Giao thức giữa máy chủ và PHP	Apache/2, apache2handler
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.5.31
Google Chrome: Phiên bản 56.0.2924.87 
![bao l i khong n d nh](https://cloud.githubusercontent.com/assets/8376014/24089446/5d82b880-0d69-11e7-8843-b27b6c1b4ccd.png)

Video: https://www.youtube.com/watch?v=rLSeQP7HSHg

**Comment by vuthao** [comment]
@hoaquynhtim99 đúng là trên Google Chrome: Phiên bản 56 nó không ổn định.

Nhiếu lúc click vào phải 5 giây sau nó mới bật lên

**Comment by vuthao** [comment]
Hiện tại đã kiểm tra các trình duyệt Mozilla Firefox, Cốc Cốc không bị lỗi này

Với Google Chrome, Phiên bản 56 chỉ bị khi truy cập từ  phần main của module upload bị lỗi, còn vào đăng bài ấn cái popup lên thì không bị

@NukeVietCMS tạm thời chuyển sang dùng Mozilla Firefox tạm nhé.

**Comment by hoaquynhtim99** [comment]
@NukeVietCMS xem thử trên bản Chrome 57.0.2987.133 (Chrome đã có bản cập nhật) có bị vấn đề này không nhé

**Comment by vuthao** [comment]
Mình kiểm tra cũng không thấy còn bị lỗi này.

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/8ba60115db17d74477e701b4ed4c0ee3dcd5f07f
