### ISSUE TITLE
Lỗi sitemap khi chạy ssl

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/nukeviet#2251]
Khi bật ssl thì sitemap bị lỗi không hiển thị

**Comment by vuthao** [comment]
Mình thấy bình thường mà: https://nukeviet.vn/sitemap.xml

Nếu site bạn lỗi gửi link demo, và xem lại quy định báo lỗi để chúng tôi tiện kiểm tra lại nhé.

**Comment by motcaiten** [comment]
Site lỗi https://maynghiengo.vn/sitemap.xml

Bị trắng nhưng Ctrl + U vẫn thấy có code html.

**Comment by vuthao** [comment]
Bạn thử tạo file sitemap2.xml ở thư mục gốc của site với nội dung sau:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/assets/css/sitemapindex.xsl"?>
<sitemapindex xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
	xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"
	xsi:schemaLocation="https://www.sitemaps.org/schemas/sitemap/0.9 https://www.sitemaps.org/schemas/sitemap/0.9/siteindex.xsd">
	<sitemap>
		<loc>https://maynghiengo.vn/sitemap-vi.about.xml</loc>
	</sitemap>
	<sitemap>
		<loc>https://maynghiengo.vn/sitemap-vi.news.xml</loc>
	</sitemap>
	<sitemap>
		<loc>https://maynghiengo.vn/sitemap-vi.page.xml</loc>
	</sitemap>
	<sitemap>
		<loc>https://maynghiengo.vn/sitemap-vi.siteterms.xml</loc>
	</sitemap>
</sitemapindex>
```

Sau đó báo lại để mình kiểm tra kỹ hơn nhé.

Hoặc bạn cài 1 site nào đó khác xem có bị không. chứ mình cài nhiều site chưa site nào bị lỗi cả.

**Comment by quangtruong412** [comment]
Trang của mình [http://thubongthiennga.com] khi up sitemap lên nó lổi chấm than báo thiếu file /sitemap-vi.page.xml là sao nhỉ
