### ISSUE TITLE
[NukeViet Dev] Thiếu ngôn ngữ Eng

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2252]
Notifications from the system Attention 	
Attention: Undefined index: captcha_type_2 in file /admin/settings/security.php on line 98
Attention 	Attention: Undefined index: recaptcha_type_image in file /admin/settings/security.php on line 99 
![4](https://cloud.githubusercontent.com/assets/6290970/24178473/e23fdd78-0edb-11e7-9ad1-74bdbd258e65.PNG)

**Comment by vuthao** [comment]
@anhyeuviolet do phiên bản trên nhánh dev khi phát triển thì ngôn ngữ chưa được chuyển hết.
Trước khi phát hành mình sẽ kiểm tra lại vấn đề này. Hiện tại anh Tú cũng đã bổ sung vấn đề này tại: https://github.com/nukeviet/nukeviet/pull/2249

**Comment by anhyeuviolet** [comment]
Vâng, em hiểu rồi. Do nay có chút việc tìm hiểu trong khu vực này nên báo luôn.
