### ISSUE TITLE
Kiểm tra chức năng nhóm tin và dòng sự kiện

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2254]
1. Chức năng nhóm tin có vẻ được cải tiến ngày càng giống với dòng sự kiện. Liệu có nên xem xét gộp chung?

2. Chức năng dòng sự kiện hiện không cho phép sắp xếp thứ tự bản tin khiến trình tự nội dung trong sự kiện bị đảo lộn nếu cần sắp xếp lại thì không sắp xếp được!

**Comment by vuthao** [comment]
dòng sự kiện hiện viết ra để phục vụ cho News (Tin tức sụ kiện, Báo điện tử ...).
Còn Nhóm tin để làm cho các tin khác mà dòng sự kiện không giải quyết được.

Nhóm tin có hạn chế nó chỉ lưu trữ mặc định 100 tin gần nhất, phục vụ chủ yếu cho các lập trình viên làm block, gom tin.

Hai cái đó không nên đồng nhất, đó là quan điểm của mình khi xây dựng.
