### ISSUE TITLE
Lỗi Cấu hình xác thực Google+ (quyền tác giả)

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2255]
Khi nhập các ký tự đặc biệt vào ô Tên tài khoản profile Google+ tại trang 

Cấu hình SEO ->      Cấu hình xác thực Google+ (quyền tác giả) 

Thì các ký tự đặc biệt không lưu được, Ví dụ nhập NukeViet&Develop thì sẽ bị mất &Develop

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/f49781c31000291a4c980685c31f7cde06affb8f
