### ISSUE TITLE
Đề xuất thêm trường sitetitle ở bảng modules

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2257]
sitetitle: tiêu đề site của module

Vấn đề gặp phải như sau:

- Sử dụng module Ca nhạc làm module ở trang chủ
- Cấu hình tên site là 

```
Module music cho NukeViet tạo lập website nghe nhạc chuyên nghiệp
```

- Khi chia sẻ trang chủ lên mạng xã hội do giá trị

```
<meta property="og:url" content="http://music.nukeviet.vn/vi/ca-nhac/" />
```

Do đó BOT tự load sang `http://music.nukeviet.vn/vi/ca-nhac/` để lấy thông tin. Do ở phần này không tùy chỉnh được tiêu đề site dẫn tới kết quả chia sẻ MXH trang chủ luôn hiện tiêu đề là *Ca Nhạc* và không hiển thị *Module music cho NukeViet tạo lập website nghe nhạc chuyên nghiệp*

> Sẵn tiện mở rộng luôn giá trị sitetitle, description và keywords cho bảng modfuncs

**Comment by motcaiten** [comment]
Trường hợp này em cũng gặp . Thường lấy module news làm module  chính. Khi share lên face thì nó không hiển thị tiêu đề website mà hiển thị là tin tức dưới load link http://domain.com/news/

**Comment by hoaquynhtim99** [comment]
Đã thêm tại https://github.com/hoaquynhtim99/nukeviet/commit/e67f8cd41ab0a2ae963bf58f8b5504449bfb3b82
