### ISSUE TITLE
lỗi chức năng Cấu hình xác thực Google+ (quyền tác giả) 

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2258]
Hiện tại chức năng này chỉ có quản trị tối cao mới được cấu hình.

Cần sửa lại để người điều hành chung có quyền.

**Comment by thehung** [comment]
Quy trình xác thực quyền tác giả với Google+ Như thế nào nhỉ? Sao không để
thành viên tự làm mà lại phải admin?

**Comment by vuthao** [comment]
Thế mới cần sửa chứ @thehung

**Comment by thehung** [comment]
Nếu vậy thì cái chức năng này nên để thành viên tự cấu hình, vì site lớn sẽ
không điều hành chung nào làm thay hết được. Quyền điều hành chung chỉ sử
dụng để can thiệp các trường hợp mà người sử dụng thông thường ko thể làm
hoặc nếu cho làm thì ảnh hưởng đến an ninh hệ thống.

**Comment by hoaquynhtim99** [comment]
@thehung mỗi module riêng thì module đó có thể tự lập trình cái chức năng đó riêng anh, còn cấu hình này chỉ để "chung" mọi module khi cần có thể lấy xài ngay.

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/1f7a1db52492f79ff6114586fbc88469d33cd58e
