### ISSUE TITLE
Kiểm tra tương thích với php 7.1.1

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2259]
Trên php 7.1.1 lỗi

```
Fatal error: Uncaught Error: [] operator not supported for strings
```

Nguyên nhân khi sử dụng `[]` để thêm phần tử cho mảng mà mảng đó chưa được khai báo kiểu array. Cần kiểm tra lại vấn đề này.

**Comment by vuthao** [comment]
Hiện tại mình mới tìm thấy lỗi này tại: 
Illegal string offset 'div_id' in file /admin/modules/main.php on line 23

 Đã fix tại: https://github.com/nukeviet/nukeviet/pull/2261/commits/d26276d0bf1911780d75d594db35285bbe3d4a8d

**Comment by vuthao** [comment]
Ngoài ra có lỗi https://github.com/nukeviet/nukeviet/issues/2241
