### ISSUE TITLE
Lỗi  không đăng nhập được bằng trình duyệt Firefox trên di động

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2268]
Mình đang gặp lỗi này trên chính site nukeviet.vn:
Sử dụng trình duyệt Firefox 52.0.2 trên Android 5.1.1 bị gặp lỗi khi sử dụng chế độ Request desktop site của trình duyệt thì mỗi khi login xong, website báo thành công nhưng site tự load lại một phát là lại trở về tình trạng chưa login.
Chế độ mobile thông thường thì ko bị vậy.

**Comment by hoaquynhtim99** [comment]
Cái này chắc do trình duyệt chứ cũng không biết kiểm tra ra sao luôn anh

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/e2d04a054ffe36c4a6bdc2e9b009134c3d3949cd
