### ISSUE TITLE
Lỗi chuyển hướng link trong admin theme block

### ISSUE THREAD

**Issue by anshpy** [nukeviet/nukeviet#2270]
nukeviet 4.1.01 lỗi chuyển hướng tới link admin theme block mà ko đóng trình duyệt khi thêm mớ hay sửa 1 block

**Comment by hoaquynhtim99** [comment]
Đọc báo lỗi này mình không thể xác định được vấn đề của bạn gặp phải để kiểm tra, bạn đọc lại quy định báo lỗi để mô tả chi tiết hơn:

https://github.com/nukeviet/nukeviet/blob/develop/.github/ISSUE_TEMPLATE.md

**Comment by anhyeuviolet** [comment]
Tải về từ commit sau:
https://github.com/nukeviet/nukeviet/commit/ea65d417cdf2c9746836b9807391d05b9653cd74

Thử nghiệm bằng IIS 10/Windows 10/ PHP 5.5/ Firefox Latest.
01/ Bật kéo thả block.
02/ Sửa một block bất kỳ. Ở đây ta thử sửa block module_block_news_center.

![image](https://cloud.githubusercontent.com/assets/6290970/24692234/36026940-1a02-11e7-8e66-9d5201d04833.png)
03/ Ta nhấn lưu block lại. Ok. 
04/ Toàn bộ trang được reload như sau, thay vì của sổ chỉnh sửa được đóng lại và trang chính được tải lại:

![image](https://cloud.githubusercontent.com/assets/6290970/24692284/6f1db16c-1a02-11e7-9b9e-2f631992c3d2.png)

**Comment by vuthao** [comment]
@anhyeuviolet bạn mới nhất mình đang làm cũng có lỗi này, để mình fix lại nó.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/da96c856964e00aeb8880244105dfd51f2ebbab4

Thank @anshpy , @anhyeuviolet
