### ISSUE TITLE
Đăng nhập bằng OpenID bị lỗi 

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#2272]
Khi dùng OpenID để đăng nhập thì báo đăng nhập thành công nhưng vào phần thành viên thì vẫn báo phải đăng nhập như chưa có đăng nhập vậy.
Kiểm tra trong quản trị admin thì thấy có tài khoảng email đã đăng nhập bằng OpenID.
OpenID: Google, Facebook

**Web**
Trình duyệt: Chrome. 
Phiên bản: 57.0.2987.133
**Mobi**
Điện thoại IOS: iphone 6. 
Điện thoại Android:  Philip, Vivo

Phiên bản nukeviet: develop
Thời gian tải: ‎04, 04, ‎2017, ‏‎17:48:27 PM
Web thử nghiệm: http://bancamera.top

**Comment by hoaquynhtim99** [comment]
Hiện tại kiểm tra không thấy lỗi này, đối với báo lỗi này không biết được phiên bản cụ thể là phiên bản nào. Website thử nghiệm cũng không dùng giao diện mặc định

**Comment by NukeVietCMS** [comment]
Giao diện default phiên bản 4.0.29 đã chỉnh sửa 
Phiên bản Nukeviet đang sử dụng: 4.1.01 
Module users: 4.0.29
Thời gian tải code: ‎04, 04, ‎2017, ‏‎17:48:27 PM

**Comment by vuthao** [comment]
Như thế thì bạn nâng cấp không hết rồi.
Phiên bản 4.1.01 chưa phát hành chính thức. Với các phiên bản chưa phát hành chính thức các bạn không nên sử dụng nó để xây dựng site, bởi  các bản này sẽ liên tục bị thay đổi.
