### ISSUE TITLE
Lỗi khi sửa từ khóa tag

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/nukeviet#2273]
trước khi sửa
![1](https://cloud.githubusercontent.com/assets/10916826/24699975/025ed2a4-1a20-11e7-94ae-1a2b998cc50f.jpg)
Sau khi sữa thành "mã nguồn mở Nukeviet" nó tự động thêm luôn cái tên tag trước đó là nukeviet
![2](https://cloud.githubusercontent.com/assets/10916826/24700078/45153f66-1a20-11e7-9492-4d577e0ebec1.jpg)
 Test trên localhost và cả host linux php 5.5

**Comment by hoaquynhtim99** [comment]
Cái này https://github.com/nukeviet/nukeviet/blob/develop/modules/news/admin/tags.php#L122 Dòng 122 chưa rõ ý định của tác giả

**Comment by anhyeuviolet** [comment]
Cái đấy để khi người dùng tìm bằng từ khoá cũ vẫn có thể tìm thấy kết quả đấy.
