### ISSUE TITLE
góp ý Module menu ( chỉnh sửa cái ghi chú ) 

### ISSUE THREAD

**Issue by anshpy** [nukeviet/nukeviet#2274]
Khi thêm chèn thêm thẻ ảnh rồi
thì nên cho cái note co giản rộng ạ 
hoặc cho nó dạng text luôn,tăng tính linh hoạt
đồng thời thêm lựa chọn cắt chuỗi note nhé
mục đich em định làm là để cái này đây ạ
anh xem qua hình để dễ hình dung nhé

http://www.upsieutoc.com/image/cIluHE
http://www.upsieutoc.com/image/cIlyE0

**Comment by vuthao** [comment]
Theo mình nghĩ cái này thuộc về giao diện, nên bạn cần chỉnh sửa riêng cho giao diện của bạn.

**Comment by vuthao** [comment]
@anshpy Khi cần đính kèm ảnh vào issues này cứ lôi ảnh trực tiếp vào của sổ đang soạn thảo cho dễ xem nhé.

**Comment by hoaquynhtim99** [comment]
Mục đích của bạn không phải là chức năng thiết kế dành cho module bạn có thể sử dụng module freecontent kèm các block giao diện tự viết là có thể có các chức năng như ảnh.
