### ISSUE TITLE
Lỗi cài nukeviet (v4.1.01) bước thứ 4

### ISSUE THREAD

**Issue by hpleduit** [nukeviet/nukeviet#2275]
Lỗi PHP HỖ TRỢ THƯ VIỆN MÃ HÓA OPENSSL
![openssl](https://cloud.githubusercontent.com/assets/4101710/24790243/9b5b02c6-1ba0-11e7-8110-51844abf036b.jpg)
 Đang thử nghiệm trên localhost máy chủ AppServ
![thong tin appserver](https://cloud.githubusercontent.com/assets/4101710/24790327/d224d35e-1ba0-11e7-8219-305f7cc53b94.jpg)
Nhờ anh em hướng dẫn khắc phục lỗi giúp. Cảm ơn.

**Comment by vuthao** [comment]
90% là máy chủ web của bạn chưa kích hoạt thử viện này cho PHP.

Hãy tao file info.php có nội dung như sau:
```
<?php

phpinfo();
```

Chạy nó và kiểm tra xem có đoạn tương tự như sau không
![screenshot 2017-04-07 14 52 07](https://cloud.githubusercontent.com/assets/2491500/24790781/db039734-1ba1-11e7-89be-b47170501e71.png)

Nếu không có liên hệ với nhà cung cấp hosting báo họ kích hoạt lên.

**Comment by hpleduit** [comment]
Chào anh Thảo hiện tại em chỉ cài trên localhost để test thôi chưa đưa lên hosting. Em đang dùng appserv như trên nhưng không có phần openssl như hình anh gửi.
![ssl](https://cloud.githubusercontent.com/assets/4101710/24792362/d9690520-1ba7-11e7-9f8c-8ecbf0685b18.jpg)
Em đã bật (Enable SSL) lên rồi và đã truy cập được https//localhost/ nhưng em chưa cài được.
Cảm ơn anh nhiều

**Comment by vuthao** [comment]
Bạn tìm file php.ini (Thường nó nằm trong C:\Windows\System32 hoặc C:\Windows với appserv)

Tìm đến dòng
```
;extension=php_openssl.dll
```

thay bằng
```
extension=php_openssl.dll
```

Khởi động lại appserv (httpd), hoặc khởi động lại máy

**Comment by hpleduit** [comment]
Cảm ơn anh, cài thành công.

**Comment by hoiuc** [comment]
Đã thay và khởi động lại xampp vẫn không được
