### ISSUE TITLE
Lỗi cache css, images trên giao diện default

### ISSUE THREAD

**Issue by thuongmaiso** [nukeviet/nukeviet#2277]
Từ phiên bản nukeviet 4x sau khi chỉnh sửa template có hiện trạng sau:
- Sửa css
- Thay hình cùng tên
- Sửa js
Thì code không nhận được những nơi đã sửa chỉ trừ khi truy cập trực tiếp vào file nó f5 lại thì mới được
Ví dụ tôi có class body trong style
Tôi muốn sửa phần color xong, tôi phải truy cập  locahost/nukeviet/themes/default/css/style.css f5 lại file này thì nó mới nhận css 
Việc làm này cực kỳ mất thời gian cho người lập trình, cũng như gây bất tiện cho khách hàng. 
Mặc dù xóa cache trình duyệt hay website đều không có tác dụng

**Comment by hoaquynhtim99** [comment]
Phần này bạn có thể vào phần cấu hình Thiết lập plugin thêm plugin cdn_css_js_image trước khi gửi nội dung đến trình duyệt. Kể từ NukeViet 4.1.01 plugin này sẽ được bật sẵn

**Comment by thuongmaiso** [comment]
vui lòng check lại kỹ vấn đề này,  plugin cdn_css_js_image  không tác dụng

**Comment by hoaquynhtim99** [comment]
@thuongmaiso check lại với bản dev nhé, nếu không vui lòng đọc lại thông báo lỗi tại đây: 

https://github.com/nukeviet/nukeviet/blob/develop/.github/ISSUE_TEMPLATE.md

Trong đó chú ý:

- Cung cấp thông tin máy chủ
- Nếu xác định lỗi từ code, vui lòng cung cấp thêm các thông tin về WebServer và trình duyệt:
> - Phiên bản NukeViet: (Ví dụ NukeViet 4.0.21 hoặc NukeViet 2574f2bc8b6f23f9fcfefc021554034e33fbc695 > - là chuỗi xác định commit trên kho code)
> - Môi trường thử Nghiệm: Localhost/ hosting
> - Hệ điều hành: (Ví dụ: Ubuntu 13.10 32-bit)
> - Trình duyệt web: (Ví dụ: Mozilla Firefox 27.0)
> - Máy chủ web: (Ví dụ: XAMPP for Linux 1.8.1 )

....

**Comment by thuongmaiso** [comment]
Đa số người dùng đều bị lỗi không xóa được cache css, js, images.
Đã áp dụng xóa cache trình duyệt lẫn, web không có tác dụng, plugin cdn_css_js_image không tác dụng

Bản develop mới tải cách đây 1h
Môi trường thử nghiệm: localhost
Hệ điều hành: win10
Trình duyệt: chrome, Mozilla Firefox
Máy chủ: xampp

**Comment by anshpy** [comment]
trước 4.0.29 sài ok ko phát sinh lỗi như trên ( từ này có 4.1 beta lỗi đó đã xuất hiện ( phải xóa cache trình duyệt web rất khổ sở ) - mong ra bản mới 9/4/17 sẽ khắc phục lỗi trên

**Comment by hoaquynhtim99** [comment]
@thuongmaiso "Đã áp dụng xóa cache trình duyệt lẫn, web" => Đã xóa cache **trình duyệt** mà không có tác dụng thì khẳng định một câu chỉ có sửa nhầm file thôi bạn! Nếu bạn đã khẳng đinh mình đã bật cdn_css_js_image lên mà không có tác dụng thì chỉ còn con đường bạn gửi teamview để mình check trực tiếp

@anshpy Xem lại comment này nhé https://github.com/nukeviet/nukeviet/issues/2277#issuecomment-292697689
