### ISSUE TITLE
Lỗi khi kiểm tra phiên bản NukeViet

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2286]
Môi trường thử nghiệm xảy ra lỗi như sau:
> - Phiên bản NukeViet: 4.1.01
> - Hệ điều hành: Windows 10
> - Trình duyệt web: Mozilla Firefox 52, Chrome 57
> - Phần mềm máy chủ web: Vertrigo 2.35
> - Môi trường thử nghiệm: Localhost

![anhchup-203](https://cloud.githubusercontent.com/assets/1892900/24840043/0e5b8a84-1d90-11e7-937a-1a31ececd531.jpg)

**Comment by hoaquynhtim99** [comment]
@thehung hiện em đã cài thử Vertrigo 2.35 (PHP 5.5) test với NukeViet 4.4.01 và Vertrigo 2.49 (PHP 5.6.33) test với NukeViet 4.3.00 không thấy lỗi này, nên nhiều khả năng vấn đề này đến từ phần mềm cài đặt, hơn nữa trên môi trường máy chủ thật hầu như không ghi nhận lỗi này. 
Anh check lại xem thế nào nhé!

**Comment by thehung** [comment]
Ok. Vậy tạm thời cứ đóng issue này lại đi em.

Vào 24 thg 1, 2018 14:33, "Tan Dung Phan" <notifications@github.com> đã
viết:
