### ISSUE TITLE
Kiểm tra lại giấy  phép plugins cleanlink của CKeditor

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2287]
NukeViet 4.1.01 hiện có plugins cleanlink của CKeditor chưa rõ giấy phép
![anhchup-205](https://cloud.githubusercontent.com/assets/1892900/24840078/bd444b3a-1d90-11e7-8f17-a6f1153adff1.jpg)

**Comment by hoaquynhtim99** [comment]
Anh @vuthao xem thử cái này nhé, em không rõ plugin này ở đâu nữa tìm không thấy nguồn gốc

**Comment by vuthao** [comment]
@thangbv đã cập nhật tại: https://github.com/nukeviet/nukeviet/pull/2319
