### ISSUE TITLE
Sửa lại thông tin bản quyền trong phần giới thiệu plugins tbvdownload của CKeditor

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2288]
NukeViet 4.1.01 
Plugins tbvdownload của CKeditor cần sửa lại thông tin bản quyền cho phù hợp giấy phép:
![anhchup-204](https://cloud.githubusercontent.com/assets/1892900/24840061/4eb833ac-1d90-11e7-89a1-fb1a54340f91.jpg)
`Bản quyền © Mr.Thang - kid.apt@gmail.com. Giữ toàn quyền.`
Nên sửa thành
`Giấy phép GNU/GPL. Phát triển bởi Mr.Thang - kid.apt@gmail.com.`

**Comment by vuthao** [comment]
@thangbv xem có thể sửa lại phần này không  nhé.

**Comment by hoaquynhtim99** [comment]
@thangbv sao rồi anh, hôm nay cần chốt cái này rồi anh

**Comment by vuthao** [comment]
@thangbv đã cập nhật tại: https://github.com/nukeviet/nukeviet/pull/2319
