### ISSUE TITLE
Hỏi : Cần phương án khắc phục lại ảnh image thumb 

### ISSUE THREAD

**Issue by volong1012** [nukeviet/nukeviet#2289]
Hiện nay ảnh thumb của tin tức và các module khác đang bị nhòe đi do dử sụng padding để tạo chỗ cho border ảnh.
Lấy ví dụ : 1 ảnh thumb dc cấu hình 200px chiều rộng (ở cả module upload  và cấu hình tin tức) khi ra ngoài site hiển thị sẽ bị nhòe tầm 20 - 40% (tùy ảnh) do có thuộc tính padding : 1px trong đó . 
Nếu bỏ thuộc tính này thì ảnh sẽ hiển thị về px gốc của thiết lập (ảnh sẽ nét hơn rất nhiều)

Hướng xử lí có thể là : sử dụng thuộc tính css **outline** để thay thế cho border , nhược điểm của outline là ko thể bo góc.

Đây là hướng xử lí hình ảnh hiện nay của mình ko biết mọi người ai có phương án nào khác ko ??

**Comment by nambmtk1993** [comment]
Việc ảnh Thumb bị nhòe theo mình nhớ NukeViet đã có hướng khắc phục vấn đề này rồi bạn. 
Bạn vào phần **Quản lý File** sau đó tìm **Cấu hình ảnh thumbnail** rồi chỉnh lại kích thước cho nó. 
Ví dụ như ảnh bạn để kích thước 200px thì trong phần đó bạn cũng chỉnh là 200px là được, vì mặc định nó để 100px * 150px mà :)

**Comment by hoaquynhtim99** [comment]
Cấu hình ảnh trong module news là 200.ZZZpx
Ngoài site padding 1 + border 1 => ảnh thực kích thước là 186.ZZZpx
Cấu hình kích thước ảnh Thumb của module upload là 186px

**Comment by ThinhNguyenVB** [comment]
Tốt nhất là cấu hình ảnh thumbnail trong module upload to hơn thì khi ngoài site nó zom dù có padding hay border nó nét hơn cũ mặc định tùy theo ý muốn thiết lập kích thước thumbnail
