### ISSUE TITLE
Về chức năng chèn Logo trong class Image hiện tại của NukeViet.

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2290]
Khi làm việc với class này, mình phát hiện vài thứ khá ngộ.
Về lý thuyết và cũng theo hướng dẫn từ Wiki của Nukeviet, ta ứng dụng như sau:
```
$createImage = new NukeViet\Files\Image(NV_ROOTDIR . '/' . $path . '/' . $file, NV_MAX_WIDTH, NV_MAX_HEIGHT);
$createImage->addlogo($upload_logo, '', '', $config_logo);
```

Trong đó khi dùng phần addlogo, ta truyền vào 4 mảng tham số. Nhưng mình để ý trong rất nhiều chỗ, hai tham số về vị trí logo luôn được bỏ trống. Tuy vậy khi tham khảo hướng dẫn từ Wiki, ta có:

`$image->addlogo( $logo, $align = 'right', $valign = 'bottom' );`
(từ https://wiki.nukeviet.vn/programming4:class#cac_class_co_thuờng_dung)

Khi áp dụng thử với một số module độc lập, mình nhận ra việc truyền 2 tham số  $align, $valign không cho kết quả như mong muốn. Ảnh luôn luôn bị chèn logo ở góc dưới bên phải.
Tuy vậy, đối với công cụ upload ảnh thông qua Quản lý file, logo được đặt ở vị trí cấu hình trước.
Đào sao vào file xử lý upload của phần admin/upload, mình thấy đoạn code như sau:

https://github.com/nukeviet/nukeviet/blob/develop/admin/upload/upload.php#L120-L125
Trong đó, phần xử lý vị trí logo may mắn thay, được ghi chú khá rõ.

```
$config_logo['x'] = $file_size[0] - $w - 5; // Horizontal: Right
$config_logo['y'] = $file_size[1] - $h - 5; // Vertical: Bottom
```
Code trên rõ ràng xác định vị trí mặc định, tức là phía dưới, bên phải cho Logo.
Xử lý tiếp, ta có:

                        // Logo vertical
                        if (preg_match("/^top/", $global_config['upload_logo_pos'])) {
                            $config_logo['y'] = 5;
                        } elseif (preg_match("/^center/", $global_config['upload_logo_pos'])) {
                            $config_logo['y'] = round(($file_size[1] / 2) - ($h / 2));
                        }
                        
                        // Logo horizontal
                        if (preg_match("/Left$/", $global_config['upload_logo_pos'])) {
                            $config_logo['x'] = 5;
                        } elseif (preg_match("/Center$/", $global_config['upload_logo_pos'])) {
                            $config_logo['x'] = round(($file_size[0] / 2) - ($w / 2));
                        }
Tức là tuỳ theo cấu hình từ $global_config truyền vào mà đối chiếu và đưa ra vị trí tương ứng.
Sau đó, xuất ra ảnh mới, thì sẽ là:

`$createImage->addlogo(NV_ROOTDIR . '/' . $global_config['upload_logo'], '', '', $config_logo);`

=> Thuộc tính vẫn không được truyền vào thông qua tham số thứ 2 và thứ 3. Mình cảm thấy kỳ lạ.
Mình thử áp dụng các code bên trên bổ sung vào module độc lập và nhận thấy ảnh có thể chèn logo vào vị trí mong muốn. Nhưng vẫn chưa thoả mãn !
Đào tiếp vào class, ta lại thấy như sau:
```
                if (isset($config_logo['w']) and isset($config_logo['h'])) {
                    $dst_w = $config_logo['w'];
                    $dst_h = $config_logo['h'];
                } else {
                    $dst_w = $logo_info['width'];
                    $dst_h = $logo_info['height'];
                }
```
https://github.com/nukeviet/nukeviet/blob/develop/vendor/vinades/nukeviet/Files/Image.php#L734-L766

Tới đây mình hoàn toàn hết hiểu vì ngoài tầm. Nhưng có vẻ vị trí của logo từ $align và $valign, thay vào đó lấy vị trí từ mảng $config_logo ( ??? Không chắc chỗ này).

Mình quả thực không hiểu class này. Module độc lập có thể giải quyết được vấn đề vị trí ảnh, nhưng phải tốn kha khá dòng code cho một class lẽ ra có sẵn và xử lý sẵn.
Liệu có phương án nào tốt hơn không ?

**Comment by hoaquynhtim99** [comment]
@anhyeuviolet trên wiki ghi nhận phiên bản cũ của class, phiên bản mới có thêm tham số thứ tư, khi tham số thứ tư truyền vào (mảng 1 chiều gồm x và y) thì sẽ bỏ qua hai tham số 2 và 3. Nếu không truyền tham số thứ 4 vào thì hai tham số 2 và 3 được dùng để xác định vị trí (chung quy ra là class tự build ra tham số thứ 4)

**Comment by anhyeuviolet** [comment]
Vậy thì cuối cùng class nên dùng như thế nào :(

**Comment by hoaquynhtim99** [comment]
Hiện mình đã cập nhật hướng dẫn: https://wiki.nukeviet.vn/programming4:class#images_class @anhyeuviolet  dùng thế nào cũng được tùy sở thích 😸

**Comment by anhyeuviolet** [comment]
Oke, cảm ơn nhiều nha.
Để nghiên cú thêm ! :D
