### ISSUE TITLE
Về: Chế độ Debug cho NukeViet

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2291]
NukeViet hiện xử lý và ẩn toàn bộ báo cáo lỗi.
Cái này nhiều lúc rườm rà trong quá trình phát triển và tìm lỗi.
Liệu chúng ta có thể thêm 1 cái nút cấu hình Debug ( hiển thị các loại lỗi mong muốn như Joomla) hoặc một dòng code để bật chức năng sửa lỗi (Như Wordpress : define( 'WP_DEBUG', true );) được hay không ?
Cái này tốt cho người làm nông.

**Comment by hoaquynhtim99** [comment]
Cái này tất cả các lỗi không gây ra trắng trang đều đã hiển thị trực tiếp ngay trên giao diện lần đầu tiên đối với admin, lỗi gây ra trắng trang từ bản NukeViet 4.1.00 đã ghi vào file log. @anhyeuviolet  có thể tra cứu ở  `data\logs\error_logs`

**Comment by anhyeuviolet** [comment]
Mình biết điều đó. Nhưng không phải lỗi nào cũng đi vào log đó. 
Log của NukeViet cũng khá bất tiện để theo dõi :)

**Comment by mynukeviet** [comment]
Cái này mình cũng thấy thật sự cần cho developer đó chứ, trước mình có nghĩ ra giống @anhyeuviolet , cũung có thêm vài dòng và commit lên rồi nhưng không nhớ vì lý do gì đó mình lại remove.

Việc xem log cũng bất tiện hơn so với việc luôn hiển thị lỗi trên màn hình khi bật chế độ phát triển

**Comment by anhyeuviolet** [comment]
@mynukeviet nói hộ lòng tôi.

**Comment by vuthao** [comment]
Cái này chắc để sang bản 4.2 rồi bàn cụ thể sẽ phải làm ghì nhé các bạn. Ai có ý tưởng cứ note lại đây.

**Comment by vuthao** [comment]
@hoaquynhtim99 xem xét cấu hình luôn hướng dẫn này vào code của NukeViet 4.3 được không nhé: http://dungpt.vinades.net/blog/huong-dan-bat-chuc-nang-hien-thi-loi-khi-trang-trang-tren-nukeviet.html

**Comment by hoaquynhtim99** [comment]
@vuthao lỗi Error xảy ra ở vị trí A sẽ kéo theo rất nhiều lỗi phía sau đó cho nên cấu hình hiển thị ra như warning là không được. Ở phiên bản hiện tại có thể bổ sung 

- Hoặc là vào cấu hình
- Hoặc là vào file constants.php

Một thông số nào đó để class Error xử lý, thay vì cho trang trắng sẽ display cái lỗi ra màn hình

**Comment by vuthao** [comment]
@hoaquynhtim99 thế đưa vào file config.php, cái file constants.php hạn chế tối đa sửa nó.

**Comment by hoaquynhtim99** [comment]
Đã thêm https://github.com/hoaquynhtim99/nukeviet/commit/d0fd9b6ee4263de58182b5e02ec39ddfc09aa150
