### ISSUE TITLE
Lỗi Undefined index

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#2292]
Lỗi này chỉ cần phiên bản thử nghiệm:

Nên chú ý: Undefined index: elas_use in file /modules/news/admin/setting.php on line 182
Nên chú ý: Undefined index: external_link in file /modules/news/theme.php on line 305

Nukeviet 4.1.01: https://github.com/nukeviet/nukeviet/commit/03f4c38608ffae66dda1b03b078c2aa2b3e9a173

**Comment by anhyeuviolet** [comment]
Lỗi này cũng xảy ra khi cập nhật tự động từ 4.1 beta lên 4.1.01 Beta.

**Comment by anshpy** [comment]
cài đặt mới cũng lỗi à
Nên chú ý: Undefined index: external_link in file /modules/news/theme.php on line 305

**Comment by hoaquynhtim99** [comment]
Lỗi: `Nên chú ý: Undefined index: elas_use in file /modules/news/admin/setting.php on line 182` không thấy gặp

Lỗi: Undefined index: external_link đã fix https://github.com/hoaquynhtim99/nukeviet/commit/e4da781642070aec237731d4da296a281b137828 hướng dẫn ở https://nukeviet.vn/vi/forum/Huong-dan-sua-mot-so-loi-o-ban-4-1-01-t41957/

**Comment by anhyeuviolet** [comment]
Về lỗi elas_use, sau khi cài lại vẫn dính lỗi. Cảm thấy khó hiểu, dù trong action_mysql đã có trường này.
![4101](https://cloud.githubusercontent.com/assets/6290970/24938584/5026f66e-1f62-11e7-8be0-e4863ebfbb26.PNG)

**Comment by hoaquynhtim99** [comment]
Cái này do Update thiếu rồi, do tác giả không ghi nhận thay đổi CSDL khi viết gói nâng cấp bỏ qua cái này chạy lệnh:

```sql
INSERT INTO nv4_config (lang, module, config_name, config_value) VALUES ('vi', 'news', 'elas_use', '0');
INSERT INTO nv4_config (lang, module, config_name, config_value) VALUES ('vi', 'news', 'elas_host', '');
INSERT INTO nv4_config (lang, module, config_name, config_value) VALUES ('vi', 'news', 'elas_port', '9200');
INSERT INTO nv4_config (lang, module, config_name, config_value) VALUES ('vi', 'news', 'elas_index', '');
```

**Comment by hoaquynhtim99** [comment]
Đã có hướng dẫn https://nukeviet.vn/vi/forum/Huong-dan-sua-mot-so-loi-o-ban-4-1-01-t41957-p183660/#p183660

**Comment by anshpy** [comment]
Thông báo từ Hệ thống
Nên chú ý Nên chú ý: getimagesize(): Read error! in file /includes/core/filesystem_functions.php on line 704

**Comment by anhyeuviolet** [comment]
^
cái của bạn An là trong shops hay sao nhỉ ?

**Comment by hoaquynhtim99** [comment]
@anshpy chưa mô tả trường hợp cụ thể nên không check được, tuy nhiên lỗi này là do file không tương thích, file không có quyền đọc, file không tồn tại... thôi không phải lỗi từ hệ thống
