### ISSUE TITLE
Lỗi rewrite url phân trang nukeviet 4.1 beta 2

### ISSUE THREAD

**Issue by daoduytung** [nukeviet/nukeviet#2294]
Lỗi không rewrite được url phân trang ở main.php của **module news** và **module page** và bị lỗi 404 
Ví dụ: http://localhost/nukeviet/index.php?language=vi&nv=news/page-2
Khi link trực tiếp http://localhost/nukeviet/news/page-2.html trực tiếp vẫn lỗi

**Comment by hoaquynhtim99** [comment]
Đã sửa https://github.com/hoaquynhtim99/nukeviet/commit/324fcc5abae9eae965104b712257b5d36dedbffe

Hướng dẫn https://nukeviet.vn/vi/forum/Huong-dan-sua-mot-so-loi-o-ban-4-1-01-t41957/
