### ISSUE TITLE
Lỗi upload hình ảnh sai kích thước và dung lượng ảnh

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#2297]
**Cấu hình upload ví dụ:** 
Kích thước tối đa của file tải lên 900 x 900 có chọn Tự động resize ảnh nếu kích thước lớn hơn kích thước tối đa.
Dung lượng tối đa của file tải lên:	1.28MB.
Kiểu kiểm tra file tải lên: Mạnh.

**Vào Quản lý Files để upload file** chọn: **Upload từ máy tính**.
Chọn 1 file ảnh có Kích thước  **374 x 524 pixels (81 KB)** rồi upload file này lên host 
Thì có kết quả của file trên host là:  Kích thước: **642 x 900 pixels (241.58 KB)**

Upload file từ internet thì ok

Phiên bản web tải về: nukeviet4.1beta2-setup.zip (Phiên bản NukeViet 4.1.01)
Thời gian tải: 21h50 ngày 12/04/2017

Môi trường kiểm tra:  
Hệ điều hành máy chủ	LINUX 
Google Chrome: Phiên bản 57.0.2987.133
Web thử nghiệm: http://dochoixeoto.net

**Comment by hoaquynhtim99** [comment]
#2300

**Comment by hoaquynhtim99** [comment]
Đã fix ở: https://github.com/hoaquynhtim99/nukeviet/commit/b107ff02a99706874da6a875e301fcacfb2e2338
Hướng dẫn: https://nukeviet.vn/vi/forum/Huong-dan-sua-mot-so-loi-o-ban-4-1-01-t41957-p183936/#p183660
