### ISSUE TITLE
Lỗi khi cài đặt ngôn ngữ tiếng Nhật mà chưa cài tiếng anh

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2298]
> Phiên bản NukeViet	4.1.01
Phiên bản PHP	5.6.8
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.6.24

```
ERROR SETUP: 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nuukeviet_nuukeviet4_minhsinhtravel.nv4_en_modules' doesn't exist
```

![screenshot from 2017-04-13 06-57-48](https://cloud.githubusercontent.com/assets/6407361/24984273/88107532-2016-11e7-85c0-8a503d74ed25.png)

**Comment by hoaquynhtim99** [comment]
@mynukeviet cho biết quá trình cài đặt gói ngôn ngữ diễn ra như thế nào nhé, đối với bản mặc định chỉ có ngôn ngữ anh pháp việt, có thể quá trình tạo gói ngôn ngữ chưa phù hợp dẫn tới lỗi như trên. @mynukeviet  thử cài download gói ngôn ngữ ở https://translate.nukeviet.vn/en/translate/download/ về cài đặt xem còn lỗi không nhé.
