### ISSUE TITLE
Lỗi cài đặt ngôn ngữ tiếng Nhật

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2299]
> Phiên bản NukeViet	4.1.01Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.6.8
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.6.24

Gói ngôn ngữ tiếng nhật download tại https://translate.nukeviet.vn/en/translate/download/

Cài đăt báo lỗi ra màn hình, không thấy ghi log chi tiết
```
ERROR SETUP: 
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'
```

![screenshot from 2017-04-13 07-01-16](https://cloud.githubusercontent.com/assets/6407361/24984357/0392dc18-2017-11e7-9c4d-99fb32f63564.png)

**Comment by vuthao** [comment]
duplicate: https://github.com/nukeviet/nukeviet/issues/2306
