### ISSUE TITLE
Lỗi khi chọn chức năng "tự động resize hình ảnh nếu kích thước lớn hơn kích thước tối đa"

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/nukeviet#2300]
Nếu cấu hình upload là _tự động resize nếu kích thước lớn hơn kích thước tối đa_ thì khi upload hình từ máy tính lên nếu kích thước hình nhỏ hơn kích thước tối đa thì hình gốc sẽ bị resize chiều rộng với chiều rộng tối đa.

**Comment by thehung** [comment]
Thế là hoạt động đúng chức năng rồi còn gì nữa hả bạn?

**Comment by motcaiten** [comment]
Xin lỗi anh em ghi không rõ. Cái này nếu kích thước upload lên mà nhỏ hơn kích thước tối đa thì sẽ bị resize bằng với kích thước tối đã.

**Comment by vuthao** [comment]
@motcaiten có hai cái cần phân biệt.
- Nếu là ảnh thumb thì nó sẽ là cái ảnh có kích thước nhỏ nhất: Nếu file đưa lên nhỏ dướt kích thước cấu hình, thì ảnh thumb sử dụng cho site sẽ chính là ảnh gốc.

- Nếu resize, thì bạn sẽ phải là người quyết định chọn cái nào, chương trình chỉ resize là đúng kích thước đó và không quan tâm đến nó lớn hay nhỏ hơn kích thước đó. (Tương tự như bạn dùng phần mềm khác)

Bạn xem lại cái đó và xem đó có phải là lỗi không đó

**Comment by thehung** [comment]
Ý bạn ấy có lẽ là cái chức năng auto resize ảnh quá cỡ khi upload chứ không
phải chức năng resize ảnh thủ công.

**Comment by motcaiten** [comment]
@thehung  

- Cái này em hiểu . 

- Cái này em hơi mập mờ ý của anh.

Ở đây theo em hiểu là khi mình cấu hình kích thước hình tối đa được tải lên là 1500x1500px , nếu mình cấu hình __Tự động resize ảnh nếu kích thước lớn hơn kích thước tối đa_  thì chỉ những hình lớn hơn kích thước trên thì sẽ bị resize lại kích thước trên. 

Nhưng ở đây kích nếu tải hình kích thước bé hơn khi upload lên nó vẫn resize bằng kích thước đúng với kích thước tối đa. Nếu đúng thì phải để nguyên hình gốc chứ.

**Comment by vuthao** [comment]
Mình sẽ kiểm tra lại cái này.

**Comment by motcaiten** [comment]
@vuthao  @thehung 

Cấu hình ở đây sẽ bị lỗi trên

![capture](https://cloud.githubusercontent.com/assets/8292355/24995687/eda6ecda-2059-11e7-9e1a-afaa7e8d4a51.JPG)

**Comment by NukeVietCMS** [comment]
Theo mình biết thì hình **Tự động resize ảnh tối đa** đúng nghĩa là niếu ảnh lớn hơn kích thước tối đa khi up lên sẽ resize lại bằng với kích thước tối đa. 
Niếu ảnh up lên nhỏ hơn khích thước tối đa thì giữ nguyên kích thước ảnh.

Còn trong vấn đề này mình thấy thì **tự động resize ảnh tối đa** thì lại là ảnh up lên sẽ bằng với kích thước tối đa. Ảnh nhỏ hơn hay lớn hơn điều resize ảnh về 1 kích thước tối đa đã cấu hình.

**Comment by NukeVietCMS** [comment]
Cấu hình vuông 900 Tự động resize ảnh tối đa. Up file 241 x 241  3KB lên thành 900 x 900  96KB. Niếu đúng thì phải là **241 x 241  3KB**
Chi tiết xem https://www.youtube.com/watch?v=x6qblejeqeM&feature=youtu.be

**Comment by anhyeuviolet** [comment]
Mô tả đơn giản thì là ảnh nhỏ hơn hay to hơn 1500Px (cấu hình kích thước ảnh mặc định) thì ảnh đó đều được chỉnh thành 1500px hết.
Kể cả ảnh 200x200 thì thành 1500x1500 luôn.

**Comment by hoaquynhtim99** [comment]
Đã fix ở: https://github.com/hoaquynhtim99/nukeviet/commit/b107ff02a99706874da6a875e301fcacfb2e2338
Hướng dẫn: https://nukeviet.vn/vi/forum/Huong-dan-sua-mot-so-loi-o-ban-4-1-01-t41957-p183936/#p183660

**Comment by vuthao** [comment]
Đây chư phải là phương án xử lý tối ưu nên tôi xin phép mở lại issues này.

vấn đè như sau: nếu ngưòi dùng không biết dùng các công cụ ảnh, cứ chụp và đưa lên sẽ sao.?

Kích thước ảnh giờ rất lớn từ 10 - 20MB, nếu không resite được trên trình duyệt, quá trình upload file sẽ rất lâu, sau đó trên máy chủ sẽ phải xử lý rất tốn tài nguyên

**Comment by hoaquynhtim99** [comment]
Cái này đã sửa ở: https://github.com/hoaquynhtim99/nukeviet/commit/61259613407e387b00042bc6e6f52e98db96dc25 mọi người check trên các trình duyệt khác nhau nhé
