### ISSUE TITLE
Lỗi khi tạo chủ đề trùng tên

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2301]
Môi trường thử nghiệm xảy ra lỗi như sau:
> - Phiên bản NukeViet: 4.1.01
> - Hệ điều hành: Windows 10
> - Trình duyệt web: Mozilla Firefox 52, Chrome 57
> - Phần mềm máy chủ web: Vertrigo 2.35
> - Môi trường thử nghiệm: Localhost

Thao tác dẫn đến lỗi:
- Tạo chủ đề có tên "Khoa học" thì alias của nó tự động tạo ra là "khoa-hoc". Sau đó tạp tiếp chủ đề có tên "Khoa học" nằm trong một chủ đề khác: nếu thao tác chậm thì alias sẽ được tạo tự động là "khoa-hoc-22", tuy nhiên nếu thao tác nhanh (lưu chuyên mục mới khi alias chưa kịp tạo ra) thì sẽ gặp báo lỗi "Trùng tên" như ảnh dưới:
![anhchup-224](https://cloud.githubusercontent.com/assets/1892900/25033205/c66240e6-2105-11e7-82e0-3e1831954c67.jpg)
Kiểm tra thì thấy nó tự động tạo ra Alias là "Khoa-hoc"

Một vấn đề khác đáng lưu ý là trường hợp thao tác nhanh (lưu chuyên mục mới khi alias tự động chưa kịp kiển thị) thì alias này sẽ bị tạo không đúng chuẩn (không được chuyển thành chữ thường).

**Comment by hoaquynhtim99** [comment]
Lỗi đã được sửa tại: https://github.com/hoaquynhtim99/nukeviet/commit/850e2ca19ec24c13828cf10d0fb2685389094f3c
