### ISSUE TITLE
News: nofollow một số link

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2302]
Thêm ` rel="nofollow"` cho savefile và print

**Comment by thehung** [comment]
Nên bổ sung thẻ canonical vào đó nữa.

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/3dc6fa11e70b79e7d59aa7b7bac8be53161c4be3 canonical đã có từ trước
