### ISSUE TITLE
Vấn đề trong quản lý từ khóa của News

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2303]
Môi trường thử nghiệm:
> - Phiên bản NukeViet: 4.1.01
> - Hệ điều hành: Windows 10
> - Trình duyệt web: Mozilla Firefox 52, Chrome 57
> - Phần mềm máy chủ web: Vertrigo 2.35
> - Môi trường thử nghiệm: Localhost

Vấn đề gặp phải:
- Vào Admin Control Panel/ News/ Quản lý từ khóa. Tạo 5 từ khóa mới là: Lớp 1, Lớp 2, Lớp 3, Lớp 4, Lớp 5 (xem ảnh dưới)
![anhchup-222](https://cloud.githubusercontent.com/assets/1892900/25033332/f24c39cc-2106-11e7-8d15-8decd23c796c.jpg)
- Nhận được kết quả như ảnh dưới:
![anhchup-223](https://cloud.githubusercontent.com/assets/1892900/25033339/02987fe8-2107-11e7-93ea-2e087b21fc36.jpg)
- Khi tạo bài viết mới, hệ thống lại gợi ý tới 10 từ khóa (5 có dấu, 5 không dấu - xem hình) chứ không phải là 5 từ khóa như đã tạo.
![anhchup-221](https://cloud.githubusercontent.com/assets/1892900/25033360/34ca92bc-2107-11e7-83a6-9290694f6944.jpg)

**Comment by hoaquynhtim99** [comment]
#2273
