### ISSUE TITLE
Bất tiện khi thiết kế giao diện

### ISSUE THREAD

**Issue by thuongmaiso** [nukeviet/nukeviet#2304]
> - Phiên bản NukeViet: NukeViet 4x
> - Môi trường thử Nghiệm: Localhost/ hosting
> - Hệ điều hành: win10 64bit
> - Trình duyệt web: tất cả trình duyệt
> - Máy chủ web: XAMPP 
Hiện nay từ bản nukeviet 4.0.29 đều phát sinh vấn đề " Phải dọn dẹp hệ thống " trong admin thì mới load được những gì mình sửa, như sau:
- Chép đè file ảnh
- Chỉnh sửa css, js
Trong khi các bản nukeviet khác thì chỉ cần login user admin thì chỉnh sửa f5 là nó đã nhận js, css chỉnh sửa rồi. Điều này vô cùng bất tiện với mình khi làm giao diện. 
Vậy mong đội code xem xét và cho mình 1 phương án giải quyết vấn đề trên

**Comment by vuthao** [comment]
bản 4.1.01 đã khắc phục lỗi này rồi nhé bạn.

Với bản 4.0.29 bạn kích hoạt plugin cdn_js_css_image.php trước khi gửi nội dung cho trình duyệt
![screen shot 2017-04-15 at 08 37 26](https://cloud.githubusercontent.com/assets/2491500/25059766/c651843e-21b6-11e7-8821-024dc2cbe156.png)

Khi bạn xóa cache của hệ thống hệ thông sẽ tự động load lại file css, js
