### ISSUE TITLE
Thông báo Yêu câùu kích hoạt đa ngôn ngữ vẫn hiện mặc dù đã kích hoạt

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2305]
Kích họat Đa ngôn ngữ rồi nhưng dòng thông báo màu vàng này vẫn hiện

![screenshot from 2017-04-15 06-30-27](https://cloud.githubusercontent.com/assets/6407361/25058571/2ad1d632-21a5-11e7-91ad-19e7be312586.png)

**Comment by hoaquynhtim99** [comment]
Cái này chỉ mang tính chất hướng dẫn thôi có gì đâu phải sửa nhỉ

**Comment by mynukeviet** [comment]
Đúng thì nó chẳng ảnh hưởng gì nhưng thấy nó thừa thôi, kích họat rồi thì thông báo kích họat làm gì nữa @@

**Comment by hoaquynhtim99** [comment]
@mynukeviet  sửa giúp nó được không

**Comment by mynukeviet** [comment]
Thôi cứ để đây đã đừng close, rảnh tr sửa luôn

**Comment by thehung** [comment]
Theo anh vì đây chỉ là 1 câu hướng dẫn, không phải la thông báo cho nên không nên sửa. 

Vì nếu sửa thì tự dưng làm phức tạp vấn đề: phải can thiệp bằng câu lệnh if để kiểm tra cấu hình sau đó lại phải chia đôi chuỗi language này ra https://github.com/nukeviet/nukeviet/blob/4.1.01/includes/language/vi/admin_language.php#L58

Code phải thay đổi trong khi người sử dụng không được lợi lộc gì!

**Comment by anhyeuviolet** [comment]
> Để thêm mới ngôn ngữ dữ liệu, bạn cần kích hoạt chức năng đa ngôn ngữ, để download ngôn ngữ mới truy cập website Ngôn ngữ cho NukeViet 4

Cần lưu ý thêm là ngay chỗ "kích hoạt chức năng đa ngôn ngữ" nó là một cái link, click vào là tự nó sẽ kích hoạt chức năng đa ngôn ngữ lên.
Nên nếu vẫn để thì phải giải quyết như thế nào đó cho hợp lý ở cái "link" này.
