### ISSUE TITLE
Lỗi gói ngôn ngữ tải về từ https://translate.nukeviet.vn

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2306]
Không biết có phải lỗi không mình đưa lên đây đội code kiểm tra lại thử.

Download gói ngôn ngữ (tiếng Nhật) tại https://translate.nukeviet.vn thấy trong mấy file nó chỉ có mấy dòng thông tin thôi chứ ko có biến ngôn ngữ nào cả, trong khi ở nv3 đã dịch rất nhiều.

VD đây là file `modules/news/language/admin_js.php`

![screenshot from 2017-04-15 07-35-22](https://cloud.githubusercontent.com/assets/6407361/25059299/2702c24c-21ae-11e7-8b41-a81d6f23ad03.png)

Gói mới tải về sáng nay 
[nv4_language_ja.zip](https://github.com/nukeviet/nukeviet/files/923172/nv4_language_ja.zip)

**Comment by vuthao** [comment]
Lỗi này liên quan đến site translate.nukeviet.vn Code trên github không cần sửa nhé các bạn.

**Comment by hoaquynhtim99** [comment]
Hiện tại hệ thống dịch đã được nâng cấp lên cấu trúc mới nhất của NukeViet 4.1
