### ISSUE TITLE
Thời gian chờ sau khi đọc dữ liệu ngôn ngữ lâu quá

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2307]
Cấu hình / Ngôn ngữ / Cấu hình / Đọc dữ liệu

Đọc xong phải chờ lâu quá trog khi ko có liên kết để ngưòi dùng click vào đỡ phải chờ

![screenshot from 2017-04-15 07-45-38](https://cloud.githubusercontent.com/assets/6407361/25059363/b7c6903c-21af-11e7-80b1-3602de3cffcc.png)

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/addf2468b7744de0a61f287ffc9211828ff17188
