### ISSUE TITLE
Lỗi cảnh báo: explode() expects parameter 2 .... mainfile.php on line 321

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#2320]
Từ phiên bản: 4.1.01 năng cấp tự động trong quản trị lên NukeViet 4.1 Official (4.1.02).

Thông báo từ Hệ thống
Lỗi cảnh báo: explode() expects parameter 2 to be string, array given in file /includes/mainfile.php on line 321

Cái này trong admin và ngoài site điều thấy cả. Đối với khách (không đăng nhập quản trị) thì không thấy

**Module users**
Tài khoản -> Cấu hình module
**Thông báo từ Hệ thống**
Lỗi cảnh báo	Lỗi cảnh báo: explode() expects parameter 2 to be string, array given in file /includes/mainfile.php on line 321
Nên chú ý	Nên chú ý: Undefined index: dir_forum in file /modules/users/admin/config.php on line 229
Nên chú ý	Nên chú ý: Undefined index: nv_unickmin in file /modules/users/admin/config.php on line 239
Nên chú ý: Undefined index: nv_unickmax in file /modules/users/admin/config.php on line 248
Nên chú ý: Undefined index: nv_upassmin in file /modules/users/admin/config.php on line 269
Nên chú ý: Undefined index: nv_upassmax in file /modules/users/admin/config.php on line 278
Tổng cộng có khoảng trên 300 dòng **Nên chú ý**

**Cấu hình máy chủ**
Phiên bản NukeViet	4.1.02 Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.5.37
Giao thức giữa máy chủ và PHP	Apache/2, apache2handler
Hệ điều hành máy chủ	LINUX 
Trình duyệt: Google Chrome  Phiên bản 57.0.2987.133

**Comment by hoaquynhtim99** [comment]
@NukeVietCMS tạo chủ đề trên diễn đàn để thảo luận vấn đề này nhé, đây không phải là lỗi để kiểm tra và phát triển nên mình xin phép close lại
