### ISSUE TITLE
Sitemap: kiểm tra nếu không có dữ liệu thì không hiện

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2322]
Hiện tại sitemap không có dữ liệu vẫn hiện, làm google webmaster tool báo lỗi `Thiếu thẻ bắt buộc. Hãy thêm thẻ đó và gửi lại.`

Ví dụ module page, kích hoạt cái page lên chỉ để thêm block html chứ ko có bài viết

![screenshot from 2017-04-24 16-03-34](https://cloud.githubusercontent.com/assets/6407361/25329827/9cce4d1a-2907-11e7-9c28-4ed506e74bea.png)

![screenshot from 2017-04-24 16-03-27](https://cloud.githubusercontent.com/assets/6407361/25329826/9cce4360-2907-11e7-96c5-bd4646fc5e94.png)

**Comment by vuthao** [comment]
@mynukeviet , @hoaquynhtim99 Liệu có nên gộp chung cấp hình sitemap và RSS vào 1 hay là tách làm 2 nhỉ.

nếu không gộp thì thêm 1 cấu hình nữa, tại trang admin/index.php?language=vi&nv=modules&op=edit&mod=page
Thêm cấu hình Kích hoạt chức năng rss:

**Comment by mynukeviet** [comment]
Cái này nó chi liên quan tới sitemap thì em nghĩ kiểm tra luôn trong code nếu có dữ liệu thì mới đưa vào sitemap

**Comment by vuthao** [comment]
Việc kiểm tra luôn sẽ tốn rất nhiều tài nguyên, và mỗi cái viết sitemap khác nhau.

Và những cái sitemap,  RSS phục vụ cho SEO là chính nên theo mình gộp lại 1 cấu hình trong quản lý module.

**Comment by mynukeviet** [comment]
Nếu giải quyết được vấn đề em nêu bên trên thì ok anh

**Comment by hoaquynhtim99** [comment]
@vuthao @mynukeviet đồng quan điểm của a Thảo, nên tách ra chứ không nên gộp chung vào RSS module nào không có nội dung thì tắt chức năng sitemap việc kiểm tra hiển thị sẽ tốn tài nguyên và phức tạp. Module page đặc thù sẽ tự tắt sitemap khi cài đặt.

**Comment by hoaquynhtim99** [comment]
Phần này đã thêm tại https://github.com/hoaquynhtim99/nukeviet/commit/3d60bbf28705500778e1d8737cdb27fa3d0e3569
