### ISSUE TITLE
Lỗi ghi log

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2323]
> Phiên bản NukeViet	4.1.02Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.5.26
Giao thức giữa máy chủ và PHP	Apache/2, cgi-fcgi
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.5.41

Sau khi nâng cấp lên 4.1.02 mình thấy có vấn đê này, không biết đúng là lỗi không.

Cùng 1 lỗi nhưng nó ghi lại liên tục mỗi lần gặp phải, cụ thể ở đây là lỗi không kết nối được SMTP

![screenshot from 2017-04-25 16-00-57](https://cloud.githubusercontent.com/assets/6407361/25376998/65045ab8-29d0-11e7-8c8b-b0b612cc5062.png)

**Comment by anhyeuviolet** [comment]
Mình bị tình trạng tương tự. Hệ thống request SMTP cho tới khi nào được thì thôi. 
Thi thoảng tèo cả hosting.

**Comment by vuthao** [comment]
@anhyeuviolet cái này mình nghĩ ko đúng, cái lỗi này ghi lại như @mynukeviet  nói chỉ khi gửi mail.

**Comment by mynukeviet** [comment]
Mình đang chạy cron gửi mail, gửi ko dc nên cứ 10s nó lại ra một dòng như thế :)

**Comment by anhyeuviolet** [comment]
@mynukeviet Nếu vậy thì đúng rồi.
Cơ mà mình bị lạc đề, bạn nói về vấn đề ghi log, còn mình bị lạc sang việc gọi SMTP :(

**Comment by hoaquynhtim99** [comment]
Cái này chính xác là lỗi, mình sẽ kiểm tra lại

**Comment by vuthao** [comment]
Cái này do mình gây ra, để mình sửa lại cho

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/pull/2376
