### ISSUE TITLE
[Giao diện] Lỗi cảnh báo khi chỉ có 1 position trong config.ini của theme

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2326]
+ NukeViet 4.1.02.
XAMPP 1.8.3

Mô tả:

Mở file \themes\default\config.ini
Xoá tất cả position và chỉ chừa lại 01 position duy nhất, ví dụ:
```
	<positions>
		<position>
			<name>PERSONALAREA</name>
			<tag>[PERSONALAREA]</tag>
		</position>
	</positions>
```
Trang chủ sẽ thu được báo lỗi như sau:
Illegal string offset 'tag' in \includes\core\user_functions.php on line 59

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/95e6185f91e13490c477c4d37ba40fd298c936d6

**Comment by ThinhNguyenVB** [comment]
Đã ok

**Comment by anhyeuviolet** [comment]
Sửa rồi thì phải ok thôi.
