### ISSUE TITLE
session_handler

### ISSUE THREAD

**Issue by thanhtranntkh** [nukeviet/nukeviet#2328]
sau khi nâng cấp từ phiên bản 4.1 lên 4.1.02 tôi gặp lỗi sau:
Undefined index: session_handler in file /includes/ini.php on line 20
Undefined index: session_handler in file /includes/ini.php on line 24

Phiên bản NukeViet	4.1.02
Phiên bản PHP	5.5.38
Giao thức giữa máy chủ và PHP	Microsoft-IIS/8.5, cgi-fcgi
Hệ điều hành máy chủ	WINDOWS NT
Phiên bản Database	mysql 5.5.45
http://xaydung.ddns.net

**Comment by mynukeviet** [comment]
Cái này nó bị từ mấy phiên bản trước, mình cũng có thấy mà chưa quan tâm :)

**Comment by vuthao** [comment]
Các bạn khi uống thuốc cần đọc hướng dẫn sử dụng nhé:

https://github.com/nukeviet/update

Trong đó có đoan:
Mở config.php (file này có thể khác tùy theo thiết lập của quản lý site), thêm sau dòng $global_config['cached'] = 'files';:

$global_config['session_handler'] = 'files';
