### ISSUE TITLE
Lỗi url module page sau khi nâng cấp len 4.1.02

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2329]
Ở các phiên bản trước module sẽ ko hiển thị tên module page trong url, ví dụ https://raodn.com/Dang-tin-mien-phi-tai-rao-vat-Da-Nang.html

Nhưng bây giờ sau nâng cấp tự nhiên có thêm cái page vào làm sai URL https://raodn.com/page/Dang-tin-mien-phi-tai-rao-vat-Da-Nang.html

Một mớt URL SEO đang chết :)

**Comment by anhyeuviolet** [comment]
http://anhyeuviolet.nukeviet.store/gioi-thieu-ve-nukeviet.html

Mình thì mình không bị.

**Comment by thehung** [comment]
Cái này chắc do Triển đang cấu hình việc loại bỏ tên module trên URL mà không phải module page đó rồi. Vào cấu hình chung để thực hiện cấu hình lại xem!

**Comment by mynukeviet** [comment]
Đúng rồi @anhyeuviolet @thehung, mình chọn loại bỏ module là một module khác chứ không phải page. Vấn đề ở đây là, ở các bản trước **tên module page** được **tự động loại bỏ khỏi url** chứ không cần cấu hình (cái này @vuthao biết).

Nhưng khi nâng cấp lên bản mới này, thì **tên module page** nó không được **tự động loại bỏ** nữa.

**Nên** với những url từ bản cũ (không có tên module page trong url) khi nâng cấp lên bản mới này sẽ bị lỗi 404

**Comment by anhyeuviolet** [comment]
Xác nhận vấn đề này có tồn tại.

**Comment by anhyeuviolet** [comment]
Như này, bản cũ thì hệ thống tự bỏ tên module Page khỏi URL.
Còn các module ảo của Page (About) sẽ không được phép chọn để xoá tên module khỏi hệ thống (Tất nhiên).
Giờ thì sẽ cho chọn cả About, vì thế Page sẽ không còn được hệ thống tự bỏ tên module khỏi URL nữa.
Do đó nếu trước đó dùng Page nhiều thì phải vào cấu hình lại cho Page. Nhưng nếu trước đó xoá cả tên một Module nào đó khác nữa thì sẽ là vấn đề lớn :)

**Comment by hoaquynhtim99** [comment]
#2458

**Comment by hoaquynhtim99** [comment]
Xem hướng dẫn ở https://nukeviet.vn/vi/forum/Huong-dan-sua-duong-dan-module-page-sau-khi-nang-cap-len-ban-4-1-Official-tro-len-t44216/
