### ISSUE TITLE
Lỗi không hiện thị banner "banner của site"

### ISSUE THREAD

**Issue by anshpy** [nukeviet/nukeviet#2331]
# Hiện tại mình cài mới NukeViet 4.1 Official 
có sử dụng chức năng úp banner như ra ngoài site vẫn ko hiện
![image](https://cloud.githubusercontent.com/assets/17925443/25442621/b2477c2e-2acf-11e7-8b86-cc19b6f555f8.png)

**Comment by vuthao** [comment]
Giao diện mặc định không hỗ trợ  cấu hình này bạn

**Comment by anshpy** [comment]
thế giao diện nào mới hỗ trợ đc ạ ( bản nukeviet 4.0.25 trở lại thì có mà ah )

**Comment by hoaquynhtim99** [comment]
@anshpy mình vừa cài đặt thử bản 4.0.25 để kiểm tra nhưng vẫn không thấy có hỗ trợ
