### ISSUE TITLE
Lỗi module News

### ISSUE THREAD

**Issue by thanhtranntkh** [nukeviet/nukeviet#2332]
sau khi đã nâng cấp từ 4.1 lên 4.1.02 thàn công thì bị lỗi sau:
[Thu, 27 Apr 2017 08:28:59 +0700] [116.99.243.162] [Notice(8): Undefined index: htmlhometext] [FILE: /modules/news/admin/setting.php] [LINE: 177]
[Thu, 27 Apr 2017 08:29:34 +0700] [116.99.243.162] [Notice(8): Undefined index: htmlhometext] [FILE: /modules/news/admin/setting.php] [LINE: 177]
[Thu, 27 Apr 2017 08:29:49 +0700] [116.99.243.162] [Notice(8): Undefined index: htmlhometext] [FILE: /modules/news/admin/setting.php] [LINE: 177]
[Thu, 27 Apr 2017 08:30:06 +0700] [116.99.243.162] [Error(1): Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'titlesite' in 'field list'' in E:\WWW\WEB1\modules\news\funcs\detail.php:36
Stack trace:
#0 E:\WWW\WEB1\modules\news\funcs\detail.php(36): PDO->query('SELECT titlesit...')
#1 E:\WWW\WEB1\index.php(265): require('E:\\WWW\\WEB1\\mod...')
#2 {main}
  thrown] [FILE: /modules/news/funcs/detail.php] [LINE: 36]
[Thu, 27 Apr 2017 08:30:38 +0700] [116.99.243.162] [Notice(8): Undefined index: htmlhometext] [FILE: /modules/news/admin/setting.php] [LINE: 177]
hiêm module này không hoạt động

**Comment by vuthao** [comment]
Bạn hãy backup lại bản cũ, rồi tiến hành nâng cấp lại thử xem sao. Chú ý trong quá trình nâng cấp có lỗi nào cần ghi lại để chúng tôi kiểm tra.

**Comment by hoaquynhtim99** [comment]
@thanhtranntkh các trường đó được thêm vào từ bản 4.0.29 lên bản 4.1.00 nếu site của bạn lỗi các trường đó tức là quá trình đưa lên 4.1.00 của bạn đã sai sót, vấn đề đó bạn tiến hành thảo luận ở diễn đàn https://nukeviet.vn/vi/forum/ nhé
