### ISSUE TITLE
Lỗi URL phân trang không loại bỏ tên module

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2335]
> Phiên bản NukeViet	4.1.02
Phiên bản PHP	5.5.26
Giao thức giữa máy chủ và PHP	Apache/2, cgi-fcgi
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.5.41

Các phiên bản trước không lỗi, phiên bản 4.1.02 lỗi này.

Kiểm tra:
1. Cấu hình loại bỏ tên module khỏi URL là news
2. Xem bài viết theo danh sách
3. URL bây giờ sẽ là `domain/news/page-2/` (trong khi các bản cũ sẽ là ``domain/page-2/``)

**Comment by mynukeviet** [comment]
@vuthao cái này ko phải tính năng cần phát triển mà là lỗi ý anh, mấy bản trước không có lỗi này, bản 4.1.02 đang gặp, google webmaster báo một đống lỗi 404 vì cái link này

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/3a7bb5b15481499b0b8b6c5f99645bf28aaee525

**Comment by ThinhNguyenVB** [comment]
OK
