### ISSUE TITLE
Lỗi URL phân trang khi tắt rewite

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2336]
> Phiên bản NukeViet	4.1.02Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.6.8
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.6.24

1. Cấu hình chung tắt rewite
2. Link phân trang bây giờ sẽ là `http://domain/index.php?language=vi&nv=news/page-2` => lỗi 404

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/aea658c9883abd845b667b35f622613deb2a13b1

**Comment by ThinhNguyenVB** [comment]
Đã thấy OK
