### ISSUE TITLE
[News] [Funcs Content] Lỗi Console của CKeditor

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2338]
+ NukeViet 4.1.02/Firefox Latest.
---
+ Cho phép thành viên đăng bài thông qua chức năng Content của modules.
+ Logout Admin nếu có, đăng nhập ngoài site thông qua module Users (domain.com/users/).
+ Truy cập vào Content của news.

Console trình duyệt báo như sau:
![666](https://cloud.githubusercontent.com/assets/6290970/25652299/b7da46a2-3011-11e7-8016-c4eae8cfb87a.PNG)

**Comment by anhyeuviolet** [comment]
Khi đăng nhập thông qua /admin/ sẽ không bị vấn đề này.

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/c156b5365863eebf814614b1ca4f52b67e715345

**Comment by ThinhNguyenVB** [comment]
đã thấy ok
