### ISSUE TITLE
Cải tiến cấu hình các block.

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2339]
Hiện tại các block đang cấu hình mặc định cắt các ký tự.

Cách làm này chỉ giải quyết cho các anh làm giao diện cho xong việc.

Còn nhiều người làm site không muốn chữ bị cắt đi.

Do đó sẽ cấu hình lại mặc định sẽ không cắt chữ trong các block hoặc các chức năng.

**Comment by hoaquynhtim99** [comment]
Các block mặc định đã được config không cắt tiêu đề, về dữ liệu mẫu em đã cập nhật tại https://github.com/hoaquynhtim99/nukeviet/commit/2fba1d3d41c979e132ce1b039443f7978fc97b36
