### ISSUE TITLE
Lỗi js

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/nukeviet#2349]
Hiện tại em cài bản mới nhất và module shops thì bị lỗi js như hình dưới.

![capture](https://cloud.githubusercontent.com/assets/8292355/25825962/2a88b934-346f-11e7-832e-4449aa2148f9.JPG)

**Comment by vuthao** [comment]
Bạn vui lòng đọc lại quy định báo lỗi tại: https://github.com/nukeviet/nukeviet/blob/develop/.github/ISSUE_TEMPLATE.md

Mục đích:  để chúng tôi có thể xây dựng môi trường thử nghiệm giống của bạn để kiểm tra

**Comment by vuthao** [comment]
Hiện tại module shop sẽ cần phải nâng cấp để tương thích với phiên bản NukeViet 4.1

**Comment by anhyeuviolet** [comment]
Cái này là đến từ module shops nhé bạn.
Phải cái là bạn không nêu ra phiên bản bạn cài là bao nhiêu để tìm lỗi dễ hơn.

**Comment by motcaiten** [comment]
Thông tin:

- Phiên bản nukeviet 4.1.02 
- Môi trường thử nghiệm : Localhost
- Máy chủ web : Xampp
- Phiên bản shops mới nhất trên github

**Comment by motcaiten** [comment]
Lỗi không phải đến từ module shops vì em xóa module shops đi thì lỗi vẫn như cũ

![capture](https://cloud.githubusercontent.com/assets/8292355/25836377/759e79fe-34b0-11e7-9ee2-eee89b4af377.JPG)
