### ISSUE TITLE
Ghi nhật ký nâng cấp

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2352]
Khi nâng cấp ứng dụng hoặc site cần ghi nhật ký để sau này kiểm tra lại

**Comment by hoaquynhtim99** [comment]
Added  https://github.com/hoaquynhtim99/nukeviet/commit/a1c7010cc683709d5bb407456ad5cbf7cb5909ac

**Comment by ThinhNguyenVB** [comment]
đã ok
