### ISSUE TITLE
Lỗi 500 khi cài đặt

### ISSUE THREAD

**Issue by thuongmaiso** [nukeviet/nukeviet#2362]
Phiên bản NukeViet	4.1.02
Phiên bản PHP	5.5.38
Giao thức giữa máy chủ và PHP	Apache/2, apache2handler
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.5.31
1. Tải bản mởi nhất của dev về lỗi 500 khi bắt đầu cài đặt, phải chạy domain.com/install/
2. Sau khi cài xong thì chạy được, điều đó mình nghĩ lỗi file .htaccess
3. Lỗi
Nên chú ý: Undefined variable: lang_global in file /admin/settings/admin.menu.php on line 21
Nên chú ý: Undefined variable: lang_global in file /admin/settings/admin.menu.php on line 28
Nên chú ý: Undefined variable: lang_global in file /admin/database/admin.menu.php on line 17

**Comment by vuthao** [comment]
@thuongmaiso bạn lấy mã nguồn từ link nào nhỉ.

**Comment by thuongmaiso** [comment]
trực tiếp à anh https://github.com/nukeviet/nukeviet/archive/develop.zip

**Comment by vuthao** [comment]
nếu bạn dùng làm sản phẩm, bạn nên download bản từ nguồn thông báo phát hành, bản trên nhánh develop là bản đang phát triển, code không ổn định và có thể thay đổi mà không được hỗ trợ nâng cấp.

còn nếu là để test báo lỗi, rất cám ơn bạn. đã thông báo lỗi. Trong tuần vừa qua chúng tôi sửa rất nhiều cái nhỏ và chưa kiểm tra lại hết được.

**Comment by thuongmaiso** [comment]
à em bên phát triển mà ✌️  hà hà

**Comment by vuthao** [comment]
Nếu bạn bên phát triển, có thể sửa giúp được chúng tôi những lỗi nào sửa luôn nhé.

Cái đó sửa khá đơn giản do thiếu biến khi gọi global (Do các bạn sửa biến thừa chắc xóa nhầm)

**Comment by vuthao** [comment]
@thuongmaiso mình đã sửa lại rồi nhé.

bạn kiêm tra lại dùm nhé.

**Comment by ThinhNguyenVB** [comment]
Đã thấy OK
