### ISSUE TITLE
Thông báo lúc cài đặt các bản develop

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2363]
Thông báo vào các bản đang phát triển để người dùng không sử dụng làm để xây dựng site chính thức.

**Comment by hoaquynhtim99** [comment]
Added: https://github.com/hoaquynhtim99/nukeviet/commit/1cb906656d8fa1d48cbd720f56e3588fbbaf6edb

**Comment by ThinhNguyenVB** [comment]
Đã thấy ok
