### ISSUE TITLE
Module news: theo dòng sự kiện selectbox sắp xếp có vấn đề

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2367]
> Phiên bản NukeViet	4.1.02Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.6.8
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.6.24

Khi không phân trang, ở selectbox có thêm option số 0, chọn số không thì báo **Vì một lý do nào đó.....**

![screenshot from 2017-05-17 14-57-29](https://cloud.githubusercontent.com/assets/6407361/26143950/3dd886ba-3b11-11e7-9e1e-fac582c00df9.png)

Khi phân trang thì mấy con số nó không đúng

![screenshot from 2017-05-17 14-58-54](https://cloud.githubusercontent.com/assets/6407361/26144009/698decbe-3b11-11e7-91f5-2418446c9fe1.png)

**Comment by hoaquynhtim99** [comment]
Lỗi đã fix ở https://github.com/hoaquynhtim99/nukeviet/commit/6f2fcfbe44bb6f4895c0873c5fc087757faec82f tuy nhiên đây mới chỉ fix lỗi. Cách trình bày phân trang mà có select box là không tối ưu bởi hiện tại chỉ có thể thay đổi thứ tự trên 1 trang nhất định, không thể thay đổi thứ tự giữa các trang nếu cho phép thay đổi các trang thì sẽ dẫn tới tiếp việc quá nhiều dòng gây treo trình duyệt

**Comment by ThinhNguyenVB** [comment]
khối theo dòng sự kiện 1 website khoogn dùng quá 10 cái, cho lên select cho các trang trang để sắp xếp ko vấn đề gì. ở một trang thì hơi bí

**Comment by thehung** [comment]
@hoaquynhtim99, có một cách xử lý đơn giản là cho phép cho gõ số và chỉ cần kiểm tra tính hợp lệ của số được gõ.
Cách khác: Cho phép thay đổi số lượng hiển thị trên 1 trang, như vậy mình chỉ cần đổi vài lần là ok :D

**Comment by hoaquynhtim99** [comment]
@thehung hiện có thể áp dụng như cách làm của module news phần quản lý chuyên mục tuy nhiên tốn khá nhiều thời gian

**Comment by thehung** [comment]
Nếu cho thay đổi số lượng hiển thị trên 1 trang thì sao lại tốn nhiều thời gian nhỉ @hoaquynhtim99 ?

**Comment by hoaquynhtim99** [comment]
@thehung do cơ chế hiện tại là mỗi một dòng sẽ xuất ra một ô select do đó nếu rất nhiều dòng sẽ có rất nhiều ô select mỗi một ô select sẽ có số option bằng với số dòng, để xuất ra như vậy thì máy chủ sẽ phải loop cực lớn

Ví dụ có 400 dòng thì có 400 ô mỗi ô 400 option => Máy chủ phải chạy 160k vòng lặp chỉ để xuất ra như thế sẽ mất thời gian, chưa kể trình duyệt sẽ phải build ra 400 ô select rất dài => Xử lý rất lâu

Cho nên thay đổi số dòng để giải quyết sẽ không tối ưu, cần làm như module news đang làm là chỉ xuất ra số dòng sau đó khi người dùng ấn vào thay đổi thứ tự thì mới build ra cái select rồi cache nó lại.

**Comment by thehung** [comment]
Cần gì đến 400 em?
Chỉ cần 2 tùy chọn thay đổi phân số mục trên 1 trang, 1 cái 20 (mặc định), 1 cái 25, thế là đủ.
Như vậy khi cần chuyển từ mục 1 trên trang 2 sang thành mục 20 trên trang 1 thì chỉ cần chọn lại phân trang từ 20 mục/ trang thành 25 mục/ trang. Như thế là mục 1 trang 2 khi trước sẽ thành mục 21 của trang 1, tha hồ đổi!

**Comment by hoaquynhtim99** [comment]
@thehung cái này là để giải quyết làm sao "làm cho được" chứ đâu phải hay anh, để sắp xếp thì người sắp xếp chủ đich biết vị trí đưa đến nó nằm ở đâu bên trên, bên dưới cái nào.

Chả lẽ lại quay sang trang 4 xem thử nằm ở đâu hợp lý rồi tính toán vị trí mới, sau đó quay sang trang 1 để thay đổi thành số đó rồi lại quay sang trang 4 xem kết quả

**Comment by thehung** [comment]
Sao lại trang 4 với trang 1 là như thế nào nhỉ? Cụ thể hơn đi em!

Vào 24 thg 1, 2018 11:42, "Tan Dung Phan" <notifications@github.com> đã
viết:

@thehung <https://github.com/thehung> cái này là để giải quyết làm sao "làm
cho được" chứ đâu phải hay anh, để sắp xếp thì người sắp xếp chủ đich biết
vị trí đưa đến nó nằm ở đâu bên trên, bên dưới cái nào.

Chả lẽ lại quay sang trang 4 xem thử nằm ở đâu hợp lý rồi tính toán vị trí
mới, sau đó quay sang trang 1 để thay đổi thành số đó rồi lại quay sang
trang 4 xem kết quả

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/nukeviet/nukeviet/issues/2367#issuecomment-360019101>,
or mute the thread
