### ISSUE TITLE
Lỗi js trong default/js/main.js

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2368]
> Phiên bản NukeViet	4.1.02 (mới nhất ngày 18/05/2017)
Phiên bản PHP	5.6.8
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.6.24

![screenshot from 2017-05-18 10-22-53](https://cloud.githubusercontent.com/assets/6407361/26185258/fbd776ec-3bb3-11e7-942e-559508ca2f1c.png)

**Comment by hoaquynhtim99** [comment]
Lỗi do @anhtunguyen  sửa ở commit này https://github.com/nukeviet/nukeviet/commit/d2d1b490dca86d46c78507e008a6afca5c55bd5a không hiểu lý do vì sao, mình đã sửa lại ở https://github.com/hoaquynhtim99/nukeviet/commit/74e4e6d8dcc9046cca220633c0bca07a0f682a57
