### ISSUE TITLE
Cấu hình các dữ liệu của module users

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2369]
Mặc định khi tạo tài khoản có các trường:
1. Câu hỏi bảo mật
2. Câu trả lời 
3. Tên 	
4. Họ 	
5. Giới tính 	
6. Ngày tháng năm sinh
7.  Chữ ký 

Nhưng cần cấu hình các chức năng sau thì không được:
1. Trường dữ liệu bắt buộc(Nếu là trường bắt buộc sẽ được hiển thị trong quá trình đăng ký)
2. Hiển thị khi đăng ký 	
3. Thành viên có thể thay đổi 	
4. Hiển thị tại trang tài khoản

Hướng giải quyết:
- Đưa các trường này vào trong phần tùy biến dữ liệu. Khi cài đặt mặc định thêm luôn.
- Có thêm 1 trường là trường mặc định của hệ thống. Các trường có sẵn của hệ thống thì không hiển thị lại ở phần tùy biến dữ liệu. Và coi đây là các cấu hình để kiểm tra cho các trường này.
- Không cho xóa

**Comment by ngocphan123** [comment]
Không cấu hình Hình đại diện ạ

**Comment by vuthao** [comment]
@ngocphan123 , cấu hình Ngày tháng năm sinh

Sẽ cần 1 cấu hình tại cấu hình của module users: Số tuổi của thành viên ít nhất để tham gia

Khi lập trình sẽ tính từ ngày tháng năm sinh ra, nếu không đủ tuổi sẽ dừng đăng ký luôn.

**Comment by hoaquynhtim99** [comment]
@vuthao @ngocphan123 kết quả test:

- Một số lỗi từ error log:

```
[Thu, 01 Jun 2017 07:51:27 +0700] [127.0.0.1] [Notice(8): Undefined index: value] [FILE: /modules/users/theme.php] [LINE: 106]
[Thu, 01 Jun 2017 08:05:45 +0700] [127.0.0.1] [Notice(8): Undefined offset: 0] [FILE: /modules/users/funcs/register.php] [LINE: 260]
[Thu, 01 Jun 2017 08:06:01 +0700] [127.0.0.1] [Notice(8): Undefined index: your_question_empty] [FILE: /modules/users/funcs/register.php] [LINE: 318]
```

- Câu hỏi bảo mật mặc định không có gì
![01-06-2017 8-12-34 sa](https://cloud.githubusercontent.com/assets/2421714/26660947/84911a50-46a5-11e7-8a1e-9b0823834009.png)
- Báo lỗi tuổi đè lên không pick date được:
![01-06-2017 8-15-14 sa](https://cloud.githubusercontent.com/assets/2421714/26660954/8c81ae8c-46a5-11e7-93f6-6fbe3b180361.png)
- Cấu hình giới hạn tuổi về 0 hoặc âm thì không đăng ký được và không có thông báo lỗi gì. Sau đó, tăng tuổi lên lại 16 cũng không đăng ký được nữa cũng không báo lỗi gì.
- Chưa thấy các thay đổi áp dụng cho giao diện mobile_default
- Cài đặt mới vào cấu hình trường dữ liệu bỏ chọn bắt buộc ở ngày sinh, chọn thêm giá trị mặc định ngày hiện tại ra ngoài site đăng ký không được và không có thông báo gì.
- Sắp xếp thứ tự ở phần tùy biến dữ liệu đang có vấn đề: 2 => 7 sau đó quay về 1
![01-06-2017 8-35-37 sa](https://cloud.githubusercontent.com/assets/2421714/26660958/92ae4fae-46a5-11e7-9ee4-751b97701a0a.png)


Kết thúc test do không đăng ký tài khoản được.

**Comment by vuthao** [comment]
@hoaquynhtim99 xem và sửa luôn dùm anh nhé.

**Comment by hoaquynhtim99** [comment]
@vuthao cái này cần bàn một tí:

Hiện tại có vấn đề đối với các trường `system=1` mặc dù đưa vào CSDL tuy nhiên khi xuất ra site các trường này xuất độc lập (fix cứng trong code) không xuất dạng các field do dó việc change weight là vô hiệu cái này cần viết lại.

Vấn đề thứ 2 ở hai trường first_name, last_name hai trường này weight nó cần khác nhau ở mỗi ngôn ngữ tương ứng biến `$global_config['name_show']` do đó cột weight của bảng field cần phải là weight theo lang. Cần sửa lại cái này.

**Comment by vuthao** [comment]
@hoaquynhtim99 
Các trưởng system = 1 là các trường của hệ thống, các trường này fix cứng không cho xóa, thay đổi vị trí (Nếu nó sai thì cấu hình lại cho đúng). Các trường này thực chất chỉ dùng các cấu hình.

Còn vấn đề first_name, last_name tạm thời ko nên thay đổi.

**Comment by hoaquynhtim99** [comment]
Hiện tại nếu cài đặt thêm ngôn ngữ tiếng Anh thì các trường dữ liệu hệ thống không có giá trị ở "Tiêu đề", phần các tùy chọn ở trường giới tính vẫn giữ Nam và Nữ

Hiên không xóa được trường dữ liệu tùy chọn ngay sau trường hệ thống, trường tiếp theo thứ 2 tùy chọn thì xóa được.
