### ISSUE TITLE
NukeViet 4.1 Official [Cấu hình chung] Giá trị của Google Maps API key

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2377]
Phần này, hệ thống tự lược dash (-) và underscore(_), trong khi API có 2 ký tự này.
Ngoài ra hệ thống tự chèn 1 API khác mặc định, mà có vẻ cũng sai cấu trúc.

https://github.com/nukeviet/nukeviet/blob/develop/admin/settings/system.php#L66-L69

**Comment by hoaquynhtim99** [comment]
Hiện mình đã fix ở đây https://github.com/hoaquynhtim99/nukeviet/commit/3a59a8c129d65745cfdcf92ba97d8027fad75af1 chính xác là Google MAP api key có cả ký tự `-` và `_` và bỏ luôn cái API key mặc định đó. Người dùng có thể bỏ trống chứ không nhất thiết phải cấu hình trường đó. Còn key mặc định hiện tại không sai

**Comment by anhyeuviolet** [comment]
Mình thấy như commit của @hoaquynhtim99 là ổn rồi. User có thể tự tìm cách cấu hình để lấy API được mà.

**Comment by ThinhNguyenVB** [comment]
ok rồi đó
