### ISSUE TITLE
Cấu hình bắt buộc sử dụng chức năng hai bước.

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2382]
Ở các phần mềm khác thường có Cấu hình bắt buộc sử dụng chức năng hai bước.

1. Force Clients to enable Two Factor Authentication on Next Login
2. Force Administrator Users to enable Two Factor Authentication on Next Login

Hiện tại NukeViet chưa có chức năng này.

Với NukeViet, mình đề xuất áp dụng cấu hình này cho từng nhóm tài khoản:
/admin/index.php?language=vi&nv=users&op=groups

Khi đó kiểm tra nếu tài khoản đăng nhập, mà chưa kích hoạt chức năng hai bước và thuộc 1 nhóm thì sẽ yêu cầu bắt buộc dùng chức năng này mới cho dùng các chức năng khác (Trừ module xác thực hai bước)

**Comment by hoaquynhtim99** [comment]
Đã thêm cơ bản tại: https://github.com/hoaquynhtim99/nukeviet/commit/78e91d8009fbd01ccf51ff0dee57147245845202

Hiện còn hai vấn đề sau cần làm tiếp:

Khi ngoài site không bắt buộc xác thực hai bước, trong admin bắt buộc, admin tiến hành đăng nhập thì nhận được thông báo là cần xác thực hai bước để tiếp tục nhấp vào link để bật, bên dưới có nút đăng nhập và link quên pass. Lúc này, không thể nhấp vào link quên pass vì hiện tại đã có tư cách thành viên rồi.

Như vậy thì có hai trường hợp:

- Không thể là thành viên khi đăng nhập như vậy
- Ẩn nút đăng nhập và link quên pass chỉ để lại thông báo.

Cái nào sẽ hợp lý?

**Comment by hoaquynhtim99** [comment]
Xử lý vấn đề 1 https://github.com/hoaquynhtim99/nukeviet/commit/a40dd07de12058dc640dbf28e2f45e6c22766c69

**Comment by vuthao** [comment]
Cái đó trên nguyên tắc sau: 
Chức năng xác thực 2 bước chỉ kiểm tra nếu là thành viên (Các nhóm không phải là thành viên sẽ không áp dụng.

Ngoài ra nếu bắt buộc xác thực hai bước ngoài site, admin không cần thì xảy ra trường hợp là admin nhưng không là thành viên? Như thế có vẻ vô lý.

Cái này có thể như sau: Khu vực admin chỉ truy cập từ 1 IP, nên có thể sẽ không cần xác thực 2 bước, việc này nên để mở để cho quản trị cấu hình.

**Comment by hoaquynhtim99** [comment]
@vuthao như vậy thì hiện tại đã xong.
