### ISSUE TITLE
Mất chức năng scroll trong quản trị

### ISSUE THREAD

**Issue by volong1012** [nukeviet/nukeviet#2387]
Ko biết có ai bị lỗi này ko nhưng khi em cài site lên thì trong admin ko thể cuộn được chuột lên xuống ?? toàn phải kéo bằng tay ... test thử ở ngoài site vẫn kéo bình thường và các trang website cũng ko sao cả.

**Comment by vuthao** [comment]
@volong1012 Xem lại quy định báo lỗi nhé.

* Nếu xác định lỗi từ code, vui lòng cung cấp thêm các thông tin về WebServer và trình duyệt

> - Phiên bản NukeViet: (Ví dụ NukeViet 4.0.21 hoặc NukeViet 2574f2bc8b6f23f9fcfefc021554034e33fbc695 - là chuỗi xác định commit trên kho code)
> - Môi trường thử Nghiệm: Localhost/ hosting
> - Hệ điều hành: (Ví dụ: Ubuntu 13.10 32-bit)
> - Trình duyệt web: (Ví dụ: Mozilla Firefox 27.0)
> - Máy chủ web: (Ví dụ: XAMPP for Linux 1.8.1 )
