### ISSUE TITLE
Mất nút Xóa module khỏi danh sách module ngưng hoạt động

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2393]
> Phiên bản NukeViet	4.1.02Kiểm tra phiên bản NukeViet
Phiên bản PHP	5.6.8
Giao thức giữa máy chủ và PHP	Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.6.24

![screenshot from 2017-06-15 06-43-49](https://user-images.githubusercontent.com/6407361/27159306-1f5098ae-5196-11e7-860c-026dea462dd8.png)

**Comment by vuthao** [comment]
Phiên bản đang phát triển lỗi này đã được sửa lại, @mynukeviet kiểm tra lại dùm xem nhé.

**Comment by mynukeviet** [comment]
Bản phát triển mới nhất hôm nay em vẫn còn thấy lỗi @vuthao

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/6a01b7a5f2b66f575df6b99921b2ed39c2254560
