### ISSUE TITLE
Lỗi chức năng chọn ảnh của module upload

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2395]
Phiên bản mới nhất trên nhánh dev bị lỗi:

Hiện tại tất cả các chức năng chọn ảnh của module upload từ các module đều không hoạt động.

Ví dụ: chọn logo của site
Chọn ảnh cho module news

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/6bb7b7eb7a55f8e5ac558bb58a0e52487ad59138
