### ISSUE TITLE
Lỗi cảnh báo về bảo mật Nukeviet khi kiểm thử bảo mật 

### ISSUE THREAD

**Issue by tranviethuy** [nukeviet/nukeviet#2403]
Bản Nukeviet 4.1 chạy trên Localhost, khi chạy phần mềm kiểm thử bảo mật OWASP-ZAP thì thấy có các cảnh báo bảo mật ở muc nguy hiểm cao (cờ màu đỏ) về: Cross-site Scripting, Path Traversal, SQL injection... như hình dưới. Mong bạn giúp đỡ xem thế nào?

![img-2017_loi](https://user-images.githubusercontent.com/25944302/27426537-38734716-5766-11e7-84cb-7a310d923150.png)

**Comment by vuthao** [comment]
Cám ơn bạn @tranviethuy đã thông báo.
Tuy nhiên bạn yên tâm các cảnh báo đó hầu hết là không đúng, hoặc không nguy hiểm thực sự.

Chúng tôi sẽ sửa lại code trong bản tới để chương trình này sẽ không thông báo các lỗi này.

**Comment by vuthao** [comment]
@tranviethuy hiện tại bản NukeViet 4.3 đã được kiểm tra và sửa để hạn chế các lỗi thông báo sai.
