### ISSUE TITLE
[News] Cho phép cấu hình layout cho 1 bài viết cụ thể trong module News

### ISSUE THREAD

**Issue by buiqthong** [nukeviet/nukeviet#2404]
Hiện tại chỉ có module page có chức năng cấu hình layout cho bài viết.
Khi tạo bài viết thì tất cả các bài viết của module news được cấu hình layout theo cấu hình layout của module. 

Tuy nhiên, một số users chỉ sử dụng module news nên không có biết hoặc không có quyền sử dụng module khác, vì vậy không thể cấu hình layout được theo ý muốn của họ.
VD: Cấu layout bài viết của module news là LEFT-MAIN-RIGHT và bây giờ users cần cấu hình 1 bài viết có layout là MAIN.

Do đó nên cho phép chức năng này trong tùy chỉnh nâng cao của module news giống như module page.

**Comment by hoaquynhtim99** [comment]
Hiện tại tính năng này đã có trên NukeVet 4.3.00
