### ISSUE TITLE
Một  số vấn đề của two step verification

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2410]
1. Không có link tắt two step verification (cái này test trên NukeViet.vn, cần kiểm tra lại trên bản NukeViet mới nhất!)

2. Nếu vô tình đang login mà truy cập trực tiếp link tạo mã dự phòng mới (link dưới) thì hệ thống xóa luôn mã cũ mà không hỏi lại, màn hình cũng thông báo gì. Nếu người dùng mà không để ý thì sẽ không lưu lại các mã này. Nguy cơ bị mất khả năng truy cập rất cao!

http://*.*/vi/two-step-verification/changecode/

**Comment by hoaquynhtim99** [comment]
Phần này đã sửa tại đây https://github.com/hoaquynhtim99/nukeviet/commit/1d038e13f8aea7dd9038f1283e5838e979c18e77
