### ISSUE TITLE
Lỗi khi trỏ url frame về website nukeviet bị trắng trang

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#2413]
Website chạy trên hosting linux nhưng khi trỏ một tên miền khác về website sử dụng nukeviet bị lỗi (bản mới nhất 4.1.02) bị lỗi dù ko bật tính năng chặn frame.

Đã kiểm tra cả theme mặc định và theme mới đều dính

**Comment by vuthao** [comment]
Vị dụ cụ thể hơn được không @ThinhNguyenVB 
Đọc thế này hại não quá.

**Comment by ThinhNguyenVB** [comment]
Ví dụ như này anh nhé:
Em sử dụng DNS của nhà cung cấp với domain giangiaolienviet.vn sử dụng tính năng url frame về giangiaolienviet.com thì sẽ không hoạt động được. Nhưng cũng tính năng url frame đó với mã nguồn khác thì bình thường
hay www.chocau.com frame về giangiaolienviet.com đều bị lỗi trắng tinh khôi

**Comment by hoaquynhtim99** [comment]
Phần này do các header X-Frame-Options' to 'sameorigin' mới add vào gần đây

**Comment by vuthao** [comment]
@hoaquynhtim99 Sửa lại cái đó dùm anh như sau nhé:
- khi cài mặc định bật tính năng: Chống IFRAME
- Nếu bật tính năng Chống IFRAME thì hãy thêm thẻ X-Frame-Options' to 'sameorigin'  ở ngoài site. Admin và các cái này luôn bật header X-Frame-Options' to 'sameorigin'

**Comment by hoaquynhtim99** [comment]
Đã sửa https://github.com/hoaquynhtim99/nukeviet/commit/de181870c7988a9b40197c7f776ca1e6c03e1110

**Comment by mynukeviet** [comment]
@ThinhNguyenVB Open cái này lại em với, có vẻ như đang lỗi

![screenshot from 2017-08-30 16-21-53](https://user-images.githubusercontent.com/6407361/29866076-76ecc79e-8da1-11e7-9e9d-ade4ff4fd40d.png)

![screenshot from 2017-08-30 16-21-30](https://user-images.githubusercontent.com/6407361/29866077-76ee618a-8da1-11e7-9a33-da87a99c0a0f.png)

**Comment by vuthao** [comment]
Để cấu hình lại vào phần:
/admin/index.php?language=vi&nv=settings&op=security

Chống IFRAME, hoặc cáu hình lại theo hướng dẫn của firebug
