### ISSUE TITLE
Module users: bỏ bắt buộc nhập tên và ngày sinh

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2416]
Thêm thành viên tại ACP, đang bắt thuộc phải nhập tên và ngày sinh, cái này mình thấy không cần thiết

![screenshot from 2017-07-11 16-59-44](https://user-images.githubusercontent.com/6407361/28063158-6b8ec988-665a-11e7-95dc-d17d0ae83dea.png)

**Comment by vuthao** [comment]
Thử bản mới nhất chưa em, nó cấu hình trong phần: admin/index.php?language=vi&nv=users&op=fields

**Comment by mynukeviet** [comment]
ôi, đúng là em đang xem trên bản cũ chứ ko phải đang phát triển, em mới xem rồi, thấy đúng là dã chuyển sang custom field.

Em chưa hiểu ý định chổ này, mấy trường này ở bảng `nv4_users` cũng có mà bảng `nv4_users_filed` cũng có, dữ liệu như nhau

**Comment by hoaquynhtim99** [comment]
@mynukeviet các trường đó mặc định không cho xóa không cho thay đổi kiểu chỉ có thể đổi tên, cấu hình cho ẩn hiện khi đăng ký nhằm mục đích tùy biến được cái form đăng ký.

Việc giữ nguyên ở bảng nv4_users nhằm đảm bảo các ứng dụng khác có thể khai thác dữ liệu như cũ mà không cần phải sửa đổi code, ngoài ra các trường này chỉ được lưu ở bảng nv4_users không lưu vào bảng nv4_users_info nên cũng không thừa dữ liệu

**Comment by mynukeviet** [comment]
Ok, tks @hoaquynhtim99
