### ISSUE TITLE
Lỗi khi sửa bài viết module news

### ISSUE THREAD

**Issue by nguyenphuongdong** [nukeviet/nukeviet#2418]
khi sửa bài viết trong module news. nó báo lỗi như này

![image](https://user-images.githubusercontent.com/19875796/28101855-72c7c150-66f5-11e7-883c-5b4bf416481f.png)

Phiên bản Nukeviet 4.1.01

**Comment by vuthao** [comment]
Đây không phải là lỗi bạn, mà 1 lúc có 2 người cùng sửa 1 bài viết

**Comment by nguyenphuongdong** [comment]
Không ạ. Bài đó viết xong, Nhân viên đó thoát ra 2-3 ngày sau vào sửa. Vẫn báo lỗi trên. Chứ ko phải là giữ quyền 2 người sửa. Rất bất tiện ạ

**Comment by nguyenphuongdong** [comment]
Xin hướng dẫn cách bỏ luôn chức năng đó. trở về như trước đây ạ

**Comment by vuthao** [comment]
Không bỏ được đâu bạn. Bạn phải tra thôi

Vào 12 Th7, 2017 11:47, "Lê Thúc Vinh" <notifications@github.com> đã viết:

**Comment by nguyenphuongdong** [comment]
Mình đã tra tới đoạn đó. bỏ trong code luôn cơ. Làm lỗi không sử dụng được ạ

**Comment by nguyenphuongdong** [comment]
Bạn phải tra thôi >> là tra code hay sao ạ

**Comment by nguyenphuongdong** [comment]
Có bạn nào giúp đỡ check tính năng này không ạ? Mình đã thoát tất cả câc nick ra. Reset mạng. Vào sửa vẫn báo lỗi chiếm dụng. Chứ có đang sửa gì đâu. Lỡ lưu 1 bài là không sửa được. Phải xóa đăng lại.

**Comment by anhyeuviolet** [comment]
Cái này em mới test lại tức thì trên NukeViet 4.1 bản mới nhất (4.1.02).
Tình trạng vẫn bị như trong issue này:
https://github.com/nukeviet/nukeviet/issues/2224

> 
> Vấn đề 2:
> Bạn B nhấn sửa bài, để đó không nhấn lưu. Nhấn vào Logo về trang chủ Admin.
> Bạn A chờ tới mùa quýt vẫn bị chiếm quyền =]]
> 
> Vấn đề 3:
> Bạn B nhấn sửa bài, để đó không nhấn lưu. Nhấn vào Logo về trang chủ Admin.
> 
> Del acc bạn B, bạn A vẫn bị thông báo lại là "Bạn bị chiếm quyền ... " ????

Trường hợp khác nữa là Admin B nhấn sửa bài, vì lý do gì đó không lưu (không lưu được) mà tắt cửa sổ đi luôn. Khi đó cũng bị khoá không thể sửa bài tới mãi mãi :(

**Comment by hoaquynhtim99** [comment]
Cái này mình thấy trên NukeViet 4.3.00 vẫn còn bị. Trong phân tích rất lâu rồi mình có ghi:

> Trong quá trình sửa bài cần request mỗi 10s một lần tới máy chủ để cập nhật lại thời gian online cuối cùng, nếu thời gian chênh lệch 60s tức xem như bài viết này đã "không còn sửa".

Khi làm các bạn làm đã bỏ qua ý này do đó trạng thái sửa bài sẽ tồn tại vĩnh viễn nếu không nhấn nút lưu.

Ngoài ra còn hai vấn đề:

- Tại trang list bài viết cần hiển thị icon "ổ khóa" tại những bài viết đang được sửa, khi để chuột vào thì hiển thị tip người đang sửa, sửa lúc nào.
- Check luôn quyền của người đang xem list, nếu bài viết đang sửa bởi người có quyền thấp hơn thì mới hiển thị nút sửa, xóa nếu quyền cao hơn hoặc ngang hàng cần phải ẩn nút này đi.
- Thêm lỗi: Nếu người khác đang sửa, người này vào sửa không được bị báo là đang bị sửa, tuy nhiên người này hoàn toàn có thể xóa bài viết đó đi.....

Các vấn đề này đã tồn tại lâu cần xử lý dứt điểm trên NukeViet 4.3.01

**Comment by hoaquynhtim99** [comment]
Các vấn đề đã được fix tại https://github.com/hoaquynhtim99/nukeviet/commit/3e142a247ec9cb824d57e94fc628b1b63c49f6b3
