### ISSUE TITLE
Thêm cấu hình tự động chuyển www.domain.com sang domain.com

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2430]
Cái này hiện tại nếu muốn làm phải thêm thủ công vào .htaccess, nên có cấu hình để khỏi bị mất mỗi khi cập nhật cấu hình chung

**Comment by vuthao** [comment]
Việc này có thể thực hiện trên domain là nhanh nhất, nếu thêm càng nhiều cấu hình vào hệ thống thì càng nặng nề.
Ngoài ra  trên nginx cũng không chạy được phần này.

Nên chăng viết 1 plugin làm việc này có thể sẽ tốt hơn.

**Comment by mynukeviet** [comment]
dạ, plugin cũng là 1 ý hay đó anh

**Comment by mynukeviet** [comment]
```
if (substr($_SERVER['HTTP_HOST'], 0, 4) === 'www.') {
    header("HTTP/1.1 301 Moved Permanently");
    header('Location: http' . (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' ? 's' : '') . '://' . substr($_SERVER['HTTP_HOST'], 4) . $_SERVER['REQUEST_URI']);
    exit();
}
```
Em đã test ổn, @vuthao xem qua xí rồi em đưa lên kho code nhé

**Comment by vuthao** [comment]
Chắc là ổn đó @mynukeviet 
đặt tên plugin là: redirect_www_to_nowww.php nhỉ

**Comment by mynukeviet** [comment]
**redirect_to_non_www.php** tên này anh hì, để em commit

**Comment by mynukeviet** [comment]
Đã thêm https://github.com/nukeviet/nukeviet/commit/80b093691323a421955ef9fbd0c3c44c0421b22d
