### ISSUE TITLE
Phát triển tính năng quản lý quảng cáo ngoài site

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2443]
Yêu cầu:
- Do phần quản lý tài khoản tách riêng, ko liên quan đến thành viên. Nên xen xét việc bỏ tài khỏan quảng cáo đi, mà thay  bằng sử dụng thành viên. Hoặc là có chức năng đăng ký tài khoản quảng cáo từ việc lấy thông tin thành viên.
- Phân quyền khối quảng cáo, có cho thành viên đăng hay không. Cấu hình thời gian được hiển thị ngoài site cho từng khối (Khi thêm mới quảng cáo)
- Khi tài khoản đăng quảng cáo ngoài site, thì quản trị duyệt và kích hoạt mới hiển thị ra ngoài site.

**Comment by hoaquynhtim99** [comment]
@vuthao theo em bỏ tài khoản quảng cáo đi là hợp lý, tuy nhiên trong quản trị mục thêm khách hàng, khách hàng thì vẫn giữ lại và toàn bộ các thông tin khác trừ **Kiểu file được upload** là lấy từ tài khoản thành viên luôn.

Bên ngoài site nếu khi thành viên login vào chưa được set tài khoản quảng cáo trong admin thì hiển thị form đăng ký càng tốt.

Có chức năng cấu hình cho phép/không cho phép thành viên đăng ký

**Comment by vuthao** [comment]
Theo anh sửa lại như sau:
- Bỏ phần qủan lý khách hàng.
- Trong mỗi khối quảng cáo cấu hình thêm như sau:
1. Thêm Kiểu file được upload: images, flash bởi mỗi khối quảng cáo có nhu cầu riêng.
1. Cấu hình nhóm thành viên nào được đăng quảng cáo.
1. Cấu hình thời gian được hiển thị ngoài site cho từng khối (Khi thêm mới quảng cáo)
- Khi tài khoản đăng quảng cáo ngoài site, thì quản trị duyệt và kích hoạt mới hiển thị ra ngoài site.(nếu chưa có thời gian hết hạn mà có cấu hình thời gian hết hạn theo khối thì set lại thời gian hết hạn tính từ thời điểm kích hoạt). Duyệt rồi sẽ không cho sửa nữa.
- Bên ngoài site: /banners/addads/ bỏ thời gian bắt đầu, kết thúc. Nếu khối không yêu cầu hình ảnh thì ẩn   chức năng upload ngoài site đi.

**Comment by hoaquynhtim99** [comment]
@vuthao ok anh thế cũng được. Có cái này:

> Nếu khối không yêu cầu hình ảnh thì ẩn chức năng upload ngoài site đi.

Cái này anh thấy ổn không, không yêu cầu với không cho phép là khác nhau ấy.

**Comment by mynukeviet** [comment]
> Theo anh sửa lại như sau:

Em cũng đồng ý với phương án này

**Comment by vuthao** [comment]
Hiện tại phần này đã xử lý xong, mình xin phép đóng vấn đề này lại
