### ISSUE TITLE
[Đề xuất] Thêm cấu hình module mặc định hiển thị trên trang chính khu vực quản trị

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2444]
Mặc định hiển thị cái siteinfo, nhưng một số trường hợp quản trị muốn hiển thị ngay một module nào đó chứ không phải là siteinfo nữa

**Comment by vuthao** [comment]
@mynukeviet nếu thế cần nghĩ thêm các cái sau:
- Mỗi ngưòi quản trị thích một kiểu.
- Mỗi ngôn ngữ thích 1 kiểu.
- Quản trị cấu hình 1 kiểu, ngưòi dùng cấu hình 1 kiểu.
- Quyền hạn của người điều hành module không có.
....
Sẽ phải nghĩ tất cả các tính huống trước khi lập trình nhé.

**Comment by mynukeviet** [comment]
> Mỗi ngưòi quản trị thích một kiểu.
Mỗi ngôn ngữ thích 1 kiểu.
Quản trị cấu hình 1 kiểu, ngưòi dùng cấu hình 1 kiểu.

Cái này mình quy định toàn hệ thống luôn anh hì, chứ không cho tùy biến đến từng người quản trị làm gì.

> Quyền hạn của người điều hành module không có.

Còn cái này thì nếu ko có thì dùng siteinfo hiển thị mặc định. Mấy hôm nay em xử cái này.

**Comment by vuthao** [comment]
@mynukeviet Cái này sẽ áp dụng cho cả site hay cấu hình cho từng người quản trị.

Nếu áp dụng cho từng người quản trị, em thêm dùm anh 1 cấu hình: “Giao diện sử dụng”, còn phần lập trình cho cái này anh sẽ lập trình sau.

**Comment by vuthao** [comment]
Hiện tại tính năng này đã có ở bản NukeViet 4.3.01.
