### ISSUE TITLE
Thay đổi đường dẫn module Page

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/nukeviet#2458]
Hồi trước em thấy module page không có tên module trên đường link giống với loại bỏ tên module nhưng 2 bản gần đây thấy module page hiển thị tên module trên đường link.

**Comment by hoaquynhtim99** [comment]
Module page giờ là một module độc lập, theo như cách cũ thì không thể có module thứ hai ngoại trừ module page có dạng link:

```
http://domain.com/alias-post.html
```

Mà bắt buộc phải là:

```
http://domain.com/cat-alias/post-alias.html
```

Nếu hi sinh đi module page thì tất cả các module khác có thể rút ngắn gọi link một cách triệt để. Từ hai phiên bản trở lại đây đang áp dụng phương án đó.

Nếu bạn đã lỡ SEO một website có link module page và news đồng thời rút gọn thì hãy làm một chủ đề trên diễn đàn, sau khi bản 4.2.01 phát hành mình sẽ hướng dẫn cách khắc phục

**Comment by vuthao** [comment]
@hoaquynhtim99 4.2 đã ra rồi, sắp sửa là 4.3 nhưng chưa có hướng dẫn này nhỉ.

**Comment by hoaquynhtim99** [comment]
Xem hướng dẫn ở https://nukeviet.vn/vi/forum/Huong-dan-sua-duong-dan-module-page-sau-khi-nang-cap-len-ban-4-1-Official-tro-len-t44216/
