### ISSUE TITLE
Báo lỗi Does not exist khi Search any thing on site

### ISSUE THREAD

**Issue by billygoat-trump** [nukeviet/nukeviet#2469]
Nâng cấp thành công 4.1 -to- 4.2 tuy nhiên khi tìm kiếm trên site thì báo lỗi này:

**Thông báo từ Hệ thống Lỗi cảnh báo Lỗi cảnh báo**: file_get_contents(/home/xxxxxxxxx/public_html/xxxxxxxxx.com.vn/themes/default/modules/seek/result.tpl): failed to open stream: No such file or directory in file /includes/xtemplate.class.php on line 1395

[XTemplate] [] (/home/xxxxxxxxx/public_html/xxxxxxxxxx.com.vn/themes/default/modules/seek/form.tpl) does not exist

@MOD kiểm tra dùm xem, Khi update tự động thì Module SEEK mất tác dụng và trong /default/modules/seek/ không có folder seek, cài lại trong ACP cũng không được, buộc phải dẫn bằng FTP vào host mới khắc phục

**Comment by vuthao** [comment]
Lối này liên quan đến hosting của bạn nhiều hơn là do code.

Để có thể dễ phân tích hơn, bạn vui lòng cung cấp thông tin theo hướng dẫn: https://github.com/nukeviet/nukeviet/blob/develop/.github/CONTRIBUTING.md
