### ISSUE TITLE
Khi nhập tin và chuyển duyệt bài thì trạng thái bài viết trong danh sách bài viết hiển thị không phù hợp.

### ISSUE THREAD

**Issue by tranviethuy** [nukeviet/nukeviet#2470]
Trường hợp khi thêm bài viết trong admin control của chuyên mục tin tức News (nukeviet 4.1), sau khi nhập xong nội dung bài viết:
+ Nếu chọn **lưu bài. chuyển biên tập** thì trạng thái trong danh sách bài viết là **Từ chối duyệt bài**
+ Nếu chọn **lưu bài. chuyển tổng biên tập** thì trạng thái bài viết là **Ngưng hiệu lực**
Như vậy là trạng thái bài viết không phù hợp với chức năng đã chọn. Nhờ các bạn xem có gì nhầm ở đây không?

![image](https://user-images.githubusercontent.com/25944302/29070245-ac5fb8b8-7c68-11e7-8884-9d0825a2095e.png)

**Comment by vuthao** [comment]
Bặm nâng cấp lên bản 4.2 nhé

**Comment by tranviethuy** [comment]
Nếu sử dụng Modul News 4.2 cho 4,1 để sửa lỗi nay có được không bạn?

**Comment by vuthao** [comment]
Bạn nên nâng cấp site nhé.

**Comment by tranviethuy** [comment]
Cảm ơn bạn.
