### ISSUE TITLE
Lỗi cấu hình google font của giao diện

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2473]
Tại khu vực Quản lý giao diện => Thiết lập giao diện => Google Font

Khi nhấp lưu lại (trước đó đã có) hệ thống không xóa đi file css tương ứng ở assets/css điều này sẽ gây phiên toái trong trường hợp thay đổi đường dẫn site ví dụ domain.com/folder/ thành domain.com/

**Comment by vuthao** [comment]
@hoaquynhtim99 Xem dùm em cái này nhé.

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/80601771afc873d04fc2d64e9da3817df5141712
