### ISSUE TITLE
Lỗi lang khi sử dụng input kiểu file trên trình duyệt chorme

### ISSUE THREAD

**Issue by ngocphan123** [nukeviet/nukeviet#2475]
Khi sử dụng trình duyệt  chorme cho giao diện tiếng anh sử dụng thẻ input sau:

`<input type="file" name="image" id="image" value="" class="form-control">`

thì vẫn giữ nguyên ngôn ngữ tiếng việt không đổi sang tiếng anh tương ứng.

**Comment by vuthao** [comment]
Cái này nó theo ngôn ngữ lúc cài trình duyệt .

**Comment by hoaquynhtim99** [comment]
Cái này hiện CSS là không thể đổi được lang của nút browse file. Chỉ có thể làm thủ công bằng cách cho nút upload "trong suốt" sau đó bên dưới nút upload thêm một label với ngôn ngữ theo ý.
Có thể thực hiện cái trên bằng 2 cách:
-  Kiểm tra và sửa từng chỗ có file upload => Rất lâu
- Dùng javascript quét và sửa => Không phải lúc nào cũng hoạt động được đối với các thành phần được control bằng javascript sau khi load trang ví dụ nút chọn file ở module download khi nhấn nút "thêm file download"
