### ISSUE TITLE
Bài hẹn giờ đăng thường khi share facebook bị facebook báo lỗi truy cập 404 

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2479]
Lỗi xuất hiện trên site NukeViet.vn

Hẹn đăng bài lúc 7h45'
![anh-chup-14](https://user-images.githubusercontent.com/1892900/29394775-d16694f4-8336-11e7-8ae3-6e8c3da6c423.jpg)

Nhưng kiểm tra trên "trình gỡ lỗi chia sẻ" của facebook thấy facebook đã nạp cache từ trước đó (ngay sau lúc bài submit lên website thì phải). Đây là lý do bị báo lỗi 404.
![anh-chup-13](https://user-images.githubusercontent.com/1892900/29394809-12139254-8337-11e7-8a52-82e29bdc2a60.jpg)

Cần kiểm tra xem tại sao facebook biết link và truy cập trang này khi nó còn chưa phát hành?

**Comment by vuthao** [comment]
Cái này do quản trị thôi, chưa cho hiệu lực share làm ghì, tự làm tự chịu vậy

**Comment by thehung** [comment]
Share trước khi đăng bài thì nói làm gì! Ở đây là sau khi bài xuất bản mới share mà bị lỗi thì mới có chuyện để nói ấy chứ :-)

**Comment by hoaquynhtim99** [comment]
Phần này em đã kiểm tra lại, bài đăng hẹn giờ không xuất hiện ở đâu, chỉ duy nhất khi quản trị click xem ngoài site.
Như vậy khả năng duy nhất là cái plugin Facebook Like nó tự cache, em đã sửa khi bài chưa đăng thì cho ẩn các công cụ social tại https://github.com/hoaquynhtim99/nukeviet/commit/e4181419e773d5c3e00affcad1c0fae494337aed
