### ISSUE TITLE
Hỗ trợ Hook và Event cho Nukeviet module

### ISSUE THREAD

**Issue by tanviet12** [nukeviet/nukeviet#2481]
Hiện tại khi viết module, nếu muốn phát triển một số tính năng can thiệp nhiều hơn vào hệ thống cho Nukeviet thì rất khó và hầu như phải sửa code. Sửa code thì dễ dẫn đến lỗi, rất khó update cũng như khó cho cho người dùng. Nếu Nukeviet hỗ trợ Hook thì tốt biết mấy cho Developer.

Về hook thì khi một sự kiện (event) quan trọng xảy ra, Nukeviet sẽ gọi đến hook tương ứng. Khi lập trình module có thể đăng ký hook để hệ thống tự gọi.

 Ví dụ. Muốn thực hiện một action nào đó SAU KHI người dùng LOGIN. 
1. Nukeviet hỗ trợ hook tên là after_clientlogin , thư mục để chứa hook là includes/extend/hooks/

2. Developer tạo file after_clientlogin_tenmodule_01.php vào, file này chứa code php cần thực thi như code tạo cookie chẳng hạn.

3. Mỗi khi user login, hệ thống sẽ tự động thực thi file includes/extend/hooks/after_clientlogin_tenmodule_01.php .

Tham khảo https://codex.wordpress.org/Plugin_API/Hooks_2.0.x , https://developers.whmcs.com/hooks/

**Comment by mynukeviet** [comment]
Chuẩn lắm @tanviet12 , cái này em thích đã lâu nhưng không biết dùng ngôn từ gì để mô tả, đọc tài liệu thấy hàm `add_filter` của wp em rất khoái :). Thêm cái này vào nó làm được khá là nhiều việc, ủng hộ phát triển (y)

**Comment by tanviet12** [comment]
`Chuẩn lắm @tanviet12 , cái này em thích đã lâu nhưng không biết dùng ngôn từ gì để mô tả, đọc tài liệu thấy hàm add_filter của wp em rất khoái :). Thêm cái này vào nó làm được khá là nhiều việc, ủng hộ phát triển (y)`

Anh thấy nó giống như tiêu chuẩn rồi. Các hệ thống cho code tích hợp module thì đều có hook. Tiện lắm :D

**Comment by hoaquynhtim99** [comment]
Các phần đã làm cho NukeViet 5:
- Hook của hệ thống đặt vào https://github.com/nukeviet/nukeviet/tree/develop/src/includes/plugin
- Hook của module đặt vào thư mục hooks của mỗi module https://github.com/nukeviet/nukeviet/tree/develop/src/modules/Menu/hooks
- Chuyển các plugin và phần quản lý plugin thành quản lý hook (/admin/index.php?language=vi&nv=settings&op=plugin). Hạn chế của phần này còn tồn đọng:
    - Hook của hệ thống chỉ thêm được 1 lần => Đã ok
    - Hook của module do có module ảo nên việc xác định đã thêm trên tất cả các module ảo hay chưa chưa ổn, code chỗ này lằng nhằng mà chưa xong.
- Thêm hàm [nv_apply_hook](https://github.com/nukeviet/nukeviet/blob/develop/src/includes/functions.php#L2155)
- Thêm hàm [nv_add_hook](https://github.com/nukeviet/nukeviet/blob/develop/src/includes/functions.php#L2209)
- Khi build file config_global.php thì ghi ra file phần hook này https://github.com/nukeviet/nukeviet/blob/develop/src/includes/core/admin_functions.php#L222-L255
- Sau khi load ngôn ngữ chính xong thì require các file hook này https://github.com/nukeviet/nukeviet/blob/develop/src/includes/mainfile.php#L160-L171
- Danh sách các hook đã viết ở NukeViet 5 https://wiki.nukeviet.vn/nukeviet5:codex:hooks-reference
- Có một tool đã viết quét hết các file php tìm và trích xuất tài liệu cho wiki https://github.com/nukeviet/nukeviet/tree/develop/tools/hooks

**Comment by hoaquynhtim99** [comment]
Đối với hook của module (đặt trong thư mục modules/xxxx/hooks) có thể bổ sung 2 giá trị  `$nv_hook_module, $nv_receive_module` ví dụ

```php
<?php

/**
 * @Project NUKEVIET 4.x
 * @Author VINADES.,JSC <contact@vinades.vn>
 * @Copyright (C) 2014 VINADES ., JSC. All rights reserved
 * @License GNU/GPL version 2 or any later version
 * @Createdate Dec 3, 2010 11:24:58 AM
 */

//$nv_hook_module = 'Marketing';
$nv_receive_module = 'Marketing'; // Event của hệ thống và module nhận là Marketing

$callback = function($vars, $from_data, $receive_data) {
    $module_name = $receive_data['module_name'];
    $module_info = $receive_data['module_info'];
    $module_data = $module_info['module_data'];

    $campaign = $vars[0]; // Chiến dịch
    $event = $vars[1]; // Sự kiện
    
    return $is_event_ok;
};
nv_add_hook($module_name, 'mt_check_contact_c1_44', $priority, $callback, $hook_module, $pid);
```

- `$nv_hook_module` biểu thị module xảy ra event
- `$nv_receive_module` biểu thị module nhận event (truyền event đó tới)

Hai giá trị này nhận `$module_file` không phải `$module_name`, nó dùng trong phần thiết lập plugin ở quản trị giúp quản trị chọn module diễn ra event và module nhận event đó.

Không khai báo `$nv_hook_module` tức là nhận event từ hệ thống, không khai báo `$nv_receive_module` tức là truyền event đó tới hệ thống.

Ví dụ: 

- File hook đặt trong modules/custom/hooks.php
- Nhận event từ các module gốc, module ảo của news 
- Truyền tới module gốc, ảo của page thì viết

```php
<?php

/**
 * @Project NUKEVIET 4.x
 * @Author VINADES.,JSC <contact@vinades.vn>
 * @Copyright (C) 2014 VINADES ., JSC. All rights reserved
 * @License GNU/GPL version 2 or any later version
 * @Createdate Dec 3, 2010 11:24:58 AM
 */

$nv_hook_module = 'news';
$nv_receive_module = 'page'; 

$callback = function($vars, $from_data, $receive_data) {
    $module_name = $receive_data['module_name'];
    $module_info = $receive_data['module_info'];
    $module_data = $module_info['module_data'];

    $campaign = $vars[0]; // Chiến dịch
    $event = $vars[1]; // Sự kiện
    
    return $is_event_ok;
};
nv_add_hook($module_name, 'event_name', $priority, $callback, $hook_module, $pid);
```

Lưu ý: Hiện tại mỗi file chỉ được viết 1 hook vào, không thể viết nhiều hook trong cùng 1 file.

**Comment by hoaquynhtim99** [comment]
Hiện phần này đã đưa vào NukeViet 4.6, đang sử dụng và tính năng đã tương đối hoàn thiện, ổn định
