### ISSUE TITLE
Thêm plugin khu vực admin

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2483]
Hiện plugin chỉ được dùng cho khu vực site, đề xuất thêm tùy chọn cho khu vực admin

**Comment by vuthao** [comment]
plugin hiện tại khi cấp hình sẽ áp dụng cho cả site.

Muốn gới hạn như thế nào người lập trình tự quyết định nhé @mynukeviet

**Comment by mynukeviet** [comment]
Ý em là plugin hệ thống **Cấu hình / Thiết lập plugin** ý anh, em chưa thấy nó được gọi ở admin

**Comment by vuthao** [comment]
Cho 1 ví dụ cụ thể đi để anh kiểm tra @mynukeviet

**Comment by mynukeviet** [comment]
à sr anh, em có chút nhầm lẫn
