### ISSUE TITLE
Kiểm tra phiên bản NukeViet và các module

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2486]
Hiện tại tính năng kiểm tra phiên bản NukeViet tương đối tốt.

Tuy nhiên có những module, giao diện đã được lập trình viên tùy biến lại rất nhiều. Nếu ngưòi dùng nâng cấp vào khả năng chắc chắn sẽ không dùng được. Lỗi module đó.

Do đó cần có cấu hình cứng từ file config danh sách các module không cần kiểm tra nâng cấp để tránh người dùng hoang mang.

**Comment by hoaquynhtim99** [comment]
Phần này em đã thêm tại https://github.com/hoaquynhtim99/nukeviet/commit/7a7e84972515f7e01190f4c8ba40f478c393831e
Hướng dẫn: https://wiki.nukeviet.vn/nukeviet4:advanced_setting:file_config
