### ISSUE TITLE
Module menu nạp cả những bài viết không được kích hoạt của module about

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2491]
Phiên bản NukeViet 4.2.01, Trong phần quản trị module menu, khi thực hiện thao tác "Nạp lại các thành phần con là chủ đề của module", nó nạp tất cả các bài viết đã ngưng hoạt động của module about dẫn đến tình trạng link menu đó không tồn tại!

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/dcc451e3bd6ad4d98b92d39acd292e036caa4f48
