### ISSUE TITLE
Cần bổ sung cấu hình số lượng quảng cáo sẽ hiển thị trong mỗi khối quảng cáo (module banners)

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2492]
Hiện, mỗi khối quảng cáo có 2 kiểu trình bày là random (ngẫu nhiên) và sequential (tuần tự), nhưng cả 2 kiểu trình bày này đều ở dạng "liệt kê" khiến cho toàn bộ các quảng cáo trong khối quảng cáo được hiển thị ra ngoài. Điều này là không phù hợp trong nhiều trường hợp vì diện tích quảng cáo thường bị hạn chế, ví dụ: vị trí quảng cáo chỉ có thể đặt 1 banner nhưng được "chia sẻ" cho 4 khách hàng.

Để giải quyết bài toán này, cần bổ sung thêm cấu hình số quảng cáo tối đa hiển thị cùng lúc (Nếu không khai báo thì cho hiển thị toàn bộ).

**Comment by vuthao** [comment]
Đây là thiết kế mặc định.

Nếu muốn hiển thị thì sẽ phải viết thêm javascipt cho việc này.

và việc này dành cho các nhà phát triển tùy biến riêng cho site mình.
