### ISSUE TITLE
Module upload: thêm tính năng lấy url của ảnh

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2495]
Hiện tại 1 hình ảnh trong module upload không biết lấy link như thế nào.

Đề nghị bổ sung thêm tính năng để có thể copy được link khi click vào nút xem chi tiết.

**Comment by thehung** [comment]
Hiện phải click chuột phải để copi image location :D

**Comment by hoaquynhtim99** [comment]
Đã thêm https://github.com/nukeviet/nukeviet/pull/2499
