### ISSUE TITLE
Mất chức năng chỉnh kích cỡ logo khi chèn logo vào ảnh theo cách thủ công

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2497]
Ở các phiên bản bản NukeViet cũ, việc chèn logo vào ảnh thủ công cho phép chỉnh ích cỡ logo theo ý thích. Tuy nhiên bản 4.2 hiện giờ bị fix cứng theo cấu hình chèn tự động. Nên cho phép người quản lý thay đổi kích thước trong trường hợp chèn thủ công!

**Comment by hoaquynhtim99** [comment]
Đã sửa ở https://github.com/hoaquynhtim99/nukeviet/commit/691cad3688ac3ec7101496d7213f901f8857e565
