### ISSUE TITLE
Module voting: quản trị không thấy được thống kê chi tiết

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2498]
Hiện khu vực quản trị chỉ mới thấy được thống kê tổng quát, chưa thấy thống kê chi tiết.

Đề xuất thêm popup xem chi tiết thông tin

![screenshot from 2017-09-05 15-29-59](https://user-images.githubusercontent.com/6407361/30052253-193bb706-924f-11e7-974b-924cf8468f73.png)

**Comment by hoaquynhtim99** [comment]
Đã thêm ở https://github.com/hoaquynhtim99/nukeviet/commit/9f8dae6ebc876becc5f639d0d0317518e541ae0e
