### ISSUE TITLE
Báo lỗi: Đăng ký popup bản 4.2

### ISSUE THREAD

**Issue by thanhchunghti** [nukeviet/nukeviet#2507]
Mình báo lỗi lúc đăng ký bẳng popup không chọn được ngày sinh.

Còn ở link đăng ký users/register thì vẫn chọn được ngày sinh bình thường.

Mình cảm ơn.

**Comment by hoaquynhtim99** [comment]
Lỗi này đã được sửa và sẽ fix trong bản tới, nếu bạn đang dùng bản cũ muốn sửa trước thì làm theo hướng dẫn tại đây https://nukeviet.vn/vi/forum/Huong-dan-sua-mot-so-loi-o-ban-4-2-01-t43591/
