### ISSUE TITLE
Lỗi tương thích với phiển bản php 7.2

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2513]
PHP hiện tại chưa phát hành chính thức nhưng có nhiều thay đổi sẽ phải sửa lại code.

https://wiki.php.net/rfc/deprecations_php_7_2
https://viblo.asia/p/deprecations-trong-phien-ban-php-72-eoazLJEWROm

Ví dụ: 

1. parse_str() bắt buộc có tham số thứ 2
2. bỏ function each chuyển sang dùng foreach 
....

**Comment by hoaquynhtim99** [comment]
2. Sử dụng cú pháp tìm `[\s\t\=]+each[\s]*\((.*?)` bằng NotePad++ cho ra 13 vị trí đang dùng.
