### ISSUE TITLE
Module News không có tính năng tắt chủ đề

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2517]
Hiện tại mới chỉ có tính năng hiển thị trên trang chủ, chứ không thể cấm truy cập chuyên mục.

**Comment by vuthao** [comment]
Theo mình là thêm 1 trường active kiểm tra trạng thái của chủ đề. với các giá trị:
0: Cấm truy cập
1: Hiển trị theo phân chuyền của chủ đề đó.
2: Hiển thị trên trang chủ.

Sau đó xóa phần cấu hình hiển thị trên trang chủ hiện tại đi, để đỡ nhiều cấu hình.

**Comment by hoaquynhtim99** [comment]
### Hiện có hai phương án:

1. Thực hiện truy vấn cập nhật cho tất cả các tin khi kích hoạt/ngưng kích hoạt chủ đề, các tin này nằm trong bảng rows và bảng cat tương ứng
2. Thực hiện câu truy vấn ngay lúc duyệt tin thông qua lệnh IN(các catid được phép) hoặc NOT IN(các catid bị cấm)

### Vấn đề:

Phương án 1: 

- Dữ liệu cập nhật có thể sẽ rất lớn lên đến hàng triệu rows. Áp dụng cơ chế khi số lượng bài viết lớn hơn 500.000 chẳng hạn thì ẩn đi và khóa chức năng đình chỉ chủ đề lại.
- Khi cập nhật cần phải lưu giá trị status vào một trường bstatus để khi kích hoạt lại chủ đề thì đẩy trường bstatus trở lại vào status. Khi chủ đề bị khóa thì khóa luôn chức năng thay đổi trạng thái và các tiến trình như cron thao tác với bài viết.
- Dừng hoạt động chủ đề cha sẽ dừng luôn chủ đề con và các bài viết tương ứng.

Phương án 2:

- Các khu vực sau sẽ phải dùng lệnh IN hoặc NOT IN: Trang chủ với kiểu hiển thị Danh sách mới lên trên, cũ lên trên, xem dạng lưới, xem dạng tiêu đề; sitemapl rss, search; block news cat; block tophits => Việc dùng lệnh này sẽ tăng thời gian truy vấn CSDL lên đáng kể.
- Chỉ phù hợp với dữ liệu nhỏ

**Comment by vuthao** [comment]
Mình chọn phương án 1, chú ý lập trình khi cập nhật CSDL lớn.

**Comment by hoaquynhtim99** [comment]
Một vấn đề nữa là bài viết đang bị khóa bởi chuyên mục này, nếu sửa bài viết và đưa sang chuyên mục khác thì cần phải lập trình trả lại trạng thái bài viết trước đó

**Comment by thehung** [comment]
Theo anh không nên can thiệp vào việc hiển thị bài viết, tức là chỉ cần
kiểm tra chuyên mục có bị khóa hay không, nếu chuyên mục bị khóa mà bài
được gọi qua chuyên mục đó thì nó sẽ không hiển thị.

Tuy nhiên lúc này cần xem xét vấn đề chuyên mục chính, chuyên mục phụ. Vì
google nó sẽ dẫn bài qua chuyên mục chính. Mà chuyên mục chính bị khóa thì
sẽ lỗi!

**Comment by hoaquynhtim99** [comment]
@thehung Cái này yêu cầu không phải chỉ là cho xem chi tiết hay không thôi anh mà cần phải tắt hiển thị hết tại tất cả các khu vực: Main, viewcat, groups, block, rss, sitemap ở cấp độ chuyên mục lẫn bài viết

**Comment by thehung** [comment]
Điều em nói hoàn toàn đúng khi bài viết ở 1 chuyên mục.

Nhưng nếu 1 bài viết nằm ở nhiều chuyên mục và chỉ 1 trong số các chuyên
mục đó bị khóa (chuyên mục khác không bị), thì bài viết vẫn phải được hiển
thị ở chuyên mục không bị khóa chứ? Như vậy việc hiển thị hay không sẽ phụ
thuộc chuyên mục, đâu phụ thuộc bài viết!

Rắc rối rồi đây!

**Comment by hoaquynhtim99** [comment]
@thehung Để chắc chắn không bị sai thì em cho lâp trình nếu khóa chuyên mục thì sẽ khóa tất cả các bài viết có ở chuyên mục đó bao gồm việc bài viết có chuyên mục chính hay phụ là chuyên mục bị khóa.
Khi mở khóa thì kiểm tra nếu bài viết không thuộc chuyên mục nào bị khóa mới trả lại trạng thái ban đầu.
Việc khóa bài viết không ảnh hưởng đến việc sửa bài viết, nếu sửa bài viết mà đổi hoàn toàn chuyên mục sang các chuyên mục khác thì bài viết sẽ tự động được trả lại trang thái ban đầu trước khi bị khóa.
