### ISSUE TITLE
Lỗi Menu Responsive

### ISSUE THREAD

**Issue by volong1012** [nukeviet/nukeviet#2518]
Hiện nay ở phiên bản mới nhất thì menu (mặc định) khi hiển thị ở các thiết bị di động đều sổ hết cả ra .. trường hợp menu ngắn thì không sao nhưng nếu dài thì kéo mệt nghỉ luôn

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/026754f0dec1c3233ae62adf58ec3808a93f9d5e
