### ISSUE TITLE
Loại bỏ bớt các dữ liệu được sao chép khi copi bản tin

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2532]
Khi thực hiện copi bản tin trong news, các dữ liệu không cho phép admin can thiệp như: số lượng xem, số lượng comment, số lượng vote, điểm vote... cần được reset về 0.

**Comment by thuvp1995** [comment]
Lỗi này đã được fix

**Comment by vuthao** [comment]
@thuvp1995 khi fix em cần copy link ứng với commit để mọi ngưòi tiện kiểm tra nhé.
