### ISSUE TITLE
Thêm tính năng đính kèm file vào module News

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2538]
Hiện tại module News chưa có đính kèm riêng file. do đó có thể xử lý lại như sau

Nếu bài viết có ảnh hoặc iframe thì không bắt buộc nhập text nữa.
Thêm chức năng đính kèm file tương tự như module văn bản (Cho phép upload nhiều file, CSDL chỉ lưu vào bảng news_detail). Khi xem ngoài file, có chức năng download các file này và
1. Nếu là file ảnh thì hiển thị luôn.
2. Nếu là file pdf thì dùng /assets/js/pdf.js để hiển thị. Việc kiểm tra quyền hiển thị file như quyền xem chi tiết nội dung.
3. Nếu là các file văn bản khác có thể xem qua iframe thông qua google doc (Như trong trình soạn thảo)

**Comment by hoaquynhtim99** [comment]
Các file đính kèm list ở đầu hoặc ở cuối bài viết (ưu tiên ở đầu), nếu có cấu hình module thì càng tốt.
List dạng danh sách các file tải về như law, nhấp vào để tải về, cái nào hỗ trợ hiển thị thì có nút xem (click vào "collapse" để hiển thị như laws)

**Comment by vuthao** [comment]
Nếu sau khi làm xong cho News thì làm cho cả module Page luôn.

**Comment by thehung** [comment]
Nên cải thiện chức năng này từ trình quản lý tệp tin để sử dụng chung cho các module khác, không nên làm chức năng riêng cho news (sau này dễ thành copi code cho các module), dẫn đến rủi ro cho việc bảo trì code.

**Comment by vuthao** [comment]
Trình soạn thảo không thể làm hết việc này được đâu @thehung

**Comment by thehung** [comment]
Một phương án khác là bổ sug API cho nhúng tag gọi file đến module download từ các module khác. Ví dụ trong bài viết tin tức, muốn gọi đến file có ID 199 trong module download thì đặt vào trong bài 1 tag kiểu như `{module:download|id:199}`
Demo như ở cuối bài này: https://www.thongtincongnghe.com/article/21122

**Comment by hoaquynhtim99** [comment]
Cái này soạn thảo bbcode hoặc Markdown còn trình soạn thảo HTML mà chèn cái này thì em thấy không ổn, viết mấy cái này chỉ dành do những người rất am hiểu.
Tốt nhất vẫn làm riêng chức năng cho module, ai cũng dùng được

**Comment by thuvp1995** [comment]
Module news đã được thêm chức năng đính kèm file vào bài viết
