### ISSUE TITLE
Cơ chế thuộc tính meta og:description khi chọn module hiển thị mặc đinh

### ISSUE THREAD

**Issue by motcaitenit38** [nukeviet/nukeviet#2541]
Hiện e đang dùng bản egov, có cài đa ngôn ngữ, bên tiếng Việt thì em chọn module news là hiển thị mặc định, nhưng khi share lên fb thì nó lấy thuộc tính  meta og:description không chọn cái cấu hình đã cài trong ACP, mà nó chỉ hiển thị Tin tức - Tin tức - domain
--
Em không biết miêu tả như thế nào :))
không biết là do đa ngôn ngữ hay không, vì các site trước (không dùng egov) thì share ra nó lấy đúng với cấu hình trong ACP/

**Comment by anhyeuviolet** [comment]
eGov bị mình nghĩ do theme.php xử lý khác với code nukeviet ban đầu nên mới vậy.
Đa ngôn ngữ hẳn là không tội tình gì ở vấn đề này.

**Comment by vuthao** [comment]
bạn gửi link trang web bị lỗi để mình kiểm tra nhé.

**Comment by motcaitenit38** [comment]
Xl anh e gửi muộn.
link đây anh ạ. http://ctsvhumg.com
em đã chuyển qua nuke 4.3 rồi vẫn bị :) 
Chắc không phải do egov mà có lẽ do thằng đa ngôn ngữ :)

**Comment by hoaquynhtim99** [comment]
Vấn đề này do thẻ `og:url` và `canonical` gây ra, vì các trang mạng xã hội sẽ load info từ thẻ og:url chứ không phải cái url mà người dùng gửi lên, cụ thể nếu trang share lên là http://ctsvhumg.com/, do chọn module news làm mặc định do đó module news sẽ xuất ra 

```
<meta property="og:url" content="http://ctsvhumg.com/vi/news/">
<link rel="canonical" href="http://ctsvhumg.com/vi/news/">
```

Các trang mạng xã hội sẽ load info từ url http://ctsvhumg.com/vi/news/ kết quả cho ra description của module news chứ không phải của cấu hình site

**Comment by hoaquynhtim99** [comment]
@vuthao trong file main của module news có đoạn này:

```php
    if ($viewcat == 'viewcat_none') {
        $contents = '';
        if ($home == 1) {
            $canonicalUrl = NV_MAIN_DOMAIN . nv_url_rewrite(NV_BASE_SITEURL . 'index.php?' . NV_LANG_VARIABLE . '=' . NV_LANG_DATA, true);
            $meta_property['og:url'] = $canonicalUrl;
        }
```
Như vậy thì cái $canonicalUrl trỏ về trang chủ nếu cấu hình module không hiển thị gì? Không biết chủ ý khi lập trình tại sao lại như thế

**Comment by motcaitenit38** [comment]
Cái này bây giờ tạm thời em cứ cấu hình module, chuyên mục các thứ thêm hết thẻ giới thiệu các thứ :D thấy nó vẫn lấy được nên cứ dùng tạm vậy. 
kể ra cấu hình chung trong ACP không ảnh hưởng.

**Comment by vuthao** [comment]
Hiện tại mình đã sửa lại nó ở đây.
https://github.com/vuthao/nukeviet/commit/172887381e2a19698bd79d507cf381ba53e7ddc9

@hoaquynhtim99  kiểm tra lại dùm xem như thế đã được chưa nhé.

**Comment by hoaquynhtim99** [comment]
@vuthao em thấy đã ok rồi anh
