### ISSUE TITLE
Tùy chỉnh lại tùy chọn hiển thị hình minh họa trong bài viết

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#2546]
![image](https://user-images.githubusercontent.com/13896524/32359773-e550a606-c082-11e7-9603-61fbc8f730c7.png)

Hiện tại mặc định chúng ta có 3 lựa chọn
1. Không hiển thị
2. Hiển thị bên trái phần mở đầu
3. Hiển thị dưới phần mở đầu
Như vậy là khó trong trường hợp mà không cần hình đại diện ở trong bài viết. Do vậy cần thêm 1 tùy chọn nữa là chỉ hiển thị mô tả không hiển thị hình và lấy nó làm mặc định khi đăng bài giống như các trang báo điện tử hiện nay

**Comment by vuthao** [comment]
Không có ảnh mà hiển thị mô tả là sao nhỉ, em có thể đưa ra ví cụ cụ thể hơn

**Comment by ThinhNguyenVB** [comment]
ví dụ như bài báo này trên trang vnexpress
![image](https://user-images.githubusercontent.com/13896524/32359968-3d833dc4-c084-11e7-855e-751d1d989fa7.png)
Đầu tiên là tiêu đề

Mô tả (tức là phần giới thiệu ngắn gọn trong quản trị)

Nội dung

https://suckhoe.vnexpress.net/tin-tuc/suc-khoe/hanh-trinh-cung-con-chien-dau-voi-benh-u-nao-cua-ba-me-goc-viet-3663460.html

**Comment by vuthao** [comment]
Oái thế chọn phương án 1: Không hiển thị là xong mà

**Comment by ThinhNguyenVB** [comment]
@vuthao như vậy, phương án 1 thì anh lại phải soạn sao chép nội dung của mô tả xuống và chèn thẻ để google biết tính ra mất công hơn

**Comment by vuthao** [comment]
Xem kỹ lại đi thịnh nhé.

**Comment by ThinhNguyenVB** [comment]
@vuthao thực tế đây anh, em chọn phương án 1 thì em phải nhập lại nội dung mô tả xuống dưới, nếu chọn phương 1 thì phải sửa đổi lại là phần mô tả vẫn hiển thị bình thường thay vì ẩn đi.
http://binhduong.gate.edu.vn/so-giao-duc-va-dao-tao/boi-duong-nang-cao-ky-nang-soan-giang-tren-bang-tuong-tac-thong-minh-106.html

**Comment by ThinhNguyenVB** [comment]
@vuthao  ok anh, nhưng trong bản chính lên chọn phương án 1 làm mặc định thay vì phần đó phải chọn lại
