### ISSUE TITLE
Lỗi phần đăng kí, chọn phần câu hỏi bảo mật, trường ngày tháng năm sinh bị đè lên các lựa chọn

### ISSUE THREAD

**Issue by bacuong** [nukeviet/nukeviet#2555]
1. Thông tin máy chủ
-  Phiên bản NukeViet:NukeViet 4.3
- Môi trường thử Nghiệm: Localhost
- Hệ điều hành: Window 8.1
- Trình duyệt web: Chrome
- Máy chủ web: Xampp

Ảnh minh họa lỗi: 
![loidangki](https://user-images.githubusercontent.com/32260353/32597889-a3f3ac8e-c56a-11e7-884c-4f19eb989e20.png)

**Comment by hoaquynhtim99** [comment]
Lỗi này đã được sửa, hướng dẫn ở https://nukeviet.vn/vi/forum/Huong-dan-sua-mot-so-loi-o-ban-4-3-00-t43874-p187044/#p187044
