### ISSUE TITLE
Module Quảng cáo bản nv4.2.01 lỗi

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#2562]
Không sửa được quảng cáo; không thêm được quảng cáo. Mong được pix lỗi. Thank!

**Comment by quangcuong** [comment]
Trên bản 4.3 cũng bị, chưa được fix

**Comment by vuthao** [comment]
Mình kiểm tra lại Cả bản 4.2 và 4.3 mặc định không bị lỗi này các bạn ạ.

Cách fix đơn giản nhất: Xem  bảng của bản ứng với site của các bạn cài mới và so sánh bảng dữ liệu để sửa lại. Hoăc xóa các bảng nv4_bannerxxxxxxxxxxx của site đi thay bằng CSDL của bản tương ứng
