### ISSUE TITLE
Bỏ bắt buộc nhập mô tả nhóm thành viên

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2564]
Thông tin này không quan trọng nên mình nghĩ bỏ bắt buộc chổ này đi

![screenshot from 2017-11-15 14-04-54](https://user-images.githubusercontent.com/6407361/32823014-fa86384e-ca0d-11e7-91d1-15d7865ba043.png)

**Comment by hoaquynhtim99** [comment]
Đã thêm https://github.com/hoaquynhtim99/nukeviet/commit/615e13d1e842822ab54877d66d9b2bfb478d4153
