### ISSUE TITLE
Lỗi Hiển Thị Menu của block bootstrap

### ISSUE THREAD

**Issue by huuducinfo** [nukeviet/nukeviet#2565]
Mình đang gặp lỗi menu cấp thứ 2 nó chồng lên menu thứ nhất. có cách nào di chuyển nó hiên thị bên tay phải khi mình bấm vào không ạ. lỗi như hình phía dưới ạ

![menu](https://user-images.githubusercontent.com/33726919/32901135-b823f558-cb21-11e7-964e-cf26fe55c010.jpg)

**Comment by hoaquynhtim99** [comment]
Giao diện này không phải giao diện mặc định bạn, bạn thảo luận vấn đề này trên diễn đàn nhé
