### ISSUE TITLE
[Structured Data] Review-aggregate có vấn đề

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2566]
Đang lỗi nên không hiển thị dấu sao trên kết quả tìm kiếm google

![screenshot from 2017-11-17 07-39-00](https://user-images.githubusercontent.com/6407361/32923486-67e70c76-cb6a-11e7-95a3-7061a9f376e1.png)

**Comment by hoaquynhtim99** [comment]
Phần này đang có vấn đề với toàn bộ chức năng xem chi tiết bài viết. Có tác động nhiều đến giao diện nên để làm ở NukeViet 4.4.

**Comment by hoaquynhtim99** [comment]
Đã sửa ở https://github.com/nukeviet/nukeviet/commit/95c0119a44f2093ddc11527a7422b973c2b5b5be
