### ISSUE TITLE
Lỗi giao diện module news - block headline

### ISSUE THREAD

**Issue by thuvp1995** [nukeviet/nukeviet#2571]
Nukeviet 4.3 theme mặc định mình nếu dùng module block headline, khi đang đăng nhập ở tài khoản quản trị để kéo thà block headline thì "tin tiêu điểm và tin mới nhất" hiện thị đúng css.
xem ảnh đính kèm https://imgur.com/SAgKENW
Nhưng khi thoát khỏi tài khoản quản trị thì css của tin tiêu điểm và tin mới nhất bị lỗi đè lên nhau
xem ảnh đính kèm https://imgur.com/wm3LvkN

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/8b85c6fd767a95a8cefa2a6516b4c0f175b50bad
