### ISSUE TITLE
Lỗi hiển thị qrcode trên giao diện mobile

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2577]
> Phiên bản NukeViet | 4.3.00
> Phiên bản PHP | 5.6.8
> Giao thức giữa máy chủ và PHP | Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
> Hệ điều hành máy chủ | LINUX
> Phiên bản Database | mysql 5.6.24
> 

Trên giao diện mobile click vào icon qrcode không hiện ảnh qrcode

![screenshot from 2017-12-14 15-56-05](https://user-images.githubusercontent.com/6407361/33984501-6a7b124e-e0ea-11e7-8bf4-78416ee2b914.png)

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/ecdafe60b7dad694d8383450011a51b85c2de6f5
