### ISSUE TITLE
Nukeviet 4.3 - Lỗi vận hành với PHP 5.5

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2585]
PHP 5.5.38/IIS10/Windows 10.
Thu được lỗi như sau:

> PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in C:\www\429\vendor\illuminate\support\helpers.php on line 554

**Comment by hoaquynhtim99** [comment]
`vendor\illuminate` NukeViet không có cài thư viện mặc định đó nhé, bạn cài thư viện ngoài cần kiểm tra tính tương thích
