### ISSUE TITLE
[SMTP] Vấn đề gửi mail với Gmail qua PHPMailer

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2587]
NukeViet 4.3
Thử nghiệm với Module contact, thông qua chức năng Gửi mail.

> /admin/index.php?language=vi&nv=contact&op=send

Thu được lỗi sau:

> Lỗi: Hệ thống không gửi được email, Vui lòng liên hệ với Quản trị site để cấu hình lại chức năng gửi mail: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

Tiến hành "đào" vào file send.php của module.
Tìm đến dòng 38:
```
        $mail = new NukeViet\Core\Sendmail($global_config, NV_LANG_INTERFACE);
        $mail->Subject($post['title']);

```
Thêm xuống bên dưới:
```
        $mail->SMTPOptions = array(
            'ssl' => array(
                'verify_peer' => false,
                'verify_peer_name' => false,
                'allow_self_signed' => true
            )
        );

```

Thu được thông báo sau:

> Đã gửi thành công

Hòm mail của người nhận cũng đồng thời nhận được Email.
Đây là cách sửa thủ công và phải sửa vào từng module gọi Class này,
Liệu có cách nào sửa để áp dụng cho toàn hệ thống không nhỉ ?

**Comment by anhyeuviolet** [comment]
Đường dẫn tham chiếu:
https://stackoverflow.com/a/47646027/4299057

**Comment by vuthao** [comment]
Cái này có sẵn trong NukeViet 4.3 rồi mà nhỉ các bạn.
https://screenshots.firefox.com/FkASkqk9mv65jjLN/nukeviet.vn
hai dòng:
Ssl verify peer
Ssl verify name peer

**Comment by anhyeuviolet** [comment]
Ghi nhận.
Cảm ơn anh @vuthao ! 
![ssl](https://user-images.githubusercontent.com/6290970/34473132-6ab7c458-efa1-11e7-99fa-a49ff971dfa0.PNG)

**Comment by chauphira** [comment]
> NukeViet 4.3
> Thử nghiệm với Module contact, thông qua chức năng Gửi mail.
> 
> > /admin/index.php?language=vi&nv=contact&op=send
> 
> Thu được lỗi sau:
> 
> > Lỗi: Hệ thống không gửi được email, Vui lòng liên hệ với Quản trị site để cấu hình lại chức năng gửi mail: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
> 
> Tiến hành "đào" vào file send.php của module.
> Tìm đến dòng 38:
> 
> ```
>         $mail = new NukeViet\Core\Sendmail($global_config, NV_LANG_INTERFACE);
>         $mail->Subject($post['title']);
> ```
> 
> Thêm xuống bên dưới:
> 
> ```
>         $mail->SMTPOptions = array(
>             'ssl' => array(
>                 'verify_peer' => false,
>                 'verify_peer_name' => false,
>                 'allow_self_signed' => true
>             )
>         );
> ```
> 
> Thu được thông báo sau:
> 
> > Đã gửi thành công
> 
> Hòm mail của người nhận cũng đồng thời nhận được Email.
> Đây là cách sửa thủ công và phải sửa vào từng module gọi Class này,
> Liệu có cách nào sửa để áp dụng cho toàn hệ thống không nhỉ ?

tìm sile sen.php ở đâu vậy
