### ISSUE TITLE
Kết nối Mysql từ xa

### ISSUE THREAD

**Issue by nhdanh** [nukeviet/nukeviet#2588]
Em có cấu hình 1 server MySQL để dùng db chung cho source nukeviet để phát triển. Mình dùng HeidiSQL để kết nối. Kết nối thành công. Nhưng ở nukeviet thì không thể kết nối được từ xa. DB đó để localhost thì được nhưng kết nối qua bên server của em thì không được. Làm sao để cấu hình ? Em cám ơn

**Comment by vuthao** [comment]
@nhdanh đây không phải là lỗi của NukeViet nhé bạn.

Cái này là do cách cấu hình của bạn chưa đúng, bạn thảo luận vấn đề này trên diễn đàn hoặc group nhé.
