### ISSUE TITLE
đóng chỉ số /statistics/ trong robots.txt

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/nukeviet#2591]
Trong tệp robots.txt, bạn phải vô hiệu hóa việc lập chỉ mục cho tất cả các robot của đường dẫn /statistics/ để ngừng lập chỉ mục các liên kết trên trang / thống kê /statistics/allreferers/

Hiển thị danh sách /statistics/allreferers/chỉ trong bảng quản trị, cũng để ngăn việc lập chỉ mục các liên kết bên ngoài nằm trên trang này trong máy chủ cột
  
 Bạn cần thêm vương miện (plugin) để tự động loại bỏ giới thiệu tại thời gian đã chỉ định

**Comment by vuthao** [comment]
@NukeVlad bạn có thể cấu hình module statistics chỉ cho quản trị xem module này. 

Chúng tôi sẽ cấu hình thêm để robots không thu thập module này trong phiên bản tới.

**Comment by vuthao** [comment]
@NukeVlad bạn có thể tự cấu hình tại khu vực:
http://mydomain.com /admin/index.php?language=vi&nv=seotools&op=robots

![a0b745d2-eb3b-439c-8d36-53e23a0e6685](https://user-images.githubusercontent.com/2491500/35605396-2aea839c-067b-11e8-9452-28db63c033fe.png)

Ở phiên bản 4.3.01 khi cài mới mình sẽ cài đặt mặc định thông số này.
