### ISSUE TITLE
Module banners

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/nukeviet#2596]
Module banners. Chức năng gỡ bỏ biểu ngữ quảng cáo không hoạt động. Khi bạn nhấp vào liên kết, liên kết sẽ giống như: /admin/index.php?language=ru&nv=banners&op=banners_list#

**Comment by hoaquynhtim99** [comment]
Lỗi này đã được sửa trước đó, đã có hướng dẫn ở https://nukeviet.vn/vi/forum/Huong-dan-sua-mot-so-loi-o-ban-4-3-00-t43874/
