### ISSUE TITLE
Giới hạn phiên bản PHP

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2597]
Do NukeViet dùng PHP và chỉ đươc test trên các bản đã phát hành. Các bản mới hơn có thể có lỗi không tương thích.

Do đó cần sửa lại để khi cài đặt chỉ cho phép chạy trên các bản PHP nhất định.

Ví dụ: 
1. NukeViet 4.0 - 4.2 chỉ cho chạy trên PHP: 5.5, 5.6, 7.0
2. NukeViet 4.3 chỉ cho chạy trên PHP: 5.6, 7.0, 7.1, 7.2

**Comment by hoaquynhtim99** [comment]
Đã thêm https://github.com/hoaquynhtim99/nukeviet/commit/1738bee7c36d87f1c02cb3844f5b62d71574dad0
