### ISSUE TITLE
Cải tiến cấu hình giao diện

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2600]
Hiện tại NukeViet chỉ cho dùng 1 giao diện duy nhất cho site.

Khi xây dựng giao diện mới cần đưa lên site để cấu hình, thì lúc này muốn cấu hình sẽ phải chuyển ngay sang giao diện mới để dùng, dẫn đến việc chuẩn bị và kiểm tra không được tốt sẽ ảnh hướng đến site.

Để xuất cho quản trị có thể chọn giao diện để cấu hình trước khi kích hoạt giao diện chính thức.

**Comment by thehung** [comment]
Trước đây, NukeViet 2.x còn cho người sử dụng chọn giao diện. Nếu dự định làm tính năng này thì cân nhắc luôn việc phân quyền giao diện hay không!

**Comment by vuthao** [comment]
Tính năng cho người sử dụng chọn giao diện: và việc xây dựng 1 giao diện cho web rất tốn công, và site không có bản sắc riêng, mối người dùng 1 kiểu nên  thực tế là không có người dùng. Do đó tính năng này chỉ làm để cho người quản trị cấu hình.

**Comment by thehung** [comment]
Hữu dụng trong trường hợp cho người dùng preview để lấy ý kiến người dùng
khi đổi giao diện!

**Comment by vuthao** [comment]
nếu thế thì chốt lại như sau nhé:
1) Với mỗi giao diện chưa kích hoạt sẽ có cấu hình cho phép chạy thử giao diện đó. và đưa link này để quản trị đưa ra ngoài site để khảo sát.
2) Dùng sesion lưu lại biến này để lưu lại.
3) Khi lập trìn chú ý kiểm tra chỉ các giao diện được cho phép mới cho chạy thử. 
4) Khi cấu hình chạy thử giao diện sẽ áp dụng cho tất cả các module (Bởi giao diện đang kích hoạt chính thức có thể mối module dùng 1 giao diện không kiểm tra được hết).

**Comment by vuthao** [comment]
Hiện tại tính năng này đã làm xong sẽ cập nhật cho NukeViet 4.3.02
