### ISSUE TITLE
Lỗi class request đối với các tag bị cấm

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2601]
Hiện tại khi gọi class request của NukeViet ra thì dữ liệu submit $_GET, $_POST bị sửa đổi, cụ thể là lọc bỏ hết các tag không nằm trong `NV_ALLOWED_HTML_TAGS`

Như vậy người dùng không thể nào gửi dữ liệu lên ví dụ 

```
VINADES.,JSC <email@gmail.vn>
```

Thậm chí là:

```
Ví dụ mặt cười 1 cái <' -_- '>
```

Theo ý kiến của mình thì có thể sửa class request lại thay vì lọc bỏ các tag bị cấm thì sẽ chuyển các tag bị cấm sang mã htmlspecialchars để giữ lại chúng

**Comment by hoaquynhtim99** [comment]
Liệu có thể nào không làm thay đổi trực tiếp vào `$_GET, $_POST` chỉ áp dụng cho các method của class thôi?
Người dùng tự lường trước nguy hiểm khi dùng trực tiếp các biến `$_GET, $_POST`

**Comment by anhtunguyen** [comment]
https://github.com/nukeviet/nukeviet/pull/2933
Thay đổi này cho phép các lập trình viên tự quyết định có áp dụng lọc an ninh cho các biến $_GET, $_POST, $_COOKIE... nào đó hay không. Mặc định là có ($filter = true ở get_title, get_editor...).
