### ISSUE TITLE
Cần phải chuẩn bị hệ thống cho các yêu cầu mới

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/nukeviet#2603]
Cần phải chuẩn bị hệ thống cho các yêu cầu mới
http://bigdata-madesimple.com/4-critical-big-data-developments-to-prepare-for-in-2018/

**Comment by vuthao** [comment]
@NukeVlad mình có xem bài viết bạn gửi.

Đây là xu hướng công nghệ chung chung. Để dùng cho mỗi site lớn cần có bài toàn cụ thể để thiết kế và cầu hình.
Nếu được bạn Nêu cụ thể các phần cần cải tiến nhé.
