### ISSUE TITLE
Lỗi biến $user_info['in_groups']

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2604]
Khi **thêm tài khoản**, chọn tài khoản thuộc nhiều nhóm thành viên, thì biến `$user_info['in_groups']` chỉ ghi lại được ID của nhóm thành viên chính.

Chỉ khi **Sửa tài khoản** và lưu lại, thì biến này mới được cập nhật thêm ID các nhóm khác.

> Phiên bản NukeViet | 4.3.00
Phiên bản PHP | 5.6.8
Giao thức giữa máy chủ và PHP | Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3, apache2handler
Hệ điều hành máy chủ | LINUX
Phiên bản Database | mysql 5.6.24

**Comment by hoaquynhtim99** [comment]
@mynukeviet  check lại ở bản mới nhất thử, mình check không thấy lỗi này nhỉ

**Comment by vuthao** [comment]
Mình kiểm tra cũng không thấy có lỗi này nữa, nên nếú @mynukeviet vẫn thấy còn lỗi thì thông báo lại nhé.

**Comment by mynukeviet** [comment]
OK anh xác nhận đã hết lỗi
