### ISSUE TITLE
Lỗi url khi hết thời gian đăng nhập

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2610]
Khi thành viên, admin đăng nhập ngoài site mà không thao tác thì sau 30 phút bị đẩy ra và trình duyệt bị lỗi URL https://domain.com/post-alias/undefined

**Comment by motcaitenit38** [comment]
Bản 4.3.01 cũng dính lỗi này.
tại do trước k để ý, nay đẻ site chạy thế nó vẫn về 404
url thêm đoạn undefined phía sau.

**Comment by vuthao** [comment]
Sao mình thử không bị nhỉ, bởi chỗ đó dùng window.location.href = location.reload()

**Comment by hoaquynhtim99** [comment]
Em đã sửa tại https://github.com/hoaquynhtim99/nukeviet/commit/5f18d03a444469da3b7f97c1cdb98d9f37640883, lỗi do dùng window.location.href chỉ cần dùng  location.reload()
