### ISSUE TITLE
Vấn đề về đa ngôn ngữ khu vực admin

### ISSUE THREAD

**Issue by motcaitenit38** [nukeviet/nukeviet#2613]
Hiện tại chức năng đa ngôn ngữ khu vực admin đang khá là rối, nếu chọn ngôn ngữ lúc đăng nhập admin thì mọi thứ đều ok hết. Nhưng khi đã đăng nhập xong, chọn thay đổi ngôn ngữ trên header thì nó CỰC KỲ là rối, nửa ngôn ngữ này, nửa ngôn ngữ kia. 
Có thể chỉ cho chọn ngôn ngữ khi đăng nhập và bỏ đi khu vực chọn ngôn ngữ trên header trong admin
hoặc có giải pháp để chuyển đổi ngôn ngữ hợp lý hơn.
Mong đội code có giải pháp hợp lý và thay đổi ở phiên bản mới.

**Comment by thehung** [comment]
Trước mình có đề xuất giải pháp cho chọn lại ngôn ngữ giao diện nhưng hình như không được vì việc ghi lại session khiến admin bị out ra.

Mình thấy việc ngôn ngữ giao diện 1 đằng, ngôn ngữ data một nẻo vẫn hay hơn là đổi ngôn ngữ cơ sở dữ liệu thì đổi luôn ngôn ngữ giao diện. Bởi vì thói quen thao tác trên phần mềm thì bất chấp việc bạn đang thao tác với dữ liệu nào cũng không khó khăn. Ngược lại, chỉ cần đổi ngôn ngữ giao diện là nhiều khi chết mệt với các menu và thuật ngữ không quen.

Cho nên nếu không cho đổi được ngôn ngữ giao diện trong quá trình sử dụng thì thà cứ để như hiện tại còn hơn là đổi ngôn ngữ thao tác vào csdl là ngôn ngữ giao diện bị đổi theo!

**Comment by motcaitenit38** [comment]
Đổi ngôn ngữ giao diện thì nó kiểu như google dịch, đôi lúc nó khó hơn là đọc ngôn ngữ gốc 💃 
Em thấy như bây giờ đổi ngôn ngữ sql nó ổn rồi,tách bạch, rõ ràng nhưng không hiểu sao nó không chuyển hoàn toàn khi thay đổi trong admin

**Comment by thehung** [comment]
Ngôn ngữ giao diện ko ổn thì là do gói ngôn ngữ dịch. Không liên quan đến vấn đề lập trình.

Còn lý do không chuyển ngôn ngữ giao diện khi chuyển ngôn ngữ Csdl thì bạn đọc kỹ comment trước của mình.

**Comment by vuthao** [comment]
@motcaitenit38 @thehung 
hay là trình bày như thế này nhỉ: https://screenshots.firefox.com/z9E7muE1TiAaEuRK/989me.vn

**Comment by thehung** [comment]
Có vẻ ổn đấy!
Nhưng còn vấn đề nữa cần tính tới là xung đột giữa ngôn ngữ giao diện phần quản trị với ngôn ngữ giao diện ngoài site. Ví dụ trường hợp ngôn ngữ giao diện là tiếng Việt, ngôn ngữ Cơ sở dữ liệu là tiếng Anh, Admin click nút Home để ra ngoài site thì sẽ thấy ngoài site là tiếng Anh hết, nhưng trở lại trong site có như cũ không hay phải chọn lại?

**Comment by motcaitenit38** [comment]
Như anh @thehung  nói đấy, sợ nó xung với giao diện ngoài site, chứ nếu phân biệt như anh @vuthao  nói thì trong admin thế là rõ ràng rồi.

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/f131c79d9548157a8c7738876c9b4afdface2373
