### ISSUE TITLE
lỗi trong thuộc tính menu

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/nukeviet#2616]
Tập tin \themes\default\modules\menu\global.bootstrap.tpl
Hàng 22:
            <li {TOP_MENU.current} rol="presentation"><a class="dropdown-toggle" {TOP_MENU.dropdown_data_toggle} href="{TOP_MENU.link}" role="button" aria-expanded="false" title="{TOP_MENU.note}"{TOP_MENU.target}>  <img src="{TOP_MENU.icon}" />&nbsp;  {TOP_MENU.title_trim} <strong class="caret">&nbsp;</strong>

Lỗi trong thuộc tính rol="presentation" Tôi đoán tôi cần phải thay thế bằng role="presentation"
hoặc xóa.

Error: Attribute rol not allowed on element li at this point.

From line 95, column 25; to line 95, column 63

          <li  class="active" rol="presentation"><a cla

Attributes for element li:
Global attributes
If the element is not a child of an ul: value

http://w3c.github.io/html/single-page.html#the-li-element

**Comment by vuthao** [comment]
Thank @NukeVlad
