### ISSUE TITLE
Lỗi: Trong khu vực quản trị module user không thêm được quản trị khi cấu hình username chỉ gồm chữ số

### ISSUE THREAD

**Issue by thuvp1995** [nukeviet/nukeviet#2619]
Chức năng thêm quản trị tại module user đang hoạt động không đúng trong trường hợp cấu hình username chỉ dùng chữ số. Chức năng chọn tài khoản từ list thành viên trả về kết quả là tên đăng nhập của tài khoản đó, trong khi đó tại trường này yêu cầu nhập userid mới đúng dẫn đến khi submit thì báo lỗi:Bạn chưa chỉ định thành viên chọn làm quản trị

**Comment by motcaitenit38** [comment]
Nhớ k nhầm thì bạn nhấn vào chữ chọn xong chọn tài khoản ok thì mới được, chứ gõ thẳng k được ✌️

**Comment by thuvp1995** [comment]
@motcaitenit38 mình nhấn chữ chọn đó bạn, sau khi chọn tài khoản mong muốn thì nó lấy username điền vào form

**Comment by vuthao** [comment]
Để mình xem và sửa luôn lỗi mày.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/13f79a530980ab9eb7feaff28a6a5adf4942dd59
