### ISSUE TITLE
Lỗi og:image ở module news lấy sai ảnh

### ISSUE THREAD

**Issue by motcaitenit38** [nukeviet/nukeviet#2620]
Hiện tại thuộc tính og:image đang lấy sai ảnh nếu như cấu hình "Trình bày hình trong bài viết " là bên trái phần mở đầu thì thuộc tính og:image lấy không đúng ảnh (e debug trên tool facebook) thì nó lấy ảnh trong asset 
Sau khi được anh Ứng dụng Nukeviet bảo thử cấu hình lại là bên dưới phần mở đầu thì nó nhận đúng thuộc tính og:image là ảnh đại diện được upload lên trong thư mục upload.
đây là link bài viết em hỏi trên groups 🗡 https://www.facebook.com/groups/nukeviet/permalink/1952463108129113
==
Không biết đây là tính năng hay lỗi, nhưng nó gây khó khăn khi share bài lên facebook 💃

**Comment by vuthao** [comment]
Bạn sử dụng phiên bản NukeViet nào nhỉ @motcaitenit38

**Comment by motcaitenit38** [comment]
bản mới nhất 4.3.01 anh ạ @vuthao

**Comment by vuthao** [comment]
@motcaitenit38 bạn sửa lại như sau xem nhé:
https://github.com/vuthao/nukeviet/commit/8079a9a31758ed894ec273e1c315f8ae5add1b92

**Comment by motcaitenit38** [comment]
@vuthao  hiện tại thì e để cấu hình mặc định là ảnh hiển thị phía dưới thì nó lấy chuẩn 🗡  với bug này chắc phiên bản sau sẽ được fix chứ a 👍

**Comment by vuthao** [comment]
Mình đã fix rồi đó, nếu bạn còn ảnh ử bên trái thì sửa code theo link trên.

**Comment by motcaitenit38** [comment]
Vâng anh 🗡  cảm ơn anh
