### ISSUE TITLE
URL khi trang web đang làm việc bằng một ngôn ngữ

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/nukeviet#2623]
Tôi nghĩ rằng trong trường hợp của một trang web chỉ làm việc trong một ngôn ngữ, bạn cần phải cắt bỏ các biểu thức từ URL với một chuyển hướng language=nv&
Tôi yêu cầu thảo luận vấn đề này.

**Comment by thehung** [comment]
Bạn có thể tắt biến ngôn ngữ trên URL khi chỉ có 1 ngôn ngữ mà!

**Comment by NukeVlad** [comment]
Có, có thể, nó sẽ được chính xác để lại như là
