### ISSUE TITLE
Phát triển tính năng chống flood

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2627]
Hiện tại tính năng chống flooddd đang chặn mọi IP.

Nên có cấu hình thêm các IP không bị chặn bởi có những IP mà quản trị thường xuyên truy cập hay lập trình dẫn tới bị khóa lại mà không thể mở ra được.

Khi cài đặt NukeViet nếu IP = 127.0.0.1 hay các IP ở dạng local thì add luôn IP này để khi lập trình không bị chặn.

**Comment by hoaquynhtim99** [comment]
Đã thêm https://github.com/nukeviet/nukeviet/pull/2628

**Comment by hoaquynhtim99** [comment]
Em có ghi nhận thay đổi CSDL ở https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.3#ch%E1%BB%A9c-n%C4%83ng-c%E1%BA%A5u-h%C3%ACnh-ip-ngo%E1%BA%A1i-tr%E1%BB%AB-ki%E1%BB%83m-tra-flood
