### ISSUE TITLE
Cập nhật CSDL xác định IP các quốc gia

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2629]
Hiện tại CSDL này trong NukeViet đã cũ, lâu không được cập nhật.

Cần viết 1 tool (Lưu trữ mã nguồn tool này tại: https://github.com/nukeviet/nukeviet-tools) cập nhật CSDL từ https://dev.maxmind.com/geoip/geoip2/geolite2/ sau đó ghi lại CSDL về IP đặt tại thư mục: /data/ip và /data/ip6

**Comment by hoaquynhtim99** [comment]
Em đã xuất dữ liệu IP ở đây, anh xem ok chưa nhé https://github.com/nukeviet/nukeviet-tools/tree/master/release

**Comment by hoaquynhtim99** [comment]
@vuthao em đã xuất lại anh coi nhé https://github.com/nukeviet/nukeviet-tools/tree/master/release
