### ISSUE TITLE
tự động chuyển sang tin tức kế tiếp khi cuộn xuống

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/nukeviet#2632]
Vui lòng xem xét tạo một cơ chế để tự động thay đổi id của bài đăng khi di chuyển bởi người dùng cho đến khi nhận xét cuối cùng và hiển thị thông suốt mà không có tiêu đề của bài đăng tiếp theo. Số lượng bài đăng được hiển thị được đặt trong cài đặt mô-đun, sau khi hiển thị bài đăng mới nhất, xuất xuống tiêu đề.

**Comment by hoaquynhtim99** [comment]
Các xử lý này không phổ biến, module news sẽ không hỗ trợ
