### ISSUE TITLE
Lỗi SSL

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/nukeviet#2633]
Khi cài đặt trên localhost XAMPP bị tự động bật SSL vào CSDL hay config đều không thấy.

- Phiên bản NukeViet: 4.3.01
- Môi trường thử Nghiệm: Localhost
- Trình duyệt web: Tất cả các trình duyệt đều bị
- Máy chủ web: XAMPP

![capture](https://user-images.githubusercontent.com/8292355/37695666-8a74affa-2d03-11e8-949e-1068b83c029f.JPG)

![capture](https://user-images.githubusercontent.com/8292355/37695597-1402cbf4-2d03-11e8-9bcf-b93f1502bdde.JPG)

**Comment by vuthao** [comment]
cái này liên quan đến localhost của bạn, bạn cần tự cấu hình lại nhé, nó ko phải lỗi của NukeViet.
