### ISSUE TITLE
Thêm sub title cho block

### ISSUE THREAD

**Issue by aptx1987** [nukeviet/nukeviet#2634]

**Comment by aptx1987** [comment]
1 số website thường dùng tới 2 tiêu đề, 1 title 1 là mô tả cho block (đây là nukeviet). Có thể thêm 2-3 trường nữa dc ko ạ
![capture](https://user-images.githubusercontent.com/13611322/37748673-50d0c7e8-2db7-11e8-9657-a46371eb95f7.PNG)

**Comment by mynukeviet** [comment]
Mình cũng nghĩ không cần thiết nhé
