### ISSUE TITLE
Chống IFRAME và không Chống IFRAME

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#2635]
Bật hay Tắc phần **Chống IFRAME** trong quản trị. Không thấy giá trị thay đổi khi chèn iframe lên website (giao diện web người dùng công khai) vẫn thấy bình thường.

Hỏi: Khi một trang **web A** khác muống chèn 1 trang **web B** chạy code nukeviet theo dạng iframe lên thì chỉ thấy là 1 trang trắng vậy làm sao để có thể chèn vào mà vẫn thấy được nội dung của trang web B? (Bảng 3.4.02 phần này chèn được bình thường).

Thử nghiệm trên Phiên bản NukeViet: 4.3.00

**Comment by hoaquynhtim99** [comment]
Đã sửa https://github.com/hoaquynhtim99/nukeviet/commit/6846b2f99bab6341df7c0fe8d7da0a45962f5061
