### ISSUE TITLE
Đăng nhập 2 trình duyệt cùng tài khoản

### ISSUE THREAD

**Issue by nhdanh** [nukeviet/nukeviet#2637]
Hiện tại mình đang cấu hình website có 1 chuyên mục. dùng tài khoản chung cho cả phòng. Nhưng chỉ được 1 máy đăng nhập. Máy khác sẽ bị out. Mình muốn hỏi làm sao để có thể đăng nhập 1 tài khoản trên nhiều máy được ?

**Comment by vuthao** [comment]
Hiện tại NukeViet 4 chưa cho phép làm điều này.
bạn cần tạo nhiều tài khoản, mỗi người dùng 1 tài khoản.
