### ISSUE TITLE
Thêm cấu hình cho cronjobs

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2639]
Cron NukeViet đang phụ thuộc vào sự truy cập site, điều này khiến việc chạy cron trong một số trường hợp trở nên thụ động. Một số tiến trình được lập trình xử lý mất nhiều thời gian, điều này làm ảnh hưởng đến tốc độ truy cập website khj cron đang chạy.

Đề xuất thêm 1 cấu hình, là sử dụng cùng hệ thống như hiện tại, và 1 cấu hình chạy cron dựa vào máy chủ (đa số hệ điều hành máy chủ nào cũng có cronjobs cả)

Có thể thực thi url này là xong `domain/index.php?second=cronjobs`

**Comment by vuthao** [comment]
@mynukeviet em xem các cái cấu hình trên các hệ điều hành như thế nào vào đây nhé:
Anh đã tạo nội dung 1 phần ở: https://wiki.nukeviet.vn/nukeviet4:admin:settings:cronjobs

**Comment by hoaquynhtim99** [comment]
Trùng https://github.com/nukeviet/nukeviet/issues/2490 và cũng được phát triển
