### ISSUE TITLE
Xóa allreferers

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/nukeviet#2645]
Hãy thêm một chức năng trong phần webtools/clearsystem để xóa tất cả các trình phục vụ allreferers từ phần Thống kê

**Comment by hoaquynhtim99** [comment]
@vuthao phần này sẽ đưa vào quản trị của module thống kê thay vì để ở phần dọn dẹp hệ thống nhé anh

**Comment by NukeVlad** [comment]
@vuthao  Nó sẽ được tốt đẹp để thêm vào cài settings/plugin plugin allreferers.php để gỡ bỏ tự động thông qua các thiết settings/cronjobs

**Comment by hoaquynhtim99** [comment]
@vuthao em đã viết thêm chức năng xóa thống kê tại đây https://github.com/hoaquynhtim99/nukeviet/commit/1ee19619a8f6fa8877f2d75b928efdf23914ca46 phần này cho phép xóa tất cả các loại thống kê của NukeViet - Chỉ admin tối cao được dùng

**Comment by NukeVlad** [comment]
Cảm ơn bạn, tính năng rất hữu ích!
