### ISSUE TITLE
Module contact: sửa tính năng Gửi bản sao thư này cho tôi

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2646]
Tính năng Gửi bản sao thư này cho tôi rất hay.

Tuy nhiên nếu không phải là đúng người đó sẽ ra sao. có thể sẽ bị lợi dụng phát tán spam.

Do đó cần thêm 1 cấu hình của module:  
1) Cấu hình:  có sử dụng tính năng Gửi bản sao cho người gửi nếu là thành viên đã xác nhận email.
2) Module Users: thêm 1 trường ghi nhận thời gian người dùng đã Email Verification, để sau này làm căn cứ những tài khoản sau bao lâu phải verified lại email một lần.

**Comment by vuthao** [comment]
@hoaquynhtim99 Theo anh nên sửa cái này vào bản 4.3

Để mặc định là tắt tính năng: "Gửi bản sao", còn nếu site nào sửa lại giao diện thì mới bật lên. Đây là lỗi logic nghiêm trọng nên cần fix lại.

**Comment by hoaquynhtim99** [comment]
Em đã sửa tại đây https://github.com/hoaquynhtim99/nukeviet/commit/07d70f3d31182c8101bcfb9ed7d28e550a7f6db2
