### ISSUE TITLE
Module banners, hệ thống với SWF?

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2650]
Nên hay không nên việc loại bỏ code xử lý swf ra khỏi hệ thống (logo site) và module banners

Mình bỏ 1 phiếu nên loại.

**Comment by vuthao** [comment]
+1 cho vịec loại bỏ.

**Comment by hoaquynhtim99** [comment]
https://github.com/nukeviet/nukeviet/commit/9539c8e603e3769de903983428d75ced284fdedd

**Comment by anhtunguyen** [comment]
OK. Vì nó quá lạc hậu rồi
