### ISSUE TITLE
Sai chính tả tại dữ liệu mẫu module news

### ISSUE THREAD

**Issue by thuvp1995** [nukeviet/nukeviet#2657]
trong list bài viết mẫu của nukeviet: "Tuyển dụng lập trình viên front-end (HTML/CSS/JS) phát triển NukeViet" có phần giới thiệu ngắn gọn sai chính tả: "Bạn đam mê nguồn mở? Bạn đang cần tìm một công việc phù hợp với thế mạnh của bạn về front-end (HTML/CSS/JS)?. Hãy gia nhập VINADES.,JSC để xây dựng mã nguồn mở hàng đầu cho Việt Nam" -> Bị thừa dấu chấm câu sau dấu hỏi thứ hai

**Comment by vuthao** [comment]
Fixed: https://github.com/nukeviet/nukeviet/commit/2e0dfbc30b72f02caa91f0fed3eccbf6392335f2
