### ISSUE TITLE
Lỗi hiển thị số liệu tại chức năng thống kê lượt truy cập

### ISSUE THREAD

**Issue by thuvp1995** [nukeviet/nukeviet#2658]
Khi mới cài site lên: ngày đầu tiên thì tại biểu đồ tròn thống kê theo ngày trong tuần không hiển thị đúng lượt truy cập
![capture](https://user-images.githubusercontent.com/15797813/39355723-29e545bc-4a38-11e8-816e-e1d5b8f66ea8.PNG)

**Comment by hoaquynhtim99** [comment]
Phần này không phải lỗi mà do dữ liệu ít quá Chart.js không xác định được

**Comment by vuthao** [comment]
@hoaquynhtim99 Nếu Chart không hiện thị được thì cần tìm giải pháp khác, chứ biểu đồ không đúng thì không nên dùng.

**Comment by hoaquynhtim99** [comment]
Cái này cũng không cần thiết lắm, hoặc có thể bỏ đi các label = 0.
Nếu có xử lý cần chuyển sang NukeViet 4.4

**Comment by hoaquynhtim99** [comment]
Fixed: Hiện tại chart.js mới nhất sẽ ẩn biểu đồ đi nếu toàn bộ dữ liệu = 0
