### ISSUE TITLE
Lỗi không Ping không khi đăng bài ở NukeViet 4.3.02

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#2661]
Sau khi viết bài, hệ thống tự động Ping bài viết, nhưng báo "Lỗi không xác định", mình đang sử dụng Nukeviet 4.3.02, mong đội code xem lỗi này. và lỗi Sitemap Ping sau khi nấn nút Gửi đi
![02](https://user-images.githubusercontent.com/11238423/39533207-b8aedc80-4e58-11e8-9694-4ff3090bab17.png)
![011](https://user-images.githubusercontent.com/11238423/39533209-b8e88db8-4e58-11e8-9287-a37fb4c2ccfa.png)

**Comment by hoaquynhtim99** [comment]
Ping của NukeViet mặc định là xml-rpc ping theo quy chuẩn chung cho tất cả các máy chủ tìm kiếm, không phải dạng ping sitemap thông thường.

Hiện tại ping list hầu như đã dừng hoạt động gần đây, vấn đề này nằm ngoài việc kiểm soát lỗi thông thường, cần theo dõi thêm trong thời gian tới

**Comment by hoaquynhtim99** [comment]
Hiện tại các dịch vụ Ping này đã chính thức không còn hoạt động, NukeViet đã gỡ bỏ tại bản 4.3.05 https://github.com/hoaquynhtim99/nukeviet/commit/a68c7981c2dd85c7805622a97a681a6baca68699

**Comment by vuthao** [comment]
@hoaquynhtim99 Nếu phần nào bỏ đi nên ghi chú lại ở tài liệu trên wiki, ví dụ: https://wiki.nukeviet.vn/nukeviet4:admin:seotools:sitemapping

**Comment by hoaquynhtim99** [comment]
@vuthao cái này chỉ gỡ những máy chủ không còn ping được thôi anh, chứ cái simapping và RPC ping của vài máy chủ vẫn còn nên tính năng sẽ vẫn còn nguyên
