### ISSUE TITLE
Sửa lại trang đăng nhập.

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2663]
Khi đăng nhập site có nv_redirect thì trang đăng nhập luôn có logo site.

Dẫn đến site khi này có logo
![4d44cd46-1c94-49cf-b30e-f4febcc018c4](https://user-images.githubusercontent.com/2491500/39690619-e9a80eec-5204-11e8-80e0-8a534ec60ebe.png)

Nên sửa lại để nếu trang không có Header mới hiển thị logo.

**Comment by aptx1987** [comment]
nên cho hiển thị logo dạng svg vì khi thêm vào và đăng nhập ko thấy logo đâu luôn
