### ISSUE TITLE
Lỗi hiển thị phần danh mục tin bên phải trong Block "module block_newscenter" của Module Tin tức

### ISSUE THREAD

**Issue by hungattok57** [nukeviet/nukeviet#2666]
- Ngày: 14/05/2018
- Phiên bản: NukeViet 4.3.02
- Thông tin máy chủ: XAMPP 3.2.2 + PHP 7+ Chrome + Window 10
- Gói giao diện mặc định

Ở gói giao diện mặc định, khi hover chuột lên phần ảnh của danh sách tin bên phải trong Block "module block_newscenter" của Module Tin tức sẽ hiển thị tooltip của tin, nhưng nếu phần tooltip có một phần hiển thị trùng với ảnh tin thì khi hover vào phần trùng đó tooltip sẽ nháy liên tục.

![untitled](https://user-images.githubusercontent.com/29617761/39977938-8d99009e-5767-11e8-9660-9b8ec5098879.png)

**Comment by NukeVlad** [comment]
Thật vậy, tôi cũng có một hình ảnh nhấp nháy

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/d2ec4364aa2fe8aa84dee928635da61f55bb3e53
