### ISSUE TITLE
[SMTP] Lỗi không gửi được mail khi cấu hình SMTP

### ISSUE THREAD

**Issue by vanhuonghn011291** [nukeviet/nukeviet#2667]
NukeViet 4.3
Thử nghiệm với Module contact, thông qua chức năng Gửi mail.

> /admin/index.php?language=vi&nv=contact&op=send

Thu được lỗi sau:

> Lỗi: Hệ thống không gửi được email, Vui lòng liên hệ với Quản trị site để cấu hình lại chức năng gửi mail: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

Website sử dụng ssl, đã tạo mật khẩu ứng dụng.

> - Phiên bản NukeViet: Nukeviet 4.3
> - Môi trường thử Nghiệm: hosting
> - Hệ điều hành: Windows 64bit
> - Trình duyệt web: Chrome
> - Máy chủ web: 
![image](https://user-images.githubusercontent.com/10495040/40035002-a9e5d9ee-5829-11e8-9273-010080097d10.png)

**Comment by hoaquynhtim99** [comment]
Mình mới test thử vẫn gửi đi bình thường. Đa số các share hosting chặn SMPT port. Vấn đề này liên quan đến nhà cung cấp, code không lỗi nha bạn

**Comment by billygoat-trump** [comment]
> 
> Mình mới test thử vẫn gửi đi bình thường. Đa số các share hosting chặn SMTP port. Vấn đề này liên quan đến nhà cung cấp, code không lỗi nha bạn

Vấn đề nhỏ là, đang sử dụng bình thường trên V.4.3.03 // PHP 7.0 // Litespeed Shared hosting // rất ngon và chuẩn xác ... nhưng khi upgraded sang V.4.3.05 // PHP 7.2 // Litespeed Shared hosting // thì hàm SMTP không còn hoạt động nữa, hàm PHPmail và Linuxmail cũng tịt luôn ... chắc có lỗi lần gí đó với PHP rồi ..

**Comment by webchuyennghiep247** [comment]
Mình mò mẫm làm các kiểu cuối cùng cũng thành công (sử dụng VPS vultr cài hocvps scrips)
mình có viết bài các bạn có thể tham khảo: https://webchuyennghiep247.com/loi-smtp-khong-the-ket-noi-den-smtp-host
