### ISSUE TITLE
Sửa lại trình bày trang xem chi tiết bản tin không được cấp quyền xem chi tiết trong module News

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2672]
Để tránh bị lỗi và đạt hiệu quả SEO, cần sửa lại trình bày trang xem chi tiết bản tin không được cấp quyền xem chi tiết trong module News: Cho phép hiển thị các nội dung đã được hiển thị ra ngoài (Title, ảnh đại diện, mô tả ngắn gọn) thay vì chỉ có mỗi thông báo "Bạn không được phép xem bài viết"

**Comment by vuthao** [comment]
SEO quan trọng nhất là content, mà không có nội dung chi tiết thì cũng không index được.
Mục đích SEO là để nhiều người tiếp cận, Nếu mà không cấp quyền cho mọi người thì SEO làm ghì.

**Comment by thehung** [comment]
Mục tiêu của tính năng này không phải ngăn chặn xem nội dung mà là thúc đẩy khách đăng ký thành viên => Hiện tại khi bật chức năng này đường link được Google index đến các bài viết bị xếp vào dạng trùng lặp nội dung.

**Comment by hoaquynhtim99** [comment]
Không cho index những bài này
