### ISSUE TITLE
Loại url sau khi vô hiệu hóa lỗi SEO

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/nukeviet#2679]
Trong tất cả các mô-đun, khi bạn tắt SEO trong Cài đặt / Cài đặt cơ bản / Kích hoạt liên kết SEO = 0
liên kết có biểu mẫu, ví dụ:
domen/index.php?language=vn&nv=news&op=novosti-nukeviet/proba-6.html
Tôi tin rằng kết thúc của nó được hình thành không chính xác, nó phải sau khi vô hiệu hóa SEO:
domen/index.php?language=vn&nv=news&op=novosti-nukeviet&id=6

**Comment by hoaquynhtim99** [comment]
@NukeVlad 
Rewrite của NukeViet chỉ thực hiện được bởi hai phần NV và OP khi truyền thêm biến khác vào URL thì không thể rewrite được nữa mà sẽ xuất hiện dấu ?.

Ví dụ link `domen/index.php?language=vn&nv=news&op=novosti-nukeviet&id=6`

Sẽ thành `domen/vn/news/novosti-nukeviet/?id=6`

Đối với OP có thể truyền nhiều biến vào bằng cách phân cách chúng bởi dấu `/` khi đó hệ thống tự cắt ra và cho vào biến `$array_op`

Đối với liên kết `domen/index.php?language=vn&nv=news&op=novosti-nukeviet/proba-6.html` thì

`$array_op[0] = novosti-nukeviet`
`$array_op[1] = proba-6`

Người lập trình cần tuân thủ theo đúng quy luật đó

**Comment by hoaquynhtim99** [comment]
Ký tự cuối cùng `.html` là do người lập trình cố tình tạo ra. Cái này có thể thay đổi bằng cách sửa giá trị `$global_config['rewrite_exturl']='.html';`

**Comment by NukeVlad** [comment]
Tôi biết điều này $ global_config ['rewrite_exturl'] = '. Html'. Theo ý kiến của tôi, khi chuyển đổi chế độ xem của liên kết động thành tĩnh và ngược lại, việc thay thế phải được thực hiện tự động và chỉ khi đó quản trị viên mới quyết định nên áp dụng phần mở rộng nào.

**Comment by hoaquynhtim99** [comment]
Do vấn đề này có liên quan sâu đến code và kiến thức của SEO nên hiện tại không hỗ trợ cấu hình tự động.
Chỉ những ai biết can thiệp vào hệ thống mới có thể sửa những thông số đó.
Và cũng chưa có kế hoạch đưa phần đó vào cấu hình

**Comment by NukeVlad** [comment]
tốt, bỏ vé đi
