### ISSUE TITLE
Vấn đề lưu file data/config/config_ini.xxxxxx.php

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2682]
Hiện tại hệ thống đang lưu file data/config/config_ini.xxxxxx.php theo các domain được truy cập vào.

Nhưng vấn đề các domain chưa được kiểm tra truy cập vào site trước khi lưu file này. Dẫn đến các site sẽ sinh ra rất nhiều file  data/config/config_ini.xxxxxx.php

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/nukeviet/pull/2694
