### ISSUE TITLE
users: không hiển thị input first_name, last_name khi tắt hiển thị giới tính

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2683]
NukeViet 4.3.02 -> Tài khoản -> Tùy biến dữ liệu -> tắt hiển thị giới tính khi thêm thành viên

Thì lúc này 2 input tên và họ tên cũng bị mất luôn, khi lưu thì báo bắt buộc nhập tên

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/nukeviet/pull/2702
