### ISSUE TITLE
Lỗi không hiển thị nội dung file.pdf trong Module Giới thiệu

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#2686]
Ở Module Giới thiệu có biểu tượng up file.pdf. Nhưng khi up thì oki, lỗi ra trang chủ không hiển thị nội dung file pdf. Mong được hướng dẫn. Thank!
![pdf](https://user-images.githubusercontent.com/11238423/41576914-d1a746d6-733e-11e8-86a2-98c8f6eac0cd.png)

**Comment by hoaquynhtim99** [comment]
Chức năng hiện tại chỉ hoạt động nếu website đưa lên hoạt động ở hosting thật, không hoạt động ở localhost
