### ISSUE TITLE
Thêm chức năng kiểm tra kết nối SMTP

### ISSUE THREAD

**Issue by aptx1987** [nukeviet/nukeviet#2687]
Hiện nay khi thêm smtp để gửi mail thì test tới lui rất chi là cực đôi khi còn ko biết lỗi ở đâu

**Comment by hoaquynhtim99** [comment]
Bạn hoàn toàn có thể kiểm tra bằng việc gửi một email đi, có rất nhiều chỗ: Gửi liên hệ, gửi bài viết (news) cho người khác, sửa thông tin tài khoản...
Còn lỗi do đâu thì lỗi do cấu hình sai hoặc hosting chặn. Những cái này khó có thể xác định cụ thể được.
Ngoài ra cấu hình SMTP nói chung là một phần nâng cao, không đơn thuần dành cho người dùng phổ thông như việc đăng bài viết, quản lý bài viết ....

**Comment by mynukeviet** [comment]
Cái này mình cũng nghỉ là nên có, đơn giản là thêm một cái nút "Kiểm tra kết nối" tại form cấu hình SMTP, sẽ tiện và tiết kiệm được nhiều thời gian cho người dùng.

**Comment by hoaquynhtim99** [comment]
Tại mỗi trang đều có tài liệu tương ứng. Tại phần cấu hình SMTP để ý vào nút bên phải có dẫn tới hướng dẫn: https://wiki.nukeviet.vn/nukeviet4:admin:settings:smtp

**Comment by mynukeviet** [comment]
Hướng dẫn cấu hình là một chuyện, và test xem đã cấu hình đúng chưa là một chuyện khác. Đối với người thành thạo rồi thì cấu hình phát được ngay, nhưng với người mới thì việc cấu hình phải làm lui tới nhiều lần vì họ có thể chưa hiểu các tham số, điền lui điền tới vài lần mới đúng, mà mỗi lần test lại phải đi mở các module khác ra để test thì mất thêm thời gian.

Mình thấy nhiều mã nguồn đều có nút test này, vài câu lệnh đơn giản thôi nhưng hữu ích. Nên mình đề xuất thêm nút này.

**Comment by vuthao** [comment]
Thêm mình giải quyết như sau.
Có thêm 1 nút kiểm tra, lúc đó sẽ gửi mail đến chính tài khỏan mail (Nếu có email, hoặc email của website) .
Nếu gửi được thì thông báo thành công. Nếu lỗi thì show log trong quá trình gửi ra để người quản trị xem log để điều chỉnh.

**Comment by hoaquynhtim99** [comment]
Đã thêm https://github.com/hoaquynhtim99/nukeviet/commit/7fd887279c9372e1e749751cdb041ed16881269a
