### ISSUE TITLE
Lỗi gọi tên trong module comment

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2688]
NukeViet develop

- Nếu thông tin thành viên không có nhập họ tên, thì khi nhấn "Trả lời" nó hiện mỗi ký tự @
- Đúng của chổ này là nếu không có họ tên thì phải hiển thị username

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/nukeviet/pull/2697
