### ISSUE TITLE
Không cài được module báo lỗi safe mode trên mac

### ISSUE THREAD

**Issue by johnsmeeth** [nukeviet/nukeviet#2692]
hi all,
Mình vừa cài NukeViet 4.3.02 trên mac book cá nhân, sau khi cài xong mình vào admin -> mở rộng chọn cài đặt module shop sau khi click vào text "click vào đây để cài đặt" mình nhận được message lỗi "Host không thể tạo thư mục do safe mod on" (mình đã thử set safe_mode = Off trong php.ini nhưng vẫn không được) và một danh sách các file màu đỏ sẽ cài đặt.
Trước khi cài đặt mình đã chmod -R 777 cho các thư mục upload, assest, data, .htaccess.

Thông tin môi trường:
- OS: MacOS 10.13.6
- PHP 7.1.16
- Apache: 2.4.33
- MariaDB 10.3.8
- NukeViet 4.3.02

**Comment by vuthao** [comment]
@johnsmeeth Bạn thử như sau nhé, vào quản trị quyền admin tối cao,   Cấu hình  ->  Cấu hình FTP  sau đó thử lại nhé. 
Nếu trên máy cá nhân phục vụ test bạn chmod làm sao để php có thể  ghi được file ở tất cả các thư mục của Nukeviet nhé.

**Comment by johnsmeeth** [comment]
Cám ơn @vuthao sau khi chmod -R 777 cho các thư mục modules và themes mình đã cài đặt thành công, nhưng như thế sau khi mình cài xong phải chmod lại để đảm bảo bảo mật hay sao nhỉ? và việc này chắc cũng cần lặp lại khi update.

**Comment by vuthao** [comment]
@johnsmeeth Việc này liên quan đến việc cấu hình localhost của bạn cái này bạn phải nghiêm cứu để xử lý. Trên các hosting thường dùng việc này không xẩy ra (Quá trình cài đặt thực chất là php dùng quyền hosting cấp để ghi các file trong gói cài đặt xuống các thư mục)

**Comment by johnsmeeth** [comment]
@vuthao Ok.
