### ISSUE TITLE
Sửa phần tìm kiếm nhật ký hệ thống.

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2696]
Nếu Chọn từ ngày A-> B  hiện tại đang thống kê từ từ 0h00 ngày A đến 0h00 ngày B
Thường nhũng cái không chọn giờ sẽ phải lấy toàn bộ cả ngày A và cả ngày B.

Do đó cần sửa lại thống kê từ từ 0h00p ngày A đến 23h59p:59s ngày B

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/nukeviet/pull/2698
