### ISSUE TITLE
news: Vấn đề page_title của tag

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2706]
https://github.com/nukeviet/nukeviet/blob/develop/src/modules/News/funcs/tag.php#L26

Khi xem 1 tag, thì `$page_title = $alias`, điều này có vẻ không đúng, đúng là phải `$page_title = $key_words` chứ?

**Comment by hoaquynhtim99** [comment]
@mynukeviet xem vấn đề này nữa nhé https://github.com/nukeviet/nukeviet/issues/2705 cái này đã lưu ở đây.

Để trường `$key_words` làm title cũng không được vì nó đang cộng dồn mỗi lần sửa tag. Cái này theo như một lần trước có ai đó nói nguyên nhân là để lưu lại các tag trước đó!

**Comment by mynukeviet** [comment]
Bàn lại thử. Chứ như vấn đề mình nói ở trên cũng không hợp lý cho lắm

**Comment by hoaquynhtim99** [comment]
Đã xử lý
