### ISSUE TITLE
Vấn đề kí tự $ trong .tpl

### ISSUE THREAD

**Issue by aptx1987** [nukeviet/nukeviet#2709]
Trong .tpl có $ thì treo luôn frontend có thể do xtemplate nhận diện nhầm thành biến chăng

**Comment by hoaquynhtim99** [comment]
@aptx1987  Mình không thấy lỗi này, bạn cho ví dụ cụ thể nhé!

**Comment by anhyeuviolet** [comment]
Ví dụ:
```
<div class="header-top">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="top-bar text-right">
								<span><i class="fa fa-phone"></i>+880 123 456 789</span>
								<span><a href="http://sobuj4u.com/themexone/teashop/teashop/index.html#"><i class="fa fa-cart-plus"></i>$0.00</a></span>
							</div>
						</div>
					</div>
				</div>
			</div>
```

**Comment by webvangvn** [comment]
> <div class="header-top">
> 				<div class="container">
> 					<div class="row">
> 						<div class="col-md-24">
> 							<div class="top-bar text-right">
> 								<span><i class="fa fa-phone" aria-hidden="true"></i>+880 123 456 789</span>
> 								<span><a href="http://sobuj4u.com/themexone/teashop/teashop/index.html#"><i class="fa fa-cart-plus" aria-hidden="true"></i>$0.00</a></span>
> 							</div>
> 						</div>
> 					</div>
> 				</div>
> 			</div>
> 
> 
chèn dấu $ vào là bị quay hoài luôn 
thử chèn vào header_exten.tpl nhé

**Comment by aptx1987** [comment]
cụ thể là chèn $0 vào tpl là bị treo frontend ngay

**Comment by hoaquynhtim99** [comment]
Cái này tạm thời thay `$` bằng mã `&dollar;`

**Comment by ThinhNguyenVB** [comment]
Nếu là đơn vị tiền tệ tốt nhất cho vào flie ngôn ngữ gọi sang hay hơn là chèn luôn vào file html

**Comment by hoaquynhtim99** [comment]
Do đây là thư viện bên thứ 3, nên sẽ không sửa trong NukeViet, bạn có thể điều chỉnh theo hướng ở comment https://github.com/nukeviet/nukeviet/issues/2709#issuecomment-415667235
