### ISSUE TITLE
Một số vấn đề về Google structured-data

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2710]
1. Block company_info đang thiếu thuộc tính image, thuộc tính này bắt buộc
2. Module news, review đang sai cú pháp, nên không hiển thị đánh giá trên kết quả tìm kiếm

**Comment by hoaquynhtim99** [comment]
Cái này hình như đã đánh dấu lâu tuy nhiên chưa thể làm vì nó sửa banh giao diện :) chắc phải chuyển cho NukeViet 5

**Comment by mynukeviet** [comment]
:((

**Comment by hoaquynhtim99** [comment]
Đã xử lý
