### ISSUE TITLE
Config: về khởi tạo file theo domain trong data/config/

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#2712]
Hệ thống đang dùng NukeViet 4.3.03. Ubuntu 16.04 + PHP 7.1

Nhiều domain không có trong cấu hình nhưng vẫn có file khởi tạo.
Ngoài ra hệ thống cũng phân biệt hoa thường, có dấu - và không có - nên sinh ra file cực kỳ nhiều.
![config](https://user-images.githubusercontent.com/6290970/44327636-619db380-a489-11e8-930b-ab65c8fe7105.PNG)

**Comment by hoaquynhtim99** [comment]
Cái này đã sửa ở NukeViet 4.3.03 theo ghi nhận ở Issue này, https://github.com/nukeviet/nukeviet/issues/2682

@anhyeuviolet kiểm tra lại thử nhé

**Comment by anhyeuviolet** [comment]
Cảm ơn @hoaquynhtim99.
Giờ hệ thống chưa phát hiện tình trạng trên.
Bù lại thì .. domain của mình có cái - mà khi tạo file thì bị mất.
Rủi mai này mua thêm domain giống như vậy, chỉ không có - thì làm thế nào :P

**Comment by hoaquynhtim99** [comment]
Cũng không sao đâu, về cơ bản nó lưu `$sys_info` là thông số của server, các domain có trùng cũng không vấn đề gì
