### ISSUE TITLE
Lỗi upload ảnh trực tiếp từ trình soạn thảo

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2719]
Phiên bản 4.3.03

Module tin tức => Đăng bài mới:

Chỗ trình soạn thảo ấn nút chèn ảnh, qua tab tải lên, chọn ảnh xong ấn tải lên máy chủ thì báo 

```
Incorrect server response.
```

Ảnh vẫn được upload lên server tuy nhiên không chọn ảnh đó được

**Comment by hoaquynhtim99** [comment]
> Starting from CKEditor 4.9.0 all file uploads (including the one initiated by the filebrowser plugin) expect json response similar to this one: https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_upload.html#response-file-uploaded-successfully

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/nukeviet/pull/2720

**Comment by vuthao** [comment]
@hoaquynhtim99 Em kiểm tra lại nếu 1 trang nào có hai trình soạn thảo xem có vấn đề ghì không nhé.

**Comment by hoaquynhtim99** [comment]
@vuthao đã kiểm tra và không thấy lỗi. Quá trình upload này trả về dữ liệu trực tiếp nên không cần `$CKEditorFuncNum`
Khi ấn nút duyệt máy chủ vẫn sử dụng biến `$CKEditorFuncNum` như cũ

**Comment by quangcuong** [comment]
MÌnh bị lỗi upload hình trong module news (ở phần soạn thảo và phần hình minh họa đều bị"
Lỗi như sau: Error #Lỗi HTTP: hinh.jpg 
HÌnh có dung lượng 2MB, trong khi cấu hình cho phép upload file 5MB
Kiểm tra file logs thì thấy báo: "
[Error(1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes)] [FILE: /vendor/vinades/nukeviet/Files/Image.php] [LINE: 432]"
Lỗi này xuất hiện sau khi nâng cấp lên bản 4.3.03
