### ISSUE TITLE
Lỗi cài đặt cronjobs từ Mở rộng

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2725]
Nhấn Cài đặt, báo tải file thành công xong tới bước cuối báo

![screenshot from 2018-09-21 08-59-55](https://user-images.githubusercontent.com/6407361/45855992-e4fa3f80-bd7c-11e8-9655-2198b7a6ef3e.png)

**Comment by hoaquynhtim99** [comment]
@mynukeviet cho ví dụ về gói cài đặt nhé
