### ISSUE TITLE
Lỗi HTTP ERROR 500 khi đăng, sửa bài viết trên module news - ver 4.0.29

### ISSUE THREAD

**Issue by luannguyennnnn** [nukeviet/nukeviet#2730]
Khi em thêm, sửa và đăng bài viết mới trên Tin tức (module news) thì không thấy báo lỗi mà xuất hiện trắng trang kèm theo dòng:
" Trang này hiện không hoạt động
domain.vn hiện không thể xử lý yêu cầu này.
HTTP ERROR 500 "
Mong anh em giúp em với.
Cám ơn nhiều.
--
> Phiên bản NukeViet: NukeViet 4.0.29
> - Môi trường thử Nghiệm: Apache, cgi-fcgi
> - Hệ điều hành: LINUX
> - Trình duyệt web: Chrome 69.0.3497.100
> + Công cụ quản lý hosting: Cpanel 74.0 (build 8)
> + Các thông tin khác về phần mềm webserver, PHP và cơ sở dữ liệu:  Apache 2.4.33, MySQL 5.6.40, PHP 5.5.38
--

**Comment by hoaquynhtim99** [comment]
Hiện tại là bản 4.3 rồi nha bạn. Bạn tìm các hướng dẫn liên quan để cập nhật site của mình lên hoặc gỡ lỗi theo hướng dẫn ở https://dungpt.vinades.net/blog/huong-dan-bat-chuc-nang-hien-thi-loi-khi-trang-trang-tren-nukeviet.html rồi gửi lỗi lên diễn đàn để mọi người trợ giúp.
