### ISSUE TITLE
Tài nguyễn Server quá tải khi bật chế độ auto bakup trong admin đối với data bigdata

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/nukeviet#2732]
Hiện mình đang có 1 website với module văn bản gồm 60 column, và 22k dòng data (4GB). Khi mình bật chế độ auto bakup sql trong admin thì hệ thống hàng ngày đều chạy lệnh backup. Trong quá trình chạy thì khi đến sao lưu sql của Văn Bản Row thì làm hệ thống tài nguyên cpu lên tới 500%. Xin hỏi mọi người có giải pháp cho auto bakup với data lớn như vậy không? 
![image](https://user-images.githubusercontent.com/8604866/46711758-e336e400-cc77-11e8-89b6-010088d04e4f.png)

**Comment by thehung** [comment]
Theo anh những hệ thống lớn nên có phương án backup chuyên dụng, công cụ backup từ Admin Control Panel của site chỉ sử dụng cho những site nhỏ.

**Comment by mynukeviet** [comment]
CSDL chắc là chạy trên máy chủ, bạn có thể tiến trình của máy chủ nhé. NukeViet chỉ có thể backup database nhỏ.
