### ISSUE TITLE
Lỗi module upload: khi upload hình ảnh có chú thích

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2734]
1. Khi upload hình ảnh, mặc dù đã điền chú thích cho hình nhưng sau khi upload xong thì chú thích được điền sẽ bị mất mà hệ thống lại lấy chú thích là tên hình như mặc định (đúng ra chỉ sử dụng tên file khi người dùng không điền chú thích)

2. Khi upload bằng chế độ kéo thả trong trình soạn thảo, hình không được điền chú thích => Cần lấy chú thích mặc định là tên hình như chế độ upload trong module quản lý upload.

**Comment by hoaquynhtim99** [comment]
Lỗi này đã được fix tại https://github.com/hoaquynhtim99/nukeviet/commit/66fd445c25d738fe3ee96d7c277828c42a28e360 do plupload bị hỏng, đã trả về phiên bản ổn định nhất 2.3.6

Về ý số 2: Hiện tại nó đã như thế rồi, anh check lại nhé!

**Comment by thehung** [comment]
> 
> Về ý số 2: Hiện tại nó đã như thế rồi, anh check lại nhé!
Anh check bản mới nhất thấy vẫn còn lỗi này!
Em thử bằng cách kéo 1 ảnh vào trình soạn thảo, chờ upload xong em click đúp vào ảnh để nó mở hộp thoại sửa thuộc tính ảnh, sẽ thấy "chú thích ảnh" bị trống (xem ảnh dưới)
![Module upload của NukeViet lỗi thiếu chú thích ảnh khi upload trực tiếp](https://user-images.githubusercontent.com/1892900/56599258-67532680-6620-11e9-9564-f8e819e7bba7.jpg)

**Comment by hoaquynhtim99** [comment]
@thehung em đã kiểm tra lại vấn đề số 2 đối với Ckeditor nó là plugin có sẵn cái này tra cứu trong tài liệu và cả demo của nó chưa có chức năng trả về cái ALT của image nên không thể sửa đổi được.

**Comment by thehung** [comment]
> @thehung em đã kiểm tra lại vấn đề số 2 đối với Ckeditor nó là plugin có sẵn cái này tra cứu trong tài liệu và cả demo của nó chưa có chức năng trả về cái ALT của image nên không thể sửa đổi được.

OK, thế report cho bên CKEditor xử lý vậy!

Hoặc xem có thể tắt chế độ bắt buộc có chú thích hay không?

**Comment by hoaquynhtim99** [comment]
@thehung Cái đó thì mình làm được, em đã tắt ở phiên bản sắp tới

**Comment by ngohieu244** [comment]
Còn em thì bị mất mục upload, xoá 2 thư mục ckfinder và ckeditor rồi up lại là bình thường ạ nhưng tình trạng này xảy ra liên tục. Có cách nào khắc phục triệt để không ạ

**Comment by hoaquynhtim99** [comment]
@ngohieu244 NukeViet không dùng CKFinder chỉ có sẵn ckeditor và phần quản lý file tự viết riêng. Có lẽ bạn đã tự tùy chỉnh vào chức năng đó thì bạn cần tự kiểm soát khả năng ảnh hưởng có thể xảy ra
