### ISSUE TITLE
Webmaster tool báo "Your site has no hreflang tags"

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2737]

**Comment by mynukeviet** [comment]
Dạ, em đưa lên đây là để bổ sung vào kho code nukeviet luôn

**Comment by vuthao** [comment]
Em đã sửa rồi thì sửa luôn dùm vào nhánh https://github.com/nukeviet/nukeviet/tree/nukeviet4.3 để anh trộn nhé.

**Comment by mynukeviet** [comment]
Ok anh

**Comment by vuthao** [comment]
@mynukeviet tạo thêm 1 site nữa chạy trên local với nhánh 4.3

**Comment by mynukeviet** [comment]
ok a

**Comment by hoaquynhtim99** [comment]
@mynukeviet cái này có vấn đề thế này @mynukeviet xem thử đúng không nhé.

1. Google ví dụ 3 trường hợp cần chỉ ra hreflang

- Chỉ dịch giao diện và giữ nguyên nội dung bài viết, thường áp dụng ở diễn đàn. 
- Trên các ngôn ngữ khác nhau có một phần nào đó ngôn ngữ luôn cố định so với các ngôn ngữ khác.
- Toàn bộ trang được dịch hết sang nhiều ngôn ngữ.

2.  Cách chỉ ra hreflang là phải khai báo toàn bộ các phiên bản khác nhau (ngôn ngữ khác nhau) của một trang ở tất cả các ngôn ngữ mà site đó tồn tại

3. Áp dụng cho NukeViet:

- Site không kích hoạt đa ngôn ngữ? Thì làm gì có loại ngôn ngữ nào khác, ngôn ngữ của site đã khai báo ở thẻ `<html lang="vi" xmlns="http://www.w3.org/1999/xhtml" prefix="og: http://ogp.me/ns#">` và không cần cái hreflang này.

- Nếu site kích hoạt đa ngôn ngữ ví dụ en, vi thì tại một trang cần khai báo meta như thế này để google biết.

```
<link rel="alternate" hreflang="en"  href="https://nukeviet.vn/en/forum/HELP-Web-tu-dong-chuyen-ve-HTTPS-t45038/" />
<link rel="alternate" hreflang="vi"  href="https://nukeviet.vn/vi/forum/HELP-Web-tu-dong-chuyen-ve-HTTPS-t45038/" />
```

Quay trở lại cái commit của @mynukeviet 

- Tắt hay bật đa ngôn ngữ đều khai báo hreflang. Cái này nếu tắt đa ngôn ngữ mà vẫn khai báo thì cũng được chả sao.
- Chỉ khai báo một ngôn ngữ duy nhất cho hreflang như vậy Google sẽ không biết được trang đó trên phiên bản tiếng  Anh, tiếng Trung sẽ như thế nào.

Vấn đề lớn nằm ở cái làm sao list được URL đó trên các ngôn ngữ khác nhau:

- Module đó tồn tại trên tiếng việt thì có tồn tại trên tiếng anh không
- Bài viết hiện tại của module đó có trên tiếng việt thì có trên tiếng anh không

Theo D để đơn giản thì cần phân làm 2 khu vực: Home và không Home. Đối với home hoàn toàn có thể khai báo nhiều ngôn ngữ khác nhau (bởi ngôn ngữ nào lúc nào cũng tồn tại trang home)

Khi không phải Home thì chỉ khai báo như @mynukeviet làm hiện tại.

**Comment by hoaquynhtim99** [comment]
Sau khi xem xét, các cái này đưa cho core là bất khả thi, hiện tại đã xây dựng cơ chế cho phép các module tự quyết định bằng cách thêm vào biến:

```php
$nv_html_links[] = [
    'rel' => 'alternate',
    'href' => $u,
    'hreflang' => $l
];
```

Tham khảo ở module news. Khi thêm như thế hệ thống tự sinh meta khi vào trang có hỗ trợ. Ngoài ra đây không phải là yêu cầu bắt buộc của Google nên các module tùy thấy nếu mình có đa ngôn ngữ dạng cùng dữ liệu chỉ khác lang thì có thể bổ sung, không cứ để như thế.
