### ISSUE TITLE
không thể kết nối FPT

### ISSUE THREAD

**Issue by phucyeu2ly** [nukeviet/nukeviet#2752]
khi cấu hình FPt nhập thông số ấn chọn xác định tự động thì toàn được báo là "Không thể tìm thấy thông số nào phù hợp, hãy kiểm tra lại tên đăng nhập và mật khẩu"
mình đăng nhập = filelizza trên máy tính thì được luôn
mong nhận được hỗ trợ

**Comment by hoaquynhtim99** [comment]
Vấn đề của bạn bạn lên diễn đàn hoặc fanpage để được giúp đỡ nhé. Tại khu vực phát triển nếu bạn xác định đây là lỗi chính xác thì ghi cụ thể lỗi.
Nếu lỗi không thể xác định được bạn báo lỗi theo nguyên tắc như hướng dẫn https://github.com/nukeviet/nukeviet/blob/develop/.github/ISSUE_TEMPLATE.md
