### ISSUE TITLE
Thêm cấu hình phân biệt / không phân biệt ký tự viết hoa, viết thường trong mật khẩu

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2754]
Ngày nay truy cập trên di động rất phổ biến, thường thì điện thoại mặc định gõ ký tự đầu tiên là viết hoa. Với các đổi tượng cơ bản như học sinh đôi khi họ không để ý khi khai báo mật khẩu trên điện thoại, nên khi đăng nhập trên máy tính cứ quen viết thường ký tự đầu, thành ra cứ báo sai mật khẩu mà không biết do đâu.

Đề xuất "Thêm cấu hình phân biệt / không phân biệt ký tự viết hoa, viết thường trong mật khẩu"

**Comment by hoaquynhtim99** [comment]
D chỉ thấy nó mặc định viết hoa với kiểu text còn nhập password thì không tự viết hoa.
Với lại cái mật khẩu mà không phân biệt hoa thường thì rất là vô lý.

**Comment by mynukeviet** [comment]
À, cái này do thành viên báo lên, tr chưa test, giờ thử trên di động mới thấy pass nó ko viết hoa =))
