### ISSUE TITLE
news: Lỗi sắp xếp hiển thị bài viết hẹn giờ đăng

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2761]
Xem code thấy hiện tại đang sắp xếp theo addtime, thành ra việc sắp xếp bài viết bị sai.

Đội code xác nhận để em sửa luôn cái

**Comment by mynukeviet** [comment]
à em nhầm, thêm cấu hình mà không biết :)

**Comment by vuthao** [comment]
Mình thử thì thấy có lỗi ở phần này như sau.
Khi tìm kiếm, ví dụ lọc theo  -- Trạng thái -- , sau đó click vào link sắp xếp (Tiêu đề | Thời gian đăng) thì mất hết các dữ liệu khi tìm kiếm

**Comment by hoaquynhtim99** [comment]
Đã sửa
