### ISSUE TITLE
Gõ bỏ Google+

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2762]
Google đã thông báo Hủy bỏ tất cả tích hợp web Google+ từ ngày vào ngày 07 tháng 3 năm 2019

Nếu không rỡ bỏ các đoạn code google+ có khả năng ảnh hưởng đến bố cục của website và chức năng
Các nhà phát triển được đề nghị loại bỏ mã có liên quan từ trang web của họ càng sớm càng tốt.

NukeViet sẽ sửa lại phần này vào đầu tháng 3 tới.

chi tiết: https://www.facebook.com/groups/nukeviet/permalink/2583698605005557/

**Comment by thanhchunghti** [comment]
Từ ngày 2/4 kìa a

**Comment by truongemcom** [comment]
gỡ càng sớm càng tốt

**Comment by vuthao** [comment]
## Hướng dẫn Xỏa bỏ tích hợp web Google+ trên giao diện 

Tìm trong giao diện các file sau:
1. themes/my_theme/modules/news/detail.tpl
2. themes/my_theme/modules/page/main.tpl
3. themes/mobile_my_theme/modules/news/detail.tpl
để xóa bỏ đoạn: 
```
<div class="g-plusone" data-size="medium"></div>
```

Tìm trong giao diện các file sau:
1. /themes/my_theme/js/main.js
2. /themes/mobile_my_theme/js/main.js
để xóa bỏ đoạn: 
```
0 < $(".g-plusone").length && (window.___gcfg = {
        lang: nv_lang_data
    }, function() {
        var a = document.createElement("script");
        a.type = "text/javascript";
        a.async = !0;
        a.src = "//apis.google.com/js/plusone.js";
        var b = document.getElementsByTagName("script")[0];
        b.parentNode.insertBefore(a, b);
    }());
```
