### ISSUE TITLE
Thêm cấu hình tùy chọn chèn logo với mỗi lần đăng ảnh

### ISSUE THREAD

**Issue by thanhchunghti** [nukeviet/nukeviet#2763]
Nukeviet đang có 2 phần chèn logo
(1) là chèn với mỗi ảnh sau khi up 
(2) là chèn theo cấu hình mặc định.
Tuy nhiên có 1 cái phát sinh là nếu cấu hình mặc định, có những bài viết mình cần chèn, nhưng có bài mình không cần chèn. Nếu sử dụng chức năng như (1) thì khá là mất thời gian và công sức.

Nên em đề xuất có tùy chọn Chèn logo hoặc không ở mỗi lần upload để có thể linh động hơn cho người dùng.

Thanks all.

**Comment by thehung** [comment]
Theo anh thì cứ để như hiện tại và hiển thị thêm tùy chọn để chèn hoặc ko chèn khi upload là tiện hơn. (Nếu không thay đổi thì cứ theo cấu hình)

**Comment by thanhchunghti** [comment]
Dạ đúng rồi a. Vẫn như hiện tại nhưng thêm là Chèn/Không chèn ở mỗi lần upload

**Comment by hoaquynhtim99** [comment]
Đã thêm chức năng này tại https://github.com/hoaquynhtim99/nukeviet/commit/e59a51f668b0d0ddbfb5e09878402eb6014569a1
