### ISSUE TITLE
Lỗi comment không biết từ đâu ra?

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#2765]
Lỗi này xuất hiện trong Google webmaster: Tất cả các phiên bản nukeviet đều bị.
Không biết nó nằm ở đâu mà google nó mò ra được và báo lỗi:
- Chữ quá nhỏ để đọc
- Các phần tử có thể nhấp quá gần nhau
- Chưa đặt cửa sổ xem
Link lỗi: https://giaisach.com/index.php?language=vi&nv=comment&module=news&area=8&id=1460&allowed=6&checkss=363b35231788368c8e73658be2be94d9&perpage=5

**Comment by vuthao** [comment]
@truongemcom Tạm thời bạn vào module Comment đóng không kích hoạt cho module news nữa xem.

**Comment by truongemcom** [comment]
Đóng module thì ko thể bình luận rồi.

**Comment by hoaquynhtim99** [comment]
Module comment ở phiên bản NukeViet 4.0.11 trở về trước sử dụng iframe để chèn bình luận ở phần hiển thị bài viết.
Từ bản cao hơn chỗ đó đã được thay bằng code HTML trực tiếp.
Nếu bạn còn link sót lại lỗi thì có thể thêm vào robots.txt link chặn tới module comment
