### ISSUE TITLE
Module voting lỗi khi xem kết quả thăm dò ý kiến của thăm dò không hoạt động

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2767]
> - Phiên bản NukeViet:  4.3.04, cập thật vào: 15/11/2018 00:00
> - Môi trường thử Nghiệm: hosting
> - Trình duyệt web: Chrome Version 72.0.3626.119 (Official Build) (64-bit)
> - Máy chủ web: Apache/2.4.6 (CentOS)

Khi xem kết quả thăm dò ý kiến của 1 thăm dò (đang ở trạng thái không hoạt động, xem trong Admin Control Panel) thì popup load ra trang chủ website.

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/cf89f1831e763e9f47c0e55ecb7426bac8a0ecb2
