### ISSUE TITLE
Lỗi sai thời gian thực thi cron

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2768]
Việc sai thời gian thực thi cron đã có từ lâu vì cơ chế chạy cron khi có lượt truy cập vào website. Nhưng có một vấn đề nữa là tgian cron bị sai theo dây chuyền.

VD 1 con hẹn chạy vào 1 giờ sáng, 1 giờ 1 lần, nhưng không có người truy cập nên 1h30 nó mới chạy. Và lượt tiếp theo của nó là 2h30 (đúng ra phải 2 giờ)

Đội code xem vấn đề này, em sẽ xử lý.

**Comment by mynukeviet** [comment]
https://github.com/nukeviet/nukeviet/pull/2769

**Comment by hoaquynhtim99** [comment]
D thấy thế cũng hợp lý, a @vuthao thấy sao, ok anh trộn code nhé

**Comment by hoaquynhtim99** [comment]
@mynukeviet hiện tại nếu sửa theo cách này thì còn một chỗ là tính thời gian thực hiện tiếp theo

```php
$cronjobs_next_time = NV_CURRENTTIME + $interval;
```
Cũng sẽ có vấn đề, Triển xem lại nhé, với cả cái comment này luôn https://github.com/nukeviet/nukeviet/pull/2769#issuecomment-471857929 chuyển cái này cho phiên bản sau nhé!

**Comment by mynukeviet** [comment]
Cái này tr sửa và đã theo dõi trong một tgian dài, kết quả là tgian hoàn toàn chính xác. Nó sẽ căn cứ vào cái tgian bắt đầu để làm chuẩn.

Còn cái cấu hình j anh Thảo với Dũng nói tr chưa hiểu lắm :D

![image](https://user-images.githubusercontent.com/6407361/54401462-54ccff80-46fa-11e9-82c1-75b0e8862a09.png)

**Comment by hoaquynhtim99** [comment]
Ok, thế trộn cái này nhé, còn cấu hình kia D sửa luôn cho

**Comment by mynukeviet** [comment]
ok

**Comment by hoaquynhtim99** [comment]
Cái này đã thêm cấu hình và chỉnh sửa ở bản 4.3.05 rồi nhé
