### ISSUE TITLE
Lỗi cảnh báo Undefined index: site_name

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2770]
https://github.com/nukeviet/nukeviet/blob/nukeviet4.3/includes/mainfile.php#L185

Dòng này gọi hàm `nv_info_die`, trong hàm này có sử dụng `$global_config['site_name']`

Trong khi, biến `$global_config` được định nghĩa ở bên dưới https://github.com/nukeviet/nukeviet/blob/nukeviet4.3/includes/mainfile.php#L317

=> Lỗi cảnh báo như tiêu đề khi lọt vào điều kiện gọi hàm `nv_info_die`

**Comment by hoaquynhtim99** [comment]
Cái này thấy lâu rồi mà chưa mò ra sao nó vậy, thanks Triển, đã fix https://github.com/hoaquynhtim99/nukeviet/commit/dccfbcb3ec561bb0e8da490d8a4f355b1dc9069c

**Comment by mynukeviet** [comment]
ok, thank Dũng
