### ISSUE TITLE
Lỗi tự động xóa cookie, session khi thành viên truy cập đông

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2776]
Vấn đề này mình gặp trên hệ thống thi trắc nghiệm, đã theo dõi lâu rồi, nhưng dần loại được các vấn đề cho module trắc nghiệm sinh ra, mình nghĩ chỉ có thể là lỗi đâu đó từ hệ thống NukeViet, nên đưa lên đây nhờ đội code lưu tâm giúp.

Vấn đề xảy ra khi nhiều thành viên cùng hành động 1 lúc, cụ thể ở đây là **nộp bài thì**.

Khi nộp bài thi, xảy ra trường hợp tài khoản thành viên bị thoát ra (rất nhiều máy bị thoát), và session cũng bị làm trắng luôn.

Vấn đề này xảy ra trên 3 máy chủ với cấu hình khác nhau, nên có thể loại bỏ bớt một ít tỉ lê lỗi do máy chủ.

**Comment by vuthao** [comment]
Bên Vinades cũng có hệ thống tương tự xây dựng cho khách hàng, ngày nào cũng có người thi, số người thi cùng lúc khoảng 50  người trong 1 năm nay chưa bao giờ bị như thế. 

Bạn thử kiểm tra lại việc cấu hình cookie và session trên máy chủ xem sao.

**Comment by mynukeviet** [comment]
Cảm ơn @vuthao . Mình có lần được vào chổ này của NukeViet https://github.com/nukeviet/nukeviet/blob/nukeviet4.3/includes/ini.php#L205, và đang có niềm tin là vấn đề đang ở chổ này.

```
ini_set('session.gc_maxlifetime', 3600);
````
Khả năng là những bài thi có thời gian kéo dài hơn 1 tiếng theo như thông số ở đây sẽ bị tự động xóa session.
