### ISSUE TITLE
Bổ sung cảnh báo dữ liệu không được mã hóa khi site không dùng SSL

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2778]
Cần bổ sung cảnh báo về việc dữ liệu không được mã hóa khi site không dùng SSL. Đặc biệt ở các khu vực nhạy cảm như trang quản trị.

> Warning: this page is not encrypted for secure communication. User names, passwords, and any other information will be sent in clear text. For more information, contact your administrator.

> Cảnh báo: Dữ liệu gửi tới trang này hiện không được mã hóa. Tên đăng nhập, mật khẩu hoặc bất kỳ dữ liệu nào bạn gửi đi đều ở dạng nhìn thấy được. Hãy cân nhắc trước khi đăng nhập. Để có thêm thông tin, hãy liên hệ với người quản trị website của bạn!

**Comment by nvu-github** [comment]
@thehung Anh ơi, anh cho em hỏi là cảnh báo này mình sẽ hiển thị xuyên suốt trong phiên làm viêc hay là chỉ hiển thị trong 1 khoảng thời gian nhất định thôi ạ.

**Comment by nvu-github** [comment]
@thehung Anh ơi, anh có thể mô tả rõ hơn về yêu cầu xử lý được không ạ

**Comment by thehung** [comment]
Nếu phát hiện site không sử dụng SSL thì hiện cảnh báo khi người dùng thực hiện các hành động nhạy cảm như là đăng nhập để cảnh báo nguy cơ lộ mật khẩu thôi!

Kiểu như thế này:  
![image](https://user-images.githubusercontent.com/1892900/156542119-865d0203-f6f2-4776-a906-2f5e30b5950f.png)
