### ISSUE TITLE
comment: nhảy vào xem cụ thể 1 comment rất khó thấy, khó theo dõi

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2786]
`domain/bai-viet.html#cid=1` hiện tại khi truy cập trực tiếp đến một comment (có đối số cid để xác định comment cần xem) nó nằm lẫn vào 1 danh sách dài rất khó thấy.

Cần có hiệu ứng màu nổi bật cái comment cần xem lên, tầm 5 giây thì mờ dần đi (đa số các cms khác đều thấy có cái hiệu ứng này) để dễ thấy được commennt cần xem

**Comment by hoaquynhtim99** [comment]
Đã thêm https://github.com/nukeviet/nukeviet/pull/2788/files
