### ISSUE TITLE
default: thêm phím tắt đóng modal

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2792]
Modal của default mỗi lần muốn tắt phải click vô cái icon đóng, không thể dùng phím tắt hay click chuột ra ngoài để tắt được, điều này bất tiện

![image](https://user-images.githubusercontent.com/6407361/56452620-03e5a200-635d-11e9-847c-8840abdc5b4d.png)

**Comment by hoaquynhtim99** [comment]
Cái này cập nhật lên Bootstrap 4 có sẵn đấy :D
