### ISSUE TITLE
Thêm cấu hình, lựa chọn chỉ đăng nhập bằng email 

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/nukeviet#2795]
Trong module user chưa có cấu hình lựa chọn chỉ đăng nhập bằng email không đăng nhập qua tk username mặc dù tồn tại username.

**Comment by anhtunguyen** [comment]
[Đã thêm vào NukeViet4.6](https://github.com/nukeviet/nukeviet/commit/2ea6f532b7674251bae24a79d40311c0bddcbd30)
