### ISSUE TITLE
Lỗi http: khi upload ảnh trên nukeviet 4.0.29

### ISSUE THREAD

**Issue by ccu1tn** [nukeviet/nukeviet#2796]
Mình đang sử dụng nukeviet phiên bản 4.0.29. Hiện tại mình đang gặp lỗi http: 
![bg1](https://user-images.githubusercontent.com/43333942/56938061-7b23ee80-6b32-11e9-950c-8520a103f273.PNG)

khi upload ảnh lên website. Lỗi này xuất hiện ở trên hosting còn ở localhost thì không bị. 
Mình đã cấu hình lại thư mục upload ở trong admin,  và trên hosting mình đã chmod thư mục upload và assests là 777 nhưng vẫn không được. 
Mình kiểm tra lỗi trên hosting thì báo như sau:
![4](https://user-images.githubusercontent.com/43333942/56938082-90008200-6b32-11e9-8802-b6ace62669e1.PNG)

Mình hiện tại không biết cách khắc phục nó. 
Bạn có thể chia sẻ cách khắc phục giúp mình với. 
Cảm ơn bạn nhiều.

**Comment by hoaquynhtim99** [comment]
Bạn lẫy full file log lên xem sao, nội dung file log này không liên quan gì đến lỗi upload nên không check được.

**Comment by hoaquynhtim99** [comment]
Cái này bạn kiểm tra lại nhé, nếu cần thiết bạn cần nâng cấp lên NukeViet mới nhất. Nếu vấn đề này còn xảy ra bạn tham khảo cách báo lỗi https://github.com/nukeviet/nukeviet/blob/develop/.github/ISSUE_TEMPLATE.md để tạo báo lỗi khác nhé.
