### ISSUE TITLE
Chức năng chiếm quyền chỉnh sửa bài viết trong module news

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2803]
Ở NukeViet bản mới nhất, hiện chức năng chiếm quyền chỉnh sửa bài viết trong module news chưa tối ưu. Ví dụ: điều hành chung đang sửa bài, sau đó mở thêm 1 tab mới và logout ở tab này. Về mặt cơ bản hệ thống đã ghi nhận admin này đã logout. Tuy nhiên khi một admin khác sửa bài viết thì hệ thống vẫn báo bài viết đang được sửa => không chính xác!

**Comment by hoaquynhtim99** [comment]
Hiện tại trong code đang thiết lập thời hạn timeout là 180 giây. 
Nếu sau 180 giây admin  rời trang chỉnh sửa thì bài viết đó xem như đã hết sửa.
Trường hợp của anh anh kiểm tra lại xem thời điểm admin khác vào chỉnh sửa có ít hơn 3 phút kể từ thời điểm admin trước rời đi hay không.
