### ISSUE TITLE
news: redirect về url mới khi đổi chủ đề bài viết

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2804]
Hiện tại khi đổi chủ đề của bài viết thì URL cũ sẽ bị 404. URL bài viết có mang theo ID bài viết ở cuối nên có thể viết lại để tự redirect URL cũ về URL khi thay đổi chủ đề bài viết

**Comment by hoaquynhtim99** [comment]
@mynukeviet phần này hình như đã làm rồi, Tr kiểm tra xem đoạn này phải là nó không và có lỗi gì không https://github.com/nukeviet/nukeviet/blob/nukeviet4.3/modules/news/functions.php#L120

**Comment by mynukeviet** [comment]
Ok đã test, chổ này nó chỉ đúng khi đổi alias chủ đề, còn khi chọn lại chủ đề cho bài viết thì nó lỗi 404 như mô tả

**Comment by hoaquynhtim99** [comment]
Đã thêm: https://github.com/hoaquynhtim99/nukeviet/commit/4c18d4ed4d8ac821e54f58b23c5e4ae95f7175d7

Do phần này ảnh hưởng đến hiệu suất một tí nên đã bổ sung thêm cấu hình bật tắt trong quản trị
