### ISSUE TITLE
Thêm cấu hình Zalo appid, thêm nút chia sẽ qua Zalo

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2806]
Kênh zalo cũng đã và đang trở thành một kênh truyền thông nổi bật tại Việt Nam. Hiện để thêm các tiện ích từ zalo (nút chia sẽ,....) thì nó bắt phải có OA.

Có cần thêm cấu hình mã này, và gắn thêm nút chia sẽ zalo (bên cạnh nút chia sẽ facebook) cho news, page,...?

**Comment by truongemcom** [comment]
nút chia sẻ nên để cấu hình: người quản trị tự chọn thêm (zalo, fb, tw, ...)
