### ISSUE TITLE
Lỗi đăng nhập bị đá ra 

### ISSUE THREAD

**Issue by thuongmaiso** [nukeviet/nukeviet#2807]
Nukeviet phiên bản 4.3.5
includes\core\is_user.php
$user = json_decode($user, true);
sửa thành 
 $user = unserialize($user);  hoặc   $user = unserialize(nv_base64_decode($user));

**Comment by mynukeviet** [comment]
Sao thế anh, em cũng đang quan tâm tới lỗi này

**Comment by thuongmaiso** [comment]
lỗi này xuất hiện khi update từ phiên bản cũ lên có 2 cách khắc phục:
1. mở includes\core\is_user.php tìm dòng $user = json_decode($user, true); sửa thành $user = unserialize($user); hoặc $user = unserialize(nv_base64_decode($user));
2. modules\users\functions.php
tìm đoạn     $nv_Request->set_Cookie('nvloginhash', serialize($user), $live_cookie_time);
sửa thành:      $nv_Request->set_Cookie('nvloginhash', json_encode($user), $live_cookie_time);
lỗi không trùng json, cái sài json cái sài serialize
