### ISSUE TITLE
users: trường tùy biến dữ liệu đặt ký tự in hoa sẽ bị lỗi

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2811]
> Phiên bản NukeViet | 4.3.05Kiểm tra phiên bản NukeViet
-- | --
Phiên bản PHP | 7.2.18
Giao thức giữa máy chủ và PHP | Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/7.2.18, apache2handler
Hệ điều hành máy chủ | LINUX
Phiên bản Database | mysql 5.5.60-MariaDB

Đặt tên trường với ký tự viết hoa, ví dụ `Unit`, thì khi sửa thành viên, giá trị ở Unit sẽ không được điền

`unit` viết thường thì không lỗi

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/c8f4cedc659158036e86fe56200d98f6dd0048fc
