### ISSUE TITLE
Lỗi javascript khi click link trong của trang cơ cấu tổ chức

### ISSUE THREAD

**Issue by truyentranthanh** [nukeviet/nukeviet#2813]
Xin chào Nukeviet,
Hiện tại tôi dưới local bị báo lỗi javascript ở console nên tôi cũng đã thử chạy trên trang demo http://egov-demo.nukeviet.vn/co-cau-to-chuc/vieworg/Thanh-uy-15/ thì cũng lỗi tương tự.
Refused to execute script from 'http://egov-demo.nukeviet.vn/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
jquery.min.js?t=30:2 jQuery.Deferred exception: $(...).matchHeight is not a function TypeError: $(...).matchHeight is not a function
    at HTMLDocument.<anonymous> (http://egov-demo.nukeviet.vn/co-cau-to-chuc/vieworg/Thanh-uy-15/:594:18)
    at j (http://egov-demo.nukeviet.vn/assets/js/jquery/jquery.min.js?t=30:2:29999)
    at k (http://egov-demo.nukeviet.vn/assets/js/jquery/jquery.min.js?t=30:2:30313) undefined
r.Deferred.exceptionHook @ jquery.min.js?t=30:2
k @ jquery.min.js?t=30:2
setTimeout (async)
(anonymous) @ jquery.min.js?t=30:2
i @ jquery.min.js?t=30:2
fireWith @ jquery.min.js?t=30:2
fire @ jquery.min.js?t=30:2
i @ jquery.min.js?t=30:2
fireWith @ jquery.min.js?t=30:2
ready @ jquery.min.js?t=30:2
S @ jquery.min.js?t=30:3
jquery.min.js?t=30:2 Uncaught TypeError: $(...).matchHeight is not a function
    at HTMLDocument.<anonymous> ((index):594)
    at j (jquery.min.js?t=30:2)
    at k (jquery.min.js?t=30:2)
(anonymous) @ (index):594
j @ jquery.min.js?t=30:2
k @ jquery.min.js?t=30:2
setTimeout (async)
r.readyException @ jquery.min.js?t=30:2
(anonymous) @ jquery.min.js?t=30:2
j @ jquery.min.js?t=30:2
k @ jquery.min.js?t=30:2
setTimeout (async)
(anonymous) @ jquery.min.js?t=30:2
i @ jquery.min.js?t=30:2
fireWith @ jquery.min.js?t=30:2
fire @ jquery.min.js?t=30:2
i @ jquery.min.js?t=30:2
fireWith @ jquery.min.js?t=30:2
k @ jquery.min.js?t=30:2
setTimeout (async)
(anonymous) @ jquery.min.js?t=30:2
i @ jquery.min.js?t=30:2
fireWith @ jquery.min.js?t=30:2
fire @ jquery.min.js?t=30:2
i @ jquery.min.js?t=30:2
fireWith @ jquery.min.js?t=30:2
ready @ jquery.min.js?t=30:2
S @ jquery.min.js?t=30:3
Do mới lần đầu tôi gởi bài nên không biết có hợp lệ không nữa? nếu có gì sai sót xin bỏ qua cho tôi.
Đúng ra tôi có chụp hình nhưng không biết đính kèm theo như thế nào nên tôi chỉ copy đoạn báo lỗi
![error](https://user-images.githubusercontent.com/43329270/59477431-62239280-8e7f-11e9-9721-912a541258b5.png)

# Quy định thông báo lỗi

Khi báo lỗi bạn vui lòng cung cấp các thông tin sau để chúng tôi có thể xây dựng môi trường thử nghiệm giống của bạn để kiểm tra. Các thông tin này rất cần thiết trong quá trình đội code kiểm tra và sửa lỗi, đề nghị thành viên cung cấp đầy đủ thông tin để việc sửa lỗi được nhanh chóng.

1. Tiêu đề thông báo lỗi ngắn gọn, xúc tích, đảm bảo tóm tắt được nội dung.

2. Mô tả chi tiết lỗi gặp phải, quá trình hoặc thao tác dẫn đến lỗi.Việc mô tả quá trình dẫn đến lỗi đặc biệt quan trọng vì nhiều khi lỗi chỉ xảy ra đúng với một số thao tác nhất định màvới các thao tác khác thì hệ thống không bị lỗi. Ví dụ trường hợp này: https://github.com/nukeviet/nukeviet/issues/1178

3. Cung cấp thông tin máy chủ

* Nếu xác định lỗi từ code, vui lòng cung cấp thêm các thông tin về WebServer và trình duyệt

> - Phiên bản NukeViet: (Ví dụ NukeViet 4.0.21 hoặc NukeViet 2574f2bc8b6f23f9fcfefc021554034e33fbc695 - là chuỗi xác định commit trên kho code)
> - Môi trường thử Nghiệm: Localhost/ hosting
> - Hệ điều hành: (Ví dụ: Ubuntu 13.10 32-bit)
> - Trình duyệt web: (Ví dụ: Mozilla Firefox 27.0)
> - Máy chủ web: (Ví dụ: XAMPP for Linux 1.8.1 )

Nếu NukeViet cài trên hosting (website đang chạy thực tế) cần có thêm thông tin
> + Công cụ quản lý hosting: (Ví dụ: Cpanel/ Vista Panel/ Parallels Plesk/ DirectAdmin/ Kloxo...)
> + Các thông tin khác về phần mềm webserver, PHP và cơ sở dữ liệu: (Ví dụ: Apache 2.4.7, MySQL 5.5.36, PHP 5.4.25)

 
* Nếu xác định lỗi từ giao diện, vui lòng cung cấp thêm thông tin về  Tên gói giao diện (Chỉ kiểm tra đối với giao diện tích hợp sẵn trong source NukeViet)
 
* Nếu là các lỗi nhỏ, cơ bản, dễ xác định lỗi... hay các câu hỏi, đề xuất, góp ý... thì không cần cung cấp thông tin về máy chủ, giao diện tại phần 2, 3.

**Comment by truyentranthanh** [comment]
Tôi có thử thì thấy là thiếu file js jquery.matchHeight-min.js.

Đã tạm sử dụng nhưng không biết làm như vậy có đúng không? Nếu có gì nhờ hướng dẫn giúp.

**Comment by hoaquynhtim99** [comment]
Bạn fix được thì cứ tạm dùng chứ không có vấn đề gì. Cái này thuộc về NukeViet eGovernment, bạn có thể báo lỗi tại đây https://github.com/nukeviet/eGovernment/issues
Ở kho NukeViet này mình tạm đóng Issue này lại.
