### ISSUE TITLE
Điều kiện thỏa mãn để chạy được mà không gặp lỗi kết nối data trên bản  4.3.06

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/nukeviet#2820]
1 hình chụp lỗi
![image](https://user-images.githubusercontent.com/8604866/60415451-6385e680-9c05-11e9-8b55-1cee48a5a123.png)

2. Mô tả chi tiết lỗi gặp phải, quá trình hoặc thao tác dẫn đến lỗi.

Sau khi thực hiện nâng cấp thì báo không kết nối database mặc dù nhập đúng thông số database

Lỗi tại dòng này trong vendor/vinades/nukeviet/Core/Database.php :

$this->setAttribute(PDO::ATTR_STATEMENT_CLASS, ['\NukeViet\Core\NukeVietPDOStatement', [$this]]);
xóa đi thì dùng bình thường.
![image](https://user-images.githubusercontent.com/8604866/60415518-94661b80-9c05-11e9-9aee-cb8a2d1371b6.png)

Điều kiện thỏa mãn để chạy được là gì vậy

3. Cung cấp thông tin máy chủ

* Nếu xác định lỗi từ code, vui lòng cung cấp thêm các thông tin về WebServer và trình duyệt

> - Phiên bản NukeViet: 4.3.06
> - Môi trường thử Nghiệm: hosting 

Nếu NukeViet cài trên hosting (website đang chạy thực tế) cần có thêm thông tin
> + Công cụ quản lý hosting: Cpanel
> + Các thông tin khác về phần mềm webserver, PHP và cơ sở dữ liệu: (Ví dụ: Apache 2.4.7, MySQL 5.5.36, PHP 5.6)

**Comment by hoaquynhtim99** [comment]
Lỗi này xảy ra khi sửa file config.php

```php
$db_config['persistent'] = true;
```

Cần loại bỏ debug nếu sửa thủ công thông số persistent ở file config.
