### ISSUE TITLE
Link đến module comment bị google index, báo lỗi giao diện

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#2834]
Chi tiết Trần Phương có mô tả tại https://www.facebook.com/groups/nuke.vn/permalink/2346126402371434/

**Comment by mynukeviet** [comment]
https://github.com/nukeviet/nukeviet/pull/2835/commits/3d724131e484eec11000cf93f034cdf60683f874

**Comment by hoaquynhtim99** [comment]
Hiện tại khu vực đó NukeViet không dùng, theo mình nếu không dùng thì xóa đi không nên để nữa.
Tác giả báo lỗi chưa cho xem demo nên chưa nhận định được tại sao lại có trường hợp đó xảy ra và module nào đang dùng khu vực đó.

**Comment by hoaquynhtim99** [comment]
Phần này mình đã check lại, nguyên nhân do link này 

```
var nv_url_comm = '/index.php?language=vi&nv=comment&module=news&area=8&id=6&allowed=6&checkss=8ceb67ce788bcf319a5167fc98d0bab2&perpage=5';
 ```

**Comment by hoaquynhtim99** [comment]
Hiện tại mình đã sửa thêm một chút tại https://github.com/hoaquynhtim99/nukeviet/commit/2592e442a27e0678e22d2b4dc0ada30bfd26d147
