### ISSUE TITLE
News: Lỗi "%s" trong dòng thông báo đăng nhập thành viên để bình luận

### ISSUE THREAD

**Issue by phavaphu** [nukeviet/nukeviet#2847]
Mình đang dùng Nukeviet phiên bản mới hiện nay, trên localhost, Xampp panel 3.2.2
Không biết cuối bài viết chỗ đăng nhập bình luận nó lỗi gì đó phải không ACE nhỉ. 
Dòng thông tin yêu cầu người dùng đăng nhập để bình thuận với bài viết của module News:
"Bạn cần đăng nhập với tư cách là %s để có thể bình luận" (trích nguyên văn)
sao có "%s"?
Mình thanks.
![12](https://user-images.githubusercontent.com/20265066/65253594-1854e300-db25-11e9-8e24-f8c9f029eb82.jpg)

**Comment by nambmtk1993** [comment]
Bạn xem lại xem bạn website của bạn đang sử dụng themes nào. Nếu là themes mặc định thì không có lỗi này. Còn không phải themes mặc định Nukeviet mà còn dùng module Contact thì bạn phải sửa lại khai báo giá trị
Trong file /themes/[tên-themes]/comment/main.tpl
{LANG.comment_login} thành {LOGIN_MESSAGE}
