### ISSUE TITLE
Module News: Struct data (Schema) cho chi tiết của bài viết

### ISSUE THREAD

**Issue by aptx1987** [nukeviet/nukeviet#2849]
#SEO
Module News của Nukeviet theo mình rất hoàn thiện. Có gần như đầy đủ tất cả các tính năng cần thiết cho một website về tin tức một cách rất chuyên nghiệp. Tuy nhiên gần đây Google đánh giá các website có dữ liệu cấu trúc (Schema) tốt hơn những website không có. Mình góp ý với đội code bổ sung dữ liệu cấu trúc dạng script json gom lại thành 1 cục cho dễ quản lý. Trước tới h module news chưa hề có chỉ có phần ratting mà còn bị sai (phần này xài microdata nhìn rối mù). Nay mình góp ý chút xíu về phần này. Code mẫu:

`<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "NewsArticle",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "{SELFURL}"
  },
  "headline": "{DETAIL.title}",
  "image": "{NV_MY_DOMAIN}{DETAIL.homeimgfile}",
  "datePublished": "{DETAIL.addtime_json}",
  "dateModified": "{DETAIL.edittime_json}",
  "author": {
    "@type": "Person",
    "name": "{DETAIL.author}"
  },
   "publisher": {
    "@type": "Organization",
    "name": "{DETAIL.author}",
    "logo": {
      "@type": "ImageObject",
      "url": "{NV_MY_DOMAIN}{DETAIL.homeimgfile}"
    }
  },
  "description": "{DETAIL.hometext}"
}
</script>`

Nhìn rất dễ hiểu và quản lý trong đó addtime_json và edittime_json là ngày tháng định dạng  năm-tháng-ngày. Đây là ví dụ về đoạn json mình áp dụng và thành công.

**Comment by truongemcom** [comment]
thêm một số schema cơ bản nữa bạn

**Comment by hoaquynhtim99** [comment]
Phần dữ liệu có cấu trúc mình đã bổ sung trước đó tại đây (đã valid cho cả news và page) https://github.com/nukeviet/nukeviet/commit/4dff963d32d0463d2a996f4d8cc4836f55a25b1a
Còn phần góp ý của bạn hoàn toàn có thể viết plugin (chức năng plugin hiện tại làm được điều này)
