### ISSUE TITLE
Module News: Tuỳ chọn Nofollow và Dofollow

### ISSUE THREAD

**Issue by aptx1987** [nukeviet/nukeviet#2850]
Trong Module News gần như link nào cũng là định dạng dofollow. Tuy nhiên trong quá trình thực chiến SEO đã nghiệm ra sau 6 tháng với 66 bài viết và 60 bài key trang 1 (top 1-4 khá nhiều) thì nên có thêm phần droplist cho lựa chọn link dofollow và nofollow. Ví dụ mình thử với module news thì nofollow cho tất cả chuyên mục vì chỉ SEO chi tiết bài viết là chính. Hình mình hoạ trang chủ + chi tiết tin tức. Link có viền đỏ xung quanh là dofollow. Việc này nhằm hạn chế link rác (nukeviet index link rất là link tinh không kiểm soát được) và những link không mong muốn trên google. Tạo cho những người SEOer chủ động hơn trong việc lựa chọn link cần index hay không

<img src="https://www.upsieutoc.com/images/2019/09/30/screencapture-vute-edu-vn-gpa-la-gi-gpa-co-quan-trong-khong-hoc-bong-nao-khong-can-gpa-html-2019-09-30-20_34_31.jpg" alt="screencapture-vute-edu-vn-gpa-la-gi-gpa-co-quan-trong-khong-hoc-bong-nao-khong-can-gpa-html-2019-09-30-20_34_31.jpg" border="0">
<img src="https://www.upsieutoc.com/images/2019/09/30/screencapture-vute-edu-vn-2019-09-30-20_33_58.jpg" alt="screencapture-vute-edu-vn-2019-09-30-20_33_58.jpg" border="0">

**Comment by truongemcom** [comment]
những phần tin cũ hơn, theo dòng sự kiện nên để rel=bookmark

**Comment by hoaquynhtim99** [comment]
Thông số này không quan trọng lắm vì Google vẫn nhận nếu có link từ ngoài vào.
Nếu xử lý cái này thì xử lý qua meta robot = noindex thì tốt hơn.
