### ISSUE TITLE
Loại bỏ comment đơn

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#2851]
Cần loại bỏ comment đơn (comment chỉ hiển thị nội dung mà không có bài viết đi kèm) ra khỏi hệ thống.

**Comment by hoaquynhtim99** [comment]
Hiện tại kiểm tra đây là lỗi đến từ module page, khi xóa bài viết thì comment không được xóa theo.
Nếu bạn kiểm tra nguyên nhân khác nữa thì comment để mình check nhé!
