### ISSUE TITLE
Gom CSS, JS lại cho tối ưu tốc độ

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#2853]
Gộp những file Css và JS có cùng nhóm chức năng hoặc chuyên mục lại cho tối ưu

**Comment by aptx1987** [comment]
bản trước nk 3.4 có chức năng này rất hay, việc gom css + js lại thành 1 cục giúp giảm request lên server và tăng tốc tải web rất tốt

**Comment by hoaquynhtim99** [comment]
Phần này bạn có thể viết thêm các plugin hoặc dùng tool nén js, css lại. Core sẽ không đưa mặc định vào
