### ISSUE TITLE
Thêm cấu hình link

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#2854]
Thêm cấu hình link cho bài viết, ví dụ:
domain/giờ-ngày-tháng/tiêu đề.html
domain/cate/tiêu đề.html
... nói chung cái này nên làm giống WP

**Comment by aptx1987** [comment]
phải là domain.com/tieu-de-bai-viet
Không cần phần mở rộng nữa. Cty mình hơi bị nhiều khách liên hệ làm website cũ của họ từ wp, mà ko thể chuyển qua nuke dc vì link cũ google index sẽ bị 404 ngay. Redirect 301 thì cũng cực khổ phải lọc link phải làm = tay. Gặp site nhiều bài lâu năm ngán lắm, chưa kể link redirec nhiều ko dc google đánh giá cao và việc rớt hạng là điều đương nhiên. Vì vậy rất cần việc rút gọn lại link như trên để chuyển đổi mã nguồn góp phần phổ biến hơn cho nukeviet

**Comment by hoaquynhtim99** [comment]
Với cách cấu hình đó bạn có thể tự viết module khác, đối với module news hiện tại không thể chuyển sang các cách cấu hình link như vậy, vì có rất nhiều việc khác cần làm quan trọng hơn.
Với khả năng loại bỏ tên module thì hoàn toàn có thể tạo ra link tùy ý thích.
Hoặc nếu bạn có thể làm, thì bạn có thể làm và đóng góp cho cộng đồng.

**Comment by truongemcom** [comment]
Để Nukeviet trở thành một CMS SEO mạnh thì nó phải được tối ưu thân thiện với Google. Trong đó cấu hình đường link: domain/tiêu đề.html là một yêu cầu tối quan trọng. 
Rất mong đội code cải tiến vấn đề này. 
Trân trọng

**Comment by hoaquynhtim99** [comment]
@truongemcom nội dung này đã ghi nhận ở đây nhé bạn https://github.com/nukeviet/nukeviet/issues/2897
