### ISSUE TITLE
Trả về trang chủ khi phân trang Tag

### ISSUE THREAD

**Issue by nvnghiem** [nukeviet/nukeviet#2866]
Hệ thống tgktrans.com đang chạy phiên bản Nukeviet 4.3.06, theme default. Phát hiện lỗi trả về trang chủ khi phân trang Tag (Ví dụ:  https://tgktrans.com/tag/v%E1%BA%ADn-chuy%E1%BB%83n-si%C3%AAu-tr%C6%B0%E1%BB%9Dng-si%C3%AAu-tr%E1%BB%8Dng).
Từ page thứ 2 trở đi đều bị trả về trang chủ.

**Comment by nvnghiem** [comment]
Mình phải xử lý như thế nào về lỗi này ạ?

**Comment by hoaquynhtim99** [comment]
@nvnghiem sửa như commit trên nhé bạn
