### ISSUE TITLE
Nukeviet cant be install in sub-dir ?

### ISSUE THREAD

**Issue by GaneshKandu** [nukeviet/nukeviet#2868]
https://nukeviet.vn/en/download/CMS/NukeViet-4-3-06.html

1. Unzip the downloaded file.
2. Upload all files and subdirectories in the directory "nukeviet" to the **_root_** directory of the website.
3. Access the website by internet browser to install.

**Comment by hoaquynhtim99** [comment]
NukeViet can be installed from subdirectories. You can completely install NukeViet with the link https://mydomain.com/subdir/
