### ISSUE TITLE
Lỗi đường dẫn không truy cập trang khi cài trên localhost

### ISSUE THREAD

**Issue by hpleduit** [nukeviet/nukeviet#2870]
Chào mọi người hiện tại mình đang cài trên localhost trên phần mềm appserv-x64-9.3.0

    Máy chủ: localhost via TCP/IP
    Kiểu máy chủ: MySQL
    Server connection: SSL is not being used Tài liệu
    Phiên bản máy phục vụ: 8.0.17 - MySQL Community Server - GPL
    Phiên bản giao thức: 10
    Người dùng: root@localhost
    Bảng mã máy chủ: UTF-8 Unicode (utf8mb4)
     Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.10
    Phiên bản cơ sở dữ liệu máy khách: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
    Phần mở rộng PHP: mysqli  Tài liệu curl Tài liệu mbstring Tài liệu
    Phiên bản PHP: 7.3.10
Cài đặt mới không thông báo lỗi gì nhưng khi truy cập các đường dẫn trên trang chủ thi không truy cập được Not Found
The requested URL was not found on this server
Và mình đã vào thư mục data\logs\error_logs thì không có thông báo error_logs
Mọi người hướng dẫn sửa lỗi giúp. 
Cảm ơn

**Comment by hoaquynhtim99** [comment]
Bạn vào quản trị, cấu hình => Cấu hình chung để tắt đi chức năng rewrite rồi ra truy cập xem sao nhé

**Comment by hpleduit** [comment]
cảm ơn @hoaquynhtim99 
Mình nghĩ chắc do appserv-x64-9.3.0 có vấn đề gì đó. Mình đã cài lại bằng phần mềm Vertrigo là được không bị lỗi.

**Comment by hoaquynhtim99** [comment]
Mình đã tạo môi trường test với phần mềm appserv-x64-9.3.0 không thấy lỗi này, chỉ có điều đường dẫn nó không đẹp vì Appserv mặc định không hỗ trợ rewrite http://localhost/nukeviet/index.php/vi/news/Tin-tuc/ho-tro-tap-huan-va-trien-khai-nukeviet-cho-cac-phong-so-gd-dt-17.html
Nếu bạn còn gặp thử vào cấu hình chung để tắt rewrite đi
