### ISSUE TITLE
Vấn đề dữ liệu cấu trúc 

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2886]
Breadcrumbs chuyển sang schema https://developers.google.com/search/docs/data-types/breadcrumb?hl=vi 

Review-aggregate module news vẫn còn lỗi

**Comment by hoaquynhtim99** [comment]
Review-aggregate không còn áp dụng cho loại bài viết => Đã bỏ

**Comment by truongemcom** [comment]
vẫn còn dùng CreativeWorkSeries

**Comment by hoaquynhtim99** [comment]
@truongemcom CreativeWorkSeries chỗ nào nhỉ?

**Comment by truongemcom** [comment]
> @truongemcom CreativeWorkSeries chỗ nào nhỉ?

Google sẽ chỉ hiển thị các đánh giá với những schema (và các kiểu con tương ứng của chúng) như sau:

schema.org/Book
schema.org/Course
schema.org/CreativeWorkSeason
schema.org/CreativeWorkSeries
schema.org/Episode
schema.org/Event
schema.org/Game
schema.org/HowTo
schema.org/LocalBusiness
schema.org/MediaObject
schema.org/Movie
schema.org/MusicPlaylist
schema.org/MusicRecording
schema.org/Organization
schema.org/Product
schema.org/Recipe
schema.org/SoftwareApplication

**Comment by hoaquynhtim99** [comment]
@truongemcom ý mình hỏi là trong code chỗ nào còn dùng CreativeWorkSeries ?
Bạn báo 

> vẫn còn dùng CreativeWorkSeries

tức là nhìn thấy trong code còn

**Comment by truongemcom** [comment]
à ý mình nói là Review-aggregate vẫn còn áp dụng cho loại bài viết CreativeWorkSeries nên chuyển qua dùng loại đó.

**Comment by hoaquynhtim99** [comment]
@truongemcom Tuyệt! Với đoạn này

```html
<div itemscope itemtype="https://schema.org/AggregateRating">
  <div itemprop="itemReviewed" itemscope itemtype="https://schema.org/CreativeWorkSeries">
    <span itemprop="name">Tên bài viết</span>
  </div>
  Tổng xếp hạng
  <span itemprop="ratingValue">4.2</span> / <span itemprop="bestRating">5</span> sao -
  <span itemprop="ratingCount">123</span> lượt đánh giá
</div>
```

**Comment by motcaiten** [comment]
Hiện tại ở Breadcrumbs đang xài data-vocabulary.org  sắp tới google không còn hỗ trợ data-vocabulary.org cần chuyển qua schema.org

**Comment by hoaquynhtim99** [comment]
@motcaiten cái này đã chuyển trước đó tại đây https://github.com/nukeviet/nukeviet/commit/2802e325b5388d340cdfcb031a91d6e502d243a6

**Comment by truongemcom** [comment]
chuyển qua nhưng lại bị báo lỗi: data-vocabulary.org schema deprecated trong google search console 
<div class="breadcrumbs-wrap">
<div class="display">
<ul class="breadcrumbs list-none"><li id="brcr_0" itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a itemprop="url" href="/"><span itemprop="title">Trang nhất</span></a></li><li id="brcr_1" itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a itemprop="url" href="/book/"><span itemprop="title">Sách</span></a></li><li id="brcr_2" itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a itemprop="url" href="/book/toan-hoc/"><span itemprop="title">Toán học</span></a></li></ul>
</div>
<ul class="temp-breadcrumbs hidden" itemscope itemtype="https://schema.org/BreadcrumbList">
<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><span itemprop="position" content="1" /><a itemprop="item" href="/" title="Trang nhất"><span itemprop="name">Trang nhất</span></a></span></li>
<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><span itemprop="position" content="2" /><a itemprop="item" href="/book/" title="Sách"><span class="txt" itemprop="name">Sách</span></a></span></li><li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><span itemprop="position" content="2" /><a itemprop="item" href="/book/toan-hoc/" title="Toán học"><span class="txt" itemprop="name">Toán học</span></a></span></li>
</ul>
</div>
</div>

**Comment by hoaquynhtim99** [comment]
@truongemcom cái đó bạn check lại giao diện bạn đang sử dụng, chuyển đổi theo bài viết https://writeblabla.com/blog/chuyen-doi-cua-nukeviet-breadcrumb-tu-vocabulary-sang-schema-org.html

**Comment by motcaiten** [comment]
Cảm ơn. Hiện tại đã fix đã được chấp nhận 
<img width="1131" alt="Ảnh chụp Màn hình 2020-01-28 lúc 21 09 13" src="https://user-images.githubusercontent.com/8292355/73271046-7780dd80-4212-11ea-8b88-88fca34f960c.png">

**Comment by motcaiten** [comment]
> data-vocabulary.org

Sai đây nè bạn. Cái này không xài nữa mà

**Comment by hoaquynhtim99** [comment]
> > data-vocabulary.org
> 
> Sai đây nè bạn. Cái này không xài nữa mà

Bạn ghi rõ hơn đi, trong chuỗi báo lỗi này có nhiều bài viết bạn ghi đơn giản quá không nắm được

**Comment by truongemcom** [comment]
ý bạn ấy nói là đã sửa rồi nhưng không hiểu cái data-vocabulary.org còn nằm ở đâu mà vẫn bị báo lỗi data-vocabulary.org schema deprecated trong google search console.
Cái đó nó nằm trên class="breadcrumbs list-none"><li id="brcr_0"

**Comment by truongemcom** [comment]
cái data-vocabulary.org còn nằm ở đây: themes/giao-dien-cua-ban/js/main.js

**Comment by hoaquynhtim99** [comment]
> cái data-vocabulary.org còn nằm ở đây: themes/giao-dien-cua-ban/js/main.js

Cái nằm ở đó là cái lỗi, bạn xem bài này để bỏ nó đi https://writeblabla.com/blog/huong-dan-sua-loi-breadcrumb-bi-dao-nguoc-tren-nukeviet-4.html

**Comment by truongemcom** [comment]
> > cái data-vocabulary.org còn nằm ở đây: themes/giao-dien-cua-ban/js/main.js
> 
> Cái nằm ở đó là cái lỗi, bạn xem bài này để bỏ nó đi https://writeblabla.com/blog/huong-dan-sua-loi-breadcrumb-bi-dao-nguoc-tren-nukeviet-4.html

Vấn đề đã được giải quyết, bạn nên thêm phần này vào hướng dẫn thay schema Breadcrumbs để mọi người làm đúng.

**Comment by truongemcom** [comment]
Đã sửa Breadcrumbs đảo ngược nhưng vẫn còn báo lỗi: data-vocabulary.org schema deprecated , thật bó tay 
link lỗi: https://baihochay.com/uploads/news/2020_02/loi-data-vocabulary.jpg

**Comment by hoaquynhtim99** [comment]
@truongemcom bạn vào dọn dẹp hệ thống, xóa cache để set lại JS mới xem google có cache js không.
Còn lại thì chờ thôi (❁´◡`❁)

**Comment by motcaiten** [comment]
> Đã sửa Breadcrumbs đảo ngược nhưng vẫn còn báo lỗi: data-vocabulary.org schema deprecated , thật bó tay
> link lỗi: https://baihochay.com/uploads/news/2020_02/loi-data-vocabulary.jpg

xoá cache rồi cập nhật trên websmaster  -- > Chờ google 

Mình thấy bên mình ok rồi https://packagingsolution.vn/vi/news/blogs/van-chuyen-kinh-an-toan-voi-thanh-nep-giay-thanh-nep-goc-22.html

**Comment by truongemcom** [comment]
cái nào có hiển thị `<ul class="subs-breadcrumbs"></ul>` sẽ lỗi
