### ISSUE TITLE
Lỗi khi lưu sau khi copi bài viết trong module about

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2888]
Phiên bản NukeViet mới nhất trở về trước đều gặp phải lỗi: Khi copi bài viết trong module about, sửa alias xong lưu lại nó không nhận mà lại lấy alias là tiêu đề bỏ dấu.

**Comment by hoaquynhtim99** [comment]
Bổ sung thêm lỗi: Khi cấu hình đăng bài mới lên đầu tiên, copy xong bài viết mới được copy ở vị trí thứ 2
