### ISSUE TITLE
Lỗi bình luận với IPv6

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#2889]
Mặc định Nukeviet quy định trường Post_ip trong bản Vi_comment là 15 ký tự đối với IPv4
Nhưng đối với IPv6 độ dài ký tự là 39 do đó sẽ bị lỗi không bình luận được.
=> thay đổi giá trị này thành 39.

**Comment by hoaquynhtim99** [comment]
Đã cập nhật ở commit trên.
