### ISSUE TITLE
Bổ sung tính năng giảm chất lượng cho từng bức ảnh

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2894]
Có những bức ảnh có chất lượng cao khiến dung lượng rất lớn, cần bổ sung chức năng chuyển ảnh sang định dạng jpg và giảm chất lượng ảnh JPG xuống.

**Comment by anhtunguyen** [comment]
Thấy google đang khuyến khích chuyển từ ảnh jpg quá cũ kĩ sang định dạng webp - một định dạng cho phép nén ảnh tốt, khiến dung lượng ảnh giảm 30-40% mà chất lượng không thay đổi. Php có function imagewebp cho phép tạo ảnh định dạng webp. Các trình duyệt hiện đại đều hỗ trợ định dạng này. Việc giảm chất lượng ảnh thì không vấn đề gì khó cả.

**Comment by anhtunguyen** [comment]
[ Thêm khả năng tạo file WEBP ở trình quản lý file ](https://github.com/nukeviet/nukeviet/commit/a008fd52f6a6135fd49269a3b53a23fcecd5805c)
