### ISSUE TITLE
Thêm lựa chọn Giao diện mặc định cho mobile

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#2895]
Hiện tại fix cứng giao diện cho mobile là mobile_default, điều này rất bất tiện khi mỗi lần nâng cấp lại phải sửa giao diện mobile.
Do đó cần có thêm lựa chọn giao diện mặc định cho mobile.

**Comment by hoaquynhtim99** [comment]
Giao diện mobile không fix cứng, được cấu hình tại Cấu hình => Cấu hình site (/admin/index.php?language=vi&nv=settings&op=main) mục **Giao diện mặc định cho Mobile**

**Comment by truongemcom** [comment]
> Giao diện mobile không fix cứng, được cấu hình tại Cấu hình => Cấu hình site (/admin/index.php?language=vi&nv=settings&op=main) mục **Giao diện mặc định cho Mobile**

à phải đặt tên giao diện là mobile_.... mới đc
