### ISSUE TITLE
Thêm lựa chọn cấu hình đường link

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#2897]
Hiện tại nukeviet đang cấu hình đường link theo kiểu: tênmiền/category/tên bài viết_số thứtự.html
có thể thêm cấu hình đường link là tênmiền/tên bài viết_số thứ tự.html (vì mỗi bài viết đều được đánh số ở cuối link nên hãy thêm lựa chọn này)

**Comment by hoaquynhtim99** [comment]
Module news hiện tại và tương lai không sửa chức năng này, nếu bạn cần hãy viết module khác và dùng chức năng loại bỏ tên module khỏi URL để có đường link như mong muốn.
Còn việc rewrite cho cả hệ thống vấn đề này đã có bàn với các cuộc offline của cộng đồng cũng như trong định hướng về NukeViet 5 https://nukeviet.vn/vi/news/nhom-phat-trien/ke-hoach-phat-trien-nukeviet-phien-ban-5-0-574.html

**Comment by hoaquynhtim99** [comment]
Cái này khá rắc rối vì phải kiểm tra liên kết tĩnh của chuyên mục với liên kết tĩnh của từng bài viết + id bài viết nên tạm thời không xử lý được với module news.

**Comment by hoaquynhtim99** [comment]
Trùng https://github.com/nukeviet/nukeviet/issues/2714 cần chuyển sang thảo luận ở đó
