### ISSUE TITLE
Đưa Litespeed vào nukeviet

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/nukeviet#2907]
Hiện tại em thấy Litespeed được nhiều nhà cung cấp hosting hỗ trợ nhưng chưa ứng dụng được vào Nukeviet. Không biết anh chị nào làm vấn đề này chưa

**Comment by hoaquynhtim99** [comment]
@motcaiten Litespeed tương thích với Apache nên mình thấy chạy bình thường. Vấn đề bạn gặp phải là gì?
Nó chỉ khác LiteSpeed load .htaccess một lần, khi sửa thì phải restart lại service.
