### ISSUE TITLE
Lỗi comment đơn

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#2908]
Google căn cứ vào chỗ này để báo: Lỗi comment đơn 

```
<script type="text/javascript">
--
  | var nv_url_comm = '/index.php?language=vi&nv=comment&module=news&area=8&id=4406&allowed=6&checkss=9cfdcf94ad43b794bbf068ea8b8ff537&perpage=5';
  | $("#sort").change(function() {
  | $.post(nv_url_comm + '&nocache=' + new Date().getTime(), 'sortcomm=' + $('#sort').val() , function(res) {
  | $('#idcomment').html(res);
  | });
  | });
  | </script>
```
chỉ cần copy: `/index.php?language=vi&nv=comment&module=news&area=8&id=4406&allowed=6&checkss=9cfdcf94ad43b794bbf068ea8b8ff537&perpage=5` và thêm tên miền vào phía trước sẽ dẫn ra khung comment thần thánh.

**Comment by hoaquynhtim99** [comment]
@truongemcom bạn gửi cụ thể cảnh báo lỗi của google là gì xem?
Ngoài ra bản bạn đang sử dụng là bản nào?
Bản mới nhất link đó đã được thêm cả header và thẻ meta noindex

**Comment by truongemcom** [comment]
Đúng là bản mới nhất đã chặn google với thẻ noindex, nhưng ý mình muốn đề cập là google nó link vào liên kết này để index. Vậy tại sao không sửa lại liên kết này, liên kết không có giao diện mà nó vẫn chạy thì không nên để.
`https://nukeviet.vn/index.php?language=vi&nv=comment&module=news&area=8&id=613&allowed=4&checkss=e6ea7a66829b0398aaaf5abb42d5d90c&perpage=5#`

**Comment by hoaquynhtim99** [comment]
Link này dùng để load comment khi sắp xếp, mình sẽ nghiên cứu bỏ nó ở bản tới

**Comment by hoaquynhtim99** [comment]
Hiện tại mình đã gỡ link này ra, sẽ cập nhật ở phiên bản tới
