### ISSUE TITLE
Triển khai hreflang không đúng

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#2909]
Google đã phát hiện thấy một số trang trên trang web của bạn đã triển khai thẻ rel-alternate-hreflang không đúng. Đặc biệt, có thể đã xảy ra sự cố với mã khu vực và ngôn ngữ không đúng hoặc liên kết hai chiều không chính xác (nếu trang A liên kết tới trang B bằng hreflang thì cũng phải có một liên kết ngược lại từ B đến A).

**Comment by hoaquynhtim99** [comment]
Mình check trong code không có thẻ hreflang? Có phải là bạn tự thêm?

**Comment by truongemcom** [comment]
Thật không biết google nó mò ở đâu, mình kiểm tra cũng không có thẻ hreflang thế mà nó lại báo: https://sachgiai.com

**Comment by hoaquynhtim99** [comment]
Bạn check lại site của mình nhé, về hreflang bạn xem thêm ở đây https://github.com/nukeviet/nukeviet/issues/2737
