### ISSUE TITLE
Báo Lỗi Trường itemreviewed bị thiếu

### ISSUE THREAD

**Issue by hungga** [nukeviet/nukeviet#2912]
Báo Lỗi Trường itemreviewed bị thiếu do google báo lỗi 
![Screenshot_20200211-121450](https://user-images.githubusercontent.com/9975118/74213228-e35f4d80-4cca-11ea-970c-0d1680e7cdeb.png)

**Comment by hoaquynhtim99** [comment]
Phần này đã sửa ở https://github.com/nukeviet/nukeviet/commit/95c0119a44f2093ddc11527a7422b973c2b5b5be
Sẽ được phát hành ở NukeViet 4.3.09, bạn có thể tham khảo bài viết này để sửa cho giao diện của bạn hoặc sửa trước khi phát hành https://writeblabla.com/blog/huong-dan-sua-loi-review-snippet-tren-nukeviet-4-3.html

**Comment by hoaquynhtim99** [comment]
https://github.com/nukeviet/nukeviet/issues/2886
