### ISSUE TITLE
Múi giờ đồng bộ ngược

### ISSUE THREAD

**Issue by khaiphan9x** [nukeviet/nukeviet#2916]
Hãy sử dụng múi giờ mới Asia/Ho_Chi_Minh thay vì múi giờ cũ Asia/Saigon, đã được báo cáo sửa đổi trên Timezone quốc tế

**Comment by vuthao** [comment]
Thank @khaiphan9x đã báo

Mình đã sửa lại tại: https://github.com/nukeviet/nukeviet/pull/2917/commits/7a8da3a573ae48737e38616c4c106b5616658d08
