### ISSUE TITLE
Báo lỗi Chức năng upload file lỗi: 1 bên là cây thư mục, bên còn lại tải ra trang chủ 

### ISSUE THREAD

**Issue by nguyenvandu125** [nukeviet/nukeviet#2923]
1. Chức năng upload file lỗi: 1 bên là cây thư mục, bên còn lại tải ra trang chủ khi cài đặt trên hosting DirectAdmin:
2. Khi thực hiện upload bất kỳ ảnh, file... lên web đều lỗi như trên.
3. Cung cấp thông tin máy chủ
> - Phiên bản NukeViet:  NukeViet eGovernment 1.1.02
> - Môi trường thử Nghiệm: hosting
> - Hệ điều hành: Win 10 62-bit)
> - Trình duyệt web: Chrome  80.0.3987.122
> - Máy chủ web: DirectAdmin

 NukeViet cài trên hosting (website đang chạy thực tế) cần có thêm thông tin
> + Công cụ quản lý hosting: DirectAdmin
> + Các thông tin khác về phần mềm webserver, PHP và cơ sở dữ liệu: 

DirectAdmin 1.58.1 
Dovecot 2.3.6 (7eab80676) |  
Exim 4.92 
Apache  | 2.4.39 |  
MySQL 10.3.16 |  
php 7.2.19 |  
Pure-FTPd  1.0.49 |  
sshd

**Comment by hoaquynhtim99** [comment]
Bạn gửi giúp mình thông tin hosting và tài khoản quản trị qua Messenger mình check thử nhé 
https://www.facebook.com/tandungcoder
Chỗ này chưa ghi nhận có lỗi như thế.

**Comment by hoaquynhtim99** [comment]
Phần này đã kiểm tra và thông tin do máy chủ của bạn.
Chi tiết thêm bạn xem ở https://writeblabla.com/blog/khac-phuc-tinh-trang-khong-tai-duoc-phan-quan-ly-file-tren-nukeviet.html
