### ISSUE TITLE
Lỗi không nhận nv_unickmax khi thay đổi username

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#2925]
`$error = nv_check_valid_login($login, $global_config['nv_unickmax'], $global_config['nv_unickmin']);`

Biến $global_config['nv_unickmax'] không được khai báo global

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/nukeviet/commit/7e2396caf5a0a854f1a19f58cf1e9e48396729cc
