### ISSUE TITLE
Mật khẩu dài quá sẽ không thể xóa được tài khoản quản trị khác

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2944]
Nếu mật khẩu dài, ví dụ: F25uoG13ZArlSGnWPQ9vfxxJIl23u2H
Khi xóa tài khoản quản trị khác, sẽ nhận được báo lỗi: 

> Mật khẩu quản trị “F25uoG13ZArlSGnWPQ9v” không chính xác. Hãy thử lại lần nữa.

Có vẻ như mật khẩu chỉ cho sử dụng 21 ký tự.

**Comment by hoaquynhtim99** [comment]
Đã sửa. Chỗ này nguyên nhân do lấy giới hạn ô nhập là số ký tự theo cấu hình hiện thời.
Có thể trước đó pass trong CSDL dài hơn cấu hình hiện tại.
Cái này sửa để bỏ giới hạn đó, cho nhập thoải mái, thực ra mục đích giới hạn là để người dùng nhập đúng số yêu cầu khi tạo tài khoản thôi, còn khi khác không nhất thiết phải giới hạn
