### ISSUE TITLE
Lỗi cấu hình gửi mail

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2949]
Sau khi cập nhật lên NukeViet 4.4.00

- Trước đây site đang để  PHPmail
- Cập nhật lên 4.4.00 => Hệ thống không gửi email nữa
- Vào cấu hình gửi email ấn gửi thử email nhận được báo lỗi `no mail mode`
- Chọn PHPmail rồi lưu lại => Mất cái checked của radio nhưng thử gửi email test lại thì báo thành công.

**Comment by hoaquynhtim99** [comment]
Site đang để cấu hình SMTP thì thấy bình thường.

**Comment by webchuyennghiep247** [comment]
bác thử check port 465 và 587 xem mở chưa nhé https://ping.eu/port-chk/
tham khảo cách khắc phục:https://webchuyennghiep247.com/loi-smtp-khong-the-ket-noi-den-smtp-host
