### ISSUE TITLE
Menu mobile không hoạt động

### ISSUE THREAD

**Issue by Hoang-dev** [nukeviet/nukeviet#2950]
Test trên máy tính, Menu không hoạt động
![1](https://user-images.githubusercontent.com/64528697/80583765-d84eca80-8a3a-11ea-987c-4be113088bff.png)

Phiên bản NukeViet | 4.4.00
Phiên bản PHP | 5.6.17
Giao thức giữa máy chủ và PHP | Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/5.6.17 mod_wsgi/4.4.21 Python/3.5.1, apache2handler
Hệ điều hành máy chủ | WINDOWS NT
Phiên bản Database | mysql 5.6.28

**Comment by hoaquynhtim99** [comment]
Cái này do jquery không tương thích, bạn tải file cũ này ghi đè nhé https://github.com/nukeviet/nukeviet/blob/nukeviet4.3/assets/js/jquery/jquery.min.js

**Comment by hoaquynhtim99** [comment]
Đã cho hạ xuống Jquery 3.4.1 https://github.com/nukeviet/nukeviet/commit/9b5cc4e81667c16e000c3cb489eb7545d41d1798
