### ISSUE TITLE
Hoàn thiện chức năng quản lý tác giả

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#2951]
Cần hoàn thiện chức năng quản lý tác giả để độc giả có thể xem các bài cùng tác giả (thay vì xem theo người đăng như hiện tại):
- Liên kết tác giả vào users. Các trường hợp này cho xem theo tác giả. Có thể gắn nhiều users trong 1 bài viết (Để định danh nhiều tác giả) giống như kiểu gắn tag.
- Trường hợp tác giả chưa có tài khoản trên hệ thống thì cho phép điền Text như cũ.

Các issue liên quan: #1880

**Comment by truongemcom** [comment]
Kết hợp sửa luôn cái này nữa thì tốt biết mấy: [#2855](https://github.com/nukeviet/nukeviet/issues/2855)

**Comment by cuongquachc88** [comment]
@thehung tính năng đã dev chưa bác ?

**Comment by thehung** [comment]
> @thehung tính năng đã dev chưa bác ?

Chưa bạn ơi, dự kiến tới version 4.4.01 (nội tỏng 3 tháng nữa) nhé!

**Comment by cuongquachc88** [comment]
À tại mình hỏi định tham gia contribute dev tính năng này

**Comment by truongemcom** [comment]
Vậy là cái author như của WP rồi.
