### ISSUE TITLE
Tối ưu hiển thị nhóm thành viên

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2952]
Ở trong các module, hiện tại Nhóm thành viên nếu đã nhưng hiệu lực  vẫn hiển thị để người quản trị chọn.
Nếu site có khoảng 1000 nhóm thành viên, trong khi chỉ có 20 nhóm hiệu lực để phân quyền.

Do đó cần tối ưu lại phần này, như thê cấu hình: có hiển thị nhóm thành viên ngưng hiệu lực ở các module.

**Comment by hoaquynhtim99** [comment]
Cái này em thấy các module nên tự lập trình thì ổn hơn.
Nếu không hiển thị thì sẽ gặp tình trạng: Ấn sửa 1 nội dung được phân quyền, nhóm đó bị mất khỏi danh sách, khi lưu lại kiểm tra bằng lệnh `array_intersect($group_id, array_keys($group_lists))` thì mất tiêu những nhóm trước đó.
Mặc dù nhu cầu là vẫn muốn phân quyền có cái nhóm đang ngưng hiệu lực vào đó, khi kích hoạt nhóm lại thì vẫn xài bình thường.

Nếu không có giải pháp nào thay thế thì em nghĩ cái này không thực hiện.

**Comment by hoaquynhtim99** [comment]
Lâu không có thảo luận thêm nên close nhé anh. Nếu cần a mở lại và thảo luận tiếp ạ
