### ISSUE TITLE
Giao diện mobile_default không hiển thị nội dung

### ISSUE THREAD

**Issue by phudq90** [nukeviet/nukeviet#2954]
Web mình trước chạy ổn, bữa nay trên mobile bị lỗi không hiện nội dung gì cả.
Giao diện desktop vẫn hiển thị đầy đủ bình thường.
Giao diện mobile đang sử dụng là mobile_default theo nukeviet không edit gì thêm.
Đã test trên Chrome, Firefox, Safari

Screenshot ở đây:
<img width="1436" alt="Screen Shot 2020-05-15 at 5 38 10 PM" src="https://user-images.githubusercontent.com/6510187/82042450-12bf9500-96d4-11ea-92d8-3d12690a69bc.png">

- Phiên bản NukeViet: 4.3.00
- PHP: 5.6.40
- Giao thức giữa máy chủ và PHP: LiteSpeed, litespeed
- Hệ điều hành máy chủ: LINUX
- Phiên bản Database: mysql 10.3.22-MariaDB-cll-lve
- Link website: phukienturack.com

**Comment by hoaquynhtim99** [comment]
Mình vào thấy chạy bình thường
