### ISSUE TITLE
Lỗi cấu hình gửi mail trên NukeViet 4.4

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2958]
Khi khai báo đầy đủ tất cả các cấu hình ở /admin/index.php?language=vi&nv=settings&op=smtp

Nhưng khi gửi đi, email của site vấn lấy là email trong cấu hình chung, chứ không lấy thông tin cấu hình SMTP

**Comment by hoaquynhtim99** [comment]
Em dường như thấy 1 số máy chủ gửi mail, ví dụ Gmail không thể thay đổi email người gửi được
Nó luôn luôn hiển thị là email của tài khoản SMTP
Chỉ có thể thay tên người gửi

Trong cấu hình có ghi `Lưu ý: Giá trị này có thể không có tác dụng tùy theo máy chủ gửi hoặc máy chủ nhận`

**Comment by hoaquynhtim99** [comment]
Ngoài ra a check xem mục **Cố định người gửi. Dùng để ép tất cả thông tin người gửi có giá trị theo cấu hình tại đây thay vì thông tin trong mỗi lần gửi** đã check chưa
Nếu chưa check thì code mặc định trước giờ vẫn lấy email, tên gửi là email và tên của site tại cấu hình chung. Muốn đổi cần viết lại code sendmail https://github.com/nukeviet/nukeviet/blob/nukeviet4.4/includes/functions.php

```
 * @param array|string $from:
 *            Nếu $from là string thì nó được hiểu là reply_address
 *            Nếu là array thì có các giá trị sau đây:
 *            [reply_name: 'Reply Me' (string|array),
 *            reply_address: 'reply@nukeviet.vn'(string|array),
 *            from_name: contact@nukeviet.vn (string),
 *            from_address: 'NukeViet']
```

Code hiện tại chỉ truyền vào 2 tham số hoặc 1 tham số dạng string, cần thay nó thành 4 tham số.

Hiện em check khi cố định thì không thấy lỗi
