### ISSUE TITLE
Cải thiện module Page

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#2965]
Thực chất module Page và About là giống nhau.
Hiện tại nếu chọn loại bỏ tên module Page trong cấu hình site thì liên kết sẽ thành: domain/tên-bài-viết.html
OK, Vậy ta chỉ cần phân nhóm cho bài viết (giống như chuyên mục) và thêm Theo dòng sự kiện cho Page là đã nạp được SEO cực mạnh cho Page rồi.
Vậy cần thêm: Nhóm, Dòng sự kiện, Thống kê lượt xem, .. và theme để hiển thị trang chủ là OK.

Các bạn cho ý kiến thêm nhé!

**Comment by vuthao** [comment]
Gửi @truongemcom trong phiên bản NukeViet 5 chúng tôi sẽ chú ý vấn đề này.

Còn phiên bản NukeViet 4 việc này không thực hiện được, do sẽ phải sửa lại rất nhiều code

**Comment by hoaquynhtim99** [comment]
@truongemcom đây không phải là vấn đề của module mà toàn hệ thống.
Nội dung này tương tự https://github.com/nukeviet/nukeviet/issues/2897
Issue này mình sẽ đóng, bạn cần thảo luận gì thảo luận ở Issue trên nhé.
