### ISSUE TITLE
Kiểm tra lỗi NukeViet khi cài trên Openlitespeed 1.6.1

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2966]
Khi đăng nhập admin, bị chặn: Your request is blocked
Nguyên nhân cụ thể:
Máy chủ thật chạy cổng 8080 `[SERVER_PORT] => 8080`
Cấu hình proxy server `[HTTP_X_FORWARDED_PORT] => 80`
Tức thực tế domain vẫn hoạt động với dạng `domain.com` chứ không phải `domain.com:8080`

Trong code NukeViet xác định PORT của server: 

```
$server_port = ($_SERVER['SERVER_PORT'] == '80' or $_SERVER['SERVER_PORT'] == '443') ? '' : (':' . $_SERVER['SERVER_PORT']);
```

Tức đang lấy từ máy chủ thật dẫn tới khi cấu hình proxy web chạy domain `domain.com` trong khi code lại xác định domain là `domain.com:8080`

Theo nguyên tắc đó có nên áp dụng luôn cho host và giao thức hay không?

```
[HTTP_X_FORWARDED_HOST] => real.domain.com
[HTTP_X_FORWARDED_PORT] => 80
[HTTP_X_FORWARDED_PROTO] => http
```

**Comment by vuthao** [comment]
@hoaquynhtim99 Theo anh cái này nên cấu hình cứng vào file config để khỏi mất công xác định.
