### ISSUE TITLE
Lỗi cài đặt module NukeViet 5

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#2969]
Tôi đóng gói module page của NukeViet 5

1. Sau đó đổi tên thành module Elearning
2. Cái đặt module bình thường.
3. Khi vào quản trị module thì báo module không tồn tại.

Tôi đã khắc phục tạm bằng cách vào bảng nv5_vi_modules đổi tên module Elearning thành elearning thì mới quản trị được module.
[nv4_module_Elearning.zip](https://github.com/nukeviet/nukeviet/files/4817052/nv4_module_Elearning.zip)

**Comment by hoaquynhtim99** [comment]
NukeViet 5 đã dừng phát triển, bản 4.6 chưa có kế hoạch bắt buộc tên module viết hoa
