### ISSUE TITLE
SCHEMA_HEADLINE không có dữ liệu

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#2972]
Thông số SCHEMA_HEADLINE trong detail.tpl của module News
<span class="hidden hide d-none" itemprop="description">{SCHEMA_HEADLINE}</span>
Không có dữ liệu trả về.

**Comment by motcaiten** [comment]
Trong theme.php dưới dòng 720 thêm

`$xtpl->assign('SCHEMA_HEADLINE', $news_contents['hometext']);`

**Comment by hoaquynhtim99** [comment]
@motcaiten chỗ đó thừa bởi bên dưới đã có `<div class="hometext m-bottom" itemprop="description">{DETAIL.hometext}</div>` mình đã fix ở commit trên
