### ISSUE TITLE
reCaptcha V3 không hoạt động với NukeViet

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#2974]
Nếu cài đặt reCaptcha V3 cho NukeViet thì sẽ bị báo lỗi và không hiển thị mã Captcha.

**Comment by hoaquynhtim99** [comment]
Cái này chưa hỗ trợ ở thời điểm hiện tại bạn, sẽ tích hợp trong tương lai. Nhanh nhất là NukeViet 5
