### ISSUE TITLE
Kiểm tra module news

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2976]
Hiện tại trong quản trị, link ajax không truyền biến lang, do đó lang khi thực hiện dựa vào cookie (lang lần cuối truy cập).   
Dẫn đến hiện tượng sau:

- Mở admin tiếng Việt
- Mở tiếp admin tiếng Anh trong tab mới
- Quay lại tab admin tiếng Việt click chọn tất cả các bài viết và xóa
- Kết quả hệ thống không xóa bài viết tiếng Việt mà xóa hết bài viết tiếng Anh

**Comment by htuyen1994** [comment]
Giao Nam học việc xử lý

**Comment by hoaquynhtim99** [comment]
Sửa vào js của news. Trường xử lý

**Comment by hoaquynhtim99** [comment]
Đã xong
