### ISSUE TITLE
Cập nhật code google analytics mới

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#2981]
Hiện tại Google đã thay đổi code thống kê: Google analytics.
Vậy mong đội code hướng dẫn giúp để cập nhật mã mới này. Cảm ơn nhiều!

**Comment by hoaquynhtim99** [comment]
@truongemcom chắc bạn nói cái mới là googletagmanager phải không?

**Comment by truongemcom** [comment]
đúng rồi, google nó chuyển sang gtag.js rồi

**Comment by hoaquynhtim99** [comment]
```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxxx-y"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-xxxx-y');
</script>
```

**Comment by truongemcom** [comment]
ý là trong code NukeViet vẫn còn là bản cũ, sửa ở file nào để cập nhật cái mới này vào đó bạn ơi!
