### ISSUE TITLE
HELP! Lỗi unexpected 'self' (T_STRING) trong file config_ini

### ISSUE THREAD

**Issue by nguyennamha** [nukeviet/nukeviet#2988]
Cho mình hỏi cách sửa lỗi trong file **config_ini.yourdomain.com**.  Trang web mình chạy mới rồi bị trắng trang, mình kiểm tra nó hiển thị lỗi 

`syntax error, unexpected 'self' (T_STRING), expecting ')'`

Lỗi đó ở trong file **config_ini.yourdomain.com** thể hiện ở phần nháy đơn  **'self'** đoạn **'content-security-policy'=>'frame-ancestors 'self'.**

`$sys_info['server_headers'] = array('server'=>'nginx','content-type'=>'text/html; charset=UTF-8','x-f-cache'=>'BYPASS','x-signature'=>'FASTIS','x-xss-protection'=>'1; mode=block','x-frame-options'=>'SAMEORIGIN','x-content-type-options'=>'nosniff','content-security-policy'=>'frame-ancestors 'self';','content-encoding'=>'br');`

mình sửa ngay trong file thành nháy kép **"self"** , nhưng chỉ chạy được vài ngày nó lại trở về nháy đơn -> gây lỗi trang.

Vậy mình hỏi cách khắc phục ở file nào nhỉ? thanks.

Bản mình đang dùng là 4.3.02

**Comment by hoaquynhtim99** [comment]
Bạn tạo 1 file nội dung 

```php
<?php

echo "<pre><code>";
echo addslashes("frame-ancestors 'self';");

```

Đặt vào thư mục gốc của site rồi chạy http://domain.com/filename.php xem kết quả ra sao.
Nếu có thể gửi giúp thông tin qua https://www.facebook.com/tandungcoder mình check trực tiếp thử

**Comment by nguyennamha** [comment]
Mình đã update lên bản mới nhất **4.4.02** nên ko còn bị lỗi như trên nữa. Bắt đầu từ bản **4.3.08** mình thấy đã khắc phục được lỗi này, 

`frame-ancestors \'self\';`

**Comment by hoaquynhtim99** [comment]
👍
