### ISSUE TITLE
Lỗi đường dẫn page-2~

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#2990]
Hiện tại NukeViet đang bị lỗi đường dẫn page khiến mọi liên kết đều chạy nhưng chỉ hiện về trang chủ. 
Điều này thật quá nguy hiểm khi trình tìm kiếm index, nó cho rằng cả triệu liên kết khác nhau đều trỏ về một trang.
ví dụ: https://nukeviet.vn/vi/news/page-2/
page chạy từ 2 đến vô cùng. Mọi site NukeViet đều dính lỗi này.
Mong đội code đưa ra phương án khắc phục gấp. Cảm ơn!

**Comment by hoaquynhtim99** [comment]
Cái này mình nghĩ cũng không có gì quá gấp, liên kết đó bạn tự đánh thì nó mới có chứ thực tế không tồn tại trên website
Google chỉ index vào các liên kết có trên site chứ đâu tự nghĩ ra liên kết rồi index

**Comment by hoaquynhtim99** [comment]
Thử 1 vài site nhé:
https://zingnews.vn/tin-tuc-xuat-ban.html/page-10/
https://zingnews.vn/tin-tuc-xuat-ban.html/page-11/
https://zingnews.vn/tin-tuc-xuat-ban.html/page-100/
https://zingnews.vn/tin-tuc-xuat-ban.html/page-10/check1/xxxxx/
https://vnexpress.net/giai-tri/gioi-sao-p200
https://vnexpress.net/giai-tri/gioi-sao-p201
https://vnexpress.net/giai-tri/gioi-sao-p200111111111111111111111
........
Site nào nó cũng thế thôi, cái này không nhất thiết và cũng rất khó để kiểm soát

**Comment by hoaquynhtim99** [comment]
Hơn nữa cái này cũng chả khác gì việc bạn điền
https://www.facebook.com/nukeviet/?module=nukeviet
https://www.facebook.com/nukeviet/?module=tui
https://www.facebook.com/nukeviet/?module=ong
https://www.facebook.com/nukeviet/?module=ban

**Comment by truongemcom** [comment]
> Cái này mình nghĩ cũng không có gì quá gấp, liên kết đó bạn tự đánh thì nó mới có chứ thực tế không tồn tại trên website
> Google chỉ index vào các liên kết có trên site chứ đâu tự nghĩ ra liên kết rồi index

Nếu google không index thì mình cũng ko đưa lên đây làm gì.

**Comment by hoaquynhtim99** [comment]
Google index thì gỡ tạm thời hoặc dùng htaccess chuyển hướng 404 not found các liên kết đó http://api.writeblabla.com/blog/su-dung-htaccess-de-chuyen-huong-cac-lien-ket-loi.html
