### ISSUE TITLE
Lỗi ghi file config.ini module news

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#2993]
Chức năng cấu hình khối quảng cáo bên trên và bên dưới chuyên mục của news làm file config.ini của giao diện được thay đổi.
Tuy nhiên khi ghi lại thì nội dung text bị mã hóa ví dụ `Giao di&#x1EC7;n B&#xEC;nh Ph&#x1B0;&#x1EDB;c V2`

**Comment by quocdatit** [comment]
Em mới tạo PR cho issue này #3006

**Comment by quocdatit** [comment]
Tham khảo: https://stackoverflow.com/questions/18039765/php-not-have-a-function-for-xml-safe-entity-decode-not-have-some-xml-entity-dec
