### ISSUE TITLE
Vấn đề với tìm kiếm

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#2998]
Khi tìm kiếm một từ khóa trong module seek
Nếu cho ra nhiều kết quả được phân trang (ví dụ: 3 trang)
Nhưng nếu bấm thêm số trang (>3) thì liên kết vẫn chạy, nhưng lại cho ra kết quả không tìm thấy. 
Đáng lẽ ra phải thông báo là số trang không hợp lệ hoặc báo lỗi 404.
_* Note: Hình như code NukeViet đang bị người ta tìm mọi cách phá phách, truy vào các lỗ hổng bảo mật, SEO,..._

**Comment by vuthao** [comment]
@truongemcom cho demo ví dụ cụ thể nhé, mình thử trên trang NukeViet.vn không bị lỗi đó.

**Comment by truongemcom** [comment]
demo: https://nukeviet.vn/vi/seek/?q=nukeviet&m=news&page=35
Không chỉ là seek mà tất cả các category, và các module khác đều bị như vậy. 
Nếu ai đó cố tình đánh thêm số page không nằm trong CSDL thì sẽ thông báo 404.

**Comment by hoaquynhtim99** [comment]
Cái này chưa có kiểm soát sẽ sửa, nhưng cũng không đáng lo ngại.

- Query string không có tác động đến SEO như thế, bạn dùng robot để chặn toàn bộ module tìm kiếm là xong, không ai SEO link tìm kiếm cả.
- Đây cũng không phải lỗ hổng bảo mật.

Cái này tìm ra thì tốt, để sửa có gì đâu phá phách 🤣🤣🤣

**Comment by truongemcom** [comment]
nó bơm link kiểu này
![bkt](https://user-images.githubusercontent.com/12554922/95477204-4a481a00-09b2-11eb-846c-3f090a1675c9.jpg)
thấy có ổn ko?
bên WP nếu tự thêm page ko có trong CSDL sẽ báo OOP! 404 ngay.

**Comment by hoaquynhtim99** [comment]
@truongemcom vấn đề này đã fix ở https://github.com/nukeviet/nukeviet/commit/cdc8ad08c75141f41097bc6266166df7284d3010
