### ISSUE TITLE
Error: Cách khai báo array{} không còn dùng được sau khi update php version 7.4

### ISSUE THREAD

**Issue by HQuang** [nukeviet/nukeviet#3001]
Trong admin:
Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /includes/functions.php on line 331
Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /includes/functions.php on line 334
Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /includes/functions.php on line 379
Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /includes/functions.php on line 382
Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /vendor/vinades/nukeviet/Core/Encryption.php on line 28
Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /vendor/vinades/nukeviet/Core/Encryption.php on line 32

Ngoài site:
Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /includes/functions.php on line 331
Nên chú ý Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /includes/functions.php on line 334
Nên chú ý Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /includes/functions.php on line 379
Nên chú ý Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /includes/functions.php on line 382
Nên chú ý Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /includes/request_uri.php on line 65
Nên chú ý Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /includes/request_uri.php on line 68
Nên chú ý Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /includes/request_uri.php on line 72
Nên chú ý Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /includes/request_uri.php on line 75
Nên chú ý Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /vendor/vinades/nukeviet/Core/Encryption.php on line 28
Nên chú ý Nên chú ý: Array and string offset access syntax with curly braces is deprecated in file /vendor/vinades/nukeviet/Core/Encryption.php on line 32

**Comment by vuthao** [comment]
@HQuang kiểm tra lại  phiên bản nhé, chứ bản NukeViet 4.4 

https://github.com/nukeviet/nukeviet/blob/nukeviet4.4/includes/functions.php#L331

Không dùng đến array

**Comment by HQuang** [comment]
@vuthao ok anh, em vừa check lại đang xài NukeViet bản cũ.
