### ISSUE TITLE
Lỗi phân trang trong quản trị news

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3004]
Khi tìm kiếm trạng thái bài viết "Ngưng hiệu lực" được 4 trang, ấn qua trang 4 thì mất điều kiện tìm kiếm.

> Check xem các điều kiện khác có mất hay không

**Comment by htuyen1994** [comment]
Giao Nam học việc xử lý

**Comment by hoaquynhtim99** [comment]
Trường xử lý
