### ISSUE TITLE
Cho phép tạo thư mục trong folder admin của 1 module

### ISSUE THREAD

**Issue by nhoxbin** [nukeviet/nukeviet#3010]
Hiện tại thì khi lập trình, trong folder admin của 1 module nếu nhiều chức năng thì sẽ có rất nhiều file sẽ rất khó quản lý... nếu tạo folder và quản lý các chức năng này thì rất hay.
`$allow_func = [
   'main',
   ['<tên thư mục>' => '<tên file>']
];`
cứ có 1 thư mục là 1 mảng
url thì kết hợp folder với function luôn.
ví dụ: del/cat.php => op=delcat
hợp lệ ko nhỉ?

**Comment by hoaquynhtim99** [comment]
Mình nghĩ cái này không cần thiết, chưa thấy module nào mà khủng tới nhiều chức năng tới mức mà quá nhiều file không quản lý được bạn.

Còn tổ chức menu cho gọn thì đã có chức năng, bạn tham khảo module shops
