### ISSUE TITLE
Module News: Thêm cấu hình bài viết hiển thị trên di động

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#3020]
Hiện tại mặc định số bài viết hiển thị được quy định cho cả desktop và mobile.
Tuy nhiên để tối ưu tốc độ trên di động ta cần tách biệt hai phần này ra:
**Thêm tuỳ chọn hiển thị bài viết trên di động**
- Số bài viết được hiển thị cùng với phần giới thiệu ngắn gọn trên một trang: ...
- Số bài viết chỉ hiển thị link: ...
Cảm ơn!

**Comment by hoaquynhtim99** [comment]
Như trên group đã hướng dẫn có nhiều cách bạn:

- Dùng 2 giao diện cho mobile và destop để hiển thị, bỏ hiển thị
- CSS tùy ý để ẩn/hiện các thành phần

Cái này không đưa vào core

**Comment by truongemcom** [comment]
Bỏ hiển thị thì dễ rồi, tuy nhiên trong truy vấn SQL nó vẫn chạy lệnh.
Do đó để tối ưu tốc độ trên mobile thì cần có thêm lựa chọn này.

**Comment by hoaquynhtim99** [comment]
Tối ưu tốc độ trên mobile không phải cấu hình bỏ cái đó là tối ưu bạn ơi. 1 2 câu lệnh đó không làm chậm máy chủ đâu. Bạn cần tối ưu cỡ đó thì phải có kiến thức:
- Tối ưu câu lệnh => Module news đã được thiết kế để tối ưu câu lệnh truy vấn
- Nếu muốn nhanh hơn hãy sử dụng các mod cache, module news là dạng read nhiều do đó mod cache trên hosting, server là giải pháp hợp lý.
- Nếu dữ liệu lớn quá lớn hãy thiết kế một hệ thống cân bằng tải

**Comment by truongemcom** [comment]
Với một vài người truy cập thì chẳng vấn đề, nhưng có trên cả ngàn người truy cập cùng lúc thì vấn đề tốn tài nguyên CPU chắc chắn sẽ xảy ra.
- Vì sao PageSpeed trên desktop: 90 mà trên mobile: 30 => Vấn đề này có lẽ nằm ở những lệnh thừa trong code.
