### ISSUE TITLE
Thêm cấu hình Rating

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#3021]
Trong module news rating hiện đang fix cứng, do vậy cần có thêm lựa chọn cấu hình rating: Cho phép đánh giá hoặc không.

**Comment by hoaquynhtim99** [comment]
Module news trước giờ có cấu hình bật tắt cái đó rồi

![2021-01-19_19-30-15](https://user-images.githubusercontent.com/2421714/105034949-d9be9800-5a8c-11eb-879b-10fcf67aecbe.jpg)

**Comment by hoaquynhtim99** [comment]
![2021-01-19_19-30-15](https://user-images.githubusercontent.com/2421714/105035043-fb1f8400-5a8c-11eb-90d1-78b7ff3bbd1a.jpg)

Trước giờ nó có cấu hình đó rồi

**Comment by truongemcom** [comment]
Đây là cấu hình cho từng bài viết riêng lẻ, không phải cấu hình cho module

**Comment by inngochuong** [comment]
Phần đánh giá * này có hiển thị ra google không admin

**Comment by thehung** [comment]
Có đó bạn!
