### ISSUE TITLE
Phân quyền quản trị cho người điều hành module

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#306]
Module chung cơ sở dữ liệu ngôn ngữ nhưng khi Phân quyền quản trị cho người điều hành module ở 1 ngôn ngữ thì sang ngôn ngữ khác người ta không nhìn thấy gì.

**Comment by hoaquynhtim99** [comment]
Trên NukeViet 4.6 hiện giờ khi thêm quản trị đã có thể phân quyền toàn bộ các ngôn ngữ
