### ISSUE TITLE
Cơ chế xác định canonical của NukeViet

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#3064]
Hiện tại canonical tự động đặt bằng `$client_info['selfurl']` nếu không khai báo. Điều này làm sinh ra rất nhiều URL "ảo" ảnh hưởng đến SEO. Ví dụ

https://dauthau.asia/view/?id=837546&content=1

```
<link rel="canonical" href="https://dauthau.asia/view/?id=837546&content=1">
```

https://dauthau.asia/listprequalification/?type_search=2&dungpt=1

```
<link rel="canonical" href="https://dauthau.asia/listprequalification/?type_search=2&dungpt=1">
```

Cần sửa lại:

- Bỏ xác định tự động canonicalUrl theo $client_info['selfurl']
- Nếu site có nhiều domain từ mới kích hoạt việc gán  $canonicalUrl = str_replace(NV_MY_DOMAIN . '/', NV_MAIN_DOMAIN . '/', $client_info['selfurl']);
- phân trang sẽ xử lý như hướng dẫn ở: https://www.searchenginejournal.com/technical-seo/pagination/
```
One pagination tag on the root page, pointing to the next page in series.
<link rel="next" href="https://www.example.com/category?page=2″>
<link rel="canonical" href="https://www.example.com/category">

Two pagination tags on page 2.
<link rel="prev" href="https://www.example.com/category">
<link rel="next" href="https://www.example.com/category?page=3″>
<link rel="canonical" href="https://www.example.com/category?page=2">

Two pagination tags on page 3.
<link rel="prev" href="https://www.example.com/category?page=2″>
<link rel="next" href="https://www.example.com/category?page=4″>
<link rel="canonical" href="https://www.example.com/category?page=3">

One pagination tag on page 4, the last page in the paginated series.
<link rel="prev" href="https://www.example.com/category?page=3">
<link rel="canonical" href="https://www.example.com/category?page=4"> (edited) 
```

Ngoài ra cũng cần kiểm tra lại cái phân trang của các module ở bên ngoài site. Hiện có thể đặt tùy ý số page, news ...
```
https://nukeviet.vn/vi/news/Tin-tuc/page-14000/
https://nukeviet.vn/vi/news/Tin-tuc/page-14001/
https://nukeviet.vn/vi/news/Tin-tuc/page-14002/
https://nukeviet.vn/vi/news/Tin-tuc/page-14003/
https://nukeviet.vn/vi/news/Tin-tuc/page-99999999999999999999999999999999999999999999/
```

Rà soát từng function của các module để khai báo canonicalUrl và kiểm soát việc đặt url tùy ý. Kết hợp hai cái này sẽ tối ưu cho SEO. Cần ưu tiên đặt canonicalUrl hơn. 

Ưu tiên cho các module public hơn rồi mới đến các module đang để no-index (comment, freecontent, banner, menu, statistics, users, two-step-verification)

Việc kiểm soát việc đặt url tùy ý thường chỉ kiểm soát phần `path` của url (tương tự như khi xem chi tiết bản tin module news) và phần query cần để tùy ý.

Tránh trường hợp kiểm soát quá chặt dẫn đến hoạt động bất thường ví dụ khi share bản tin lên facebook thì ấn vào link đó phần query sẽ thêm đoạn

```
?utm_source=facebook&utm_medium=cpm&utm_campaign=
```

Nếu kiểm soát quá chặt thì nó sẽ không thể hoạt động được. Điều này module news đã gặp phải

**Comment by anhtunguyen** [comment]
OK. Anh sẽ làm cái này
