### ISSUE TITLE
Tách các static file của website sang hosting khác

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#3072]
Hiện tại các file static của website đang nằm cùng trên một host

với các site nhở không sao, các site cần tác ra để giảm tải sẽ khó khăn. (có thể sửa dụng CDN, nhưng CDN  nhiều lúc vẫn vào hosting chính)

Đề xuất thêm 1 cấy hình NV_STATIC_URL (có thể thêm vào file config.php hoặc cấu  hình trong admin vào file data/config/config_global.php) là url của host static file, nếu biến này không định nghĩa thì được gán bằng NV_BASE_SITEURL

Sau đó sửa lại đường dẫn đến các file này.

**Comment by tmsholdings** [comment]
Anh Thảo với Anh Tú cho em hỏi thêm vấn đề này chút.
Nukeviet mình  tương lai có tách luôn host chứa data hình ảnh luôn không anh.
2 anh có thể gợi ý cơ chế cho em mò vọc trước được không ạ
em thấy tách host static file đã thấy khá ổn rồi ạ

**Comment by anhtunguyen** [comment]
Host static files có thể hiểu là host chứa các file tĩnh, không chỉnh sửa trong suốt quá trình vận hành site (files hình ảnh, js, css, fonts ...). Trong phiên bản sắp tới của NukeViet sẽ có thêm tính năng này.
Nếu bạn không muốn đợi, có thể tự nâng cấp thủ công theo như ở đây:
https://github.com/nukeviet/nukeviet/pull/3076/commits/3762b6c2298da5a14d1cc8f4b1d1bcc67ef2f45c
và ở đây:
https://github.com/nukeviet/nukeviet/commit/fd704504a8e9ca77193b343a6ec4d352e54090a5

[Lưu ý về host chứa các file tĩnh](https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.5#m%C3%A1y-ch%E1%BB%A7-ch%E1%BB%A9a-c%C3%A1c-t%E1%BB%87p-t%C4%A9nh)

**Comment by tmsholdings** [comment]
Dạ cảm ơn anh Tú,
Em có tải bản này về đã thấy và sử dụng chức năng Host static files  rồi ạ, em thấy hoạt động rất tốt
Do 1 số hệ thống site lớn, ngoài cdn ra em thấy họ tách luôn server chứa hình ảnh video của website nên em mới hỏi xem thử ạ.
Em cũng đang xử lý 1 website lớn nên muốn hỏi anh xem có phương án tách luôn hosting chứa hình ảnh , video, files  trong quá trình mình up tin, sản phẩm không ạ. Được thì anh cho em xin định hướng em thử mò thêm ạ
cảm ơn anh

**Comment by anhtunguyen** [comment]
@vuthao

**Comment by vuthao** [comment]
@tmsholdings cái này là do các ứng dụng quyết định thôi. 

Với kiến trúc của module NukeVeit 4 hiện tại việc xử lý tất cả các module không được, do cách code ban đầu luôn kiểm tra file có tồn tại trước khi hiển thị. Các module mặc định hiện tại chưa có kế hoạch tách nó ra bạn.

Còn các module viết mới vinades đã tách nó ra khỏi server

Ví dụ: 

https://igiaoduc.vn/Bai-19-Duong-giao-thong-l1229.html?w=1507

https://dauthau.net/vi/dau-thau/tbmt/Thu-moi-chao-gia-du-an-Thi-cong-he-thong-thoat-nuoc-mua-nuoc-thai-duong-N1-D4-Khu-cong-nghiep-Viet-Phat-tai-huyen-Thu-Thua-tinh-Long-An-TB210317733-01.html

Đã tách file server ra khỏi hosting chứa website, sau đó dùng CDN cho cả  file server

**Comment by tmsholdings** [comment]
Cái này đúng là em đang cần ạ,
anh có đoạn code để  up bài, hình ảnh cho sang server khác hoặc có module nào cùi cùi cho em xin về em học hỏi và chuyển cho cho các module cơ bản được không ạ.
Do em chưa định hướng được mình cần can thiệp thế nào để kết nối được dữ liệu và up được dữ liệu qua server khác.
Cảm ơn anh Thảo

**Comment by vuthao** [comment]
Cái này mình cần dựng fileserrver riêng, quản lý khá phức tạp.

cách đơn giản  bạn xem dùng dịch vụ S3 của Amazone Web Service nhé. Sau đó sẽ phải sửa lại code phần lưu trữ URL file và các cái xử lý ảnh thumb nếu có.
