### ISSUE TITLE
Vấn đề nhận mã màu ở class Request

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3073]
Hiện tại class Request đang xử lý attr dạng mã màu hex để chuyển thành RGB https://github.com/nukeviet/nukeviet/blob/c2292b39cfae4b7ba44876a0b76e26020927c8ad/vendor/vinades/nukeviet/Core/Request.php#L756

Tuy nhiên việc này xung đột khi sử dụng tính năng chèn điểm neo trong trình soạn thảo. Ví dụ mã HTML

```html
<a href="#b2b">Business To Business</a>
```

Khi submit nó ra

```html
<a href="rgb(11,%202,%2011);">Business To Business</a>
```

@anhtunguyen anh xem giúp em cái này với.

**Comment by anhtunguyen** [comment]
OK
