### ISSUE TITLE
Cải tiến module news

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3078]
- [x] Bổ sung bộ lọc thông tin theo thời gian & theo người đăng, theo tác giả.
- [x] Phần quản lý tin tức trong Admin Control Panel, sửa cột "Người tạo" thành "Tác giả"
- [x] Trong bài viết để mặc định tác giả là người đăng (có thể chọn 1 hoặc nhiều tác giả là users), khi đăng/ sửa có thể xóa đi và chọn tác giả là thành viên khác hoặc những cái tên tự điền (text).
- [x] Check lại phần xem ngoài site chỉ hiển thị bài theo thành viên => chỉ hiển thị khi thành viên đó là tác giả (trước là liệt kê hết bài theo người đăng). Tất cả bài của khách khi xem ngoài site thì đưa về 1 danh sách.

**Comment by hoaquynhtim99** [comment]
#416

**Comment by hoaquynhtim99** [comment]
Yêu cầu trên NukeViet 4.5.01:

Hiện vẫn chưa thấy lọc bài viết theo thời gian.

**Comment by ngoclam99** [comment]
@hoaquynhtim99
