### ISSUE TITLE
Lỗi không xem được danh mục bài viết theo Tag ở module News

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3082]
Hiện tại code mới nhất ở nhánh nukeviet4.5 đã thêm trường title cho  tag tuy nhiên ngoài site chưa lập trình để sử dụng biến này dẫn tới trang chi tiết tag không chạy được. Cần sửa modules\news\funcs\tag.php:

- Bỏ kiểm tra `if (!empty($page_title) and $page_title == strip_punctuation($page_title)) {`
- `$page_title` không phải lấy `$page_title = trim(str_replace('-', ' ', $alias));` nữa mà lấy từ title của tag

**Comment by hoaquynhtim99** [comment]
Ngoài ra đoạn này

```
        $base_url_rewrite = nv_url_rewrite($base_url_rewrite, true);
        $base_url_check = str_replace('&amp;', '&', $base_url_rewrite);
        if (strpos($_SERVER['REQUEST_URI'], $base_url_check) !== 0 and strpos(NV_MY_DOMAIN . $_SERVER['REQUEST_URI'], $base_url_check) !== 0) {
            nv_redirect_location($base_url_check);
        }
        $canonicalUrl = NV_MAIN_DOMAIN . $base_url_rewrite;
```

Không chạy được do hàm strpos không hỗ trợ UTF-8

**Comment by anhtunguyen** [comment]
Không phải do hàm strpos không hỗ trợ UTF-8 mà là so sánh 1 chuỗi ký tự unicode đã mã hóa (rawurlencode) và một chuỗi chưa khiến cho kết quả luôn là false.
