### ISSUE TITLE
Tích hợp bootstrap 5 vào NukeViet

### ISSUE THREAD

**Issue by anhtunguyen** [nukeviet/nukeviet#3085]
**Tại sao nên tích hợp Bootstrap 5**
NukeViet hiện đang sử dụng Bootstrap 3 trong thiết kế giao diện. Nó hỗ trợ IE 8-9. Thế nhưng giờ đây trình duyệt IE đã không còn được hỗ trợ, dẫn đến bootstrap 3 cũng không còn là lựa chọn tối ưu. Bootstrap 3 đã ngừng phát triển từ tháng 8/2017, thay vào đó là Bootstrap 4 và sắp tới là Bootstrap 5 với các thành phần mới, biểu định kiểu nhanh hơn và phản ứng nhanh hơn. Chính vì vậy việc nâng cấp lên Bootstrap 5 là cần thiết.

**Phương pháp nâng cấp lên Bootstrap 5**
Ở Bootstrap 5 có rất nhiều các class dựng sẵn, đủ để thiết kế giao diện cho NukeViet mà không cần viết thêm. Vì vậy phương án tích hợp là:
- Lấy nguyên selectors mặc định của Bootstrap 5 làm chủ đạo (Không can thiệp sâu)
- Xóa các css viết riêng cho từng module (Vì trong Bootstrap 5 đã có phương án thay thế)
- Quản lý các css bằng SASS/SCSS
- Vẫn giữ nguyên 2 chế độ giao diện: responsive, non-responsive
- Bỏ chế độ grid 24, thay vào đó là 12
- Grid Tier mặc định là XXL (tương đương 1344px)

Việc tích hợp Bootstrap 5 đòi hỏi thay đổi rất nhiều files, không thích hợp cho việc nâng cấp tự động. Cho nên tốt nhất là tạo 1 nhánh phát triển mới.

Demo: https://nukeviet.gq/

Mọi người xem và cho ý kiến.

**Comment by hoaquynhtim99** [comment]
Ý kiến của em:

Em có thắc mắc là sao anh Tú lại cải tiến rất nhiều vào NukeViet4.5 trong khi đó không làm NukeViet 5 mặc dù kế hoạch của mình là làm bản 5, nukeviet 4 chỉ sửa những lỗi tồn đọng thôi
Nếu làm thêm nữa mình sẽ có nhiều nhánh long time support:

- NukeViet 4.2
- NukeViet 4.3
- NukeViet 4.4
- NukeViet 4.5
- Nhánh mới này
- Và tương lai là 5.x

==> Với nhân lực của mình sẽ quá tải.
==> Nên em nghĩ anh tạm dừng cải tiến thêm NukeViet 4 để chuyển sang NukeViet 5, cái Bootstrap 5 này cũng đưa vào NukeViet 5 luôn là hợp lý.

**Comment by vuthao** [comment]
Theo em các thay đổi này nên phát triển cho NukeViet 5, nhánh đang phát triển là nhánh develop: https://github.com/nukeviet/nukeviet/tree/develop

**Comment by anhtunguyen** [comment]
Anh không thấy nhánh NukeViet 5 đâu . Cho anh tiếp cận với nó cũng như đọc tài liệu về nó

**Comment by vuthao** [comment]
@anhtunguyen thông tin chung ở đây anh: 
https://nukeviet.vn/vi/news/nhom-phat-trien/ke-hoach-phat-trien-nukeviet-phien-ban-5-0-574.html

1. Kho code của NukeViet 5: https://github.com/nukeviet/nukeviet/tree/develop
2. Cấu trúc thư mục của kho code NukeViet 5: https://wiki.nukeviet.vn/nukeviet5:codex:directory-structure

**Comment by hoaquynhtim99** [comment]
@anhtunguyen nhánh NukeViet 5 là nhánh anh Thảo mới gửi: https://github.com/nukeviet/nukeviet/tree/develop

Hiện tại nó khá cũ so với những phát triển của NukeViet 4 nên việc đầu tiên là cần cập nhật nó ngang hàng với NukeViet 4.x trước.  
Sau đó kế hoạch phát triển như đây https://nukeviet.vn/vi/news/nhom-phat-trien/ke-hoach-phat-trien-nukeviet-phien-ban-5-0-574.html

Các tài liệu tạm có:
- Cài đặt tự động: https://wiki.nukeviet.vn/nukeviet5:codex:auto-test
- Hook https://wiki.nukeviet.vn/nukeviet5:codex:hooks-reference (build tự động từ tool https://github.com/nukeviet/nukeviet/tree/develop/tools/hooks)
- API https://wiki.nukeviet.vn/programming5:module:api có sự lỗi thời so với NukeViet 4.5 https://wiki.nukeviet.vn/programming4:api
- Giao diện trong admin cắt theo template https://vinades.org/nukeviet/theme-admin (Bootstrap 4 => Làm lại trên bản 5 càng hay)

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Việc cập nhật cho NukeViet 5 ngang hàng với NukeViet 4 hiện tại mà để anh làm sẽ rất lâu. Em đã quen với nó rồi nên cập nhật giúp nhé.

**Comment by hoaquynhtim99** [comment]
@anhtunguyen chắc cứ từ từ thôi anh. Em giờ không còn quỹ thời gian cho Core nữa nên mới dừng luôn từ bản 4.4.02 tới giờ chưa phát hành thêm bản mới theo đúng lịch.

**Comment by datdevs** [comment]
Hiện tại em có thể hỗ trợ team thiết kế hoặc cắt giao diện Admin Template, vì em đã làm việc với các framework, Admin Template, Bootstrap 5, có thể giảm thiểu việc sử dụng Jquery và chuyển sang Vanilla Js để tăng performance
