### ISSUE TITLE
Thông báo bảo trì website

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#3092]
Hiện tại website bảo trì vẫn trả về mã  200

Đúng ra cần trả  về mã 503
```php
http_response_code(503);
```

Ngoài ra cần bổ sung thời điểm bảo trì xong để các công cụ tìm kiếm không vào trong thời gian bảo trì, ví dụ
```php
header('Retry-After: '.gmdate('D, d M Y H:i:s', $timestamp).' GMT');
```

**Comment by vuthao** [comment]
Trong quá trình bảo trì website có thể sẽ phải Stop CSDL.

Khi Stop CSDL thì website báo lỗi CSDL chứ không còn vào được thông báo bảo trì.

Do đó nội dung thông báo bảo trì nên lưu xuống file, và ở ngoài site nên thông báo trước khi kết nối CSDL. Còn trong admin thì kiểm tra các trường hợp sau khi kết nối CSDL.

**Comment by anhtunguyen** [comment]
@vuthao Khi stop CSDL sẽ không xác minh admin được, cả trong admin-panel cũng không vô được. Cho nên, trong trường hợp này thông báo bảo trì sẽ hiện ở tất cả các khu vực
