### ISSUE TITLE
Lỗi quản lý module khi bật php 8.0

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3118]
Mình test bản nukeviet 4.5,  trên môi trường centos 8.0 xảy ra các hiện tượng cảnh báo như sau:

Nên chú ý: Required parameter $info_title follows optional parameter $page_title in file /includes/core/theme_functions.php on line 140
Nên chú ý: Required parameter $info_content follows optional parameter $page_title in file /includes/core/theme_functions.php on line 140
Lỗi vào thiết lập module không hiện thị module cần cài đặt, mặc dù đã up module mới lên

**Comment by anhtunguyen** [comment]
Chỗ này có 2 lỗi:

- Ở php v8.x không cho phép viết đối số không bắt buộc trước đối số bắt buộc trong khu vực khai báo các đối số của hàm, vì thế:
`function nv_info_die($page_title = '', $info_title, $info_content, $error_code = ...)`
 phải viết lại là:
`nv_info_die($page_title, $info_title, $info_content, $error_code = ...)`
- Nếu trước phiên bản 8.0 hàm in_array có đối số thứ 3 là $strict có giá trị mặc định là false thì giờ đây là true, vì thế việc so sánh trở nên chính xác hơn. Việc so sánh kiểu như: in_array('page', array('banners' => 0, 'comment' => '1', 'page' => 2)) trước kia cho kết quả là true thì giờ cho kết quả là false.
    Tôi đã fix lỗi này rồi, nhưng có thể còn ở chỗ khác . Nếu gặp, bạn tiếp tục thông báo nhé.

**Comment by tmsholdings** [comment]
cảm ơn anh, đã ổn ạ
