### ISSUE TITLE
Lỗi cấu hình Cấu hình cookie session

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3120]
Phiên bản nukeviet 4.5  admin/index.php?language=vi&nv=settings&op=variables
Không lưu được cấu hình  Cấu hình cookie session , tất cả trường đêu lưu không được
Đã thử php 7 hay php 8 đều không có tác dụng

**Comment by anhtunguyen** [comment]
Tôi thử và thấy OK. Bạn cần mô tả lỗi cụ thể hơn (Môi trường?)

**Comment by tmsholdings** [comment]
em đã tim ra lỗi, funtion nv_save_file_config_global    em xóa cái này đi thì lưu được   if ($global_config['idsite']) { return false; }
Chưa xác định nguyên do

**Comment by anhtunguyen** [comment]
Ở file /config.php tìm và sửa giá trị $global_config['idsite'] là 0
