### ISSUE TITLE
Bổ sung phiên bản php 8.0.6 và lỗi cảnh báo tin tức

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3121]
Hiện em dùng centos 8.0, sài phiên bản nukeviet 4.5 
Nay php đã có update  8.0.6 nhưng phiên bản hiện nukeviet 4.5 tại hỗ trợ 8.0.5 liệu rằng em sửa php cài đặt  $sys_info['php_allowed_max'] = '8.0.10'; có vấn đề gì không anh.
Ngoài ra module tin tức khi chạy trên php 8.0.6 phát sinh cảnh báo 
Nên chú ý: Required parameter $nv_redirect follows optional parameter $msg1 in file /modules/news/admin.functions.php on line 706

**Comment by anhtunguyen** [comment]
Cảm ơn bạn. Tôi đã fix lỗi "Required parameter $nv_redirect follows optional parameter $msg1 in file /modules/news/admin.functions.php on line 706" rồi (Theo quy định mới của php8.x thì đối số bắt buộc trong khai báo hàm không thể nằm sau đối số không bắt buộc).
OK `$sys_info['php_allowed_max'] = '8.0.10';`
