### ISSUE TITLE
Hiển thị thời gian không đồng nhất giữa các khu vực ngoài site module tin tức

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3134]
Trang chính tin tức, trang chi tiết dạng: 09/11/2017 15:25   
Trang xem theo thể loại (danh sách): 04/08/2017 04:07:00 PM

**Comment by hapro574** [comment]
Đang sửa lỗi

**Comment by anhtunguyen** [comment]
@hapro574 Cần sửa ở nhánh 4.5
