### ISSUE TITLE
Bug: Khi tìm kiếm thì bị lỗi

### ISSUE THREAD

**Issue by daiubqn113** [nukeviet/nukeviet#3209]
**Mô tả lỗi**
Không tìm kiếm được 

**Thao tác dẫn đến lỗi**
Các bước để thấy lỗi:
1. Đi tới trang chủ
2. Nhấp vào thanh tìm kiếm nhập 1 từ bất kỳ rồi ấn enter nó sẽ hiện lỗi

**Kết quả mong đợi**
Khi nhập thông tin tìm kiếm, nó sẽ hiển thị tất cả những gì mình đang tìm kiếm

**Máy tính để bàn (vui lòng điền đầy đủ thông tin sau):**
  - Hệ điều hành: Windows
  - Trình duyệt chrome

**Comment by hoaquynhtim99** [comment]
Mô tả thêm lỗi:

```
This page isn’t working
ERR_TOO_MANY_REDIRECTS
```

**Comment by anhtunguyen** [comment]
@daiubqn113 Thank you for reporting the error!
Bạn cập nhật code như [ở đây](https://github.com/nukeviet/nukeviet/commit/0c998604a6d77ac4251c094a5bbaec048fc5c8d4#diff-1c08b27bcf43583c75cbc442bc401638be3427586fe544f3389e22c9979fa1af)
và kiểm tra lại xem còn lỗi này không nhé

**Comment by daiubqn113** [comment]
@anhtunguyen Vâng em đã cập nhật và dùng được rồi anh ạ. Em cảm ơn
