### ISSUE TITLE
PDF.js làm việc không ổn định

### ISSUE THREAD

**Issue by anhtunguyen** [nukeviet/nukeviet#3211]
Khi file đính kèm bản tin là PDF có dung lượng tương đối lớn (Từ 2 trang trở lên), tool xem trước lúc báo lỗi, lúc không. Nói chung làm việc không ổn định.

Hướng giả quyết: Thay pdf.js bằng Google Docs Viewer - Công cụ trực tuyến xem được nhiều loại file như pdf, doc, docx, ppt, txt ...

**Comment by hoaquynhtim99** [comment]
Em thấy Google Docs Viewer nó càng không ổn định anh. Thực tế bên mình support rất cực và hiện tại đội support đã hướng dẫn khách upload lên Drive để lấy iframe link.

Ngoài ra Google Docs Viewer không xem offline được. PDF.js em cũng chưa gặp tình trạng báo lỗi với dung lượng lớn
