### ISSUE TITLE
Site tự redirect 

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3215]
NukeViet 4.5 cài mới có đa ngôn ngữ, khi vào trang chủ (chỉ gõ domain) thì bị redirect về url `/vi/news/`

**Comment by hoaquynhtim99** [comment]
@vuthao @anhtunguyen em thấy http://v45.nukeviet4.my/ nó vẫn bị redirect về http://v45.nukeviet4.my/vi/

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 em kiểm tra trên môi trường đa ngôn ngữ à?

**Comment by hoaquynhtim99** [comment]
@anhtunguyen dạ vâng anh, đa ngôn ngữ.
