### ISSUE TITLE
Nâng cấp tìm kiếm module new

### ISSUE THREAD

**Issue by dinhthi080599** [nukeviet/nukeviet#3219]
Ở module new > function tìm kiếm mới hiển thị kết quả mặc định gồm tiêu đề và giới thiệu ngắn gọn.  
Nếu hiển thị sẵn nội dung người dùng tìm kiếm ra ngoài sẽ không phải vào xem chi tiết nữa.  

![image](https://user-images.githubusercontent.com/35556936/122541518-e6ebad00-d053-11eb-8a6f-882fe2a42f17.png)

**Comment by thehung** [comment]
Lúc đó kết quả tìm kiếm em sẽ trình bày thế nào?

**Comment by dinhthi080599** [comment]
Em nghĩ thay vì hiển thị đoạn mô tả ngắn gọn thì sẽ hiển thị **trích đoạn** bao gồm từ **khóa tìm kiếm** sẽ tiện lợi hơn cho người dùng ạ.

**Comment by thehung** [comment]
Thế thì hay quá, như Google. Nhưng khi truy vấn vào CSDL lớn liệu có sợ làm chậm CSDL không?

**Comment by dinhthi080599** [comment]
Ở đây mình phải truy vấn sẵn vào trường nội dung để lấy dữ liệu rồi.
Nên em nghĩ sẽ không ảnh hưởng nhiều đến tốc độ đâu anh ạ.

**Comment by anhtunguyen** [comment]
@dinhthi080599 Ý kiến của bạn cũng tương tự như trong module seek
[Ví dụ](http://nukeviet.online/vi/seek/?q=th%E1%BB%AD+nghi%E1%BB%87m&m=news)
OK. Tôi sẽ fix như ý kiến của bạn.

**Comment by anhtunguyen** [comment]
@dinhthi080599 Tôi đã nâng cấp. Bạn kiểm tra xem OK chưa nhé

**Comment by thehung** [comment]
À mà cái này là chỉ cần sửa cho phần tìm kiếm trong module news chứ module tìm kiếm chung ngoài site đã như thế rồi :D
