### ISSUE TITLE
Lỗi Bình luận nukeviet 4.5

### ISSUE THREAD

**Issue by anvhceo** [nukeviet/nukeviet#3220]
![image](https://user-images.githubusercontent.com/72913760/122629814-fe757500-d0e9-11eb-9214-c6e637972b54.png)
cụ thể mình vào bài viết để bình luận thì nó báo là ( Nội dung không được để trống. )

**Comment by anhtunguyen** [comment]
OK. Cảm ơn bạn báo lỗi!
Lỗi này xuất hiện khi bật trình soạn thảo và đã đăng nhập thành viên.
Tôi sẽ fix nó.

**Comment by anvhceo** [comment]
![image](https://user-images.githubusercontent.com/72913760/122631316-4352d900-d0f5-11eb-9b74-ddb666e99307.png)
admin bình luận 
![image](https://user-images.githubusercontent.com/72913760/122631327-54034f00-d0f5-11eb-95c7-013a14525404.png)
bên này thành viên vẫn k thấy ( phải bấm f5 lại mới hiện ) 
![image](https://user-images.githubusercontent.com/72913760/122631341-68dfe280-d0f5-11eb-8907-2a19870773f5.png)
không rõ vấn đề này bị sao nhỉ

**Comment by anhtunguyen** [comment]
Việc tự động cập nhật khi có comment mới nằm ngoài dự tính của module này bạn.

**Comment by anhtunguyen** [comment]
@anvhceo Tôi đã fix. Bạn kiểm tra xem OK chưa nhé

**Comment by anvhceo** [comment]
> @anvhceo Tôi đã fix. Bạn kiểm tra xem OK chưa nhé

mình tải nukeviet 4.5 về cài đặt lại hay sao bạn

**Comment by anvhceo** [comment]
> Việc tự động cập nhật khi có comment mới nằm ngoài dự tính của module này bạn.

mình nghĩ nên xử lý việc này luôn thì quá tốt ( đó với module news đã làm trang tin tức báo chí - tin tức khối nhà nước họ cần dc cập nhật tức thời các bình luận ( chứ không lẽ mỗi lần vào hay tv vào cmt thì bấm f5 hay sao bạn )

**Comment by hoaquynhtim99** [comment]
Cái này là ghi lại thông tin nhận xét của 1 bài báo chứ đâu phải khung chat đâu mà cần cập nhật realtime bình luận 🙄

**Comment by anvhceo** [comment]
![image](https://user-images.githubusercontent.com/72913760/125150138-a02b3780-e167-11eb-9510-8255af1ff3c4.pdng)
dù mình tải bản mới https://github.com/nukeviet/nukeviet/archive/refs/heads/nukeviet4.5.zip như vẫn lỗi trên
