### ISSUE TITLE
Cảnh báo của Google Chrome về header

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3229]
Em thấy có cảnh báo thế này ở bản 4.5

```
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
```

Không có kinh nghiệm lắm nên các anh xem xét thử có cần quan tâm không hay hệ nó

**Comment by anhtunguyen** [comment]
Cái này lên quan đến FLoC - công nghệ theo dõi và thu thập thông tin cá nhân KHÔNG thông qua phương pháp truyền thống là cookie của bên thứ 3, đang được Google phát triển. Công nghệ này đang trong giai đoạn thử nghiệm và gây tranh cãi lớn giữa Google và các nhà quảng cáo. Tất cả các trình duyệt hiện đại hỗ trợ header interest-cohort=() ngoại trừ Chrome - con đẻ của Google. Có thể tham khảo [tại đây](https://trainghiemso.vn/google-floc/).
Việc chấp nhận FLoC hay không đến giờ vẫn chưa ngã ngũ. Cho nên tạm thời chặn và bỏ qua cảnh báo của của trình duyệt Chrome.
