### ISSUE TITLE
Thêm phương án cấu hình page title

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3233]
Tại /admin/index.php?language=vi&nv=seotools&op=pagetitle

Đang chấp nhận các biến 

```
- pagetitle: Tiêu đề trang được xác định trong từng trường hợp cụ thể,
- funcname: Tên function,
- modulename: Tên module,
- sitename: Tên của site
```

funcname đang lấy là `$module_info['funcs'][$op]['func_custom_name']` hiện ở phần quản lý các funcs của module đã có thêm "Giá trị cho tiêu đề site" lưu vào `$module_info['funcs'][$op]['func_site_title']`

Nên bổ sung thêm phương án cho cái "Giá trị cho tiêu đề site"

**Comment by anhtunguyen** [comment]
Việc bổ sung thêm phương án cấu hình pagetitle không thực sự cần thiết.
"Giá trị cho tiêu đề site" là tiêu đề của function dành cho việc hiển thị ở tag title, chứ nó không phải là 1 biến độc lập.
Cái cần sửa ở đây là ở function nv_html_page_title: nếu "func_site_title" được định nghĩa thì ta lấy nó, nếu không thì lấy "func_custom_name":
```php
        // $module_info['funcs'][$op]['func_site_title'] đã được định nghĩa ở đây:
        // https://github.com/nukeviet/nukeviet/blob/eb042e37437b793202f5e6d7b5c3e6f89e536b90/includes/mainfile.php#L449
        if (empty($page_title) and !preg_match('/(funcname|modulename|sitename)/i', $global_config['pageTitleMode'])) {
            $_title = $module_info['funcs'][$op]['func_site_title'] . NV_TITLEBAR_DEFIS . $module_info['custom_title'];
        } else {
            $_title = preg_replace([
                '/pagetitle/i',
                '/funcname/i',
                '/modulename/i',
                '/sitename/i'
            ], [
                $page_title,
                $module_info['funcs'][$op]['func_site_title'],
                $module_info['custom_title'],
                $global_config['site_name']
            ], $global_config['pageTitleMode']);
        }
```
