### ISSUE TITLE
Thêm tính năng đăng nhâp thành viên qua Zalo

### ISSUE THREAD

**Issue by vingheo** [nukeviet/nukeviet#3258]
Mình thấy một số trang có Thêm tính năng đăng nhâp thành viên qua Zalo (https://thanhnien.vn). NV có thêm tính năng này thì hay.

**Comment by thehung** [comment]
Hay đó!

**Comment by vingheo** [comment]
Mình có thể thêm nút chia sẻ zalo luôn

**Comment by hoaquynhtim99** [comment]
@vingheo nút chia sẻ NukeViet 4.5 đã add vào rồi bạn, mặc định nó không show cần bật lên trong cấu hình module news. 
Tính năng đăng nhập Zalo cũng đã add vô dạng "thử nghiệm" trong bản 4.5.01 sắp tới
