### ISSUE TITLE
Block [HEAD_RIGHT] không hiển thị

### ISSUE THREAD

**Issue by Hoangcodedev** [nukeviet/nukeviet#3259]
**Mô tả lỗi**
Block [HEAD_RIGHT] không hiển thị, F5 thì hiển thị xong rồi mất, lỗi này từ bản 4.4.02 đã bị

**Comment by hoaquynhtim99** [comment]
Mình không thấy lỗi này. Bạn cung cấp thêm bạn đặt block gì vào đó?

**Comment by bocutom** [comment]
> **Mô tả lỗi**
> Block [HEAD_RIGHT] không hiển thị, F5 thì hiển thị xong rồi mất, lỗi này từ bản 4.4.02 đã bị

Này chắc do bạn bật chặn quảng cáo trên trình duyệt, vì nó có class="right-ads" nên nó chặn,
