### ISSUE TITLE
Lỗi cấu hình thống kê

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3271]
**Mô tả lỗi**
Trong mục Cấu hình thống kê không thể cập nhật dữ liệu cho 2 trường
Mã Google Analytics 4
Mã Google Universal Analytics
Phiên bản test 4.5.00 OpenBeta 1

Các bước để thấy lỗi:
1. Đi tới Công cụ web
2. Nhấp vào Dọn dẹp hệ thống
3. Cuộn xuống Mã Google Analytics 4 ,Mã Google Universal Analytics
4. Xem lỗi
![screenshot_1626285478](https://user-images.githubusercontent.com/82592373/125670036-e14e8e5b-574c-41ea-9bd2-58fb8ef71de9.png)

**Comment by hoaquynhtim99** [comment]
Mình thấy bình thường, bạn nhập đúng chuẩn thì nó mới ghi nhận còn nhập đại 1 giá trị nào đó nó sẽ không ghi nhận
