### ISSUE TITLE
Lỗi load modules voting

### ISSUE THREAD

**Issue by bocutom** [nukeviet/nukeviet#3282]
**Mô tả lỗi**
Khi bấm vào "kết quả" là site load nguyên trang. Trong admin cũng bị tương tự.
 Apache 2.4.47, MySQL 5.7.33, PHP 7.4.19

![voting](https://user-images.githubusercontent.com/87262549/126053494-b4105bb8-81bd-4eb1-9dd6-60de235b9b57.jpg)

**Comment by anhtunguyen** [comment]
@bocutom Đã thấy lỗi. Cảm ơn bạn đã báo
