### ISSUE TITLE
Lỗi tương thích phiên bản PHP

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3293]
https://github.com/nukeviet/nukeviet/blob/nukeviet4.5/install/ini.php#L48

Link này khai báo hỗ trợ php 5.6 đến 8.1 tuy nhiên NukeViet 4.5 không hoạt động được trên PHP 5.6 mà yêu cầu php 7.1

**Comment by anhtunguyen** [comment]
Đã hỗ trợ [php 5.6](https://github.com/nukeviet/nukeviet/commit/f7ef8a6880d548883533efabaa96b0f7d3cc5d2b)
