### ISSUE TITLE
Không kích hoạt được tài khoản từ link kích hoạt qua email

### ISSUE THREAD

**Issue by banhan00dt1** [nukeviet/nukeviet#3297]
Phiên bản: 4.5.00
Lỗi: Không kích hoạt được tài khoản từ link kích hoạt qua email khi đăng ký mới và phương thức kích hoạt tài khoản là kích hoạt qua email.

**Comment by anhtunguyen** [comment]
@banhan00dt1 Vui lòng chép đường link kích hoạt mà bạn nhận được qua email lên đây

**Comment by banhan00dt1** [comment]
> @banhan00dt1 Vui lòng chép đường link kích hoạt mà bạn nhận được qua email lên đây

https://old.028.vn/index.php?language=vi&nv=users&op=active&userid=3&checknum=8209c0f00999bc7218d9e610dc36e3d4 link đây @anhtunguyen  nhé

**Comment by banhan00dt1** [comment]
mình không biết hàm này mục đích làm gì nhưng bỏ qua câu lệnh này thì nó active được.
$canonicalUrl = getCanonicalUrl($page_url);
trong module users/funcs/active.php
Nhờ mọi người kiểm tra lại giúp lỗi này nhé, tạm thờii mình bỏ lệnh gọi hàm  getCanonicalUrl()

**Comment by anhtunguyen** [comment]
@banhan00dt1 Bạn [tải về](https://github.com/nukeviet/nukeviet/archive/refs/heads/nukeviet4.5.zip)
Giải nén và ghi đè lên các file cũ.
Sau đó kiểm tra xem còn bị không nhé.

**Comment by banhan00dt1** [comment]
> @banhan00dt1 Bạn [tải về](https://github.com/nukeviet/nukeviet/archive/refs/heads/nukeviet4.5.zip)
> Giải nén và ghi đè lên các file cũ.
> Sau đó kiểm tra xem còn bị không nhé.

code mới không lỗi, cảm ơn @anhtunguyen  nhé

**Comment by banhan00dt1** [comment]
> @banhan00dt1 Bạn [tải về](https://github.com/nukeviet/nukeviet/archive/refs/heads/nukeviet4.5.zip)
> Giải nén và ghi đè lên các file cũ.
> Sau đó kiểm tra xem còn bị không nhé.

bản anh gởi ko lỗi nhưng vào trang admin nó báo version 4.4.02 @anhtunguyen  ơi.

**Comment by anhtunguyen** [comment]
@banhan00dt1 Đợi 1-2 ngày nữa dùng luôn thể. Đội code đang chuẩn bị nâng cấp lên 4.5.01
