### ISSUE TITLE
Thêm phần quản lý thay đổi dữ liệu (migrations)

### ISSUE THREAD

**Issue by quocdatit** [nukeviet/nukeviet#3314]
**Yêu cầu tính năng của bạn có liên quan đến sự cố không? Làm ơn miêu tả.**
Hiện tại, mỗi lần muốn thay đổi cấu trúc bảng dữ liệu thì phải tự đổi trong phpmyadmin, rồi cập nhật vào file action_mysql.php, hoặc phải viết file module.update.php để chạy ngoài thư mục gốc.

**Mô tả giải pháp bạn muốn**
- Chuyển đổi phần action_mysql thành một thư mục dạng migrations trong Laravel, khi cài đặt hoặc gỡ cài đặt sẽ thực thi các file bên trong thư mục theo thứ tự thời gian.
- Khi muốn thay đổi cấu trúc bảng, nhà phát triển sẽ tạo 1 file thực thi việc thay đổi đó, và chạy thực thi phía admin. Tạo file thực thi đó theo 1 mẫu sẵn: có thể tải ở đâu, hoặc gõ lệnh để sinh ra file.

**Comment by hoaquynhtim99** [comment]
@quocdatit cái này bạn viết gói nâng cấp nhé, có sẵn rồi https://wiki.nukeviet.vn/programming4:moduleupdate  
Ví dụ nâng cấp download: https://github.com/nukeviet/module-download/tree/to-4.3.00

Ý thứ 2 của bạn thì bạn viết file để build gói update tự động. Gói của bạn có thể đăng lên NukeViet Store thì toàn bộ các site đang cài có thể cập nhật được

**Comment by quocdatit** [comment]
@hoaquynhtim99 cảm ơn bác nhé, để em nghiên cứu thêm
