### ISSUE TITLE
NukeViet 4.4 vấn đề khi xác định auto og:url

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3318]
Đối với NukeViet 4.5, 4.6 thì không vấn đề gì vì người dùng buộc nâng cấp các module nhưng NukeViet 4.4.03 và 4.4.04 nếu không nâng cấp module thì lỗi như sau:

Biến `$current_page_url` khi $page_url không khai báo được lấy đến $op [(LINK)](https://github.com/nukeviet/nukeviet/blob/nukeviet4.4/includes/core/user_functions.php#L278)

Biến đó được ép làm og:url [(LINK)](https://github.com/nukeviet/nukeviet/blob/nukeviet4.4/includes/core/user_functions.php#L433) nếu module không khai báo `$meta_property['og:url']` dẫn tới:

Link: `/vi/dau-thau/du-an/Tung-test-tao-du-an-nhap-so-4-xong-chuyen-sang-cong-khai-DA210895635-01.html`

Khi share lên facebook không nhận, nó chỉ nhận `/vi/dau-thau/du-an/`

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 trong trường hợp không muốn khai báo $page_url mà lại muốn facebook nhận diện đúng trang thì chỉ có cách dùng lại $client_info['selfurl']. Mà $client_info['selfurl'] thì chứa đầy hiểm họa

**Comment by hoaquynhtim99** [comment]
@anhtunguyen ý em không phải là `không muốn khai báo $page_url` mà là các site khách hàng đang dùng module cũ chưa cập nhật lên tức là họ chưa khai báo hoặc chưa kịp khai báo.

Nguyên tắc của mình cam kết là bản 4.x cùng con số x thì làm sao để người ta không cập nhật (module, giao diện) vẫn chạy bình thường, nếu bắt buộc phải cập nhật (module, giao diện) mới hoạt động bình thường thì sai cam kết của mình rồi anh.

Em thấy nếu không có khai báo thì có thể bỏ luôn thẻ meta og:url facebook sẽ nhận luôn cái link người ta share.

**Comment by hoaquynhtim99** [comment]
Em lấy ví dụ link này https://wiki.nukeviet.vn/nukeviet4:admin:themes:config không có bất kỳ thẻ `og` nào khi share lên thì facebook nó sẽ tự tìm lấy ảnh tự tìm tiêu đề, mô tả ở những thẻ meta cơ bản của HTML để hiển thị

**Comment by anhtunguyen** [comment]
Nhất trí với em về việc: **Nếu không có khai báo thì bỏ luôn thẻ meta og:url**
