### ISSUE TITLE
php 5.6 ko cài dược NukeViet 4.5

### ISSUE THREAD

**Issue by webvang** [nukeviet/nukeviet#3322]
![image](https://user-images.githubusercontent.com/8552350/129447200-5c89af7d-4365-4720-b596-b67a9ea50c26.png)
Phiên bản 4.5 cho phép yêu cầu php 5.6 đến 5.7, tuy niên minh set php 5.6 thi platform_check.php bắt php >7.1

mình set lại php7.4 

* php5.6
PHP_VERSION_ID : 50640
* php5.6
PHP_VERSION_ID : 70422
![image](https://user-images.githubusercontent.com/8552350/129448819-02a412b5-7c05-4b5c-8acd-e425ab67ccba.png)

**Comment by hoaquynhtim99** [comment]
Trùng với issue này https://github.com/nukeviet/nukeviet/issues/3293
