### ISSUE TITLE
Lỗi không úp được ảnh avatar 4.5

### ISSUE THREAD

**Issue by anvhceo** [nukeviet/nukeviet#3323]
mình có cài 2 phiên bản thì thấy có lỗi chổ úp avatar

/users/avatar/  ( phiên bản 4.5 ) ( lỗi k úp dc ) 
/index.php?nv=users&op=avatar/opener  ( phiên bản 4.5.00 OpenBeta 1 ) ( úp dc ảnh )

**Comment by hoaquynhtim99** [comment]
Bạn dùng bản 4.5 tải ở đâu? Thao tác (vị trí up) của bạn là chỗ nào (trong quản trị, block user_button hay trang thiết lập tài khoản ngoài site?)

Bạn test với NukeViet download ở đây xem lỗi không? https://github.com/nukeviet/nukeviet/tree/nukeviet4.5

Bản 4.5 mình test thấy `/users/avatar/` này không có:

- Nếu up trong admin nó là `/users/avatar/openner/`
- Up ngoài site nó là `/users/avatar/upd/`

Không có link trực tiếp đến `/users/avatar/`

**Comment by anvhceo** [comment]
mình úp trong quản trị và ngoài site 

phiên bản 4.5 ) ( lỗi k úp dc )

![image](https://user-images.githubusercontent.com/72913760/129653728-22789a82-b95b-4c77-8b5b-39daafb0e1cb.png)


phiên bản 4.5.00 OpenBeta 1 ( úp dc ảnh )
![image](https://user-images.githubusercontent.com/72913760/129653530-4906ce1f-c437-497c-847b-7c01eeb7a4e7.png)

**Comment by anvhceo** [comment]
https://github.com/nukeviet/nukeviet/releases/download/4.5.00/nukeviet4.5.00setup.zip  ( mình cài phiên bản này ) thì k dc 

https://github.com/nukeviet/nukeviet/tree/nukeviet4.5  ( bản này ok )

**Comment by hoaquynhtim99** [comment]
Ok bạn, bản kia có lỗi đã fix rồi, sẽ phát hành sớm (chờ xem còn lỗi gì ko).
