### ISSUE TITLE
Lỗi không thể nhập họ và tên chứa con số

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3324]
NukeViet 4.4, 4.5, 4.6 (mới nhất trên kho code) mới cài lên mặc định => Không nhập tên tài khoản có chứ con số được ví dụ `Công ty 1 thành viên`

**Comment by hoaquynhtim99** [comment]
Chữ số từ 0 - 9 bị xem là `ký tự đặc biệt`

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Đây không phải là lỗi, mà là theo logic thì họ và tên người không có số (Theo tùy biến dữ liệu, chỉ chấp nhận các chữ cái unicode, dấu gạch ngang, dấu nháy đơn và dấu cách). Nếu site có nhu cầu sử dụng các trường Họ và Tên để lưu các giá trị không chỉ là họ và tên thì cần thay đổi tùy biến về "Không kiểm tra"

**Comment by hoaquynhtim99** [comment]
Em nghĩ họ và tên xuất hiện con số trong đó là bình thường. Ở đây mình dùng
nhiều mục đích chứ không hẳn họ và tên chỗ đó bắt buộc phải là người thật.

Nếu vẫn ràng buộc không thể có con số theo em mặc định để không kiểm tra vì
có nhiều trường hợp người dùng đặt họ tên là tên chi nhánh, tên trường.

Giả sử 1 tổng công ty phát điện 1 sẽ có tài khoản chi nhánh đặt là Hải
Phòng 1, Hải Phòng 2...

Phòng giáo dục sẽ có tài khoản đặt là TH Kim Đồng 1, TH Kim Đồng 2.

Người dùng sẽ "loay hoay" khi cài đặt xong đặt tên lại không được.

1 vấn đề nữa là: Cài đặt xong vào quản trị thêm tài khoản nó báo "Họ và tên
không hợp lệ" => không biết như thế nào mới là hợp lệ.


Vào 20:15, Th 3, 17 thg 8, 2021 Nguyen Anh Tu ***@***.***> đã
viết:

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 OK. Anh [cập nhật](https://github.com/nukeviet/nukeviet/commit/7986506f15ae8b5d5ae609d8348ee7cf89e3fd49) dữ liệu mặc định là "Không kiểm tra" rồi.
