### ISSUE TITLE
Lỗi getCanonicalUrl khi kích hoạt tài khoản qua mail  hiên bản NukeViet $.5

### ISSUE THREAD

**Issue by webvang** [nukeviet/nukeviet#3325]
$url_rewrite = nv_url_rewrite($page_url, true);
    $url_rewrite_check = str_replace('&amp;', '&', $url_rewrite);
    $url_rewrite_check = urldecode($url_rewrite_check);
    $url_parts = parse_url($url_rewrite);
    !isset($url_parts['query']) && $url_parts['query'] = '';

    $request_uri = urldecode($_SERVER['REQUEST_URI']);
    if (str_starts_with($request_uri, NV_MY_DOMAIN)) {
        $request_uri = substr($request_uri, strlen(NV_MY_DOMAIN));
    }

    $request_parts = parse_url($request_uri);
	
    !isset($request_parts['query']) && $request_parts['query'] = '';

    if (empty($request_parts['path']) or strcmp($url_parts['path'], $request_parts['path']) !== 0) {
		nv_redirect_location($page_url);
    }

strcmp($url_parts['path'], $request_parts['path']) => so sánh path không đồng nhất 1 cái url_rewrite ccái còn lại không phải rewrite dẫn đến strcmp($url_parts['path'], $request_parts['path'])  = 3072 luôn !==0 nên ko actie user khi kích hoạt qua mail được. 

fix : thêm 	$request_uri = nv_url_rewrite($request_uri, true); trước đoạn 

$request_parts = parse_url($request_uri);

**Comment by anhtunguyen** [comment]
@webvang lỗi ở đây là quên xử lý URL kích hoạt tài khoản qua hàm nv_url_rewrite trước khi gửi nó đến email người dùng.
Bạn sửa lại như [ở đây](https://github.com/nukeviet/nukeviet/blob/614d94de61d2247b4ee302bbf3f670b58f203ec7/modules/users/funcs/register.php#L439-L440), hoặc sửa tổng thể như [ở đây](https://github.com/nukeviet/nukeviet/commit/614d94de61d2247b4ee302bbf3f670b58f203ec7)
Thanks!
