### ISSUE TITLE
Lỗi SQLSTATE: Syntax error khi không có từ khóa tìm kiếm, nhưng có chủ đề hoặc thời hạn ở module News

### ISSUE THREAD

**Issue by anhtunguyen** [nukeviet/nukeviet#3331]
Khi không có từ khóa tìm kiếm, nhưng có chọn chủ đề hoặc thời hạn đăng ở khu vực tìm kiếm của module News sẽ xuất hiện lỗi:
![ảnh](https://user-images.githubusercontent.com/5074710/130310954-e78bea3b-bed3-48a0-abfd-0d1f9ac5b987.png)

Môi trường: 
![ảnh](https://user-images.githubusercontent.com/5074710/130310991-5baed9bb-2209-44f1-b515-dc148937f486.png)

**Comment by anhtunguyen** [comment]
@htuyen1994 anh đã fix phần CSDL MySQL. Em làm giúp anh phần Elastic nhé

**Comment by hoaquynhtim99** [comment]
@anhtunguyen Elasticsearch ở news cũ lắm rồi anh nên cái này sửa cho MySQL là ok rồi ạ. Cần ES thì viết lại để nâng lên bản mới nhất luôn
