### ISSUE TITLE
thêm tính năng chuyển nhanh list danh sách thành viên giữa các nhóm, set password hàng hoạt tk

### ISSUE THREAD

**Issue by webvang** [nukeviet/nukeviet#3332]
![image](https://user-images.githubusercontent.com/8552350/130313299-51f59e6a-7e57-46d8-9ca8-e6c7af7ca918.png)

Muốn chuyển 1 lượng lớn thành viên sang nhóm khác thì không thực hiện được phải thao tác bằng tay từng tk

**Comment by webvang** [comment]
set password hàng hoạt tài khoản lớn, chứ set từng users mất thời gian lâu

**Comment by vuthao** [comment]
Tính năng này nên để các tính năng của các ứng dụng riêng biệt.
Theo mình ko nên đưa nào NukeViet mặc định làm ghì nó cồng kềnh.

Trên NukeViet Store đã có ứng dụng này rồi

**Comment by hoaquynhtim99** [comment]
Vote không đưa vào!
