### ISSUE TITLE
lỗi khi cài 1 module khác vào nukeviet 4.5 mở trang chủ là bị thế này 

### ISSUE THREAD

**Issue by anvhceo** [nukeviet/nukeviet#3334]
![image](https://user-images.githubusercontent.com/72913760/130397745-f25f9a96-02b7-46f3-bf2a-ed3713462932.png)
![image](https://user-images.githubusercontent.com/72913760/130397861-f3aa272a-8415-40c9-8647-3b44d69969c0.png)

nhờ ad xem giúp

**Comment by hoaquynhtim99** [comment]
Cái này do block tophit của module news chưa được cập nhật đúng phiên bản. Bạn đọc lại tài liệu cũ này để sửa https://github.com/nukeviet/update/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-n%C3%A2ng-c%E1%BA%A5p-giao-di%E1%BB%87n-t%C6%B0%C6%A1ng-th%C3%ADch-t%E1%BB%AB-NukeViet-4.2.01-l%C3%AAn-NukeViet-4.3.00#3-c%E1%BA%ADp-nh%E1%BA%ADt-c%C3%A1c-block-module-news
