### ISSUE TITLE
Cache lại một số bảng tần suất dùng cao

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#3335]
**1) Bảng nv4_authors_module dùng ở :** 

- https://github.com/nukeviet/nukeviet/blob/nukeviet4.5/admin/index.php#L40
- https://github.com/nukeviet/nukeviet/blob/nukeviet4.5/includes/core/user_functions.php#L870

**2) Bảng nv4_authors** Khi check vào admin luôn check đến nó, bảng này ít, tần xuất thay đổi cũng ít. dùng ở : 
- https://github.com/nukeviet/nukeviet/blob/nukeviet4.5/includes/core/admin_access.php#L112
- https://github.com/nukeviet/nukeviet/blob/nukeviet4.5/includes/core/admin_access.php#L226

**Comment by anhtunguyen** [comment]
@vuthao bảng `nv4_authors` có chứa các field: `last_login`, `last_ip`, `last_agent` nên cache bảng này có vẻ như không hợp lý. Vì thế anh chỉ cho cache bảng `nv4_authors_module`
