### ISSUE TITLE
Nội dung tiêu đề của Tag bị mất, khi nâng cấp lên 4.5

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#3347]
Khi nâng cấp từ NUKEVIET 4.4.02 lên 4.5

Vào module news kiểm tra quản lý tag, thì thấy giá trị tiêu đề của Tag bị trống.

Nguyên nhân: 

4.4.02 không có field "TITLE""

<img width="486" alt="php-tags" src="https://user-images.githubusercontent.com/6806295/132026187-fa007095-d698-42a3-9034-52f2970c372f.PNG">

<img width="794" alt="Lối quản lý tag" src="https://user-images.githubusercontent.com/6806295/132026244-8763e44f-4831-487e-8cd4-a5775c143af7.PNG">

Cải tiến:  Nên lấy giá trị của Keyword gán vào giá trị của Title

Vì khi duyệt site, mặc dù giá trị của title là rỗng, nhưng hệ thống vẫn lấy giá trị keyword gán vào giá trị title

**Comment by hoaquynhtim99** [comment]
Chỗ này đang xử lý nếu như không có tiêu đề thì lấy từ alias bỏ đi các dấu gạch ngang và viết hoa chữ cái đầu tiên, mặc định alias có dấu nó sẽ hoàn toàn giống với tiêu đề. Còn lấy từ keywords nó không chính xác bởi cơ chế cộng dồn tiêu đề từ trước giờ

Nếu bạn dùng site cũ cấu hình alias không có dấu có thể chạy lệnh sau

```sql
UPDATE `nv4_vi_news_tags` SET `title`=`keywords` WHERE `title`='';
```
