### ISSUE TITLE
Cải tiến phần quản lý captcha

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#3348]
Ở NukeViet 4.5 việc quản lý captcha được giao cho từng module.

Việc này dẫn đến việc thay đổi cấu hình ở các site có nhiều module rất tốn công, và làm bị sót.

Để nghỉ bổ sung thêm ở bên dới tab: Cấu hình hiển thị captcha (/admin/index.php?language=vi&nv=settings&op=security&selectedtab=2)
danh sách các module có captcha_type ở cấu hình
với mỗi dòng (module) sẽ có radio để chọn: Không sử dụng, Captcha hình, hoặc reCaptcha

Ngoài ra có thể áp 1 cấu hình: Không sử dụng, Captcha hình, hoặc reCaptcha cho tất cả các module (Việc này chỉ nên làm ở đúng chức năng đang code, không phải đi sửa code cho cấc module).

Với các module hiện tại đang cấu hình captcha_type  ở các chỗ khác cần đưa về cấu hình ở bảng NV_CONFIG_GLOBALTABLE để có thể quản lý tập trung.

Sau khi làm xong cho NukeViet 4.5 trộn qua NukeViet 4.6

**Comment by anhtunguyen** [comment]
@vuthao 
Cập nhật [ở đây](https://github.com/nukeviet/nukeviet/commit/e22f2ebb325f7dc04cc4bb7e8897c02e0c8ed5b0)
Ghi chú [ở đây](https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.5#c%E1%BA%ADp-nh%E1%BA%ADt-qu%E1%BA%A3n-l%C3%BD-t%E1%BA%ADp-trung-captcha)
