### ISSUE TITLE
Check lỗi không xóa session trong nukeviet 4

### ISSUE THREAD

**Issue by thangbv** [nukeviet/nukeviet#3349]
**Kiểm tra phần xóa session tmp**
Kiểm tra code thì có vẻ Nukeviet đang lưu session theo cấu hình php.ini và chưa có cơ chế để xóa các file session cũ này đi thì phải?

**Comment by hoaquynhtim99** [comment]
NukeViet 3 lưu sess riêng, đến NukeViet 4 để về mặc định của máy chủ. Đây là chuyển đổi của anh @vuthao chắc sẽ có giải thích rõ hơn.

Hiện muốn reset em nghĩ có thể vào `Cấu hình cookie session` đổi `Tiền tố session` là được.

**Comment by billygoat-trump** [comment]
`_Hiện muốn reset em nghĩ có thể vào Cấu hình cookie session đổi Tiền tố session là được._`

không biết nữa, vì mới test trong PHP thấy rằng session khá nặng, nên clear trong Phpmyadmin cho nó nhanh và sạch. Liệu đỗi Tiền tố session có làm sạch các table cũ, hay nó lại gia tăng Mb trong database ?

**Comment by hoaquynhtim99** [comment]
@billygoat-trump bảng nv4_sessions không phải lưu session thực nó chỉ lưu key để phục vụ việc đếm số người truy cập.

Có 2 cách xóa data của nó:
1. Nó tự mất hết nếu máy chủ khởi động lại.
2. Nó tự xóa định kỳ nhờ tiến trình `online_expired_del`. Nếu CSDL của bạn phình quá lớn vì nó thì check cái online_expired_del xem có bị stop lại không

**Comment by billygoat-trump** [comment]
`Nó tự xóa định kỳ nhờ tiến trình online_expired_del. Nếu CSDL của bạn phình quá lớn vì nó thì check cái online_expired_del xem có bị stop lại không`
Lần test vừa qua, move data qua lại vài cái server, trong phpmyadmin nó báo lỗi session vượt quá "ko nhớ chính xác là gì" nhưng sau đó CLEAN sạch nó đi và CÓ kiểm tra lại, nó vẫn ghi tốt.
