### ISSUE TITLE
how can i install your script

### ISSUE THREAD

**Issue by zeus6999** [nukeviet/nukeviet#3350]
Hello.
please how can i install your script?
Regards

**Comment by billygoat-trump** [comment]
All that you look for: https://wiki.nukeviet.vn/nukeviet4

All for you, you can use Google's Translate tool and translate the language you can read. This CMS is quite easy to install new, in the Admin Control Panel available in English language (setup step) and can set up in many different languages at back_end.

**_happy time and enjoy !_**
