### ISSUE TITLE
Recaptcha không hoạt động trên Live và Localhost

### ISSUE THREAD

**Issue by billygoat-trump** [nukeviet/nukeviet#3351]
Chào,

Như tiêu đề Recaptcha không hoạt động trên cả hai website đã thiết lập và cài đặt - 1 site đang chạy 4.4 - Upto 4.5 và localhost cài mới hoàn toàn 4.5 - hầu như các thiết lập Cấu hình hiển thị captcha không có phản ứng gì. có 2 tiểu mục.

1. Nếu upgraded từ 4.4 lên 4.5 tại mục Recaptcha không cho chọn "Phiên bản recaptcha" --> không kích hoạt được
2. Nếu gặp trường hợp 1, tôi copy cả thư mục ADMIN từ bản cài mới 4.5 đổ sang site upgraded --> đã có thể chọn được "Phiên bản recaptcha" các số "2 và 3"  --> thiết lập Site key và Secret key, Refesh và clear cache bowser/ site --> vẫn không thể kích hoạt khi log_in admin

**_Cung cấp thông tin máy chủ_**

> - Phiên bản NukeViet: Share_Hosting 4.4 -- upto 4.5 // Localhost 4.5 newly
> - Môi trường thử Nghiệm: Localhost / shared hosting (local SGN)
> - Hệ điều hành: litespeed
> - Trình duyệt web: Mozilla Firefox // chorme
> - Máy chủ web: XAMPP

**_Nếu NukeViet cài trên hosting (website đang chạy thực tế) cần có thêm thông tin_**
> + Công cụ quản lý hosting: Cpanel
> + Các thông tin khác: PHP 8.0

**Comment by tmsholdings** [comment]
đã add tên miền vào Recaptcha  google chưa bạn. mình từng bị nên phải add domain vào, còn Localhost  mình nghĩ nó sẽ ko hoạt động

**Comment by hoaquynhtim99** [comment]
Bạn vào cấu hình của module users (/admin/index.php?language=vi&nv=users&op=config) để chọn:
- Khu vực sử dụng captcha
- Kiểu captcha
Nhé! Recaptcha sẽ không show nếu không add key vào, đối với recaptcha v3 chắc chắn nó sẽ không show

**Comment by billygoat-trump** [comment]
Thank you !

@tmsholdings mình sài Recaptcha cho nhiều site mà, chứ có phải mới dùng đâu ... hi hi ko lo lắng nhé, ngay cả bản 4.3.x.x cũng đã dùng V2..
@hoaquynhtim99 - thanks bác TÍM chẳng thề nào ngờ thay đổi này .. nhét hết cái Active trong quản lý module User, trước chỉ có kích hoạt trong "kích hoạt an ninh" --> ok mọi việc có vẻ ổn hơn khi test với V2 và V3 nhưng Firefox nó cho cái thông báo này ...
" LỖI mà chủ sở hữu trang web sẽ thấy: Loại khóa không hợp lệ " mình vẫn phải test trên Chorme và Private .. hy vọng vài ngày nữa sẽ ổn 
* phải clear secret key và site key trong database nó mới chịu nhận - khi chuyển đổi giữa các V2-<>-V3 .. khó tính quá.

**Comment by hoaquynhtim99** [comment]
@billygoat-trump bản 4.5 có thay đổi lớn là đưa hết cấu hình captcha về từng module nên nó vậy bạn. Sang bản mới nó sẽ có luôn chỗ quản lý cấu hình chung cho tất cả các module luôn.

> LỖI mà chủ sở hữu trang web sẽ thấy: Loại khóa không hợp lệ

Cái này có vẻ cache gì đó thôi chứ mình không nghĩ do cấu hình trong quản trị mà cần phải clear trong DB

**Comment by billygoat-trump** [comment]
@hoaquynhtim99 đã tìm hiểu qua lỗi trên - hiện nay bản V3 chưa thật sự sẵn sàng cho việc dùng chính thức - với thông báo này của chính Google: "Note: The scores for this site may not be accurate before running with sufficient live traffic. Please see our developer site for more information." --> _**Điểm số cho trang web này có thể không chính xác trước khi chạy với đủ lưu lượng truy cập trực tiếp. Vui lòng xem trang web dành cho nhà phát triển của chúng tôi để biết thêm thông tin.**_ thời gian post của ghi chú này: Last updated 2021-07-16 UTC.":

- Recaptcha V2 hiện nay dùng cho Nukeviet chắc là ngon nhất rồi .. bản tiếp theo chắc có V3 upgrade.
- Không hiểu là việc tách riêng cấu hình Captcha cho riêng module là tốt hay không?

**Comment by hoaquynhtim99** [comment]
@billygoat-trump tách ra ở bản 4.5 đã phát hành còn bản mới nhất lại đưa về quản lý tập trung tại 1 chỗ "thiết lập an ninh" rồi bạn, mình nghĩ cái mới nhất (chuẩn bị phát hành) là tốt nhất!
