### ISSUE TITLE
Lỗi cài đặt không qua được bước 3

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3352]
Mình mới tải bản code mới nhất 4.5 về cài đặt thì không qua được bước 3.
Môi trường locahost
PHP version: 7.1.8
khi xóa thử dòng
if ($step > $maxstep and $step > 2) {
    $step = $maxstep;
    nv_redirect_location(NV_BASE_SITEURL . 'install/index.php?' . NV_LANG_VARIABLE . '=' . NV_LANG_DATA . '&step=' . $step);
}
thì sẽ qua được bước 3 vậy có nghĩa câu $maxstep = $nv_Request->get_int('maxstep', 'session', 1);
không lấy được dữ liệu
Không biết có phải phần mềm locahost mình có vấn đề không vì trước đó mấy ngày tải về vẫn cài bình thường

**Comment by vuthao** [comment]
Nếu thế nhiều khả năng locahost  của bạn bị lối session, hãy thử khởi động lại máy xem sao

**Comment by tmsholdings** [comment]
cảm ơn anh Thảo, đã phát hiện ra lỗi vì chiếm dụng gov.vn để chạy locahost nên không cài được đã đổi sang tên miền khác thì cài được bình thường ✌️
