### ISSUE TITLE
Lỗi khi Kiểm tra phiên bản Nukeviet

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#3353]
Sau khi cài đặt bản mới nhất, tiến hành kiểm tra phiên bản thì báo lỗi như hình ảnh:
![68](https://user-images.githubusercontent.com/11238423/135702514-347c25bb-b4ea-45b7-8540-7387f5ea711d.jpg)
Mong anh em đội Code kiểm tra và pix dùm. Thank!

**Comment by hoaquynhtim99** [comment]
Đã sửa lỗi!

**Comment by hoanglongvnpt** [comment]
Thank ban!



*CÔNG NGHỆ WEB SỐ  Add: 28 Phạm Đình Hổ-Thành phố Đông hà-Tỉnh Quảng trịHot
Line: 0889 335 345*
*Số Tài khoản: 0600 - 9454 - 0057*
*Tại Ngân hàng: Sacombank - TP Hồ Chí Minh*
*Chủ TK: NGUYỄN TẤT THẮNG*


Vào Th 2, 11 thg 10, 2021 vào lúc 08:46 Tan Dung Phan <
***@***.***> đã viết:
