### ISSUE TITLE
Lỗi khi xem Thông tin về Khối quảng cáo trong admin

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#3354]
Chức năng Thông tin về Khối quảng cáo trong admin dùng ajax để lấy thông tin.

Ví dụ https://my-domain/admin/index.php?language=vi&nv=banners&op=info_plan&id=5 có mã html
```html
<script type="text/javascript">
    nv_plan_info(5, 'plan_info');
    nv_show_banners_list('banners_list_act', 0, 5, 1);
    nv_show_banners_list('banners_list_queue', 0, 5, 4);
    nv_show_banners_list('banners_list_timeract', 0, 5, 0);
    nv_show_banners_list('banners_list_exp', 0, 5, 2);
    nv_show_banners_list('banners_list_deact', 0, 5, 3);
</script>

```
Việc tạo liên tục nhiều kết nối để lấy thông tin có thể bị firewall, mysql chặn.

Nên cải tiến lại phần này, nếu dữ liệu không quá nhiều không nên dùng ajax ở những chỗ như thế này.

Có thể dùng php để lấy tất cả thông tin trong 1 khối, rồi sắp xếp vào mảng để hiển thị tại các khu vực khác nhau

**Comment by anhtunguyen** [comment]
@vuthao Fixed

**Comment by hoaquynhtim99** [comment]
@anhtunguyen nó có một vấn đề không mượt lắm anh. Các mục giờ nó chuyển thành accordion mặc định thu gọn toàn bộ.
Khi em mở 1 mục để xem các quảng cáo trong đó giả sử có 10 quảng cáo đang hoạt động, em xóa đi 1 quảng cáo trang sẽ load lại và nó lại thu gọn. Em lại phải tiếp tục click để nó đổ nội dung ra. Giả sử em cần xóa đi 5 quảng cáo thì thao tác này cứ lặp đi lặp lại khá bất tiện

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 OK, anh [đã sửa rồi](https://github.com/nukeviet/nukeviet/commit/ef1e2d7270c3392e8c83a43bd596164e9814ad36)
