### ISSUE TITLE
LỖI COPY PASS HÌNH ẢNH VÀO BÌNH LUẬN K HIỆN THỊ ẢNH 

### ISSUE THREAD

**Issue by anvhceo** [nukeviet/nukeviet#3355]
![image](https://user-images.githubusercontent.com/72913760/136512205-120f8f2e-3c65-42f9-ac02-35397bb85020.png)
đây là phiên bản 4.5 
![image](https://user-images.githubusercontent.com/72913760/136512404-2fc47883-40ba-4ef5-9979-7687ccefbb79.png)
còn đây là phiên bản cũ

**Comment by hoaquynhtim99** [comment]
Bạn tắt CSP hoặc thêm tên miền của website an toàn vào ô "img-src" trong thiết lập CSP

**Comment by anvhceo** [comment]
> Bạn tắt CSP hoặc thêm tên miền của website an toàn vào ô "img-src" trong thiết lập CSP

mình đã thêm tên miền web của mình vào mà vẫn k hiện ấy bạn, k lẽ copy ảnh từ web khác vào là điền tên web đó làm ( có hàng trăm web - để copy ảnh sao bạn

**Comment by hoaquynhtim99** [comment]
Vậy thì tắt CSP thôi bạn ơi!
