### ISSUE TITLE
Lỗi cài đặt bước 5

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3359]
Em mới tải bản nukeviet 4.5 mới nhất 
Cài đến bước 5 thì báo lỗi
error set module: users
Không biết em có bỏ qua điều gì không.

**Comment by hoaquynhtim99** [comment]
Mình thử không thấy lỗi. Bạn cung cấp thêm các thông tin:
- Link bạn tải NukeViet
- Phiên bản php đang sử dụng?
- Gửi lên nội dung file log trong data/logs/error_logs/*.log

**Comment by tmsholdings** [comment]
bản develop mới nhất đó Dũng

`[Mon, 25 Oct 2021 17:34:11 +0700] [sieusan.vip] [127.0.0.1] [User Notice(1024): PDOException Object
(
    [message:protected] => SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
    [string:Exception:private] => 
    [code:protected] => 42000
    [file:protected] => F:\www\www\sieusan.vip\vendor\vinades\nukeviet\Core\Database.php
    [line:protected] => 528
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => F:\www\www\sieusan.vip\vendor\vinades\nukeviet\Core\Database.php
                    [line] => 528
                    [function] => query
                    [class] => PDO
                    [type] => ->
                    [args] => Array
                        (
                            [0] => CREATE TABLE IF NOT EXISTS tms_users_openid (
    userid mediumint(8) unsigned NOT NULL DEFAULT '0',
    openid varchar(255) NOT NULL DEFAULT '',
    opid char(50) NOT NULL DEFAULT '',
    id char(50) NOT NULL DEFAULT '',
    email varchar(100) NOT NULL DEFAULT '',
    UNIQUE KEY opid (openid, opid),
    KEY userid (userid),
    KEY email (email)
) ENGINE=MyISAM
                        )

                )

            [1] => Array
                (
                    [file] => F:\www\www\sieusan.vip\admin\modules\functions.php
                    [line] => 192
                    [function] => query
                    [class] => NukeViet\Core\Database
                    [type] => ->
                    [args] => Array
                        (
                            [0] => CREATE TABLE IF NOT EXISTS tms_users_openid (
    userid mediumint(8) unsigned NOT NULL DEFAULT '0',
    openid varchar(255) NOT NULL DEFAULT '',
    opid char(50) NOT NULL DEFAULT '',
    id char(50) NOT NULL DEFAULT '',
    email varchar(100) NOT NULL DEFAULT '',
    UNIQUE KEY opid (openid, opid),
    KEY userid (userid),
    KEY email (email)
) ENGINE=MyISAM
                        )

                )

            [2] => Array
                (
                    [file] => F:\www\www\sieusan.vip\install\index.php
                    [line] => 662
                    [function] => nv_setup_data_module
                    [args] => Array
                        (
                            [0] => vi
                            [1] => users
                        )

                )

        )

    [previous:Exception:private] => 
    [errorInfo] => Array
        (
            [0] => 42000
            [1] => 1071
            [2] => Specified key was too long; max key length is 1000 bytes
        )

    [xdebug_message] => <tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes in F:\www\www\sieusan.vip\vendor\vinades\nukeviet\Core\Database.php on line <i>528</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0024</td><td bgcolor='#eeeeec' align='right'>668544</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='F:\www\www\sieusan.vip\install\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.5936</td><td bgcolor='#eeeeec' align='right'>3561720</td><td bgcolor='#eeeeec'>nv_setup_data_module(  )</td><td title='F:\www\www\sieusan.vip\install\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>662</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.6682</td><td bgcolor='#eeeeec' align='right'>3658440</td><td bgcolor='#eeeeec'>NukeViet\Core\Database->query(  )</td><td title='F:\www\www\sieusan.vip\admin\modules\functions.php' bgcolor='#eeeeec'>...\functions.php<b>:</b>192</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.6682</td><td bgcolor='#eeeeec' align='right'>3658488</td><td bgcolor='#eeeeec'><a href='http://www.php.net/NukeViet\Core\Database.query' target='_new'>query</a>
(  )</td><td title='F:\www\www\sieusan.vip\vendor\vinades\nukeviet\Core\Database.php' bgcolor='#eeeeec'>...\Database.php<b>:</b>528</td></tr>

)
] [FILE: /admin/modules/functions.php] [LINE: 194]
`

**Comment by anhtunguyen** [comment]
[Fixed](https://github.com/nukeviet/nukeviet/commit/d06d6cba2e24c39532f9568461ea9afc81d7e22e)
