### ISSUE TITLE
Lỗi  $callback 

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3365]
Phiên bản test 4.5 mới nhất
Sử dụng php 8.0
Nên chú ý: Required parameter $callback follows optional parameter $priority in file /includes/functions.php on line 2962

**Comment by anhtunguyen** [comment]
@tmsholdings File includes/functions.php không có dòng 2962. Nó kết thúc ở dòng [2848](https://github.com/nukeviet/nukeviet/blob/cbf0240ba2aedd797b995c1e547b329e68a0253d/includes/functions.php#L2848)
