### ISSUE TITLE
Lỗi đăng nhập zalo, facebook, google

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3366]
Phiên bản nukeviet 4.5 mới mất
Test môi trường php 8.0
đăng nhập bằng zalo facebook, google ở block thì ok không vấn đề gì
nhưng chuyển vào funtion đăng nhập thành công nhưng link chuyển trang bị lỗi
https://domain.vnhttps//domain.vn/users/login/
Ngoài ra lựa chọn  Đăng nhập tự động bằng một tài khoản do hệ thống tự tạo
không có tác dụng, nó vẫn hiện thị cho người dùng tự lựa chọn gắn tài khoản có sẵn hoặc tạo tài khoản mới

**Comment by anhtunguyen** [comment]
@tmsholdings 
Tôi đã sửa lại code để nó nghe theo cấu hình "Các phương án hành động sau khi tiếp nhận Oauth mới", [commit đây](https://github.com/nukeviet/nukeviet/commit/cbf0240ba2aedd797b995c1e547b329e68a0253d), ghi chú [ở đây](https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.5#fix-l%E1%BB%97i-t%E1%BB%B1-t%E1%BA%A1o-t%E1%BA%A1i-kho%E1%BA%A3n-khi-ti%E1%BA%BFp-nh%E1%BA%ADn-oauth-m%E1%BB%9Bi).
Riêng Oauth "Zalo" không thể áp dụng chế độ Tự động tạo tài khoản được vì Zalo-server không cung cấp e-mail người dùng cho ta, buộc phải để khách khai báo bổ sung.
Phần lỗi redirect tôi chưa thấy nên chưa sửa được.

**Comment by tmsholdings** [comment]
dạ em đã xem lại
`<meta property="og:url" content="http://sieusan.viphttp://sieusan.vip/">`
em xem thì bị cái này

**Comment by anhtunguyen** [comment]
@tmsholdings Lỗi này không thuộc module Users và nó chỉ xảy ra ở host của bạn. Liệu cho tôi mượn host để test được không?

**Comment by tmsholdings** [comment]
ko biết code em lỗi chố nào, nhưng test bản mới nhất thì ok rồi ạ, cảm ơn anh https://thutran.vn/
