### ISSUE TITLE
Tạo tài khoản không bị cấm trong cấu hình ở trang admin

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/nukeviet#3368]
hiện tại thì trong admin khi tạo tài khoản với tên tk có trong danh sách cấm của cấu hình thì vẫn tạo được vớii tên tk đó. cải tiến chỉ được tạo tk khi tk không nằm trong danh sách tên bị cấm trong admin

**Comment by hoaquynhtim99** [comment]
Cá nhân em nghĩ thế là bình thường, ràng buộc quá nhiều khi mình không làm được việc mình muốn.

**Comment by webvang** [comment]
![z2948628791096_f0339e1a1f6c1f8701f10ea3f3f5022d](https://user-images.githubusercontent.com/8552350/142578384-1bd007ae-455b-493d-b2ce-dd67b700eef7.jpg)
trong cấu hình thì có ở đây nhưng ngoài site thì ko có kiêm tra tên tk có chứa những từ bị cấm này

**Comment by webvang** [comment]
ngoài site cấm nhưng admin thì lại ko cấm mà vẫn tạo được bt

**Comment by hoaquynhtim99** [comment]
Đúng rồi, admin thì vẫn tạo được tự do, không nên ràng buộc như thế.

**Comment by webvang** [comment]
đã cấm thì cấm toàn bộ chứ, ko cấm trong admin, các quản trị module lỡ như bị hack pass rồi tạo tk ko mong muốn có trong danh sách cấm, hoặc có cấu hình là bật tắt cấm trong admin. đa phần các mã nguồn là đã cấm thì cấm hết vì đã nghĩ đến bảo mật cả ngoài site và admin.
