### ISSUE TITLE
Xem xét lại gửi email cập nhật tài khoản lộ mật khẩu

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3374]
Phiên bản nukeviet 4.5.1
Thử nghiệm trên nền tảng php 8.2
Sau khi login vào admin đổi mật khẩu, hệ thống gửi email hiện cả mật khẩu, như vậy rất là nguy hiêm.
Em đề xuất nên thông báo: Đã đổi mật khẩu thành công  thay vì để thế này: 
Tài khoản của bạn tại website TMS Holdings đã được cập nhật với Mật khẩu mới là cbvfh97.

**Comment by hoaquynhtim99** [comment]
Hệ thống cho bạn tùy chọn gửi thông tin và không gửi thông tin. Mặc định không gửi thông tin, giải thích cũng nêu rõ 

> Nếu chọn, sau khi cập nhật tài khoản thành công thành viên sẽ nhận được email thông báo về các thay đổi của tài khoản, thông tin bao gồm tên đăng nhập và mật khẩu (nếu mật khẩu được thay mới)

**Comment by anhtunguyen** [comment]
@tmsholdings Ngoài ra, còn trường hợp thành viên đổi mật khẩu ngoài site hoặc dùng công cụ khôi phục mật khẩu. Việc gửi thư thông báo mật khẩu mới của cả 2 trường hợp này được quản lý bởi chỉ thị `send_pass` (Gửi thông tin mật khẩu đến email người dùng) trong cấu hình của module Users.

**Comment by tmsholdings** [comment]
vâng anh
