### ISSUE TITLE
Lỗi chuyển hướng tại module banners

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3375]
Ở các link này https://domain.com/banners/click/?id= Google vẫn báo lỗi chuyển hướng mặc dù đã có header `X-Robots-Tag: "noindex"`

Hiện tại đang làm phép thử cả `X-Robots-Tag: "noindex,nofollow"`

**Comment by hoanganhcntt** [comment]
mình cũng đang quan tâm đến vấn đề này ko biết có bác nào fix chưa

**Comment by anhtunguyen** [comment]
Đã fix [ở đây](https://github.com/nukeviet/nukeviet/commit/564a9d0b876300fcb03d55afe7f3eefae3d56404)
