### ISSUE TITLE
Lỗi iconv_set_encoding khi chạy trên php > 5.6

### ISSUE THREAD

**Issue by loveall123** [nukeviet/nukeviet#3376]
iconv_set_encoding(): Use of iconv.output_encoding is deprecated] [FILE: /includes/utf8/iconv_string_handler.php]

Đã xử lý thành công

if (PHP_VERSION_ID < 50600) {
    iconv_set_encoding('input_encoding', 'UTF-8');
    iconv_set_encoding('output_encoding', 'UTF-8');
    iconv_set_encoding('internal_encoding', 'UTF-8');
} else {
    ini_set('default_charset', 'UTF-8');
}

Đội code xem xét điều chỉnh trong nhân hệ thống

**Comment by anhtunguyen** [comment]
@loveall123 OK. Đã sửa trong [NukeViet 4.6](https://github.com/nukeviet/nukeviet/commit/d167e92d87e47d13933abd50b29e7a6e4097ea78)
