### ISSUE TITLE
Lỗi bị thoát ra đăng nhập khi chuyển từ máy tính sang mobile

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3379]
Hiện tại các bản nukeviet 4x đều bị dính vấn đề này. Mình không biết nó bị lỗi hay do cơ chế nukeviet bắt buộc thiết lập như vậy.
Trình trạng: website đang ở giao diện máy tính, nhấn phân tích phần tử rồi chọn mobile
Thì tài khoản sẽ bị đẩy ra ngoài phải đăng nhập lại.
Nếu là cố tính thì có cách nào xử lý vấn đề này không

**Comment by hoaquynhtim99** [comment]
Có lẽ đây đúng là vấn đề vì lệnh này 

```php
if ($user['checkhash'] === md5($user['userid'] . $user['checknum'] . $global_config['sitekey'] . $client_info['browser']['key'])) {
```

Đang sử dụng cả biến `$client_info['browser']['key']` @anhtunguyen @vuthao

**Comment by anhtunguyen** [comment]
@tmsholdings @hoaquynhtim99 Đúng là vấn đề ở $client_info['browser']['key'].
- Khi bạn thay đổi chế độ tương thích của trình duyệt thì key của trình duyệt đó cũng thay đổi (trình duyệt thay đổi USER_AGENT), dẫn đến việc cookie đăng nhập thành viên không hợp lệ. 
- Có lẽ không thể căn cứ vào $client_info['browser']['key'] để xác định đăng nhập, bởi nó không phải là thứ bất biến. Có lẽ cần dựa vào một cookie khác được sinh ra từ đầu và bất biến

**Comment by anhtunguyen** [comment]
@tmsholdings thử xem còn bị không nhé: [Fix ở đây](https://github.com/nukeviet/nukeviet/commit/3db53873c9135a273374a8ff1d33e109f672ae96)

**Comment by tmsholdings** [comment]
đã ổn, em cảm ơn anh
