### ISSUE TITLE
Lỗi upload trên một số hosting

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3386]
Dòng này  https://github.com/nukeviet/nukeviet/blob/nukeviet4.5/vendor/vinades/nukeviet/Files/Upload.php#L1122 đang sử dụng hàm exif_read_data(), hàm đó buộc phải có thư viện exif, trong khi một số hosting không có sẵn, do đó không thể upload được file ảnh

```
[Error(1): Uncaught Error: Call to undefined function NukeViet\Files\exif_read_data() in public_html/vendor/vinades/nukeviet/Files/Upload.php:1122
Stack trace:
#0 public_html/admin/upload/upload.php(71): NukeViet\Files\Upload->save_file(Array, '/home/dom...', false, 1)
#1 public_html/admin/index.php(182): require('/home/cbitc/dom...')
#2 {main}
  thrown] [FILE: /vendor/vinades/nukeviet/Files/Upload.php] [LINE: 1122]

```

**Comment by anhtunguyen** [comment]
[Fixed](https://github.com/nukeviet/nukeviet/commit/aeaa40811aa7b88f0c3ae328c02f715983e45b3d)
