### ISSUE TITLE
Mặc định khi cài đặt nên tắt CSP và "Chặn máy chủ index website"

### ISSUE THREAD

**Issue by loveall123** [nukeviet/nukeviet#3387]
Bản mới có chức năng chặn index của các công cụ tìm kiếm và chặn chèn nguồn bên ngoài (CSP)

<meta name="robots" content="noindex, follow">
<meta name="googlebot" content="noindex, follow">

Theo mình nên để mặc định tính năng này TẮT. 

Mình đã làm 3 web từ lúc 4.5.01 xuất bản nhưng cả 3 đều bị vướng chổ này, (Chèn youtube không hiển thị, bị chặn google index). Phải tốn nhiều thời gian mới nhớ đi tắt nó.

Như vậy các thành viên mới khi cài mới web mới sẽ gặp rắc rối làm họ bất mãn với mã nguồn chúng ta.

**Comment by hoaquynhtim99** [comment]
Mục "Chặn các máy chủ tìm kiếm đánh chỉ mục website" mặc định tắt. Nó chỉ bật nếu lúc cài bạn chọn **CHẾ ĐỘ PHÁT TRIỂN**. 
CSP mình bỏ 1 phiếu mặc định tắt.

**Comment by anhtunguyen** [comment]
[Đã set lại](https://github.com/nukeviet/nukeviet/commit/b67874022fa9f99d8a1c983ef100dd79081cfd42)
