### ISSUE TITLE
Các từ khóa cấm và Thành viên thoát với cấu hình đăng nhập từ nhiều trình duyệt

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3392]
Hiện tại bản nukeviet 4.6 mới nhất mình cài lên
Trong admin khi thêm tài khoản có các từ khóa cấm:anonimo, anonymous, god, linux, nobody, operator, root
Mình thử tạo tài khoản : root thì vẫn tạo được trong admin, không biết đây có phải lỗi không
---
Hiện tại chúng ta cấu hình đăng nhập nhiều trình duyệt khác nhau.
tuy nhiên thi thoát ra thì chỉ thoát được trình duyệt hiện tại.
Chúng ta có nên học theo facebook, thoát hết các trình duyệt để nâng cao bảo mật không

**Comment by anhtunguyen** [comment]
@tmsholdings 
- Về việc tạo được tài khoản với tên bị cấm trong ACP: Ngụ ý của các tên bị cấm là áp dụng cho người dùng khi đăng ký thành viên thôi. Còn admin không bị hạn chế bởi cấu hình này.
- Việc thoát khỏi tình trạng đăng nhật ở một nơi cho tất cả: Ý kiến rất hay. Tôi sẽ suy nghĩ và làm theo ý của bạn.

**Comment by tmsholdings** [comment]
cảm ơn anh Tú
