### ISSUE TITLE
URL của quảng cáo khi tạo không được kiểm tra

### ISSUE THREAD

**Issue by danlt150** [nukeviet/nukeviet#3396]
Khi chỉnh sửa quảng cáo, URL đã nhập vào được kiểm tra pattern để đảm bảo format. Tuy nhiên URL này có thể được nhập bất kỳ mà không được kiểm tra khi thêm quảng cáo mới.
Hình ảnh dưới là hình ảnh URL được kiểm tra khi chỉnh sửa quảng cáo, URL này đã được nhập vào từ bước thêm mới nhưng không bị lỗi.
![image](https://user-images.githubusercontent.com/83101691/144980034-13142bc6-0c9f-446b-be97-9f8914b04dcb.png)

**Comment by hoaquynhtim99** [comment]
Cái này cần sửa lại khi sửa quảng cáo thì không kiểm tra thay vì sửa lại kiểm tra url khi thêm quảng cáo.
Vì đang cố tình để nhập URL tự do ví dụ banner vào module contact thì chỉ cần nhập url `/vi/contact/` khi đổi tên miền không bị lỗi. Nếu bắt nhập đủ http://..... thì sau khi đổi tên miền phải vào hết các quảng cáo chỉnh lại rất mất thời gian.

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Anh cho rằng, không kiểm tra URL là không nên. Ít ra cũng phải kiểm tra một cách hình thức bằng function nv_is_url. Việc xác định xem URL có phải là URL nội bộ site hay không cũng đơn giản (Có http hay https hay không).  Nếu là URL nội bộ thì gán NV_MY_DOMAIN vào trước rồi tiến hành kiểm tra bằng hàm nv_is_url.
Anh đã fix lỗi này ở [NV4.6](https://github.com/nukeviet/nukeviet/commit/3fa75996e8be5269f99ee2246061dfad60ea73e9)
