### ISSUE TITLE
Lỗi trắng trang khi truy cập "Quyền truy cập API", "Quản lý API Roles" trong module QUẢN TRỊ

### ISSUE THREAD

**Issue by ngoctu2008** [nukeviet/nukeviet#3401]
Error on file /vendor/vinades/nukeviet/Core/Database.php line 528:
Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nukeviet4500.dakto_authors_api_role' doesn't exist in D:\website\htdocs\nukeviet4.5.00\vendor\vinades\nukeviet\Core\Database.php:528
Stack trace:
#0 D:\website\htdocs\nukeviet4.5.00\vendor\vinades\nukeviet\Core\Database.php(528): PDO->query('SELECT * FROM d...')
#1 D:\website\htdocs\nukeviet4.5.00\admin\authors\api-roles.php(28): NukeViet\Core\Database->query('SELECT * FROM d...')
#2 D:\website\htdocs\nukeviet4.5.00\admin\index.php(182): require('D:\\website\\htdo...')
#3 {main}
  thrown
==================================

**Comment by anhtunguyen** [comment]
@ngoctu2008 Trong CSDL của bạn thiếu bảng nv4_authors_api_role
