### ISSUE TITLE
Lỗi không thể tạo tài khoản tường lửa khu vực admin

### ISSUE THREAD

**Issue by HQuang** [nukeviet/nukeviet#3403]
**Mô tả lỗi**
- Khi thêm tài khoản tường lửa khu vực admin thì bị trắng trang.
- Nội dung log: 
```
[Error(1): Uncaught PDOException: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'mask' at row 1 in nukeviet\vendor\vinades\nukeviet\Core\Database.php:672
Stack trace:
#0 nukeviet\vendor\vinades\nukeviet\Core\Database.php(672): PDOStatement->execute(NULL)
#1 nukeviet\admin\authors\config.php(170): NukeViet\Core\NukeVietPDOStatement->execute()
#2 nukeviet\admin\index.php(182): require('www\\...')
#3 {main}
  thrown] [FILE: /vendor/vinades/nukeviet/Core/Database.php] [LINE: 672]

```

**Thông tin bổ sung**
- Hiện tại structure của field mask trong bảng authors_config đang đặt là unsigned  `mask tinyint(4) unsigned NOT NULL DEFAULT '0'`
- Nhưng các query liên quan đến field mask này thì lại đặt là giá trị âm.
- Trường hợp gây lỗi ở đây xác định là do sử dụng unsigned nhưng lại set giá trị âm khi insert và update nên query lỗi.

**Comment by anhtunguyen** [comment]
@HQuang thanks
