### ISSUE TITLE
Lỗi cache module news trên NukeViet 4.5, 4.6

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3405]
Từ NukeViet 4.5 bổ sung thêm cấu hình **Phương án thể hiện trang chủ ở giao diện mobile** tuy nhiên file cache lại chỉ xác định theo giao diện, function và số trang `$module_info['template'] . '-' . $op . '-' . $page` dẫn tới việc site lúc thì hiển thị dạng chuyên mục, lúc thì lại hiển thị dạng list

**Comment by anhtunguyen** [comment]
OK. Lỗi này chỉ thấy ở NukeViet 4.5 thôi em.
[nukeviet4.5](https://github.com/nukeviet/nukeviet/blob/5eb43adda8434d7671899d5c634d3b75b5179a74/modules/news/funcs/main.php#L41):
```php
$cache_file = NV_LANG_DATA . '_' . $module_info['template'] . '-' . $op . '-' . $page . '-' . NV_CACHE_PREFIX . '.cache';
```
[nukeviet4.6](https://github.com/nukeviet/nukeviet/blob/45dc05813ce4c08a467331b4c69fcebbbec3c566/modules/news/funcs/main.php#L41):
```php
$cache_file = NV_LANG_DATA . '_' . $module_info['template'] . '-' . $op . '-' . $viewcat . '-' . $page . '-' . NV_CACHE_PREFIX . '.cache';
```
