### ISSUE TITLE
Cải tiến CSDL comment

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3406]
Hiện tại cặp khóa  area và id trong bảng nv4_vi_comment đang có kiểu số điều này hạn chế khả năng tùy biến, nên đặt thành varchar để dễ tùy biến hơn trong một số trường hợp:

- Tại một khu vực có nhiều khung comment (vấn đề về area)
- Obj comment không quản lý theo dạng id int auto increament (vấn đề về id). Cụ thể ví dụ: Một học liệu elearning có nhiều part (trang igiaoduc) đối với các path được upload lên (video, scorm, pdf) thì được quản lý dạng ID nên có thể comment. Còn các link bên ngoài (md5 link) thì không thể comment vì không có số ID cụ thể

**Comment by anhtunguyen** [comment]
Đã cải tiến ở NukeViet 4.6
