### ISSUE TITLE
Lỗi Lọc các mã HTML nguy hiểm trước khi gửi biểu mẫu NukeViet 4.6

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#3407]
Khi bật tính năng Lọc các mã HTML nguy hiểm trước khi gửi biểu mẫu trong khu vực tương tác với người dùng thì bị lỗi như sau:

Module Quảng cáo đang bị lỗi, em không thêm được banner mới. Nó cứ báo cần điền đủ thông tin vào các ô bắt buộc mặc dù đã điền đủ rồi. 

Module Users: đổi ảnh đại diện sau khi chọn hình để cắt, ấn cắt hình không được ạ.

**Comment by anhtunguyen** [comment]
@vuthao [Fixed](https://github.com/nukeviet/nukeviet/commit/791d5c419df939ad773fa6b7426a6719063c6b9e)
