### ISSUE TITLE
Lỗi đăng nhập user và admin

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3409]
Trên bản nukeviet 4.6 mới nhất xảy ra tình trạng này
Bước 1: đăng nhập 1 user bất kỳ (không phải admin)
Bước 2: Đăng nhập admin Không thoát user ở bước 1.
Nếu bình thường khi đăng nhập admin thì user đăng nhập bước 1 sẽ bị đá ra
Tuy nhiên phiên bản 4.6 thì nó tồn tại 2 user , nếu thoát admin ra thì nó sẽ xuất hiện user số 1
Mình nghĩ đây là lỗi

**Comment by anhtunguyen** [comment]
@tmsholdings Cơ chế đăng nhập admin và user khác nhau. Nếu user1 là tài khoản thành viên được đề bạt làm quản trị site, user2 chỉ là tài khoản thành viên => chỉ khi thoát admin  của tài khoản user1 thì tài khoản thành viên của user2 mới hoạt động. Tôi chưa nhìn thấy sự ảnh hưởng lẫn nhau của user1 và user2, nên không cho đây là lỗi. Bạn có thể chỉ ra "lỗi" ở đây là gì không? Lỗi xảy ra trong bối cảnh nào?

**Comment by tmsholdings** [comment]
trước kia là khi user2 đăng nhập mà sau đó em tiếp tục dùng user1 đăng nhập admin thì hệ thống sẽ đá luôn user2 ra. còn phiên bản hiện tại, khi user1 admin đăng nhập thì user 2 vẫn tồn tài, nếu thoát đăng nhập admin thì hệ thống sẽ hiện thị user 2 đang đăng nhập đó anh

**Comment by tmsholdings** [comment]
@anhtunguyen  anh có thể xem lại vấn đề này không ạ, admin đăng nhập nhưng lấy sestion của user nên dẫn đến lỗi vì nó không đá user ra được

**Comment by anhtunguyen** [comment]
@tmsholdings 
- Cập nhật bản mới nhất
- Sửa DB như hướng dẫn [ở đây](https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.6#th%C3%AAm-t%C3%B9y-ch%E1%BB%89nh-bu%E1%BB%99c-%C4%91%C4%83ng-xu%E1%BA%A5t-kh%E1%BB%8Fi-t%C3%A0i-kho%E1%BA%A3n-ng%C6%B0%E1%BB%9Di-d%C3%B9ng-khi-%C4%91%C4%83ng-nh%E1%BA%ADp-admin---17022022)
- Vào `https://mysite.com/admin/index.php?language=vi&nv=authors&op=config` và cấu hình tùy chỉnh "Buộc đăng xuất khỏi tài khoản người dùng khi đăng nhập với tư cách quản trị viên"

**Comment by tmsholdings** [comment]
em cảm ơn anh, đã thành công
