### ISSUE TITLE
Lỗi bài viết ko lấy được tác giả (author)

### ISSUE THREAD

**Issue by nhoxbin** [nukeviet/nukeviet#3410]
modules news file theme.php function viewcat_page_new biến array_catpage => biến này phần tử author không có? nên lấy bài viết  ở biến này sẽ ko lấy được tên tác giả cùng với alias author

**Comment by hoaquynhtim99** [comment]
Bạn có nhu cầu lấy author ra thì phải viết thêm nhé bạn, mặc định module tin tức không hiển thị tác giả ra bên ngoài chỗ nào ngoại trừ phần chi tiết bài viết.

Ở bản 4.5 trở đi tác giả có 2 loại: Tác giả bên ngoài và tác giả là thành viên, tác giả bên ngoài lưu ở trường author như bạn đang mong muốn còn tác giả thành viên (xem theo danh sách được) thì cần truy vấn vào bảng nv4_vi_news_authorlist, nv4_vi_news_author để lấy ra.

Việc lấy sẵn ra trong các function show list bài viết là không tối ưu nên sẽ không thể sửa bổ sung vào được.

Tùy thuộc nhu cầu của bạn mà bạn có thể sửa code, hoặc chỉ sử dụng tác giả bên ngoài mà không chọn tác giả là thành viên
