### ISSUE TITLE
Cải tiến các function không còn được hỗ trợ trong module ô chữ khi cài đặt ở phiên bản mới

### ISSUE THREAD

**Issue by nvu-github** [nukeviet/nukeviet#3414]
Hiện tại em đang dùng nukeviet phiên bản 4.5.01, sau khi cài đặt module ô chữ vào hệ thống thì module không thể hoạt động do có các function không còn hỗ trợ ở phiên bản mới.
Cụ thể là các function:
- mysql_query()
- filter_text_input()
- mysql_num_rows()
- mysql_fetch_array()

**Comment by hoaquynhtim99** [comment]
Module đó không hỗ trợ phiên bản NukeViet mới bạn, và nó không liên quan đến core NukeViet, bạn viết issue nhầm chỗ rồi.
