### ISSUE TITLE
Cho phép chèn các đoạn mã google search console, adsense, analytics vào NukeViet

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#3415]
**Nghiên cứu cho phép chèn các đoạn mã google search console, adsense, analytics vào NukeViet**
Tôi nghĩ các bạn phát triển NukeViet lên phát triển thêm trong quản trị NukeViet phần cho nhúng các đoạn mã google vào trong thẻ <head>, <footer>
Chứ tôi thấy mỗi lần tôi muốn chèn code hay người dùng bình thường chèn code google để quản lý site phải mở hosting tìm kiếm mấy file header_only.tpl và footer_only.tpl. Với người hiểu thì có thể dễ dàng với người sử dụng đơn thuần thì lại khó khăn. Chưa kể nếu không quản lý hosting thì mấy việc này cũng không làm được

Thế nên tôi khuyến nghị các bạn phát triển NukeViet nên tính toán cho việc người dùng có thể dung mã google cho thuận tiện hơn

**Comment by hoaquynhtim99** [comment]
Cái này không nên đưa vào core làm rườm rà hơn bộ core. Mã của họ thay đổi liên tục mình không phải theo.

Có thể đơn giản viết block, chia sẻ lên kho ứng dụng NukeViet, website nào thích thì dùng ngay. Hiện trên mạng cũng có rất rất nhiều block dạng như thế.

1. Chèn vào head thì đưa vào biến $my_head
2. Chèn vào footer thì đưa vào biến $my_footer
3. Muốn giữ cho script không auto kéo xuống footer thì thêm `data-show="inline"` vào thẻ script
