### ISSUE TITLE
Lỗi og:url khi bật Plugin get_rewrite_domain

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3436]
Như tiêu đề mô tả
Khi bật Plugin get_rewrite_domain trên phiên bản 4.6 mới nhất thì og:url sẽ bị dính lỗi x 2 lần tên miền dẫn đến bị lỗi 
meta property="og:url" content="https://domain.comhttps://domain.com/"

**Comment by tmsholdings** [comment]
Hồi trước em cũng báo lỗi này nhưng không tìm được nguyên nhân, @thehung  @anhtunguyen xem giùm em nhé
Cảm ơn anh

**Comment by anhtunguyen** [comment]
@tmsholdings Cập nhật mới nhất và làm theo hướng dẫn [ở đây](https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.6#fix-l%E1%BB%97i-url-khi-b%E1%BA%ADt-plugin-get_rewrite_domain---06042022). Có gì báo cho anh biết kết quả nhé

**Comment by tmsholdings** [comment]
đã ổn cảm ơn anh
