### ISSUE TITLE
Cải tiến nút xem trước trong phần đính kèm file module news trong nukeviet

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#3441]
Hiện nút xem trước trong phần đính kèm file trong chi tiết bài viết đang không phân biệt được file nào xem được trực tiếp file nào không.
Cần cải tiến như sau
- Với file pdf thì cho hiển thị xem trước (có thể như hiện tại)
- Với file không phải pdf thì hiển thị icon chấm than cảnh báo. là kiểu file không xem trước được

**Comment by hoaquynhtim99** [comment]
Vấn đề này cần check kỹ lại. Đúng thiết kế nó thì PDF và ảnh là xem trực tuyến, các file doc, excel, powerpoint là xem từ Google Quick View, còn lại không xem chỉ tải về.

Nếu có sai thì quá trình code có lẽ đã lỗi

**Comment by hoaquynhtim99** [comment]
Hiện check lại NukeViet mặc định đã phân biệt file nào xem trực tiếp, file nào không rồi. Xem ảnh dưới
![2022-06-02_13-50-18](https://user-images.githubusercontent.com/2421714/171570364-230f5c99-aedf-40eb-863b-f230b8035632.jpg)
Có thể đó là lỗi của giao diện
