### ISSUE TITLE
Cải tiến việc đổi (*) đỏ bắt buộc thành chữ "bắt buộc"

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#3442]
Nhiều người mới sử dụng nukeviet không biết các trường có dấu (*) là bắt buộc phải điền trừ khi là phải ấn nút lưu mới có thông báo khi đó biết phải nhập
Cần cải tiến sửa dấu (*) này thành (bắt buộc) như vậy người dùng có thể hiểu luôn khi đọc tiêu đề input đó

**Comment by hoaquynhtim99** [comment]
Mình thấy cái này không cần thiết. Từ khi biết dùng website đến giờ chưa có 1 trang web nào để cả chữ "Bắt buộc" dài dòng như thế

**Comment by nambmtk1993** [comment]
Nếu không thể cho chữ bắt buộc. Thì mình nghĩ nên thêm chú thích trên cùng và dưới cùng mỗi form nhập thông tin. Để người dùng có thể biết đó là phải nhập

**Comment by tmsholdings** [comment]
> 

bạn thêm vào chữ bắt buộc là đc, mấy cai tpl ấy lôi ra viết thêm vào
