### ISSUE TITLE
e gặp lỗi url 4.5.01

### ISSUE THREAD

**Issue by hades-1997** [nukeviet/nukeviet#3443]
e gặp lỗi với url **/index.php?language=vi&nv=news&op=thu-thuat-chia-se-hay/them-nut-xem-them-va-thu-gon-danh-cho-chi-tiet-san-pham-74.html**
cùng 1 data gọi ra nhưng cái hình thì bị url như trên. Còn cái  href của title thì lại không bị.
xin được giúp đỡ 
website e: https://vncode.info/

**Comment by hoaquynhtim99** [comment]
Chào bạn, 
Vấn đề này mời bạn thảo luận ở đây https://www.facebook.com/groups/nukeviet/ 
Trên Github này tiếp nhận ý tưởng, đề xuất cải tiến và báo lỗi core chứ không hỗ trợ bạn chỉnh sửa giao diện của bạn
