### ISSUE TITLE
Lỗi cấu hình gửi email

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#3446]
Mình đã làm theo hướng dẫn để cấu hình gửi email trong nukeviet nhưng vẫn không được? Vậy nên rất mong đội code nghiên cứu và hướng dẫ anh em pix lỗi này
![email](https://user-images.githubusercontent.com/11238423/165043702-8482907c-5414-4286-ba52-a188a86dc6ba.jpg)

**Comment by hoaquynhtim99** [comment]
Cái này không phải là lỗi code, @hoanglongvnpt gửi lên group https://www.facebook.com/groups/nukeviet để được hỗ trợ. Hoặc đọc tài liệu trên wiki https://wiki.nukeviet.vn/nukeviet4:admin:settings:smtp

Trên đây thảo luận những vấn đề dành cho các nhà lập trình
