### ISSUE TITLE
Lỗi css js Quản lý File 

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3448]
Phiên bản 4.6 mới nhất xuất hiện lỗi css js Quản lý File 

![screenshot_1651115813](https://user-images.githubusercontent.com/82592373/165669606-b4c238d2-687e-4ea7-8142-ccb7a3b46db5.png)
chưa xác định được nguyên nhân

**Comment by tmsholdings** [comment]
@anhtunguyen có khi nào lỗi do phần Tệp cấu hình máy chủ mới thêm vào ko anh
trước đó vẫn chạy bình thường

**Comment by tmsholdings** [comment]
![screenshot_1651115988](https://user-images.githubusercontent.com/82592373/165669782-d6602447-7c8d-4cb6-874b-e55c95a3411f.png)

**Comment by anhtunguyen** [comment]
@tmsholdings Lỗi phát sinh từ việc sửa lại  file cdn_js_css_image.php. Để anh sửa

**Comment by anhtunguyen** [comment]
@tmsholdings Fix lỗi [ở đây](https://github.com/nukeviet/nukeviet/commit/2ca9e1b9b9fd0a26d814b5275da8b7010f03d5bb)
