### ISSUE TITLE
Lỗi ghi nhận IP trong class Error

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#3451]
Ở Class Error đang xác định IP qua REMOTE_ADDR

còn NV_CLIENT_IP xác định qua class Ips function nv_getip

NV_CLIENT_IP  --> đây là IP chính xác của người dùng nếu website dùng qua Proxy.

Vấn đề Class Error đang ghi theo REMOTE_ADDR nên ghi là IP của Proxy.

Cần thống nhất xác định IP ở 1 class duy nhất để tiện việc sửa chữa và debug

**Comment by anhtunguyen** [comment]
@vuthao OK. Để anh xem lại
