### ISSUE TITLE
Lỗi module search

### ISSUE THREAD

**Issue by loilarryhttn** [nukeviet/nukeviet#3452]
Tính năng search bị lỗi :
- Không tìm kiếm theo ngày được (hình 1), cụ thể: Em chọn ngày chỉ trong năm 2022 nhưng khi ra kết quả vẫn có năm 2010
![3](https://user-images.githubusercontent.com/71362414/167569081-88799403-9915-4244-ab39-e2e5dfbca90d.png)
![2 (2)](https://user-images.githubusercontent.com/71362414/167569150-0cb19859-cad6-47a5-bae3-9c47f1bc869d.png)
- Không cho tìm kiếm tất cả chủ đề ở phần tin tức (trang vinades thì tìm kiếm tất cả chủ đề được) (hình 2)
![1 (2)](https://user-images.githubusercontent.com/71362414/167569235-a56beb19-cf6b-4230-bb53-67cb67b83413.png)

**Mô tả các lựa chọn thay thế bạn đã xem xét**
Trang vinades > Cho phép tìm kiếm theo ngày
Trang vinades > Cho phép tìm kiếm tất cả chủ đề
![Untitled](https://user-images.githubusercontent.com/71362414/167569970-85ac4db8-86c9-4050-9b68-290b6cbaa06d.png)

**Comment by anhtunguyen** [comment]
@loilarryhttn Lỗi này chỉ tồn tại ở bản NukeViet4.4 trở xuống. Nó đã được fix ở bản 4.5.
Nếu bạn dùng 4.4, bạn có thể tự fix lỗi như [ở đây](https://github.com/nukeviet/nukeviet/commit/7fa5deea1ac6b9a7e1b355a2840f0d83e0a23dac)

**Comment by loilarryhttn** [comment]
> @loilarryhttn Lỗi này chỉ tồn tại ở bản NukeViet4.4 trở xuống. Nó đã được fix ở bản 4.5. Nếu bạn dùng 4.4, bạn có thể tự fix lỗi như [ở đây](https://github.com/nukeviet/nukeviet/commit/7fa5deea1ac6b9a7e1b355a2840f0d83e0a23dac)

có phần nào tải về module mới nhất luôn không anh, em dùng phiên bản cũng lâu rồi, giờ tự fix lỗi lại nó lại lỗi thêm!

**Comment by anhtunguyen** [comment]
@loilarryhttn Đơn giản bạn [copy nội dung ở đây](https://raw.githubusercontent.com/nukeviet/nukeviet/7fa5deea1ac6b9a7e1b355a2840f0d83e0a23dac/modules/news/funcs/search.php) và chép đè lên nội dung cũ của file modules/news/funcs/search.php

**Comment by loilarryhttn** [comment]
hình như phiên bản egov vẫn chưa được fix đó anh!

**Comment by loilarryhttn** [comment]
> @loilarryhttn Lỗi này chỉ tồn tại ở bản NukeViet4.4 trở xuống. Nó đã được fix ở bản 4.5. Nếu bạn dùng 4.4, bạn có thể tự fix lỗi như [ở đây](https://github.com/nukeviet/nukeviet/commit/7fa5deea1ac6b9a7e1b355a2840f0d83e0a23dac)

dạ em cám ơn anh! Sau khi thay đổi theo code thì có thể tìm được tất cả chủ đề, nhưng còn tìm kiếm theo ngày vẫn chưa được!
