### ISSUE TITLE
Lỗi bài viết ở trạng thái chuyển duyệt bài vẫn hiển thị phía bên ngoài website

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#3464]
NukeViet bản > 4.5.00

Bài viết trong phần tin tức chuyển ở trạng thái Chuyển duyệt bài. Nhưng nếu có link trực tiếp của bài viết đó thì người dùng không cần đăng nhập vẫn xem được bài viết đó

![image](https://user-images.githubusercontent.com/9360175/172080232-7d7cb13e-2e58-4813-adfc-4e652bdfbec7.png)

**Comment by hoaquynhtim99** [comment]
@anhtunguyen anh xem thử ạ, cái này em thử thấy đúng là lỗi.
