### ISSUE TITLE
Lỗi di chuyển bài viết trong News

### ISSUE THREAD

**Issue by CucGach** [nukeviet/nukeviet#3475]
**Mô tả lỗi**
Muốn di chuyển bài viết từ Chuyên mục A sang Chuyên mục B sẽ lỗi, phiên bản Nukeviet 4.5.02

Error on file /modules/news/admin/move.php line 108:
Uncaught Error: Function name must be a string in /home/chuye277/public_html/modules/news/admin/move.php:108
Stack trace:
#0 /home/chuye277/public_html/cms/index.php(182): require()
#1 {main}
  thrown

**Comment by tmsholdings** [comment]
Tìm dòng 108     'checked' => (in_array((int) $catid_i, $array_map('intval', $catids), true)) ? ' checked="checked"' : '', 
sửa thành     'checked' => (in_array((int) $catid_i, array_map('intval', $catids), true)) ? ' checked="checked"' : '',

**Comment by hoaquynhtim99** [comment]
Fixed: 
- https://github.com/nukeviet/nukeviet/commit/55ffb8c30b0dc1019840ff1a341e74cf3ed7adae
- https://github.com/nukeviet/nukeviet/commit/76bf8e6ccfe4da9532f095754b2f216f3d87967c
