### ISSUE TITLE
Module Văn bản không hiển thị danh sách văn bản trong phần thể loại

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#3479]
**Mô tả lỗi**
Module văn bản khi cài trên NukeViet 4.5 không hiển thị danh sách các văn bản trong phần thể loại

**Thao tác dẫn đến lỗi**
1. Đăng văn bản mới
2. Chọn thể loại cho văn bản
3. Điền đầy đủ thông tin lưu lại
4. Ra ngoài xem danh sách trong thể loại văn bản không thấy có văn bản nào

**Ảnh chụp màn hình**
![image](https://user-images.githubusercontent.com/9360175/177242740-c863cc45-ef97-4675-89cf-5410d53ff0d1.png)
![image](https://user-images.githubusercontent.com/9360175/177242767-2a663f6f-4d2b-48cc-8e63-74244191e388.png)

**Comment by hoaquynhtim99** [comment]
Đã sửa

**Comment by hoaquynhtim99** [comment]
@nambmtk1993 tạo issue nhầm kho code
