### ISSUE TITLE
Cải tiến lại đoạn code trong module freecontent

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#3484]
Trong module freecontent đang có đoạn text chưa được gán vào lang của module mà viết trực tiếp vào file php

https://github.com/nukeviet/nukeviet/blob/f7d0207a84a12849b6a48d46e2ccf82c6d1bebf1/modules/freecontent/admin/main.php#L31

https://github.com/nukeviet/nukeviet/blob/f7d0207a84a12849b6a48d46e2ccf82c6d1bebf1/modules/freecontent/admin/main.php#L61

**Comment by hoaquynhtim99** [comment]
@nambmtk1993 cái này không cần thiết vì trong điều kiện hoạt động bình thường thì không có message đó. Message đó chỉ xảy ra nếu người dùng cố tình gửi dữ liệu lỗi lên
