### ISSUE TITLE
THêm Tính năng báo lỗi nội dung cho bài viết cho Nukeviet

### ISSUE THREAD

**Issue by vingheo** [nukeviet/nukeviet#3495]
Mình đọc nội dung bài viết của trang [https://thuvienphapluat.vn/](url) thấy tính năng báo nỗi nội dung rất hay, ứng dụng trong thực tế rất tốt. Đội code tham khảo.
![1](https://user-images.githubusercontent.com/22491878/186323611-367dc655-ce74-402c-98d2-93024bcb2ee9.jpg)

**Comment by anhtunguyen** [comment]
@vingheo Cảm ơn bạn đã mách bảo.
Chúng tôi đã thêm tính năng báo cáo lỗi cho module News ở NukeViet 4.6:
https://github.com/nukeviet/nukeviet/commit/0ac1b894e29b854039cd310c150292146f936682
Xem ghi chú ở đây:
https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.6#12112022-th%C3%AAm-t%C3%ADnh-n%C4%83ng-b%C3%A1o-c%C3%A1o-l%E1%BB%97i-cho-module-news
