### ISSUE TITLE
Module users tùy biến dữ liệu đã chọn không bắt buộc nhưng khi tạo user mới vẫn buộc nhập

### ISSUE THREAD

**Issue by loveall123** [nukeviet/nukeviet#3497]
fields.check.php trong module users tùy biến dữ liệu select, chặn luôn trường hợp $row_f['required'] == 0, mong đội code chỉnh lại lỗi này.

**Comment by hoaquynhtim99** [comment]
Không biết bạn dùng phiên bản nào và tạo field đó như thế nào? Mình thử trên bản 4.5.04 không thấy bị vấn đề như thế

**Comment by hoaquynhtim99** [comment]
Closed issue because there has been no response for a long time
