### ISSUE TITLE
Thêm nút hiện mật khẩu khi đăng nhập và index tiêu đề thân thiện với trình tìm kiếm

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#3498]
- Hiện tại NukeViet không có nút hiển thị mật khẩu khi đăng nhập. Vui lòng cập nhật nút này để người dùng xem mình đã nhập đúng mật khẩu hay chưa.
- Hiện nay NukeViet bị các trình tìm kiếm index không đúng tiêu đề (title) của bài viết, mà nó index một cách lung tung. Mong rằng đội ngũ code nghiên cứu kỹ vấn đề này. Cảm ơn!

**Comment by thehung** [comment]
1. Ok
2. Google đã có thông báo là nó không chọn tiêu đề bài viết làm tiêu đề index. Việc này ko có cách gì can thiệp được ngoại trừ việc bạn cần viết nội dung cho phù hợp và đặt tiêu đề hợp lý rồi cầu cho Google nó hiểu ý mình thôi 🙄

**Comment by truongemcom** [comment]
2. Anh xem qua WP nó index chính xác title và link trên dữ liệu tìm kiếm nhé a

**Comment by anhtunguyen** [comment]
> * Hiện tại NukeViet không có nút hiển thị mật khẩu khi đăng nhập. Vui lòng cập nhật nút này để người dùng xem mình đã nhập đúng mật khẩu hay chưa.

Việc thêm nút ẩn/hiện mật khẩu vào form đăng nhập không khó. Anh chỉ lăn tăn không thể quyết định được là nếu thêm cũng đồng nghĩa với việc dễ bị lộ mật khẩu.
