### ISSUE TITLE
Lỗi khi điền alias đằng sau topic của module news -> trắng trang

### ISSUE THREAD

**Issue by nctoon2308** [nukeviet/nukeviet#3499]
**Mô tả lỗi**
Lỗi khi điền alias đằng sau topic của module news

**Thao tác dẫn đến lỗi**
Các bước để thấy lỗi:
1. Đi tới **domain/news/topic/** thì được
2. Thêm alias đằng sau thì lỗi trắng trang, ví dụ: **domain/news/topic/ha-noi/**

**Thông tin bổ sung**
Hiện tại em thử trên ver 4.5.01 thì báo lỗi.

**Comment by anhtunguyen** [comment]
@nctoon2308 Tôi thử tạo topic "Hà Nội" và truy cập vào domain/news/topic/ha-noi/ vẫn thấy bình thường.
Môi trường của máy chủ thế nào bạn?

**Comment by hoaquynhtim99** [comment]
@nctoon2308 đã 4 tháng mà không có phản hồi nên chúng tôi đóng issue này lại. Nếu bạn tiếp tục gặp vấn đề này có thể vào thư mục data/logs/error_logs gửi nội dung lên đây để chúng tôi kiểm tra.
