### ISSUE TITLE
Lỗi: Đường dẫn liên kết trong phần menu site quá dài sẽ không còn nhìn thấy cột chức năng

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#3500]
**Mô tả lỗi**
Mô tả rõ ràng và ngắn gọn về lỗi là gì.

**Thao tác dẫn đến lỗi**
Đường dẫn liên kết trong menu site nếu nhập một đường link quá dài thì bảng sẽ không nhìn được cột chức năng nữa

**Kết quả mong đợi**
Với các menu site có link có thể để icon link hoặc chữ link. Hover vào sẽ thấy link đó

**Ảnh chụp màn hình**
![image (1)](https://user-images.githubusercontent.com/9360175/194010732-94a52a9a-aeca-4d7e-85d5-ea2d43e04ec8.png)

**Comment by anhtunguyen** [comment]
Đã [fix cho NV4.6](https://github.com/nukeviet/nukeviet/commit/ce43813c797e780be67eac61c251d91a18a074c3)
