### ISSUE TITLE
Cảnh báo nếu xóa thủ công API

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3502]
1 API trước đó đã cấp quyền trong API Roles nếu quản trị xóa file API đi thì vào phần cấu hình API Roles sẽ bị cảnh báo như sau

```
Nên chú ý: Undefined index: XXXXX in file /admin/authors/api-roles.php on line 55
```

**Comment by anhtunguyen** [comment]
Ở NukeViet 4.5 hả em?
