### ISSUE TITLE
Lỗi trắng trang khi truy cập lần đầu Phiên bản nukeviet 4.6 mới nhất

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3503]
Phiên bản nukeviet 4.6 mới nhất
Php phiên bản 7.4
Truy cập website hoặc admin xuất hiện trắng trang xem log lỗi thì báo thế này
có tồn tại file: data/config/config_ini.https.nukeviet.vnn.php
@anhtunguyen check giùm em lỗi này với nha, cảm ơn anh
---------------
[Thu, 27 Oct 2022 19:04:29 +0000] [nukeviet.vnn] [127.0.0.1] [Warning(2): include_once(F:/TMS2022/www/nukeviet.vnn/data/config/config_ini.https.nukeviet.vnn.php): failed to open stream: No such file or directory] [FILE: /includes/ini.php] [LINE: 364] [REQUEST: /]
[Thu, 27 Oct 2022 19:04:29 +0000] [nukeviet.vnn] [127.0.0.1] [Error(1): Uncaught Error: Call to undefined function str_starts_with() in F:\TMS2022\www\nukeviet.vnn\includes\ini.php:329
Stack trace:
#0 F:\TMS2022\www\nukeviet.vnn\includes\ini.php(368): set_ini_file()
#1 F:\TMS2022\www\nukeviet.vnn\includes\mainfile.php(86): require('F:\\TMS2022\\www\\...')
#2 F:\TMS2022\www\nukeviet.vnn\index.php(38): require('F:\\TMS2022\\www\\...')
#3 {main}
  thrown] [FILE: /includes/ini.php] [LINE: 329] [REQUEST: /]

**Comment by anhtunguyen** [comment]
@tmsholdings Lỗi này xảy ra khi truy cập file ini.php đối với các máy chủ có phiên bản php thấp (không hỗ trợ hàm str_starts_with).
Em cập nhật lại code [ở đây](https://github.com/nukeviet/nukeviet/commit/012efb1a243a63551583c1f9b4646509a429c3e5) và [ở đây](https://github.com/nukeviet/nukeviet/commit/ac4ef61cbc144d7f23376086b9c628ff449f58c5) nhé
