### ISSUE TITLE
Chức năng quản lý block không thể bật block đã tắt trong Admin Control Panel 

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#3514]
**Vấn đề**
Hiện tại, nếu block có chức năng đặt thời gian hết hạn bằng cách chọn ngày, tuy nhiên sửa ngày thì block không hiển thị lại!

Nguyên nhân là tính năng đặt thời gian hết hạn sử dụng "ké" tính năng bật/ tắt block ở ngoài site (quá thời gian hết hạn thì tắt nhưng nếu chỉnh lại thời gian thì "quên" bật lại)

![image](https://user-images.githubusercontent.com/1892900/199522851-0ab76f46-91f3-4190-89e2-91e714bf80d3.png)

**Mô tả giải pháp mong muốn**

1.  Cần bổ sung chức năng "bật/ tắt" block khi sửa block.

2.  Bổ sung chức năng hẹn giờ bật (nếu đang tắt) hoặc tắt (nếu đang bật). Nếu được thì có thể cho bật/ tắt đồng thời hoặc theo chu kỳ nhất định (tương tự lên lịch lặp lại của Google Calendar). Ví dụ bật hàng ngày lúc 8h sáng và tắt hàng ngày lúc 8h tối.  

![image](https://user-images.githubusercontent.com/1892900/199523634-995be889-9624-4e85-9f60-feaf00235dbc.png)
![image](https://user-images.githubusercontent.com/1892900/199523811-b0a42ef5-e115-4c4a-8af0-67602e9a69fb.png)

3.  Sắp xếp và Bổ sung chức năng bật/ tắt block trong Admin Control Panel:

![image](https://user-images.githubusercontent.com/1892900/199525187-777b33b5-8cb7-4597-9eb6-d8ef273858c1.png)

- [ ]  Dồn 2 cột  "Tên block" và "File" thành cột "Tên block & tên file" (ảnh trên)
- [ ]  Thêm chức năng Bật (Tắt) block vào cột "Chức năng" (nếu đang bật thì hiện nút tắt, đang tắt thì hiện nút bật)  (ảnh trên)
- [ ]  Thêm chức năng Bật (Tắt) block vào các menu thao tác hàng loạt cuối trang (ảnh dưới)  
![image](https://user-images.githubusercontent.com/1892900/199525731-3dc98395-2105-481f-bcfc-f082eb708c0a.png)
- [ ]  Thêm menu thao tác hàng loạt (các nút thao tác như ở ảnh trên) lên bên trên bảng (vị trí ảnh dưới) để tiện thao tác
![image](https://user-images.githubusercontent.com/1892900/199525992-58cd0faa-7b27-4cfa-be24-4b2ba37c2c7b.png)

**Comment by anhtunguyen** [comment]
Anh đã thêm Quản lý thời gian hiển thị của block vào NukeViet 4.6:
Admin có thể chọn một trong những hình thức hiển thị block sau đây:
- Hiển thị thường xuyên
- Hiển thị trong khoảng thời gian được xác định cụ thể
- Hiển thị hàng ngày (trong khoảng thời gian được xác định cụ thể)
- Hiển thị hàng tuần (trong khoảng thời gian được xác định cụ thể)
- Hiển thị hàng tháng (trong khoảng thời gian được xác định cụ thể)
- Hiển thị hàng năm (trong khoảng thời gian được xác định cụ thể).

Đã thêm nút Bật/tắt vào popup tạo/sửa block và trang quản lý block trong ACP.

**Comment by thehung** [comment]
Vâng anh!
