### ISSUE TITLE
NukeViet 4.6 cần thêm một hook gửi email

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3516]
Trước [dòng này](https://github.com/nukeviet/nukeviet/blob/nukeviet4.6/includes/functions.php#L1433) nhu cầu cần bổ sung một hook để thực thi các lệnh như

```php
$mail->addCustomHeader('References', '<EmailIDRefID@mydomain.com>');
```

Để nhóm các dòng email tùy theo nhu cầu. Hiện mỗi email gửi đi không có header References và header Message-ID của nó luôn làm mới do đó không thể nhóm email vào cuộc hội thoại như ý muốn

**Comment by anhtunguyen** [comment]
https://github.com/nukeviet/nukeviet/commit/9aa4d11e4e3d4d7c1b4501952ef351adfa1f5388
