### ISSUE TITLE
Thay đổi cách quản lý API

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#3518]
Hiện tại API đang quản lý dựa theo tài khoản  của quản trị trong Admin

1) Trong nhiều trường hợp cần cung cấp API cho tài khoản thông thường:  Do đó lúc cấp quyền Thêm quyền truy cập API, thay vì chọn Quản trị, có thể chọn tài khoản  (Tương tự việc thêm tài khoản quản trị:  admin/index.php?nv=users&op=getuserid&area=userid&return=username).

2)  Tính toán bố trí CSDL cho người dùng đăng ký sử dụng các API public
- Giới hạn các API được gọi (có thể thông qua Qua các API Roles)
- Lúc này có thể anh sách Quyền truy cập API sẽ rất nhiều nếu hiển thị trong admin

**Comment by vuthao** [comment]
Trong phần danh sách Quyền truy cập API admin/index.php?language=vi&nv=authors&op=api-credentials

Hiện không có chắc nâng bật tắt quyền truy cập, Bất tiện trong việc cấp quyền (Ví dụ chưa đóng tiền dùng API, phải tắt tạm, nhưng không có, giờ chỉ có cách xóa đi, sau đó thêm lại, bên dùng API sẽ phải khai báo lại gây bất tiện)

**Comment by anhtunguyen** [comment]
Đã thực hiện với NukeViet 4.6 [tại đây](https://github.com/nukeviet/nukeviet/commit/01830939907165fda6d8af3624f621a52857c808)
