### ISSUE TITLE
Bổ sung thuộc tính cần có cho OG:Image

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3522]
Thiếu thẻ meta: og:image:alt

Cần bổ sung cho NukeViet 4.5 nữa

**Comment by hoaquynhtim99** [comment]
Đã bổ sung cho NukeViet 4.5 chưa làm cho các phiên bản khác

**Comment by anhtunguyen** [comment]
Đã thêm vào [NukeViet 4.6](https://github.com/nukeviet/nukeviet/commit/bd78600c3b58b481c090049960db3b237c915ea3)
Ở NukeViet 4.4 không được thêm vào.
