### ISSUE TITLE
Bug: Sửa thông báo khi khách hàng tạo một tài khoản trùng với tài khoản chờ kích hoạt

### ISSUE THREAD

**Issue by daiubqn113** [nukeviet/nukeviet#3530]
**Mô tả lỗi**
- Đăng ký tài khoản (chờ kích hoạt ở mail)
- Đăng ký một tài khoản trùng với tài khoản chờ kích hoạt thì có thông báo `tài khoản ... có người sử dụng rồi. Bạn có thể dùng chức năng quên mật khảu để lấy lại mật khẩu`
-> Sửa lại thông báo  `Rất tiếc, địa chỉ email này đã được sử dụng`
* **Lưu ý** Tình huống này hoặc là sửa lại cho đúng, hoặc mọi người sợ bị khai thác thì có thể xóa đi. Tùy mọi người quyết định

![image](https://user-images.githubusercontent.com/59864736/207506254-ce89b4eb-8049-4d8b-8de4-3f86bb356bdc.png)

**Comment by anhtunguyen** [comment]
@daiubqn113 Theo tôi, vì lý do bảo mật thông tin, hệ thống không nên đưa ra thông báo chi tiết là email đó đã được gán với user nào đó hay đang chờ kích hoạt. Chỉ đơn giản: Email đã được sử dụng thôi bạn.

**Comment by daiubqn113** [comment]
@anhtunguyen Em cập nhật lại issues. Anh xem được chưa ạ
