### ISSUE TITLE
NukeViet 4.5: Lỗi trên PHP 5.6

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3531]
Mô tả:

- Vào link /admin/ để đăng nhập quản trị
- Nhập user/pass ấn đăng nhập thì lỗi

```
Error on file /vendor/vinades/nukeviet/Core/Request.php line 1715:
Call to undefined function NukeViet\Core\session_create_id()
```

**Comment by anhtunguyen** [comment]
[Fixed](https://github.com/nukeviet/nukeviet/commit/f0f237db914eeddd3ebbeefedfc607bbaba5e6c8)
