### ISSUE TITLE
Lỗi cài đặt NV 4.5.03

### ISSUE THREAD

**Issue by vingheo** [nukeviet/nukeviet#3535]
**Mô tả lỗi**
Khi tải NV về cài, mặc định cài đặt là tiếng Anh. Nếu chuyển cài đặt bằng tiếng Việt thì khi cài đặt xong bị lỗi: "Khi nhấp vào link bài viết thì ko vào đc nội dung bài viết mà ra trang chủ. Tạo bài viết mới cũng vậy...."
**Máy tính để bàn (vui lòng điền đầy đủ thông tin sau):**
  - Hệ điều hành: Windows 11 64bit
  - Trình duyệt: chrome, Coccoc
  - The AppServ Open Project - 9.3.0 for Windows:
 [Apache Web Server](http://httpd.apache.org/)[ Version 2.4.41](http://httpd.apache.org/)
[PHP Script Language](http://www.php.net/)[ Version 7.3.10](http://www.php.net/)
[MySQL Database](http://www.mysql.com/)[ Version 8.0.17](http://www.mysql.com/)
[phpMyAdmin Database Manager](http://www.phpmyadmin.net/)[ Version 4.9.1](http://www.phpmyadmin.net/)

**Thông tin bổ sung**
Thêm bất kỳ thông tin nào khác về vấn đề ở đây.

**Comment by anhtunguyen** [comment]
@vingheo thử vào don dẹp hệ thống:
admin/index.php?language=vi&nv=webtools&op=clearsystem

**Comment by vingheo** [comment]
Đúng là có vấn đề: mình cũng đã dọn dẹp hệ thống cũng ko đc.
Mình còn cài đặt phiên bản 4.5.02 thi chạy ok. Sau đó nâng cấp lên 4.5.03 thì bị lỗi như trên (các link từ bài viết đến modun chuyền thành ........../index.php)

**Comment by hoaquynhtim99** [comment]
@vingheo bạn chép nội dung file .htaccess lên đây thử nhé

**Comment by hoaquynhtim99** [comment]
Bạn có cài vào subfoloder không hay là root? Domain dạng http://localhost/index.php hay là http://localhost/nukeviet/index.php

**Comment by vingheo** [comment]
**- Nội dung file .htaccess:**
```
#nukeviet

<Files ~ "\.(htm|html|css|js|php)$">
  AddDefaultCharset UTF-8
</Files>

##################################################################################
#nukeviet_config_start //Please do not change the contents of the following lines
##################################################################################

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteCond %{REQUEST_FILENAME} /(\.(.*)|composer\.json|default\.(htaccess\.txt|web\.config\.txt|php)|mainfile\.php|web\.config|config\.php)$ [NC]
  RewriteRule ^.* - [L,R=404]
  RewriteCond %{REQUEST_URI} ^/(data/ip6?|includes|install/tpl|vendor|assets/tpl|data/cache|data/certs|data/logs)/.* [NC]
  RewriteRule ^.* - [L,R=404]
  RewriteCond %{REQUEST_URI} ^/(admin)/.*/.*$ [NC]
  RewriteRule ^.* - [L,R=404]
  RewriteCond %{REQUEST_URI} ^/(install/(css|images)|modules|themes|assets|data/config|data/tmp|uploads)/.*\.((j|a)spx?|(p|s)html|cgi|inc|ini|php|pl|py|sh|sql\.gz|tpl|xml)($|\?|\/) [NC]
  RewriteRule ^.* - [L,R=404]
</IfModule>

ErrorDocument 400 /error.php?code=400&nvDisableRewriteCheck=1
ErrorDocument 403 /error.php?code=403&nvDisableRewriteCheck=1
ErrorDocument 404 /error.php?code=404&nvDisableRewriteCheck=1
ErrorDocument 405 /error.php?code=405&nvDisableRewriteCheck=1
ErrorDocument 408 /error.php?code=408&nvDisableRewriteCheck=1
ErrorDocument 500 /error.php?code=500&nvDisableRewriteCheck=1
ErrorDocument 502 /error.php?code=502&nvDisableRewriteCheck=1
ErrorDocument 503 /error.php?code=503&nvDisableRewriteCheck=1
ErrorDocument 504 /error.php?code=504&nvDisableRewriteCheck=1

<IfModule mod_deflate.c>
  <FilesMatch "\.(css|js|xml|ttf)$">
    SetOutputFilter DEFLATE
  </FilesMatch>
</IfModule>

<IfModule mod_headers.c>
  <FilesMatch "\.(js|css|xml|ttf|pdf)$">
    Header append Vary Accept-Encoding
    Header set Access-Control-Allow-Origin "*"
    Header set X-Frame-Options "SAMEORIGIN"
    Header set X-Content-Type-Options "nosniff"
    Header set X-XSS-Protection "1; mode=block"
  </FilesMatch>

  <FilesMatch "\.(doc|pdf|swf)$">
    Header set X-Robots-Tag "noarchive, nosnippet"
  </FilesMatch>

  <FilesMatch "\.(js|css|jpe?g|png|gif|webp|swf|svg|ico|woff|ttf|xsl|pdf|flv|mp3|mp4)(\?[0-9]{9,11})?$">
    Header set Cache-Control 'max-age=2592000, public, no-cache="set-cookie"'
  </FilesMatch>
</IfModule>

#nukeviet_config_end
##################################################################################

##################################################################################
#nukeviet_rewrite_start //Please do not change the contents of the following lines
##################################################################################

#Options +FollowSymLinks

<IfModule mod_rewrite.c>
RewriteEngine On
#RewriteBase /
RewriteCond %{REQUEST_METHOD} !^(POST) [NC]
RewriteRule ^api\.php(.*?)$ - [F]
RewriteCond %{REQUEST_FILENAME} /robots.txt$ [NC]
RewriteRule ^ robots.php?action=%{HTTP_HOST} [L]
RewriteRule ^(.*?)sitemap\.xml$ index.php?nv=SitemapIndex [L]
RewriteRule ^(.*?)sitemap\-([a-z]{2})\.xml$ index.php?language=$2&nv=SitemapIndex [L]
RewriteRule ^(.*?)sitemap\-([a-z]{2})\.([a-zA-Z0-9-]+)\.xml$ index.php?language=$2&nv=$3&op=sitemap [L]
RewriteRule ^(.*?)sitemap\-([a-z]{2})\.([a-zA-Z0-9-]+)\.([a-zA-Z0-9-]+)\.xml$ index.php?language=$2&nv=$3&op=sitemap/$4 [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule (.*)(\/|\.html)$ index.php
RewriteRule (.*)tag\/([^?]+)$ index.php
RewriteRule ^([a-zA-Z0-9-\/]+)\/([a-zA-Z0-9-]+)$ /$1/$2/ [L,R=301]
RewriteRule ^([a-zA-Z0-9-]+)$ /$1/ [L,R=301]
</IfModule>

#nukeviet_rewrite_end
##################################################################################
```

**Comment by vingheo** [comment]
> Bạn có cài vào subfoloder không hay là root? Domain dạng http://localhost/index.php hay là http://localhost/nukeviet/index.php
Của mình dạng này: **http://localhost/nukeviet/index.php**

**Comment by hoaquynhtim99** [comment]
@vingheo bạn cài vào sub thì ở phiên bản này đang lỗi tí. Bạn đăng nhập quản trị và cấu hình => Thiết lập an ninh ấn lưu lại 1 cái là được.

Nó đã được fix ở đây https://github.com/hoaquynhtim99/nukeviet/commit/ac60ede929f3e6ba6a09dfffa21018cd874132f1

**Comment by vingheo** [comment]
> @vingheo bạn cài vào sub thì ở phiên bản này đang lỗi tí. Bạn đăng nhập quản trị và cấu hình => Thiết lập an ninh ấn lưu lại 1 cái là được.
> 
> Nó đã được fix ở đây [hoaquynhtim99@ac60ede](https://github.com/hoaquynhtim99/nukeviet/commit/ac60ede929f3e6ba6a09dfffa21018cd874132f1)

Mình đã làm lại theo 2 cách thì vẫn như vậy. Mình cũng thử cài NV 4.6 tình trạng vẫn vậy

**Comment by hoaquynhtim99** [comment]
@vingheo bạn đã khắc phục được chưa nhỉ? Hiện còn chỗ nào bị không gửi thông tin mình check trực tiếp thử

**Comment by hoaquynhtim99** [comment]
Close do lâu không có phản hồi, nếu bạn vẫn còn đang gặp vui lòng mở lại mình cùng nhau gỡ tiếp
