### ISSUE TITLE
Lỗi khi nhấp vào từng đường link

### ISSUE THREAD

**Issue by hades-1997** [nukeviet/nukeviet#3537]
Sau khi cài đặt xong thì e nhấp vào link bài viết bị chuyển hướng 
![image](https://user-images.githubusercontent.com/70182883/209770591-677ac719-fdc2-4d88-94d1-06ca51d1f530.png)

**Comment by hoaquynhtim99** [comment]
Cái này có lỗi tí, bạn đăng nhập quản trị và cấu hình => Thiết lập an ninh ấn lưu lại 1 cái là được
