### ISSUE TITLE
Không cập nhật được phiên bản 4.5.03 từ 4.4.0.6

### ISSUE THREAD

**Issue by sondoan1204** [nukeviet/nukeviet#3539]
**Mô tả lỗi**
Không tương thích phiên bản

**Thao tác dẫn đến lỗi**
Cập nhật bằng cách thủ công, download file upto về. cả 3 phiên bản đều báo không tương thich

**Kết quả mong đợi**
Muôn lên bản 4.5.03 từ bản 4.4.06

**Comment by hades-1997** [comment]
Hạ xuống 4.4.02 cập nhật thủ công lên. trước e làm vậy

**Comment by hoaquynhtim99** [comment]
Bạn làm theo hướng dẫn này https://nukeviet.vn/vi/news/nhom-phat-trien/huong-dan-cap-nhat-nukeviet-4-4-x-len-4-5-711.html
