### ISSUE TITLE
Lỗi khi đăng bài có nội dung kèm class="..." trong văn bản

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/nukeviet#3548]
Lỗi này chặn không cho đăng nội dung bài viết ở các module sử dụng trình soạn thảo ckeditor sẽ ra cảnh báo lỗi error code 403.

Nguyên do là khi trong văn bản có các thẻ html mà kèm theo class=".." thì  sẽ bị chặn không đăng được bài. Cách đơn giản ví dụ là nhúng link video youtube sau đó tùy chọn responsive các thứ để có class thì sẽ đưa ra 403 không cho đăng bài, sử dụng iframe ko có class gì thì không bị làm sao hết.
Phiên bản lỗi này là nukeviet 4.5.03, các phiên bản khác chưa kiểm tra chưa rõ

**Comment by hoaquynhtim99** [comment]
Cần mô tả cụ thể hơn ví dụ mã HTML đang dùng để đăng là như thế nào.

**Comment by hoaquynhtim99** [comment]
Hơn 1 năm không thấy tác giả mô tả thêm nên close issue lại. Nếu tác giả vẫn còn gặp mở lại issue và gửi mô tả thêm để kiểm tra lại
