### ISSUE TITLE
Thay đổi định dạng tên các file log lỗi

### ISSUE THREAD

**Issue by danlt150** [nukeviet/nukeviet#3552]
Nên thay đổi định dạng tên các file log lỗi theo dạng `Y-m-d` để file tự động sắp xếp theo thứ tự thời gian, thuận tiện hơn cho việc check lỗi

**Comment by hoaquynhtim99** [comment]
+1

**Comment by vuthao** [comment]
+1

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/0da8d8a750a1b9fc96c105daab1befb5aa456aab
