### ISSUE TITLE
Nghiên cứu error class có thể show các lỗi 500 internal server error

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3558]
Ví dụ trong 1 file php xóa dấu `;` cuối dòng để lỗi cú pháp thì nếu sửa như https://writeblabla.com/blog/hien-thi-bao-loi-khi-website-bi-loi-500-internal-server-error.html thì nó hiển thị lỗi còn [error class](https://github.com/nukeviet/nukeviet/blob/nukeviet4.5/vendor/vinades/nukeviet/Core/Error.php#L173) nó không hiển thị

**Comment by vuthao** [comment]
Cách sửa TẠM như sau: mở file includes\mainfile.php

Tìm đến dòng
```php
require NV_ROOTDIR . '/vendor/autoload.php';
```

Thêm lên trên nó đoạn sau:
```php
register_shutdown_function("fatal_handler");
function fatal_handler()
{
    $error = error_get_last();
    if (NV_DEBUG == 1 and $error !== NULL) {
        echo ('<pre><code>' . print_r($error, true) . '</code></pre>');
    }
```

**Comment by anhtunguyen** [comment]
@vuthao Trong class Error của mình đã có sẵn hàm shutdown rồi nên không cần thêm như trên. Đơn giản là tìm đến dòng 399:
```php
if (!empty($error) and $error['type'] === E_ERROR) {
```
Sửa thành:
```php
if (!empty($error) and ($error['type'] === E_ERROR | E_PARSE)) {
```

**Comment by anhtunguyen** [comment]
Đã fix trong code: https://github.com/nukeviet/nukeviet/commit/be6134d3265a5b714aa94b782cc2fc9aceff96f7
