### ISSUE TITLE
Module Users: Đa ngôn ngữ phần tùy biến dữ liệu

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#3561]
Hiện tại phần tùy biến dữ liệu với các loại dữ liệu lấy dữ liệu từ nhập liệu, hoặc csdl thì đều bị fix cứng giá trị -> dẫn đến khi sang ngôn ngữ khác vẫn hiển thị giá trị của ngôn ngữ được cấu hình

![image](https://user-images.githubusercontent.com/10300770/220807620-6550685c-b5ec-48f2-bf40-583d5be073d7.png)

**Comment by anhtunguyen** [comment]
Đã cập nhật tại đây https://github.com/nukeviet/nukeviet/commit/a09c5c62f940304a41908b22304e76a61d2d0aea

Lưu ý khi cập nhật:
Bước 1: Sao lưu CSDL (bảng nv4_users_field)
Bước 2: Cập nhật như trên
Bước 3: Vào khu vực quản lý dữ liệu tùy biến và khai báo lại (nếu cần) và click vào nút "Lưu" (Bắt buộc)
