### ISSUE TITLE
Bổ sung tính năng cài đặt schema Hộp tìm kiếm

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#3562]
Bổ sung tính năng cài đặt schema Hộp tìm kiếm cho đường liên kết trang web cho NukeViet CMS

**Comment by anhtunguyen** [comment]
@htuyen1994 Cái này liên quan đến tích hợp tìm kiếm của Google?

**Comment by hoaquynhtim99** [comment]
@anhtunguyen cái này Tuyên nó viết mô tả không rõ ràng. Đây anh ạ https://developers.google.com/search/docs/appearance/structured-data/sitelinks-searchbox?hl=vi
