### ISSUE TITLE
Lỗi login openid khi sử dụng chung 1 email

### ISSUE THREAD

**Issue by thangbv** [nukeviet/nukeviet#3563]
**Lỗi chức năng openid của module users**
Tại bảng `users_openid` phần email đang để khóa key vì vậy sẽ có lỗi trong trường hợp sau:

**Thao tác dẫn đến lỗi**
Emai đăng ký facebook & google là 1 nếu họ vừa dùng facebook để login xong lần sau login bằng google nữa sẽ lỗi trùng lặp email
**Đề xuất xử lý**
Tạo khóa key = 2 cột: email & openid
**Lưu ý trường hợp ứng dụng openid không trả về email**
Thường trên facebook sẽ có tài khoản đăng ký bằng số điện thoại hiện tại openid đang trả ra lỗi

**Comment by hoaquynhtim99** [comment]
@thangbv @anhtunguyen cái này anh Thắng nhầm hay sao ấy a hoặc là phiên bản cũ. Chứ index để tối ưu khi thực hiện SQL nó đâu có ràng buộc unique, bỏ index thì truy vấn chậm hơn trong một số trường hợp. Bảng đó unique 2 trường openid, opid.

openid = tên nhà cung cấp
opid = hash (ID trả về)

Chứ không liên quan email.

**Comment by anhtunguyen** [comment]
@thangbv anh đã tìm ra lỗi. Em cập nhật và kiểm tra xem còn không nhé
