### ISSUE TITLE
[NukeViet 4.6] Lỗi không thể kích hoạt tài khoản trong quản trị

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3575]
Tại khu vực: `/admin/index.php?language=vi&nv=users&op=user_waiting`  
Lỗi khi: Tại phần tùy biến dữ liệu, mục ngày sinh không bắt buộc nhập khi đăng ký => nó bị rỗng

Ngoài ra khi xóa tài khoản có cảnh báo

```
[Notice(8): Undefined index: userid] [FILE: /modules/users/admin/del.php] [LINE: 75]
```

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Anh kiểm tra không thấy lỗi "Lỗi khi: Tại phần tùy biến dữ liệu, mục ngày sinh không bắt buộc nhập khi đăng ký => nó bị rỗng"
Em cập nhật lại code lên bản mới nhất xem sao nhé.
Mô tả lại lỗi đó rõ hơn chút.

**Comment by hoaquynhtim99** [comment]
@anhtunguyen em thấy anh có commit rồi chắc là đã sửa rồi á a.

Lỗi ở đây ý là nếu phần tùy biến dữ liệu chỉnh lại ngày sinh từ bắt buộc nhập khi đăng ký thành không bắt buộc (hoặc không bắt buộc và ẩn khi đăng ký). Khi người dùng đăng ký ngoài site, quản trị vào kích hoạt sẽ không kích hoạt được, trường birthdate báo lỗi Incorect double value ....

Quản trị nhận được thông báo DB-error1
