### ISSUE TITLE
Lỗi cảnh báo ở quản trị module contact mục nhân viên hỗ trợ

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3579]
Nếu không có phòng ban nào, vào đó có một số lỗi cảnh báo như ảnh

![3 (1)](https://user-images.githubusercontent.com/2421714/226168119-a54fe6a3-0110-4bfa-be38-ef24c84dc718.PNG)

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Không rõ bạn nào viết cái này. Đọc nó xong chỉ muốn viết lại

**Comment by hoaquynhtim99** [comment]
> @hoaquynhtim99 Không rõ bạn nào viết cái này. Đọc nó xong chỉ muốn viết lại

Cái này Triển làm ấy anh.
