### ISSUE TITLE
Lỗi không hiện thị giọng đọc module news

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3580]
Không biết tính năng này đã hoàn thiện chưa tuy nhiên không thể hiện thị phần uploads file giọng đọc trong admin news, mặc dù kiểm tra xem có phần cấu hình thì cũng khống có. phiên bản nukeviet 4.6 mới nhất
@hoaquynhtim99 @anhtunguyen

**Comment by hoaquynhtim99** [comment]
@tmsholdings bạn để chuột vào menu **Cấu hình** module tại module news sẽ có menu thiết lập giọng đọc. Sau khi thiết lập giọng đọc xong đăng bài trong phần **Tùy chọn nâng cao**  mới có chỗ điền audio
