### ISSUE TITLE
Báo lỗi Call to undefined function get_value_by_lang() chưa định nghĩa css cho oauth google-identity

### ISSUE THREAD

**Issue by tmsholdings** [nukeviet/nukeviet#3581]
Nukeviet 4.6 bản mới nhất
Call to undefined function get_value_by_lang() in /modules/users/blocks/global.login.php
Không định nghĩa $get_value_by_lang gây ra lỗi
ngoài ra chưa định nghia· class cho google-identity
![screenshot_1679454785](https://user-images.githubusercontent.com/82592373/226792976-f15e9793-e090-4b81-a2a0-541bc4db6dfa.png)

**Comment by anhtunguyen** [comment]
@tmsholdings anh đã bỏ sót block này. Tam thời ẩn nó đi em nha. Vài hôm nữa anh sẽ sửa và up lên
