### ISSUE TITLE
Cors request ở NukeViet 4.6

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3582]
Em có một số vấn đề cùng thảo luận ạ:

**Vấn đề 1:**

Khi mới cài đặt, NukeViet đang share tài nguyên với mọi trang khác, có vẻ không an toàn. Vì khi cài lên trong .htaccess header `Access-Control-Allow-Origin` đang cho phép mọi Origin đến

```
  <IfModule mod_setenvif.c>
    SetEnvIf Origin "https?://(www\.)?(.*)$" cors_origins=$0
    Header add Access-Control-Allow-Origin %{cors_origins}e env=cors_origins
    Header merge Vary Origin
  </IfModule>
```

Theo em mặc định cài lên không xuất tiêu đề này ra header, đồng nghĩa không share với origin nào cho đến khi được bật ở phần **Tệp cấu hình máy chủ**

**Vấn đề 2:**

Access-Control-Allow-Origin trong .htaccess không phân biệt file tĩnh và request đến file xử lý PHP. Do đó nó sẽ xuất ra với mọi request. Trong khi class request có một chức năng kiểm soát `Access-Control-Allow-Origin` thông qua phần Thiết lập Cross-Site nó cũng xuất tiếp tiêu đề đó đối với các cross request

Điều này dẫn đến Cors request đến các chức năng của site ví dụ sload.php, mload.php hoặc các phần khác sẽ không chạy được bởi xuất hiện 2 tiêu đề `Access-Control-Allow-Origin`

![2023-03-23_13-41-56](https://user-images.githubusercontent.com/2421714/227123959-42b4ca91-28a0-40dd-b126-3d5e3a023a17.jpg)

```
Access to XMLHttpRequest at 'https://domain1.com' from origin 'https://domain2.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'https://domain1.com, https://domain2.com', but only one is allowed.
```

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Anh đồng ý với em là bỏ tính năng xuất tiêu đề Access-Control-Allow-Origin tự động ở .htaccess. Nhưng .htaccess chỉ giải quyết cấu hình ở một site. Trong trường hợp cấu hình máy chủ để mặc định là cấp quyền Access-Control-Allow-Origin cho bất kỳ Origin nào hay cho một số Origin nhất định nào đó thì việc class request xuất tiếp tiêu đề Access-Control-Allow-Origin sẽ vẫn gây ra lỗi như em viết trên. Có thể cho kiểm tra xem headers đã có tiêu đề Access-Control-Allow-Origin chưa. Nếu chưa có thì mới thêm vào?

**Comment by hoaquynhtim99** [comment]
@anhtunguyen trong quá trình vận hành em chưa gặp máy chủ có sẵn cái header Access-Control-Allow-Origin trừ khi quản trị máy chủ cố tình cấu hình thêm (cộng đồng chưa thấy báo lỗi, hosting của một số nhà cung cấp mà mình có đối tác/khách hàng chưa thấy, máy chủ của chính mình cài cũng không gặp).

Nếu kiểm tra thế không quá cồng kềnh thì cũng được anh, hoặc đơn giản hơn thêm cấu hình bật/tắt xuất tiêu đề Access-Control-Allow-Origin ở class request chằng hạn cho đơn giản.

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Anh đã test trường hợp máy chủ tự động điền tiêu đề Access-Control-Allow-Origin đối với các truy vấn gửi đến có tiêu đề Origin, kết quả là máy chủ xuất tiêu đề Access-Control-Allow-Origin sau khi class request của mình xuất ra. Như vậy không thể áp dụng phương pháp "kiểm tra xem headers đã có tiêu đề Access-Control-Allow-Origin chưa. Nếu chưa có thì mới thêm vào". Anh giải quyết vấn đề này như ý em: Xóa trong .htaccess và làm nút bật tắt trong cấu hình để admin tự quyết định
