### ISSUE TITLE
NukeViet 4.6 không ghi error log xuống file được

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3585]
Cái này đang test lại, tuy nhiên ghi ở đây để khỏi quên hoặc nếu ai đó có gặp phải:

Trong quá trình sử dụng, có ít nhất 2 lần nhân viên báo website lỗi:

```
An error occurred while loading the page: Error(1).
Please let us know about this!
```

Tuy nhiên vào tra error_log hoặc notice_log thì không thấy đâu, phải bật chế độ nhà phát triển lên thì lỗi mới hiển thị trực tiếp trên màn hình để xem. Website đang tắt chế độ nhà phát triển và bật ghi log

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Theo [php.net](https://www.php.net/manual/en/errorfunc.constants.php) thì lỗi số 1 (E_ERROR) có nội dung:
```
Fatal run-time errors. These indicate errors that can not be recovered from, such as a memory allocation problem. Execution of the script is halted. 
```
Lỗi nghiêm trọng, việc thực thi tập lệnh bị tạm dừng. Liệu vì thế không ghi log được?

**Comment by hoaquynhtim99** [comment]
Cái này cũng không hẳn anh ạ, tại có một lần check lỗi chỉ là câu lệnh SQL lỗi: `IN()`. Kệ nó đi anh, để em theo dõi thêm trong tương lai nếu nó có tiếp.

**Comment by hoaquynhtim99** [comment]
Lâu này không thấy vấn đề xảy ra nữa, em đóng issue. Nếu có lại tính tiếp
