### ISSUE TITLE
Lỗi cảnh báo khi sử dụng trình duyệt Firefox truy cập vào bản nukeviet mặc đinh 4.5.03

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#3587]
**Mô tả lỗi**
Truy cập nukeviet mặc định bản 4.5.03 bằng trình duyệt firefox thấy có rất nhiều lỗi cảnh báo liên quan tới css trình duyệt firefox

**Thao tác dẫn đến lỗi**
- Sử dụng trình duyệt Firefox vào một website bản 4.5.03 bất kỳ mặc định
- Mở kiểm tra (f12) sẽ thấy có rất nhiều lỗi cảnh báo liên quan tới css của trình duyệt Firefox

**Kết quả mong đợi**
Mong sẽ sửa các lỗi cảnh báo này

**Ảnh chụp màn hình**
![image](https://user-images.githubusercontent.com/9360175/229743012-3d82e17d-0e8d-4046-85da-a2ff758e66c8.png)

**Comment by anhtunguyen** [comment]
@nambmtk1993 File bootstrap.non-responsive.css chứa các css dùng để trình bày html cho một trang web. Các css phải đáp ứng đòi hỏi của nhiều trình duyệt phổ biến như Microsoft Edge, Firefox, Chrome... Mỗi một trình duyệt lại có những đặc thù riêng. Một số thuộc tính được viết cho trình duyệt A, nhưng lại không được chấp nhận ở trình duyệt B. Ví dụ như trong file minh họa lỗi của bạn, "alpha" được Edge chấp nhận, nhưng Firefox lại không hiểu gì. Chính vì vậy xuất hiện cảnh báo. Những cảnh báo kiểu này không được coi là lỗi từ lâu lắm rồi. Bạn cứ an tâm sử dụng nhé.
