### ISSUE TITLE
NukeViet 4.5 và 4.6: Nhu cầu bổ sung cấu hình bật/tắt hiển thị tác giả

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3593]
Nhu cầu:

- Đăng bài điền tác giả thuộc quyền quản lý, tác giả bên ngoài
- Khi xem bài viết lại chỉ muốn hiển thị tác giả bên ngoài thôi
- Lại muốn xem được trang riêng chứ không muốn tắt trang riêng /vi/news/authors/but-danh/

Hiện tại muốn ẩn thì vào đình chỉ tác giả đó, tuy nhiên đình chỉ thì trang riêng /vi/news/authors/but-danh/ cũng mất

Do đó cần bổ sung cấu hình hiển thị tác giả bên trong, bên ngoài khi xem bài đăng. Có thể 2 cái checkbox, bỏ check hết thì ẩn phần tác giả.

**Comment by hoaquynhtim99** [comment]
Phần này cần xử lý trong PHP để đảm bảo không ảnh hưởng đến giao diện, không bắt phải cập nhật giao diện

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Em muốn anh thêm 2 nút bật/tắt việc hiển thị tác giả bên trong, bên ngoài ở từng bài viết hay ở cấu hình module?

**Comment by hoaquynhtim99** [comment]
> @hoaquynhtim99 Em muốn anh thêm 2 nút bật/tắt việc hiển thị tác giả bên trong, bên ngoài ở từng bài viết hay ở cấu hình module?

Em nghĩ thêm cấu hình cho cả module luôn cho nó đơn giản thôi anh
