### ISSUE TITLE
[4.6] Cải tiến tính năng xem nhật ký lỗi

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3598]
Hiện tại bản mới nhất bổ sung chức năng đọc lỗi tại phần quản trị, để tối ưu hơn trong quá trình sử dụng em đề xuất nên có thêm một selectbox chọn kiểu hiển thị:

- Nhóm theo lỗi (như hiện tại)
- Plaintext: Hiển thị nguyên nội dung file lỗi.

Hoặc bổ sung thêm tính năng tìm kiếm vào đó.

Cách hiển thị như hiện tại phù hợp khi quản trị dò tìm và xử lý từng lỗi/cảnh báo nhưng không phù hợp đối với 1 website lớn có nhiều người dùng/quản trị/tính năng. Giả sử khi sale báo trang này đang bị lỗi trang trắng hoặc xử lý dữ liệu không đúng. Người quản lý cần vào error_log để tra cứu, lúc đó không dò nổi từ trên xuống dưới để tìm ra trang lỗi.

![2023-04-19_12-04-47](https://user-images.githubusercontent.com/2421714/232972689-6a972753-ce56-46fc-a092-4c9c096e0469.jpg)

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 
- Thêm phương án hiển thị lỗi dạng plaintext (Hiển thị nguyên nội dung file lỗi): OK, anh sẽ làm.
- Bổ sung thêm tính năng tìm kiếm: Tìm kiếm theo mã lỗi do người dùng cung cấp?

**Comment by hoaquynhtim99** [comment]
@anhtunguyen 

> Bổ sung thêm tính năng tìm kiếm: Tìm kiếm theo mã lỗi do người dùng cung cấp?

Cái này bỏ đi anh, hiển thị plaintext rồi thì Ctrl + F vào trình duyệt tìm cho nó lành. Thường thì ví dụ website gặp lỗi ở chức năng nào đó mà sale báo lại thì kỹ thuật hay đọc log để tìm theo url là chủ yếu. Ví dụ tìm nguyên url mà sale đang gặp lỗi hoặc tìm tên function (file) đó
