### ISSUE TITLE
Một số vấn đề về module push

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3603]
- [x] Nên đổi tên module này thành notification (thông báo) dùng tên push dễ hiểu nhầm sang chức năng [Web Push](https://web.dev/notifications/), [Push Notification](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Re-engageable_Notifications_Push) của Progressive Web Apps. Push yêu cầu phải hiển thị thông báo lên máy tính/trình duyệt người dùng đã cấp phép ngay khi họ không mở trình duyệt hay website của chúng ta.

- [x] Giao diện block notification trên máy tính cần tối ưu, nên đưa poup giống như phần block user button bên cạnh chứ hiện tại dropdown của nó lệch hoàn toàn về bên phải, nếu màn hình độ phân giải cao ví dụ 1920x1080 nhìn nó không cân đối. Phần này đã sửa [tại đây](https://github.com/nukeviet/nukeviet/pull/3602/files)

- [x] Cần giải pháp để xử lý phần thông báo này đa ngôn ngữ. Ví dụ một thông báo mà có thể dịch sang tiếng Việt, Anh, Pháp... để hiển thị trên tất cả các ngôn ngữ. Hoặc chỉ hiển thị thông báo trên một/một số ngôn ngữ nào đó.

- [x] Api `PushAction` cho admin và `PushGroupAction` cho user có yêu cầu tham số `action`. Tham số này bị trùng với `action` trong core api để xác định ra [tên api](https://wiki.nukeviet.vn/programming4:api#nguyen_t%E1%BA%AFc_chung) nên không dùng được

- [x]  Api `PushAction` cho admin và `PushGroupAction` cho user có yêu cầu tham số `checkhash`. Yêu cầu này có vẻ quá phức tạp cần bỏ, bởi đã là API thì nó đã có phần security riêng (role, quyền truy cập api)

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 
Anh đã thêm đa ngôn ngữ cho thông báo đẩy, nhưng không hoàn toàn như ý em viết trên:
- Bắt buộc phải khai báo nội dung thông báo ở ngôn ngữ được chọn là mặc định
- Nội dung thông báo ở các ngôn ngữ khác có thể bỏ qua. Nếu nó rỗng => nó sẽ được thay thế bằng nội dung thông báo bằng ngôn ngữ mặc định.
Tức là: Thông báo sẽ được hiển thị trong mọi trường hợp (hoặc thông báo bằng ngôn ngữ hiện tại nếu có, hoặc thông báo bằng ngôn ngữ mặc định)
