### ISSUE TITLE
Предупреждение о спаме в файле main.tpl

### ISSUE THREAD

**Issue by arzemas** [nukeviet/nukeviet#3606]
**Mô tả giải pháp bạn muốn**
Mô tả rõ ràng và ngắn gọn về những gì bạn muốn xảy ra.

Для предупреждения отправления спама, предлагаю выводить предупреждающюю информацию перед нажатием на кнопку отправить
(https://github.com/nukeviet/nukeviet/tree/nukeviet4.5/themes/default/modules/comment)/main.tpl
после строки 80 добавить:
(https://github.com/nukeviet/nukeviet/tree/nukeviet4.5/themes/mobile_default/modules/comment)/main.tpl
после строки 80 добавить:

            <div class="alert alert-info" id="alert-info"><h4 class="alert-heading">Перед записью комментария, вы обязаны выразить свое согласие:</h4>
  <hr>          
  <p>"Нажимая кнопку 'Записать', я даю согласие на обработку предоставленных мной персональных данных в соответствии с Федеральным законом от 27 июля 2006 г. № 152-ФЗ."</p>
  <hr>
  <p class="mb-0">"Нажимая кнопку 'Записать', я предупрежден, что распространение рекламы по сетям электросвязи в отсутствие предварительного согласия абонента на получение рекламных сообщений не допускается (ч.1 ст. 18 Закона № 38-ФЗ."</p></div>

**Comment by arzemas** [comment]
`            <div class="alert alert-info" id="alert-info"><h4 class="alert-heading">Перед записью комментария, вы обязаны выразить свое согласие:</h4>
  <hr>          
  <p>"Нажимая кнопку 'Записать', я даю согласие на обработку предоставленных мной персональных данных в соответствии с Федеральным законом от 27 июля 2006 г. № 152-ФЗ."</p>
  <hr>
  <p class="mb-0">"Нажимая кнопку 'Записать', я предупрежден, что распространение рекламы по сетям электросвязи в отсутствие предварительного согласия абонента на получение рекламных сообщений не допускается (ч.1 ст. 18 Закона № 38-ФЗ."</p></div>`
![111](https://user-images.githubusercontent.com/131642621/234168849-c6f37854-c186-41cd-b6df-f1b10c168da6.jpg)

**Comment by arzemas** [comment]
[https://arzemas.ru/uploads/111.jpg](url)

**Comment by anhtunguyen** [comment]
@arzemas Это просто предупреждение о спаме, а не имеется антиспамовый эффект. Если это предупреждение требуется по закону в России или Европе, я добавлю опцию «Включить/выключить» предупреждение в области управления модулем Comments. Тогда администратор сайта может самостоятельно решить, добавить его или нет в области комментариев.

**Comment by arzemas** [comment]
@anhtunguyen
 Вы поняли меня правильно. Добавьте исключение «Включить/выключить» предупреждение в области управления модулем Комментарии. Тоже самое нужно сделать в функции отправить новость другу на почту. Спасибо!

**Comment by anhtunguyen** [comment]
@arzemas Обновите, пожалуйста, свой сайт до версии 4.6. Согласно политике развития системы, мы прекратили добавлять новые функции в версии 4.4 и 4.5 и сосредоточились только на исправлении ошибок. Все новые функции добавляются в последнюю версию 4.6.

**Comment by arzemas** [comment]
> @arzemas Обновите, пожалуйста, свой сайт до версии 4.6. Согласно политике развития системы, мы прекратили добавлять новые функции в версии 4.4 и 4.5 и сосредоточились только на исправлении ошибок. Все новые функции добавляются в последнюю версию 4.6.

Спасибо, работаю по этому вопросу, но пока не получается, читаю инструкции, но они не очень понятны.

**Comment by anhtunguyen** [comment]
Дабавлено в версию 4.6.
Спасибо @arzemas
