### ISSUE TITLE
[4.6] Lỗi mất tự động điền tiêu đề và link menu

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3611]
Trước đây khi thêm một menu vào khối, khi chọn "Liên kết đến module" hoặc "Liên kết đến mục của module"  thì ô "Tên mục" và "URL liên kết" được tự động điền. Bây giờ không thấy tự động nữa

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Chọn liên kết đến module và ở dòng URL liên kết click nút bên phải

**Comment by hoaquynhtim99** [comment]
Dạ vâng a, e đã thấy
