### ISSUE TITLE
[4.6] Việc xác định giao diện gửi email không thống nhất

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3620]
Ví dụ website đang sử dụng giao diện XXXX có file system/mail.tpl đã sửa footer theo đúng của công ty. Thì một số tính năng gửi qua bất đồng bộ nv_sendmail_async không nhận template gửi email nó lại lấy của default kết quả người dùng lúc thì nhận được kiểu email này lúc thì nhận kiểu khác không thống nhất.

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Hướng giải quyết của anh là loại bỏ themes/XXXX/system/mail.tpl đi, thay vào đó sẽ là assets/tpl/mail.tpl. Ý em sao?

**Comment by hoaquynhtim99** [comment]
Hướng đó em không có ý kiến ạ, anh @vuthao làm file đó anh cho ý kiến nhé anh.

**Comment by danlt150** [comment]
@anhtunguyen Cũng liên quan đến hàm send_mail_async này, em thấy đang sử dụng sload để thực hiện nv_sendmail, tuy nhiên vì sload không xác định ngôn ngữ nên khi cần sử dụng giao diện mail đa ngôn ngữ thì không làm được ạ.  
Nên anh có thể bổ sung thêm phần xác định ngôn ngữ cho sload được không ạ?

**Comment by hoaquynhtim99** [comment]
Còn một cái nữa là mình đang cố định lấy template từ `assets/tpl/mail.tpl` có 2 vấn đề anh xem thử làm sao ạ:
- Người dùng sửa vào đó để tùy biến mẫu email theo nhu cầu, cập nhật phiên bản lên có khả năng bị đè mất
- Đa ngôn ngữ cho mẫu email

**Comment by anhtunguyen** [comment]
@conkhikho22 Liên quan đến vấn đề đa ngôn ngữ của hàm nv_sendmail/nv_sendmail_async anh đưa ra giải pháp thế này:
- Thêm đối số không bắt buộc $lang cho hàm nv_sendmail/nv_sendmail_async với giá trị mặc định rỗng.
- Nếu $lang rỗng nó sẽ là NV_LANG_INTERFACE.

@hoaquynhtim99
- Về khả năng bị đè mất assets/tpl/mail.tpl anh đưa ra giải pháp thế này: Tạo biến toàn cục $mail_tpl được xác định trong phần "cấu hình chung" của site với giá trị mặc định là assets/tpl/mail.tpl. Nếu trong thư mục themes/tên_theme/system/ có file mail.tpl thì nó sẽ là một trong những lựa chọn cho biến $mail_tpl. Site dùng mẫu email nào do admin xác định
- Về vấn đề đa ngôn ngữ cho mẫu email: anh đưa ra giải pháp thế này: Thêm đối số không bắt buộc $lang cho hàm mailAddHtml với giá trị mặc định rỗng. Nếu $lang rỗng nó sẽ là NV_LANG_INTERFACE

Các em xem thấy hợp lý chưa. Góp ý để anh viết chúng

**Comment by hoaquynhtim99** [comment]
Theo em thêm một case nữa cho chỗ email ạ
- Đọc file mail_vi.tpl, mail_en.tpl nếu có
- Nếu không có mặc định đọc mail.tpl

**Comment by anhtunguyen** [comment]
> Theo em thêm một case nữa cho chỗ email ạ
> 
>     * Đọc file mail_vi.tpl, mail_en.tpl nếu có
> 
>     * Nếu không có mặc định đọc mail.tpl

Nếu vậy thì biến toàn cục $mail_tpl được xác định trong "Cấu hình site" theo ngôn ngữ
