### ISSUE TITLE
Lỗi xác định rewrite ở các bản NukeViet mới

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3623]
**Case 1: Ràng buộc chéo dẫn đến không thể xác định support rewrite**

1. Website đang không hỗ trợ rewrite và ở bản NukeViet 4.4.06 hoặc cao hơn mà trong .htaccess tại thư mục gốc không có dòng
```
RewriteRule ^(.*?)check\.rewrite$ index.php?rewritesupport=apache [L]
```
Không hỗ trợ rewrite có nhiều lý do ví dụ như máy chủ cũ có vấn đề và người dùng chuyển sang máy chủ mới hỗ trợ rewrite, hoặc các vấn đề đã mô tả [tại issue này](https://github.com/nukeviet/nukeviet/issues/3605)

2. Để build lại .htaccess để có thể add được dòng đó thì phải đi qua hàm `nv_rewrite_change` mà trong hàm đó lại tiếp tục dùng lệnh kiểm tra `if ($sys_info['supports_rewrite'] == 'rewrite_mode_apache')` (giá trị đang false) dẫn đến file .htaccess sẽ không được build lại. Và cứ thế không có cách gì để website có thể được hỗ trợ rewrite nữa đối với người dùng thông thường. Chỉ có những người am hiểu vào debug và  fix mới giải quyết được.

**Case 2: Treo máy chủ nếu file .htaccess có vấn đề**

Nếu gặp vấn đề nào đó mà file .htaccess bị mất dòng `RewriteRule ^(.*?)check\.rewrite$ index.php?rewritesupport=apache [L]`. Ví dụ như đang ở case số 1 bên trên, bị ghi đè, bị copy đè nhầm, bị sửa nhầm do người dùng hoặc thậm chí do các control panel như Cpanel. Thì đến chu kỳ làm mới file data/config/config_ini.....php máy chủ sẽ treo. Nguyên nhân:

- Gọi `file_get_contents(NV_MY_DOMAIN . NV_BASE_SITEURL . 'check.rewrite')` để check rewrite
- Nếu .htaccess không có rewrite rule để bắt request đó nó sẽ trả về trang home của website.
- Tại trang home lại bắt request đó và cứ thế vòng lặp đệ quy này sẽ gây treo máy chủ.

Vấn đề này gần giống với trước đây đã gặp https://github.com/nukeviet/nukeviet/blob/4.4.02/includes/ini.php#L62-L68

**Comment by vuthao** [comment]
Theo mình chỉ cần cấu hình trong quản trị có hỗ trợ rewite (htaccess, Nginx, openlitespeed ...) hay không, chứ không để xác định tự động

Sau đó theo cấu hình xuất sắn fle rewite phù hợp để người dùng tự cấu hình

**Comment by hoaquynhtim99** [comment]
@vuthao cần làm sao đơn giản nhất để người dùng biết dùng anh. Các bản NukeViet trước đây em thấy chỗ đó ổn, vài bản trở lại đây a Tú sửa qua bất đồng bộ nên gặp nhiều vấn đề mới.

Đại đa số người dùng sẽ không biết mấy cái đó đâu, mua hosting về tải lên và cài là xong thôi còn lại phó mặc cho phần mềm. Do vậy việc xác định tự động là cần thiết. Việc làm thủ công này nếu add vào thì càng tốt ví dụ chức năng "Gỡ lỗi rewrite" chẳng hạn.

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 @vuthao 
- Với những lý do em nêu trên, anh đồng ý không kiểm tra rewrite theo cách Gọi `file_get_contents(NV_MY_DOMAIN . NV_BASE_SITEURL . 'check.rewrite')`
- Hàm `nv_rewrite_change` không có chức năng kiểm tra lại kiểu hỗ trợ rewrite, mà nó chỉ tạo lại file cấu hình máy chủ (.htaccess, web.config) dựa trên cấu hình của site. Từ thời xa xưa, chúng ta đã mặc định trong file .htaccess có các đoạn mã được viết trong các block `#NUKEVIET_REWRITE_START ... #NUKEVIET_REWRITE_END` `#NUKEVIET_CONFIG_START ... #NUKEVIET_CONFIG_END` không được thay đổi thủ công. Tất cả các cấu hình thủ công phải được viết bên ngoài các block này.
- Việc xác định kiểu hỗ trợ rewrite hoàn toàn dựa vào includes/ini.php. Lỗi phát sinh từ đoạn: `$_check_rewrite = file_get_contents(NV_MY_DOMAIN . NV_BASE_SITEURL . 'check.rewrite');` (Với lý do như em nêu ở Case2). Vì vậy, anh sẽ bỏ đoạn này, thay vào đó thì biến `$sys_info['supports_rewrite']` sẽ được gán cho giá trị là `NV_MY_REWRITE_SUPPORTER` (kiểu hỗ trợ rewrite được khai báo thủ công ở file includes/constants.php). Như vậy ta sẽ có: Nếu hệ thống không thể xác định tự động kiểu hỗ trợ rewrite dựa vào môi trường máy chủ thì nó sẽ lấy `NV_MY_REWRITE_SUPPORTER` làm giá trị.
