### ISSUE TITLE
Lỗi khi nâng cấp từ 4.5.00 lên 4.5.03

### ISSUE THREAD

**Issue by hades-1997** [nukeviet/nukeviet#3624]
Em gặp lỗi này ở thiết lập an ninh. và bên ngoài site không redirect chuyển hướng xem bài viết
![image](https://github.com/nukeviet/nukeviet/assets/70182883/06f50998-0c09-4558-9713-b160f594929f)

**Comment by hoaquynhtim99** [comment]
Các cảnh báo đó do site của bạn có vấn đề khi cập nhật lên 4.4.01 chứ nó không liên quan 4.5.00 lên 4.5.03. 
Bạn có thể xem các ghi nhận thay đổi CSDL tại đây cho lỗi đó https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.4#th%C3%AAm-m%E1%BB%99t-s%E1%BB%91-c%E1%BA%A5u-h%C3%ACnh-an-ninh

Nếu khó bạn có thể nhờ hỗ trợ trên Group https://www.facebook.com/groups/nukeviet
