### ISSUE TITLE
[4.6] Thảo luận về xác thực 2 bước

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3627]
Các bản trước:

Nếu hệ thống cấu hình hiển thị captcha khi thành viên đăng nhập, thành viên đó có bật xác thực 2 bước.  
Khi đăng nhập bước 1 xong hệ thống sẽ không hỏi captcha cho bước 2 nữa.

NukeViet 4.6  hiện giờ vừa xác thực captcha xong nhập mã từ ứng dụng lại phải xác nhận tiếp nữa.   
Có vẻ hơi mất thời gian không?

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Anh định thế này: Nếu bật xác thực 2 bước thì không cần kiểm tra captcha. Ý em sao?

**Comment by hoaquynhtim99** [comment]
> @hoaquynhtim99 Anh định thế này: Nếu bật xác thực 2 bước thì không cần kiểm tra captcha. Ý em sao?

Em đồng ý ạ.
