### ISSUE TITLE
Chuyển phần cấu hình email sang hỗ trợ đa ngôn ngữ

### ISSUE THREAD

**Issue by danlt150** [nukeviet/nukeviet#3628]
Hiện tại cấu hình email đang sử dụng chung cho mọi ngôn ngữ, dẫn đến nếu muốn sửa các thiết đặt email cho ngôn ngữ khác (ví dụ cần dịch sender_name, reply_name) thì phải sửa trong code.  
Do đó phần cấu hình cũng email nên cập nhật để hỗ trợ đa ngôn ngữ.

**Comment by anhtunguyen** [comment]
Vấn đề này @vuthao và @hoaquynhtim99 xem có cần thiết không? Nếu cần anh sẽ thay đổi.
Ngoài ra, có một vấn đề nữa là khi muốn gửi mail đến thành viên đăng ký ngôn ngữ giao diện (A) khác với ngôn ngữ hiện tại mà admin đang sử dụng (B) thì admin buộc phải chuyển đổi ngôn ngữ giao diện sang ngôn ngữ của thành viên (A) trước khi tiến hành gửi mail. Như vậy có bất cập không?

**Comment by hoaquynhtim99** [comment]
Em thấy cái đó cần anh ạ, site của mình đang gặp vấn đề.  
Phần email gửi đi từ admin ít, chủ yếu là các email tương tác khi người dùng thao tác trên site nên chắc kệ thôi.
