### ISSUE TITLE
Lỗi chuyển hướng http -> https

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/nukeviet#3629]
Hiện tại khi cài đặt bản mới nhất trên phiên bản PHP 7.2 thì phát sinh lỗi không tự động chuyển từ http --> https tuy đã cấu hình Yêu cầu chuyển hướng http->https.

**Comment by hoaquynhtim99** [comment]
Cái này mình cũng có gặp mấy lần, ngờ ngợ không biết lỗi hay nhầm lẫn, mà nhiều người gặp chắc lỗi thật

**Comment by hoaquynhtim99** [comment]
@motcaiten phiên bản mới nhất có chức năng kiểm tra hosting xem có hỗ trợ https hay không. Nếu không hỗ trợ thì chỗ đó có bật nó cũng sẽ không chuyển hướng.

Cấu hình đó được kiểm tra và ghi cứng xuống file config và được định kì check lại 1 ngày 1 lần. Trường hợp này bạn kiểm tra thử lại xem máy chủ có hỗ trợ HTTPS không, nếu có thử xóa các file data/config/config_ini.xxxx.php sau đó truy cập lại.

Tất cả các case trên nếu bạn thử đều không được hãy nêu rõ thông tin về môi trường máy chủ của bạn và mở lại issue để chúng tôi kiểm tra lại.
