### ISSUE TITLE
Lỗi khi nâng cấp lên bản 4.5.03

### ISSUE THREAD

**Issue by hades-1997** [nukeviet/nukeviet#3630]
Cho e xin hỏi e bị lỗi này khi nâng cấp lên bản 4.5.03 thì bị, ngoài đường dẫn thì lỗi redirect hết về home 
![image](https://github.com/nukeviet/nukeviet/assets/70182883/d0492693-a3b9-423b-a61e-5556e4cc4d3c)

**Comment by hoaquynhtim99** [comment]
Bạn tự xóa bằng tay theo yêu cầu của nó thôi. Phần này có thể dùng tài khoản root upload gói cập nhật lên nên PHP không có quyền xóa
