### ISSUE TITLE
[4.6] Cần 1 trang danh sách bài đăng của khách

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3631]
Hiện đang có trang xem bài đăng theo tác giả, đối với những bài đăng của khách thì cũng đưa về một trang để xem danh sách

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Khách ở đây là User có đăng ký hay Guest?

**Comment by hoaquynhtim99** [comment]
> @hoaquynhtim99 Khách ở đây là User có đăng ký hay Guest?

Theo em hiểu ở đây khách là trường hợp còn lại :v. Còn thế nào thì chủ ý là anh @thehung anh giải thích mong muốn rõ hơn ạ.

**Comment by thehung** [comment]
@hoaquynhtim99 viết vắn tắt quá và cắt ra khỏi bối cảnh nên làm anh Tú khó hiểu.

Anh @anhtunguyen, "bài đăng của khách" mà Dũng mô tả ở trên là những bài mà tác giả bài viết không thuộc quyền quản lý trên site mà là tác giả bên ngoài. Hiện tại các bài này không được liên kết với tác giả cụ thể nào nên nó bị rời rạc. Giờ mình nhóm lại để có thể xem như là cùng 1 tác giả (link kiểu https://nukeviet.vn/news/author/guests/) anh ạ!

**Comment by daiubqn113** [comment]
Anh xem qua lỗi của em ạ
#### Mô tả
Em đăng tin tức trên nukeviet4.6.
Ra ngoài site xem `danh sách bài của tác giả` thì không có ảnh minh họa .

![image](https://github.com/nukeviet/nukeviet/assets/59864736/79956a8c-7783-4e8a-9965-6daa85ac4103)

#### Kết quả mong muốn:
Có link ảnh bên cạnh danh sách như hình dưới
![image](https://github.com/nukeviet/nukeviet/assets/59864736/82505756-05d6-4c44-9c3a-3ef55a447834)

**Comment by anhtunguyen** [comment]
@daiubqn113 Em cập nhật lại và check xem OK chưa
