### ISSUE TITLE
Unknown: function '1' not found or invalid function name nukeviet 4.6.00

### ISSUE THREAD

**Issue by arzemas** [nukeviet/nukeviet#3635]
Развернул на сервере версию 4.6 php 7.0
Пробовал php от 7.1 до 8.0 установка со второго шага перекидывала на первый.
 После установки система выдала ошибку:
An error occurred while loading the page:
Array
(
    [type] => 2 (Warning)
    [message] => Unknown: function '1' not found or invalid function name
    [file] => Unknown
    [line] => 0
)

Имя 	Firefox
Версия 	91.3.0esr
не удается залогиниться, но если после этого перейти на домашнюю стрраницу, слева появляется админ панель и можно в нее войти.

При попытке скачать язык vi система обрывает закачку.
 В логах система выдает следующее:

[TIME: Fri, 09 Jun 2023 13:20:19 +0300][SERVER: sait][IP: ][ERRNO: 8 (Notice)][ERRSTR: ob_start(): failed to create buffer][FILE: /includes/core/theme_functions.php][LINE: 313][REQUEST: /install/index.php?language=en&step=5&t=1686306019&nocache=1686306029011][METHOD: POST][AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36]
-------------------
[TIME: Fri, 09 Jun 2023 13:22:45 +0300][SERVER: sait][IP: ][ERRNO: 8 (Notice)][ERRSTR: Undefined index: check_rewrite_file][FILE: /includes/core/admin_functions.php][LINE: 427][REQUEST: /install/index.php?language=en&step=6][METHOD: POST][AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36]
-------------------
[TIME: Fri, 09 Jun 2023 16:50:21 +0300][SERVER: sait][IP: ][ERRNO: 8 (Notice)][ERRSTR: Undefined index: csp_frame-ancestors][FILE: /admin/settings/security.php][LINE: 1067][REQUEST: /admin/index.php?language=en&nv=settings&op=security][METHOD: GET][AGENT: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0]
^^^ [TRACE#01][FILE: /admin/index.php][LINE: 183]
-------------------

**Comment by anhtunguyen** [comment]
@arzemas Свяжитесь со мной. Я постараюсь помочь. +84933777637 (Вацап)

**Comment by arzemas** [comment]
> @arzemas Свяжитесь со мной. Я постараюсь помочь. +84933777637 (Вацап)

К сожалению, у меня пока нет возможности, только майл.
