### ISSUE TITLE
nukeviet4.6-language или nukeviet4.6

### ISSUE THREAD

**Issue by arzemas** [nukeviet/nukeviet#3636]
Какая ветка будет теперь поддерживаться, nukeviet4.6-language или nukeviet4.6
Спасибо.

**Comment by anhtunguyen** [comment]
@arzemas В ветке nukeviet4.6-language есть серьезные изменения, и они проверяются на наличие ошибок. Эта ветка предназначена только для разработчиков. После завершения проверки она будет импортирована в ветку nukeviet4.6.

**Comment by arzemas** [comment]
@anhtunguyen Спасибо за информацию. Я развернул 4.6. Выбрал режим многоязычности. Делаю вход на русском языке, нажимаю войти, тишина. Перевыбираю вьетнамский язык и тут же происходит вход. Тоже самое, если вначале выбираю вьетнамский язык. Вход происходит после перевыбора языка на русский. Это ошибка системы или что то не так на моей стороне?

**Comment by anhtunguyen** [comment]
Попробуйте отформатировать языковые файлы RU в UNIX без BOM.

Vào 22:36, Th 2, ngày 12 tháng 6 năm 2023 NukeVlad ***@***.***>
đã viết:

**Comment by arzemas** [comment]
[anhtunguyen](https://github.com/anhtunguyen) (https://github.com/nukeviet/nukeviet/issues/3636#issuecomment-1587597131) 
Попробуйте отформатировать языковые файлы RU в UNIX без BOM.
________________
Так дело в том, что я их не переводил, они остались vi, я только изменил в наименованиях vi на ru.

Тоже самое я обнаружил при вышедшем обновлении 4.4.06 до 4.4.07 и откатился назад. Там была еще ошибка, созданная новость не сохрранялась, а повисала как белый лист.

Принял решение и развернул чистую nukeviet4.6. В ней нет проблемы зависания на чистый лист, остался вопрос логирования. На майл вам скину сообщение
