### ISSUE TITLE
Nuke 4.5.03 bị quét ra lỗi Cross-site Scripting (XSS)

### ISSUE THREAD

**Issue by sondoan1204** [nukeviet/nukeviet#3647]
**Mô tả lỗi**
Mình có nâng cấp trang lên bãn 4.5.03. bên hệ thống quét trang báo lỗi xss như hình dưới, mình có đọc thấy bản 4.5.0.2 đã fix xss rồi nhưng sao phần mềm quét vẫn ra. 
Ai có cách fix hay chặn luôn không cho quét lỗi kiểu này chỉ mình với.

**Thao tác dẫn đến lỗi**
phần mềm Acunetix Security Audit quét báo lỗi

**Ảnh chụp màn hình**
![Screenshot 2023-07-05 190512](https://github.com/nukeviet/nukeviet/assets/21288630/8f5ee472-6769-4966-8fd7-12af58f1891e)
![Screenshot 2023-07-05 190615](https://github.com/nukeviet/nukeviet/assets/21288630/8238c191-c90d-4fcd-a1c9-0f8681fcedda)

[20230704_Affected_Items.pdf](https://github.com/nukeviet/nukeviet/files/11957708/20230704_Affected_Items.pdf)

**Comment by hoaquynhtim99** [comment]
Cá nhân mình thấy đó không phải là lỗi XSS. Người dùng bình thường/ bot/ hacker có thể truyền param vào tùy ý quan trọng là hệ thống có nhận nó và xuất ngược ra html dưới dạng plaintext hay không đó mới là vấn đề.

Ở đây phần mềm này chỉ truyền vào request và chưa chỉ ra được gì về đầu ra (respon header + body) chứa mã độc

**Comment by sondoan1204** [comment]
> Cá nhân mình thấy đó không phải là lỗi XSS. Người dùng bình thường/ bot/ hacker có thể truyền param vào tùy ý quan trọng là hệ thống có nhận nó và xuất ngược ra html dưới dạng plaintext hay không đó mới là vấn đề.
> 
> Ở đây phần mềm này chỉ truyền vào request và chưa chỉ ra được gì về đầu ra (respon header + body) chứa mã độc

mình cũng đã thử, không có gì thay đổi, nhưng bị báo cáo như vậy, vậy có cách nào mình chặn luôn không? cám ơn!

**Comment by hoaquynhtim99** [comment]
Mình nghĩ có thể xử lý theo hướng:
Cái này có thể viết 1 plugin, dùng `HTML Purifier` clean cái REQUEST_URI của thằng máy chủ nếu giá trị clean khác với giá trị gốc thì stop request trả về `400 Bad Request` chẳng hạn.

Chắc phải làm thử mới biết được. Còn việc sửa vào NukeViet có lẽ không nên, bởi phải liên tục kiểm soát cái đó tốn không ít tài nguyên của máy chủ.
