### ISSUE TITLE
Lỗi xác định supports_rewrite khi bật ssl

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/nukeviet#3648]
Đối với bản mới nhất. Sau khi kích hoạt ssl thì sẽ không xác định được supports_rewrite , đưa về false.

**Comment by anhtunguyen** [comment]
@motcaiten Là phiên bản nào vậy bạn?

**Comment by motcaiten** [comment]
> @motcaiten Là phiên bản nào vậy bạn?

Bản 4.5.03 đã fix [lỗi không xác định được loại rewrite](https://github.com/nukeviet/nukeviet/commit/cb3289e1554b7c8ef622b5222343c7550cb84186) hoặc bản dev đều bị anh.

**Comment by anhtunguyen** [comment]
@motcaiten Bạn thử fix như ở đây: https://github.com/nukeviet/nukeviet/commit/47861966284bdf482835e45c5c2fef88f5c511d8

**Comment by motcaiten** [comment]
> @motcaiten Bạn thử fix như ở đây: [4786196](https://github.com/nukeviet/nukeviet/commit/47861966284bdf482835e45c5c2fef88f5c511d8)

Hiện tại đã fix theo hướng dẫn và cho giá trị về true. Để em theo dõi xem còn bị không.

Vì trước đó cứ đưa về true là nó ok sau vài hôm nó lại cho về false.

**Comment by motcaiten** [comment]
@anhtunguyen Sau 2 hôm supports_rewrite thì nó lại chuyển về false . Và hiển thị index.php

**Comment by anhtunguyen** [comment]
@motcaiten Em cho biết môi trường máy chủ

**Comment by motcaiten** [comment]
@anhtunguyen đây là môi trường máy chủ em đang sử dụng ạ
<img width="1338" alt="Screenshot 2023-07-11 at 08 25 00" src="https://github.com/nukeviet/nukeviet/assets/8292355/c30cdafd-1660-4b32-8be1-1ac9bd9ea7b2">

**Comment by anhtunguyen** [comment]
Em liên hệ anh qua zalo 0 9 3 3 7 7 7 6 3 7

**Comment by motcaiten** [comment]
@anhtunguyen Vâng. Đã inbox cho anh.
