### ISSUE TITLE
Modules Zalo trong admin bị dẫn sai đường link(Nukeviet4.6)

### ISSUE THREAD

**Issue by daiubqn113** [nukeviet/nukeviet#3651]
**Mô tả lỗi**
Link: http://nukeviet46.my/admin/index.php?language=vi&nv=zalo&op=settings&action=general_settings

**Thao tác dẫn đến lỗi**
Các bước để thấy lỗi:
1. Click vào modules Zalo -> Thông tin QA
2. Lỗi - link dẫn đến cấu hình

**Những trang bị lỗi**
1. Thông tin QA
2. Người quan tâm
3. Bài viết
4. Chatbox
5. Nhãn
6. Mẫu tin nhắn
7. File tải lên
8. Video tải lên

**Kết quả mong đợi**
Link phải dẫn đến đúng trang `thông tin QA` chứ không phải `cấu hình`

**Ảnh chụp màn hình**
![image](https://github.com/nukeviet/nukeviet/assets/59864736/04350b00-560c-4028-b4ea-96db2c5049f4)

**Comment by anhtunguyen** [comment]
@daiubqn113 Trước hết phải khai báo đầy đủ thông tin OA, khi đó tất cả các trang em nêu mới làm việc
