### ISSUE TITLE
Ẩn hiện mật khẩu ở module user

### ISSUE THREAD

**Issue by danlt150** [nukeviet/nukeviet#3653]
NukeViet 4.6:  
Tạo user mới tại: `/admin/index.php?language=vi&nv=users&op=user_add` thì mặc định không che mật khẩu  
![image](https://github.com/nukeviet/nukeviet/assets/83101691/69598997-06aa-42c9-9da1-c3cd58610728)

Sau khi bật che mật khẩu thì bị thừa một nút hiển thị mật khẩu:  
![image](https://github.com/nukeviet/nukeviet/assets/83101691/6f9dee10-057b-4209-86c6-81da0d04efaf)

**Comment by anhtunguyen** [comment]
@conkhikho22 Em kiểm tra lại. Anh không thấy xuất hiện lỗi này?

**Comment by hoaquynhtim99** [comment]
@anhtunguyen cái đó em thấy lỗi á anh. Từ [commit này](https://github.com/nukeviet/nukeviet/commit/ea0457600c5a092c01e3d3a0c4c0d50f0369e1f4#diff-b68adcf105693f633bf0f4354b41225aa492981a579cceb756f131030df4fc0bR290) nè a. À, hoặc là chủ đích là như thế luôn, e với cả Đan thấy nó không quen 😶

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 
Thừa đoạn mã JS:
```
$.toggleShowPassword({
            field: '#password2',
            control: '#methods'
        });
```
