### ISSUE TITLE
Cải tiến cho phép lấy link động của một bài viết bất kỳ trong module tin tức

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#3654]
**Mô tả vấn đề**
Hiện tại, việc lấy link động bài viết trong module tin tức rất nhiều thao tác.
Ví dụ cụ thể: trong tin tức có 1 bài viết tiêu đề "ABC". Muốn đưa link theo dạng /vi/news/su-kien/abc.html thì phải ấn vào bài viết đó để ra trang chi tiết bài viết. Copy link theo dạng trên rồi về module menu paste link lại.
Với 1,2 bài thì thao tác chỉ có 6 bước. Nhưng nếu 10,20 bài thì là 30-60 bước rất nhiều

**Mô tả giải pháp bạn muốn**
Trong quản trị thêm biểu tượng lấy link tự động. Muốn copy link chỉ cần ấn vào link đó sau đó thì paste vào menu là được. Như vậy sẽ tiết kiệm được 50% công cấu hình

![image](https://github.com/nukeviet/nukeviet/assets/9360175/b0c905c9-c237-408f-b01d-9ac2387761a8)

**Comment by hoaquynhtim99** [comment]
Ý kiến của mình: Cái này đơn giản, nếu có nhu cầu nên viết 1 module để làm việc này, không nên thêm tính năng vào news

**Comment by hoaquynhtim99** [comment]
> trong tin tức có 1 bài viết tiêu đề "ABC". Muốn đưa link theo dạng /vi/news/su-kien/abc.html thì phải ấn vào bài viết đó để ra trang chi tiết bài viết. Copy link theo dạng trên rồi về module menu paste link lại

Cái này chỉ cần chuột phải vào tiêu đề bài viết chọn `Copy link address` là xong, chỉ có 1 bước

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 thêm cái nút copy cũng chỉ là vài dòng code. Anh sẽ thêm vào một cách đơn giản nhất
