### ISSUE TITLE
[4.6-lang] Một số lỗi bắt gặp khi kiểm tra ở bên ngoài site

### ISSUE THREAD

**Issue by quangpro1610** [nukeviet/nukeviet#3655]
**Mô tả lỗi**
- **Trang chủ**: Hiển thị lỗi báo sai đường dẫn trong console trình duyệt, khả năng là thiếu tên giao diện. [Hình ảnh báo lỗi](https://monosnap.com/file/T49eVP62Iq1Zl7nGp2PungkAsv5DEJ)

- **Block menu**: 
Hiển thị thông tin không đúng, thiếu lang. [Hình ảnh báo lỗi](https://monosnap.com/file/GSPQ3I6nxXe30ZaSZfU4CYCh5u8rx9)
Lỗi khi vào cấu hình block, chỉ hiển thị loading và xuất hiện error 500 xuất hiện ở console trình duyệt. [Hình ảnh báo lỗi](https://monosnap.com/file/2mXm0Ctt26CxJhJf0xkvC8oZO6rG0R)

- **Module Banners (Quảng cáo)**: Hiển thị lỗi khi load trang. [Hình ảnh báo lỗi](https://monosnap.com/file/hoI5xkqU1qeP3eZmT6WsdCBcizdKW1)

**Comment by arzemas** [comment]
Cố gắng hoàn tác hành động cuối cùng trong cấu hình trang web hoặc khôi phục từ bản sao lưu.
