### ISSUE TITLE
[4.6] Kiểm tra lại class Error

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3657]
Trên php 8.2 dường như hệ thống ghi toàn bộ lỗi vào `2023-07-21_error_log.log` không còn file dạng notice_log.log nữa

**Comment by anhtunguyen** [comment]
Vấn đề là từ php8.0 nhiều lỗi trước kia là E_NOTICE  được chuyển thành E_WARNING . 
Hướng giải quyết: Tất cả các lỗi không phải là fatal errors đều ghi vào file notice_log.log.
https://github.com/nukeviet/nukeviet/commit/7032d70849788a40c728882d9f83920e212e81ea
