### ISSUE TITLE
Lỗi không lưu được avatar tác giả trong module news

### ISSUE THREAD

**Issue by hades-1997** [nukeviet/nukeviet#3664]
![image](https://github.com/nukeviet/nukeviet/assets/70182883/a68d018e-4810-4cbd-bda6-e8476ba5e964)

**Comment by hoaquynhtim99** [comment]
Bạn dùng phiên bản nào nhỉ? Cái này hình như đã ghi nhận và fix ở đây rồi https://github.com/nukeviet/nukeviet/issues/3607

**Comment by hades-1997** [comment]
> Bạn dùng phiên bản nào nhỉ? Cái này hình như đã ghi nhận và fix ở đây rồi #3607

e đang dùng bản 4.5.03 á a

**Comment by hades-1997** [comment]
> Bạn dùng phiên bản nào nhỉ? Cái này hình như đã ghi nhận và fix ở đây rồi #3607

e xem code thay đổi thì đâu có cái nào can thiệp tới upload image đâu a. nó bị check lỗi ngay đây nè a. nó trả về cái else
![image](https://github.com/nukeviet/nukeviet/assets/70182883/3dc753d4-be28-4265-a18e-3ed16210315d)

**Comment by anhtunguyen** [comment]
@hades-1997 Avatar của tác giả chỉ chấp nhận các hình được tải lên máy chủ và lưu vào thư mục uploads/news/authors, không chấp nhận các hình từ bên ngoài. Rất có thể bạn đã gán URL vào ô hình đại diện?
Ngoài ra bạn kiểm tra xem có thư mục uploads/news/authors không nhé. Nếu không thì tạo nó

**Comment by hades-1997** [comment]
> @hades-1997 Avatar của tác giả chỉ chấp nhận các hình được tải lên máy chủ và lưu vào thư mục uploads/news/authors, không chấp nhận các hình từ bên ngoài. Rất có thể bạn đã gán URL vào ô hình đại diện? Ngoài ra bạn kiểm tra xem có thư mục uploads/news/authors không nhé. Nếu không thì tạo nó

dạ trong phần upload ảnh author của news nó ko trỏ về authors a
