### ISSUE TITLE
Thay thông tin VINADES.,JSC trong dữ liệu mẫu các phiên bản NukeViet 4.4 > 4.6

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3681]
Địa chỉ mới: Tầng 6, tòa nhà Sông Đà, 131 Trần Phú, Văn Quán, Hà Đông, Hà Nội.

Tiếng Anh: 6th floor, Song Da building, No. 131 Tran Phu street, Van Quan ward, Ha Dong district, Hanoi city.

**Comment by arzemas** [comment]
Спасибо, заменил
