### ISSUE TITLE
Khôi phục khi Mất tất cả thiết bị 2FA và mã dự phòng

### ISSUE THREAD

**Issue by vuthao** [nukeviet/nukeviet#3686]
Do có khá nhiều tài khoản kích hoạt xác thực 2 bươc, sau đó xóa App đi nên ko đăng nhập được nữa

Tham khảo cách làm của cloudflare

Nếu bạn có mã dự phòng hoặc thiết bị 2FA khác được định cấu hình trên tài khoản của mình, bạn có thể sử dụng một trong số chúng để đăng nhập tại đây và sau đó vô hiệu hóa thiết bị bị mất của mình. Nếu bạn đã thử cách này mà không thành công, hãy tiếp tục nhấn vào Begin Recovery bên dưới.

Nếu bạn đã mất tất cả các thiết bị xác thực yếu tố thứ 2 (2FA), thì bạn có thể sử dụng trình duyệt mà bạn đã đăng nhập thành công gần đây để khôi phục quyền truy cập. Vì lý do bảo mật, bạn sẽ phải đợi 3 ngày để nhận được mã truy cập tạm thời sau khi hoàn tất xác minh.

Bước 1
Xác minh địa chỉ email được liên kết với tài khoản Cloudflare của bạn

Bước 2
Xác minh thiết bị mà bạn đã đăng nhập trước đó

Bước 3
Cloudflare sẽ xem xét yêu cầu của bạn và gửi email cho bạn sau 3-5 ngày

**Comment by hoaquynhtim99** [comment]
@anhtunguyen em có góp ý ạ:

Hiện tại khi gửi yêu cầu tắt xác thực 2 bước, hệ thống chỉ thêm thông báo vào hệ thống, cái này dễ bị trôi. Như HSTDT gần như ít ai quan tâm đến số thông báo đó, vì nó lẫn nhiều với các thông báo khác. Nên bổ sung thêm:
- Đếm số thành viên gửi yêu cầu tắt xác thực 2 bước ở "Các công việc chờ xử lý từ các module" tại trang chính /admin/index.php?language=vi&nv=siteinfo
- Tại trang danh sách users /admin/index.php?language=vi&nv=users thêm bộ lọc các tài khoản đang yêu cầu tắt xác thực 2 bước.

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Anh đã làm xong theo y/c của em. Cập nhật mới nhé
