### ISSUE TITLE
NukeViet 4.6: Cần thay đổi mẫu các email gửi đi của module users

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3696]
Cần rà soát các email gửi đi từ module users và cả hệ thống (nếu được):

- Bổ sung username vào câu xin chào. Ví dụ **Xin chào Nguyễn Văn A (tên đăng nhập: nguyenvana)**
- Bỏ chữ ký cuối email kiểu "Quản trị site"

**Comment by anhtunguyen** [comment]
Để có thể sửa nhanh, tạm thời anh đã làm như [ở đây](https://github.com/nukeviet/nukeviet/commit/bf795e6909ee18233624755d38eb13f13da7ffd7).
@hoaquynhtim99 Em cho các bạn chỉnh sửa lại ở các chỗ không có trong nhân của NukeViet theo ghi chú [ở đây](https://github.com/nukeviet/nukeviet/wiki/Ghi-ch%C3%BA-ph%C3%A1t-tri%E1%BB%83n-NukeViet-4.6#04122023-qu%E1%BA%A3n-l%C3%BD-l%E1%BB%9Di-ch%C3%A0o-trong-email)
Tương lai sẽ thay bằng module templates
