### ISSUE TITLE
NukeViet 4.6: Nhu cầu bổ sung tính năng gán quyền điều hành chung có thời hạn

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3697]
Do nhu cầu cấp quyền điều hành chung hoặc quyền quản lý module trong một thời gian cụ thể nào đó nên cần tính năng này.

- Khi cấp quyền có thêm ô chọn thời điểm hết hạn (ngày, giờ). Bỏ trống thì cấp vô thời hạn.
- Đối với cấp điều hành chung chắc có thêm ô trạng thái xử lý khi hết hạn: Đình chỉ/ chuyển thành quản trị module (tùy chọn này mở ra danh sách module như cấp quyền quản lý module)
- Yêu cầu ghi nhật ký lại việc cấp quyền và tự đình chỉ quyền để xem lại giống như nhật ký mở lại/ đình chỉ quản trị như hiện tại.

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Theo anh thì không nên tạo sẵn trạng thái xử lý khi hết hạn vì nó sẽ gây ra vòng lặp (ví dụ: chuyển từ Quản trị chung sang Điều hành module: Sau khi hết hạn Quản trị module thì lại phải làm gì?). Tốt nhất là trước kỳ hạn 10 ngày thì báo cáo với quản trị cấp trên để họ có phương án giải quyết
