### ISSUE TITLE
Chấp nhận  <style amp-custom> cho cấu hình AMP mobile

### ISSUE THREAD

**Issue by hades-1997** [nukeviet/nukeviet#3703]
Em đang gặp vấn đề khi làm giao diện cho mobile. Khi hiển thị trên trang thì style amp-custom phần amp-custom bị xoá mất. google không chấp nhận điều này ạ

**Comment by anhtunguyen** [comment]
@hades-1997 Tôi đã fix. Bạn cập nhật lại mã nguồn nhé.

**Comment by hades-1997** [comment]
> @hades-1997 Tôi đã fix. Bạn cập nhật lại mã nguồn nhé.

a ơi cho e hỏi thêm ạ : 
+ có cách nào không tự động thêm jquery.min.js khi teamplate có <body></body> không ạ
+ khi e thêm noscript <style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style> /noscript thì thẻ style amp-boilerplate bị nhảy ra khỏi noscript

![image](https://github.com/nukeviet/nukeviet/assets/70182883/4b81bfbf-6f22-4020-94be-c7bf0207c08a)

**Comment by hoaquynhtim99** [comment]
Cái này nếu làm đội code sẽ nghiên cứu về AMP và sửa 1 lần để full support. Sửa nhỏ nhỏ này qua từng issue không ổn.

**Comment by hades-1997** [comment]
> Cái này nếu làm đội code sẽ nghiên cứu về AMP và sửa 1 lần để full support. Sửa nhỏ nhỏ này qua từng issue không ổn.

e thấy nó chỉ còn 2 vấn đề đó á a. cái noscript với cái nó tự động insert jquery

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 Vấn đề thứ 2 mà bạn ấy nêu, nếu mình nhìn rộng thêm, liên quan đến các html tags nằm trong `<noscript></noscript>` chứ không chỉ liên quan riêng đến AMP đâu. Đúng là lỗi em à.
@hades-1997 Vui lòng tạo issue mới khi có câu hỏi mới khác với câu hỏi đầu
