### ISSUE TITLE
Xử lý lại check code khi cài đặt/update NukeViet 4.5 và 4.6.

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/nukeviet#3708]
Trong issue này mô tả đến NukeViet 4.5, NukeViet 4.6 cũng cần rà soát các vấn đề tương tự.

- Curl là thư viện khuyến khích nên có, khi cài đặt bình thường nhưng cài đặt xong bị trang trắng sau 1 khoảng thời gian do includes/ini.php dùng trực tiếp curl như là 1 thành phần bắt buộc. Các phiên bản trước không bị.
- ini_get_all là hàm sẽ bị disabled trên một số hosting (chạy nhưng kết quả trả về là null), hiện includes/ini.php dùng nó như một thành phần bắt buộc trong khi cài đặt không cần dùng và không kiểm tra nó, dẫn đến cài xong không chạy được. Các phiên bản trước không bị.
    + $ini_list trả về null do đó đoạn kiểm tra session sẽ bị `exit('Session object not supported');`
    + null hàm này dẫn đến lỗi trên php8.2 khi truyền vào `$diff = array_diff_assoc($ini_list_new, $ini_list);`
- Xem xét trong một số trường hợp file data/config/config_ini.xxxx.php ghi ra đoạn

```
ini_set('display_errors', '0');
ini_set('display_startup_errors', '0');
ini_set('log_errors', '0');
ini_set('session.cookie_httponly', '1');
ini_set('session.gc_maxlifetime', '3600');
ini_set('user_agent', 'NV4');
```

Nhưng hàm ini_set bị cấm sẽ không chạy.

Đây là danh sách thực tế các hàm bị chặn trên Byethost Free

```php
$sys_info['disable_functions'] = ['php_uname', 'putenv', 'exec', 'phpinfo', 'system', 'passthru', 'escapeshellarg', 'escapeshellcmd', 'proc_close', 'proc_open', 'ini_alter', 'popen', 'pcntl_exec', 'socket_accept', 'socket_bind', 'socket_clear_error', 'socket_close', 'socket_connect', 'socket_create_listen', 'socket_create_pair', 'socket_create', 'socket_get_option', 'socket_getpeername', 'socket_getsockname', 'socket_last_error', 'socket_listen', 'socket_read', 'socket_recv', 'socket_recvfrom', 'socket_select', 'socket_send', 'socket_sendto', 'socket_set_block', 'socket_set_nonblock', 'socket_set_option', 'socket_shutdown', 'socket_strerror', 'socket_write', 'stream_socket_server', 'pfsockopen', 'disk_total_space', 'chown', 'diskfreespace', 'getrusage', 'get_current_user', 'set_time_limit', 'dl', 'listen', 'chgrp', 'link', 'symlink', 'proc_nice', 'proc_get_stats', 'proc_terminate', 'shell_exec', 'ssh2_exec', 'posix_getpwuid', 'posix_getgrgid', 'posix_kill', 'ini_restore', 'dbase_open', 'posix_mkfifo', 'sleep', 'imap_open', 'apache_child_terminate', 'apache_get_modules', 'apache_get_version', 'apache_getenv', 'apache_lookup_uri', 'apache_note', 'apache_request_headers', 'apache_response_headers', 'ini_get_all', 'apache_setenv', 'getallheaders', 'virtual', 'curl_multi_exec'];
```

**Comment by anhtunguyen** [comment]
@hoaquynhtim99 
- Các dòng `ini_set` trong file data/config/config_ini.xxxx.php chỉ xuất hiện khi ini_support là true.
- Anh đã không sử dụng `ini_get_all`
- Curl đã chuyển sang dạng bắt buộc. Nếu thư viện Curl không được cài đặt hoặc các functions cơ bản của nó bị cấm sử dụng thì sẽ xuất hiện thông báo lỗi ngay, site sẽ không chạy.

**Comment by hoaquynhtim99** [comment]
@anhtunguyen trong `$sys_info['disable_functions']` bên trên nó có hàm `curl_multi_exec` hàm này thực tế chưa thấy dùng bao giờ. Nhưng nó bị tính thành `$sys_info['curl_support'] = false;` nên không dùng được ấy anh.

**Comment by hoaquynhtim99** [comment]
Em đã sửa để giảm bớt cấp độ check. Giống như ở install/ini.php.
