### ISSUE TITLE
E gặp vấn đề tự động thêm jquery vào khi có thẻ body, và code style trong noscript bị nhảy ra ngoài ạ

### ISSUE THREAD

**Issue by hades-1997** [nukeviet/nukeviet#3709]
+ `<script src=" jquery.min.js"></script>` tự động thêm vào sau thẻ body
+ khi e thêm `<noscript>  <style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style> </noscript>` thì thẻ style amp-boilerplate bị nhảy ra khỏi noscript

**Comment by anhtunguyen** [comment]
@hades-1997 
- Vấn đề tự động thêm jquery: Nếu bạn không muốn tự động thêm jquery, hãy mở file `includes/footer.php`, tìm đến: `$optimizer->process();` và thay bằng `$optimizer->process(false);`. Hoặc nói chung bạn tìm kiếm tất cả các chỗ có từ khóa `$optimizer->process(` và thay bằng `$optimizer->process(false`
- Vấn đề nội dung trong `<noscript></noscript>` bị nhảy ra ngoài: Đúng là có lỗi này. Chúng tôi sẽ đưa ra bản vá lỗi sớm

**Comment by anhtunguyen** [comment]
@hades-1997 Bạn cập nhật lại mã nguồn nhé

**Comment by hades-1997** [comment]
> @hades-1997 Bạn cập nhật lại mã nguồn nhé

![image](https://github.com/nukeviet/nukeviet/assets/70182883/df3cf2b3-3b43-4d8d-8b3d-e56096db8662)
Dạ e làm được rồi ạ. cảm ơn a nhiều ạ.

**Comment by hades-1997** [comment]
> * $optimizer->process();

khi e thêm biến $optimizer->process(false); thì khi e tạo 1 trang layout khác thêm bằng tay jquery.min.js nó cũng tự động bị xoá đi ạ

**Comment by anhtunguyen** [comment]
Cách xử lý đơn giản nhất: Đổi tên jquery.min.js thành jquery.js

Vào Th 2, 18 thg 12, 2023 vào lúc 12:14 Đắc Lợi ***@***.***>
đã viết:
