### ISSUE TITLE
Lỗi cài đăt nukeviet tại bước 6 

### ISSUE THREAD

**Issue by kapno** [nukeviet/nukeviet#3713]
Lỗi cài đặt nukeviet ver 4.5.0.3 tại bước 06Thông tin website. 
Nhập đầy đủ thông nhấn thực hiện -> web phát sinh lỗi : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'

log ghi nhận
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 17]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 22]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 27]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 32]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 37]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 42]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 47]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 52]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 57]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 62]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 67]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 72]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 77]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 82]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 87]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 92]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 97]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 102]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 107]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 112]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 117]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 122]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 127]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 132]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 137]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 142]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 147]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 152]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 157]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 162]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 167]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 172]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 177]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 182]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 187]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 192]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 197]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'phone' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 202]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'] [FILE: /modules/users/language/data_vi.php] [LINE: 208]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2' for key 'PRIMARY'] [FILE: /modules/users/language/data_vi.php] [LINE: 213]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3' for key 'PRIMARY'] [FILE: /modules/users/language/data_vi.php] [LINE: 218]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4' for key 'PRIMARY'] [FILE: /modules/users/language/data_vi.php] [LINE: 223]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'PRIMARY'] [FILE: /modules/users/language/data_vi.php] [LINE: 228]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6' for key 'PRIMARY'] [FILE: /modules/users/language/data_vi.php] [LINE: 233]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '7' for key 'PRIMARY'] [FILE: /modules/users/language/data_vi.php] [LINE: 238]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'title' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 244]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'title' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 249]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'title' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 254]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'title' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 259]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'title' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 264]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'title' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 269]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'title' in 'field list'] [FILE: /modules/users/language/data_vi.php] [LINE: 274]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'] [FILE: /modules/users/language/data_vi.php] [LINE: 397]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2' for key 'PRIMARY'] [FILE: /modules/users/language/data_vi.php] [LINE: 402]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3' for key 'PRIMARY'] [FILE: /modules/users/language/data_vi.php] [LINE: 407]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4' for key 'PRIMARY'] [FILE: /modules/users/language/data_vi.php] [LINE: 412]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'PRIMARY'] [FILE: /modules/users/language/data_vi.php] [LINE: 417]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6' for key 'PRIMARY'] [FILE: /modules/users/language/data_vi.php] [LINE: 422]
[Fri, 12 Jan 2024 11:06:54 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '7' for key 'PRIMARY'] [FILE: /modules/users/language/data_vi.php] [LINE: 427]
[Fri, 12 Jan 2024 11:08:05 +0700] [localhost] [::1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'] [FILE: /install/index.php] [LINE: 883]

**Comment by hoaquynhtim99** [comment]
Bạn check lại bộ code của mình. Core của NukeViet không có file /modules/users/language/data_vi.php.
