### ISSUE TITLE
Lỗi editors 

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/nukeviet#3718]
Hiện tại NKV đang dùng ckeditor 4.22.1 hiện tại https://cke4.ckeditor.com/ckeditor4-secure-version/versions.json?v=4.22.1 nó không còn hỗ trợ bị 404. Nên update nó lên.

**Comment by hoaquynhtim99** [comment]
https://ckeditor.com/cke4/builder tại thời điểm này 4.22.1 là phiên bản mới nhất của dòng V4 rồi bạn. V5 hoàn toàn khác nếu có nó sẽ có ở bản 4.6, 5.0. Nâng lên Ckeditor 5 sẽ phải viết lại toàn bộ chứ không hẳn là nâng cấp bình thường.

**Comment by motcaiten** [comment]
> https://ckeditor.com/cke4/builder tại thời điểm này 4.22.1 là phiên bản mới nhất của dòng V4 rồi bạn. V5 hoàn toàn khác nếu có nó sẽ có ở bản 4.6, 5.0. Nâng lên Ckeditor 5 sẽ phải viết lại toàn bộ chứ không hẳn là nâng cấp bình thường.

Hiện tại thấy nó có bản 4.24 rồi.

**Comment by hoaquynhtim99** [comment]
@motcaiten 4.24.0 LTS là bản dành cho những người có giấy phép được CKSource cấp bạn. Open Source vẫn là bản 4.22.1

**Comment by hoaquynhtim99** [comment]
@motcaiten Hiện tại đội code đã tích hợp CKEditor 5. Bạn có thể trải nghiệm thử phiên bản đó nếu muốn cái mới hơn.
