### ISSUE TITLE
Lỗi không xem được nhật ký hệ thống

### ISSUE THREAD

**Issue by Giaiphaptop** [nukeviet/nukeviet#3754]
**Mô tả lỗi**
(Nukeviet 4.4.0.3) Mình mới chuyển web sang vps mới, trong admin mình click vào tab Nhật ký hệ thống thì bị lỗi 502 Bad Gateway (trong khi vào các tab khác bình thường). Nhờ các tiền bối hướng dẫn fix trường hợp này. Trân trọng cảm ơn!

**Comment by hoaquynhtim99** [comment]
Bạn cấu hình các tham số của nginx lên bằng này hoặc cao hơn xem
```
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
proxy_buffer_size 128k;
proxy_buffers 4 256k;
proxy_busy_buffers_size 256k;
```

Sau đó khởi động lại nginx
```
nginx -t
systemctl restart nginx
```

Đây là vấn đề thiết lập nginx hơn là vấn đề của code

**Comment by Giaiphaptop** [comment]
Hi hoaquynhtim99,

Thanks bạn! Mình config nginx theo thông số trên của bạn những vẫn bị lỗi 502 Bad Gateway. Mình đã thử download mã nguồn nukeviet 4.5 về cài mới thì bước Check Server có 2 chổ not compatible (Hình đính kèm), không biết đây có phải là nguyên nhân không? Rất mong bạn tư vấn giúp

Trân trọng cảm ơn bạn!

![not compatible](https://github.com/nukeviet/nukeviet/assets/169884713/e28db6c3-c662-4f26-84bb-16b41facf9fd)

**Comment by Giaiphaptop** [comment]
Hi hoaquynhtim99,

Mình gửi thêm hình ảnh đã cấu hình file nginx va proxy. Rất mong nhận được tư vấn từ bạn.

Trân trọng!
![nginx config](https://github.com/nukeviet/nukeviet/assets/169884713/c2dcf387-6bfc-45e8-84a4-298cc6b5c2fa)
![Proxy config](https://github.com/nukeviet/nukeviet/assets/169884713/a0a14a40-bec6-4423-b1ee-c55f6ebf4883)

**Comment by hoaquynhtim99** [comment]
Bạn thử lấy error_log tại /var/log/nginx/error_log xem sao.

**Comment by Giaiphaptop** [comment]
Hi hoaquynhtim99,

Mình không thấy có folder nginx trong folder log (như đường dẫn trên)
![duong dan](https://github.com/nukeviet/nukeviet/assets/169884713/57b10822-87c2-4d2d-9c6d-fbc9ba87ffda)

Trong Aapanel check nginx cũng không thấy có error
![Nginx_Errorlog](https://github.com/nukeviet/nukeviet/assets/169884713/948e48a1-841c-4e09-8da3-7f747e3f50fb)

Tuy nhiên, nếu mình dùng 1 domain mới, cài mới nukeviet (trên vps này luôn), cài xong vào admin thì xem được Nhật ký hệ thống của web.

Mong kinh nghiệm của bạn có thể giúp mình tìm được vấn đề

Trân trọng!

**Comment by hoaquynhtim99** [comment]
> Tuy nhiên, nếu mình dùng 1 domain mới, cài mới nukeviet (trên vps này luôn), cài xong vào admin thì xem được Nhật ký hệ thống của web.

Mình chỉ nghĩ được khả năng liên quan timeout và buffer size. Còn đâu phải mày mò chứ không nhận định được gì thêm. Bởi site cũ thì trong trang log đó nó khá nặng. Cả buffer lẫn load lâu. Bạn cứ thử các config buffer và timout to lên thử xem sao. k không được thì lên M thử

**Comment by Giaiphaptop** [comment]
Thanks bạn nhiều ha! Để mình tìm hiểu thêm
