### ISSUE TITLE
Lỗi đăng sản phẩm trong Nukeviet Version 4.4

### ISSUE THREAD

**Issue by Giaiphaptop** [nukeviet/nukeviet#3759]
**Mô tả lỗi**
Khi đăng sản phẩm mới thì báo lỗi: INSERT INTO vh_shops_group_items VALUES(464, :group_id)

Rất mong được anh em Nukeviet hỗ trợ cách Fix.

Thanks anh em rât nhiều!

Trân trọng

**Comment by Giaiphaptop** [comment]
Mình gửi thêm ảnh lỗi chi tiết mọi người tham khảo
![Loi them sp_chi tiet](https://github.com/nukeviet/nukeviet/assets/169884713/88654bcc-5e89-41cb-9fe4-e24f3968b3eb)

**Comment by hoaquynhtim99** [comment]
Chào bạn, đây là khu vực phát triển của NukeViet CMS. Module shops bạn có thể báo lỗi tại đây https://github.com/nukeviet/module-shops/issues. Trong quá trình báo lỗi bạn cần cho biết môi trường máy chủ bạn sử dụng, link bạn tải module shops, phiên bản của module shops bạn dùng

**Comment by Giaiphaptop** [comment]
Thanks admin nhé
