### ISSUE TITLE
Bổ sung trường số phone cho moduel users

### ISSUE THREAD

**Issue by thanhtrung87** [nukeviet/nukeviet#3772]
**Yêu cầu tính năng của bạn có liên quan đến sự cố không? Làm ơn miêu tả.**
Mô tả rõ ràng và ngắn gọn về vấn đề là gì. Ví dụ. Tôi luôn bực bội khi […]

**Mô tả giải pháp bạn muốn**
Mô tả rõ ràng và ngắn gọn về những gì bạn muốn xảy ra.

**Mô tả các lựa chọn thay thế bạn đã xem xét**
Mô tả rõ ràng và ngắn gọn về bất kỳ giải pháp hoặc tính năng thay thế nào mà bạn đã xem xét.

**Thông tin bổ sung**
Thêm bất kỳ thông tin mô tả hoặc ảnh chụp màn hình nào khác về yêu cầu tính năng tại đây.

**Comment by hoaquynhtim99** [comment]
@thanhtrung87 module users có chức năng tùy biến dữ liệu, tại đó bạn có thể tùy ý bổ sung những dữ liệu bạn có nhu cầu.
