### ISSUE TITLE
Báo lỗi PDOException trên Mariadb10.5

### ISSUE THREAD

**Issue by MINHDUONG0812** [nukeviet/nukeviet#3773]
->>>>> ĐOẠN MÃ DÙNG INSERT INTO DỮ LIỆU VÀO DATA
if ($nv_Request->isset_request('submit_word', 'post')) {
    $examid = $nv_Request->get_int('examid', 'post', 0);
    $array_question = $nv_Request->get_string($module_data . '_array_question', 'session');
    if (!empty($array_question)) {
        $array_question = unserialize($array_question);
        $array_question = $array_question['data'];

        try {
            $username_alias = change_alias($admin_info['username']);
            $upload_user_path = nv_upload_user_path($username_alias);
            $currentpath = $upload_user_path['currentpath'];
            $uploads_dir_user = $upload_user_path['uploads_dir_user'];

            // xóa câu hỏi cũ trước khi import
            $db->query('DELETE FROM ' . NV_PREFIXLANG . '_' . $module_data . '_question WHERE examid=' . $examid);

            $number = 1;

            // insert câu hỏi mới
            foreach ($array_question as $question) {
                if (!empty($question['answer'])) {
                    if ($question['type'] == '4') {
                        $question['answer'] = $question['answer'][1]['content'];
                    } else {
                        foreach ($question['answer'] as $index => $answer) {
                            if (preg_match_all("/\<img[^\>]*src=\"([^\"]*)\"[^\>]*\>/is", $answer['content'], $match)) {
                                foreach ($match[0] as $key => $_m) {
                                    $image_url = $image_url_tmp = $match[1][$key];
                                    $image_url = NV_ROOTDIR . '/' . $currentpath . '/' . basename($image_url);
                                    if (nv_copyfile(NV_ROOTDIR . $image_url_tmp, $image_url)) {
                                        $image_url = str_replace(NV_ROOTDIR, '', $image_url);
                                        $question['answer'][$index]['content'] = str_replace($image_url_tmp, $image_url, $answer['content']);
                                    }
                                }
                            }
                        }
                    }
                }
                $type = $question['type'];
                $max_answerid = count($question['answer']);
                $answer = !empty($question['answer']) ? serialize($question['answer']) : '';
                $answer_editor = 1;
                $answer_style = 0;
                $count_true = 1;
                $generaltext = $question['generaltext'];
                $_sql = 'INSERT INTO ' . NV_PREFIXLANG . '_' . $module_data . '_question
                (examid, title, useguide, type, answer, weight, answer_style, count_true, max_answerid, generaltext, from_question, to_question, answer_editor) VALUES
                (:examid, :title, :useguide, :type, :answer, :weight, :answer_style, :count_true, :max_answerid, :generaltext, :from_question, :to_question, :answer_editor)';
                $stmt = $db->prepare($_sql);
                $stmt->bindParam(':examid', $examid, PDO::PARAM_INT);
                $stmt->bindParam(':title', $question['question'], PDO::PARAM_STR);
                $stmt->bindParam(':useguide', $question['useguide'], PDO::PARAM_STR);
                $stmt->bindParam(':type', $type, PDO::PARAM_INT);
                $stmt->bindParam(':answer', $answer, PDO::PARAM_STR);
                $stmt->bindParam(':weight', $number, PDO::PARAM_INT);
                $stmt->bindParam(':answer_style', $answer_style, PDO::PARAM_INT);
                $stmt->bindParam(':count_true', $count_true, PDO::PARAM_INT);
                $stmt->bindParam(':max_answerid', $max_answerid, PDO::PARAM_INT);
                $stmt->bindParam(':generaltext', $generaltext, PDO::PARAM_STR);
                $stmt->bindParam(':from_question', $question['from_question'], PDO::PARAM_INT);
                $stmt->bindParam(':to_question', $question['to_question'], PDO::PARAM_INT);
                $stmt->bindParam(':answer_editor', $answer_editor, PDO::PARAM_INT);
                if ($stmt->execute()) {
                    $number++;
                }
            }
            $db->query('UPDATE ' . NV_PREFIXLANG . '_' . $module_data . '_exams SET num_question=' . ($number - 1) . ', count_question=' . $number . ' WHERE id=' . $examid);
            nv_exam_question_status($examid);
            $nv_Request->unset_request($module_data . '_array_question', 'session');
            $nv_Cache->delMod($module_name);
            nv_jsonOutput(array(
                'error' => 0,
                'redirect' => NV_BASE_ADMINURL . 'index.php?' . NV_LANG_VARIABLE . '=' . NV_LANG_DATA . '&' . NV_NAME_VARIABLE . '=' . $module_name . '&' . NV_OP_VARIABLE . '=question&examid=' . $examid,
            ));
        } catch (PDOException $e) {
            trigger_error($e->getMessage());
            nv_jsonOutput(array(
                'error' => 1,
                'msg' => $lang_module['error_unknow'],
            ));
        }
    }
}

->>>>> Báo lỗi do không tương thích PDO
        } catch (PDOException $e) {
            trigger_error($e->getMessage());
            nv_jsonOutput(array(
                'error' => 1,
                'msg' => $lang_module['error_unknow'],
            ));
        }
- Trên Mariadb 10.1 hoạt động ok
- Trên Mariadb 10.1 do không tương thích PDO

**Comment by MINHDUONG0812** [comment]
Trên Mariadb 10.5 do không tương thích PDO

**Comment by hoaquynhtim99** [comment]
@MINHDUONG0812 đoạn code trên không phải NukeViet CMS. Bạn cần báo lỗi đến tác giả đã cung cấp module trên cho bạn

**Comment by MINHDUONG0812** [comment]
Dạ vâng anh. Xin anh chỉ cách khắc phụ ạ

Vào 07:42, T.6, 21 Th6, 2024 Tan Dung Phan ***@***.***> đã
viết:

**Comment by hoaquynhtim99** [comment]
Bạn dọn dẹp hệ thống, sau đó:

`trigger_error($e->getMessage());` bạn sửa thành `trigger_error($e);` rồi thao tác lại. Khi lỗi bạn lấy nội dung file trong data/logs/error_logs/,,,.log gửi lên đây.

**Comment by MINHDUONG0812** [comment]
Gửi anh nội dung báo lỗi ạ. Xin nhờ anh giúp. Cảm ơn anh nhiều
[Fri, 21 Jun 2024 08:12:06 +0700] [hoctotvatli.vn] [171.251.197.175]
[Notice(8): Undefined index: useguide] [FILE:
/modules/test/admin/question-content.php] [LINE: 314]
[Fri, 21 Jun 2024 08:12:22 +0700] [hoctotvatli.vn] [171.251.197.175] [User
Notice(1024): PDOException: SQLSTATE[HY000]: General error: 1364 Field
'note' doesn't have a default value in /home/s4rnmhlbqv0g/
hoctotvatli.vn/vendor/vinades/nukeviet/Core/Database.php:499
Stack trace:
#0 /home/s4rnmhlbqv0g/
hoctotvatli.vn/vendor/vinades/nukeviet/Core/Database.php(499):
PDO->query('INSERT INTO nv4...')
#1 /home/s4rnmhlbqv0g/hoctotvatli.vn/modules/test/admin/questionword.php(82):
NukeViet\Core\Database->query('INSERT INTO nv4...')
#2 /home/s4rnmhlbqv0g/hoctotvatli.vn/admin/index.php(183):
require('/home/s4rnmhlbq...')
#3 {main}] [FILE: /modules/test/admin/questionword.php] [LINE: 96]

**Comment by hoaquynhtim99** [comment]
Lỗi trên do chưa chỉ ra trường `note` khi lưu CSDL. Đoạn SQL bạn sửa thành

```php
$_sql = 'INSERT INTO ' . NV_PREFIXLANG . '_' . $module_data . '_question
            (examid, title, useguide, type, answer, weight, answer_style, count_true, max_answerid, generaltext, from_question, to_question, answer_editor, note) VALUES
            (:examid, :title, :useguide, :type, :answer, :weight, :answer_style, :count_true, :max_answerid, :generaltext, :from_question, :to_question, :answer_editor, \'\')';
```

**Comment by MINHDUONG0812** [comment]
Dạ cảm ơn anh nhiều ạ

Vào 08:18, T.6, 21 Th6, 2024 Tan Dung Phan ***@***.***> đã
viết:

**Comment by MINHDUONG0812** [comment]
Dạ vâng cảm ơn anh [hoaquynhtim99](https://github.com/hoaquynhtim99) nhiều ạ. Em đã khắc phục được rồi. Cảm anh nhé
