### ISSUE TITLE
Biến $global_config['nat_ports'] không hoạt động

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#3786]
https://wiki.nukeviet.vn/nukeviet4:advanced_setting:file_config

![image](https://github.com/user-attachments/assets/4de6f579-5611-4b0b-952b-596a750b26ee)

Theo Wiki, biến $global_config['nat_ports'] dùng để khai báo khi sử dụng site với Reverse Proxy.
Tuy vậy, sau khi khai báo, một số vị trí của site vẫn nhận diện domain kèm với port "bên trong".
Bao gồm:
Hằng NV_MY_DOMAIN.

Đã kiểm thử với NukeViet 4.5.06. Biến $global_config['nat_ports'] được copy sang file config_temp bên trong thư mục data nhưng các cổng đã khai báo thì không được chuyển sang.

Môi trường máy chủ web: IIS.
Môi trường Proxy: Nginx.

**Comment by hoaquynhtim99** [comment]
@anhyeuviolet bạn thêm vào nginx

`proxy_set_header X-Forwarded-Port 80;` cho phiên bản http và `proxy_set_header X-Forwarded-Port 443;` cho phiên bản https sau đó thử lại nhé

Ví dụ:

```
server {
    listen 80;
    server_name nukeviet.local;

    location / {
        proxy_pass http://nukeviet:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port 80;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name nukeviet.local;

    ssl_certificate /etc/nginx/conf.d/server.crt;
    ssl_certificate_key /etc/nginx/conf.d/server.key;

    location / {
        proxy_pass https://nukeviet:8443;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port 443;
    }
}
```

Trong trường hợp bạn không có quyền sửa config của nginx thì ở config.php thêm vào cuối

```php
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO'])) {
    if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
        $_SERVER['HTTP_X_FORWARDED_PORT'] = 443;
    } else {
        $_SERVER['HTTP_X_FORWARDED_PORT'] = 80;
    }
}
```
