### ISSUE TITLE
Lỗi không hiển thị ảnh thumbnail ngoài trang chủ

### ISSUE THREAD

**Issue by hwangjiang80** [nukeviet/nukeviet#3794]
Khi đăng bài viết, có lỗi không hiển thị ảnh thumbnail ngoài trang chủ nếu chọn mục "Trình bày hình trong bài viết" là "Không hiển thị". Sau khi chọn "Hiển thị dưới bài viết" thì lại được

**Comment by hoaquynhtim99** [comment]
Mình thử thấy bình thường, 
![2024-10-15_11-36-26](https://github.com/user-attachments/assets/d7b03077-e552-41fe-9ec1-d2441559f536)
