### ISSUE TITLE
Lỗi không vào được phần Quản trị (Admin) sau khi hosting nâng cấp

### ISSUE THREAD

**Issue by hieuvuduy** [nukeviet/nukeviet#3802]
Chào các bạn, Hiện tại mình đang sử dụng  NukeViet eGovernment, hosting mình đang sử dụng PAVIETNAM. cách đây vài ngày PAVIETNAM thông báo nâng cấp server nhưng sau khi nâng cấp mình vào thể truy cập vào được mục quản trị. Đăng nhập đúng rồi, đến màn hình vào quản lý thì lại bị out ra ngoài màn hình đăng nhập.
Bạn nào biết nguyên nhân, xin hướng dẫn qua cho mình với
mình cảm ơn
![image](https://github.com/user-attachments/assets/567c55c9-651b-4587-9e87-84fc75731fb3)
![image](https://github.com/user-attachments/assets/a28edab0-d573-4782-bf40-7e8da3bbc1c1)

**Comment by hoaquynhtim99** [comment]
Chào bạn. Vấn đề này bạn đăng lên group để được giúp đỡ nhé https://www.facebook.com/groups/nukeviet  
Lỗi này đến từ việc hosting không lưu được session.
Trên Git này dành cho việc phát triển, bạn đọc quy đinh báo lỗi ở đây nhé https://github.com/nukeviet/nukeviet/blob/nukeviet4.5/.github/ISSUE_TEMPLATE.md
