### ISSUE TITLE
Xóa nhóm nhưng k thấy xóa bảng nv4_users_groups_detail đi kèm

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#3805]
https://github.com/nukeviet/nukeviet/blob/nukeviet4.5/modules/users/admin/groups.php#L180 

Xóa nhóm nhưng k thấy xóa bảng nv4_users_groups_detail đi kèm

**Comment by truongemcom** [comment]
cài lại module user mà dữ liệu còn nguyên luôn admin ơi

**Comment by hoaquynhtim99** [comment]
@truongemcom module users được code để không xóa dữ liệu người dùng khi cài lại bạn chứ nếu lỡ ấn cài lại thì nó sập hết cả site.
