### ISSUE TITLE
Bổ sung chức năng chuyển đổi dạng hiển thị chi tiết bài viết trong NukeViet 4.6

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/nukeviet#3814]
Bổ sung chức năng **Chuyển đổi hiển thị tin bài**: bình thường hoặc dạng tạp chí (magazine)

Kiểu như:
https://thanhnien.vn/tau-khong-so-trong-ky-uc-anh-hung-ho-dac-thanh-12-chuyen-tau-sinh-tu-185241220112307654.htm

Hiện nukeviet 4.5 đã có **Chọn bố cục layout** trong phần tùy chọn nâng cao. Nhưng tối nghĩa với người dùng.

Tách riêng ra sẽ dễ hiểu hơn cho người dùng nếu muốn chuyển dạng bài viết từ dạng tin bình thường sang dạng tạp chí)

**Comment by hoaquynhtim99** [comment]
Hợp nhất issue: https://github.com/nukeviet/nukeviet/issues/3814
