### ISSUE TITLE
Góp ý chức năng quản lý tag, module news

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#400]
Hiện tại khi thêm bài viết mới, muốn sử dụng từ khóa đã có thì chỉ cần gõ 1, 2 ký tự đầu tiên thì hệ thống tự tìm kiếm và đề xuất các từ khóa đó. -> điều này rất tiện dụng

Tuy nhiên, nếu ở mục quản lý tag có chức năng gắn tag đó vào bài viết cụ thể mà không cần phải sửa bài viết thì tuyệt. (Giống chức năng thêm bài viết vào topic)

Thêm nữa, trong mục quản lý tag, cũng nên cho display miêu tả (description) của tag đó, để khi vào quản lý, nếu thấy tag nào chưa có mô tả, thì có thể sửa hoặc thêm vào ngay. Chứ nếu như hiện tại, muốn tìm tag nào chưa có mô tả để thêm vào thì cũng hơi bị lâu. Nếu chỉ có vài chục từ khóa như site nhỏ thì không sao, nhưng nếu nukeviet mà hướng đến báo điện tử thì việc này hơi gay go đấy

Lại thêm phần tag tự động, cái này nên có hay không? vì nếu để tag tự động thì nó hiện ra vô số từ khóa đa số là vô nghĩa, mất công đi xóa, đặt biệt nếu khi tạo bài viết mà lỡ quên không chọn ít nhất một từ khóa trước khi lưu, thì ôi thôi, phải đi dọn các từ khóa vừa bị lưu tự động đó, sang bên phần quản lý tag thì nó đã sort theo alphabet rồi, không còn biết từ nào mới từ nào cũ nữa.

Do đó theo mình, nếu ô này không có từ khóa nào thì nên remind nhắc nhỡ chọn một từ khóa cho bài viết, nếu sau đó mà vẫn không có từ khóa nào được chọn thì để trống. ...
Và trong mục quản lý bài viết thì ở mỗi tiêu đề của mỗi bài chèn số lượng tag hiện có của bài viết đó giống phần quản lý topic, để có thể thêm vào khi cần. như thế sẽ giúp cho việc quản lý dễ dàng hơn

**Comment by vuthao** [comment]
@phongaz 
Tôi đã thêm nút khi click dúp chuột sẽ xóa nó đi, chứ cho về đầu nó kỳ kỳ.

Chức năng gắn tag cho bài viết giống như topic, tạm thời chúng tôi chưa phát triển thêm, do nhiều chức năng khác cần ưu tiên làm trước.
