### ISSUE TITLE
Incorrect content language code

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#499]
The content language code specified in the HTML content-language meta tag is "vietnamese". The correct and preferred code is "vi". Detail: http://w3techs.com/sites/info/nukeviet.vn

**Comment by thehung** [comment]
W3techs báo lỗi ngôn ngữ: http://w3techs.com/sites/info/pgdhadong.edu.vn
>Contradictory content language specifications
>>Found on page http://pgdhadong.edu.vn/
The text-processing language "en" specified in the HTML content language attribute is not amongst the languages specified in the HTTP content-language header.

Giải thích: http://w3techs.com/quality/alert/54

Ngoài ra việc xác định ngôn gnuwx đang sử dụng là en cũng chưa chuẩn.

**Comment by phongaz** [comment]
Cái này hình như mới chỉ fix trên theme modern thì phải

**Comment by vuthao** [comment]
Thêm đã có cái này ngay từ đầu nên ko phải fix nhé @phongaz 
 <html lang="{LANG.Content_Language}" xmlns="http://www.w3.org/1999/xhtml" prefix="og: http://ogp.me/ns#">

**Comment by phongaz** [comment]
ở Theme default không có cái này: xml:lang="{LANG.Content_Language}"
