### ISSUE TITLE
[SEO] - đường dẫn URL title nên tối ưu chuyển hết chữ Hoa về chữ thường

### ISSUE THREAD

**Issue by nethoabinh** [nukeviet/nukeviet#503]
Link mặc định: http://localhost/nukeviet/Tin-tuc/Ma-nguon-mo-NukeViet-gianh-giai-ba-Nhan-tai-dat-Viet-2011-10.html
Link nên sửa thành: .../ma-nguon-mo-nukeviet-gianh-giai-ba-nhan-tai-dat-viet-2011-10.html
Có nghĩa là chuyển tất cả các chữ cái viết hoa trên url --> thành chữ thường tốt cho seo.
Thanks

**Comment by vuthao** [comment]
tính năng này sẽ được cập nhật trong bản 4.0.11
