### ISSUE TITLE
Nên tách full_name thành firsname và lastname để phù hợp với nhiều module khác khi sử dụng

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#516]
Đa phần các website bây giờ đều tách 2 phần này ra để phù hợp với nhiều loại hình website và các mạng xã hội lớn cũng làm như vậy.

**Comment by vuthao** [comment]
@dangdinhtu2014 đã xây dưng xong chức năng này trên phiên bản mới  . Tứ kiểm tra xem có vấn đề ghì không nhé.
