### ISSUE TITLE
menusite bên trái trong admin không hiển thị trên iOs 8.1

### ISSUE THREAD

**Issue by favouritekid** [nukeviet/nukeviet#522]
Mình logon bằng ipad để viết bài không tìm được menu trái trong admin để đăng bài mới
![image](https://cloud.githubusercontent.com/assets/9113677/4963718/396090a6-6728-11e4-9631-84d30e30b580.jpg)
Môi trường thử nghiệm:
Trình duyệt safari 
Hệ điều hành iOs 8.1

**Comment by anhyeuviolet** [comment]
Có thể dùng development tools của Chrome để giả lập các trình duyệt và kích thước di động :D 
Cái này nếu ipad xoay dọc thì sẽ bị ẩn mất tiêu menu
![mobile-chrome](https://cloud.githubusercontent.com/assets/6290970/5796609/9759d42c-9fdd-11e4-9313-77b257b9a2ba.JPG)

Độ phân giải là 768 x 1024.

**Comment by thehung** [comment]
Cái này không phải do hệ điều hành hay trình duyệt mà do độ phân giải này
nó bị mất menu đó!

**Comment by trinhthinhhp** [comment]
@anhyeuviolet  dùng dể test trên smartphone thì coi trên firefox nhé, chư chrome lúc được lúc ko ko dc chuẩn đâu nha

**Comment by PhamQuocTien132** [comment]
Cái này không hiện thị trên Đúng màn hình 768px - Đã fix
