### ISSUE TITLE
module users: nên có yêu câu thay đổi tên đăng nhập cho phù hợp với cấu hình của module

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#531]
Trong phần cấu hình module users, phần thiết lập độ dài password, độ dài tên đăng nhập, các tên cấm sử dụng trong tài khoản, các mật khẩu đơn giãn cấm sử dụng, nếu admin thay đổi 1 trong các thông số này, nếu có thành viên đã đăng ký tài khoản trước khi thiết lập thì hợp lệ, nhưng sau khi admin thiết lập lại cấu hình thì hệ thống nên nhắc nhở thành viên thay đổi thông tin đó mới được login

Vi dụ: Độ dài mật khẩu hiện tại ngắn hơn so với thiết lập mới thì ngay khi đăng nhập, hệ thống yêu cầu đổi mật khẩu kèm theo lý do
Chứ hiện tại nếu users không thay đổi thông tin thành viên thì hệ thống cũng không nhắc nhở

Thêm nữa: Nội dung email thông báo kích hoạt tài khoản, hoặc đổi mật khẩu, đôi khi link kích hoạt hoặc đổi mật khẩu đó không ở dạng link mà dạng text, nếu người người không rành (không tự copy đường link text đó và dán vào trình duyệt) thì không thể nào kích hoạt được

Do đó cần có thêm câu: 
Nếu bạn không mở được link, hãy copy và dán vào trình duyệt để tiếp lục, (Đại loại như thế)

**Comment by vuthao** [comment]
@phongaz các ý kiến của bạn chúng tôi ghi nhận, và triển khai khi có điều kiện.

Tôi đã cấu hình lại việc gửi mail bằng html để cho link gửi trong mail sẽ có đường link để click: https://github.com/nukeviet/nukeviet/commit/cfc92f0676f2fc8ff2f0fbce31558e7cda3ad2c6
