### ISSUE TITLE
Lỗi trình bày ngôn ngữ 

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#534]
$lang_module['upload_mode_local'] = 'upload_ mode local';
language/en/admin_upload.php
cách dùng từ có vẻ không sát nghĩa ?
$lang_module['upload_mode_remote'] = 'upload mode remote';
$lang_module['upload_mode_local'] = 'upload_ mode local';

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/nukeviet/commit/0b0efa6d628e7401bf199897e51baf47c244bd76
