### ISSUE TITLE
module comment: kaspersky nhận định link đăng nhập redirect từ module comment

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#535]
ở bài viết được thiết lập chế độ cần đăng nhập để bình luận, khi click vào link thì trình duyệt virus cảnh báo là fishing url. 

![fishing url- module comment](https://cloud.githubusercontent.com/assets/6806295/5106907/8817e5b8-702f-11e4-8b13-bfacc79c3174.png)

Nếu người dùng khi click vào comment mà có cảnh báo như thế này thì họ mất niềm tin vào website, và chắc không ghé lại lần sau.

Ở phiên bản 3.4.02 thì không có hiện tượng này

Phiên bản NukeViet: 4.0.09 (download 18.11.2014)
Hệ điều hành: window 8.1 64-bit
Trình duyệt web: 38.0.2125.111 m

hosting: godaddy.
Máy chủ web: cPanel Version 11.46.0 (build 14)
Apache Version 2.4.10
PHP Version 5.4.34
MySQL Version 5.5.35-cll-lve

**Comment by vuthao** [comment]
@phongaz 
Phiên bản kis là bao nhiêu bạn.

**Comment by phongaz** [comment]
Bản kis 2014,

**Comment by vuthao** [comment]
@phongaz bạn kiểm tra lại dùm bản mới nhất tại https://github.com/nukeviet/nukeviet/archive/develop.zip còn bị lỗi không nhé, nếu còn lỗi vui lòng mở báo lỗi mới tại https://github.com/nukeviet/nukeviet/issues
