### ISSUE TITLE
Custom field select value của user không chọn theo value đã lưu vào CSDL 

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/nukeviet#539]
Custom field select value của user không chọn theo value đã lưu vào CSDL  mà luôn chỉ chọn value đầu tiên

- VD field acctype có 3 giá trị lựa chọn (1,2,3)

 - CSDL lưu field acctype = 2 trong table user_info

- Khi edit thành viên thì custom field select acctype luôn chọn value 1 (selected)

**Comment by vuthao** [comment]
@ webvangvn
Bạn kiểm tra xem phiên bản hiện tại trên kho code xem còn lỗi đó không, mình kiểm tra không thấy lỗi như thông báo.
