### ISSUE TITLE
Meta tag tự động chuyển thành chữ thường

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#540]
Meta tag thêm qua Admin Control Panel tự động chuyển thành chữ thường sau khi lưu khiến cho việc nhận diện không chính xác khi hệ thống nhận diện meta tag kiểm tra chính xác hoa thường.

**Comment by vuthao** [comment]
@thehung cho biết phiên bản bị lỗi nhé, phiên bản hiện tại không bị lỗi này.

**Comment by thehung** [comment]
Phiên bản NukeViet 3.x, 4.x đều bị tất!

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/hoaquynhtim99/nukeviet/commit/43a319a25614b22620fa5c8e330971976299d36b
