### ISSUE TITLE
Lỗi khi Loại bỏ tên module GIới thiệu trên url 

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#542]
Hiện tại vẫn bị lỗi khi Loại bỏ tên module Giới thiệu trên url 
![26-11-2014 15-21-54](https://cloud.githubusercontent.com/assets/8481170/5198139/0c42a36e-7580-11e4-8776-4a8b6c04a601.jpg)

**Comment by vuthao** [comment]
Module page là module đặc biệt của site.
Tôi đã cấu hình lại trên nukeviet sắp tới,  không cho Lỗi khi Loại bỏ tên module ảo của module này.
nếu cần url ngắn nhất bạn cần nhập vào module page:
fixed: https://github.com/nukeviet/nukeviet/commit/fea5cad992b744c6ffeeb328c5d68c333dfadd4b
