### ISSUE TITLE
Module comment: Lỗi hiển thị Đăng ký thành viên/Quên mật khẩu

### ISSUE THREAD

**Issue by hungga** [nukeviet/nukeviet#543]
Sau khi đọc xong bài, phần Ý kiến bạn đọc ---> click vào Bạn cần đăng nhập thành viên để có thể bình luận bài viết này -----> click vào Đăng ký thành viên hoặc Quên mật khẩu?, hiện ra cả giao diên mobile Đăng ký thành viên/Quên mật khẩu

Môi trường thử Nghiệm
- Phiên bản NukeViet: 4.0.10
- Hệ điều hành: Win 7-32bit
- Trình duyệt web: Chrome Version 39.0.2171.71 m
- Máy chủ web: XAMPP for Linux 1.8.1 
+ công cụ quản lý hosting: cpanel
+ Apache 2.4.10, MySQL 5.6.21, PHP 5.4.31

**Comment by vuthao** [comment]
@thangbv 
Chức năng bình luận hiện tại thiết lập: chỉ có thành viên mới được thảo luận, nhưng lại có form ngay để thảo luận, lưu lại thì  báo lỗi.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/cc96503b8ec8954e6cc42810b33e45a388eace80
