### ISSUE TITLE
Lỗi cắt ảnh của module news

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#544]
"Có bạn nào bị lỗi giống mình không, mình đã chỉnh cấu hình trong module ảo của news anh thumb (Kích thước của hình tại trang chủ) là 140px rồi nhưng hình vẫn bị crop kích thước 100px thôi, gây hiện tượng vỡ hình"

**Comment by anhyeuviolet** [comment]
:| Có vẻ như bị nhầm lẫn. 
Cấu hình tại modules chỉ là về kích thước. Còn đối với việc resize, crop hình khi up lên thì nằm trong Quản lý Files của Admin Panels.
Nhầm lẫn này khiến chỉnh hoài mà hình cứ bị crop ở 100px.

**Comment by hongoctrien** [comment]
Cái này sao rồi @anhyeuviolet , có phải là lỗi không bạn?

**Comment by anhyeuviolet** [comment]
Xác nhận KHÔNG phải lỗi bạn @hongoctrien  ạ !
Chỉ cần vào quản lý file, cấu hình thumbnail cho modules và thậm chí cho từng thư mục là ok.
Các quản lý trong từng modules chỉ quyết định kích thước thể hiện ra TPL chứ ko quyết định kích thước khi crop ảnh, nên ko thể coi là lỗi được. :D

**Comment by hongoctrien** [comment]
OK ^^
