### ISSUE TITLE
[Đề xuất] Tuỳ chỉnh Force HTTPS - Sitemap trong Robots.txt cho NukeViet

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#549]
:D Cũng không có gì đặc sắc ạ !
Vì Joomla có nút này 
![force-ssl](https://cloud.githubusercontent.com/assets/6290970/5241257/5c1396cc-794b-11e4-89d9-5ba7215144b9.png)
Mình mới cài SSL ( HTTPS) cho web thì xử lý 301 thủ công qua .htaccess cũng xong

RewriteCond %{HTTPS} !=on
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

Nhưng có thêm tuỳ chỉnh trong Admin Panel thì tiện hơn nhiều.
Ngoài ra thì URL Sitemap mặc định trong Robots vẫn còn là HTTP, nên hy vọng đường dẫn này có thể được điều chỉnh cho chính xác hơn khi áp dụng SSL cho trang.

Và cuối cùng là Rewrite URL cho NV thì giờ mình thấy nên dùng 

RewriteRule ^(.*?)sitemap\.xml$ index.php?nv=SitemapIndex [L]

Nó ra domain.com/sitemap.xml cho tiện. Nhiều bạn SEO, ko rành NV thì đều khó khăn khi tìm cái sitemap và NV vốn có sẵn và rất tốt này.

Vài góp ý, mong nhận được phản hồi ạ ! :D

**Comment by vuthao** [comment]
Tính năng này chúng tôi đã code xong, và sẽ cập nhật vào phiên bản tới
