### ISSUE TITLE
Công cụ chèn hình ảnh trong bài viết chưa lấy được phần chú thích - Module news

### ISSUE THREAD

**Issue by xuanluc73** [nukeviet/nukeviet#552]
Khi chèn ảnh vào bài viết và đánh dấu tích vào công cụ chèn ảnh nhưng chưa lấy được phần chú thích. Phần này theo tôi chỉ nên sử dụng công cụ chèn ảnh và chú thích một lần.
Xem hình:
![thuoc-tinh-anh-01](https://cloud.githubusercontent.com/assets/951683/5257940/0400cab6-7a15-11e4-8824-76e55ca13dd0.jpg)

![thuoc-tinh-anh-02](https://cloud.githubusercontent.com/assets/951683/5257944/2e3a0bda-7a15-11e4-9453-d594bda6d7ff.jpg)

**Comment by xuanluchp** [comment]
Lỗi này đã được fix trong bản close beta 4.0.13, nhưng ở bản 4.0.21 lại không có?
