### ISSUE TITLE
Bảng: nv4_vi_searchkeys không có dữ liệu

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#559]
Theo mình biết mỗi khi người duyệt web tìm kiếm một từ khóa nào đó và truy cập đến site của mình thì từ khóa đó được ghi vào table này
Tuy nhiên, ở nukeviet 4.0.10 vẫn chưa ghi dữ liệu vào bảng này.

Thêm nữa, có nên có chức năng thống kê từ khóa truy cập đến site từ bảng này, (ở admin hoặc dùng block để đưa ra ngoài site để phục vụ phân tích SEO không nhỉ?
Vì bảng này tồn tại nhưng chưa thấy có tools nào để thống kê nó cả. Nếu bảng này thống kê được từ khóa xuất hiện trên SERP gắn với bài viết nào thì tốt quá

**Comment by vuthao** [comment]
@phongaz 
bạn kiểm tra dùm phiên bản hiện tại đã ghi nhận chưa.

Còn block liên quan đến block này hiện tại chưa có.

**Comment by phongaz** [comment]
@vuthao Mình vừa kiểm tra, đã thấy có update rồ nhé
Hy vọng sẽ có block thống kê từ khóa tìm đến site giống như của google
