### ISSUE TITLE
Module statistics- Gía trị HEIGHT luôn bằng 0

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#560]
Khi xem đường dẫn từ SITE theo tháng thì biểu đồ không có màu
View source thì thấy giá trị  height="{HEIGHT}  bằng 0

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/eede4a50fcc1f76e5e7400d4232793caf4ffe0cc
