### ISSUE TITLE
Template: Lỗi hiển thị Block

### ISSUE THREAD

**Issue by hangluatdana** [nukeviet/nukeviet#562]
http://dana.vn/download/ 
- Block news global.block_groups: màu sắc Tiêu đề hiển thị không hợp lý khi ở Template Primary
- Block news global.block_tophits: lỗi hiển thị khi ở các Module khác

**Comment by xuanluchp** [comment]
Block header hiển thị bài viết khi đang lưu tạm trong trang quản trị.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/ccf197dab36bb6040e819761c15095de3058ed89
