### ISSUE TITLE
[SEO] nuke nhà mình nên dựa theo thằng này để cải thiện seo của code

### ISSUE THREAD

**Issue by nethoabinh** [nukeviet/nukeviet#571]
https://chkme.com/page-seo-tools
Đây là trang web, đội code và admin có thể nghiên cứu để làm đúng theo chuẩn seo trong này thì tốt
- Lưu ý nhỏ: vì LINK URL bài viết trên code nukeviet hiện tại nếu Viết hoa tiêu đề thì link url cũng viết hoa 
nên khi post vào đây, trang này nó tự động thu nhỏ kí tự trên đường link url đã gửi vào (mà url bài viết nukeviet thì có VIết hoa) nên báo lỗi không check được
Đã báo cáo anh em code nên thu hết chữ HOA trên url về chữ thường 
 nhưng chưa thấy phản hồi
mình nghĩ cải thiện được code theo chuản này thì ok
thanks kiu

**Comment by nukewebs** [comment]
Mình từng sửa theme mặc định bản 3.4 (cũng có thể gọi là làm mới) cố gắng lắm cũng chỉ đạt 75%
Bản 4.x chắc chắn khá hơn, chưa thử nhưng nếu lên 100% như wp là hơi khó. Thấy html giao diện mặc định  vẫn hơi ôm đồm chưa tối ưu. Nếu tối ưu có thể giảm được khoảng 25% lượng code phần giao diện  và phần seo cũng dễ cải thiện

**Comment by vuthao** [comment]
Theo các bạn nên cấu hình tính năng cho cả site, hay cả ngôn ngữ, hay cho từng module với tính năng: Chuyển thành chữ thường khi tạo liên kết tĩnh tự động

**Comment by nethoabinh** [comment]
Theo ý kiến em sẽ có tùy chọn URL như wordpress cho người dùng chọn
1- Domain.com/catagery/ten-bai-viet.html
2- domain.com/ten-bai-viet.html
3 - domain.com/vi -en/module/ten-bai-viet.html
làm như thế thì cho anh em thoải mái hơn trong việc lựa chọn url và cũng kích thích người dùng nukeviet , vì hiện tại đội ngũ support trong forum hơi nghèo nàn nên mình phải hoàn thiện sản phẩm đề người dùng thích luôn không chỉnh sửa nhiều nữa.
Em sẽ quay lại nukeviet và góp ý nhiều
không hứa giúp nuke tốt hơn wordpress nhưng sẽ ít nhất là ngang = wordpress để lôi kéo người dùng
