### ISSUE TITLE
Thiếu thẻ title cho ảnh thumb module news

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#573]
Tất cả các thẻ img của ảnh thumb module news đều thiết thẻ title: view cat, main, groups, topics

**Comment by vuthao** [comment]
@phongaz @thehung 
Trong thẻ img, không có quy định sử dụng thuộc tính title
Xem chi tiêt  tại: http://www.w3schools.com/tags/tag_img.asp

Nếu có thẻ title: thẻ ghi đè lên thẻ alt. Giữ chuột qua hình ảnh này sẽ hiển thị tiêu đề giống như tooltip.
