### ISSUE TITLE
Lỗi không kiểm tra được phiên bản

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/nukeviet#576]
http://nukeviet.net/nukeviet-develop/admin/index.php?language=vi&nv=webtools&op=checkupdate

Hệ thống: Lỗi: Không có nhiệm vụ nào được chỉ định
Các ứng dụng: Lỗi: Không có nhiệm vụ nào được chỉ định

**Comment by hoaquynhtim99** [comment]
Cái này mình xin được phép close
