### ISSUE TITLE
Lỗi hiển thị hình ảnh bài viết theo tag

### ISSUE THREAD

**Issue by hungga** [nukeviet/nukeviet#578]
Cấu hình hiển thị module tin tức: theo lưới mới lên trên
Hiển thị ảnh No-Image nếu không bài viết không có hình minh họa: đã chọn 1 hình logo mặc định cho mọi bài viết: /images/logo.png
Khi tìm kiếm theo tag, nó hiển thị danh sách bài viết nhưng lại sai đường dẫn làm hình ảnh ko hiển thị: domain.com/tag/images/logo.png

Môi trường thử Nghiệm

Phiên bản NukeViet: 4.0.10
Hệ điều hành: Win 7-32bit
Trình duyệt web: Chrome Version 39.0.2171.71 m,,...
Máy chủ web: XAMPP for Linux 1.8.1
công cụ quản lý hosting: cpanel
Apache 2.4.10, MySQL 5.6.21, PHP 5.4.31

**Comment by phongaz** [comment]
Lỗi này đã khắc phục rồi bạn nhé
https://github.com/nukeviet/nukeviet/issues/538
