### ISSUE TITLE
sử dụng các plugin bên ngoài

### ISSUE THREAD

**Issue by hqc210185** [nukeviet/nukeviet#579]
Mình thấy file "bootstrap.min.js" của nukeviet 4.0.10 đặt ở cuối trang web ở file "footer.tpl". một số plugin yêu cầu nạp file  "bootstrap.min.js". Nếu bấy giờ mình để file " "bootstrap.min.js""vào file "header.tpl" thì có bị ảnh hưởng đến một số chức năng nào đó không.

**Comment by hoaquynhtim99** [comment]
Không ảnh hưởng gì nhé bạn cứ đặt thoải mái
