### ISSUE TITLE
Lỗi /modules/comment/comment.php

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#580]
Nên chú ý: Use of undefined constant NV_PER_PAGE_COMMENT - assumed 'NV_PER_PAGE_COMMENT' in file /modules/comment/comment.php on line 13

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/nukeviet/commit/c48685145f09239129f212c1f7280a1a2cd74f31
