### ISSUE TITLE
Fix cứng Title Site trong code không sử dụng LANG

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/nukeviet#582]
Trong admin phần Title Site của Quản lý chuyên mục fix cứng vào tpl: Line 34

**Comment by thangvn** [comment]
là sao ? mình không hiểu?????? mình thấy bình thường.Chắc bạn nhầm gì rồi,bạn báo lỗi chi tiết hơn đi

**Comment by phamdinhhau** [comment]
Nghĩa là cái từ đó fix cứng vào file template ko sử dụng biến lang

**Comment by anhyeuviolet** [comment]
Chắc bác @phamdinhhau nói dòng này.

<td class="text-right"><strong>Title Site: </strong></td>

Nó là trong Admin theme/cat.tpl
Cái này bị fix cứng chứ ko dùng LANG nên nếu muốn thay đổi thì phải banh code tpl ra để sửa. :D

**Comment by hongoctrien** [comment]
ok, minh hiểu cái này, cũng đa thấy lỗi :D

**Comment by hoaquynhtim99** [comment]
Cho mình hỏi cái này của NukeViet hay của module shops nếu là của NukeViet cho mình cái link chính xác của file tpl đó.

**Comment by anhyeuviolet** [comment]
Trong :
nv410\themes\admin_default\modules\news\cat.tpl

Dòng 34 thì phải
<td class="text-right"><strong>Title Site: </strong></td>

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/c676421ffe1e7ded246421694c134f133be9169b
