### ISSUE TITLE
Google quét website mình đưa ra đường link này, dù mình đã chuẩn hóa

### ISSUE THREAD

**Issue by thangvn** [nukeviet/nukeviet#583]
Ngày 4-1-2015,Google quét website mình.

Mình kiểm tra thì thấy google có đưa ra 1 đường link :
ví dụ :
http://tenmien.com/index.php?language=vi&nv=comment&module=shops&area=0&id=90&allowed=4&checkss=1b0823f5b405bd944ef02752c901f735

Mình click vào đường link ,thì thấy đây là trang SHOP được mình gán làm trang chủ

Mình đã cấu hình từ lâu là :
1) Không kích hoạt chức năng đa ngôn ngữ
2) Loại bỏ kí tự ngôn ngữ trên URL
3) Loại bỏ tên module trên URL

không biết tại sao có đường link trên ? Mình không hiểu.

Phiên bản đang sử dụng	4.0.10
Host Linux

**Comment by thehung** [comment]
Bạn test bản mới nhất nhé @thangvn, module comment đã sửa lại.
