### ISSUE TITLE
Mới download - cài đặt khi xem bài nó hiện từ này ở trang chủ

### ISSUE THREAD

**Issue by nethoabinh** [nukeviet/nukeviet#584]
Thông báo từ Hệ thống

Nên chú ý Nên chú ý: Undefined variable: module_info in file /modules/comment/comment.php on line 111

Nên chú ý Nên chú ý: Undefined variable: module_info in file /modules/comment/comment.php on line 112

Nên chú ý Nên chú ý: Undefined variable: client_info in file /modules/comment/comment.php on line 113

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/nukeviet/commit/9fa926bad4c9c0281dbbbeff75f00d0c98664a07
