### ISSUE TITLE
Lỗi block content

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#586]
[Tue, 13 Jan 2015 18:21:21 +0700] [127.0.0.1] [Notice(8): Undefined variable: array_config] [FILE: /admin/themes/block_content.php] [LINE: 230]
[Tue, 13 Jan 2015 18:21:21 +0700] [127.0.0.1] [Warning(2): array_keys() expects parameter 1 to be array, null given] [FILE: /admin/themes/block_content.php] [LINE: 230]
[Tue, 13 Jan 2015 18:21:21 +0700] [127.0.0.1] [Warning(2): array_combine() expects parameter 1 to be array, null given] [FILE: /admin/themes/block_content.php] [LINE: 231]

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/nukeviet/commit/0cf29ad2fc99dcca6808fad288427100bf278d98
