### ISSUE TITLE
lỗi doublicate title

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#587]
google quét qua site thì báo lỗi này

![duplicate title](https://cloud.githubusercontent.com/assets/6806295/5740160/6aef3a88-9c33-11e4-83dc-eb5bc5d689b3.PNG)
(chỉ tập trung vào khu vực khoanh tròn thôi, các trang khác bị lỗi là do mình chuyển ký tự thôi của URL thôi)
kiểm tra trực tiếp trên site thì khi view
domain.com và domain.com/search/ đều có chung 1 title (modulename : news)

![loi duplicate title](https://cloud.githubusercontent.com/assets/6806295/5740169/7dfef352-9c33-11e4-90fc-4ede9a2af3a1.PNG)

Phien ban 4.0.10

**Comment by thangvn** [comment]
Bạn làm thử cách sau :
Vào phần Quản lý module , bạn sẽ thấy module SEEK,chọn sửa, sau đó nhập vào phần TÊN GỌI NGOÀI SITE là : Tìm kiếm
Sau đó lưu và ra ngoài refresh lại website,sau đó vào phần xem source ( trên firefox/chrome) xem.

![noname1](https://cloud.githubusercontent.com/assets/6823461/5754091/46a887e0-9cc6-11e4-91a7-0534c4858c00.jpg)

nếu thấy dòng <title>Lessons Tutorial - Học tiếng anh online hiệu quả nhất</title>

thành <title>Tìm kiếm - Học tiếng anh online hiệu quả nhất</title>
thì OK.

**Comment by phongaz** [comment]
Hiện tại trong phần quản lý modules, tên gọi ngoài site của module SEEK vẫn là " Tìm kiếm" mà bạn
URL domain.com/seek/: vẫn là Tìm kiếm - Học tiếng anh online hiệu quả nhất

vấn đề là 2 URL đều có chung 1 title.
URL domain.com/news/: Lessons Tutorial - Học tiếng anh online hiệu quả nhất
URL domain.com/search/: Lessons Tutorial - Học tiếng anh online hiệu quả nhất

**Comment by hoaquynhtim99** [comment]
URL thứ 2 của bạn URL domain.com/search/ là url của phần tìm kiếm module néws do chưa nhập từ khóa tìm kiếm, đội code đã sửa lại như sau https://github.com/nukeviet/nukeviet/commit/4905d3fd5ecf11d9591030abd58735cd6fa423b5
