### ISSUE TITLE
Lỗi "Trang điểm mặt" và "Trang điểm mắt" của module menu

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#588]
Trong module menu chỉ điền được 1 trong 2 dù url khác nhau, lỗi bị trùng tên không thể add thêm cả 2
"Tên này đã tồn tại"

**Comment by thangvn** [comment]
mình vừa kiểm tra và bị lỗi này trong phần menu site.Có lẽ lỗi là do,đoạn code đã lọc bỏ phần dấu Tiếng Việt nên phát sinh ra 2 url trùng nhau.

ví dụ : temien.com/trang-diem-mat.html ( trang đểm mặt)
temien.com/trang-diem-mat.html(trang điểm mắt)

Vì sự trùng lặp này là do Tiếng Việt nên mình góp ý với đội code : khi phát hiện có vấn đề trùng lặp như trên,nên hiển thị ra đường link đầu tiên với thông báo : "bạn đã có 1 bài viết(hay tiêu đề) ở đây,bạn có chắc là bạn đang làm đúng ? YES/NO",khi Users xác nhận YES thì tạo 1 đường link temien.com/trang-diem-mat-1.html ( thêm số nguyên vào cuối cùng) thì xem như là link khác.

**Comment by hoaquynhtim99** [comment]
Google xem trang-diem-mat-1, trang-diem-mat-2, trang-diem-mat-3 và trang-diem-mat là 1 link, nghĩa là số cuối cùng ko có giá trị, nên trường hợp trên bạn nên tự sửa ALIAS lại thành giá trị khác.
