### ISSUE TITLE
Lỗi Open Graph protocol trong module news

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/nukeviet#590]
Trong module news phần Open Graph protocol hình ảnh bị lỗi. Cụ thế là sai đường link dẫn hình . Trong đường dẫn chỗ domain có 2 dấu "/"

![capture](https://cloud.githubusercontent.com/assets/8292355/5788380/f374fece-9de6-11e4-8c0c-c8ba4c5630ce.PNG)

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/nukeviet/commit/243974d38286b2438463083677c4f2558df5cadc
