### ISSUE TITLE
Lỗi phần og:title

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/nukeviet#592]
Trong phần og:title ngoài trang chủ nó hiển thị tên module mặc định mà không phải là tên site nên khi đưa link website lên mạng xh thì nó hiện lên tên module. Giờ làm sao để nó lấy tên site làm og:title ?

VD : Tôi chọn module Sản phẩm làm module mặc định khi share wesbite với link domain.com thì nó hiện lên tên là "Sản phẩm"

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/288b894db1e0187adeb7608161afb7a89d1d7a4c
