### ISSUE TITLE
Định dạng URL phần "Theo dòng sự kiện" không chính xác.

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#593]
Phần các bài thuộc cùng dòng sự kiện (topic) hiển thị bên dưới khi xem chi tiết bài viết, cấu trúc vẫn là 
domainabc.xyz/kinh-nghiem-thu-thuat-nukeviet/Phat-hanh-phien-ban-thu-nghiem-Nukeviet-4-0-Close-Beta-9-4/

Với kết thúc là / thay vì .html

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/fb6a7ab7648c1e1ccc0fdc1d8eadee2646270557
