### ISSUE TITLE
Ckeditor load chậm do sử dụng link ngoài

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#594]
hiện tại trình soạn thảo đang load 3 liên kết có nguồn từ bên ngoài là trang
http://latex.codecogs.com/
Nó làm ảnh hưởng đến tốc độ hiển thị của site đặc biệt là trường hợp ko có mạng internet hoặc đường truyền quốc tế bị đất như vừa rồi. Đề nghị đội code điều hướng lại phần soạn thảo này

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/227ecc2b80c8e76dcdb6bfded1bf12259e72cb82
