### ISSUE TITLE
Lỗi tùy chỉnh dữ liệu user

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#595]
Chọn kiểu dữ liệu ngày tháng, khi thêm thành viên ở custom field không hiển thị bảng chọn ngày tháng (chỉ hiển thị textbox)

**Comment by vuthao** [comment]
fix: https://github.com/nukeviet/nukeviet/commit/c0ea74309fbf19a5c23afc93b7837950abdb3d07
