### ISSUE TITLE
Trình soạn thảo trù phú và thể hiện nội dung tin tức trên giao diện default

### ISSUE THREAD

**Issue by dylerb** [nukeviet/nukeviet#596]
Chức năng "Paste as text" vẫn giữ nguyên định dạng html của văn bản gốc.
Giao diện default thể hiện nội dung khác nhiều so với khi soạn thảo, ví dụ các list, quote,... Không nên tự động căn sẵn 2 lề khi thể hiện bản tin.
Thật ra thì chỉnh sửa CSS tí là được nhưng các bạn nên lưu ý fix sẵn trong code.

**Comment by vuthao** [comment]
Bạn có thể gửi các đoạn fix css đó để chúng tôi đưa vào bản mặc định.

**Comment by vuthao** [comment]
Sau 2 tuần không thấy tác giải trả lời, nên mình đóng câu hỏi lại.
Nếu cần bạn tạo câu hỏi mới nhé.
