### ISSUE TITLE
Class của layout body-right chưa hợp lý

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#597]
Khi chọn layout là body-right thì  có một khoảng trống  dư ra ở giao diện

![col-md-8](https://cloud.githubusercontent.com/assets/6806295/6002993/85b53006-ab2a-11e4-9e51-b2763cc48c94.PNG)

mình không biết suy luận như thế này có đúng không.
Ở cột news_column có 24 cột, trong 2 thẻ div  với class là col-md-8 = 16 cột   như vậy còn một khối 8 cột  đã tạo nên khoảng trống này.

Mỉnh thử chỉnh lại là col-md-12  cho 2 thẻ div thì  được như sau:
![col-md-12](https://cloud.githubusercontent.com/assets/6806295/6002882/aeb85eca-ab29-11e4-860b-b21007c26934.PNG)

bản develop down  9.00 PM ngày 01.02.2015.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/f19cb105e423e2fa846a1f01bd933d1e95135981
