### ISSUE TITLE
Lỗi trắng khi tối ưu website

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/nukeviet#598]
Khi kích hoạt chức năng "Kích hoạt chức năng tối ưu site" thì website bị khoảng trắng.
![capture](https://cloud.githubusercontent.com/assets/8292355/6037494/ac462fc4-ac86-11e4-9c16-0a98d14849c0.JPG)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/0780e90f5faab281ea051b7da812d7322e6d8be9
