### ISSUE TITLE
Lỗi link module download

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#599]
Module download khi sử dụng các link dạng redirect thì báo lỗi Wrong URL
VD như link này https://www.dropbox.com/s/0vs8e8zhvhpgx95/fta-m5-economic_models-Vi--26012015.pdf?dl=1

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/af1d14ffbb9de02224982cfada249fcb7ddc44e2
