### ISSUE TITLE
sử dụng từ không đồng nhất

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#601]
ở dòng 134, định nghĩa hằng là CHERSET trong khi biến ngôn ngữ lại là charset

https://github.com/nukeviet/nukeviet/blob/develop/includes/core/theme_functions.php#L134

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/f3b99abb3cf233171b905031f8e79b8c6b6ea69f
