### ISSUE TITLE
[Modules Download] Sai thẻ Meta Description phần viewfile (viewfile.php)

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#603]
Như tiêu đề, ở modules\download\funcs\viewfile.php; dòng 280
( Dòng 288 trên git hiện tại )
$description = $list_cats[$row['catid']]['description'];

Dòng này làm cho tất cả các file con đều lấy thẻ mô tả của chuyên mục chứa nó thay vì lấy introtext của từng file 
=> Google báo lỗi trùng thẻ mô tả.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/94281d2cb6fc8d41ebefff17b9a9f3eb106afd5a
