### ISSUE TITLE
2 lỗi nukeviet - Góp ý bằng Video mình quay cho dễ hiểu

### ISSUE THREAD

**Issue by nethoabinh** [nukeviet/nukeviet#604]
Link Video: https://www.youtube.com/watch?v=b0CsVuNb3r4
có 2 lỗi chính là z-index. submenu bị chìm trong admin
lỗi 2 là phần thiết lập layout cho từng theme
chi tiết video mình quay: https://www.youtube.com/watch?v=b0CsVuNb3r4

**Comment by anhyeuviolet** [comment]
Tình hình là mình không bị.

**Comment by hongoctrien** [comment]
@nethoabinh bạn vui lòng cung cấp thêm điều kiện test (hệ điều hành, trình duyệt,.....) ạ.

**Comment by trinhthinhhp** [comment]
cái này mình cũng ko bị, có khi bạn đã thay đổi trong file admin.css đê thay đổi thuộc tính z-index, mình test trên máy mình chrome, firefox, safari, opera, ie đều ok hết
