### ISSUE TITLE
[góp ý] Module nên bỏ tên module trên URL ( shop,news...)

### ISSUE THREAD

**Issue by thangvn** [nukeviet/nukeviet#608]
Với module được làm trang chủ mặc định thì được nhưng với các module không phải trang chủ thì nó ra thế này :

tenmien.com/news
tenmien.com/news/noi-dung-a.html
hoặc 
tenmien.com/page

Mong ban quản trị giải quyết trường hợp này để có thể bỏ đi được.

**Comment by vuthao** [comment]
Với hệ thống hiện tại của nukeviet là đa module, nên không bỏ tự động được nhé bạn.
Nếu muốn bỏ sẽ phải sửa rất nhiều, nên phiên bản tới chúng tôi không dự định làm việc đó.
