### ISSUE TITLE
Lỗi phân quyền module contact

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#609]
Quản trị tối cao và điều hành chung không sao, quản lý module không xem được các thư liên hê.

**Comment by vuthao** [comment]
Đây không phải là lỗi nhé @hongoctrien 
- Chú ý khi thêm một quản trị module liên hệ cần vào từng bộ phận để phân quyền các chức năng; Được xem phản hồi, Được trả lời phản hồi, Gửi liên hệ tới email
