### ISSUE TITLE
Cần sửa lại những nội dung thông báo liên quan đến câu hỏi bí mật

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#610]
Câu hỏi bí mật đã được giảm tầm quan trọng, cần sửa lại những nội dung thông báo và những tính năng liên quan đến câu hỏi bí mật cho phù hợp:
- Có cần thiết phải điền câu hỏi bảo mật khi tạo tài khoản tối cao không?
- Còn chỗ nào có những chức năng thừa có liên quan?

**Comment by vuthao** [comment]
fix: https://github.com/nukeviet/nukeviet/commit/9cc257d5ef104dbaf8cefd19a5f5c28aa46aec61
