### ISSUE TITLE
Lỗi quy trình reset mật khẩu

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#611]
Khi yêu cầu reset mật khẩu thì hệ thống vừa gửi link yêu cầu reset, vừa reset luôn:
> 
> Bạn vừa gửi đề nghị thay đổi mật khẩu đăng nhập của mình tại website NukeViet. Để thay đổi mật khẩu, bạn cần truy cập theo link dưới đây:
> 
> URL: .../index.php?language=vi&nv=users&op=lostpass&u=*&k=***
> 
> Dưới đây là thông tin đăng nhập mới:
> 
> Tên tài khoản: ***
> Mật khẩu: ***
> 

Phiên bản thử nghiệm: Test trên commit mới nhất ở thời điểm viết report này.

**Comment by vuthao** [comment]
Thực tế không như @thehung  báo nhé:
Nó thực hiện như sau:
1) Gửi mail thông báo kèm với tài khoản và mật khẩu mới.
2) Nếu đọc mail và click vào link thì nó sẽ đổi, với mật khẩu đó tránh phải gửi mail nhiều lần.
3) Nếu không mail, hoặc không click vào link coi như không có việc ghì xẩy ra
