### ISSUE TITLE
Lỗi khi add thêm OpenID cho tài khoản Google

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#612]
Trong trang quản lý openID http://.../users/openid/
Khi add thêm openid nó báo lỗi như sau:

> 400. That’s an error.
> 
> OpenID auth request contains an unregistered domain: http://demo.nukeviet.vn

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/076c1e40d3988b22761431d4aedd89db85411495
