### ISSUE TITLE
Lỗi khi tạo tài khoản mới trong tùy chọn tạo tài khoản mới sau khi đăng nhập openID

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#614]
Login bằng Gmail chưa tồn tại trên hệ thống, sau đó chọn chức năng tạo tài khoản mới, đăng ký username khác nhưng khi đăng ký xong nó không phải là username mình chọn mà là... tên email (hệ thống tự gán).

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/076c1e40d3988b22761431d4aedd89db85411495
