### ISSUE TITLE
module statistics-lỗi 404

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#615]
Khi phân quyền xem cho module statistics, thì gặp lỗi 404
ví dụ: khi chọn god admin là người được truy cập thì những thành viên, khách, học nhóm khác sẽ bị lỗi 404. và google cho biết là bị duplicate title.

![capture](https://cloud.githubusercontent.com/assets/6806295/6330123/52703aa4-bba8-11e4-9bdb-b12222def76b.PNG)

**Comment by trinhthinhhp** [comment]
@phongaz  cái này đúng rồi bạn, theo nguyên tắc tính năng này sau khi phân quyền cho ai thì người đó dc coi, còn lại là báo 404 ko cho coi
