### ISSUE TITLE
module news - url của topic không phân biệt hoa thường

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#616]
Lỗi này xảy ra khi sửa Alias của topic

URL chỉ có ký tự thường
![topic url 1](https://cloud.githubusercontent.com/assets/6806295/6330258/48a1c582-bba9-11e4-9b6a-2f50128b5c5c.PNG)

URL có chứa ký tự hoa,tuy nhiên, vẫn có kết quả như bên trên

![topic url 2](https://cloud.githubusercontent.com/assets/6806295/6330264/543943f2-bba9-11e4-94fb-86c075aa3702.PNG)

Phiên bản sử dụng: closebeta 4.0.10

Bổ sung: URL của group cũng bị như thế.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/2733adc8b8f39ee1975de4458cae5e796a44cabf
