### ISSUE TITLE
Thay đổi cách load lại khung comment

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#618]
Hiện tại, khi comment (hoặc xóa comment) thì load lại trang, đồng thời nhảy về đầu trang, cái này hơi bất tiện. Chỉ nên load lại phần comment chứ không load cả trang.

**Comment by vuthao** [comment]
@PhamQuocTien132 sửa lại cái này nhé.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/cc96503b8ec8954e6cc42810b33e45a388eace80
