### ISSUE TITLE
Lỗi khi đăng liên kết bài viết lên facebook, không nhận diện được fbid

### ISSUE THREAD

**Issue by xuanluchp** [nukeviet/nukeviet#619]
Facebook hoàn toàn không chấp nhận liên kết, không hiển thị hình ảnh thumb của liên kết và nội dung giới thiệu ngắn gọn của liên kết. Sau một thời gian mày mò, sử dụng trình sử lỗi liên kết của Faebook, Tôi đã tìm ra nguyên nhân bị lỗi khi post liên kết bài viết lên tường facecbook như sau:
Mở modules/news/theme.php tìm $meta_property['fb:app_id'] và sửa lại thành $meta_property['fbid'] thì khắc phục được lỗi trên.Tôi chỉ sửa được vậy, không biết trong nhân còn chỗ nào khác nưa không?

Lỗi link trước khi sửa:
![truoc](https://cloud.githubusercontent.com/assets/10148636/6386661/2652be34-bdaf-11e4-96e8-d4d89e0746ce.jpg)

Sau khi sửa xong:
![sau](https://cloud.githubusercontent.com/assets/10148636/6386665/40e7742e-bdaf-11e4-907d-18aea1880cfd.jpg)

Đề nghi đội code khắc phục lỗi này. 
Cảm ơn!

**Comment by anhyeuviolet** [comment]
"Mở modules/news/theme.php tìm $meta_property['fb:app_id'] và sửa lại thành $meta_property['fbid'] thì khắc phục được lỗi trên."

cái này do bạn sửa thành fbid thì nó không còn là meta của Facebook chỉ định nữa. Ở hình 2 bạn có thể thấy công cụ báo lỗi rõ ràng báo là thiếu fb:app_id và fb:admins. Do đó thiếu thì ko thể thành lỗi được chứ ko phải là đã sửa được lỗi như trên.

Lý do bạn gặp vđề này đó là apps ID của FB bạn điền vào trong cấu hình modules news bị sai, hoặc sai số, hoặc nó ko phải là ID của apps, hoặc nó ko phải là ID được cấp cho domain đó nên sẽ sinh lỗi.

Còn hình thumbs thì được chỉ định bởi <meta property="og:image"  .../> Nếu ko có thì FB tự quét từ trên xuống và lấy hình ảnh đầu tiên có kích thước đạt chuẩn.
Bạn nên xem lại hosting vì bot FB thi thoảng khá đểu và quét sai hình.
Đôi lời góp ý.

**Comment by vandien** [comment]
Mình đã thay $meta_property['fb:app_id']  thành $meta_property['fbid'] nhưng không khắc phục được tình trạng trên. Mặc dù Facebook App ID đã nhập trong cấu hình chung.
Có điều lạ là tất cả các trang của http://vietnamcoffee.asia thì không được, nhưng trang http://vietnamcoffee.asia/vn thì lại được. Không hiểu lý do gì ạ.
