### ISSUE TITLE
Tùy chọn loại bỏ tên module trên thanh breakcrumb

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#620]
Trong phần Cấu hình chung có chức năng loại bỏ tên module trên url, sau khi chọn thì sẽ bỏ tên module trên url nhưng trên thanh breadcrumb thì tên module vẫn còn, mình đề xuất thêm tùy chọn loại bỏ tên module trên thanh breakcrumb

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/44b6c964d46707ad702e66a901d2158125eef348
