### ISSUE TITLE
Thêm tag HREFLANG để google hiểu ngôn ngữ website và vị trí website

### ISSUE THREAD

**Issue by thangvn** [nukeviet/nukeviet#621]
Mình xem source thì thấy chỉ có thẻ

meta name="language" content="vietnamese"
và
meta http-equiv="content-language" content="vi"

2 thẻ này thì dùng cho BING và các máy tìm kiếm khác

Google hiện đang sử dụng thẻ HREFLANG
ví dụ :
<ink rel=”canonical” href=”http://www.samplesite.com/page.aspx” />
<link rel=”alternate” hreflang=”es-mx” href=”http://www.samplesite.com/mx/page.aspx” />
<link rel=”alternate” hreflang=”de” href=”http://www.samplesite.com/de/page.aspx” />

Đội code có thể xem thêm tại đây

http://returnonnow.com/2012/06/international-seo-hreflang-tag/

hoặc tại website GOOGLE support

https://support.google.com/webmasters/answer/189077?hl=en

**Comment by vuthao** [comment]
@thangvn theo tôi hiểu cái này được dùng cho cái bài viết (các trang)  có cùng nội dung nhưng viết trên các ngôn ngữ khác nhau, cứ không phải chỉ để mô tả ngôn ngữ sử dụng trong site.

@hoaquynhtim99, @hongoctrien  cái này tham khảo để sử dụng cho module như store trong nukeviet có vẻ hợp lý, module shop
