### ISSUE TITLE
Lỗi trùng lặp bài viết khi bỏ tên module trên url

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#622]
Tình hình là khi sử dụng Nukeviet 4 khi bỏ tên module trên url
Phát sinh tình trạng lặp thẻ meta-title và meta-description rất nhiều. 
Đề xuất đội code tiến hành thêm 2 trường meta-title - meta-description cho module shops và news 
để tăng khả năng tuỳ biến dữ liệu cho việc seo. Ngay cả cơ chế can thiệp vào các thẻ meta hiện giờ rất là bí bách.
http://banrenhat.com/dem-PE/
http://banrenhat.com/san-pham/dem-PE/

**Comment by vuthao** [comment]
@dangdinhtu2014 
Việc kiểm tra chức năng url có đúng hay không được giao cho từng module quyết định, nếu không đúng thì tự chuyển tới trang phù hợp.

tham khảo tại module news: https://github.com/nukeviet/nukeviet/blob/develop/modules/news/funcs/viewcat.php

Module News đã có sẵn Tùy chỉnh Tiêu đề site cho chuyên mục, description cũng đã có sẵn cho từng chuyên mục.

 @hongoctrien : em viết thêm chức năng kiểm tra chuyên mục và điều hướng trong trường hợp này nhé.
