### ISSUE TITLE
[Đề xuất] - thêm phần tùy chọn phần quảng cáo trong từng chuyên mục cụ thể trong module new - tin tức

### ISSUE THREAD

**Issue by nethoabinh** [nukeviet/nukeviet#623]
- Ví dụ: Tại module new có các catagery sau
- Tin Trong Nước - Banner 1
- Tin QUốc Tế - Banner 2
- Tin Giới Trẻ - Banner 3

. Thì đối ứng với từng chuyên mục con của module new - sẽ hiện những phần quảng cáo riêng biệt
Hiện nay phần tùy chọn quảng cáo chỉ chia ra hiện ở các module news, shop, about. chứ chưa chia ra hiện từng chuyên mục trong phần tin tức.
Cảm ơn nukeviet nhiều lắm!
năm mới sức khỏe và thành công nhé nukeviet!

**Comment by vuthao** [comment]
Việc này là  việc tùy biến theo từng site, không phải site nào cũng có chức năng này.

Nên chúng tôi không làm sẵn chức năng này.
