### ISSUE TITLE
đề nghị thay đổi relative URL thành obsolute URL

### ISSUE THREAD

**Issue by thangvn** [nukeviet/nukeviet#624]
Mình nhận được thông báo email report từ 1 số SEOer của Mỹ về tình trạng website.Họ nói rằng : 

Sau khi kiểm tra website của mình thì họ thấy rằng có 22 broken link ( link bị đứt /* tạm dịch */ ),mình kiểm tra lại thì vấn đề là do NUKEVIET dùng link RELATIVE URL .

![noname](https://cloud.githubusercontent.com/assets/6823461/6461342/8d7faaec-c1d1-11e4-9e84-a43fc6db8ffb.jpg)

họ nói (nguyên văn ) : "For better optimization you have to use absolute URL structure (both on link & Canonical) across the site"

vì vậy,mong đội code sửa thành obsolute URL để tốt cho SEO.Như hình trên thì URL đúng là 
...a href="http://mydomain.com/iphone-6-cu/iphone-6-cu-mau-Vang-3.html">......

**Comment by vuthao** [comment]
Hiện tại tôi đã bổ sung một plugin để làm việc này.

https://github.com/nukeviet/nukeviet/commit/d39a9bacaebd7caee30d611bf892d5033b6fe170

Cần vào admin để kích hoạt plugin rewrite_obsolute.php
