### ISSUE TITLE
Không thay đổi được Email nhận thông báo lỗi

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#627]
Trong cấu hình chung không thể thay đổi được Email nhận thông báo lỗi

**Comment by vuthao** [comment]
@nhimthulinh 
bạn cần thông báo rõ phiên bản nào để chúng tôi có thể kiểm tra lại.
Phiên bản hiện tại trên kho code tôi không thấy lỗi như thông báo.
