### ISSUE TITLE
Có nên hay không cho phép thay đổi tên module ảo?

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#632]
http://forum.nukeviet.vn/viewtopic.php?f=134&p=167040#p167040

**Comment by vuthao** [comment]
Chức năng này tôi đã xây dựng sẵn, nhưng việc này không nên thay đổi bởi url sẽ thay đổi hết.

Nếu buộc phải thay đổi, hãy sửa module đó, và bỏ thuộc tính readonly của tên module
/themes/admin_default/modules/modules/edit.tpl

đoạn: <input class="w300 form-control" name="mod_name" id="mod_name" type="text" value="{DATA.mod_name}" maxlength="55" readonly="readonly"/>

**Comment by hongoctrien** [comment]
@vuthao ví dụ module ảo của module news, hiện tại khi sửa thì tên module ảo không được thay đổi trong bảng nv4_config, mà vẫn giữ nguyên tên module cũ (nên các giá trị cấu hình của module không nhận được - lỗi cảnh báo).

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/06b1192d51d4c7ed91393a3490c3c8729f8d7032
