### ISSUE TITLE
[Đề xuất]- nên tạo sẵn một số tính năng có sẵn trong nukeviet

### ISSUE THREAD

**Issue by nethoabinh** [nukeviet/nukeviet#634]
- Chào anh em nuke và các bạn yêu nuke
Hiện nay để nuke cạnh tranh được với các mã nguồn mở khác , ngoài nuke phải nâng cấp nhiều tính năng khác thì không biết là mình nên tích hợp sẵn một số chức năng chuyên dành cho site việt ta hay dùng nên tích hợp luôn vào
- Ví dụ:
 + Tính năng quảng cáo popup/1ip/lần/ngày: hiện ra giữa màn hình. cái này các trang bán hàng nào cũng cần, toàn phải tự mò nên hơi lâu và bất tiện
+ Tính năng tích hợp hỗ trợ: Yahoo/skype
+ Tính năng: comment facebook
+  tính năng quảng cáo 2 bên 
+ Tính năng thay hình nền background: chỉ cần nhập url hình ảnh vào là thay đổi theo thời gian, không cần phải sửa code
+ Một phần nữa là tính năng Ghi chú :giống như trong phần quản trị của VBB hay có là có một khung ở giữa màn hình ghi lại những đoạn, text, code , đoạn soạn thảo, ý tưởng, công việc đang làm, mà mình muốn lưu lại. khi đăng nhập lại thì vẫn lưu cái đó. Bình thường là hay lưu ra một file Text nào đó, rất bất tiện.

**Comment by vuthao** [comment]
@nethoabinh 
Một bộ code không thể ôm hết tất cả các thư được. 
Nên những tính năng này cần để các module, block đảm nhiệm.

Chúng tôi sẽ không thể đưa hết những tính năng này vào bản mặc định được.
