### ISSUE TITLE
Logo hiện bên trái trong giao diện mobile

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/nukeviet#636]
Đáng lẽ phải nằm giữa như những phiên bản trước
![screen shot 2015-03-10 at 09 33 28](https://cloud.githubusercontent.com/assets/10916826/6568351/a629ec92-c708-11e4-9fdb-72a7ac0375b2.png)

**Comment by trinhthinhhp** [comment]
Cái này đã được cập nhật trên giao diện mặc định, bạn cập nhật mới nhất về xài nha
