### ISSUE TITLE
Không thấy phần cài đặt mới và đóng gói modules trong admin

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/nukeviet#637]
![screen shot 2015-03-10 at 09 44 52](https://cloud.githubusercontent.com/assets/10916826/6568440/219e6c1c-c70a-11e4-9b99-af7099b0af33.png)

**Comment by vuthao** [comment]
@anhutbeo 
Các tính năng này đã được chuyển sang phần Mở rộng trên menu ngang.
