### ISSUE TITLE
Tách giao diện nút bấm phân trang

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#638]
Hiện tại định dạng nút phân trang (các class css) được viết luôn trong trong hàm **nv_generate_page**.
Nên đưa các class này ra ngoài để tùy biến dễ hơn ở html.

**Comment by vuthao** [comment]
@hongoctrien việc này có thể thực hiện, nhưng tôi thấy nhu cầu này không cao, và khi xử ý cái này template viết cũng rất loàng ngoằng do có tói 5 trường hợp cho 1 liên kết, nên việc này sẽ không ưu tiên xử lý.
