### ISSUE TITLE
Trình bày menu đa cấp

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#639]
Nghiên cứu thay thế menu dọc trong ACP có thể hiển thị thêm cấp 3, hiện tại chức năng module (Ví dụ shops) phát sinh nhiều, trong khi menu chỉ hiển thị được cấp 2, việc sắp xếp, trình bày rất hạn chế.

Thử dùng cái này http://demo.onokumus.com/metisMenu/index.html

**Comment by volong1012** [comment]
Nếu có thể thì xin làm lại menu (slimmenu), hiện nay slimmnenu đang sử dụng nhiều hơn dạng của boostrap. Tuy nhiên vấn đề hiện nay của menu này là icon bên cạnh text khi hiển thị rất khó điều khiển theo ý muốn vì nó tách biệt hoàn toàn với tpl của site ví dụ :

**Comment by hoaquynhtim99** [comment]
Mình nghĩ không nên làm quá nhiều cấp, nếu quá nhiều chức năng hãy nghiên cứu về xu hướng người dùng, ví dụ họ muốn thực hiện chức năng A, trong đó có một chỗ sẽ liên kết đến chức năng B, rồi từ đó họ dùng chức năng C, D, hãy dẫn người dùng từ A để đạt được mục đích. Nếu quá nhiều chức năng hơn nữa có thể thay phần main của module bằng hệ thống icon (Gird system) rồi có thể sử dụng ajax .... để trình bày dữ liệu thay vì cứ cứng nhắc một kiểu left-menu - table data như hiện tại.

**Comment by hongoctrien** [comment]
Cái này anh Thảo có viết thêm rồi, nên bỏ qua issue này.
