### ISSUE TITLE
Cần thêm tính lượng xuất hiện của tags trong module

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#645]
Hiện tại mình thấy lên cần đếm số lượng và tần xuất xuất hiện tags lưu trong csdl để viết block tags theo phong cách nhiều lần thì thì cho font to, ít thì cho font bé... -> tăng độ đa dạng để code có thể tùy biến giao diện

**Comment by hongoctrien** [comment]
Trong bảng nv4_vi_news_tags có trường **numnews** rồi đó @trinhthinhhp,trường này là số lượng bản tin sử dụng tag này.

**Comment by trinhthinhhp** [comment]
@hongoctrien module page và module download còn thiếu tags chưa được tách biệt để đếm mà tags thì ko cần đến trường images và description bởi tags -> thừa images và description tốn thêm diện tích trong csdl

**Comment by trinhthinhhp** [comment]
Theo góp ý là ko lên phân tách tags ma gom chung, mà chỉ phân biệt tiếng anh tiếng việt trong csdl, ví dụ trong site doanh nghiệp có tin tức và about thì gom chung tags cho thuận tiện hiển thị mà đỡ phải code nhiều, index lên google cũng tiện hơn

**Comment by vuthao** [comment]
@trinhthinhhp tôi đã làm theo phương án bạn trình bày, nhưng cuối cùng lại phải bỏ đi, bởi nó phát sinh quá nhiều thứ để quản lý. nên chọn phương án cho từng module.
