### ISSUE TITLE
Đề xuất nâng cấp module menu

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#649]
- Hiện tại module menu chỉ cho gợi ý url tới cấp 2, nếu ở cấp 3 cấp 4 thì phải ra ngoài site vào từng chuyên mục để copy rất bất tiện
- Module menu nên trình bày dạng kéo thả thay vì chọn select như hiện tại
- Nâng cấp block của module này sang dạng n cấp thay vì chỉ có cấp 1 và câp 2 như hiện tại

**Comment by thaotrinhj** [comment]
vấn đề muốn hiện thị menu cấp 1,2,3 hay n này không thuộc vĩ mô cho lắm. Nên ko cần đến đội code giải quyết.
Mấy cái này là kiểu menu cũ từ bản 3.4 một thời.
bản 4.0 đã tách các dạng menu riêng thành các file riêng để người dùng có thể tự cài thêm các kiểu menu rồi, như cài block vậy thôi.
Rồi bạn sẽ thấy nukeviet sẽ có nhiều kiểu menu thay vì mấy kiểu menu như hiện nay.
Còn về việc kéo thả, xếp các lớp như wp thì phải đợi đội code thôi.

**Comment by vuthao** [comment]
Menu mặc định hiện tại đã hỗ trợ N cấp.
