### ISSUE TITLE
Đề xuất công bố bản kế hoạch phát triển 

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#650]
Hiện tại các nhánh lập trình viên không rõ Vinades có những ý tưởng gì để phát triển hệ thống và tiến triển công việc tới đâu. Khó theo dõi được sự phát triển bằng văn bản cụ thể. Những lỗi đã fix, chưa fix. Điều này làm cho các code mơ hồ trong việc đóng góp ý tưởng cũng như phân bổ công việc cho các nhánh muốn đóng góp.

**Comment by trinhthinhhp** [comment]
@dangdinhtu2014 Những lỗi chưa fix thì hiện ở trên issue, còn những lỗi đã fix thì đã được đóng lại

**Comment by dangdinhtu2014** [comment]
ý tưởng phát triển thì chưa có

**Comment by trinhthinhhp** [comment]
@dangdinhtu2014  ý tưởng thì cần @thehung  tổng hợp và công bố cho mọi người biết
