### ISSUE TITLE
Fix lỗi module banners

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#651]
Lỗi: khi khách hàng QC đăng nhập thì ô điền mã capcha hiển thị ở dạng password

**Comment by trinhthinhhp** [comment]
Bổ sung thêm, cần thêm nút thoát để khách hàng có thể thoát thay vì lúc nào cũng chỉ ở trạng thái login

**Comment by vuthao** [comment]
fixed: (đăng nhập thì ô điền mã capcha hiển thị ở dạng password) https://github.com/nukeviet/nukeviet/commit/17a66966845924e0d2a149fa0b3bf05b89d1fd53
