### ISSUE TITLE
Đề xuất nâng cấp module banners

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#652]
Hiện tại hệ thống đang cho khách hàng đăng nhập ở giao diền ngoài site
- Cần có giao diện đăng nhập và xem info riêng thay vì ở ngoài site
- Cần đếm được số lượng quảng cáo hiển thị và số lượng ở dạng đồ thị và dạng form bên dưới đồ thị

**Comment by vuthao** [comment]
Đã có sẵn chức năng này nhé em:
- Tạo tài khoản riêng (Ko dùng tài khoản của site, bởi nhiều người không muốn làm thành viên của site)
- Đã có sãn tính năng này: Cần đếm được số lượng quảng cáo hiển thị và số lượng ở dạng đồ thị
