### ISSUE TITLE
Thêm cấu hình hiển thị tên

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#653]
Hệ thông mới tách full_name thành first_name và last _name nên cần có cấu hình thứ tự hiển thị.
Việt Nam gọi là **Trần Cởi** chứ Mỹ gọi là **Cởi Trần** ^^

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/f6a399e2108ca9eaeb4fd096b15705a75386091e
