### ISSUE TITLE
Module upload bị thiếu trường hợp chiều cao nhỏ hơn trong khi chiều rộng lớn hơn

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#656]
Trong phần cấu hình resize  ảnh theo 2 chiều thếu trường hợp kích thước ảnh chó chiều cao dưới mức cấu hình height và chiều cao trên mức cấu hình weight:
- khi upload ảnh với kích thước height nhỏ và weight lớn thì chỉ thấy resize ảnh chiều weight -> cần xử lý trường hợp này: kéo chiều height về mức cấu hình rồi mới tiến hành resize chiều weight

**Comment by vuthao** [comment]
Hiện tại tôi đã sửa lại phần này, khi một trong hai điều kiện thỏa mãn sẽ tiến hành resize, crop, Nếu không sẽ  chỉ copy để đỡ tốn tài nguyên: https://github.com/nukeviet/nukeviet/commit/e9649bd127cb776a076adfdbc453b548a417663c
