### ISSUE TITLE
Please upgrade to PHP 5.3.7 or higher before trying to install Nukeviet Portal

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#658]
User Error
You are running an unsupported PHP version. Please upgrade to PHP 5.3.7 or higher before trying to install Nukeviet Portal
(Code: 17f6df873d6827f0a124d647c5ba0e1f)
Mặc dù php của mình trên >5.3 sau khi cài đặt thành công thì nó lại báo như vậy, ko thể truy cập web

**Comment by dangdinhtu2014** [comment]
Phiên bản đang sử dụng [PHP: 5.6.3]
Vị trí lỗi: 
includes/ini.php dòng 66
// code lỗi
if( version_compare( PHP_VERSION, '5.3.7' ) >= 0 )
// đã sửa
if( version_compare( PHP_VERSION, '5.3.7', '<' ) )

**Comment by phongaz** [comment]
Gỉa sử như phiên bản php của server thấp hơn, yêu cầu, thì khi cài đến bước 4, nó bảo không tương thích, và không có nút bước tiếp theo (chỉ có nút quay lại thôi).
Nếu sửa tiếp file install/ini.php giống như dangdinhtu2014 hướng dẫn ở file includes/ini.php thì mới cài được. 
sau đó mới xuất hiện lỗi như nhimthulinh thông báo

**Comment by hongoctrien** [comment]
[Fixed](https://github.com/nukeviet/nukeviet/commit/0a6117b97d3676c177bc3790cac6d1aff4796304)

**Comment by phongaz** [comment]
Hình như mới fix ở file includes/ini.php, cần phải fix  file install/ini.php thì mới cài được chứ nhỉ

**Comment by hongoctrien** [comment]
oh, cảm ơn @nhimthulinh, sai sót. :D
[Fixed](https://github.com/nukeviet/nukeviet/commit/62ca493812703e38870f7226ef41b2a9ff56c6ed)
