### ISSUE TITLE
Ngôn ngữ tiếng Việt và các ngôn ngữ khác chưa được đồng bộ

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#662]
Ngôn ngữ tiếng vệt và các ngôn ngữ khác chưa được đồng bộ (ngôn ngữ khác tiếng việt chưa được dịch)

**Comment by vuthao** [comment]
Tính năng này sẽ được làm trước khi đánh dầu phiên bản vào thứ 4 tới nhé em

**Comment by vuthao** [comment]
đã đồng bộ xong ở thời điểm hiện tại
