### ISSUE TITLE
Đề xuất thay đổi module statistics

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#666]
Hiện tại module statistics đang show ở ngoài site không được hợp lý, bởi thường thống kê truy cập site của các mã nguồn đều để trong quản trị chứ ko để ngoài site như module của nukeviet, mà thống kê chỉ để cho admin và quản trị coi chứ ko show ra cho khác
Đề xuất của mình là nên đưa vào trong admin và trình bày bằng đồ thị

**Comment by anhyeuviolet** [comment]
:D Cũng phải.
Bên ngoài chỉ cần block bộ đếm thể hiện là được.
Các thông tin thống kê khác không cần/không nên thể hiện hết ra ngoài như hiện nay.

**Comment by vuthao** [comment]
Module này được thiết kế để có thể phân quyền cho ai đó vào xem, mà không muốn cho vào trong khu vực quản tri.
Nếu muốn phân quyền, thực hiện chức năng phân quyền của module, và menu là được.

Hiện tại tôi đã thiết lập khi cài đặt mặc định module này chỉ có quản trị mới được xem: https://github.com/nukeviet/nukeviet/commit/116fc84032464af960e3f016633bd92aab3668e1

**Comment by phongaz** [comment]
Ở issue 615, khi phân quyền, người không được xem thì bị lỗi 404, nên chăng không được xem thì thông báo rồi redirect về url của modules hoặc home?
https://github.com/nukeviet/nukeviet/issues/615
