### ISSUE TITLE
Góp ý về soạn thảo văn bản editor

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#667]
Theo như hệ thống hiện tại đang tích hợp editor vào làm soạn thảo văn bản, nhưng ko tiện lợi một  chút nào
- Đối với những site họ ko cần đến toán học thì quá dư thừa 
- Đối với những site viết những công thức phức tạp thì lại là vừa
-> ý kiến nhứ sau: tách editor ra thành 1 plugin, trình soạn thảo sẽ ở dạng cơ bản thông thường không cần rườm rà như editor, khi người dùng cần editor họ chỉ cần vào kích hoạt plugin editor lên để thay thế cho trình soạn thảo kia là được -> giảm được tài nguyên đối với những site không cần sử dụng editor đầy đủ

**Comment by thehung** [comment]
Không cần phức tạp vậy.
CKeditor có sẵn chế độ cấu hình trình soạn thảo cơ bản hay đầy đủ, chỉ việc bổ sung cấu hình trình soạn thảo cho người sử dụng là xong.
