### ISSUE TITLE
Breadcrumb chưa hợp lý

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/nukeviet#669]
Mình vừa test bản dev mới nhất thấy breadcrumb đã gọn hơn. Tuy nhiên ví dụ nếu đặt module news làm main mà có phân trang ở main dẫn đến hiện tượng: ../news/page-2/.
Đề xuất:
- Ở main có phân trang thì url nên là: ../page-2/ thì đẹp hơn và breadcrumb cũng chưa cần hiện vì vẫn ở homepage.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/61338c6fd86bd9b103e6a355b6a1ae2569078fc1
