### ISSUE TITLE
[propose] Thêm nút "backup now" và tự động gửi email tại phần CSDL

### ISSUE THREAD

**Issue by nukewebs** [nukeviet/nukeviet#677]
Đề xuất thêm 2 tiện ích nhỏ:
1- Thêm nút backup now
Hiện nay phần Data backup  /admin/index.php?language=vi&nv=database&op=file 
chỉ có danh sách các file backup tự động, đôi khi không muốn tải file backup vào thời điểm trong danh sách mà muốn tải ngay file backup tại thời điểm đang xem. Những lúc như vậy mình phải vào hosting để tải.
Đề xuất thêm nút "backup now" ngay trong phần Admin này
<img src="http://i.imgur.com/zTgTzC5.png" style="max-width:100%"/>
2- Thêm chức năng tự động gửi file backup vào email
Chức năng tự động gửi email trong nukeviet đã có ở một số module như user, shop,... rồi.
Nay mình đề xuất thêm chức năng tự động gửi file backup vào email. (câc mã nguồn khác thấy hay có cái này)
<img src="http://i.imgur.com/gxwZQUC.png" style="max-width:100%"/>
Nếu email trống thì ngừng gửi.

**Comment by thehung** [comment]
Nếu muốn backup bạn qua mục chính: CSDL
Email không phải nơi để sao lưu dự phòng cơ sở dữ liệu, đặc biệt là với site lớn do đó tạm thời chúng tôi chưa ưu tiên tính năng này.

**Comment by vuthao** [comment]
Tính năng 1 đã được thêm.
Tính năng 2 nó chỉ chạy được với site nhỏ, site lớn không dùng được (do nhiều mail giới hạn dung lượng, và gửi với dung lượng lớn tỷ lệ thành công không cao), nên nhóm sẽ không dự định phát triển tính năng này

**Comment by hongoctrien** [comment]
Hiện nay công nghệ điện toán đám mây phát triển ầm ầm rồi, google drive, dropbox,....
Google có cho dùng api để tự động upload lên, chắc có lẽ sau này cũng phải nghiên cứu cái này để ai có nhu cầu dùng

**Comment by thehung** [comment]
@hongoctrien Làm cronjob thực hiện việc này để đưa file backup vào Dropbox hay Gdriver... sẽ chuyên nghiệp hơn. Không nên ôm đồm vào core hệ thống.

**Comment by hongoctrien** [comment]
dạ, ý em là như thế @@.
