### ISSUE TITLE
Lỗi ở phần cài đặt ứng dụng khuyên dùng

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#678]
Chọn ứng dụng, tải về cài đặt sau khi kiểm tra thông báo lỗi: Có một lỗi không xác định đã xảy ra.
![loi2](https://cloud.githubusercontent.com/assets/11238423/6710383/e6f25812-cdb2-11e4-82fe-191677a934bd.PNG)

**Comment by thaotrinhj** [comment]
- Không rõ ứng dụng khuyên dùng dựa theo tiêu chí nào. Nhiều khi vào ứng dụng khuyên dùng chẳng liên quan gì đến chủ đề của website và nhu cầu của người dùng.
- Còn về việc cài đặt các module, block,... nukeviet đang có nhiều thay đổi lớn. Dự là hầu hết ứng dụng trên store phải sửa lại thì cài đặt trong admin mới được. Nếu không phải chép đè, mà chép đè là hạ sách của việc cài đặt & quản lý ứng dụng.

**Comment by vuthao** [comment]
Không rõ ứng dụng khuyên dùng, được quản trị module Store trên site nukeviet lựa chọn.

Trên Nukeviet 4, sẽ phải kiểm tra từng ứng dụng. bởi hiện tại chưa có mấy ứng dụng cho Nuekeviet 4.
