### ISSUE TITLE
Lỗi cài đặt giao diện

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#679]
Không cài đặt được giao diện. Hệ thống giải nén giao diện không đúng thư mục.
Đúng ra phải giải nén vào thư mục **themes**, hiện đang giải nén vào thư mục gốc nên khi chuyển đến trang quản lý giao diện không thấy giao diện mới cài đâu cả.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/bbb625fe0aa7030632aa9e1dfdc8c725f77d973c
