### ISSUE TITLE
Lỗi Chức năng hiển thị nguyên một đoạn code trong bài viết, 	highlight code

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#680]
// chuỗi ban đầu
	$string = preg_replace( '/[^'.$basic . $utf8 . $special . '[:space:]]+/iu', '', $string );
	
	// chuỗi sau hiển thị ngoài site
	$string = preg_replace( '/[^'.$basic . $utf8 . $special . '"space"]+/iu', '', $string );

**Comment by dangdinhtu2014** [comment]
[: và :]  kí tự này bị biến đổi thành dấu nháy kép "

**Comment by vuthao** [comment]
Mất 2 tiếng ngồi mà chưa biết phải giải quyết cái này thế nào đây.
[: , :],  {: , :} là những ký tự bị ảnh hưởng

**Comment by vuthao** [comment]
fixed: https://github.com/vuthao/nukeviet/commit/4ae71c6bc0753be7b4146b58b1c6bde845e1774b
