### ISSUE TITLE
Xem xét khôi phục block hệ thống

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#681]
Xem chi tiết thảo luận ở đây: https://www.facebook.com/groups/nukeviet/947146455327455/?notif_t=group_comment

**Comment by nukewebs** [comment]
Theo em thì block theo giao diện như NV4 vẫn để (để chứa các block riêng của theme đó nếu có), và thêm block hệ thống chung nữa.
Vì nhiều block ko cần theo giao diện, thay theme vẫn dùng lại block đó. 
Mà hiện nay NV4 khi thay theme lại cắt block từ theme cũ sang theme mới, đến khi dùng lại theme cũ thì cũng phải cut lại block từ theme mới về block theme cũ. 
Mặt khác hiện nay khi cài block mới vào nó chỉ cài vào 1 theme nhất định đặt trước.
Do đó nên có block hệ thống dùng chung. thấy joomla xử lý rất tốt việc này.
