### ISSUE TITLE
Lỗi cảnh báo Missing argument và Undefined variabl khi view file module dowload

### ISSUE THREAD

**Issue by vanhuonghn011291** [nukeviet/nukeviet#682]
E cài thử module dowload và khi xem file thì bị thông báo lỗi này:
Thông báo từ Hệ thống
Lỗi cảnh báo Lỗi cảnh báo: Missing argument 7 for nv_comment_module(), called in E:\xampp\htdocs\demo\nukeviet11\modules\download\funcs\viewfile.php on line 270 and defined in file /modules/comment/comment.php on line 127
Nên chú ý Nên chú ý: Undefined variable: page in file /modules/comment/comment.php on line 187

Môi trường thử Nghiệm
- Phiên bản NukeViet: 4.0.11
- Hệ điều hành: windows 7
- Trình duyệt web: Mozilla Firefox 27.0, Crome 41.0.2272.89 m
- Máy chủ web: XAMPP 1.8.3 [PHP: 5.5.9] for Window

![global block catid - test](https://cloud.githubusercontent.com/assets/10495040/6717470/44d9dce4-cddf-11e4-908c-dc3759f9f38f.png)

**Comment by vuthao** [comment]
Lỗi này hiện tại đã được sửa, và sẽ cập nhật trong bản tới
