### ISSUE TITLE
Một số block không hoạt động

### ISSUE THREAD

**Issue by vanhuonghn011291** [nukeviet/nukeviet#683]
Em có test 1 số block thì thấy có block ko hoạt dộng:
1. global department của module liên hệ
2. global upload của module dowload
3. global voting của module thăm dò ý kiến
Môi trường thử Nghiệm
- Phiên bản NukeViet: 4.0.11
- Hệ điều hành: windows 7
- Trình duyệt web: Mozilla Firefox 27.0, Crome 41.0.2272.89 m
- Máy chủ web: XAMPP 1.8.3 [PHP: 5.5.9] for Window

![block khogn hoat dong](https://cloud.githubusercontent.com/assets/10495040/6718025/3334489a-cde3-11e4-9bf9-72d6f9dc7662.png)

**Comment by trinhthinhhp** [comment]
block upload chưa sửa dc, còn 2 block còn lại mình đã sửa lại rồi nhé, đợi cập nhật nha

**Comment by vuthao** [comment]
fixed:https://github.com/nukeviet/nukeviet/commit/a303b0bd6d8e057db7d1971cad3fa96c0fb41c05
với block upload bạn cần cấu hình  trong admin của module
