### ISSUE TITLE
Lỗi module voting không chỉnh sửa dược các voting

### ISSUE THREAD

**Issue by vanhuonghn011291** [nukeviet/nukeviet#684]
Khi chỉnh sửa voting nếu chỉ chỉnh sửa các phương án mà không chỉnh sửa tiêu đề câu hỏi thì sẽ bị lỗi không lưu được dữ liệu, có lẽ do trùng lặp...
Môi trường thử Nghiệm
- Phiên bản NukeViet: 4.0.11
- Hệ điều hành: windows 7
- Trình duyệt web: Mozilla Firefox 27.0, Crome 41.0.2272.89 m
- Máy chủ web: XAMPP 1.8.3 [PHP: 5.5.9] for Window

![loi module voting](https://cloud.githubusercontent.com/assets/10495040/6718157/28d9667c-cde4-11e4-97e5-6bfaed1d62d5.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/fa69b4acc5f3de28d0470e634bdddb42470d372e
