### ISSUE TITLE
Từ chối cài đặt ứng dụng do cấu trúc không hợp lệ

### ISSUE THREAD

**Issue by vanhuonghn011291** [nukeviet/nukeviet#685]
Bình thường dù cấu trúc không hợp lệ vẫn có thể nhấn Tiếp tục để cài đặt.. vậy mà ở bản này lại không cho phép cài đặt thì những module đó phải làm thế nào.. cài bằng thủ công ạ?

Môi trường thử Nghiệm
- Phiên bản NukeViet: 4.0.11
- Hệ điều hành: windows 7
- Trình duyệt web: Mozilla Firefox 27.0, Crome 41.0.2272.89 m
- Máy chủ web: XAMPP 1.8.3 [PHP: 5.5.9] for Window

![loi cai dat module](https://cloud.githubusercontent.com/assets/10495040/6718460/6a8ac500-cde6-11e4-8620-75e3bd19a7f9.png)

**Comment by hongoctrien** [comment]
Vào **Mở rộng / Quản lý ứng dụng**, đóng gói một module hệ thống bất kỳ về (hoặc download một module bất kỳ từ store), mở file nén ra sẽ thấy 1 file config.ini. Bạn mở file này và sửa lại bằng thông tin module của bạn, sau đó nén vào chung với module của bạn.

Từ bản 4.0.11 hệ thống yêu cầu khai báo thông tin ở file này đối với các module, blocks, theme, cron.
