### ISSUE TITLE
Lỗi loại bỏ url module trên trang

### ISSUE THREAD

**Issue by thangbv** [nukeviet/nukeviet#686]
Hiện tại phần loại bỏ url module trên trang chủ gặp 1 lỗi sau đây:
VD đang để module news là module loại bỏ url, chuyên mục trong module news có alias là abc-xyz.
Như vậy url trên trang là domain.com/abc-xyz/ Vậy nếu như cũng có 1 module mang tên là abc-xyz thì sẽ ra sao? Hiện tại nếu có thì sẽ ra trang trắng.

**Comment by vuthao** [comment]
Mình đã sửa lại theo hướng: Ưu tiên kiểm tra module trước, nếu không có mới kiểm tra đến chuyên mục của module.

Còn việc kiểm tra khi tạo chuyên mục, cái này do các module tự làm

**Comment by vuthao** [comment]
đã fix lôi này ở bản đóng 4.0.10
