### ISSUE TITLE
Nên chú ý: Undefined offset: 1 in file /admin/extensions/upload.php on line 589

### ISSUE THREAD

**Issue by vanhuonghn011291** [nukeviet/nukeviet#688]
E bị lỗi này khi cài dặt module shop trong mục ứng dụng khuyên dùng..

Môi trường thử Nghiệm
- Phiên bản NukeViet: 4.0.11
- Hệ điều hành: windows 7
- Trình duyệt web: Mozilla Firefox 27.0, Crome 41.0.2272.89 m
- Máy chủ web: XAMPP 1.8.3 [PHP: 5.5.9] for Window

![test - qu n ly site - m r ng 2](https://cloud.githubusercontent.com/assets/10495040/6724176/48cd7a40-ce25-11e4-81ec-32ae7cc9c9aa.png)

**Comment by hongoctrien** [comment]
Fixed https://github.com/hongoctrien/nukeviet/commit/a443bb3d22a4fc6bdcc1c9a9dce5e43c32639454
