### ISSUE TITLE
Không cài đặt được đối với các module, block có file nằm ngoài 3 thư mục modules, uploads, themes

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#689]
Không cài đặt được đối với các module, block có file nằm ngoài 3 thư mục modules, uploads, themes.
Hiện tại trình upload ứng dụng chỉ cho phép ứng dụng co file nằm trong 3 thư mục modules, uploads, themes. Có file nằm ngoài sẽ báo lỗi không cài tiếp được.
Ví dụ module shops có file **service_shops_nganluong.php** đặt tại thư mục gốc nên không cài tự động được, tương tư cho một số module khác.

**Comment by vuthao** [comment]
Với các trường hợp này, hệ thống đã thông báo rõ ràng: 
Lỗi: Ứng dụng này có cấu trúc không phù hợp và có thể gây nguy hại đến website. Để đảm bảo an toàn, hệ thống từ chối việc tiếp tục cài đặt ứng dụng này
