### ISSUE TITLE
Không cài đặt được Modules

### ISSUE THREAD

**Issue by tunglam2014** [nukeviet/nukeviet#690]
Mình đã cài bản 10.0.11 trên localhost, trong quá trình cài không xảy ra lỗi, nhưng không cài đặt được các Modules trong admin. Trong Menu " Quản lý modules" trong có mune cài đặt và đóng gói modul.

**Comment by vanhuonghn011291** [comment]
Phần cài đặt module nằm trong phần Mở rộng/quản lý ứng dụng nhé..
 Còn để cài đặt tự đọn bạn vào **Mở rộng / Quản lý ứng dụng**, đóng gói một module hệ thống bất kỳ về (hoặc download một module bất kỳ từ store), mở file nén ra sẽ thấy 1 file config.ini. Bạn mở file này và sửa lại bằng thông tin module của bạn, sau đó nén vào chung với module của bạn.
Hoặc bạn cũng có thể cài đặt thủ công..
Từ bản 4.0.11 hệ thống yêu cầu khai báo thông tin ở file này đối với các module, blocks, theme, cron.
Việc cài đặt module trong bản mới này yêu cầu phải khai báo phiên bản cho module, bạn đọc thêm ở đây nhé
https://github.com/nukeviet/nukeviet/issues/689

**Comment by tunglam2014** [comment]
Cảm ơn nhiều.
