### ISSUE TITLE
Báo lỗi Module Download khi xem chi tiết

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#691]
Cài đặt thành công, đăng bài, ra trang chủ xem chi tiết báo lỗi:
 Thông báo từ Hệ thống

Lỗi cảnh báo Lỗi cảnh báo: 
Missing argument 7 for nv_comment_module(), called in C:\xampp\htdocs\nukeviet411\modules\download\funcs\viewfile.php on line 270 and defined in file /modules/comment/comment.php on line 127

Nên chú ý Nên chú ý: Undefined variable: page in file /modules/comment/comment.php on line 187

**Comment by trinhthinhhp** [comment]
Đã fix, đợi update lại nha
