### ISSUE TITLE
Góp ý nhỏ về thói quen viết css không nên lạm dụng !important

### ISSUE THREAD

**Issue by thaotrinhj** [nukeviet/nukeviet#692]
Góp ý cho bác làm giao diện. Các thẻ HTML như h2,h3,...p,... khi css cho chúng không nên lạm dụng !important hay nói chính xác là không dùng important. Vì đây là nhưng thẻ HTML, chúng được dùng nhiều lần cho những style khác nhau. Và chúng ta có thể kiểm chứng bằng cách không tìm thấy có trang nào dùng !important cho các thẻ HTML.
<img src="http://i.imgur.com/5ZjPtRI.jpg"/>

**Comment by dangdinhtu2014** [comment]
Thêm nữa là viết css như này trong news.css là vi phạm qui tắc quá
#print a, a:active, a:focus, a:visited{}
đề nghị loại bỏ phần css dạng toàn site vào module kiểu như này rất ức chế

**Comment by trinhthinhhp** [comment]
@dangdinhtu2014  cái này quan trọng là lúc làm cái template mới, người cắt template họ tự chọn ko phụ thuộc vào template gốc

**Comment by dangdinhtu2014** [comment]
nói thế thị chịu hẳn rồi

**Comment by vanhuonghn011291** [comment]
đúng là e cũng thấy tức tức vs cái #print a, a:active, a:focus, a:visited{} kiểu này...

**Comment by dangdinhtu2014** [comment]
@trinhthinhhp nói đến vấn đề sai nguyên tắc mà còn nói thế được thì bó tay chứ còn làm sao nữa. Phụ thuộc khỉ gió gì ở đây :))

**Comment by vuthao** [comment]
@thaotrinhj @dangdinhtu2014 
các mã css này đã tồn tại từ bản 3.4 nên một số chưa sửa đổi hết.

Các bạn xem có thể chỉnh sửa và đóng góp lại không, một mình chúng tôi không thể làm hết ngay ngày một ngày hai được.
