### ISSUE TITLE
Lỗi ở block Login

### ISSUE THREAD

**Issue by mathagu** [nukeviet/nukeviet#693]
Môi trường thử Nghiệm
- Phiên bản NukeViet: 4.0.11
- Hệ điều hành: Win 8.1 64bit
- Trình duyệt web: Chrome
- Máy chủ web: USBWebserver
+ công cụ quản lý hosting: cpanel
+ Apache 2.4.7, MySQL 5.5.36, PHP 5.4.25

Lỗi: Username lặp lại 2 lần sau khi đăng nhập ở block Login!

**Comment by trinhthinhhp** [comment]
Mình check không thấy lỗi ở block login đó, đăng nhập bình thường

**Comment by hongoctrien** [comment]
> Lỗi: Username lặp lại 2 lần sau khi đăng nhập ở block Login!

@trinhthinhhp vấn đề này em có nói anh rồi ý. Mặc định sau khi cài first_name và last_name nó lấy username

**Comment by trinhthinhhp** [comment]
@hongoctrien  ok, cái này sẽ cập nhật sau

**Comment by trinhthinhhp** [comment]
Close topic, đợi cập nhật nhé

**Comment by hongoctrien** [comment]
[Fixed](https://github.com/nukeviet/nukeviet/commit/b93df7a1850f87b444fbf37426ca840d34820b59)
