### ISSUE TITLE
module comment - loi

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#695]
Module comment bị lỗi, sau khi gửi comment , nó không call back nội dung, cũng không reset, khi bấm gửi nhiều lần thì hệ thống ghi nhiểu kết quả tương ứng (-> reload thì mới thấy kết quả)
xem video
http://youtu.be/eyM2XsFK-Vo

Neu la khach thi go captcha he thong luon bao loi la ma nhap khong dung nhung reload lai trang thi van co comment duoc gui

host vps plesk 12, centos 6.6
php 5.4.8
phien ban close beta 11
trinh duyet chrome: 41.0.2272.89 m

Thêm nữa khi cấu hình là quản trị module mới được comment thì thành viên khác đăng nhập nó hiện ra trang 403. mà lẽ ra thông báo là bạn không có quyền bình luận bài viết này rồi redirect ra trang vừa xem. chứ đằng này lại trả về trang 403 thì mất hứng quá
![capture2](https://cloud.githubusercontent.com/assets/6806295/6756477/c43669d4-cf5c-11e4-929d-0ba6913f7669.PNG)

**Comment by trinhthinhhp** [comment]
hiện tại mình ko thấy bị lỗi này, bạn kiểm tra lại chmod trên vps và kiểm tra một số hàm có được mở ko nhé

**Comment by vuthao** [comment]
@phongaz  bạn kiểm tra lại dùm phiên bản hiện tại đã hết lỗi chưa nhé:
https://github.com/nukeviet/nukeviet/archive/develop.zip

**Comment by phongaz** [comment]
Đã test  lại, không thấy phát sinh lỗi,

Các bình luận trả lời rất tốt, nó nằm đúng ngay sau comment được trả lời
