### ISSUE TITLE
Đề xuất thêm lựa chọn không hiển thị trong module news

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#696]
Hiện tại phương án hiển thị của module news vẫn chưa có chế độ tắt hiển thị MODULE_CONTENT như module shops. Mình đề xuất thêm lựa chọn này vào phương án hiển thị nhằm tạo điều kiện cho các block phát huy tác dụng tuỳ biến giao diện của nó thay vì phụ thuộc vào các phương án mặc định của hệ thống

**Comment by vuthao** [comment]
Code đã được chủ topic gửi, và đã gọp vào kho code
