### ISSUE TITLE
Lỗi đăng nhập thành viên và Admin

### ISSUE THREAD

**Issue by thangvn** [nukeviet/nukeviet#699]
Khi đăng nhập với đường link tenwebsite.com/admin thì không có vấn đề.

Nhưng khi đăng nhập tại khung đăng nhập thì Admin chỉ được xem như 1 thành viên bình thường,không có chức năng gì cả,dù đã thử truy cập đường dẫn tenwebsite.com/admin nhưng vẫn xem như là chưa đăng nhập

Hình 1 : khi đăng nhập với  tenwebsite.com/admin, vẫn có thanh quản trị phía dưới website

![1](https://cloud.githubusercontent.com/assets/6823461/6750112/a46c245a-cf29-11e4-917e-3544bca8bb61.jpg)

Hình 2 : khi đăng nhập tại khung đăng nhập ngoài trang chủ,sau đó đăng nhập tenwebsite.com/admin thì vẫn xem như chưa đăng nhập

![2](https://cloud.githubusercontent.com/assets/6823461/6750120/b6249e3e-cf29-11e4-86d8-944eb4a023cd.jpg)

Test trên website http://nukeviet.hostinggiare.net
username : anhcoo
pass : nukeviet40

Phiên bản NukeViet	 4.0.11
Phiên bản PHP	 5.3.29
Giao thức giữa máy chủ và PHP	Apache, cgi-fcgi
Hệ điều hành máy chủ	 LINUX
Phiên bản Database	mysql 5.5.40-36.1-log

**Comment by dangdinhtu2014** [comment]
vấn đề này là tất nhiên trước giờ vẫn thế mà bạn. Đăng nhập ngoài site chỉ là tư các thành viên thôi
