### ISSUE TITLE
[Lỗi] sửa thông tin user không được

### ISSUE THREAD

**Issue by thangvn** [nukeviet/nukeviet#700]
Thử tạo 1 user trong quản trị , sau đó chọn SỬA thì hiện ra trang TRẮNG

Hình 1 : thông tin về các user
![3](https://cloud.githubusercontent.com/assets/6823461/6750208/9b369f40-cf2a-11e4-9c4e-79e3a42f6932.jpg)

Hình 2 : khi chọn SỬA 1 user bất kì,trang TRẮNG hiện ra

![4](https://cloud.githubusercontent.com/assets/6823461/6750218/b550969c-cf2a-11e4-8d04-3d53c506a4c5.jpg)

Test trên website http://nukeviet.hostinggiare.net
username : anhcoo
pass : nukeviet40

Phiên bản NukeViet	 4.0.11
Phiên bản PHP	 5.3.29
Giao thức giữa máy chủ và PHP	Apache, cgi-fcgi
Hệ điều hành máy chủ	 LINUX
Phiên bản Database	mysql 5.5.40-36.1-log

**Comment by trinhthinhhp** [comment]
Tối em xem trên hosting xem sao, trên localhost của em chạy rầm rầm không hề hấn gì hết

**Comment by trinhthinhhp** [comment]
nguyên nhân có thể do anh nâng cấp chưa hết file, em thấy anh nâng từ 3.4 lên bản  11 chắc chắn thiếu một số file và function, anh cần cập nhật lại code cho module user nhé, vì nút sửa và xóa thành viên đã test trên bản 11 không có lỗi gì hết

**Comment by thangvn** [comment]
ok bạn
