### ISSUE TITLE
[Lỗi] Không comment bài viết được và lỗi cho phép thảo luận

### ISSUE THREAD

**Issue by thangvn** [nukeviet/nukeviet#701]
- Khi tạo 1 bài viết,phần cho phép thảo luận , khi chọn TẤT CẢ -> đúng ra phải chọn hết ( khách,thành viên,quản trị tối cao.....) nhưng không chọn hết.

hình 1 : khi chọn TẤT CẢ

![5](https://cloud.githubusercontent.com/assets/6823461/6750298/5ba621ba-cf2b-11e4-9c6e-39d03262a216.jpg)

- Khi đăng nhập với tư cách là thành viên [ ví dụ : user(thangvn)-pass(thang_123456)] , thì báo lỗi : CHƯA NHẬP TÊN , nhưng khung nhập tên đã bị ẨN ( VISIBLE) nên không nhập tên được,đúng ra khi đăng nhập với tư cách là THÀNH VIÊN thì phải có tên sẵn trong khung rồi

Hình 2 : comment với tư cách THÀNH VIÊN ( đã thiết lập cho phép thảo luận như hình 1 )

![6](https://cloud.githubusercontent.com/assets/6823461/6750339/d14f614c-cf2b-11e4-936e-1b6e697844ed.jpg)

- Khi đăng nhập với tư cách là QUẢN TRỊ website theo link : tenmien.com/admin hoặc khung đăng nhập ngoài TRANG CHỦ ,thì comment bị báo lỗi sau : 

![7](https://cloud.githubusercontent.com/assets/6823461/6750375/2e449494-cf2c-11e4-8ba9-d48c7badddb6.jpg)

Test trên website http://nukeviet.hostinggiare.net
username : anhcoo
pass : nukeviet40

Phiên bản NukeViet	 4.0.11
Phiên bản PHP	 5.3.29
Giao thức giữa máy chủ và PHP	Apache, cgi-fcgi
Hệ điều hành máy chủ	 LINUX
Phiên bản Database	mysql 5.5.40-36.1-log

**Comment by trinhthinhhp** [comment]
- Hình 1: lỗi này là do chưa điền tên-> muốn điền tên thì vô phần thành viên trên thanh menu để vào đó edit, vì ở ô này nếu mà cho phép tự thay đỏi thì liên quan tới csdl vì có firstname và lastname do vậy phải edit thông tin lại đầy đủ mới dc
- Hình 2: tích cho phép thảo luận như hình 1 là sai nguyên tắc, khi tích tất cả mà tích thêm các thành phần con là vô tác dụng, nó nhận thông tin ở tất cả và mọi người đều được comment
Tiếp đó là cần cấu hình mở module comment để có thể sử dụng bình luận như bình thường được bằng cách chọn module comment -> cấu hình -> chọn một cái rồi sửa, cấp thêm quyền

**Comment by thangvn** [comment]
bạn nói đúng
