### ISSUE TITLE
Module news không tìm được khóa có ký tự đặc biệt

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#703]
Ví dụ tiêu đề bài viết là một dòng tiếng Pháp.
**Visite conjointe des Recteurs de l'UCL et de FUNDP à l'IFI**
Có đoạn **l'UCL et de FUNDP à l'IFI** sẽ không tìm ra.

**Comment by vuthao** [comment]
@hongoctrien em đăng bài viết, hay là chuyển đổi dữ liệu

anh thử tạo bài viết mới tìm nó ra bình thường.

**Comment by hongoctrien** [comment]
Cái này chuyển đổi dữ liệu anh.
Em vừa test như anh nói, đúng là thêm mới vẫn tìm dc. ^^.
