### ISSUE TITLE
Xem lại tooltip khi xem bài viết

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#704]
Khi xem bài viết, phần danh sách **Những tin cũ hơn**, khi bài viết không có hình minh họa thì thay bằng ảnh đại diện mặc định, hoặc không hiển thị ảnh, hiện tại nó hiện một ô màu trắng.

**Comment by vuthao** [comment]
@hongoctrien Kiểm tra lại nhé, hiện tại mình không thấy như thông báo, nếu được cho xem demo nhé

**Comment by hongoctrien** [comment]
Ok, hết rồi @vuthao
