### ISSUE TITLE
Lỗi chuyển trang khi xóa bài viết

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#705]
Khi xóa bài viết tại trang xem bài viết, xóa xong chuyển về link hiện tại báo lỗi **404 - Link không tồn tại** (do lúc này bài đã bị xóa)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/a3b283074e28ff7f86d00343d5d6a7300048cfef
