### ISSUE TITLE
Module news: Vấn đề chuyển trang sau khi xóa, sửa,... bài viết

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#707]
Giả sử danh sách bài viết có 10 trang, khi đang đứng ở trang thứ 3, xóa một bài thì chuyển về trang 1, chứ không chuyển về trang đang đứng.

**Comment by vuthao** [comment]
Tương tự trong admin, khi tìm kiếm  1 từ khóa, xóa xong nó lại quay về trang chủ của module.

**Comment by hongoctrien** [comment]
Tương tự cho module shops

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/b198f27ba7e9a6f05442bacaa756370814f55622
@hongoctrien Sau khi xác định xóa thành công thì cho javascript load lại chính nó

**Comment by hongoctrien** [comment]
Tương tự cho bât kéo thả block
