### ISSUE TITLE
Lỗi khi quản lý block dạng kéo thả

### ISSUE THREAD

**Issue by mathagu** [nukeviet/nukeviet#709]
Mỗi khi thêm, sửa hay xóa một block từ tính năng Kéo thả block từ trang chính, khi chọn Chấp nhận thì bị chuyển sang trang trắng about:blank, sau đó phải bấm Back, và reload lại trang thì hoành động mới có hiệu lực!

**Comment by trinhthinhhp** [comment]
Bạn dụng block gì vậy bạn? có phải block của hệ thống hay là block ở bản khác bạn sử dụng?

**Comment by mathagu** [comment]
Các block menu hoặc block ở Left side của trang (đang để layout left-body). Tất cả là ở bản gốc của NukeViet 4.0.11, không thêm hay bớt gì trong ấy cả!

**Comment by vuthao** [comment]
@mathagu 

Khi báo lỗi bạn vui lòng cung cấp các thông tin sau để chúng tôi có thể xây dựng môi trường thử nghiệm giống của bạn để kiểm tra

Ví dụ: Môi trường thử Nghiệm
- Phiên bản NukeViet: 4.0.10
- Hệ điều hành: Ubuntu 13.10 62-bit
- Trình duyệt web: Mozilla Firefox 27.0
- Máy chủ web: XAMPP for Linux 1.8.1 Nếu trên website cần có thêm thông tin
+ công cụ quản lý hosting: cpanel
+ Apache 2.4.7, MySQL 5.5.36, PHP 5.4.25
-Block tên là ghì, ở module nào.

**Comment by mathagu** [comment]
Môi trường thử Nghiệm

Phiên bản NukeViet: 4.0.11
Hệ điều hành: Win 8.1 64bit
Trình duyệt web: Chrome 41.0.2272.101 m
Máy chủ web: USBWebserver 8.6
công cụ quản lý hosting: cpanel
Apache 2.4.7, MySQL 5.5.36, PHP 5.4.25

Block: bất kỳ block nào, ví dụ như global block_category của module Tin tức.

Chỉ bấm vào mục "Sửa", trong cửa sổ mới hiện ra chọn "Chấp nhận" là bị lỗi chuyển sang trang about:blank.

**Comment by vuthao** [comment]
@mathagu bạn test lại bản https://github.com/nukeviet/nukeviet/archive/develop.zip xem có lỗi không nhé. Nếu vẫn còn lỗi thông báo lại dùm.

**Comment by mathagu** [comment]
Không hiểu sao ở bản mới này vẫn bị như vậy? Mới cài đặt xong, chọn đăng nhập Admin, về giao diện chính để chọn kéo thả block, chọn xóa block quảng cáo ở Left side, thì vẫn bị chuyển đến about:blank! Có phải do hệ thống của máy bên tôi không nhỉ?

Ngoài ra, cái Site Name không nằm ngay sau cái logo mà nằm đè xuống Bootstrap Menu nữa!

**Comment by vuthao** [comment]
@mathagu Nếu có online gọi mình trên face Vu Thao để kiểm tra trên máy bạn nhé, máy mình nó không bị như thế.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/e118c1e85f7364e891500490009107e2f160564b
