### ISSUE TITLE
Rewrite cho module ở trang chủ chưa ổn

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/nukeviet#710]
Khi đang ở trang 2 mà trở về trang 1 nó có link dạng: http://nvdev.hau/news/ (Không phải là: http://nvdev.hau/page-1/ hoặc trang chủ: http://nvdev.hau)

![untitled-1](https://cloud.githubusercontent.com/assets/1614842/6769223/ac9ed022-d0c4-11e4-813d-1bbecb07cd38.jpg)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/5c33f2fd374edffea110a2dd8873c36c55972d56
