### ISSUE TITLE
Module extensions: Chưa có chức năng đóng gói block, module, lỗi khi cài blocks

### ISSUE THREAD

**Issue by xuanluchp** [nukeviet/nukeviet#711]
Hiện tại chức năng cài đặt ứng dụng đã được chuyển sang module extensions, tuy vậy khi cài đặt các ứng dụng được đóng gói từ bên ngoài đang gặp khó khăn. Chức năng đóng gói module như phiên bản 4.0.10 không còn tồn tại.
1, Lỗi khi cài ứng dụng được đóng gói từ bên ngoài: Một block, hay một module được đóng gói từ Nukeviet 4.0.10, nếu sử dụng trình cài đặt sẽ được báo lỗi là: File tải lên không hợp lệ vui lòng kiểm tra lại cách thức đóng gói ứng dụng => Cấu trúc file đóng gói như nào mới là hợp lệ? (xem hình)
![loi nukeviet](https://cloud.githubusercontent.com/assets/10148636/6769549/203be28c-d0d3-11e4-99b9-4b802b49382b.jpg)

Việc này đồng nghĩa với Nukeviet chỉ cho phép cài đặt các ứng dụng chuẩn được chi sẻ trên store của Nukeviet, còn quản trị muốn cài đặt các ứng dụng tự phát triển sẽ phải cài đặt theo cách thủ công (Giải nén và up lên host qua FTP). Không còn chức năng này thì cũng khác tiếc, có phải đấy là ý đồ và la một thay đổi của Nukeviet 4.x

2, Chức năng đóng gói module cũng không còn tồn tại?
3, Phần cài đặt themes cũng bị bỏ chỉ còn chức năng đóng gói? => phần cài đặt ứng dụng đã bị như trên thì việc cài đặt themes từ bên ngoài cũng sẽ gặp khó khăn?

**Comment by phongaz** [comment]
@xuanluchp 
Đóng gói module / themes: bạn vào mở rộng/quản lý ứng dụng, sau đó nhìn sang bên cột cuối cùng có biểu tượng đám mây, click vào module hoặc giao diện muốn đóng gói để download về. (Nó đã được đóng gói sẳn rồi)

Mình xin góp ý thêm: ở menu cài đặt giao diện nhưng click vào thì chỉ còn đóng gói theme theo module
Nếu ở phần Quản lý ứng dụng có chức năng là cài các gói ứng dụng từ local computer rồi thì ở phần giao diện sao lại có memu cài đặt giao diện, nên chăng là sửa lại tên là đóng gói giao diện theo module? 
Thêm nữa là việc đóng gói theme theo module này chưa được tiện cho lắm,mỗi lần chỉ chọn được 1 module thôi, nếu người dùng có nhu cầu đóng gói nhiều hơn 1 thì sao? phải bổ sung chức năng đóng gói nhiều module theo giao diện

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/9a3780105671ae00d03f61dbd8f13e91497df29d
