### ISSUE TITLE
Báo lỗi chồng layout

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#713]
Khi bật chức năng kéo thả block lên thì các thẻ layout chồng lên và lồng vào nhau.
Lỗi Layout.body-right.tpl khi bật kéo thả block lên thẻ {HEADER} chồng lên thẻ {TOP}. Còn {BOTTOM} lồng vào phần của {MODULE_CONTENT}
![layout](https://cloud.githubusercontent.com/assets/11238423/6772581/2ccb4752-d134-11e4-984e-0418714a058c.png)

**Comment by trinhthinhhp** [comment]
@hoanglongvnpt  bạn tắt hết các block thêm vào và để lại block mặc định của nukeviet
- Còn {BOTTOM} lồng vào phần của {MODULE_CONTENT}: chỗ này do bạn đang can thiệp vào việc css border xung quanh nằm ở thẻ ngoài ko phải thẻ bên trong lên mới có hiện tượng BOTTOM ở bên trong như vậy
- thẻ {HEADER} chồng lên thẻ {TOP}: cái này do bạn dang sử dụng block ngoài ko phải là block của hệ thống và css có vấn đề mới gây ra hiện tượng như vậy
