### ISSUE TITLE
Báo lỗi Module Download khi xem chi tiết

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#714]
Module Download khi click vào xem chi tiết thì xuất hiện báo lỗi:
 Thông báo từ Hệ thống

Lỗi cảnh báo Lỗi cảnh báo: Missing argument 7 for nv_comment_module(), called in C:\xampp\htdocs\nukeviet411\modules\download\funcs\viewfile.php on line 270 and defined in file /modules/comment/comment.php on line 127

Nên chú ý Nên chú ý: Undefined variable: page in file /modules/comment/comment.php on line 187
![7899](https://cloud.githubusercontent.com/assets/11238423/6772671/f12a2c52-d135-11e4-892d-9ba4f9448386.PNG)

**Comment by trinhthinhhp** [comment]
Đã xử lý xong, đợi update lại nhé
