### ISSUE TITLE
Lỗi comment

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#715]
Khi comment và đã hiển thị nội dung comment nhưng trong khung saonj thảo ô text vẫn còn lưu nội dung comment. Nút Reset không có tác dụng
![comment](https://cloud.githubusercontent.com/assets/11238423/6772800/6f1ba468-d138-11e4-9cf5-bd353a0e4769.png)

**Comment by trinhthinhhp** [comment]
Hiện tại mình check không có lưu lại thông tin gì hết nhé, bạn quay clip đưa lên youtube rồi send qua đây để mình xem thao tác bạn làm nhé

**Comment by vuthao** [comment]
Hiện tại chúng tôi đã rỡ trình soạn thảo tại comment, nên lỗi này sẽ tự động hết
