### ISSUE TITLE
Lỗi phân trang search trong module news

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/nukeviet#716]
Test trên bản 4.0.0.10
Chi tiết lỗi xem ảnh
![untitled-1](https://cloud.githubusercontent.com/assets/1614842/6773006/5938903a-d13c-11e4-9c7d-e7c2935572af.jpg)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/81dee88c050232591fc00f8449393fb9a6e7db2e
