### ISSUE TITLE
Lỗi bình luận cho module Download

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#717]
-Cấu hình tất cả được bình luận; ra trang chủ Download tiến hành bình luận thì báo lỗi:
Lỗi trong quá trình xử lý dữ liệu hoặc dữ liệu không đầy đủ. 
-Nút RESET cũng vô tác dụng.

**Comment by trinhthinhhp** [comment]
Hiện tại mình test ko thấy lỗi gì cả, gửi bình luận bình thường, có thể thông tin tên và họ chưa có mới sảy ra hiện tượng đó, bạn càn edit thông tin tài khoản điền vô thì mới gửi được, riêng với nút reset thì do bạn cấp quyền cho tài khoản là editor thì nút đó ko hoạt động mà chỉ có thành viên với khung soạn thảo thông thường và khách là dùng được nút đó

**Comment by vuthao** [comment]
Mình kiểm tra hiện tại lỗi này đã hết.
