### ISSUE TITLE
Lỗi khai báo thông tin thành viên trong admin và hiển thị ở trang chủ

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#718]
-Trong admin phần khai báo: Họ và tên đầy đủ
nhưng ra trang chủ: 1. Ở phần block đăng nhập thì hiển thị đủ như đã khai báo.
Ở phần comment bài viết lại thiếu phần tên: chỉ có Họ và tên lót.
Login
![login](https://cloud.githubusercontent.com/assets/11238423/6774664/b0dd8eb6-d156-11e4-8c4f-f5d74c5d5303.PNG)

Comment
![comment](https://cloud.githubusercontent.com/assets/11238423/6774665/b76911a6-d156-11e4-8180-0d9a93341a77.PNG)

**Comment by trinhthinhhp** [comment]
vấn đề này đã được fix, đợi cập nhật lại nhé

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/69b7e1611e6975eed92b01cc9357839ea4797fcd
