### ISSUE TITLE
Cần thêm tính năng update lại các chuyên mục.. hoặc bài viết trong từng module thuộc module menu

### ISSUE THREAD

**Issue by volong1012** [nukeviet/nukeviet#724]
Hiện nay module menu của mình dùng bất tiện ở 1 điểm là khi thay đổi 1 chuyên mục hoặc toàn bộ chuyên mục, bài viết nào đó của module bất kỳ thì lúc cần cập nhập lại phần chuyên mục thì chỉ có cách add thủ công và xóa các chuyên mục cũ đi.... như thế rất mất thời gian vì chỉ cần module trên 10 chuyên mục thì việc này còn khó chịu hơn nữa chứ chưa nói là update lại tầm 2, 3 module cùng lúc

**Comment by thehung** [comment]
Chuẩn.

Có thể update tự động hoặc thủ công.

Như vậy phải có cơ chế ghi nhận menu nào là tự động.

**Comment by vuthao** [comment]
@volong1012 @thehung Chắc là chưa biết cách dùng cái này nhé.

Vào một khối, sửa lại, nó sẽ nạp lại hết cả menu đó nhé. Còn muốn nạp lại 1 phần thì mình vẫn chưa nghĩ ra các quản lý cái khối đó thế nào khi menu nó không nhập hết từ chuyên mục.

**Comment by thehung** [comment]
Nên bổ sung thêm nút "Cập nhật lại khối menu" chứ không nên sử dụng chức năng "Sửa khối" để nạp lại vì như vậy sẽ gây khó hiểu cho người sử dụng.

**Comment by vuthao** [comment]
Việc này nhiều khả năng là không làm được nhé, do lưu trữ text nên rất khó làm cho tất cả các module
