### ISSUE TITLE
Tính năng đếm ký tự khi thêm tin tức trong modules news

### ISSUE THREAD

**Issue by PhamQuocTien132** [nukeviet/nukeviet#725]
Hiện tại Google chỉ hiện thị 60 ký tự trên tiêu đề và 150 ký tự cho phần mô tả.

**Comment by anhyeuviolet** [comment]
Hình như có hết rồi mà @>@

**Comment by PhamQuocTien132** [comment]
Hiện tại trong hệ thống nó cảnh báo title là 65 ký tự , mô tả là 160 ký tự

**Comment by thehung** [comment]
Chỉ là text thôi mà, em sửa luôn đi @PhamQuocTien132, tạo issues làm gì.
