### ISSUE TITLE
Sử dụng filter selectbox

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#726]
![menu_147](https://cloud.githubusercontent.com/assets/6407361/6823050/25542a18-d317-11e4-9883-e46fda168469.png)
Những selectbox khá nhiều item như thế này cần thay filter selectbox.
Đề xuất sử dụng https://select2.github.io/

**Comment by dangdinhtu2014** [comment]
ý kiến hay đấy triển khai thôi ^^

**Comment by vuthao** [comment]
Ai đăng lý làm cái này nhỉ.

**Comment by hongoctrien** [comment]
Cái này em có làm qua rồi nên đưa vào cũng nhanh. Mai em xử luôn. hì.

**Comment by thehung** [comment]
Xong chưa @hongoctrien

**Comment by hongoctrien** [comment]
@thehung cả ngày hôm nay em không có thời gian luôn. 
Giờ em sửa cái này luôn đây.

**Comment by hongoctrien** [comment]
Xong https://github.com/nukeviet/nukeviet/commit/5e974679d94275fd5260b344facc1f4310f2ecec
