### ISSUE TITLE
Cần sử dụng đúng trạng thái con trỏ chuột khi di lên trên nút đóng gói ứng dụng

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#727]
![anh chup 157](https://cloud.githubusercontent.com/assets/1892900/6880072/90286e8c-d54f-11e4-8475-a7814ec3f986.jpg)
extensions&op=manage
Phần thao tác đóng gói & xóa đề nghị khi hover qua cursor: pointer;
Chỉnh hàng cho thẳng nhìn bây giờ lệch lạc nhìn chán quá

**Comment by vuthao** [comment]
@dangdinhtu2014 bắt tay vào làm đi em, chứ hiện tại Dũng đang làm khóa luộn tốt nghiệm sẽ lâu đó.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/ab0e205ce7c30c2a86394fefcc0bd318df496306
