### ISSUE TITLE
[Đề xuất] Tách bộ gõ tiếng việt thành module riêng

### ISSUE THREAD

**Issue by thaotrinhj** [nukeviet/nukeviet#728]
Vì nukeviet hướng tới một website đa ngôn ngữ mà hiện nay phần bộ gõ tiếng việt được mặc định trong hệ thống. Mình đề xuất tách cái này riêng thành module riêng, để ai thích cài thì cài thêm. Bởi ngoài tiếng Việt còn nhiều bộ gõ khác nữa. 
<img src="http://i.imgur.com/Ibe2XHm.png"/>

**Comment by vuthao** [comment]
Tiếng việt là tiếng đặc biệt trong site, nên nó được ưu tiên xử lý. 
Nó chỉ hiện thị trên ngôn ngữ tiếng việt
