### ISSUE TITLE
Lỗi khi share bài viết lê fb không hiển thị được hình ảnh

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#729]
Thông thường khi click nút share lên fb thì hiển thị tiêu đề bài viết và đính kèm hình ảnh, nhưng nv4.0.11 không làm được việc đó, mong đội code pix sớm:
Lỗi thẻ: <meta property="og:image" content="http://xembaomoi.thanhdathotel.com.vn/uploads/news//uploads/news/nukeviet-nhantaidatviet2011.jpg" />  xuất hiện 2 lần: /uploads/news//uploads/news/
![7889](https://cloud.githubusercontent.com/assets/11238423/6865747/a7c85540-d4a3-11e4-9b4f-fc9aa7e35eb7.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/81cd4aab55a0a30fb27a9274030f4c23861af50c
