### ISSUE TITLE
[Góp ý] menu ứng dụng tại phần mở rộng

### ISSUE THREAD

**Issue by thaotrinhj** [nukeviet/nukeviet#730]
<img src="http://i.imgur.com/gNa3x62.png"/>
Nhận xét về một số mục trong phần ứng dụng:
1- Bỏ phần "Ứng dụng khuyên dùng":
Mình không rõ ứng dụng khuyên dùng dựa theo tiêu chí nào.
Mình nghĩ không cần thiết cái này, không thấy mã nguồn nào làm vậy.
Miễn sao người dùng nhìn thấy nhiều thông tin liên quan đến ứng dụng đó và dùng hay không là sở thích của người dùng
Ví dụ đối với Drupal thì họ làm thế này
<img src="http://i.imgur.com/XYd1HMs.png"/>
Với joomla & các mã nguồn khác thì họ cũng làm tương tự và chia các chủ đề, lĩnh vực rất chi tiết.
2- Bỏ Ứng dụng đã tải
3- Bỏ Ứng dụng đánh dấu
Hai chức năng này có trong trang store chứ thêm vào phần quản trị mỗi web để làm gì.
Mà phần này kết nối với tài khoản người dùng tại nukeviet.vn/store/. Một người có thể có những web khác nhau, không lẽ vào web nào cũng hiện ra danh sách các "ứng dụng đã tải", "ứng dụng đánh dấu". Mọi giao dịch đều thực hiện trên store nên 2 mục này không cần thiết.

Do vậy mình đề xuất phần mở rộng chỉ để các mục:
<img src="http://i.imgur.com/VKvbPO0.png"/>
Mở rộng (bấm vào nút này sẽ chuyển đến trang tìm kiếm ứng dụng tương tự như tìm kiếm tại nukeviet.vn/store)
- Ứng dụng mới nhât  (nên có)
- Ứng dụng phổ biến (có cũng được)
- Ứng dụng tương thích (nên có)
- Quản lý ứng dụng

**Comment by thehung** [comment]
Cái này làm theo mô hình của Google play store. Nếu bạn mua ứng dụng và có
nhiều website, hệ thống cho bạn tải về và cài lên nhiều site.

**Comment by thaotrinhj** [comment]
À mục đích chính ở đây là ta kiểm soát tốt các ứng dụng có phí, người dùng sẽ trả $ cho mỗi ứng dụng/website thay vì hiện nay tải về 1 lần rồi lại cài lên nhiều website khác.
Mà hình như cái http://nukeviet.vn/vi/store/merchant/ chưa làm xong.
Gọi là "Danh sách Merchant Site" nhưng chẳng thấy nút thêm site ở đâu, chỉ có mỗi 1 site với 2 nút sửa xóa.
Mặt khác đăng ký Merchant rồi nhưng đăng nhập Merchant /admin/index.php?language=en&nv=extensions&op=login
chưa được
