### ISSUE TITLE
Lỗi khi share bài viết lên fb không hiển thị được hình ảnh

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#732]
Không hiển thị hình ảnh khi share bài viết lên fb
![101](https://cloud.githubusercontent.com/assets/11238423/6879437/a9ecd56a-d527-11e4-8a9c-549af9303609.PNG)

**Comment by vuthao** [comment]
duplicate: https://github.com/nukeviet/nukeviet/issues/729
