### ISSUE TITLE
Đề xuất thêm vài plugin vào CKEditor trong Nukeviet

### ISSUE THREAD

**Issue by PhucSD** [nukeviet/nukeviet#733]
Mình đề xuất thêm vài tính năng cần thiết và hữu dụng vào CKEditor trong Nukeviet để thuận tiện hơn trong việc biên tập bài viết...
- Plugin ẩn hiện văn bản, giúp ẩn những đoạn text mặc định không muốn hiển thị trên trang và khi muốn hiển thị thì click vào button. http://ckeditor.com/addon/spoiler
- Plugin Resize Table bằng chuột: http://ckeditor.com/addon/tableresize
- Plugin Text Transform, convert những chữ cái từ in hoa sang chữ thường, từ chữ thường sang in hoa: http://ckeditor.com/addon/texttransform
- Plugin sử dụng font của Google, plugin này cho phép dùng những font chữ của Google Fonts, những font chữ độc đáo và đẹp: http://ckeditor.com/addon/ckeditor-gwf-plugin.

**Comment by vuthao** [comment]
Nếu quản lý plugin CKEditor cho cả site thì có thể download thêm  plugin  sau đó cấu hình lại file /editors/ckeditor/config.js
đoạn 	config.extraPlugins = 'video,eqneditor,switchbar,tbvdownload';
Còn nếu cần cấu hình plugin  cho từng người thì mới cần NukeViet xử lý, các bạn cho ý kiến nhé.

**Comment by PhucSD** [comment]
VÌ ở đây là mình muốn thêm các tính này vào bản install của nukeviet, nhưng nếu thêm quá nhiều plugin thì editor sẽ nặng và load chậm, có thể thêm Tùy chọn là bật tắt các tính năng cho khung soạn thảo CKEditor để tùy biến với nhu cầu sử dụng của mọi người, ngoài ra nên thêm hướng dẫn trong Admin Nukeviet các add plugin vào CKEditor.

**Comment by PhucSD** [comment]
Có ai quan tâm đến đề xuất nào không nhỉ. Bác @vuthao :D. Có thể làm hướng dẫn trong Admin để hướng dẫn add plugin vào trong CKEditor của Nukeviet không?

**Comment by thehung** [comment]
Cái này bạn add như add plugin bình thường của CKeditor nhé!

**Comment by hongoctrien** [comment]
@PhucSD thấy cái nào cũng hay. Mình viết hướng dẫn tự cài sau nhé.
