### ISSUE TITLE
reponsive trong admin hiện tại rất kém

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#734]
Có nên fix luôn ở phiên bản này hay đợi phiên bản chính thức mới fix nhỉ mọi người. Vì nếu mà giờ mà động vào là khá nhiều việc phải làm

**Comment by vuthao** [comment]
@dangdinhtu2014, Em đăng lý làm luôn cái này đi nhé.

**Comment by thaotrinhj** [comment]
Mình thấy phong cách như demo.opencart.com/admin/ (demo/demo) cũng khá hay.
Dùng reponsive thì nên bỏ menu kiểu hover vì thiết bị cầm tay ko có hover. menu trái click ra vài lớp menu mà ko phải chuyển trang lần lượt.

**Comment by hongoctrien** [comment]
Hiện ACP đa phần sử dụng table nên việc tùy chỉnh co reponsive khó, bootstrap nó hỗ trợ responsive cho table cũng hạn chế. Nếu mình chuyển sang control như open-cart thì việc responsive đơn giản hơn.

**Comment by vuthao** [comment]
@hongoctrien @thaotrinhj  @dangdinhtu2014 Xem giao diện admin của bạn hiện tại đã được cải thiện phần nào chưa nhé: https://github.com/nukeviet/nukeviet/archive/develop.zip

Nếu cần như sửa như thế nào thì đề xuất cụ thể sửa như thế nào đề tôi viết tool thay thế nếu được.
