### ISSUE TITLE
Thông tin kiểm tra phiên bản không chính xác

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#735]
Thông tin về chế độ lưu hành (ứng dụng độc lập hay ứng dụng hệ thống) và cảnh báo về việc kiểm tra ứng dụng (đã được đưa lên NukeViet Store hay chưa) chưa chính xác!

![anh chup 156](https://cloud.githubusercontent.com/assets/1892900/6880006/9378aac8-d54c-11e4-87a2-4fcc37136072.jpg)

* Phiên bản thử nghiệm: https://github.com/nukeviet/nukeviet/commit/37589
* Môi trường thử nghiệm: Localhost
* Phần mềm máy chủ: Vertrigo 2.3
* Các phiên bản phần mềm hỗ trợ:
   * Apache 2.2.26
   * PHP 5.3.27
   * Mysql 5.5.34
   * Smarty Smarty-3.1.15
   * SQLite 3.8.1
   * PhpMyAdmin 4.0.9
   * SQLiteManager 1.2.4
   * Xdebug 2.2.3

**Comment by hoaquynhtim99** [comment]
Cái này phụ thuộc vào dữ liệu trên kho Store, khi mình có phiên bản sử dụng chính thức sẽ tiến hành cập nhật lại phần này.
