### ISSUE TITLE
Lỗi trình bày phần quản lý ứng dụng

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#736]
**Thao tác sẽ dẫn đến lỗi:**

1. Truy cập _Admin Control Panel/ Mở rộng/ Quản lý ứng dụng_
Link: http://localhost/nukeviet4/admin/index.php?language=vi&nv=extensions&op=manage

2. Từ menu thả "Hãy lựa chọn" (ở bên phải cửa sổ _quản lý ứng dụng_), chọn "Khác" (hoặc bất kỳ menu nào), sau đó chọn lại menu "Quản lý ứng dụng" thì không được (vẫn là danh sách ứng dụng thuộc menu đã chọn trước đó).

* Phiên bản thử nghiệm: https://github.com/nukeviet/nukeviet/commit/37589
* Môi trường thử nghiệm: Localhost
* Phần mềm máy chủ: Vertrigo 2.3
* Các phiên bản phần mềm hỗ trợ:
   * Apache 2.2.26
   * PHP 5.3.27
   * Mysql 5.5.34
   * Smarty Smarty-3.1.15
   * SQLite 3.8.1
   * PhpMyAdmin 4.0.9
   * SQLiteManager 1.2.4
   * Xdebug 2.2.3

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/3787e982added923d23e498379d3c56b9450358c
