### ISSUE TITLE
Lỗi chính tả trong Thông báo không thể đăng nhập Merchant Site

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#737]
Lỗi chính tả: "Thông tin đăng nhập không chính xác, có thể bạn đã nhập sai tài khoảng đăng nhập, mật khẩu hoặc gửi yêu cầu từ một website chưa đượcc ấp phép"

**Comment by vuthao** [comment]
@hoaquynhtim99 em sửa lại cái này trên http://api.nukeviet.vn lỗi chính tả này nhé, nó không nằm trong code nukeviet 4

**Comment by thaotrinhj** [comment]
Dòng báo lỗi bằng tiếng Vireeth đã có nhưng tiếng anh thì chưa
<img src="http://i.imgur.com/vqdhlqH.png"/>
