### ISSUE TITLE
Yêu cầu mod lấy tag cho news

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#738]
Như phiên bản 3.4.02 phần lấy tag cho bài viết là có thể copy bài viết vào ô tạo từ khóa thì nó tự động load các từ khóa cho bài viết. Nhưng ở phiên bản này thiếu chức năng đó. Mỗi lần tạo từ khóa cho bài viết thật mất thời gian. Mong đội coder lưu ỹ giùm. Thank!

**Comment by thehung** [comment]
Vẫn thế thôi nhưng cái này đưa vào cấu hình để bật tắt. Do mặc định nó ở trong chế độ tắt nên thế @hoanglongvnpt

**Comment by hoanglongvnpt** [comment]
ok rùi anh
![78](https://cloud.githubusercontent.com/assets/11238423/6881385/d52e2dba-d58f-11e4-801b-c82faa40b9e6.png)
