### ISSUE TITLE
Lỗi block tophit của module news

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#739]
Hiện tại block này không hiện kết quả trên trang dù đã đặt lại time của bài viết và cấu hình thông số đúng

**Comment by vuthao** [comment]
Đâu không phải là lỗi nhé, lúc trước hệ thống không cho đăng thời gian lùi bài viết.
Hiện tại đã dửa lại quản trị site có thể điều chỉnh, điều hành moduele không được phép đăng bài lừi thời gian

**Comment by trinhthinhhp** [comment]
em đã test nhưng bài mới và cũ đều ko hiện dc theo lượt view và kết quả ngoài site

**Comment by hongoctrien** [comment]
@trinhthinhhp em có test với dữ liệu mặc định của nukeviet 4, không có lỗi gì.

**Comment by trinhthinhhp** [comment]
@hongoctrien  teamview xem cho anh nó do cái gì nha
