### ISSUE TITLE
Lỗi trắng trang khi admin trả lời liên hệ trên trang liên hệ.

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#740]
Khi admin trả lời liên hệ trên trang liên hệ (qua Admin Control Panel) thì bị trang trắng. (Localhost không hỗ trợ gửi mail)

* Phiên bản thử nghiệm: https://github.com/nukeviet/nukeviet/commit/37589
* Môi trường thử nghiệm: Localhost
* Phần mềm máy chủ: Vertrigo 2.3
* Các phiên bản phần mềm hỗ trợ:
   * Apache 2.2.26
   * PHP 5.3.27
   * Mysql 5.5.34
   * Smarty Smarty-3.1.15
   * SQLite 3.8.1
   * PhpMyAdmin 4.0.9
   * SQLiteManager 1.2.4
   * Xdebug 2.2.3

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/d9be396ebc076dac416f955d11378084112bbbad
