### ISSUE TITLE
Lỗi nút trả lời cho comment reply lần thứ 3

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#741]
**Trường hợp xuất hiện lỗi:**
A comment bài viết X, 
B trả lời A, 
C trả lời B,
Nếu D nhấp link "Trả lời" C thì nó không nhảy về ô trả lời mà về #top.

Tất cả các link chức năng dành cho bình luận của C đều bị hiện tượng #top.

* Phiên bản thử nghiệm: https://github.com/nukeviet/nukeviet/commit/37589
* Môi trường thử nghiệm: Localhost
* Phần mềm máy chủ: Vertrigo 2.3
* Các phiên bản phần mềm hỗ trợ:
   * Apache 2.2.26
   * PHP 5.3.27
   * Mysql 5.5.34
   * Smarty Smarty-3.1.15
   * SQLite 3.8.1
   * PhpMyAdmin 4.0.9
   * SQLiteManager 1.2.4
   * Xdebug 2.2.3

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/2f353db6d612ead26d7303796fb236dbadaa17f7
