### ISSUE TITLE
Báo lỗi khi không có câu hỏi bảo mật

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#742]
Theo mặc định, không cần câu hỏi bảo mật để xin lại mật khẩu. Tuy nhiên nếu bật tính năng này lên thì những người dùng đã đăng ký trước đó sẽ không có câu hỏi bảo mật nên không thể xin lại mật khẩu. Hệ thống sẽ ra thông báo:
> Câu hỏi bảo mật hoặc câu trả lời chưa được khai báo khi đăng ký tài khoản nên chúng tôi không thể cung cấp mật khẩu mới cho bạn. Hãy liên hệ với quản trị site để biết thêm chi tiết.

Nên chăng hỏi câu hỏi bảo mật như một tiêu chí bắt buộc khi đăng ký thành viên ngay cả khi cấu hình đang tắt?

**Comment by vuthao** [comment]
Đã thiết lâp lại: Câu hỏi bảo mật là tiêu chí bắt buộc khi đăng ký thành viên ngay cả khi cấu hình đang tắt: https://github.com/nukeviet/nukeviet/commit/732d77c1bf02f180179f6653e67512267c23c1da
