### ISSUE TITLE
[?] file config.ini trong mỗi ứng dụng

### ISSUE THREAD

**Issue by thaotrinhj** [nukeviet/nukeviet#744]
Hiện nay để cài được các ứng dụng trong admin thì trong tệp cài đặt ứng dụng phải có file config.ini
Mình chưa rõ sự cần thiết của nó. có lẽ chỉ dùng đọc các thông tin về ứng dụng trong lúc đang cài đặt.
Mình thấy dường như có gì đó chưa ổn, cảm giác như vừa thừa vừa thiếu cái gì đó.

[extension]
id="280" -> cái số này mình đánh lung tung, trùng với cái ứng dụng khác cũng được. Dựa vào đâu để quy định id cho ứng dụng? Nếu ứng dụng được tải vè từ kho store thì có thể có id, nhưng nếu ứng dụng dạng tự tui thì id thế nào, hay là dùng mã MD5 ?
type="module" -> ứng dụng dạng block nhưng phải viết là module thì mới cài được ?

name="name" -> sao cũng được
version="1.0.00" ->, sao cũng được
[author]
name="Thaotrihj" -> sao cũng được
email="" -> sao cũng được.
[note]
text="text" -> sao cũng được.

**Comment by anhyeuviolet** [comment]
Cái config.ini hiện chưa thể hiện được ý nghĩa của nó. 
Mình lấy đại cái ini của modules shop ném qua cho modules lậu tự chế, hệ thống vẫn cho cài, báo là an toàn :3
Do đó hiện nó chỉ gây rườm rà cho quá trình đóng gói chứ chưa thể hiện được ý đồ của file, thể hiện cấu hình, phiên bản ...

**Comment by vuthao** [comment]
File config này sẽ lấy để lưu thông tin người phát triển.
Nếu bạn không tôn trọng chính mình thì có thể nhập như thế.

**Comment by anhyeuviolet** [comment]
Không hiểu thì phải hỏi cho hiểu.
Còn hệ thống NV chỉ yêu cầu có chứ không rõ ràng nội dung quy chuẩn phải thế nào, vì trong đầu file PHP đều có khai báo tên tác giả,  nếu ko khớp với ini thì có phản hồi khi cài đặt.
Chứ gì mà tới mức không tôn trọng chính mình hả anh @vuthao ? 

Ý đồ của phiên bản là thế, người phát triển ko hiểu thì cho là họ ko biết tự trọng thì quả là đáng lo lắng.

**Comment by vuthao** [comment]
@anhyeuviolet ý của mình như sau:
- Người viết cần tham khảo mẫu, để viết cho đúng chuẩn.
- Nếu người viết module mà không viết đúng, thì sẽ không có thông tin mình mình.

**Comment by anhyeuviolet** [comment]
Vâng, cảm ơn anh đã giải thích. Em đã hiểu rồi ! :D

**Comment by thaotrinhj** [comment]
Cơ chế quản lý ID là thế nào đây Anh Vũ Thảo?
Tiện ích chính chủ đã đành, nhưng người ta có thể giả mạo các thông tin hoặc dễ gây nhầm lẫn.

**Comment by thehung** [comment]
ID của ứng dụng được xác thực thông qua kho ứng dụng. Ứng dụng cài không thông qua kho sẽ không thể xác thực.
