### ISSUE TITLE
Thông báo đã gửi email ngay cả khi hệ thống không thể gửi email

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#745]
Khi sử dụng chức năng quên mật khẩu, hệ thống thông báo đã gửi email ngay cả khi hệ thống không thể gửi email.

* Phiên bản thử nghiệm: https://github.com/nukeviet/nukeviet/commit/37589
* Môi trường thử nghiệm: Localhost
* Phần mềm máy chủ: Vertrigo 2.3
* Các phiên bản phần mềm hỗ trợ:
   * Apache 2.2.26
   * PHP 5.3.27
   * Mysql 5.5.34
   * Smarty Smarty-3.1.15
   * SQLite 3.8.1
   * PhpMyAdmin 4.0.9
   * SQLiteManager 1.2.4
   * Xdebug 2.2.3

**Comment by hongoctrien** [comment]
Fixed https://github.com/hongoctrien/nukeviet/commit/f9d29051291998a994fff600c2f39d6cc5e169f2
