### ISSUE TITLE
Lỗi khi bật CAS mà không thay đổi thông số mặc định

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#746]
Khi bật CAS mà không thay đổi thông số mặc định trong Admin Control Panel. Khi khách truy cập nhấp vào icon CAS từ trang chủ, hệ thống xuất hiện trang trắng với dòng lỗi:
> phpCAS error: phpCAS::client(): CAS_TypeMismatchException: type mismatched for parameter $server_version (should be 'string '), NULL given. in D:\VertrigoServ\www\nukeviet4\modules\users\login\cas-single-sign-on.php on line 20

* Phiên bản thử nghiệm: https://github.com/nukeviet/nukeviet/commit/37589
* Môi trường thử nghiệm: Localhost
* Phần mềm máy chủ: Vertrigo 2.3
* Các phiên bản phần mềm hỗ trợ:
   * Apache 2.2.26
   * PHP 5.3.27
   * Mysql 5.5.34
   * Smarty Smarty-3.1.15
   * SQLite 3.8.1
   * PhpMyAdmin 4.0.9
   * SQLiteManager 1.2.4
   * Xdebug 2.2.3

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/4bdaacd56e6d58fbb0350a05b36cc1fd2d4308a6
