### ISSUE TITLE
Menu "Quản trị site" có vấn đề

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#747]
Menu "Quản trị site" xuất hiện ở thanh menu ngang trong Admin Control Panel khi truy cập **Admin Control Panel/ Thành viên/ Quản trị**. Việc này khiến thanh menu ngang trong Admin Control Panel bị thụt thò không ổn định.

![anh chup 161](https://cloud.githubusercontent.com/assets/1892900/6882025/4dcff37e-d5aa-11e4-8bda-5f1b5c5d3538.jpg)

* Phiên bản thử nghiệm: https://github.com/nukeviet/nukeviet/commit/37589
* Môi trường thử nghiệm: Localhost
* Phần mềm máy chủ: Vertrigo 2.3
* Các phiên bản phần mềm hỗ trợ:
   * Apache 2.2.26
   * PHP 5.3.27
   * Mysql 5.5.34
   * Smarty Smarty-3.1.15
   * SQLite 3.8.1
   * PhpMyAdmin 4.0.9
   * SQLiteManager 1.2.4
   * Xdebug 2.2.3

**Comment by hongoctrien** [comment]
Cái script của menu ngang sao sao ý. Ở những trang có dùng $.load() là nó cứ thụt thè như anh nói.

**Comment by vuthao** [comment]
Cái này do menu ngang quá nhiều nên cần ẩn một số đi, khi nào có sự kiện mới hiển thị ra:
- module authors -> Đưa link qua module Users
- module language -> Đưa link qua module settings

**Comment by thehung** [comment]
Có lẽ nên tìm giải pháp khác thay vì để cho menu bị biến động như thế.
Ví dụ: Đưa toàn bộ menu "Quản lý module", "Quản lý giao diện" vào menu "Mở rộng".
