### ISSUE TITLE
[Hỏi] Phân quyền điều hành module (news)

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#749]
Phần quyền người điều hành module có 3 quyền 
 Quản lý Chuyên mục (cái này thì rõ rồi, vì khi chọn nó thì liệt kê các quyền mà người đó được phép
còn 2 quyền còn lại Quản lý module và  Toàn quyền module thì không biết có sự khác biệt gì không, nên có hướng dẫn cho họ biết các quyền khi điều hành module này

Ở mục phân quyền: khi phân quyền chọ họ xong, nếu muốn không dừng quyền lại thị lại không có nút xóa phân quyền

Thêm nữa, tại mục thêm quản trị viên, giả sử trao cho họ quyền hạn là điều hành module, giả sử là module news, thì họ đã cấp quyền rồi, lúc này họ toàn quyền quản lý modules news nên việc phân quyền cho họ ở module news vẫn thực hiện được nhưng không có ý nghĩa, 

Thêm nữa nếu chọn quyền là chuyên mục, nhưng không tíc vào ô chuyên mục nào cả rồi bấm lưu nhưng hệ thống không thấy trả lời gì cả, nhẽ ra nên có thông báo là bạn chưa chọn mục a,b, c gì,

**Comment by thehung** [comment]
> Quản lý module và Toàn quyền module thì không biết có sự khác biệt gì không, nên có hướng dẫn cho họ biết các quyền khi điều hành module này
Khác. Toàn quyền module là thêm cả các quyền sử dụng chức năng config và phân quyền module.

> Ở mục phân quyền: khi phân quyền chọ họ xong, nếu muốn không dừng quyền lại thị lại không có nút xóa phân quyền
Xóa quyền thì làm ngược lại với phân quyền => Tước quyền quản lý module của họ.

> Thêm nữa, tại mục thêm quản trị viên, giả sử trao cho họ quyền hạn là điều hành module, giả sử là module news, thì họ đã cấp quyền rồi, lúc này họ toàn quyền quản lý modules news nên việc phân quyền cho họ ở module news vẫn thực hiện được nhưng không có ý nghĩa, 
Có chứ, cái này mặc định sẽ không khác gì ngày xưa. Nếu site nào cần phân quyền chi tiết thì vào đây phân quyền tiếp.

> Thêm nữa nếu chọn quyền là chuyên mục, nhưng không tíc vào ô chuyên mục nào cả rồi bấm lưu nhưng hệ thống không thấy trả lời gì cả, nhẽ ra nên có thông báo là bạn chưa chọn mục a,b, c gì,
Cái này tương đương với việc cho xem mà không cho làm gì khác cả!
