### ISSUE TITLE
Ảnh tải về tự động không đặt đúng cấu trúc thư mục được cấu hình

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#750]
Khi sử dụng chức năng tải tự động ảnh trong bài viết từ nơi khác về máy chủ https://github.com/nukeviet/nukeviet/commit/c0fec67 Ảnh tải về tự động không đặt đúng cấu trúc thư mục được cấu hình.

**Comment by vuthao** [comment]
báo lỗi sau khi đã fix nhé: https://github.com/nukeviet/nukeviet/commit/4bdaacd56e6d58fbb0350a05b36cc1fd2d4308a6
