### ISSUE TITLE
Hỏi về chức năng quản lý ứng dụng

### ISSUE THREAD

**Issue by thaotrinhj** [nukeviet/nukeviet#752]
Phần quản lý ứng dụng
/admin/index.php?language=vi&nv=extensions&op=manage
sau khi nhấn nút xóa -> xác nhận xóa -> cp admin sang trang trắng chỉ hiển thị 1 dòng thông báo xóa.
Thông thường thông báo xóa thành công chỉ hiển thị dạng popup trên màn hình khoảng vài giây sau đó load lại danh sách ứng dụng.

Ngoài ra còn gặp một số vấn đề như:
Block tải lên cài xong dùng rồi nhưng không thấy có trong danh sách này.
Module tải lên thành công và sử dụng rồi nhưng không thấy nút xóa

**Comment by vuthao** [comment]
@thaotrinhj, bạn Mô tả chi tiết lỗi gặp phải:
- Module bạn xóa là module nào.
- Môi trường thử Nghiệm
    - Phiên bản NukeViet: 4.0.10
    - Hệ điều hành: Ubuntu 13.10 62-bit
    - Trình duyệt web: Mozilla Firefox 27.0
    - Máy chủ web: XAMPP for Linux 1.8.1
    Nếu trên website cần có thêm thông tin
    + công cụ quản lý hosting: cpanel
    + Apache 2.4.7, MySQL 5.5.36, PHP 5.4.25

**Comment by thaotrinhj** [comment]
1. Với phiên bản mới nhất 4.0.12 thì thông báo xóa module đã bình thường rồi. OK.
2. Module tải lên thành công và sử dụng rồi nhưng không thấy nút xóa
- Đó là module Download (mặc định) Ban đầu em thấy nó có 2 nút [tải xuống] [xóa]
Em nhấn [tải xuống] sau đó [xóa] nó để cài lại module vừa xóa.
Bây giờ trong quản lý module. module download không có nút [xóa]
- theme modern ban đầu cũng có 2 nút [tải xuống] [xóa]
em cũng làm tương tự (tải xuống, xóa đi rồi cài lại) như trên
Bây giờ trong quản lý module. theme modern thấy có 2 nút [tải xuống] [xóa] như cũ.
=> Em thấy có sự khác nhau như vậy.
module tải lên rồi thì không thấy nút xóa
theme tải lên thì vẫn có nút xóa.
3. Nukeviet bản này đã có cơ chế quản lý block global chưa, em cài block global slider elastic đó lên rồi, dùng rồi nhưng trong phần quản lý ứng dụng không thấy. Giờ em muốn xóa nó thì thế nào?
Vào Quản lý giao diện > quản lý block  thì cũng đâu xóa được nó ra khỏi hệ thống.

Môi trường thử nghiệm localhost
- Phiên bản NukeViet: 4.0.12
- Hệ điều hành: win 7ul 64bit
- Trình duyệt web: chrome 41
- Máy chủ web: XAMPP v3.2.1 for win
- Apache 2.4.4, MySQL 5.5.32,  PHP 5.5.19 

Demo online cũng thế:http://nukeviet4012.16mb.com/admin/ (admin/nukeviet4012)
video https://youtu.be/w3IzwSVl78c

**Comment by vuthao** [comment]
Nguyên tắc quản lý sẽ như sau:
- Tất cả sẽ được quản lý rại phần: Mở rộng.
- Ứng dụng nếu đã được cài vào site sẽ ko được xóa. Cần vào các phần đã cài đặt để xóa trước, sau đó mới  xóa khỏi hệ thống được.

-  Phần block tôi sẽ kiểm tra lại thêm.

**Comment by vuthao** [comment]
@hoaquynhtim99 kiểm tra lại dùm anh phần: Quản lý ứng dụng, liên quan đến việc xóa block nhé.

**Comment by hoaquynhtim99** [comment]
Mình đã kiểm tra và sửa lại. Cũng xin giải thích như sau:

- Hiện nếu ứng dụng bạn cài đặt thủ công bằng cách giải nén ghi đè, thì với NukeViet 4 sẽ không nhận diện vào phần quản lý ứng dụng được.
- Ứng dụng hiện đang được sử dụng: Giao diện đang kích hoạt, block đang thêm ở vị trí nào đó, cronjob đang cấu hình ở tiến trình tự động, module đã kích hoạt thì không xóa được, muốn xóa bạn cần hủy những trạng thái trên đối với dứng dụng đó rồi mới xóa được trong phần quản lý ứng dụng.
- Ứng dụng của hệ thống thì không xóa được.
