### ISSUE TITLE
Nguyên tắc quản lý bài nháp

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#753]
Hiện bài nháp đang được đánh đồng với bài chờ đăng. Trong khi ý nghĩa của nó khác nhau.
Thông thường, bài nháp là những bài dang dở, chưa xong, do đó nó thỏa mãn nguyên tắc:
* Bài là của riêng thành viên, mọi người không được quản lý (trừ god-admin nhằm phục vụ việc dọn rác). 
* Không cần thiết kiểm tra các điều kiện đăng bài (bài nháp có thể thiếu tiêu đề, chưa có chuyên mục...)

Đề phòng trường hợp spam, nên giới hạn số bài nháp mà một người có thể gửi.

**Comment by hongoctrien** [comment]
Đang sửa

**Comment by hongoctrien** [comment]
Sửa xong cho admin https://github.com/hongoctrien/nukeviet/commit/38d427db52e25f44cf58d00f51f8269dde230806

**Comment by vuthao** [comment]
Phần ngoài site chuyển sang: https://github.com/nukeviet/nukeviet/issues/1797
