### ISSUE TITLE
Giữ bản quyền bài viết (News) không xuống hàng được.

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#755]
NukeViet 4.0 Close Beta 11
 Trong  /admin/index.php?language=vi&nv=news&op=setting phần "Nội dung hiển thị nếu bài viết có lựa chọn giữ bản quyền bài viết" của module news không cho phép xuống hàng và in đậm. Theo tôi nghĩ thì nên cho phép xuống hàng (dòng) và in đậm, in nghiên. Cũng như hạn chế số ký tự cho phép nhập vào.

**Comment by thaotrinhj** [comment]
oh! 99% người mới bắt đầu sử dụng, hoặc ko sử dụng nukeviet cứ ngỡ các bạn là đơn vị chủ quản nukeviet cơ đấy
:D

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/d2c4e06b56ec64967ccf396ff8e13b87b2ee4519
