### ISSUE TITLE
Đề xuất CSS lại phần quản lý chuyên mục cho news

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#757]
Các cột trong phần quản lý chuyên mục CSS chưa được chuyên nghiệp. Độ rộng các cột chưa tương ứng với số ký tự của nó.
![4 copy](https://cloud.githubusercontent.com/assets/11238423/6883569/d40a7a32-d5e5-11e4-90f7-1f31f3e72995.png)

**Comment by vuthao** [comment]
Hiện tại độ rộng của các cột do trình duyệt tự điều chỉnh là chính.
Màn hình của bạn đang ở kích thước khoảng 980. KÍch thước trong admin chúng tôi thiết kế cho màn hình 1366.
Hiện tại tôi đã điều chỉnh lại chút xíu: https://github.com/nukeviet/nukeviet/commit/00578d0d3ff298f25ace8bba2fab9e1ef0f2612c

**Comment by trinhthinhhp** [comment]
hiện tại mình đã fix lại chỗ này, khi ở giao diện responsive thì ko bị mất các thông số
