### ISSUE TITLE
Lỗi Chức năng tự resize ảnh quá cỡ khi upload 

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#758]
Trong quản lý file, phần cấu hình upload có chức năng kiểm tra kích thước hình ảnh và checkbox tùy chọn, cho phép resize ảnh  về kích thước quy định khi mà ảnh quá to so với mức cho phép.

![crop-1](https://cloud.githubusercontent.com/assets/6290970/6883720/06561698-d5ed-11e4-949d-85baa4d7dfbd.PNG)

Tuy vậy thì khi up ảnh to, thì chỉ có thông báo lỗi là quá to so với mức cho phép, chứ ảnh ko được resize. Cái này có phải chức năng bị lỗi không nhỉ 
![crop-2](https://cloud.githubusercontent.com/assets/6290970/6883721/1e3c3e9a-d5ed-11e4-9865-fb4688833e11.PNG)

Vì nếu có chức năng này thì quá tốt, khi upload hàng loạt ảnh or làm slider thì căn kích thước dễ hơn. Chứ làm shop, up chừng 100 ảnh minh họa mà toàn đi resize thủ công nhiều khi ko được như ý.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/f644da62863ba3b24ea9224904ab9d4307694720
