### ISSUE TITLE
Ý kiến bổ sung phần module news khi xem từng chuyên đề

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#759]
-Dưới phần tiêu đề của bài viết nên code thêm thần:
Người đăng; time đăng; lượt xem; lượt bình luận. Ngay dưới icon news thì thấy chuyên ngiệp hơn. 
-Thêm cdoer giới hạn ký tự cho homtext và title cho các block news.
Một ý kiến nhỏ mong đội coder quan tâm. Thank!
![77](https://cloud.githubusercontent.com/assets/11238423/6884496/69d0ff3a-d61f-11e4-8f19-095f3189800b.png)
-Không hiển thị video (Trong phẩn giới thiệu) trên HĐH IOS
![78](https://cloud.githubusercontent.com/assets/11238423/6884530/051a137c-d621-11e4-9eb6-9653eba12bc9.jpg)
-Lỗi CSS phần Đăng bài viết:
![79](https://cloud.githubusercontent.com/assets/11238423/6884567/3ebbaa80-d623-11e4-9d8f-9071d7a17bb1.png)

**Comment by vuthao** [comment]
@hongoctrien  em thêm lại tính năng này đã làm cho site vnqd nhé.

**Comment by hongoctrien** [comment]
Dạ, anh cứ để issue này lại nha. Em tranh thủ chuyển qua sau.

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/nukeviet/commit/f3797ca13b572c535bb41e069d8f3f469a7f079d
