### ISSUE TITLE
Lỗi trang trắng nếu người quản trị module news chỉ được phân quyền duyệt bài

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#761]
Nếu nếu người quản trị module news chỉ được phân quyền duyệt bài viết (Quyền quản lý chuyên mục) thì khi truy cập Trang quản trị của module News người này sẽ thấy trang trắng.

* Phiên bản thử nghiệm: https://github.com/nukeviet/nukeviet/commit/37589
* Môi trường thử nghiệm: Localhost
* Phần mềm máy chủ: Vertrigo 2.3
* Các phiên bản phần mềm hỗ trợ:
   * Apache 2.2.26
   * PHP 5.3.27
   * Mysql 5.5.34
   * Smarty Smarty-3.1.15
   * SQLite 3.8.1
   * PhpMyAdmin 4.0.9
   * SQLiteManager 1.2.4
   * Xdebug 2.2.3

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/32df829b85e85c0cfce9572d5244aa74cae763e9
