### ISSUE TITLE
[ Hỏi ] Không xem được video trên các thiết bị di động

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/nukeviet#762]
Vì sao nukeviet không tích hợp để xem được trên các thiết bị cầm tay ? mình thấy cái này từ khi nukeviet có những phiên bản đầu cho đến bây giờ

**Comment by anhyeuviolet** [comment]
Hình như do dùng plugin flash ( JW Player ), do đó các thiết bị di động không hỗ trợ dẫn đến không thể hiển thị.

**Comment by vuthao** [comment]
Xin phép được đóng topic này do báo lỗi không đúng quy định:
http://forum.nukeviet.vn/viewtopic.php?f=3&t=35158
