### ISSUE TITLE
Báo lỗi content cho news

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#763]
Không hiển thị được khung soạn thảo nội dung chi tiết
http://xembaomoi.thanhdathotel.com.vn/index.php?language=vi&nv=news&op=content&contentid=0&checkss=267d032b21b59e455c8601cbd40c4b67
![loi content](https://cloud.githubusercontent.com/assets/11238423/6890052/efaefe24-d6cc-11e4-8b5c-14400c968d1b.PNG)

**Comment by motcaiten** [comment]
Cái này lỗi css thì phải 

<textarea style="width: 100%; height: 300px; visibility: hidden;" id="_bodyhtml" name="bodyhtml"></textarea>

Tìm và xóa visibility: hidden;

**Comment by hoanglongvnpt** [comment]
Test ở localhost thì ok nhưng lên hosting lại bị không hiển thị khung soạn thảo "Nội dung chi tiết"

**Comment by PhamQuocTien132** [comment]
Mình kiểm tra trên bản mặc định ko thấy lỗi này nhỉ? 
Bạn thử bật về giao diện mặc định xem có lỗi ko?

**Comment by vuthao** [comment]
Tôi kiêm  tra không thấy lỗi như bạn thông báo, 
@hoanglongvnpt , bạn thử tải bản mới nhất xem có bị không nhé, nếu vẫn bị gửi cho tôi mượn tài khoản hosting để kiểm tra nhé, gửi qua email thao @ vinades . vn
