### ISSUE TITLE
[Đề xuất] Tiêu đề tên site nhiều dòng

### ISSUE THREAD

**Issue by mathagu** [nukeviet/nukeviet#764]
Nếu xây dựng web cho một cơ quan nào đó thì thường tên site phải là hai dòng, dòng trên ghi tên cơ quan chủ quản, dòng dưới ghi tên cơ quan thực hiện.

Do vậy, đề xuất với đội code là thêm tùy chọn này vào hệ thống, nếu người dùng chọn thì in hai dòng, còn nếu không thì in một dòng!

Thân!

**Comment by vuthao** [comment]
Nếu làm trên banner thì bạn tự hực hiện bằng cách thay đổi template nhé, một mã nguồn không thể làm hết tất cả mọi thứ được, bởi nhu cần mối người một khác.
