### ISSUE TITLE
Lỗi trắng trang sau khi cài đặt thành công NukeViet: 4.0.13

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/nukeviet#769]
Phiên bản NukeViet: 4.0.13 
Môi trường thử Nghiệm: Localhost
Trình duyệt web: chrome, coccoc.
Hệ điều hành: Win 7
Máy chủ web: XAMPP Control Panel v3.2.1
Lỗi: Sau khi cài đặt thành công đăng nhập vào quản trị không thấy gì hết, trang trắng. Vào URL site cài đặt không thấy gì hết, trang trắng.
(Cài đặt NukeViet: 4.0.11 chạy bình thường)

**Comment by vuthao** [comment]
Hiện tại chúng tôi kiểm tra không thấy lỗi này, bạn thử cài đặt lại xem sao.
