### ISSUE TITLE
Block comment không hiển thị các bình luận

### ISSUE THREAD

**Issue by hungga** [nukeviet/nukeviet#770]

**Comment by hungga** [comment]
demo onlinw: http://new.baichoi.com/

**Comment by mathagu** [comment]
Sao từ máy tôi vào xem các tin tức ở trang đó đều thấy các bình luận nhỉ?

Như ở http://new.baichoi.com/Doi-tac/tytytytytytytyt-13.html có bình luận là

jgoprkt[rlpt[rtplr]rt];pởtrt
 admin   Trả lời   Thích 1   Không thích 0   03/04/2015 11:05

**Comment by hungga** [comment]
mình nói cái bock bên cột phải, đã bật lên nhưng ko thấy j

**Comment by thangbv** [comment]
Mình thấy nó hiển thị bình thường mà nhỉ. Bạn chú ý khi thiết lập block có phần Bản ghi hiển thị để con số lớn hơn 0 nhé.

**Comment by hungga** [comment]
OK, cám ơn bạn. Closed
