### ISSUE TITLE
Lỗi khung autosave không thu nhỏ được

### ISSUE THREAD

**Issue by mercury86** [nukeviet/nukeviet#771]
Phiên bản NukeViet: 4.0.13
Môi trường thử Nghiệm: Localhost
Trình duyệt web: chrome
Hệ điều hành: Win 8.1
Máy chủ web: XAMPP Control Panel mới nhất
Đang soạn thảo bản tin, một lúc lâu lâu tự nhiên bật lên khung autosave, Khung bị choáng hết màn hình soạn thảo; cũng xuất hiện lúc đăng bài trong module blog mà chưa chọn chuyên mục:
- không thể thu nhỏ khung
- không tìm thấy nút recover
- phải ấn esc mới thoát được khung

ảnh: http://d.f24.photo.zdn.vn/upload/original/2015/04/03/14/46/3144220086_615540437.jpg

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/66dbb777bf86eb7c3d1b0fdec6be8c061e823e50
