### ISSUE TITLE
Lỗi ở Block Global HTML

### ISSUE THREAD

**Issue by mathagu** [nukeviet/nukeviet#772]
Môi trường thử nghiệm:

Phiên bản NukeViet: 4.0.13
Môi trường thử Nghiệm: localhost
Trình duyệt web: Google Chrome
Hệ điều hành: Win 8.1
Máy chủ web: USBWebserver 8.6

Mô tả lỗi:
Chèn công thức Toán học từ http://latex.codecogs.com/ không được, khi chèn lệnh LaTeX cần ký tự \ để bắt đầu lệnh, nhưng khi lưu và hiển thị thì bị chuyển thành ký tự / nên công thức hiển thị không đúng như mong muốn.

Ví dụ: Cần chèn là http://latex.codecogs.com/gif.latex?\sqrt[P]{B} như sau khi lưu thì chuyển thành http://latex.codecogs.com/gif.latex?/sqrt[P]{B}.

**Comment by mathagu** [comment]
Không chỉ ở block Global HTML, mà ở module Tin tức cũng bị như vậy. Khi cần chèn một công thức mà trong lệnh LaTeX có ký hiệu \ đều bị chuyển thành /, và khi đó công thức hiển thị không đúng. Các công thức không dùng dấu \ thì hiển thị bình thường.

![image](https://cloud.githubusercontent.com/assets/11552661/6991859/d4cde4fe-dad6-11e4-972a-ff9dcd486955.png)

**Comment by vuthao** [comment]
duplicate: https://github.com/nukeviet/nukeviet/issues/680
