### ISSUE TITLE
Lỗi ban đầu về CSS giao diện

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#773]
Lỗi css
Module New: (hiển thị chuẩn)
![new](https://cloud.githubusercontent.com/assets/11238423/6979950/378b68ea-da15-11e4-89a0-6b9fbc1eef1d.png)
Các module khác: phần icon ([SOCIAL_ICONS])
bị đẩy xuống dưới:'
![module](https://cloud.githubusercontent.com/assets/11238423/6979965/6362e448-da15-11e4-8191-610d583846af.png)

**Comment by anhyeuviolet** [comment]
Đang thử nghiệm và mình thì ko thấy lỗi này. @.@

**Comment by webvangvn** [comment]
![css1](https://cloud.githubusercontent.com/assets/8604866/7038964/cddbb09e-dde3-11e4-90a8-c9a06eed52e4.jpg)



![css2](https://cloud.githubusercontent.com/assets/8604866/7038966/d463530e-dde3-11e4-9bab-66f94c85f368.jpg)


Cung chung so phan

**Comment by vuthao** [comment]
Em xin phép đóng topic này lại do báo lỗi không đúng quy định.
các bác vui lòng xem lại dùm em tại: http://forum.nukeviet.vn/viewtopic.php?f=3&t=35158
