### ISSUE TITLE
Lỗi Undefined variable: manament  ở module banner

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#774]
Khi click vào module banner thì có lỗi sau:
"Thông báo từ Hệ thống
Nên chú ý Nên chú ý: Undefined variable: manament in file /modules/banners/funcs/main.php on line 34"

Phiên bản open beta 4.0.13

**Comment by NukeVietCMS** [comment]
Cái này tôi nghĩ là lỗi ở hosting đấy. Tôi có chạy thử nghiệm ở http://dangtinbaomuaban.net nhưng không thấy báo lỗi gì hết đối với phần này.

**Comment by phongaz** [comment]
Lỗi Undefined variable là do nó chưa được khai báo trước khi sử dụng chứ có liên quan gì đến hosting.

Lỗi này chỉ xuất hiện khi trình duyệt gọi vào file chứa nó,  và nó chỉ xuất hiện 1 lần cho đến khi bạn tắt trình duyệt và duyệt lại

**Comment by anhyeuviolet** [comment]
Dọn dẹp hệ thống thì nó sẽ lòi ra lại lỗi. Nhưng mà mình test ko thấy lỗi này. @.@

**Comment by mathagu** [comment]
Theo thứ tự khởi động module thì /modules/banners/functions.php sẽ load trước /modules/banners/funcs/main.php, mà trong functions.php thì có khai báo biến $manament trong ấy rồi. Do vậy, không biết bạn có chỉnh sửa gì các file ấy hay không? Nếu không, thì thử Dọn dẹp lại hệ thống rồi chạy lại xem sao!

**Comment by hongoctrien** [comment]
Trong quá trình test có khá nhiều lỗi cảnh báo.
Mọi người mở file includes/class/error.class.php
Tìm đến đoạn (khoảng dòng 400)
```php
file_put_contents( $track_errors, '', FILE_APPEND );
```
Và comment hoặc xóa nó đi, dọn dẹp hệ thống.
Bây giờ hệ thống sẽ luôn hiển thị lỗi cảnh báo, chứ không ẩn đi nữa.

**Comment by xuanthuy235** [comment]
mình k gặp lỗi như này của bạn nhưng làm như triển nói thì có mấy lỗi phát sinh và mình đã khắc phục xong.

**Comment by xuanthuy235** [comment]
trng http://giongcaytrong.org của mình hoạt động bình thường :3 ơn giời

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/f82dd91c1407b01f85ce2b778f742df4e137e1cb
