### ISSUE TITLE
ngôn ngữ tiếng anh chưa đủ

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#775]
tai admin/index.php?language=en&nv=settings&op=system

Chưa đủ biến ngôn ngữ
![capture](https://cloud.githubusercontent.com/assets/6806295/6982548/5889855e-da3d-11e4-88ca-e0befc1ccacd.PNG)

Phiên bảng 4.0.13

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/8b48704c5d7e9291cff744a9716a7905f47dbef1
