### ISSUE TITLE
Thêm block tại cửa sổ popup bấm quay lại không thoát

### ISSUE THREAD

**Issue by mercury86** [nukeviet/nukeviet#777]
trên chrome
bản nuketviet 4.0.13
xampp server

lúc thêm block tại cửa sổ popup thêm mới, bấm quay lại không thoát

**Comment by vuthao** [comment]
Bạn kiểm tra lại với bản mới nhất tại: https://github.com/nukeviet/nukeviet/archive/develop.zip xem đã hết lỗi đó chưa nhé.

Hiện tại mình thấy lỗi này đã được sửa
