### ISSUE TITLE
Nên xóa bỏ imgthumb detail bài viết

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#778]
imgthumb ở  bài viết không cần thiết, bởi nó sẽ lặp lại hình ảnh chính trong nội dung bài viết, cần xóa nó không cần hiển thị ở html và xóa php để đỡ phải truy vấn trường homeimgfile

**Comment by vuthao** [comment]
Bạn vào phần cấu hình module tin tức sẽ có phần: Cấu hình mặc định, Trình bày hình trong bài viết khi đăng bài

Hoặc cấu hình tại mỗi bài viết với chức năng: Trình bày hình trong bài viết
