### ISSUE TITLE
import, export danh sách thành viên

### ISSUE THREAD

**Issue by dienthaitoan** [nukeviet/nukeviet#779]
Nên viết thêm phần import, export user để sau này có thể làm theo code đó viết module khác
cảm ơn nhiều

**Comment by vuthao** [comment]
Nên viết thêm phần import, export user chúng tôi dự định sẽ làm thành phần addon cho module  users. bởi để chạy thư viên này sẽ cần thêm thư viện gây nặng mã nguồn không cần thiết.

Nếu muốn tìm hiểu bạn có thể tham khảo thư viện: https://github.com/PHPOffice/PHPExcel
