### ISSUE TITLE
Lỗi không thoát hết cửa sổ popup khi áp dụng block cho từng module

### ISSUE THREAD

**Issue by mercury86** [nukeviet/nukeviet#780]
Phiên bản NukeViet: 4.0.13
Môi trường thử Nghiệm: Localhost
Trình duyệt web: chrome
Hệ điều hành: Win 8.1
Máy chủ web: XAMPP Control Panel
Mô tả lỗi: khi áp dụng block bất kỳ cho module nào đó, không thoát được cửa sổ khi hoàn thành.
Thực hiện:
Tại giao diện admin - Quản lý giao diện - Quản lý block. Mục Chọn module: chọn module bất kỳ, tại khu vực chọn Main. Chọn sửa một module bất kỳ: ví dụ sửa bock right thăm dò ý kiến, chọn sửa
Tại mục Áp dụng cho module: check vào Chọn module, tiếp theo tại mục Bình luận bỏ check  post (hoặc cái khác), tiếp tục bấm Chấp nhận. Kết quả (vẫn còn khung-cửa sổ popup chưa thoát hết)
http://d.f24.photo.zdn.vn/upload/original/2015/04/05/15/47/3144859068_1765444523_574_574.jpg

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/c2be969b81402fd5c446002acbcc6895a42ee7ef
