### ISSUE TITLE
Application version is invalid

### ISSUE THREAD

**Issue by johnsmeeth** [nukeviet/nukeviet#781]
Mình cài trên localhost. Khi cài các extension của tác giả thaotrinh đều bị báo lỗi "Application version is invalid".

**Comment by anhyeuviolet** [comment]
Extension hay gói block/modules hả bạn ?
Nếu là các gói thì xem lại quy chuẩn đóng gói xem đã theo quy tắc mới chưa.

**Comment by vuthao** [comment]
@johnsmeeth , @thaotrinhj 
Các module nào không đúng vui lòng liên hệ tác giá của nó nhé.
