### ISSUE TITLE
Lỗi permisson chuyên mục tin tức

### ISSUE THREAD

**Issue by mercury86** [nukeviet/nukeviet#782]
Phiên bản NukeViet: 4.0.13
Môi trường thử Nghiệm: Localhost
Trình duyệt web: chrome
Hệ điều hành: Win 8.1
Máy chủ web: XAMPP Control Panel
Mô tả lỗi: permisson cho chuyên mục tin tức không có tác dụng trên menu trái (chuyên mục)
Thực hiện:
CPanel - Tin tức - Quản lý chuyên mục - Tin tức(3) - Tại dòng Bản tin nôi bộ chọn Sửa - Tại Các nhóm được xem: chỉ chọn thành viên - Lưu thay đổi.
Mở trình duyệt khác không đăng nhập với quyền thành viên nào cả. Tại chuyên mục tin tức bên menu trái, bấm dấu +, vào Bản tin nội bộ: mọi bài viết vẫn xem bình thường, như chưa hề permisson.

**Comment by vuthao** [comment]
@mercury86 Module tinh tức đang làm theo hướng phần phân quyền bài viết chỉ xem chi tiết, còn bên ngoài chủ đề không phân quyền. Mục đích của việc này làm cho các tạp chí chỉ có nhóm đối tượng nhất định được xem nội dung chi tiết.
Trong bản tối, chúng tôi sẽ sửa lại tiêu đề ngôn ngữ để tránh hiểu sai.
