### ISSUE TITLE
mã xác nhận không tự động thay đổi sau mỗi lần f5 hoặc nhập sai thông tin đăng nhập

### ISSUE THREAD

**Issue by hungga** [nukeviet/nukeviet#783]
Trang đăng nhập thành viên, admin: mỗi khi nhập sai tên hoặc pass sai, sau đó đăng nhập lại nhưng mã xác nhận không tự động thay đổi mới mà vẫn như cũ, tiếp tục đăng nhập thông tin chính xác với mã xác nhận đó thì báo sai mã xác nhận
demo online: http://new.baichoi.com/

**Comment by vuthao** [comment]
Khi báo lỗi bạn vui lòng cung cấp các thông tin sau để chúng tôi có thể xây dựng môi trường thử nghiệm giống của bạn để kiểm tra

Mã: Chọn tất cả
    - Phiên bản NukeViet: 4.0.10
    Môi trường thử Nghiệm: Localhost/ hosting
    - Hệ điều hành: (Ví dụ: Ubuntu 13.10 32-bit)
    - Trình duyệt web: (Ví dụ: Mozilla Firefox 27.0)
    - Máy chủ web: (Ví dụ: XAMPP for Linux 1.8.1 )
    Nếu trên website cần có thêm thông tin
    + Công cụ quản lý hosting: (Ví dụ: Cpanel/ Vista Panel/ Parallels Plesk/ DirectAdmin/ Kloxo...)
    + Các thông tin khác về phần mềm webserver, PHP và cơ sở dữ liệu: (Ví dụ: Apache 2.4.7, MySQL 5.5.36, PHP 5.4.25)

**Comment by hungga** [comment]
- Phiên bản NukeViet: 4.0.13
Môi trường thử Nghiệm: hosting
- Hệ điều hành: Cloud Linux
- Trình duyệt web: Version 41.0.2272.118 m
- Máy chủ web: (Ví dụ: XAMPP for Linux 1.8.1 )
+ Công cụ quản lý hosting: Cpanel
+ Các thông tin khác về phần mềm webserver, PHP và cơ sở dữ liệu:  Apache 2.4.7, MySQL 5.6, PHP 5.4.25

**Comment by hungga** [comment]
bấm nhầm: e bổ sung
- Phiên bản NukeViet: 4.0.13
Môi trường thử Nghiệm: hosting
- Hệ điều hành: Cloud Linux
- Trình duyệt web: Version 41.0.2272.118 m
- Máy chủ web: XAMPP for Linux 1.8.1
+ Công cụ quản lý hosting: Cpanel
+ Các thông tin khác về phần mềm webserver, PHP và cơ sở dữ liệu: Apache 2.4.7 , MySQL 5.6, PHP 5.6

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/2567a514ee50946ea1e8cede900256ed8b7a7085
