### ISSUE TITLE
Export bảng dữ liệu của module

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#784]
admin/index.php?language=vi&nv=database
Hiện tại ở đây list tất cả các bảng trong CSDL. Mỗi lần mỗi backup CSDL của riêng một modue nào đó thì phải ngồi cặm cụi check từng cái, như news mà có khoảng 4 module ảo check đuối :D.
Đề xuất thêm bộ lọc để xuất dữ liệu theo module.

**Comment by vuthao** [comment]
theo mình nên sửa vào đây: /admin/index.php?language=vi&nv=database&op=file
Sau đó thêm module ở dạng seclect, lúc đó sẽ ít thao tác chọn nhất.

**Comment by PhamQuocTien132** [comment]
Theo em thì phát triển thêm tính năng này vào: admin/index.php?language=vi&nv=database để tránh phân tán chức năng. Khi người dùng muốn sao lưu dữ liệu thì chỉ vào 1 chức năng thôi sau đó tùy chọn. 
![index](https://cloud.githubusercontent.com/assets/6023707/7669393/6341a5fa-fc9b-11e4-8f5a-598456a6ea7c.png)

Thêm 1 selectbox vào ví trí khoanh đỏ với các option: 
- Tích chọn (mặc định) 
- Tất cả 
- CSDL modules 1
- CSDL modules 2
....

**Comment by hoaquynhtim99** [comment]
Dữ liệu của module không chỉ có các bảng ```prefix_module_table``` mà còn dữ liệu cấu hình ở bảng ```prefix_config``` , nếu hiểu theo nghĩa backup module rồi backup các bảng đó thôi thì kiểu gì cũng sót dữ liệu.

**Comment by vuthao** [comment]
Nếu muốn chọn từng bảng có thể dùng phpmyadmin sẽ tiện hơn trong khoản này.

**Comment by vuthao** [comment]
Hiện tại bản NukeViet 4.3 đã có tính năng chọn nhiều bằng cách chọn điểm đầu và điểm cuối.
