### ISSUE TITLE
Thư viện jquery shadowbox đóng cửa?

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#785]
Không rõ có phải như thế không, vào trang http://www.shadowbox-js.com/ không được.
Nếu thế thì phải thay thư viện shadowbox NukeViet đang dùng bởi thư viện khác.

**Comment by vuthao** [comment]
Tôi thấy dự án đó vẫn chạy nhé.
https://github.com/mjackson/shadowbox/commits/v5
