### ISSUE TITLE
bỏ tên module tiếng Anh trên đường dẫn

### ISSUE THREAD

**Issue by thangvn** [nukeviet/nukeviet#788]
http://studiokhoa.byethost12.com/contact/

Không lẽ chúng ta chỉ bỏ được tên Module mặc định làm trang chủ mà không bỏ được tên các module khác sao ? 

Trong phần quản trị thì tên nó là Liên hệ mà đường dẫn thì là contact

**Comment by huytv56** [comment]
Bác tạo module ảo từ module contact thì đường dẫn tuỳ ý thôi ạ.

**Comment by mathagu** [comment]
Chuyện dùng phương thức GET để gọi một module là điều gần như hiển nhiên khi dùng PHP để tránh việc phải sinh ra quá nhiều biến. Có thể bỏ được tên module trên URL, nhưng NukeViet khi đó chắc nó phình ra không khác gì quả bóng.

Còn về tên thì đơn giản thôi, dù là người Việt làm nhưng không thể chỉ hướng đến người Việt, mà còn cả khu vực, thế giới, thì việc có tên tiếng Anh cũng là bình thường. Thậm chí, đó còn là tên gốc của module, cái tên "Liên hệ" chỉ là "thể hiện" của nó mà thôi.
