### ISSUE TITLE
Cấu hình hiển thị tên thành viên

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#789]
Hiện tại tách riêng first_name và last_name.
**"Kiểm tra nếu thành viên có khai báo họ tên thì hiển họ + tên (theo cấu hình hiển thị họ - tên hoặc tên - họ từ module user) ngược lại hiển thị tên đăng nhâp"**
Rất nhiều module và nhiều chỗ có sử dụng lệnh điều kiện này (VD module news, hiển thị tên người đăng,....)
Đề xuất viết 1 hàm hệ thống xử lý cái này, khi cần chỉ gọi hàm thôi trả về họ tên hoặc username thôi, khói viết lại điều kiện nhiều lần.

**Comment by vuthao** [comment]
@hongoctrien hiện tại đã viết function này:
https://github.com/nukeviet/nukeviet/commit/9e1017f98354c67a588f7d9bd56100f915a2e325

Đã giao cho @PhamQuocTien132  sửa lại phần này cho module users.

**Comment by vuthao** [comment]
Hiện tại đã xử xong phần này tại: https://github.com/nukeviet/nukeviet/commit/71f230ede3571f3cf01775ebf05b4de0d971644d
