### ISSUE TITLE
Kiểm tra điều kiện thực thi các lệnh gọi comment

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#790]
https://github.com/nukeviet/nukeviet/blob/release/modules/news/funcs/detail.php#L340
Trường hợp module comment ngưng hoạt động hoặc module không sử dụng comment thì đoạn code trong khối này vẫn được thực thi.
Kiểm tra tương tự với những module khác có sử dụng comment.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/2fb15e5a7f768fe359f880b0cac7b7eb6e47dccc
