### ISSUE TITLE
Để xuất hiển thị link sitemap trong admin 

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#791]
để tiện cho người dùng biết được link sitemap của mình để xuất hiển thị link sitemap trong admin. Hiện tại nhiều người không biết nên toàn tự tạo sitemap bên ngoài không biết Nukeviet đã có nó. và đổ thừa Nukeviet không hỗ trợ. rất bực :D. Vấn đề nữa là nếu module nào không có bài viết đề nghị ẩn sitemap module đó đi để tránh gặp thông báo lỗi khi khai báo với google. Em cũng gặp tình trạng người dùng thấy báo lỗi chấm than lại cũng đổ cho Nukeviet lỗi và cũng đi làm sitemap riêng rất khoai :D

**Comment by vuthao** [comment]
đã có sẵn trong phần: 
Công cụ SEO -> Sitemap Ping
/admin/index.php?language=vi&nv=seotools&op=sitemapPing

Với nukeviet 4, link sitemap sẽ trở thành:  http://domain.my/sitemap.xml
