### ISSUE TITLE
Oauth Google có vẻ không hoạt động

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/nukeviet#792]
Mình test bản NV 4.0.13, đã config API nhưng không thấy chạy:
Demo: http://kh.phamdinhhau.com/users/

**Comment by thaotrinhj** [comment]
nukeviet-4.0.14 
google không thấy có tác dụng gì cả
Yahoo hoạt động tốt.

**Comment by phamdinhhau** [comment]
Issue này có vẻ không ai quan tâm :dancer:

**Comment by vuthao** [comment]
@phamdinhhau  Xem và thực hiện rồi viết dùm tài liệu cho anh em nhé:

Để đăng ký OAuth 2.0 credentials, xem chi tiết tại:
https://developers.google.com/accounts/docs/OpenIDConnect#getcredentials
Phần:
Obtain OAuth 2.0 credentials

Ví dụ khai báo tại google cho site http://demo.nukeviet.vn
 Authorized JavaScript origins: http://demo.nukeviet.vn
 Authorized redirect URIs : http://demo.nukeviet.vn/index.php?language=vi&nv=users&op=oauth&server=google

Sau đó cần cấu hình tại trang: http://demo.nukeviet.vn/admin/index.php?language=vi&nv=users&op=config&oauth_config=google

App ID/API Key: là thông số Client ID do google tạo ra ví dụ: 95005052-kou7g15jsb1tq2kipixxxxxrvqmje5nc.apps.googleusercontent.com
Mã Bí Mật: Tưng ứng với Client secret  do google tạo ra ví dụ: mUScXa7FVgfsxxxxxLAnIs9x

**Comment by phamdinhhau** [comment]
- Authorized JavaScript origins
- Authorized redirect URIs
2 Phần trên là option không nhất thiết cần :)
