### ISSUE TITLE
Một vài nhầm lẫn nhỏ

### ISSUE THREAD

**Issue by thaotrinhj** [nukeviet/nukeviet#794]
Đây là một vài nhầm lẫn nhỏ từ những phiên bản trước. Tại phiên bản 4.0.14 vẫn còn tồn tại.
1- Module thành viên, tại phần tùy biến dữ liệu.
Chọn kiểu số:
"Chiều dài ký tự ít nhất" phải là "Số nhỏ nhất" và "Chiều dài ký tự nhiều nhất" phải là "Số lớn nhất" mới đúng
<img src="http://i.imgur.com/juX9pop.png"/>

2- Tại form tìm kiếm thành viên (để thêm quản trị viên) table lệch 1 ô như ảnh
<img src="http://i.imgur.com/x89eqkJ.png"/>
Vì chúng ta sử dụng đã dùng bootstrap thì mình đề nghị chúng ta tận dụng luôn bootstrap cho những form trong contol admin cho nhanh gọn trong lúc code thiết kế và lại responsive
Việc dùng table để trình bày form thế này đã lỗi thời, nhiều  bất cập.

Do lúc viết hướng dẫn module nên phát hiện có những chỗ ai chính tả tiếng việt, tuy nhiên thấy không quan trọng nên lúc đó bỏ qua.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/c0bf8fa590cbb6babab7296b85ed0c7e595aa9b3
