### ISSUE TITLE
Lỗi đa ngôn ngữ site

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#795]
Hiện tại site không kích hoạt tính năng đa ngôn ngữ, tuy nhiên khi điền vi hoặc en đều xem được
![en](https://cloud.githubusercontent.com/assets/6806295/7102034/a4f47f78-e09d-11e4-9f8b-249c27c54dca.PNG)
![vi](https://cloud.githubusercontent.com/assets/6806295/7102036/b404a3e4-e09d-11e4-95d0-f5db33d71e8f.PNG)

Phiên bản: 4.0.13 open beta 1
Hệ điều hành window 8.1
Máy chủ centos 6
trình duyệt chrome 41.0.2272.118 m

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/4854cc31240caab370f4ebc2107fe3be685f1e7f
