### ISSUE TITLE
Lỗi dư domain trong trong mail nhận được từ nút gửi bài viết

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#796]
Tại dòng 57, file sendmail.php. dư hằng nv_mydomain
https://github.com/nukeviet/nukeviet/blob/release/modules/news/funcs/sendmail.php

xem kết quả trong mail nhận được
![l i url bai vi t g i mail](https://cloud.githubusercontent.com/assets/6806295/7102164/66331c0e-e0a2-11e4-9b9f-190dcf3a1bb1.PNG)

Phiên bản: 4.0.13 open beta 1
Hệ điều hành window 8.1
Máy chủ centos 6
trình duyệt chrome 41.0.2272.118 m

**Comment by vuthao** [comment]
Hiện tại mình kiểm tra thấy phần này vẫn thấy nó bình thường.
Không viết phong có sửa chữa code lên quan đến rewite hay có bật plugin nào liên quan đến rewite  không.

**Comment by phongaz** [comment]
Mình có bật plugin rewrite absolute url thôi
Code không sửa gì hết nhé
