### ISSUE TITLE
Lỗi trùng thẻ title tag cho nút savefile

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#797]
Url lưu bài viết và url của bài viết là khác nhau nhưng có cùng thẻ title tag -> trùng lặp thẻ này.

![savefile](https://cloud.githubusercontent.com/assets/6806295/7102207/59be003c-e0a3-11e4-8de6-635b76cb5220.PNG)

Có nên sử dụng phương thức javascript: void(0) giống như nút print và send không nhỉ? 

Phiên bản: 4.0.13 open beta 1
Hệ điều hành window 8.1
Máy chủ centos 6
trình duyệt chrome 41.0.2272.118 m

**Comment by vuthao** [comment]
ơ cái này ảo vãi, trong nội dung cả file html tải về đã có đoạn code.
<link rel="canonical" href="xxxxxxxxxxxxxxxx" />

Không hiểu google đặt ra cái canonical ....., hay trang của bạn bị bỏ đoạn này đi

**Comment by phongaz** [comment]
Vẫn dùng theme mặc định mà, không chỉnh sửa gì code cả
