### ISSUE TITLE
Đề xuất form comment nukeviet mặc định cứng hiện thị thành dạng block global

### ISSUE THREAD

**Issue by thaotrinhj** [nukeviet/nukeviet#798]
Hiện nay form comment hiển thị cứng trong các trang hiển thị bài viết chi tiết ở các module.
Mình định viết tiện ích tab comment để cài đặt bao gồm comment nukeviet với những coment dạng khác nhưng form coment đã hiển thị cứng như thế này thì chịu
Mình đề nghị hiển thị form ở dạng block global để người dùng chủ động tùy ý chọn vị trí hiển thị, trang hiển thị.
Không biết ý đội code thế nào?
Ảnh thứ 2 trong demo chỉ là mình họa mong muốn
<img src="http://i.imgur.com/WAc7ToS.png"/>
<img src="http://i.imgur.com/EOshizf.png"/>

**Comment by vuthao** [comment]
Bạn vui lòng thảo luận vấn đề này tại diễn đàn. Tại trang này chúng tôi quản lý thông báo lỗi.
