### ISSUE TITLE
Lỗi chọn nguồn tin khi thêm bài viết mới

### ISSUE THREAD

**Issue by quocdatit** [nukeviet/nukeviet#799]
![untitled](https://cloud.githubusercontent.com/assets/9635199/7103909/292fa706-e0e7-11e4-8800-7d0e35185316.png)

Khi nhập nguồn tin, nó hiện gợi ý, nhưng khi chọn 1 nguồn tin trong gợi ý thì khung nhập bị xóa trắng, phải nhập lại. Phần gợi ý nguồn tin không chọn được.

Phiên bản NukeViet: 4.0.13
Môi trường thử Nghiệm: Hosting BăngThôngViệt.VN
Trình duyệt web: Cốc Cốc
Công cụ quản lý hosting: Cpanel

**Comment by vuthao** [comment]
Nguồn tin chúng tôi thiết kế là để nhập 1 url có tồn tại, và quản lý lưu trữ nó để có thể đối chiếu, chứ không thể nhập bất kỳ cái gì vào cũng được

**Comment by quocdatit** [comment]
Ví dụ như nó hiện ra list Nguồn tin, mình click chọn không được hả?
