### ISSUE TITLE
Lỗi giao diện upload trên máy chủ nginx

### ISSUE THREAD

**Issue by cpanel10x** [nukeviet/nukeviet#801]
![image](https://cloud.githubusercontent.com/assets/5106227/7106488/a66c2570-e16c-11e4-89d0-015c9415b442.png)

Lỗi này đã gặp ở 3.x đến 4.x

**Comment by vuthao** [comment]
@cpanel10x Vui lòng xem lại quy định báo lỗi.

Không phải chúng tôi đặt ra quy định giở hơi đâu. Muốn kiểm tra được lỗi thì chúng tôi cần có môi trường thử nghiệm giống bạn, chứ lúc làm chúng tôi đã kiểm tra chán rồi.
