### ISSUE TITLE
Module comment lỗi trắng trang khi dùng đa ngôn ngữ

### ISSUE THREAD

**Issue by thanhsonvn** [nukeviet/nukeviet#802]
Khi dùng đa ngôn ngữ, ví dụ ngôn ngữ Pháp (fr).
Mà trong thư mục modules/comment/language không tồn tại file fr.php thì khi xem bài viết sẽ bị trang trắng.
Đè xuất nếu không tồn tại file thì load mặc định ngôn ngữ anh hoặc việt.

**Comment by vuthao** [comment]
Việc xây dựng site bạn cần hoàn thiện ngôn ngữ trước.
còn góp ý của bạn chúng tôi đã sửa lại để tránh việc này: https://github.com/nukeviet/nukeviet/commit/a365e11e2a200790a35d98bcd5ef0480a402d4aa
