### ISSUE TITLE
Về tiêu đề (keywords) của chức năng tags trong news

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#805]
Hiện Tags có 2 cách thêm là khi chèn bài viết và tạo trong phần quản lý tags trong admin.
Khi dùng chức năng quản lý Tags để thêm, thì keywords sẽ luôn bị sinh 2 giá trị, trong đó 1 là nội dung người dùng nhập, 1 là liên kết tĩnh của tags đó.
Điều này thể hiện qua dòng 
	$keywords[] = $alias;

Mình thấy cái này không cần thiết. 1 Tags thì có 1 giá trị tiêu đề (keywords) duy nhất là đủ. Alias chỉ cần làm công việc của nó là đủ. Mình ko hiểu lắm về ý đồ dùng alias thêm vào keywords, khá bất tiện khi viết bloc tags cho news, vì các tags tạo trong Admin đều có 2 tên rất khó coi.

Ngoài ra khi thêm tags trong Admin panel thì cũng ko loại được các ký tự đặc biệt trong tags như đã thiết lập trong modules news.

**Comment by vuthao** [comment]
@anhyeuviolet không biết bạn đã thử chưa hay chỉ đọc code rồi nhận xét nhỉ.
Nếu đa thử cho tôi một ví dụ cụ thể để kiểm tra nhé, tôi nhập thử: XIn chào : các bạn việt nam
Thì chỉ có duy nhất keywords: XIn chào các bạn việt nam

**Comment by anhyeuviolet** [comment]
Mai em chụp ảnh cho anh @vuthao xem. Em dốt code lắm. Dùng rồi mò ra thôi. Anh thử vào quản lý tags rồi thêm tags xem sao.

**Comment by anhyeuviolet** [comment]
![01](https://cloud.githubusercontent.com/assets/6290970/7162764/ae3a9cb8-e3c0-11e4-8e84-d2985099a6b7.PNG)
![2](https://cloud.githubusercontent.com/assets/6290970/7162765/ae41400e-e3c0-11e4-94d0-66cc3a508509.PNG)
Đang ngủ nhưng cũng phải dậy làm cái hình.
Ảnh trên là khi điền đầy đủ 2 dòng : Liên kết tĩnh và Từ khoá. Kết quả là keywords có 2 giá trị.

Ảnh dưới là khi điền duy nhất dòng liên kết tĩnh, khi đó thì ô từ khoá mới thật sự là có 1 kết quả.
Vậy không biết em có nhầm lẫn ở cách dùng ko anh @vuthao  ?

**Comment by vuthao** [comment]
Bạn nhập từ khóa và tag khác nhau nó phải điền hai cái là đúng rồi mà.
Một tag, ứng với 1 liên kết có  thể có nhiều từ khóa

**Comment by anhyeuviolet** [comment]
Khi thêm tags với từ khoá và tags y như nhau.
![05](https://cloud.githubusercontent.com/assets/6290970/7172371/c6f3022c-e410-11e4-82b5-bfe01cd085fa.JPG)

Sau khi lưu thì thu kết quả

![03](https://cloud.githubusercontent.com/assets/6290970/7172369/c6ee8544-e410-11e4-8d6d-121f00fcc159.JPG)

Khi chỉnh sửa thì ra như này
![04](https://cloud.githubusercontent.com/assets/6290970/7172370/c6f2fbb0-e410-11e4-85b5-7bba6a2d307b.JPG)

Em chịu thua rồi. Nếu vẫn không diễn đạt thành công xem như là em không có năng khiếu nói cho người khác hiểu.
