### ISSUE TITLE
Lỗi đóng gói giao diện 

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/nukeviet#807]
![loidonggoigiaodien0](https://cloud.githubusercontent.com/assets/8604866/7114588/0470bf54-e209-11e4-895d-f5c37ac65cf9.jpg)

Khi click vào tải xuống giao diện khác ngoái themes default thì bị lỗi trang 404

![loidonggoigiaodien](https://cloud.githubusercontent.com/assets/8604866/7114598/20cbabe6-e209-11e4-9b79-4f1850f80c17.jpg)

centos 5.10
apache :2.2
mysql 5.5
php 5.5

**Comment by vuthao** [comment]
@webvangvn Tôi kiểm tra nhưng không thấy như bạn báo. Nếu được gửi dùm tôi  (thao @ vinade cham vn) tài khoản hosting tài khoản site để tôi kiểm tra thực tế xem thế nào nhé.
