### ISSUE TITLE
Lỗi sau khi cài đặt xong xem log

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#808]
[Mon, 13 Apr 2015 22:28:24 +0700] [127.0.0.1] [Notice(8): Undefined index: site_home_module] [FILE: /includes/rewrite.php] [LINE: 35]
[Mon, 13 Apr 2015 22:28:24 +0700] [127.0.0.1] [User Notice(1024): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'uploads/menu' for key 'name'] [FILE: /includes/class/db.class.php] [LINE: 123]

**Comment by vuthao** [comment]
@dangdinhtu2014 Vui lòng xem lại quy định báo lỗi.
