### ISSUE TITLE
Lỗi ở Metis Menu

### ISSUE THREAD

**Issue by mathagu** [nukeviet/nukeviet#809]
Môi trường thử nghiệm:

Phiên bản NukeViet: 4.0.13
Môi trường thử Nghiệm: localhost
Trình duyệt web: Google Chrome
Hệ điều hành: Win 8.1
Máy chủ web: Open Server 5.2.2 Ultimate

Mô tả lỗi: Thiết lập một khối Menu (có thể dùng Topmenu) có một menu chính hiển thị cho mọi người, một submenu của nó chỉ hiển thị cho Quản trị. Gọi khối Menu đó hiển thị như Metis menu.

Khi chưa đăng nhập Quản trị thì ở Metis Menu vẫn nhìn thấy dấu +  (có Submenu) nhưng bấm vào không được, ở Bootstrap menu thì không có dấu hiệu nào.

Minh họa:
![image](https://cloud.githubusercontent.com/assets/11552661/7134791/737191c8-e2ca-11e4-9918-eaead81b306d.png)

**Comment by phongaz** [comment]
Bạn dùng inspect eletement ở trình duyệt xem thử xem nó có gọi file js/jquery/jquery.metisMenu.js ra không?

**Comment by mathagu** [comment]
Trước menu có
<link rel="stylesheet" type="text/css" href="/themes/default/css/jquery.metisMenu.css?t=64">
và
<script type="text/javascript" src="/js/jquery/jquery.metisMenu.js?t=64"></script>

Sau menu thì có:
<script type="text/javascript">
$(function () {
	$('#menu_26').metisMenu({
        toggle: false
    });
});
</script>

(id của menu là menu_26) Cái này là bình thường hay bất thường?

**Comment by mathagu** [comment]
Có đầy đủ file JS va CSS. Không chỉ gọi file mà còn có hàm
$(function () {
	$('#menu_26').metisMenu({
        toggle: false
    });
});

(id của menu là menu_26).

**Comment by PhamQuocTien132** [comment]
Lỗi này do PHP các bác ơi.
Lỗi này chỉ xuất hiện khi có duy nhất 1 submenu - chỉ hiển thị cho quản trị.

**Comment by PhamQuocTien132** [comment]
Lỗi này em đã sửa các bác đợi cập nhật nhé
