### ISSUE TITLE
Bị lỗi khi up lên host

### ISSUE THREAD

**Issue by hoannhv** [nukeviet/nukeviet#810]
Thông báo từ Hệ thống
Nên chú ý Nên chú ý: Array to string conversion in file /includes/core/user_functions.php on line 349
Nên chú ý Nên chú ý: Array to string conversion in file /includes/core/user_functions.php on line 351

**Comment by vuthao** [comment]
bạn copy nội dung file /data/metatags.xml gửi lên đây để mình kiểm tra xem nhé.

**Comment by vuthao** [comment]
Đã 6 ngày không thấy phản hồi từ người báo lỗi, mình xin đóng thông báo lại

**Comment by nguyenlinh1990** [comment]
Minh cung bi loi giong ban nay minh chay tren USBWebserver v8.6

![metatags xml](https://cloud.githubusercontent.com/assets/12112116/7441119/fe84b046-f103-11e4-8983-be8da69b2245.gif)

nho anh xem
