### ISSUE TITLE
Lỗi chính tả khi nhập thông tin cho site lúc cài đặt hoặc thành hoặch

### ISSUE THREAD

**Issue by johnsmeeth** [nukeviet/nukeviet#811]
Khi cài đặt đến phần nhập thông tin cho site thì có chút lỗi chính tả như hình.
![loichinhta](https://cloud.githubusercontent.com/assets/5707587/7206053/f0497488-e557-11e4-8e61-b8d3b9bc095c.png)
Và 1 lỗi nhỏ nhỏ nữa về logic (cái này cũng không biết phải lỗi nữa không) khi click chọn loại ứng dụng cần cài trong phần quản lý ứng dụng (admin) thì trong select box không thay đổi theo như hình dưới
![loi](https://cloud.githubusercontent.com/assets/5707587/7206102/5d3e8d12-e558-11e4-89a7-ff702273135b.png)

**Comment by vuthao** [comment]
Lỗi số 1 bạn nêu, chúng tôi đã sửa lại trước đó: https://github.com/nukeviet/nukeviet/commit/c48cb8928734c90e7a02ee908c9014dad4cf8ef7

Vần đề số 2: Hiện tại đang thiết kế chỗ đó luôn hiển thị hãy lựa chọn, còn việc hiển thị đúng vị trí đã được thể hiện qua tiêu đề (vị trí breadcrumb)
