### ISSUE TITLE
Góp ý: thay đổi font-size và line-height khi xem ở mobile

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#817]
Với giao diện responsive, khi xem trên thiết bị mobile và tablet thì cở chữ, khoảng cách các hàng, đặt biệt là ở related link quá gần nhau, -> khó dùng tay để chọn đúng link mình muốn.
Điều này google cũng khuyến cáo ở page speed inside

http://nukeviet.vn/vi/news/the-gioi-cong-nghe/Ngay-mai-mot-thay-doi-cua-Google-se-khien-hang-trieu-doanh-nghiep-dieu-dung-280/

**Comment by PhamQuocTien132** [comment]
@phongaz , Cái này rất hay nhưng cần thảo luận là nên đặt như nào thì hợp lý.

**Comment by trinhthinhhp** [comment]
bạn check bằng url kia là chưa chuẩn, vì url đó là đang sử bộ mã nguồn 3.x, bạn cần check trên 4.x nhé, hiện tại mình đã bổ sung font chữ tăng lên line-height trên thiết bị có màn hình 640 trở xuống

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/4585750ade034d12ed6af38c08b3585a73a7a46e
