### ISSUE TITLE
[Hỏi] Tên website

### ISSUE THREAD

**Issue by sanvu88** [nukeviet/nukeviet#819]
Không biết đây có phải là lỗi không nữa, hay là phải cài đặt gì đó, BQT xem giúp mình nhé

![sshot-1](https://cloud.githubusercontent.com/assets/12091815/7309854/a0362d58-e9d8-11e4-82d3-d8eeb731fbbf.png)

**Comment by vuthao** [comment]
@sanvu88 Vui lòng đọc lại quy định báo lỗi tại: http://forum.nukeviet.vn/viewtopic.php?f=3&t=35158
