### ISSUE TITLE
Lỗi hiển thị Comment

### ISSUE THREAD

**Issue by mathagu** [nukeviet/nukeviet#821]
Môi trường thử nghiệm:

Phiên bản NukeViet: 4.0.15
Môi trường thử Nghiệm: localhost
Trình duyệt web: Google Chrome
Hệ điều hành: Win 8.1
Máy chủ web: Open Server 5.2.2 Ultimate

Mô tả lỗi: Vào đọc một tin tức, đăng bình luận và trả lời bình luận đó bằng module Comment của NukeViet, sau đó xóa bỏ bình luận chính (cấp cao nhất): Kết quả:

- Ở trang chủ báo tin được đọc bao nhiêu lần, và số bình luận (số bình luận trước khi xóa) (Có phải có lỗi ở đây?)
![image](https://cloud.githubusercontent.com/assets/11552661/7315947/9d21a88a-ea9c-11e4-807c-e53e3a2b74fe.png)

- Đọc chi tiết tin thì không thấy có bình luận nào
![image](https://cloud.githubusercontent.com/assets/11552661/7315978/c738295a-ea9c-11e4-8c38-c28b436535c7.png)

- Trong Quản trị site, module Bình luận thì vẫn còn các bình luận này.
![image](https://cloud.githubusercontent.com/assets/11552661/7316037/7d86f8da-ea9d-11e4-8d96-402174985827.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/3c8ad6145a5717ef2af2aee2bbbe9b232dcf2c1b
