### ISSUE TITLE
Lỗi Convert module Album 3.4 -> 4.0

### ISSUE THREAD

**Issue by tuanpb1988** [nukeviet/nukeviet#822]
Sau khi dùng tool convert module c34to40 module vẫn bị lỗi trang trắng. Có ai đã sửa hoàn thiện module này qua 4.0 chưa ạ?

**Comment by anhyeuviolet** [comment]
Cái này đưa lên Git e là không hợp !

**Comment by hongoctrien** [comment]
@tuanpb1988 bạn gửi lên forum nhé.
