### ISSUE TITLE
Lỗi sau khi login admin ra thông báo notification

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#823]
Sau khi login ra trang trắng kèm 2 dấu []

**Comment by trinhthinhhp** [comment]
![untitled](https://cloud.githubusercontent.com/assets/6928431/7332432/35e7aa34-eb69-11e4-9428-faf206036719.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/642af3b1ba34b60d1bfcb0a88bb3f7d5c006b13f
