### ISSUE TITLE
báo lỗi Import CSDL từ localhost lên hosting và từ localhost lên localhost 

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#825]
Mình cài đặt thành công code nv4.x trên localhost. Sau đó Export CSDL về PC và import lên hosting thì được thông báo lỗi:
![477](https://cloud.githubusercontent.com/assets/11238423/7337295/70c7551e-ec4f-11e4-9161-8c26de4bfa32.png)
Sau đó mình thử import CSDL đó lên lại localhost cũng bị lỗi:
![0111](https://cloud.githubusercontent.com/assets/11238423/7337301/8f686f6c-ec4f-11e4-898d-3db84f8c243f.png)
Bản nv3.4 thì không lỗi. Rất mong đội code xem xét có vẫn đề gì trong sử dụng câu lệnh import không đúng

**Comment by phongaz** [comment]
Bạn chưa add quyền cho user quangtri48 vào database phapluat nên mới có lỗi này

**Comment by mathagu** [comment]
Up lên hosting thì tạo database được nữa hay không? Ở một số hosting thì tạo trước DB, sau đó chỉ import các table thôi. Bạn kiểm tra lại.

Còn lỗi bên dưới là trùng khóa, có thể do dữ liệu cụ vẫn còn mà bạn lại import vào đó một lần nữa.

**Comment by hongoctrien** [comment]
Cái này không liên quan đến NukeViet 4, mình xin đóng issue nhé.
