### ISSUE TITLE
Lỗi invalid markup validation 

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#826]
Khi kiểm tra mark up giao diện thì phát hiện lỗi này.

Thẻ UL không được phép làm con của thẻ h5.

http://validator.w3.org/check?uri=http%3A%2F%2Fwww.aneedz.net

Phiên bản: 4.0.15

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/a9ca81df496f556892c4ceebb293c4f4d2176d8b
