### ISSUE TITLE
Lỗi tìm kiếm news

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#827]
Ở chổ tìm kiếm theo ngày tháng Từ ngày, đến ngày, nếu chọn thì không sao, còn nếu người dùng copy ngày tháng vào (sai định dạng) thì báo lỗi 404 khi nhấn tìm kiếm.
VD: 12/12/2013

**Comment by phongaz** [comment]
Khi điền 12/12/2013 vào ô tìm kiếm của module seek cũng bị lỗi tương tự
![seekerror](https://cloud.githubusercontent.com/assets/6806295/7337664/2864b3fe-ec5c-11e4-9915-d80c04bda032.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/7b275c5046d48ce07a0100b33240ca6ba390e805 https://github.com/nukeviet/nukeviet/commit/ae6db751f275c460ee447a276344a1059c718257
