### ISSUE TITLE
Lỗi "Mã chống spam"

### ISSUE THREAD

**Issue by ngduong1410** [nukeviet/nukeviet#828]
không thấy hình ảnh của mã chống Spam
![image](https://cloud.githubusercontent.com/assets/12134611/7345260/a326e358-ecdb-11e4-9268-7785688a1795.png)

**Comment by mathagu** [comment]
Bạn nên báo lỗi theo quy định tại http://forum.nukeviet.vn/viewtopic.php?f=3&t=35158 để anh em đội code thuận tiện kiểm tra nhé! Vì có thể không phải do NukeViet mà do máy chủ nữa!

**Comment by ngduong1410** [comment]
- Phiên bản NukeViet: 3.0.4.2
Môi trường thử Nghiệm: hosting
- Hệ điều hành: microsoft windows 7 32 bit
- Trình duyệt web: Mozilla Firefox 30, google chrome 41
- Máy chủ web: linux
Nếu trên website cần có thêm thông tin
+ Công cụ quản lý hosting: Cpanel
+ Các thông tin khác về phần mềm webserver, PHP và cơ sở dữ liệu: Apache
2.4.10, MySQL 5.1.61, PHP 5.5

Vào 17:22 Ngày 27 tháng 04 năm 2015, mathagu <notifications@github.com> đã
viết:

**Comment by anhyeuviolet** [comment]
Bạn @mathagu  tham khảo các bài này nhé.
http://forum.nukeviet.vn/viewtopic.php?f=137&t=30006
http://forum.nukeviet.vn/viewtopic.php?f=106&t=30583
http://forum.nukeviet.vn/viewtopic.php?f=106&t=29785
