### ISSUE TITLE
Vấn đề không tương thích 

### ISSUE THREAD

**Issue by johnsmeeth** [nukeviet/nukeviet#829]
Tình hình là lừa tình ae tí. cơ mà thật, trong open beta trước thấy có bác nào góp ý. openbeta 3 vẫn thấy dòng không tương thích khi cài đặt màu xanh. ae xem fix nhé.
![nukevieterror](https://cloud.githubusercontent.com/assets/5707587/7350438/6e5ebe0e-ed29-11e4-85b8-acf5a6a65e5e.png)

**Comment by anhyeuviolet** [comment]
Bạn cho biết môi trường thử nghiệm đi.
Mình test với XAMPP 1.8.3 không có bất kỳ dòng không tương thích nào.

**Comment by johnsmeeth** [comment]
Mình chạy thử nghiệm trên debian 7 64bit. Nhưng bạn hiểu sai ý mình rồi. Ý mình là nên fix cái dòng không tương thích thành màu đỏ (như cái dòng ở trên cùng) trong cac phần không tuơng thích ở server.

**Comment by anhyeuviolet** [comment]
Ah, ra là thế. Bạn bôi đen và mô tả thế nên mình ko hiểu lắm :D

**Comment by vuthao** [comment]
cái này lúc trước mình có fix chỗ kiểm tra thư mục, quên không fix cái này.
Mình đã fix lại cái này tại: https://github.com/nukeviet/nukeviet/commit/18eeb063d6550d3ef2575f2b039830343ae177b0
