### ISSUE TITLE
Lỗi giao diện menu bootstrap default

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#830]
Cấu hình chung => Loại bỏ tên module trên url (Chọn news)
Thì ở menu bootstrap nó active luôn cả news (mặc dù đang ở voting)
![selection_242](https://cloud.githubusercontent.com/assets/6407361/7363652/3357c7a0-eda7-11e4-85ae-720c1af70aca.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/e36eab907a6066526a71b2e009ad3eab08da6331
