### ISSUE TITLE
Lỗi link bài viết khi tắt tooltip

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#831]
Khi tắt tooltip thì link bài viết thiếu thẻ title

**Comment by vuthao** [comment]
@hongoctrien lỗi cụ thẻ ở chỗ nào nhỉ.

**Comment by hongoctrien** [comment]
admin/index.php?language=vi&nv=news&op=setting
Trong đây, chổ "Hiển thị tooltips" bỏ check đi.
Ở những vị trí này (ảnh) thẻ <a> không có thuộc tính title, nên công cụ seo sẽ cảnh báo thiếu thẻ title ơ link.
![selection_249](https://cloud.githubusercontent.com/assets/6407361/7440470/549b2e2a-f0e0-11e4-8e39-72b0aba048f2.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/7bff92ad1eae64daa4c6a944bcc502290c52205b
@hongoctrien kiểm tra lại nhé.

**Comment by hongoctrien** [comment]
Ok
