### ISSUE TITLE
Module news: Lỗi cảnh báo trang tìm kiếm

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#832]
Nên chú ý Nên chú ý: Uninitialized string offset: 0 in file /modules/news/funcs/search.php on line 41
Nên chú ý Nên chú ý: Array to string conversion in file /modules/news/funcs/search.php on line 42

http://domain/news/search/
Khi tìm kiếm bài theo ngày tháng thì lỗi này.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/66530069c6797384470045a77e9e42b22868208f
