### ISSUE TITLE
Lỗi mô tả bài viết khi sử dụng ký tự đặc biệt trong nội dung

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#833]
Ví dụ một bài viết của news, phần giới thiệu ngắn gọn:
> Gần đây nhiều "phây búc kờ" cứ hay bị người ta đăng những thứ lung tung lên tường, suốt ngày cứ phải canh me đứa nào đăng mà xóa. Bài viết dưới đây giới thiệu cách để hạn chế "vấn nạn" này.

Thì khi share bài lên facebook hay G+ phần description chỉ hiển thị **Gần đây nhiều** thôi, không lấy từ dấu ngoặc kép về sau.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/dec38febcfebf769766e615cc59cb6e6d9571dde
