### ISSUE TITLE
Lỗi cảnh báo module menu

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#835]
Sửa 1 menu, ở **Các nhóm được xem** bỏ hết nhóm đi không chọn nhóm nào cả => Lưu lại vẫn được.
Khi xem danh sách menu hiện lỗi
> Nên chú ý: Undefined index: in file /modules/menu/admin/rows.php on line 343

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/1e403aa0e5f06efc501d3621d7826573184b3b03
