### ISSUE TITLE
Module users: Lỗi thể hiện họ tên

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#837]
Cấu hình module chọn phương án hiển thị là Ho - Tên.
- Nhưng khi quản trị sửa thành viên, thì cái input Tên nó nằm trước Họ.
- Tại danh sách thành viên (ở quản trị), cũng hiển thị Tên - Họ

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/85b42cb8509449f8209d901dbe25e1ed2a254bf7
