### ISSUE TITLE
Loi thong bao tu he thong

### ISSUE THREAD

**Issue by nguyenlinh1990** [nukeviet/nukeviet#838]
Loi thong bao tu he thong 
minh chay thu tren USBWebserver v8.6
 
![localhost-8080-nukeviet4015-](https://cloud.githubusercontent.com/assets/12112116/7441148/79ae6248-f105-11e4-858e-dcf81578e02c.gif)

day la anh chup file   :    data/metatags.xml

![metatags xml](https://cloud.githubusercontent.com/assets/12112116/7441158/c35e5826-f105-11e4-9a2e-40b1f6f2edc1.gif)

nho moi nguoi xem dum

**Comment by vuthao** [comment]
@nguyenlinh1990 Nếu rảnh vào chiều thì contact với mình (facebook Vu Thao) để kiểm tra trực tiếp, chứ mình test không thấy lỗi.
