### ISSUE TITLE
không thể thêm script trong bài viết ( dạng html)

### ISSUE THREAD

**Issue by tuyetson98** [nukeviet/nukeviet#839]
<div onmousemove="myMoveFunction()">
  <p id="demo">I will demonstrate onmousemove!</p>
</div>
    <span onmouseover="showtrail('/And3Ext/ImageContact/2013-07-05T10_11_42!lehaison.JPG',' L&#234; Hải Sơn – PGĐ')" onmouseout="hidetrail()"  class="head_name"> L&#234; Hải Sơn – PGĐ</span>                   
                   Ví dụ em sử dụng script onmouse trong bài viết khi em chèn dạng html thì nó sẽ bị mất ko thể thêm được

**Comment by anhyeuviolet** [comment]
Bạn thêm để code này chạy ?
Hay chỉ thêm để làm hướng dẫn viết code ?

**Comment by thehung** [comment]
Mấy thuộc tính đó bị lọc bỏ bởi bộ lọc thẻ html của NukeViet

**Comment by tuyetson98** [comment]
Mình them để code chạy
Có cách nào cho nó chạy không ạ ? 
admin có nên thêm chỗ chọn cho chức năng này chạy em thấy hay ạ

**Comment by thehung** [comment]
Cái này bạn thảo luận trên forum.nukeviet.vn nhé @tuyetson98. Đừng quên để lại link lại đây cho mọi người dễ theo dõi. 

Đây là khu vực dành cho việc báo lỗi chứ không pahir thảo luận. Mình sẽ đóng báo lỗi này lại.

**Comment by tuyetson98** [comment]
http://forum.nukeviet.vn/viewtopic.php?f=161&t=35357&p=168673#p168673
