### ISSUE TITLE
Góp ý tính năng chia tab trong bài viết

### ISSUE THREAD

**Issue by tuyetson98** [nukeviet/nukeviet#840]
Mình thấy có 1 số hệ thống khi viết bài họ có chức năng chia tab ví dụ tôi post bài về lịch làm việc
trong đó sẽ có những tab từ t2-cn

**Comment by thehung** [comment]
Bạn mở chủ đề vào thảo luận trên forum.nukeviet.vn nhé. Khu vực này dành cho báo lỗi.
