### ISSUE TITLE
Xuất hiện lỗi khi cài giao diện mới từ locahost lên hostting

### ISSUE THREAD

**Issue by webvangvn** [nukeviet/nukeviet#841]
- Phiên bản NukeViet: 4.0.15
Môi trường thử Nghiệm:  hosting
- Hệ điều hành: centos 5.11
- Trình duyệt web: coc coc
- Máy chủ web: apache
Nếu trên website cần có thêm thông tin
+ Công cụ quản lý hosting: Kloxo
+ Các thông tin khác về phần mềm webserver, PHP và cơ sở dữ liệu: Apache 2.2, Mysql 5.5, Php 5.5

Giao diện này là giao diện default đổi tên thành webvang_mnd

![loicaidatgiaodienmoi](https://cloud.githubusercontent.com/assets/8604866/7449784/2ffb7fec-f267-11e4-9ab7-4a66107b04c5.png)

Cấu hình site có khai báo thông số FTP

![cauhinhftpmnd](https://cloud.githubusercontent.com/assets/8604866/7449799/68be11c8-f267-11e4-9121-34d8b60738ad.png)

![listfileftptmp](https://cloud.githubusercontent.com/assets/8604866/7449826/ca5ebb58-f267-11e4-9958-8eec853ce0d3.png)

**Comment by thehung** [comment]
Đây không phải lỗi NukeViet.
Bạn khai báo thông số FTP sai rồi.

**Comment by webvangvn** [comment]
em khai báo đúng FTP nhé, không có sai, em xóa cache làm đi làm lại mấy lần vẫn báo lỗi đó, nếu sai ftp thì là sai chỗ nào?, lúc install nv, em nhập các thông tin ftp vào cài đặt được. 192.168.11.251 là ip nội bộ, serverja.webvang.vn là ip public ra bên ngoài.

lúc upfile zip giao diện lên tại sao ko có file config.ini trong thư mục tmp nên nó mới báo lỗi không xóa file.
