### ISSUE TITLE
Thông báo lỗi khi xóa quản trị

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#842]
Nếu không cấu hình gửi mail thì sau khi xóa nó nhảy về luôn trang thông báo.
Trang này hơi bất tiện, không cần thiết, nên hiển thị một thông báo nhỏ ngay ở trang nhập thông tin xóa.
![selection_255](https://cloud.githubusercontent.com/assets/6407361/7452500/6623efc0-f288-11e4-92a0-d01126274143.png)

**Comment by vuthao** [comment]
fixed:https://github.com/nukeviet/nukeviet/commit/a752a8402527fe01f80892603d2eb216a7eb3941
