### ISSUE TITLE
Ô tìm kiếm bị đè lên menu

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#843]
![2015-05-02 05 29 08](https://cloud.githubusercontent.com/assets/1892900/7460847/2e94f5d4-f2d0-11e4-97a7-84404bb104dd.jpeg)
Phiên bản thử nghiệm: https://github.com/nukeviet/nukeviet/commit/a9ca81d
Độ phân giải màn hình thiết bị: 720x1280px
**Môi trường thử nghiệm:**
Phần mềm server: [Bit web server v2.1.27] (https://play.google.com/store/apps/details?id=com.andi.serverweb)
Thiết bị: Lenovo P780
HĐH: Android 4.4.2
Trình duyệt: [FireFox for Android] (https://play.google.com/store/apps/details?id=org.mozilla.firefox) bản mới nhất.

**Comment by trinhthinhhp** [comment]
Em đã fix lại anh xem tại https://github.com/trinhthinhhp/nukeviet/commit/4bd3a621e17e0a4fb52b3ae27a1f4dc7bd087996
