### ISSUE TITLE
Comment bị lỗi khi hiển thị trên màn hình mobile theo chiều dọc

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#844]
Chiều ngang hiển thị bình thường:
![2015-05-02 05 31 08](https://cloud.githubusercontent.com/assets/1892900/7461114/3213b702-f2d2-11e4-8f05-95f64a1c8739.jpeg)
Chiều dọc bị lỗi:
![2015-05-02 05 31 14](https://cloud.githubusercontent.com/assets/1892900/7461115/321a4608-f2d2-11e4-8054-0ada1112b2e4.jpeg)

Phiên bản thử nghiệm: https://github.com/nukeviet/nukeviet/commit/a9ca81d
Độ phân giải màn hình thiết bị: 720x1280px
**Môi trường thử nghiệm:**
Phần mềm server: [Bit web server v2.1.27] (https://play.google.com/store/apps/details?id=com.andi.serverweb)
Thiết bị: Lenovo P780
HĐH: Android 4.4.2
Trình duyệt: [FireFox for Android] (https://play.google.com/store/apps/details?id=org.mozilla.firefox) bản mới nhất.

**Comment by trinhthinhhp** [comment]
Em đã fix, anh @thehung cập nhật xem còn lỗi không nha
