### ISSUE TITLE
Chức năng tìm kiếm không hoạt động trong điều kiện không hỗ trợ rewrite

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#845]
Máy chủ không hỗ trợ Rewrite - Chức năng tìm kiếm không hoạt động

Ảnh dưới đây là kết quả tìm kiếm với từ khóa "NukeViet". Sau khi tìm kiếm thì website trở về trang chủ (mặc dù đường link vẫn có nội dung là từ khóa tìm kiếm):
![2015-05-02 05 33 34](https://cloud.githubusercontent.com/assets/1892900/7461169/75bf0470-f2d2-11e4-8be3-ef5c5e27f277.jpeg)

Phiên bản thử nghiệm: https://github.com/nukeviet/nukeviet/commit/a9ca81d
Độ phân giải màn hình thiết bị: 720x1280px
**Môi trường thử nghiệm:**
Phần mềm server: [Bit web server v2.1.27] (https://play.google.com/store/apps/details?id=com.andi.serverweb)
Thiết bị: Lenovo P780
HĐH: Android 4.4.2
Trình duyệt: [FireFox for Android] (https://play.google.com/store/apps/details?id=org.mozilla.firefox) bản mới nhất.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/aa187cbc23dcb74cb9ab69821a5c6ee26ba37cc9

**Comment by thehung** [comment]
Tiếp tục thử nghiệm cùng điều kiện môi trường đối với code mới nhất: Từ kết quả tìm kiếm,  chuyển sang tìm kiếm theo module (hoặc click vào link "xem tất cả") thì không thấy kết quả nào.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/a0faacf287479f7fd81b9b5c279c36e7c7dcb220
