### ISSUE TITLE
Không xem được kết quả vote trên các màn hình độ phân giải thấp.

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#846]
Demo:
![2015-05-02 05 34 20](https://cloud.githubusercontent.com/assets/1892900/7461226/dba62372-f2d2-11e4-8fd3-937e1efbb4c4.jpeg)

Phiên bản thử nghiệm: https://github.com/nukeviet/nukeviet/commit/a9ca81d
Độ phân giải màn hình thiết bị: 720x1280px
**Môi trường thử nghiệm:**
Phần mềm server: [Bit web server v2.1.27] (https://play.google.com/store/apps/details?id=com.andi.serverweb)
Thiết bị: Lenovo P780
HĐH: Android 4.4.2
Trình duyệt: [FireFox for Android] (https://play.google.com/store/apps/details?id=org.mozilla.firefox) bản mới nhất.

**Comment by vuthao** [comment]
Đã sửa lại cho phiên bản hiện tại.
