### ISSUE TITLE
Lỗi module comment

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#847]
- Cấu hình bình luận phải qua kiểm duyệt
- Khi bình luận, nhấn "Gửi bình luận" xong cái nó tự load lại khung comment (không có thông báo là đang chờ duyệt hay đã đăng thành công), nên không biết chuyện gì đang xảy ra.
- Trong admin, khi có bình luân chờ duyệt, không thấy có thông báo gì => admin không biết có bình luận mới để kiểm duyệt.

**Comment by hongoctrien** [comment]
Xóa bình luận không tự load lại danh sách bình luận.

**Comment by vuthao** [comment]
@hongoctrien Xóa bình luận không tự load lại danh sách bình luận. Giao diện mặc định vẫn bình thường nhé. Khi xóa comment. Nếu xóa được chỉ remove cái div đui thôi.

**Comment by hongoctrien** [comment]
@vuthao  xác nhận không lỗi trên default.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/d43d0405dd12443e27e03e8385de27ab47c64417

**Comment by hongoctrien** [comment]
>Khi bình luận, nhấn "Gửi bình luận" xong cái nó tự load lại khung comment (không có thông báo là đang chờ duyệt hay đã đăng thành công), nên không biết chuyện gì đang xảy ra.

Fixed: https://github.com/nukeviet/nukeviet/commit/2caa8f5ebdd8e83588fe632c78a4774dd7225e0a

>Trong admin, khi có bình luân chờ duyệt, không thấy có thông báo gì => admin không biết có bình luận mới để kiểm duyệt.

Fixed: https://github.com/nukeviet/nukeviet/commit/fac19c90ad9845c1fea72c52037aab087c32dc3c
