### ISSUE TITLE
Lỗi chưa định nghĩa biến

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#852]
Undefined variable: html] [FILE: /modules/news/blocks/global.block_news_cat.php] [LINE: 19]
Undefined variable: html] [FILE: /modules/news/blocks/module.block_headline.php] [LINE: 18]

Không biết những lỗi cơ bản kiểu như này có cần phải báo đúng quy trình không nữa :(

**Comment by thehung** [comment]
Mất gì mà không báo đúng ;-)

**Comment by dangdinhtu2014** [comment]
Mất công gõ chữ, xem mình dùng phiên, hệ điều hành bản gì nói chung là tốn thời gian lằng nhằng.

**Comment by thehung** [comment]
Copi nó sẵn thành form rồi paste nó vào  1lượt là xong. Chú xem báo lỗi của
anh thì thấy.

**Comment by dangdinhtu2014** [comment]
Chú Triển cũng có thấy báo đúng quy trình đâu anh =)). Câu lệ tiểu tiết quá nhiều khi người ta ngại báo lỗi

**Comment by thehung** [comment]
Triển tự sửa lỗi nó báo nên nó chỉ cần ghi chú để nó nhớ.
Em cũng định tự sửa hả?

**Comment by trinhthinhhp** [comment]
@dangdinhtu2014  hiện tại em chạy trên máy tính em test không thấy 2 block này hiển thị lỗi, dù đã bật cả 2 cùng lúc

**Comment by dangdinhtu2014** [comment]
vậy thì có thể khẳng định chú thiếu căn bản PHP rồi nhé #trinhthinhhp

**Comment by trinhthinhhp** [comment]
@dangdinhtu2014 :v: thì anh kêu lỗi em em báo thế, chứ em chưa có coi ruột của nó :v: vì localshot của em nó đấu có hiện thông báo như cái anh kêu là 
Undefined variable: html] [FILE: /modules/news/blocks/global.block_news_cat.php] [LINE: 19]
Undefined variable: html] [FILE: /modules/news/blocks/module.block_headline.php] [LINE: 18]

**Comment by dangdinhtu2014** [comment]
Chú hãy đọc code chức đừng trông chờ vào thông báo lỗi của Nukeviet vì không phải lúc nào chú cũng kiểm soát được thông báo lỗi

**Comment by trinhthinhhp** [comment]
@dangdinhtu2014  hehe vậy thì để em check xem :dango:

**Comment by vuthao** [comment]
Yêu cầu @dangdinhtu2014  Thực hiện đúng quy định nhé. Nếu mod không gương mẫu thì những người khách sẽ không theo đâu nhé. Chúng tôi sẽ có nhân viên văn phòng (không biết code) Nếu thông báo không đúng chuẩn sẽ đóng lại. và lỗi đó có thể bỏ qua.

Fixed: https://github.com/nukeviet/nukeviet/commit/1fb2d4360ed7c72cf1ff315e82246dff322936c4
