### ISSUE TITLE
Lỗi bề rộng của Metis Menu

### ISSUE THREAD

**Issue by mathagu** [nukeviet/nukeviet#853]
Lỗi hiển thị này thực ra không phải mới và không quá khó để sửa, nhưng thấy nó vẫn còn nên báo để anh em đội code sửa lại 1 lần cho tiện (còn nếu đây là một ý đồ gì đó thì... tùy! :D).

Môi trường thử nghiệm:
Phiên bản NukeViet: 4.0.16
Môi trường thử Nghiệm: localhost
Trình duyệt web: Google Chrome
Hệ điều hành: Win 8.1
Máy chủ web: Open Server 5.2.2 Ultimate

Lỗi: Bề rộng của Metis Menu khi lấy từ một khối menu của module Menu Site lớn hơn cột chứa nó.

Hình minh họa:
![image](https://cloud.githubusercontent.com/assets/11552661/7533922/aef6aeb2-f59f-11e4-9bc5-c17299af8554.png)

Bên trên là block Global-Category, bên dưới là block Global-Metismenu

**Comment by trinhthinhhp** [comment]
Bạn đợi cập nhật nhé, hiện tại đã fix

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/f0bc6792309a80d414871dfc98d38d797ccee7b8
