### ISSUE TITLE
Trùng lặp link canonical khi active plugin rewrite_obsolute

### ISSUE THREAD

**Issue by phamdinhhau** [nukeviet/nukeviet#855]
Trước khi active
![untitled-1](https://cloud.githubusercontent.com/assets/1614842/7548566/dd8a6ebe-f638-11e4-89a9-0b970fd77406.jpg)

Sau khi active
![untitled-2](https://cloud.githubusercontent.com/assets/1614842/7548569/f35654f6-f638-11e4-9d07-24e39ee1e503.jpg)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/024d93b6167edcb63f4005f354e3bdc03f536535
