### ISSUE TITLE
Lỗi cấu hình gửi mail SMTP trong nukeviet bản v4.0.16

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#857]
Tiến hành thực hiện:
Máy chủ (SMTP) Thư Gửi: smtp.gmail.com
Cổng gửi mail: 465 
Sử dụng Xác thực: SSL
Tên Tài khoản: (tài khoản email của mình. @gmail.com)
Mật khẩu: (Mật khẩu đăng nhập gmail của mình)
Tiến hành kiểm tra:
Vào menu Thông tin - > Tiện ích mở rộng
đã có:
![011](https://cloud.githubusercontent.com/assets/11238423/7553676/4e1af64c-f730-11e4-8e05-17e86a8f1dc6.png)

Tiến hành trả lời mail phản hồi trong mục liên hệ thì hệ thống báo lỗi:
![12](https://cloud.githubusercontent.com/assets/11238423/7553682/ad346136-f730-11e4-8a04-a497cf6bb16a.png)

**Comment by PhamQuocTien132** [comment]
@hoanglongvnpt !
Mình đã kiểm tra lỗi như bạn mô tả nhưng không gặp phải lỗi, bạn có thể cung cấp thêm thông tin về môi truờng gặp lỗi ko?

**Comment by hongoctrien** [comment]
Lỗi này do sai thông tin cấu hình hoặc sever mail không cho phép sử dụng smtp, không liên quan đến NukeViet nhé.

**Comment by hoanglongvnpt** [comment]
Dùng chung một Hosting nhưng các site khác vẫn gửi Mail phản hồi được là sao ta?

**Comment by thehung** [comment]
Bạn cho biết các site đó sử dụng phiên bản nào, cấu hình gửi mail như thế
nào?

**Comment by vuthao** [comment]
Tôi đã kiểm tra vần đề này, chủ yếu là do tài khoản gmail. Bạn xem theo hướng dẫn ở đây nhé.

 To fix this issue, you need to:

1) Login to your Gmail account using the web browser

2) Click on this link to enable applications to access your account: https://accounts.google.com/b/0/DisplayUnlockCaptcha

Lưu ý: nếu bạn đang đăng nhập nhiều tài khoản mail trên trình duyệt bạn nên đăng nhập sang trình duyệt ẩn danh

3) Click on Continue button to complete the step

4) Bạn có thể chuyển sang ứng dụng của Google như Gmail để truy cập tài khoản (khuyên dùng) hoặc thay đổi cài đặt tại https://www.google.com/settings/security/lesssecureapps để tài khoản của bạn không còn được bảo vệ bởi các tiêu chuẩn bảo mật hiện đại nữa.

**Comment by webchuyennghiep247** [comment]
Mình có mày mò và cuối cùng cũng khắc phục được
các bác chưa khắc phục dc tham khảo nhé 
https://webchuyennghiep247.com/loi-smtp-khong-the-ket-noi-den-smtp-host
