### ISSUE TITLE
Lỗi chuyên mục hiển thị trang trắng ở theme modern

### ISSUE THREAD

**Issue by hainki** [nukeviet/nukeviet#859]
Với chuyên mục là chuyên mục chính, không có chuyên mục con tại theme modern khi hiển thị sẽ ra trang trắng (ver 4.0.16)!

**Comment by PhamQuocTien132** [comment]
@hainki , Mình kiểm tra theo như bạn mô tả lỗi thì không gặp lỗi, bạn cỏ thể mô tả cụ thể hơn: Lỗi trên host hay local, cấu hình xem chuyên mục trong admin như thế nào... và nếu có hình minh họa nữa thì rất tốt.

**Comment by hainki** [comment]
lỗi này mình gặp trên local.
Cách thể hiện Chuyên mục: Theo danh sách
Với theme default thì không sao. Nhưng với theme modern là bị trang trắng với chuyên mục chính không có chuyên mục con.

**Comment by hongoctrien** [comment]
Fixed https://github.com/nukeviet/nukeviet/commit/666e30303710e3272df0cf0d8baa5414e4c1977e
