### ISSUE TITLE
Giao diện khi xem chi tiết quảng cáo lỗi

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#860]
![selection_273](https://cloud.githubusercontent.com/assets/6407361/7579059/0ecf6eba-f888-11e4-97f9-dc57700ba075.png)

**Comment by PhamQuocTien132** [comment]
![canvas](https://cloud.githubusercontent.com/assets/6023707/7655095/9f247db4-fb4b-11e4-9193-66d510ec4299.png)

**Comment by hongoctrien** [comment]
Fixed https://github.com/nukeviet/nukeviet/commit/40b949a19c23fa93b8e2b9c0a326efd6acac82b4
