### ISSUE TITLE
Không dùng code marquee trong block html được

### ISSUE THREAD

**Issue by tuyetson98** [nukeviet/nukeviet#862]
marquee  behavior="scroll" direction="up">Your upward scrolling text goes here</marquee>
chèn vô html xong ra trang chủ nó mất code

**Comment by anhyeuviolet** [comment]
Cái này bạn xem trong cấu hình có cho phép tag này chưa đã.

**Comment by phongaz** [comment]
Cái này bạn vào admin/index.php?language=vi&nv=settings&op=security, nhập chữ marquee và lưu lại là được
