### ISSUE TITLE
Vấn đề domain có www và không có www

### ISSUE THREAD

**Issue by anhtrangxua5** [nukeviet/nukeviet#863]
Khi vào domain có www thì không tự chuyển đến trang không có www, hoặc ngược lại, vấn đề này ảnh hưởng đến seo.
Mình thử bản beta 4 trên host linux, cpanel

**Comment by anhyeuviolet** [comment]
Hiện vẫn đang tự fix bằng .htaccess.
Cái này mình nhớ rất lâu trước đây, khi còn Close Beta đã có người báo mà chung kết lại vẫn chưa sửa :dancer:

**Comment by phamdinhhau** [comment]
Từ bản 3.x đã vẫn thế mà :dancer:

**Comment by thehung** [comment]
Cái này có vẻ trùng với #413 đã được report.

**Comment by phongaz** [comment]
Ở issue #413 bạn @vuthao  bảo là chức năng này đã có, ở mục cấu hình chung.
Tuy nhiên Ở phần cấu hình chung- mục <b>Các domain chạy site, cách nhau bởi dấu phảy</b>: Cái này chỉ có tác dụng là cho phép các domain được dùng để chạy site thôi, nếu muốn chạy site kiểu www thì nhập vào ô này là www.domain.com hoặc không muốn kiểu non-www thì nhập là domain.com. còn muốn chạy cả hai thì nhập là www.domain.com,domain.com, hoặc thậm chí là muốn dùng domain khác để chạy chung csdl thì cũng có thể nhập là www.domain.com,domain.com,domain.net,domain.info

Tuy nhiên đây không phải là vấn đề cần giải quyết câu hỏi của bạn @anhtrangxua5 . Bạn ý muốn là có chức năng cấu hình trong admin nếu chạy site kiểu www.domain.com thì khi ta duyệt web là (non-www).domain.com thì nó tự động redirect về www.domain.com và ngược lại chứ không cần phải dùng .htaccess trên hosting để redirect. kiểu này cũng giống như đề xuất chạy https hoặc http thôi.

Hay là bạn vuthao cải tiến cái nút Kích hoạt chế độ sử dụng SSL thành chế độ <b>prefered domain type</b> với 4 options là http://www, http://non-www, https://www và https://non-www. người dùng muốn chạy kiểu gì thì chạy kiểu đó. khi cài đặt thì căn cứ vào kiểu domain nào thì sẽ tương ứng với giá trị mặc định tại mục này và <b>Các domain chạy site, cách nhau bởi dấu phảy</b>: nếu thay đổi thì cả 2 cùng theo đổi theo để tránh conflict.

Đấy là ý kiến riêng của mình, ai có ý kiến khác thì đóng góp thêm cho nó hoàn thiện và chuyên nghiệp hơn

**Comment by vuthao** [comment]
@phongaz  Tôi đã cân nhắc rất kỹ việc này để người dùng tự làm bằng việc chỉnh sửa trong file .htaccess. Tất cả các mã nguồn đều làm thế.
Nguyên nhân: Cấu hình sai cái này có thể sẽ không vào site được nữa.
