### ISSUE TITLE
Lỗi khi phần quyền quản lý Module News

### ISSUE THREAD

**Issue by mathagu** [nukeviet/nukeviet#866]
Môi trường thử nghiệm:
Phiên bản NukeViet: 4.0.16
Môi trường thử Nghiệm: localhost
Trình duyệt web: Google Chrome
Hệ điều hành: Win 8.1
Máy chủ web: Open Server 5.2.2 Ultimate

Trình tự khi gặp lỗi:
- Đăng nhập vào ACP
- Tạo một tài khoản mới (trang mới tạo, nên phải làm bước này, nếu có tài khoản khác admin thì không cũng đươc)
- Vào module Quản trị, thiết lập quyền cho tài khoản mới là Quản lý module, chọn module là Tin tức
- Vào module Tin tức, chọn Phân quyền quản lý và Sửa quyền hạn của tài khoản lúc nãy.
- Dù chọn mục nào trong ba mục "Quản lý Chuyên mục", "Quản lý module", "Toàn quyền module" khi khi Lưu thay đổi đều bị lỗi trang trắng, khi load lại trang thì vẫn thấy quyền hạn là "Quản lý module".

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/9ad682aa1068c9d02ba20c39579928debffe64c6
