### ISSUE TITLE
Tên chức năng đặt chưa thống nhất

### ISSUE THREAD

**Issue by PhamQuocTien132** [nukeviet/nukeviet#870]
![231](https://cloud.githubusercontent.com/assets/6023707/7669423/cb232b16-fc9c-11e4-9156-187c693204d8.png)

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/e1fed6a45191d685d73c5b6cd27fcb9663f480c1
