### ISSUE TITLE
Không thể xem đuợc hết danh sách tài khoản

### ISSUE THREAD

**Issue by PhamQuocTien132** [nukeviet/nukeviet#871]
Hiện tại chức năng lọc tại phần trạng thái chỉ có 2 option: hoạt động và khóa nên khi muốn xem hết danh sách thì không xem đuợc .
![123](https://cloud.githubusercontent.com/assets/6023707/7669509/9b56df8c-fca0-11e4-8076-310bedca754b.png)

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/nukeviet/commit/9abc42f51383c4d0346beb5d3850bdf206753f62
