### ISSUE TITLE
báo lỗi CSS Admin

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#872]
css trong mục đăng tin khi upload hình ảnh thì khung css không tự co giãn được

**Comment by PhamQuocTien132** [comment]
@hoanglongvnpt , A có thể mô tả cụ thể hơn không, có hình minh họa là tốt nhất.

**Comment by hongoctrien** [comment]
@hoanglongvnpt nói rõ giúp em với ạ

**Comment by vuthao** [comment]
Các lỗi thông báo không theo quy định, các bạn đóng luôn lại nhé.
