### ISSUE TITLE
Đính kèm hình ảnh trong đăng bài viết ở trang chủ

### ISSUE THREAD

**Issue by vuongnv** [nukeviet/nukeviet#874]
Nhờ mấy anh giúp em đính kèm hình ảnh vào cái bài viết dành cho thành viên bình thường với ạ

**Comment by mathagu** [comment]
Chỗ này là để báo lỗi mà! Còn nếu bạn nhờ vả thì lên Group Facebook hoặc Forum, những người dùng khác sẽ giúp bạn!

**Comment by hongoctrien** [comment]
@mathagu @vuthao cái này mình nghĩ không phải nhờ, mà là vấn đề chung của nhiều thành viên đã phản hồi.
Cụ thể là thành viên đăng bài ngoài site (news/content/) không có chổ để chọn ảnh minh họa, trong khi ảnh minh hoạ không thể thiếu trong mỗi bài viết). Nếu không gửi dc ảnh minh họa thì buộc admin phải cập nhật ảnh khi duyệt bài viết, 1 bài còn đỡ, 1 ngày gửi 100 bài admin duyêt đuối, công đâu mà đi tìm ảnh minh hoạ........

**Comment by vuthao** [comment]
Việc cho thành viên post file lên máy chủ có thể sẽ tạo thành một lỗi hổng trong site. (30 phút có thể làm hết dung lượng lưu trữ 1GB)
Nên nếu ai hay post bài cho người ta vào trong khu vực quản trị, và dùng tính năng phân quyền nhé.

**Comment by hongoctrien** [comment]
Có khả năng xử lý lại module upload (hiện đang ở trong ACP) dùng ngoài site. VD như thêm dung lượng dc phép của mỗi người dùng. (Mỗi người tầm 20mb), để họ quản lý, mỗi người dùng là 1 thư mục.
Có dc module này nhiều module cần dùng đến, khi cần làm việc với file.
Module upload (khu vực thành viên gửi file) cũng đang cho phép thành viên upload file lên.

**Comment by trinhthinhhp** [comment]
Ở phần này thì nên cấp quyền như trên wp
![untitled](https://cloud.githubusercontent.com/assets/6928431/7752806/cb174f04-000b-11e5-9751-83594a50ad92.png)
còn đối với thành viên bình thường thì nghỉ, ko cho post bài mà cũng không cho post file
