### ISSUE TITLE
Lỗi thống kê lượt xem bài viết news 

### ISSUE THREAD

**Issue by dangdinhtu2014** [nukeviet/nukeviet#878]
$time_set = $nv_Request->get_int( $module_name . '_' . $op . '_' . $id, 'session' );
$nv_Request->set_Session( $module_data . '_' . $op . '_' . $id, NV_CURRENTTIME );

sử dụng $module_name và $module_data gây lỗi cập nhật lượt xem không bị hạn chế lượt xem nếu là module ảo của news có chứa dấu -
https://github.com/nukeviet/nukeviet/blob/develop/modules/news/funcs/detail.php

**Comment by hongoctrien** [comment]
FIxed: https://github.com/hongoctrien/nukeviet/commit/d25beaa33fc0d81f72d4e39f02a0197119187823
