### ISSUE TITLE
Lỗi trang trắng giao diện Mobile_nukeviet

### ISSUE THREAD

**Issue by macsoftnet** [nukeviet/nukeviet#879]
Em chào các bác,
Em đang sử dụng phiên bản 4.0.16. HĐH Linux.
Khi để giao diện mobile trong module tin tức (tất cả module ảo của news), rồi vào giao diện mobile (module ảo của news) thì khi view site hiện được, nhưng khi vào danh mục trên menu của giao diện mobile thì bị lỗi trang trắng.

**Comment by vuthao** [comment]
Bạn test lại dùm, phiên bản mới https://github.com/nukeviet/nukeviet/archive/develop.zip máy chủ đó xem còn lỗi không. (Cần cài mới )

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/nukeviet/commit/7bd09e1d372c0390962f796eb102d20d2a7d4828
