### ISSUE TITLE
Lỗi hiển thị kết quả tìm kiếm ở mục tìm kiếm nâng cao

### ISSUE THREAD

**Issue by macsoftnet** [nukeviet/nukeviet#880]
Em sử dụng phiên bản 4.0.16.
Khi tìm kiếm nâng cao thì bị lỗi kết quả, kết quả hiện lộn xộn, lung tung, không theo thứ tự gì hết, bị dòng trên bị tràn xuống dòng dưới. 
Lỗi em đính kèm ở ảnh dưới.
![loi-search-nangcao](https://cloud.githubusercontent.com/assets/7893100/7739995/1f4d9c50-ff9d-11e4-95ab-199a6b4c9236.png)
![erro-search-ad](https://cloud.githubusercontent.com/assets/7893100/7739997/28c3340c-ff9d-11e4-9015-1472a34ddcde.png)

**Comment by vuthao** [comment]
Bạn vui lòng đọc dòng chữ: Please review the guidelines for contributing to this repository.
Trong đó có quy định, không có những thông tin này, chúng tôi rât khó kiểm tra.

**Comment by hongoctrien** [comment]
Fixed: https://github.com/htuyen1994/nukeviet/commit/9b56013fefb4224c4e6688612c35bb98f7261712
