### ISSUE TITLE
Lỗi không gửi được email cấu hình smtp?

### ISSUE THREAD

**Issue by phamngoctai0808** [nukeviet/nukeviet#886]
Mọi người cho em hỏi tại sao em đã cấu hình đầy đủ như hướng dẫn nhưng vẫn không gửi được mail, em đang sử dụng phiên bản 4.0.13 và đã cấu hình tất cả các thông tin cần thiết như hình sau:

![cauhinh](https://cloud.githubusercontent.com/assets/11608941/7743559/3b81e45c-ffc6-11e4-994f-e5c342ed468d.PNG)

![chitiet](https://cloud.githubusercontent.com/assets/11608941/7743566/475aaf0c-ffc6-11e4-800e-06fa164cd290.PNG)
 mọi người xem giúp đở em, tại em đang cần gấp thanks all!

**Comment by vuthao** [comment]
https://github.com/nukeviet/nukeviet/issues/857
