### ISSUE TITLE
Lỗi thanh trạng thái trong admin ở kích thước mobile 360

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#890]
Hiện tại là khi truy cập admin để ở kích thước 360 sẽ  mất đi "notification , icon home, icon user, language, thoát", Còn ở các màn hình khác hiển thị bình thường

**Comment by PhamQuocTien132** [comment]
@trinhthinhhp , vẫn hiển thị đó thôi. Máy e ko hiện à, thế fix luôn nhé.
![dm](https://cloud.githubusercontent.com/assets/6023707/7750237/3d2a2e4a-fffd-11e4-818b-b72dc81153c4.png)

**Comment by htuyen1994** [comment]
đã fix

**Comment by trinhthinhhp** [comment]
@htuyen1994  ok thanks nha, nhưng đẩy lên kho code viết tiếng anh đi nha, không dc viết tiếng việt :+1: 
@PhamQuocTien132  ko hiển thị em mới issue :dancers:
