### ISSUE TITLE
Lỗi cấu hình module news

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/nukeviet#891]
Trong phần Phương án thể hiện trang chủ của module news nếu chọn hiển thị theo danh sách, mới lên trên thì ngoài trang chủ không hiển thị.

**Comment by PhamQuocTien132** [comment]
Đã fix lỗi này.

**Comment by vuthao** [comment]
@PhamQuocTien132 khi đã sửa cần copy lại link commit mình đã sửa để mọi người xem sửa thế nào nhé

**Comment by vuthao** [comment]
fixed: https://github.com/PhamQuocTien132/nukeviet/commit/56a5ac8e10d79cf5984995154e551edb74a2c4ca
