### ISSUE TITLE
Lỗi giao diện comment

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#894]
> - Phiên bản NukeViet: 4.0.16
- Môi trường thử Nghiệm: Localhost
- Hệ điều hành: Fedora 21 - 64bit
- Trình duyệt web: (Chrome 40.0.2214.93 (64-bit)
- Máy chủ web: XAMPP for Linux 1.8.1

Dan sách comment có 3 trang, khi xóa comment, button phân trang không tự cập nhật lại mà xóa hết rồi vẫn còn phân trang.

**Comment by trinhthinhhp** [comment]
@hongoctrien  chụp ảnh lên coi nha, máy anh nó cứ bắt đợi để tự comment thần thánh rồi mới test dc

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/d52a825d52be8e3e971ec87235233e26353493a9
