### ISSUE TITLE
Thành viên chưa cập nhật họ tên không bình luận được

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#896]
> - Phiên bản NukeViet: 4.0.16
- Môi trường thử Nghiệm: Localhost
- Hệ điều hành: Fedora 21 - 64bit
- Trình duyệt web: (Chrome 40.0.2214.93 (64-bit)
- Máy chủ web: XAMPP for Linux 1.8.1

Thành viên không cập nhật họ tên. Khi bình luận ô nhập họ tên, email bị khóa, không nhập được => báo lỗi chưa nhập họ tên

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/b4a2c3d8282f8f8c6a249c3952658d2f5c718ade
