### ISSUE TITLE
Module comments: Đưa các thông số vào cấu hình

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#904]
> Phiên bản NukeViet: 4.0.16
Môi trường thử Nghiệm: Localhost
Hệ điều hành: Fedora 21 - 64bit
Trình duyệt web: (Chrome 40.0.2214.93 (64-bit)
Máy chủ web: XAMPP for Linux 1.8.1

Các thông số cần đưa vào cấu hình:
- Số comment hiển thị trên 1 trang (phân trang)
- Thời gian chờ giữa 2 comment (phút)

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/hoaquynhtim99/nukeviet/commit/9cfa2405b1b38ff59d725342bf92a7813373445d
