### ISSUE TITLE
Module users: Oauth facebook, Oauth google không hoạt động

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#907]
>Phiên bản NukeViet: 4.0.16
Môi trường thử Nghiệm: Hosting
Hệ điều hành: Fedora 21 - 64bit
Trình duyệt web: (Chrome 40.0.2214.93 (64-bit)
Máy chủ web: XAMPP for Linux 1.8.1

Đã tạo API và đã khai báo thông số. Click vào icon facebook/google ở trang đăng nhập nó quay về trang đăng nhập chứ không chuyển đến trang xác nhận đăng nhập từ 2 server trên.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/4c58d360344306a8bd9a1be9956c4b8b74bee2af
Xem thêm tại: http://wiki.nukeviet.vn/nukeviet4:admin:users:oauth
