### ISSUE TITLE
Module comments: Cho phép duyệt nhanh comment bằng checkbox

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#908]
Thêm checkbox trạng thái kích hoạt / không kích hoạt để thay đổi nhanh trạng thái comment.

**Comment by trinhthinhhp** [comment]
@hongoctrien  selectbox nhé, checkb bõ thì phải thêm nút save không tiện bằng selectbox ajax loading luôn

**Comment by hongoctrien** [comment]
Không anh. Checkbox vẫn dùng ajax được, chứ ko cần save.

**Comment by trinhthinhhp** [comment]
@hongoctrien  uhm thế để xem có bị nhảy múa ko :D

**Comment by hongoctrien** [comment]
Anh xem qua quản lý module menu. 
admin/index.php?language=vi&nv=menu&op=rows&mid=1
Em có thêm loại checkbox trong đó, anh tham khảo nha.

**Comment by trinhthinhhp** [comment]
@hongoctrien   đang coi trong đó rồi, đang truyền dữ liệu bị sai

**Comment by trinhthinhhp** [comment]
@hongoctrien $module_data là comment nhưng trong csdl thì nó lại là comments, cần xem lại lỗi ở đây nha, không đồng nhất

**Comment by trinhthinhhp** [comment]
Fixed https://github.com/trinhthinhhp/nukeviet/commit/1fa1bf675cd272e9e44fb52121804105482d7ef6

**Comment by hongoctrien** [comment]
@trinhthinhhp ý em là hiển thị cái checkbox để có thể bật, tắt comment ý anh. Chứ ko phải là cái icon.
Anh xem ở quản lý menu ý @@

**Comment by trinhthinhhp** [comment]
@hongoctrien chết sặc mất, xong rồi mà vẫn thấy icon

**Comment by hongoctrien** [comment]
:D. Được rồi. sr ông anh :v

**Comment by trinhthinhhp** [comment]
@hongoctrien troll anh hơi đắng à nha :dancer:
