### ISSUE TITLE
module page không sắp xếp được thứ tự

### ISSUE THREAD

**Issue by khaihuy** [nukeviet/nukeviet#912]
Nên thêm tính năng chọn sắp xếp theo thứ tự mới nhất -> cũ, cũ -> mới và sắp xếp theo thứ tự tùy chọn(hiện tại)
khi sắp xếp thì ra ngoài trang thứ tự ko thay đổi vẫn bài nào mới thì xuống dưới

**Comment by vuthao** [comment]
Module này chúng tôi lập trình hiển thị theo sắp xếp trong trang quản trị, nếu muốn thay đổi bạn nên sắp xếp lại số thứ tự này. (Do số bài viết trong module này chúng tôi dự định không nhiều).

**Comment by khaihuy** [comment]
Hiện tại mình sắp xếp lại trong phần quản trị nhưng ra ngoài ko update lại thứ tự, mình đang dùng phiên bản mới nhất

**Comment by hongoctrien** [comment]
>Hiện tại mình sắp xếp lại trong phần quản trị nhưng ra ngoài ko update lại thứ tự, mình đang dùng phiên bản mới nhất

Fixed: https://github.com/nukeviet/nukeviet/commit/1370c78bdf29b67ee5e835d82d649296e3aa53c3

**Comment by macsoftnet** [comment]
Module này nếu như lúc add menu tới từng bài viết trong page thì sẽ hay hơn.

**Comment by vuthao** [comment]
> Module này nếu như lúc add menu tới từng bài viết trong page thì sẽ hay hơn.
Tính năng này đã có rồi nhé bạn, bạn vào phần menu xem nhé

**Comment by anhtrangxua5** [comment]
Hiện tại module này chưa cho phép xóa install, nếu không dùng có thể cho phép xóa để giảm số bảng trong database.

**Comment by vuthao** [comment]
Module này là module của hệ thống nên không xóa được bạn.
- Nó được thiết kế để có thể dùng với .htaccess làm các trang như 404
- Nó cũng chỉ có 1 bảng.
