### ISSUE TITLE
Thêm module vào sitemap ping

### ISSUE THREAD

**Issue by khaihuy** [nukeviet/nukeviet#913]
hiện tại chỉ có 2 module là news và about
Ban quản trị nên thêm module page vào phần này vì khả năng seo của module này rất tốt
thanks!

**Comment by vuthao** [comment]
Chúng tôi đã cấu hình mặc định khi cài mới site với module này: https://github.com/nukeviet/nukeviet/commit/7ed3a8fa7dfc61eec1a75388ed6aedc78498d667

Với các site đang sử dụng, Truy cập vào link http://my-domain.com/index.php?language=vi&nv=modules&op=show&mod=page sau đó sửa module, để kích hoạt tính năng Kích hoạt chức năng rss:
