### ISSUE TITLE
Báo lỗi Module New khi đăng bài viết mới

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#914]
Lỗi khi tạo bài viết mới:
1- Ở phần: Nguồn tin: Khi đã có trước đó từ "Sưu tầm" nhưng đăng bài mới ở phần nguồn tin ta gõ Sưu thì đã xuất hiện Sưu tầm, nhưng click vào từ Sưu tầm cũ đã có thì biến mất, Không lấy lại được từ đã có.
2- Ở phần: Cho phép thảo luận: Mặc định là "Thành viên" Nhưng khi click chọn tất cả thì từ "Thành viên không tự mất đi mà vẫn giữ nguyên vị trí mặc định.

**Comment by thehung** [comment]
1. Nguồn tin phải là Link. Bạn cần sửa lại nguồn tin này cho đúng. Việc này
đã có nhiều người report và tôi cũng đã kiểm tra. Ko có lỗi. Nếu bạn nghĩ
thực sự có lỗi.  Vui lòng báo đầy đủ thông tin hơn (kèm ảnh chụp chẳng hạn)
2. Mình không thấy lỗi gì nhỉ?

Bạn cung cấp thông tin điều kiện thử nghiệm: môi trường,  phiên bản... Theo
đúng quy định báo lỗi.
Vào 23-05-2015 11:05, "hoanglongvnpt" <notifications@github.com> đã viết:

**Comment by vuthao** [comment]
Nếu đã là Tất cả, nó đã bao gồm thành viên, đương nhiên cái thành viên khi đó phải bỏ chọn đi chứ @hoanglongvnpt

**Comment by mathagu** [comment]
Ở vấn đề chọn thì mình thấy khá nhiều mục trong NukeViet4 đều như thế này: Khi đã chọn Thành viên, sau đó chọn Tất cả thì chỗ chọn ở Thành viên vẫn không mất. Mà chỉ khi lưu lại thì chỗ đó mới mất, chỉ còn ở chỗ Tất cả (trong tùy chọn hiển thị cho block hay menu cũng vậy). Liệu đây có phải là ý đồ gì đó không?

**Comment by thehung** [comment]
Không có ý đồ gì cả :)

**Comment by vuthao** [comment]
Đây là logic thôi, nếu đã chọn tất cả thì tất cả các cái khác sẽ bỏ đi, bởi nếu không bỏ đi thì lưu hai biến sẽ thừa.
