### ISSUE TITLE
Giao diện block module menu không chạy được trên giao diện mobile

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#920]
Ví dụ file modules/menu/menu_blocks.php
Trong này có đọan 
``` php
if( file_exists( NV_ROOTDIR . '/themes/' . $global_config['site_theme'] . '/modules/menu/' . $block_config['block_name'] . '.tpl' ) )
{
	$block_theme = $global_config['site_theme'];
}
else
{
	$block_theme = 'default';
}
```
Lúc đang ở theme mobile thì **$global_config['site_theme']** sẽ luôn kiểm tra các giá trị là tên giao diện desktop, nên các file tpl đặt trong giao diện mobile không được liên kết tới.

**Comment by vuthao** [comment]
Thay vì sử dụng $global_config['site_theme'] hãy dùng $global_config['module_theme']

**Comment by hongoctrien** [comment]
Fixed https://github.com/nukeviet/nukeviet/commit/206e40b61c1d2ea5718fb592438b1872fb5f19fd
