### ISSUE TITLE
Lỗi phần chèn bảng trong nội dung bài viết khi hiển thị trên trang

### ISSUE THREAD

**Issue by xuanluchp** [nukeviet/nukeviet#921]
- Phiên bản NukeViet: 4.0.15
Môi trường thử Nghiệm: hosting
- Hệ điều hành: (Ví dụ: Windows 8.1 64-bit)
- Trình duyệt web: (Ví dụ: Mozilla Firefox 38.0.1)
- Địa chỉ web: http://hotruong.net/Nguoi-ho-Truong-duong-dai/gap-bac-si-biet-lam-phep-la-daniel-dung-truong-996.html
Nếu trên website cần có thêm thông tin
+ Công cụ quản lý hosting: Direct Admin

Cụ thể lỗi như sau: Trong trang quản trị khi sử dụng công cụ chèn bảng để chèn thêm ô nội dung
Phần hiển thị trong trang admin:
![00](https://cloud.githubusercontent.com/assets/10148636/7787437/4d806ef4-0236-11e5-8473-343cf9ca99b0.jpg)

Tuy nhiên khi bài viết được lưu để hiển thị ngoài trang chính thì lại bị lỗi như sau, Không phân tách được khoảng cách giữa nội dung bảng và nội dung bài viết. kể cả đã đặt khoảng cách cho dường viền và nội dung.
![01](https://cloud.githubusercontent.com/assets/10148636/7787438/64eb4b36-0236-11e5-988e-c73c1c2f8854.jpg)
Đề nghị đội code xem lại lỗi này!
Cảm ơn Nukeviet!

**Comment by mathagu** [comment]
Nếu muốn, bạn nên đặt khoảng cách cho bảng với nội dung bên ngoài bằng thuộc tính margin trong CSS. Điều bạn gặp có thể là do CSS chứ không phải do NukeViet đâu!

**Comment by xuanluchp** [comment]
Đã thêm css vào nội dung bài viết khi chuyển sang code html ở phần soạn thảo, trong trang quản trị vẫn ok nhưng ra trang chính vẫn bị vậy. Nhưng cho dù là được đi chăng nữa khi mà soạn thảo bài viết để đăng lên trang mà phải làm thủ công vậy thì quả là bất tiện.
