### ISSUE TITLE
Lỗi không hiển thị tin tức khi cấu hình module thể hiện kiểu "danh sách, mới lên trên"

### ISSUE THREAD

**Issue by duylq** [nukeviet/nukeviet#927]
- Phiên bản NukeViet: 4.0.16
- Môi trường thử Nghiệm: Cloud VPS
- Hệ điều hành: Centos 6.6 64bit
- Trình duyệt web: Chrome 43 + Firefox 37
- Các thông tin khác về phần mềm webserver, PHP và cơ sở dữ liệu: Apache 2.2.15, MySQL 5.5.43, PHP 5.4.41

Khi cấu hình module Tin tức hiển thị theo kiểu "danh sách, mới lên trên" thì trang chủ không hiển thị được tin tức báo lỗi hệ thống

![error-2](https://cloud.githubusercontent.com/assets/12582911/7789178/2419339c-0282-11e5-8b36-13fd2537062d.PNG)

**Comment by vuthao** [comment]
Lỗi này chúng tôi đã sửa, và sẽ được cập nhật cho phiên bản mới.
