### ISSUE TITLE
Quản lý báo cáo lỗi trong module Download

### ISSUE THREAD

**Issue by duylq** [nukeviet/nukeviet#928]
- Phiên bản NukeViet: 4.0.16
- Môi trường thử Nghiệm: Cloud VPS
- Hệ điều hành: Centos 6.6 64bit
- Trình duyệt web: Chrome 43 + Firefox 37
- Các thông tin khác về phần mềm webserver, PHP và cơ sở dữ liệu: Apache 2.2.15, MySQL 5.5.43, PHP 5.4.41

Mục kiểm tra Báo cáo lỗi trong trang quản trị của module download nếu không có báo cáo lỗi nào thì trình duyệt sẽ tự động redirect về trang chủ như vậy không hợp lý, nên redirect về trang quản trị của module này. 

Mục File chờ kiểm duyệt cũng gặp tình trạng tương tự

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/6a213aacfa13b1a95b1d57aa056f7e98c072dbde
