### ISSUE TITLE
Thay đổi mặc định "Cấu hình tag title"

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#929]
Mặc định là **pagetitle - sitename** trong khi google khuyến cáo tag title chỉ từ 10-70 ký tự. Thêm cái đuôi **sitename** vào chiếm mất một lượng ký tự tương đối lớn.
Có nên bỏ **sitename** khỏi cấu hình mặc định, chỉ để lại **pagetitle**, người dùng muốn thêm có thể tùy biến lại.

**Comment by vuthao** [comment]
change: https://github.com/nukeviet/nukeviet/commit/9c79ca705d363b4c5fc46f6aebae051388bb52c1
