### ISSUE TITLE
Đề xuất bỏ bộ gõ mudim trong admin lẫn ngoài site

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#939]
Hiện tại bộ gõ Mudim gây quá phiền toái
- Trên mobile để máy dựng thì nó chiếm nất nút chuyển đổi giao diện mobile và desktop
- Trong quá trình soạn thảo nó có kiểu chạy nhảy về trước kể cả khi ko bật unikey

Mà bây giờ người dùng máy tính hay điện thoại họ có sẵn bộ gõ tiếng việt rồi

**Comment by hongoctrien** [comment]
>Mà bây giờ người dùng máy tính hay điện thoại họ có sẵn bộ gõ tiếng việt rồi

(y) mần luôn đi anh :D

**Comment by vuthao** [comment]
Nếu muốn bỏ: vào admin tắt nó đi có được không nhỉ, hay phải diện tận gốc. @trinhthinhhp  @hongoctrien

**Comment by trinhthinhhp** [comment]
@vuthao diệt tận gốc luôn anh ạ

**Comment by anhutbeo** [comment]
Mình cũng nghĩ là nên diệt tận gốc. đánh nó cứ nhảy lung tung.

**Comment by thehung** [comment]
Có chức năng tắt đi trong acp rồi. Không có nhu cầu thì tắt đi.

**Comment by trinhthinhhp** [comment]
@thehung sao đóng vậy anh, đang bàn mà

**Comment by thehung** [comment]
Anh trả lời trước khi đóng rồi đấy.

**Comment by hoanglongvnpt** [comment]
Trong acp đã có chức năng rồi, thì cứ như thế đi. Ai cần thì dùng, ai không cần thì tắt đi.
