### ISSUE TITLE
Góp ý quản lý block

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/nukeviet#941]
Khi bật kéo thả block, có nút Sửa - Xóa.
Nếu có thêm nút Bật / Tắt (ajax) nữa thì tiện hơn cho người quản trị.

**Comment by hoaquynhtim99** [comment]
Added https://github.com/nukeviet/nukeviet/commit/3f1d1f1e8a6da14f68c9792ed8c4c2e13049273f
