### ISSUE TITLE
Kích hoạt đa ngôn ngữ khi cài ngôn ngữ mới

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#945]
Khi thêm ngôn ngữ, nhưng chưa **KÍch hoạt đa ngôn ngữ**, hệ thống thông báo:

>Để thêm mới ngôn ngữ dữ liệu, bạn cần kích hoạt chức năng đa ngôn ngữ, để download ngôn ngữ mới truy cập website Ngôn ngữ cho NukeViet 4

Ở đây có thể thêm một tùy chọn là "Kích hoạt chức năng đa ngôn ngữ", để khỏi phải quay lại cấu hình chung kích hoạt.

**Comment by vuthao** [comment]
Khi cài đặt site đã được khuyến cáo chọn chức năng đa ngôn ngữ.

Sau khi site đã vào hoạt động nếu bật tính năng đa ngôn ngữ lên url site sẽ thay đổi toàn bộ, sẽ ảnh hưởng đến SEO rất nhiều, nên tính năng này tôi cố thiết kế để khó dùng.
