### ISSUE TITLE
Thông báo từ Hệ thống khi cấu hình tin tức Danh sách mới lên trên

### ISSUE THREAD

**Issue by vanhuonghn011291** [nukeviet/nukeviet#946]
Bị lỗi không hiển thị khi cấu hình tin tức danh sách mới lên trên, viewcat_page_new..
- Phiên bản NukeViet: 4.0.16
- Môi trường thử Nghiệm: Localhost
- Hệ điều hành: windows 7 64 bits
- Trình duyệt web: Mozilla Firefox 38.0.1, Google Crome 43.0.2357.65 m
- Máy chủ web: XAMPP for windows 1.8.3 )
- Tên gói giao diện Modern

![image](https://cloud.githubusercontent.com/assets/10495040/7795496/f559f28e-02ff-11e5-84db-0ff9d6553cb9.png)

**Comment by vuthao** [comment]
duplicate: https://github.com/nukeviet/nukeviet/issues/927
