### ISSUE TITLE
Bổ sung chức năng tắt responsive 

### ISSUE THREAD

**Issue by thehung** [nukeviet/nukeviet#947]
Cần bổ sung chức năng tắt responsive cho giao diện responsive nếu không sẽ không xem được giao diện pc trên điện thoại.

**Comment by trinhthinhhp** [comment]
Theo em thì không cần, vì bây giờ google ưu tiên cho responsive và template mobile, nó liên quan tới thứ hạng site, tự dưng vác cái tem cứng nhắc không co giãn của PC vào làm ảnh hưởng site đó trên google

**Comment by thehung** [comment]
Cái này phục vụ người dùng,  ko phải phục vụ Google.

Ngoài ra, cần hiểu rằng:

1. Desktop Responsible không được ưu tiên bằng giao diện thuần Mobile.

2. Đừng chạy theo Google, vì Google nó phục vụ người dùng. Hãy để Google
chạy theo mình.

**Comment by vuthao** [comment]
Cấu hình như thế này được ko nhỉ, Nếu có giao diện cho mobile thì tắt tính năng Responsible của giao diện thường ?

**Comment by thehung** [comment]
Không cần thiết thêm cấu hình đó, mình đỡ mất công xử lý mà người sử dụng hay người lập trình cũng tự chủ động quyết định.

Như vậy cuối site sẽ có 3 link: 
- Desktop | Responsive | Mobile

NHư vậy giao diện Desktop và Reponsive là hai chế độ của một theme, chẳng qua mình tắt hoặc bật chế độ Responsive của theme đó mà thôi.

Trước nay các CMS thường chỉ hỗ trợ hoặc Responsive, hoặc PC/Mobile. NukeViet sẽ là CMS đầu tiên chạy chế độ dual theme kiểu này. Nó sẽ giúp gia tăng trải nghiệm người dùng mà vẫn đảm bảo tuyệt đối tối ưu cho mobile.

**Comment by anhyeuviolet** [comment]
Em thấy làm như anh @vuthao  đề cập bên trên có lẽ bớt rườm rà hơn.
Ví thiệt tế mà nói, truy cập vào site bằng điện thoại, người ta thường ko click chọn giao diện Desktop nếu giao diện Mobile đã được cấu hình hợp lý.
Chỉ cần như cũ, Desk/Mobi. Trong đó, nếu Admin cấu hình đều dùng theme có khả năng Responsive thì khi đó Desk/Mobi tương ứng là kích hoạt và ko kích hoạt Responsive.

Nếu Admin muốn cấu hình giảm tải hoàn toàn trên giao diện Mobile, thì khi này có thể dùng theme Mobile, tương ứng với tuỳ chọn trên trang chủ là Desk/Mobi.
Site không nhất thiết phải có Responsive, chỉ cần khi vào, khách có đủ thông tin, vừa với màn hình của họ là được.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/cd31bdad5305f997e48e0adddd671d2674a51f93
