### ISSUE TITLE
Góp ý: Tùy chọn hiển thị danh mục ngoài trang chủ

### ISSUE THREAD

**Issue by macsoftnet** [nukeviet/nukeviet#948]
Tùy chọn hiển thị danh mục module news trong từng danh mục khi hiển thị ra ngoài trang chủ. Tránh tình trạng quá nhiều mục ngoài trang chủ, dàn trải, ko tập trung.

**Comment by phongaz** [comment]
Cái này ở 3.4.02 đã có rồi mà bạn
Vào quản lý chuyên mục: Hiện thị ở trang chủ (chọn có/không)
