### ISSUE TITLE
Lỗi undefined index : q in includes/request_url on line 143

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#949]
Lỗi undefined index : q in includes/request_url on line 143

môi trường thử nghiệm
Máy chủ: wampserver localhost
Apache/2.4.4 (Win64) PHP/5.4.12
phiên bản: 4.0.17 https://github.com/nukeviet/nukeviet/commit/6372e19f78221e8aca6254a32b8249eadb528117
![jjcapture](https://cloud.githubusercontent.com/assets/6806295/7800136/db591488-033a-11e5-84f5-286c17cc6556.PNG)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/63a47bfe4189d67166c40917533dbbd6ef0e3e9d
