### ISSUE TITLE
[Góp ý] module menu bootstrap

### ISSUE THREAD

**Issue by phongaz** [nukeviet/nukeviet#950]
Khi menu có chứa nhiều chuyên mục chính và vượt ra khung giới hạn thì những chuyên mục sau cùng không được xuống hàng mà phải ẩn đi, như thế không bị vỡ giao diện.

Ví dụ hiện tại: Menu bị đẩy xuống rất to
![menu](https://cloud.githubusercontent.com/assets/6806295/7800197/14b91182-033c-11e5-94c9-63c1e8b86eaa.PNG)

còn ở vnexpress, chuyên mục được ẩn vào một nút, người dùng có thể click vào và truy cập

![menu vn](https://cloud.githubusercontent.com/assets/6806295/7800202/30a65026-033c-11e5-8f14-a2d344c8114c.PNG)

**Comment by trinhthinhhp** [comment]
Để như vnexpress thì bạn vào quản lý module menu rồi sắp xếp lại là dc mà
