### ISSUE TITLE
LỖi sắp xếp theo fullname tại modules tài khoản

### ISSUE THREAD

**Issue by PhamQuocTien132** [nukeviet/nukeviet#951]
![s](https://cloud.githubusercontent.com/assets/6023707/7807373/45898160-03b5-11e5-93a8-f6f93009041d.png)

**Comment by PhamQuocTien132** [comment]
Đã sửa

**Comment by hongoctrien** [comment]
@PhamQuocTien132  dẫn link commit luôn nha a.

**Comment by PhamQuocTien132** [comment]
Uh, anh đang sửa nên chưa push lên , đang sửa các lỗi khác nữa push 1 thể
