### ISSUE TITLE
NV 4.0.17 lỗi menu Global bootstrap

### ISSUE THREAD

**Issue by duongGitHub** [nukeviet/nukeviet#953]
Bản 4.0.17 cài trên localhost bị lỗi menu Global bootstrap: click vô Giới thiệu, Tin tức, Thành viên, Thống kê và Liên hệ nó không chạy, nó đơ ra. Nó không cho click sửa block menu site này, click vô đơ ra không có tác dụng. Còn Menu footer vẫn hoạt động bình thường.

**Comment by macsoftnet** [comment]
Nhưng menu mà ko có menu con thì vẫn chạy bình thường, nhưng những menu con thì ko chạy được?

**Comment by hoanglongvnpt** [comment]
Bạn kiểm tra lại link của menu của code xem đúng với link cài hiện tại của bạn xem.

**Comment by duongGitHub** [comment]
Tất nhiên link đúng. Global bootstrap chỉ hoạt động cho những menu không có menu con thôi.

**Comment by duongGitHub** [comment]
global bootstrap.tpl bị lỗi ở đoạn này : 
            <li {TOP_MENU.current} rol="presentation">
                
                <img src="{TOP_MENU.icon}" />&nbsp;
                
                <a class="dropdown-toggle" {TOP_MENU.dropdown_data_toggle} href="{TOP_MENU.link}" role="button" aria-expanded="false" title="{TOP_MENU.note}" {TOP_MENU.target}>{TOP_MENU.title_trim} <strong class="caret">&nbsp;</strong></a>
                
                {SUB}
                
   </li>
   
lấy  bootstrap.tpl của 4.0.16 thì ok chạy tốt

**Comment by trinhthinhhp** [comment]
@duongGitHub @macsoftnet  menu này được làm lại theo đúng cấu trúc của bootstrap http://getbootstrap.com/javascript/#dropdowns

**Comment by duongGitHub** [comment]
Cái này cao siêu quá, chưa đủ trình độ chỉ mong các Pro fix lỗi này.

**Comment by trinhthinhhp** [comment]
mình  sẽ bổ sung thêm config block cho các bạn có 1 trong 2 lựa chọn
- Lựa chọn 2: click vào nó sẽ vào bên trong url đó
- Lựa chọn 1: nó sẽ không cho truy cập vào url mở menu có submenu

**Comment by hongoctrien** [comment]
Menu này nếu để như cũ, có submenu vẫn click được, thì có vấn đề gì không @trinhthinhhp

**Comment by trinhthinhhp** [comment]
@hongoctrien  ở dạng cũ thì click vào thì nó vào luôn mà không hiện được submenu, bỏ giải pháo trong câu hình, anh sẽ xử lý cho nó show hết luôn khi click button thành list theo phân cấp. ai có máy tính thì coi trang alowindows.com trên mobile là thấy cái menu

**Comment by mathagu** [comment]
Mình thắc mắc là trong file modules/menu/blocks/global.bootstrap.php có hai câu lệnh này, nhìn thì có tác dụng như nhau nhưng sao lại để vậy?

$item['current'] = empty( $classcurrent ) ? '' : ' class="' . ( implode( ' ', $classcurrent ) ) . '"';

$item['dropdown_data_toggle'] = empty( $classcurrent ) ? '' : ' data-toggle="' . ( implode( ' ', $classcurrent ) ) . '"';

**Comment by trinhthinhhp** [comment]
@mathagu  2 cái gần giống nhau nhưng khác nhau nhé bạn. 1  cái là tạo thành class="dropdown" còn 1 cái tạo thành data-toggle"dropdown"

**Comment by mathagu** [comment]
À... Nếu vậy thì mình hiểu rồi! Chưa mở CSDL nên khó nhận ra được tác dụng của nó! ^^

**Comment by trinhthinhhp** [comment]
Các bạn xem ở đây nhá, hiện tại mình đã  xử lý rồi, responsive chuẩn zin luôn với submenu vì bootstrap nó không cho show submenu trên mobile
https://github.com/trinhthinhhp/nukeviet/commit/b1809ba07f0b6f6a065c24fd0ba8d30b2a9f9b38

**Comment by hoanglongvnpt** [comment]
Lấy bên v4.0.16 đưa qua cho nhanh
