### ISSUE TITLE
News: Lỗi hiển thị tin tức không đúng.

### ISSUE THREAD

**Issue by PhamQuocTien132** [nukeviet/nukeviet#954]
Lỗi phát sinh khi cài block của modules News và kiểm tra tại các modules khác News. Lỗi như hình dưới mình test với block: global block news cat và block group của modules news , Cho hiển thị block tại tất cả các modules và test tại modules : /seek/ 

Mình kiểm tra layout thì thấy có padding-left = 40px mà tìm không thấy có chỗ nào trong các file CSS có cái thông số này . 

![dfd](https://cloud.githubusercontent.com/assets/6023707/7813363/874b4d2a-03e4-11e5-9490-40d83c06293e.png)

**Comment by vuthao** [comment]
Lỗi này khi bật tính năng tối ưu sitem ở các module không phải là tin tức.

**Comment by vuthao** [comment]
@PhamQuocTien132 Để nghi khi báo lỗi mô tả tiêu đề ứng với nội dung, và cung cấp các thông tin liên theo quy định để dễ hơn cho việc phán đoán lỗi.

**Comment by trinhthinhhp** [comment]
Fixed: https://github.com/trinhthinhhp/nukeviet/commit/0ea7f33d16ccc9cf607deaa8fb27fe135ba1f197
