### ISSUE TITLE
[Góp ý] Chuyên mục mặc định trong News

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#956]
Cái này mình thấy WP làm hay nên bê sang đây góp ý thôi.
Ở Wordpress, khi khởi tạo bài viết, sẽ có sẵn một chuyên mục "uncategorized" để chứa các bài chưa được xếp vào chuyên mục. 
Khi đó người dùng đăng bài có thể chọn ngay chuyên mục này để đăng bài viết đầu tiên. Ngoài ra chuyên mục này cũng có thể thay được Tên (title) chứ alias thì không, để chỉ ra các bài chưa hay không muốn phân loại. Chuyên mục mặc định này cũng không thể bị xoá.
Khi các chuyên mục bị xoá, có chứa bài viết bên trong thì có thể xem xét chuyển sang mục "Chưa phân loại này" trong trường hợp site đó chỉ có 1 chuyên mục duy nhất tạo bởi user.

Ngoài ra thì, hiện với News (Shops cũng thế ), nếu chưa có chuyên mục thì khi thêm bài viết con, người dùng bị ép chuyển sang tạo Cat. Cái này ai dùng rồi thì ko nói. Nhiều khi người mới không tiện lắm trong việc này.
Nếu giữ cơ chế Redirect, ít nhất cần có 1 dòng thông báo " Bạn cần tạo chuyên mục trước " để cho người dùng biết họ cần làm gì cũng được.

Khi thêm xong chuyên mục hay nhóm tin gì đó, mình nghĩ cũng nên có dòng thông báo cho nó lịch sự tí :D Được như phần thêm bài viết (content) của News là ổn rồi.
Bữa giờ tính sao chép cơ chế đó cho các phần khác mà chưa tìm hiểu ra nó hoạt động thế nào.

**Comment by vuthao** [comment]
mình ủng hộ ý kiến của @anhyeuviolet, sẽ sắp xếp kỹ thuật làm phần này.

**Comment by vuthao** [comment]
Hiện tại chúng tôi đã fix phần này cho news, download: https://github.com/nukeviet/nukeviet/commit/a77443b5275400d244624f3b701c1186b36cd4eb
