### ISSUE TITLE
[Góp ý] Quản lý Tags trong News

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/nukeviet#957]
Hiện Tags chưa có phần "Chọn tất cả" để xoá các tags sai hoặc ko cần thiết.
Ngoài ra thì có thể xem xét phần phân trang cho Tags trong Admin luôn. Web mình có khoảng 600 tags, mỗi lần vào là mệt mỏi luôn. 
Hy vọng có thể bổ sung nút này trong phiên bản sau.

**Comment by vuthao** [comment]
Ơ bác nào sửa lại cái này, làm nhỉ.

Lúc đầu mình thiết kế như sau:
- Khi không tìm kiếm: nố hiểu thị ra khoảng 100 cái mới nhất.
- Khi tìm kiếm 1 cái nào mới hiểu thị hết.
- Do cái tab này rất nhiều,  không ai có thể ngồi xem hết các trang làm ghì

Việc chọn xóa tất cả theo mình là ko nên. cần cái nào tìm kiếm và xóa từng cái thôi

**Comment by anhyeuviolet** [comment]
Làm như anh vuthao nói cũng hay đấy ạ. Chủ yếu em ngán cái vụ bó show hết
tags ra thì phải biết. :|
Còn cơ chế chọn nhiều để xoá thì tuỳ đội code xử lý. Em thì thấy nó tiện
nên đề xuất thôi.
Vào 28-05-2015 18:41, "Vu Thao" <notifications@github.com> đã viết:

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/a1b8b03eef53133258cc346b1a4c7c27f9a9cfd1
