### ISSUE TITLE
Lỗi không đồng nhất của module comment

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#959]
Hiện tại in kết quả $module_data thì cho kết quả là comment
nhưng trong csdl thì nó lại là nv_vi_comments
-> như vậy thì làm sao mà thực hiện dc câu lệnh khi 1 cái cho là không có "s" phía sau còn một cái là có "s"

**Comment by vuthao** [comment]
Hiện tại truy vấn CSDL của comment đang được viết cứng.

**Comment by trinhthinhhp** [comment]
như vậy cần phải bỏ viết cứng để thống nhất trong csdl nếu cái đầu tiên là tên module thì tiếp theo sẽ là _... cho cái gì đó để dùng $module_data cho tiện

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/bec1424dea2b716a4c0f36f072ece984203ee84a
