### ISSUE TITLE
Nên sử dụng chung một file favicon.ico

### ISSUE THREAD

**Issue by xuanluchp** [nukeviet/nukeviet#963]
Favicon là một ảnh nhỏ, điển hình như logo hoặc biểu tượng khác cho trang web vì vậy cho dù có sử dụng themes nào đi chăng nữa thì cũng nên sử dụng chung một file này.
Hiện tại trong themes default đã có file này, tuy nhiên khi cài đặt và sử dụng lại themes khác như mobile default hay một themes bất kỳ nào khác đều phải thêm động tác là xóa và up lại file này cho từng themes. 
Theo đề nghị của tôi, nên quản lý nó trong trình quản trị và chỉ sử dụng một tập tin duy nhất thôi, như cách blogger đã quản lý, như vậy sẽ hay hơn.

Cảm ơn đội code!

**Comment by thehung** [comment]
Favicon của NukeViet hiện do theme quyết định. 

Nếu theme không khai báo Favicon thì trình duyệt sẽ tự động lấy file favicon.ico ở thư mục gốc của site (không phải thư mục gốc của NukeViet).

Chuyển cái này sang quản lý từ Admin Control Panel cũng hay, tuy nhiên có lẽ chưa phải cái ưu tiên ngay lúc này.

**Comment by trinhthinhhp** [comment]
Nếu cho vào code thì cũng khá hay và nó nằm cùng thư mục như cấu hình logo, trường hợp người quản trị muốn thay đổi thì không phải vô hosting mà thay đổi ngay trong admin

**Comment by anhtunguyen** [comment]
Generate favicon for Web, Android, Microsoft, and iOS (iPhone and iPad) Apps. Giờ mình chỉ dùng mỗi cái cho dekstop, không đúng chuẩn của các đồng chí khác. Trong hệ thống đã có bộ nhận diện platform khá ổn nên mình hoàn toàn có thể cho phép hiển thị favicon với từng trường hợp

**Comment by vuthao** [comment]
update: https://github.com/vuthao/nukeviet/commit/747440eafb113fdad991dfb5c4715119409b6984
