### ISSUE TITLE
Không uploads được ảnh

### ISSUE THREAD

**Issue by thanhdaomc** [nukeviet/nukeviet#965]
Phần đăng tin, upload ảnh. Cửa sổ mới hiện ra, bấm chọn kiểu uploads không có tác dụng. 

Nhưng upload  trong phần Quản lý File  thì lại được bình thường.

-Trình duyệt Chrome: Phiên bản 43.0.2357.81 m
- Cấu hình máy chủ
Phiên bản NukeViet	4.0.17
Phiên bản PHP	5.3.29
Giao thức giữa máy chủ và PHP	Apache/2, cgi-fcgi
Hệ điều hành máy chủ	LINUX
Phiên bản Database	mysql 5.1.65

**Comment by vuthao** [comment]
Bạn thử đổi sang trình duyệt khác xem có được không.

**Comment by thanhdaomc** [comment]
Dùng Cococ cũng bị thế. Dùng IE 8 thì bị lỗi như này, và không ra cửa sỏ upload anh ạ
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)
Timestamp: Fri, 29 May 2015 02:05:25 UTC
Message: Object doesn't support this property or method
Line: 2
Char: 29745
Code: 0
URI: http://nhanghinguyetmy.com/js/jquery/jquery.min.js?t=2
Message: Object expected
Line: 780
Char: 1
Code: 0
URI: http://nhanghinguyetmy.com/admin/index.php?language=vi&nv=news&op=content
Message: Object doesn't support this property or method
Line: 3
Char: 325
Code: 0
URI: http://istatic.eshopcomp.com/fo/min/wp.js?subid=723_24390&hid=864425273583311873&bname=CheapMe
Message: Object doesn't support this property or method
Line: 7
Char: 335
Code: 0
URI: http://istatic.eshopcomp.com/fo/ec/wpnewbs.js?subid=723_24390&hid=864425273583311873&bname=CheapMe
Message: Object doesn't support this property or method
Line: 2
Char: 325
Code: 0
URI: http://istatic.eshopcomp.com/fo/min/wpgb.js?bname=CheapMe&subid=723_24390
Message: Object doesn't support this property or method
Line: 3
Char: 325
Code: 0
URI: http://istatic.eshopcomp.com/fo/min/wp.js?subid=718_24390&hid=864425273583311873&bname=Fun2Save
Message: Object doesn't support this property or method
Line: 7
Char: 335
Code: 0
URI: http://istatic.eshopcomp.com/fo/ec/wpnewbs.js?subid=718_24390&hid=864425273583311873&bname=Fun2Save
Message: Object doesn't support this property or method
Line: 2
Char: 325
Code: 0
URI: http://istatic.eshopcomp.com/fo/min/wpgb.js?bname=Fun2Save&subid=718_24390


Message: 'jQuery' is undefined
Line: 5
Char: 1
Code: 0
URI: http://nhanghinguyetmy.com/js/ui/jquery.ui.core.min.js?t=2


Message: HTML Parsing Error: Unable to modify the parent container element before the child element is closed (KB927917)
Line: 0
Char: 0
Code: 0
URI: http://nhanghinguyetmy.com/admin/index.php?language=vi&nv=news&op=content


Message: Object doesn't support this action
Line: 4
Char: 29137
Code: 0
URI: http://code.jquery.com/jquery-2.0.3.min.js


Message: 'groups' is null or not an object
Line: 1027
Char: 451
Code: 0
URI: http://nhanghinguyetmy.com/editors/ckeditor/ckeditor.js?t=2

**Comment by vuthao** [comment]
Bạn kiểm tra lại dùm phiên bản hiện tại còn lỗi đó không: https://github.com/nukeviet/nukeviet/archive/develop.zip
(NukeViet 4 sẽ không hỗ trợ IE 6, 7, 8)
