### ISSUE TITLE
Báo lỗi chức năng upload Document trong khi soạn thảo nội dung bài viết (New)

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#967]
Khi đăng bài viết ở phần nội dung chi tiết. Chọn icon Document trên thanh công cụ của bộ gõ để upload. Sau khi chọn file để upload và nhấn Sent it to the server thì báo lỗi: không có tệp nào được chọn.
![011](https://cloud.githubusercontent.com/assets/11238423/7874611/f4eff80a-05db-11e5-802d-3588bb08edd2.jpg)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/7099299d444ab8bdf379e2b9a41802da61aeaad8
