### ISSUE TITLE
Hướng dẫn làm export excel trong nukeviet

### ISSUE THREAD

**Issue by phamngoctai0808** [nukeviet/nukeviet#968]
em đang làm dự án cần export excel, em đang sử dụng phiên bảng nukeviet 4.0.13 em muốn làm export ra excel để xử lý em phải làm thế nào? em đang cần rất gấp mong mọi người giúp đở! thanks all

**Comment by hongoctrien** [comment]
Vấn đề này bạn post lên diễn đàn hoặc facebook nhé. Ở đây chỉ đề báo lỗi và góp ý, không thảo luận ở đây ạ.

**Comment by phamngoctai0808** [comment]
không được hả. vậy thì mình cũng xin góp ý luôn, nên cho phép xuât file excel để quản lý riêng mình nghỉ có rất nhiều người cần chức năng này! cảm ơn !
