### ISSUE TITLE
NV 4.0.17 lỗi không cho sửa menu Global bootstrap

### ISSUE THREAD

**Issue by duongGitHub** [nukeviet/nukeviet#969]
NV 4.0.17 lỗi menu Global bootstrap không sửa, xóa được block menu site khi bật kéo thả block. Mình dùng:
Phiên bản NukeViet: 4.0.17
Môi trường thử Nghiệm: Localhost
Hệ điều hành: Win 7
Trình duyệt web: Chrome
Máy chủ web: VertrigoServ 231

**Comment by vuthao** [comment]
Đúng là cái block đó khó di chuột vào để chọn các tính năng đó.

**Comment by trinhthinhhp** [comment]
Fixed https://github.com/trinhthinhhp/nukeviet/commit/7a494dc1e966a650c20ed284a048958f2e7ff55f
