### ISSUE TITLE
Lỗi cấu hình comment

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#970]
>index.php?language=vi&nv=comment&op=config&mod_name=news

Chổ **Ai được phép đăng bình luận**, đang chọn **Theo cấu hình bài viết**, chọn sang **Thành viên** thì cái **Théo cấu hình bài viết** vẫn được chọn chứ không mất đi.

**Comment by vuthao** [comment]
Khi đó module News đã thông báo ngay bên dưới: Chức năng Cho phép thảo luận hiện tại đang được quản lý tại module Quản lý bình luận
