### ISSUE TITLE
Ngôn ngữ

### ISSUE THREAD

**Issue by hoanglongvnpt** [nukeviet/nukeviet#971]
Không biết đội code cố tình hay sơ ý mà bản này không thấy có cấu hình ngôn ngữ giao diện và các chức năng khác của ngôn ngữ nhể?

**Comment by duongGitHub** [comment]
Mình thắc mắc cái này? Sao lại không có nút chọn chuyển ngôn ngữ?

**Comment by vuthao** [comment]
Hiện tại mình đã bổ sung phần quản lý ngôn ngữ giao diện tại: https://github.com/nukeviet/nukeviet/commit/dc6b42a69728d8f99d41e784158e1e597c3f995f
