### ISSUE TITLE
Module menu thiếu phần config trong admin để điều chỉnh title_length

### ISSUE THREAD

**Issue by ntanh2605** [nukeviet/nukeviet#972]
Mình thấy module menu chưa có phần cấu hình để điều chỉnh độ dài ký tự cần cắt. Trong module có file menu_config.php nhưng chưa có menu trong admin để gọi ra !

**Comment by vuthao** [comment]
Phần hiển thị menu được cấu hình qua block của module nhé bạn.

Nếu block nào không có bạn cần chỉ cụ thể nhé.
