### ISSUE TITLE
Lỗi đóng gói module thiếu file mới tạo ra

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#975]
Phiên bản NukeViet: 4.0.16
Bị lỗi đóng gói module thiếu file mới tạo ra, ví dụ như class.php trong thư mục của module.
Nukeviet 4 đóng gói module chỉ đóng gói những file mà trước đó được cài vào vì nguyên tắc của nó là lưu CSDL danh sách những file được thêm vào. Nhưng khi muốn phát triển thêm cụ thể là thêm file mới trong quá trình xây dựng module, đến khi đóng gói lại những file thêm mới này sẽ không được đóng gói. Dẫn đến module không chạy được. -> Trắng trang.
Giải pháp cho bạn là đóng gói thủ công cho an toàn.
Mọi môi trường đều bị

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/7d51fb42e669bbac2bccd5350555dede7fe344c5
