### ISSUE TITLE
Lỗi www trước domain

### ISSUE THREAD

**Issue by truongemcom** [nukeviet/nukeviet#977]
Khi gõ www ở trước tên miền thì NukeViet sẽ báo lỗi 404 thí dụ như www.vantaixuyenviet.vn sẽ bị lỗi.
Mọi môi trường đều bị

**Comment by vuthao** [comment]
bạn vào cấu hình ->  Cấu hình chung, khai báo: Các domain chạy site, cách nhau bởi dấu phảy
