### ISSUE TITLE
Trong themes default chức năng logout  thành viên bị lỗi

### ISSUE THREAD

**Issue by HoanDateh** [nukeviet/nukeviet#978]
Trong themes default khi bấm vào Thành viên/Logout thì chạy ra trang thông tin thành viên chứ không thoát khỏi trang web
![2015-06-01_9-14-22](https://cloud.githubusercontent.com/assets/8481170/7905248/67a90854-083f-11e5-9c93-a2fdb25842d5.png)

**Comment by HoanDateh** [comment]
![2015-06-01_9-14-22](https://cloud.githubusercontent.com/assets/8481170/7905271/ac4c9ef8-083f-11e5-8d2f-26704510678d.png)

**Comment by HoanDateh** [comment]
![2015-06-01_9-14-22](https://cloud.githubusercontent.com/assets/8481170/7905275/bd1b26b4-083f-11e5-97a1-2b1dbd14e0af.png)

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/5cbca9801644cb1b78e47daf8559874900dc6243
