### ISSUE TITLE
Lỗi email admin nhận bản sao thông tin tài khoản cá nhân 

### ISSUE THREAD

**Issue by motcaitenit38** [nukeviet/nukeviet#982]
![5](https://cloud.githubusercontent.com/assets/12585383/7912839/064c9e62-0895-11e5-84e5-c19f23d4eea7.png)

![6](https://cloud.githubusercontent.com/assets/12585383/7912847/15cd5af2-0895-11e5-88da-88d5c61c99c8.png)

Admin nhận thêm bản sao thông tin tài khoản

Nguyên nhân test lỗi như sau:

- cấu hình chung
![1](https://cloud.githubusercontent.com/assets/12585383/7912862/3d8ec184-0895-11e5-8088-cda171893b96.png)

- Cấu hình SMTP
![2](https://cloud.githubusercontent.com/assets/12585383/7912870/527e535c-0895-11e5-9142-f89852db476e.png)

- User đăng ký

![3](https://cloud.githubusercontent.com/assets/12585383/7912888/70d7fff6-0895-11e5-8718-1dcfaab0e74c.png)

- User nhận email thông tin

![4](https://cloud.githubusercontent.com/assets/12585383/7912909/92267962-0895-11e5-96f8-270038b6fb0e.png)

![7 p](https://cloud.githubusercontent.com/assets/12585383/7912933/cf3714f6-0895-11e5-9add-a01b0de362ee.png)

và admin cũng có nhận email

![5](https://cloud.githubusercontent.com/assets/12585383/7912934/d6bd45a6-0895-11e5-8b4a-f69a54f4437a.png)
![6](https://cloud.githubusercontent.com/assets/12585383/7912935/d6ecbd18-0895-11e5-9127-ea3892ccdfb8.png)

**Comment by vuthao** [comment]
Về nguyên tắc: Khi dùng tài khoản SMTP thì rõ ràng hệ thông sẽ lưu thông tin này.

Mình sẽ cho sử lại không gửi mật khẩu qua email nữa.

**Comment by motcaitenit38** [comment]
nếu không cho gửi mật khẩu qua mail thì thành viên muốn lấy lại mật khẩu
khi đã mất sẽ rất khó khắn.

*Lê Xuân Trường*

*Công nghệ phần mềm - Đại học Mỏ Địa Chất - Hà Nội*

*website: http://sieuquaya1.com <http://sieuquaya1.com>*
*Điện thoại: 01674.558.597*


Vào 08:52 Ngày 02 tháng 06 năm 2015, Vu Thao <notifications@github.com> đã
viết:

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/afc0895abd16d03c9dc02570732acee6ba41e923
