### ISSUE TITLE
Cài đặt thủ công không ghi lại đường dẫn file

### ISSUE THREAD

**Issue by hongoctrien** [nukeviet/nukeviet#984]
Cài đặt ở Mở rộng thì không sao, nhưng trường hợp cài đặt thủ công (copy file vào thư mục tương ứng, rồi "Thiế lập module mới" không thấy ghi đường dẫn các file vào bảng **nv4_extension_files**, không biết cái này có ảnh hưởng gì đến việc quản lý ứng dụng không?

**Comment by vuthao** [comment]
Nếu đã cài thủ công thì hệ thống sẽ không biết lối để lần.
về tính năng sẽ không bị sao, nhưng lúc xóa có thể sẽ bị sót file, hoặc xóa nhầm file nếu dùng chung file của các module.
