### ISSUE TITLE
Global block_category lỗi trên trình duyệt IE8

### ISSUE THREAD

**Issue by duongGitHub** [nukeviet/nukeviet#985]
NV 4.0.17 lỗi Global block_category lỗi trên trình duyệt IE8, nó hiện tất cả menu con, click vô dấu "+" không có tác dụng. Mình dùng:
Phiên bản NukeViet: 4.0.17
Môi trường thử Nghiệm: Localhost
Hệ điều hành: Win 7
Trình duyệt web: IE8
Máy chủ web: VertrigoServ 231

**Comment by anhyeuviolet** [comment]
IE 8-9 thì khai tử rồi, ko biết có nên giữ code cho 2 trình duyệt này nữa không nhỉ ...

**Comment by trinhthinhhp** [comment]
IE 8 khai tử rồi nhé bác, bác dùng bản cao hơn hoặc dùng sang firefox chrome coccoc safari opera mới nhất ý, không nên code cho 2 thằng này vì chuẩn bây giờ các may tính cũ đời cổ đang dần dần đi vào sọt rác và người dùng đang chuyển qua các máy tính có cấu hình mạnh đồng nghĩa với việc cài hệ điều hành mới chứ ko dùng bản cũ, các bản thấp dưới win 7 đều do thằng cài nó cài vì nó lười nó bung ghost luôn cho nhanh, ra tiện net nhiều chỗ máy tính câu hình chip i5 ram cũng dc mà nó toàn đi cài xp

**Comment by vuthao** [comment]
Chúng tôi đã sử dụng jQuery 2.x 
jQuery 2.x does not support Internet Explorer 6, 7, or 8
