### ISSUE TITLE
Cần hiển thị thông báo hoặc để trống ngoài site khi module news chưa có chủ đề và nội dung

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#987]
Nếu module news chưa có cateogry và nội dung thì cần phải hiện form thông báo ở ngoài site là website chưa có nội dung hoặc để trống thay vì như sau
![untitled](https://cloud.githubusercontent.com/assets/6928431/7930169/442096da-0930-11e5-88dc-9fc108d3b836.png)

**Comment by mathagu** [comment]
Chắc là khi làm web thì ít ai lại đưa trang web lên mà không có nội dung gì trước. Nên anh em đội code chưa lường trước tình huống này chăng. Chứ vấn đề này có từ lâu rồi mà!

**Comment by vuthao** [comment]
https://github.com/nukeviet/nukeviet/commit/0145318fbfe982cba7ae61c13559811143099bc9
