### ISSUE TITLE
Góp ý bổ xung tính năng xem trước bài viết ở ngoài site

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#990]
Tính năng này cho phép người viết xem trước nội dung bô cục màu sắc ngoài site và có thể check seo onpage cho bài viết đó thay vì lưu rồi mới được xem bài viết ngoài site

**Comment by vuthao** [comment]
hãy lưu ở chế độ bài viết ở chế độ lưu tạm, nhé. Nó cón liên quan đến rất nhiều thứ ngoài nội dung
