### ISSUE TITLE
Lỗi trang trắng

### ISSUE THREAD

**Issue by nhimthulinh** [nukeviet/nukeviet#991]
Khi cài module shops vào, nếu shops bị lỗi trang trắng, thì khi click lại trang chủ của admin sẽ bị trang trắng theo.
Lỗi xuất phát từ shops/siteinfo.php
// Tong so binh luan duoc dang
$number = $db->query( 'SELECT COUNT(*) FROM ' . NV_PREFIXLANG . '_comments WHERE module=' . $db->quote( $module_name ) . ' AND status = 1' )->fetchColumn();
if( $number > 0 )
{
	$siteinfo[] = array( 'key' => $lang_siteinfo['siteinfo_comment'], 'value' => $number );
}

// So binh luan cho duyet
$number = $db->query( 'SELECT COUNT(*) FROM ' . NV_PREFIXLANG . '_comments WHERE module=' . $db->quote( $module_name ) . ' AND status = 0' )->fetchColumn();
if( $number > 0 )
{
	$pendinginfo[] = array( 'key' => $lang_siteinfo['siteinfo_comment_pending'], 'value' => $number );
}die( 'Stop!!!' );

**Comment by vuthao** [comment]
Nếu bạn lấy nhánh develop là nhành chưa ổn định, chúng tôi đang sửa các nhánh đó.
Bạn chỉ nên dùng các phiên bản đã thông báo phát hành, hoặc cập nhật bản mới nhất của cả nukeviet và shops mới đồng bộ.
