### ISSUE TITLE
Hiển thị "Chưa có thông báo" hoài

### ISSUE THREAD

**Issue by duongGitHub** [nukeviet/nukeviet#992]
Trong Admin khi ta vô tình hay cố ý rê chuột vô tài khoản quản trị (gốc trên bên phải màn hình) nó hiện ra thông "Chưa có thông báo" và dính luôn thậm chi rê chuột chỗ khác vẫn còn, cảm giác rất khó chịu, làm che khuất các nút chức năng của các modlue khác . Đúng ra là rê chuột vào thì hiện ra thông báo, rê chuột chỗ thì biến mất chứ.

**Comment by trinhthinhhp** [comment]
Chỗ này chưa linh hoạt thiệt, thấy hover mãi mới hiện có lúc hover từ nó quay sang nút thoát thì nó vẫn hiện

**Comment by trinhthinhhp** [comment]
https://github.com/trinhthinhhp/nukeviet/commit/6fd9817680fdd571472a32cd042d7c69670ea366

**Comment by vuthao** [comment]
@trinhthinhhp Em sửa mất luôn cái hover menu trong admin rồi nhé.

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/4e32346d7ca81869efeaff05a96a82b5def213dc
