### ISSUE TITLE
Thiếu module cài đặt đóng gói module

### ISSUE THREAD

**Issue by thinit** [nukeviet/nukeviet#993]
Giúp tôi cài đặt module shop 4.0.14 lên nukeviet 4.0.17 với!

**Comment by nhimthulinh** [comment]
bạn giải nén ra rồi cài đặt thru công, hoặc  click qua mở rộng để cài đặt tự động

**Comment by thinit** [comment]
Mình chưa biết cài thủ công bạn ơi! bạn cho mình xin hướng dẫn cài với nhé. Cảm ơn bạn.
Mình đã vào phần cài đặt tự động, tìm đến module Shop thì báo "Không tương thích" vậy là do mình cài sai hay phiên bản Nukeviet 4.0.17 không tương thích với cài module Shop nhỉ? Các Chuyên gia giúp mình với nhé. Thanks..
