### ISSUE TITLE
Lỗi trình soạn thảo Editor và hiển thị ngoài site nội dung bài viết

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/nukeviet#994]
Trong admin khi soạn thảo văn bản trên editor như sau
![1](https://cloud.githubusercontent.com/assets/6928431/7956322/5cb58910-0a09-11e5-9721-1865d9ff9e62.png)
Ngoài site hiển thị như hình sau không đúng với trong admin
![2](https://cloud.githubusercontent.com/assets/6928431/7956330/66e9e03e-0a09-11e5-8497-65d54fb8ec50.png)
Tiếp theo khi soạn thảo để ở dạng mục theo tứ tự 1 2 3 4 như sau
![3](https://cloud.githubusercontent.com/assets/6928431/7956379/ae42982c-0a09-11e5-97c1-043d040c3a8b.png)
và quay lại sửa bài viết đó thấy tự động chuyển sang dấu chấm và dính luôn cả phần bên dưới
![4](https://cloud.githubusercontent.com/assets/6928431/7956392/c43fd6ee-0a09-11e5-9429-20fb9d86a942.png)
còn ngoài site lúc này hiển thị dạng dấu chấm thay vì đánh số 1 2 3
![5](https://cloud.githubusercontent.com/assets/6928431/7956408/dd88cf2a-0a09-11e5-8915-bcfa47d6ff80.png)

**Comment by thehung** [comment]
Việc này có thể xếp hạng là bug về CSS. Trên facebook hình như đã có kiến nghị, cái này cũng có liên quan: https://github.com/nukeviet/nukeviet/issues/921

**Comment by vuthao** [comment]
fixed: https://github.com/nukeviet/nukeviet/commit/074ef48a5de3ed800ce15412a33f8614d09292f9
Các site đang chạy cần vào phần: 
Cấu hình -> Thiết lập an ninh , thêm tag "ol" vào phần Mã HTML được chấp nhận sử dụng trong hệ thống
