### ISSUE TITLE
NV 4.0.17 không thấy nút chuyển giao diện tiếng Anh và tiếng Việt.

### ISSUE THREAD

**Issue by duongGitHub** [nukeviet/nukeviet#995]
NV 4.0.17 không thấy nút chuyển giao diện tiếng Anh và tiếng Việt. Mình dùng:
Phiên bản NukeViet: 4.0.17
Môi trường thử Nghiệm: Localhost
Hệ điều hành: Win 7
Trình duyệt web: Chrome
Máy chủ web: VertrigoServ 231

**Comment by mathagu** [comment]
Ơ... Sao tiêu đề và nội dung bên trong issue chẳng liên quan gì nhau vậy? Một cái là "không cho thêm block ở vị trí Menu site", còn một cái là "không thấy nút chuyển giao diện tiếng Anh và tiếng Việt"! Ý bạn muốn nói là gì thế ạ?

**Comment by trinhthinhhp** [comment]
Nút chuyển đổi ngôn ngữ đã được tách ra thành block và được bổ sung : https://github.com/trinhthinhhp/nukeviet/commit/206a76ee2d54fc391517970f992b43a0160b0b6a
